name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/first-interaction@v1
        # fix run error: https://github.com/actions/first-interaction/issues/101#issuecomment-1262487501
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello ${{ github.actor }}, Thank you for your first issue contribution 🎉 "
          pr-message: "Hello ${{ github.actor }}, Thank you for your first PR contribution 🎉 ${{ github.actor }}"
