name: Test Action

on: [pull_request_target, issues]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Thank you for your contribution! ${{ github.actor }}"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
