export enum TorrentCategories {
  Movies = 2000,
  Movies_Foreign = 2010,
  Movies_Other = 2020,
  Movies_HD = 2040,
  Movies_UHD = 2045,
  Movies_3D = 2060,
  Movies_DVD = 2070,
  TV = 5000,
  TV_Foreign = 5020,
  TV_SD = 5030,
  TV_HD = 5040,
  TV_UHD = 5045,
  TV_Other = 5050,
  TV_Sport = 5060,
  TV_Anime = 5070,
  TV_Documentary = 5080,
}

export const MOVIE_CATEGORIES = [
  TorrentCategories.Movies,
  TorrentCategories.Movies_Foreign,
  TorrentCategories.Movies_Other,
  TorrentCategories.Movies_HD,
  TorrentCategories.Movies_UHD,
  TorrentCategories.Movies_3D,
  TorrentCategories.Movies_DVD,
  TorrentCategories.TV,
  TorrentCategories.TV_Foreign,
  TorrentCategories.TV_SD,
  TorrentCategories.TV_HD,
  TorrentCategories.TV_UHD,
  TorrentCategories.TV_Other,
  TorrentCategories.TV_Sport,
  TorrentCategories.TV_Anime,
  TorrentCategories.TV_Documentary,
];
