export const QUERY_TYPE = {
  CQL: "CQL",
  JQL: "JQL",
} as const;

// Minimum length for a valid query clause: `<field> <operator> <value>`
// Based on shortest possible: "id = 1" (6 characters)
export const MIN_CLAUSE_LENGTH = 6;

export const CQL_OPERATORS = ["=", "!=", ">", ">=", "<", "<=", "in", "not in", "~", "!~"];

export const JQL_OPERATORS = [
  "=",
  "!=",
  ">",
  ">=",
  "<",
  "<=",
  "in",
  "not in",
  "~",
  "!~",
  "is",
  "is not",
  "was",
  "was in",
  "was not in",
  "was not",
  "changed",
];

export const JQL_KEYWORDS = ["AND", "OR", "NOT", "EMPTY", "NULL", "ORDER BY"];
export const CQL_KEYWORDS = ["AND", "OR", "NOT", "ORDER BY"];

export const CQL_FIELDS = [
  "ancestor",
  "container",
  "content",
  "created",
  "creator",
  "contributor",
  "favourite",
  "favorite",
  "id",
  "label",
  "lastmodified",
  "macro",
  "mention",
  "parent",
  "space",
  "space.category",
  "space.key",
  "space.title",
  "space.type",
  "text",
  "title",
  "type",
  "watcher",
];

export const CQL_FUNCTIONS = [
  "currentUser",
  "endOfDay",
  "endOfMonth",
  "endOfWeek",
  "endOfYear",
  "startOfDay",
  "startOfMonth",
  "startOfWeek",
  "startOfYear",
  "favouriteSpaces",
  "recentlyViewedContent",
  "recentlyViewedSpaces",
];

export const JQL_FIELDS = [
  "affectedVersion",
  "approvals",
  "assignee",
  "attachments",
  "category",
  "comment",
  "component",
  "created",
  "createdDate",
  "creator",
  "Customer Request Type",
  "description",
  "due",
  "dueDate",
  "environment",
  "epic link",
  "filter",
  "request",
  "savedFilter",
  "searchRequest",
  "fixVersion",
  "issueKey",
  "id",
  "issue",
  "key",
  "labels",
  "lastViewed",
  "level",
  "originalEstimate",
  "timeOriginalEstimate",
  "parent",
  "priority",
  "project",
  "remainingEstimate",
  "timeEstimate",
  "reporter",
  "request-channel-type",
  "request-last-activity-time",
  "resolution",
  "resolved",
  "resolutionDate",
  "sla",
  "sprint",
  "status",
  "summary",
  "text",
  "timeSpent",
  "type",
  "issueType",
  "updated",
  "updatedDate",
  "voter",
  "votes",
  "watcher",
  "watchers",
  "workLogAuthor",
  "workLogComment",
  "workLogDate",
  "workRatio",
];

export const JQL_FUNCTIONS = [
  "approved",
  "approver",
  "breached",
  "cascadeOption",
  "closedSprints",
  "completed",
  "componentsLeadByUser",
  "currentLogin",
  "currentUser",
  "earliestUnreleasedVersion",
  "elapsed",
  "endOfDay",
  "endOfMonth",
  "endOfWeek",
  "endOfYear",
  "everbreached",
  "issueHistory",
  "issuesWithRemoteLinksByGlobalId",
  "lastLogin",
  "latestReleasedVersion",
  "linkedIssues",
  "membersOf",
  "myApproval",
  "myPending",
  "now",
  "openSprints",
  "paused",
  "pending",
  "pendingBy",
  "projectsLeadByUser",
  "projectsWhereUserHasPermission",
  "projectsWhereUserHasRole",
  "releasedVersions",
  "remaining",
  "running",
  "standardIssueTypes",
  "startOfDay",
  "startOfMonth",
  "startOfWeek",
  "startOfYear",
  "subtaskIssueTypes",
  "unreleasedVersions",
  "votedIssues",
  "watchedIssues",
  "withinCalendarHours",
];
