import dayjs from "dayjs";
import { Icon } from "@raycast/api";

import { COMMAND_NAME, PAGINATION_SIZE } from "@/constants";

import type { SearchFilterItem, SearchFilterCommandName } from "@/types";

const SEVEN_DAY_AGO = dayjs().subtract(7, "day").format("YYYY-MM-DD");

export const CONFLUENCE_SEARCH_CONTENT_FILTERS: SearchFilterItem[] = [
  {
    value: "default",
    title: "All Contents",
    icon: Icon.MagnifyingGlass,
    query: "",
  },
  {
    value: "full_text_search",
    title: "Full Text Search",
    icon: Icon.Text,
    query: "",
    logicOperator: "AND",
    transform: (processedQuery: string) => processedQuery.replace(/title ~ "/g, 'text ~ "'),
  },
  {
    value: "viewed_recently",
    title: "Viewed Recently",
    icon: Icon.Eye,
    query: `id in recentlyViewedContent(${PAGINATION_SIZE}, 0)`,
    autoQuery: true,
    logicOperator: "AND",
    sectionTitle: ({ fetchedCount, totalCount }) => `Viewed Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "updated_recently",
    title: "Updated Recently",
    icon: Icon.Clock,
    query: `(type in (page, blogpost, comment)) AND (created >= "${SEVEN_DAY_AGO}" OR lastmodified >= "${SEVEN_DAY_AGO}")`,
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "lastmodified DESC, created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Updated Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "created_by_me",
    title: "Created by Me",
    icon: Icon.Person,
    query: "creator = currentUser()",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Created by Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "contributed_by_me",
    title: "Contributed by Me",
    icon: Icon.Pencil,
    query: "contributor = currentUser()",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "lastModified DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Contributed by Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "mention_me",
    title: "Mention Me",
    icon: Icon.AtSymbol,
    query: "mention = currentUser()",
    autoQuery: true,
    logicOperator: "AND",
    sectionTitle: ({ fetchedCount, totalCount }) => `Mention Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "my_favourites",
    title: "My Favourites",
    icon: Icon.Star,
    query: "favourite = currentUser()",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "favourite DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `My Favourites (${fetchedCount}/${totalCount})`,
  },
  {
    value: "watched_by_me",
    title: "Watched by Me",
    icon: Icon.Eye,
    query: "watcher = currentUser()",
    autoQuery: true,
    logicOperator: "AND",
    sectionTitle: ({ fetchedCount, totalCount }) => `Watched by Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "content_type_page",
    title: "Pages",
    icon: Icon.Receipt,
    query: "type = page",
    logicOperator: "AND",
  },
  {
    value: "content_type_blogpost",
    title: "Blog Posts",
    icon: Icon.QuotationMarks,
    query: "type = blogpost",
    logicOperator: "AND",
  },
  {
    value: "content_type_comment",
    title: "Comments",
    icon: Icon.Bubble,
    query: "type = comment",
    logicOperator: "AND",
    transform: (processedQuery: string) => processedQuery.replace(/title ~ "/g, 'text ~ "'),
  },
  {
    value: "content_type_attachment",
    title: "Attachments",
    icon: Icon.Paperclip,
    query: "type = attachment",
    logicOperator: "AND",
    transform: (processedQuery: string) => processedQuery.replace(/title ~ "/g, 'text ~ "'),
  },
];

export const CONFLUENCE_SEARCH_SPACE_FILTERS: SearchFilterItem[] = [
  {
    value: "default",
    title: "All Spaces",
    icon: Icon.MagnifyingGlass,
    query: "",
  },
  {
    value: "favourite_spaces",
    title: "Favourite Spaces",
    icon: Icon.Star,
    query: "type = space AND space.type = favourite",
    autoQuery: true,
    logicOperator: "AND",
  },
  {
    value: "personal_spaces",
    title: "Personal Spaces",
    icon: Icon.Person,
    query: "type = space AND space.type = personal",
    logicOperator: "AND",
  },
  {
    value: "global_spaces",
    title: "Global Spaces",
    icon: Icon.Globe,
    query: "type = space AND space.type = global",
    logicOperator: "AND",
  },
];

export const JIRA_SEARCH_ISSUE_FILTERS: SearchFilterItem[] = [
  {
    value: "default",
    title: "All Issues",
    icon: Icon.MagnifyingGlass,
    query: "",
  },
  {
    value: "full_text_search",
    title: "Full Text Search",
    icon: Icon.Text,
    query: "",
    logicOperator: "AND",
    transform: (processedQuery: string) => processedQuery.replace(/summary ~ "/g, 'text ~ "'),
  },
  {
    value: "open_issues",
    title: "Open Issues",
    icon: Icon.Circle,
    query: "resolution = Unresolved",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "updated DESC, priority DESC, created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Open Issues (${fetchedCount}/${totalCount})`,
  },
  {
    value: "my_open_issues",
    title: "My Open Issues",
    icon: Icon.Circle,
    query: "assignee = currentUser() AND resolution = Unresolved",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "priority DESC, updated DESC, created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `My Open Issues (${fetchedCount}/${totalCount})`,
  },
  // {
  //   value: "done_issues",
  //   title: "Done Issues",
  //   icon: Icon.CheckCircle,
  //   query: "statusCategory = Done",
  //   autoQuery: true,
  //   logicOperator: "AND",
  //   orderBy: "priority DESC, updated DESC, created DESC",
  //   sectionTitle: ({ fetchedCount, totalCount }) => `Open Issues (${fetchedCount}/${totalCount})`,
  // },
  {
    value: "assigned_to_me",
    title: "Assigned to Me",
    icon: Icon.Person,
    query: "assignee = currentUser()",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Assigned to Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "reported_by_me",
    title: "Reported by Me",
    icon: Icon.Person,
    query: "reporter = currentUser()",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Reported by Me (${fetchedCount}/${totalCount})`,
  },
  {
    value: "created_recently",
    title: "Created Recently",
    icon: Icon.Clock,
    query: "created >= -1w",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "created DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Created Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "updated_recently",
    title: "Updated Recently",
    icon: Icon.Clock,
    query: "updated >= -1w",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "updated DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Updated Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "resolved_recently",
    title: "Resolved Recently",
    icon: Icon.CheckCircle,
    query: "resolutiondate >= -1w",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "updated DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Resolved Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "viewed_recently",
    title: "Viewed Recently",
    icon: Icon.Eye,
    query: "issuekey in issueHistory()",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "lastViewed DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Viewed Recently (${fetchedCount}/${totalCount})`,
  },
  {
    value: "watched_by_me",
    title: "Watched by Me",
    icon: Icon.Eye,
    query: "watcher = currentUser()",
    autoQuery: true,
    logicOperator: "AND",
    orderBy: "updated DESC",
    sectionTitle: ({ fetchedCount, totalCount }) => `Watched by Me (${fetchedCount}/${totalCount})`,
  },
];

export const SEARCH_FILTER_CONFIGS = {
  [COMMAND_NAME.CONFLUENCE_SEARCH_CONTENT]: CONFLUENCE_SEARCH_CONTENT_FILTERS,
  [COMMAND_NAME.CONFLUENCE_SEARCH_SPACE]: CONFLUENCE_SEARCH_SPACE_FILTERS,
  [COMMAND_NAME.JIRA_SEARCH_ISSUE]: JIRA_SEARCH_ISSUE_FILTERS,
} as const satisfies Record<SearchFilterCommandName, SearchFilterItem[]>;
