import {
  Detail,
  ActionPanel,
  Action,
  Icon,
  AI,
  environment,
  showToast,
  Toast,
} from "@raycast/api";
import { useState, useEffect } from "react";

interface AIExplanationProps {
  prompt: string;
  title: string;
}

function getErrorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === "string") return err;
  return "Unknown error";
}

export function AIExplanation({ prompt, title }: AIExplanationProps) {
  const [data, setData] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchAI() {
      if (!environment.canAccess(AI)) {
        setError(
          "Raycast AI is not available. You may need Raycast Pro, or AI may not be supported on your platform yet.",
        );
        setIsLoading(false);
        return;
      }

      try {
        const answer = await AI.ask(prompt);
        setData(answer);
      } catch (err: unknown) {
        console.error("AI Error:", err);
        const msg = getErrorMessage(err);
        if (
          msg.includes("Model is not supported") ||
          msg.includes("Worker unloaded")
        ) {
          setError(
            "**Raycast AI is not yet supported on Windows.**\n\n" +
              "The AI API requires Raycast for macOS with a Pro subscription.\n\n" +
              "As a workaround, you can use an external AI service. Check extension preferences for options.",
          );
        } else {
          setError(`Failed to load AI response: ${msg}`);
        }
        showToast({
          style: Toast.Style.Failure,
          title: "AI Not Available",
          message: "Raycast AI may not be supported on this platform.",
        });
      } finally {
        setIsLoading(false);
      }
    }

    fetchAI();
  }, [prompt]);

  return (
    <Detail
      isLoading={isLoading}
      markdown={error || data || "Generating AI response..."}
      metadata={
        !error ? (
          <Detail.Metadata>
            <Detail.Metadata.Label
              title="Response generated by"
              text="Raycast AI"
              icon={Icon.Stars}
            />
          </Detail.Metadata>
        ) : undefined
      }
      navigationTitle={title}
      actions={
        <ActionPanel>
          {data && !error && (
            <Action.CopyToClipboard title="Copy AI Response" content={data} />
          )}
        </ActionPanel>
      }
    />
  );
}
