import { defineConfig } from "eslint/config";
import raycastConfig from "@raycast/eslint-config";

export default defineConfig([
  // Generated by `npm run generate` from the live GitHub schema — never hand-edited, and large
  // enough that linting it is pure noise.
  { ignores: ["src/generated/**", "**/*.graphql"] },
  ...raycastConfig,
]);
