import { defineConfig } from "eslint/config";
import raycastConfig from "@raycast/eslint-config";

export default defineConfig([
  // Generated by `npm run generate` from the live GitHub schema — never hand-edited, and large
  // enough that linting it is pure noise.
  // `raycast-env.d.ts` is also generated from package.json by Raycast tooling and can contain
  // rule directives/types that drift from the installed lint stack.
  { ignores: ["src/generated/**", "**/*.graphql", "raycast-env.d.ts"] },
  ...raycastConfig,
]);
