import type { PaperEntity } from "./types";

/**
 * Offline sample library used when Paperlib is not running (CI, first launch, demos).
 * Metadata matches well-known papers so copy DOI / citation / BibTeX stay realistic.
 */
export const DEMO_PAPERS: PaperEntity[] = [
  {
    id: "vaswani2017attention",
    title: "Attention Is All You Need",
    authors:
      "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Lukasz Kaiser, Illia Polosukhin",
    abstract:
      "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The Transformer architecture relies entirely on attention mechanisms, dispensing with recurrence and convolutions.",
    note: "",
    publication: "Advances in Neural Information Processing Systems",
    pubTime: "2017",
    pubType: 1,
    doi: "10.48550/arXiv.1706.03762",
    arxiv: "1706.03762",
    mainURL: "",
    publisher: "Curran Associates, Inc.",
    pages: "5998-6008",
    volume: "30",
    number: "",
    rating: 5,
    flag: true,
    tags: [{ name: "transformers" }, { name: "nlp" }],
    folders: [{ name: "Foundations" }],
  },
  {
    id: "devlin2019bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
    authors: "Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova",
    abstract:
      "BERT pre-trains deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers. Fine-tuning with one additional output layer produces state-of-the-art models for a wide range of NLP tasks.",
    note: "",
    publication: "Proceedings of NAACL-HLT",
    pubTime: "2019",
    pubType: 1,
    doi: "10.18653/v1/N19-1423",
    arxiv: "1810.04805",
    mainURL: "",
    publisher: "Association for Computational Linguistics",
    pages: "4171-4186",
    volume: "",
    number: "",
    rating: 5,
    flag: false,
    tags: [{ name: "nlp" }, { name: "pretraining" }],
    folders: [{ name: "Foundations" }],
  },
  {
    id: "he2016resnet",
    title: "Deep Residual Learning for Image Recognition",
    authors: "Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun",
    abstract:
      "Deeper neural networks are more difficult to train. Residual learning reformulates layers as residual functions with reference to layer inputs, making it easier to optimize very deep networks and improving ImageNet accuracy.",
    note: "",
    publication: "IEEE Conference on Computer Vision and Pattern Recognition",
    pubTime: "2016",
    pubType: 1,
    doi: "10.1109/CVPR.2016.90",
    arxiv: "1512.03385",
    mainURL: "",
    publisher: "IEEE",
    pages: "770-778",
    volume: "",
    number: "",
    rating: 5,
    flag: true,
    tags: [{ name: "vision" }, { name: "architectures" }],
    folders: [{ name: "Vision" }],
  },
  {
    id: "kingma2015adam",
    title: "Adam: A Method for Stochastic Optimization",
    authors: "Diederik P. Kingma, Jimmy Ba",
    abstract:
      "Adam computes individual adaptive learning rates for different parameters from estimates of first and second moments of the gradients. The method is straightforward to implement, computationally efficient, and well suited to large-scale problems.",
    note: "",
    publication: "International Conference on Learning Representations",
    pubTime: "2015",
    pubType: 1,
    doi: "10.48550/arXiv.1412.6980",
    arxiv: "1412.6980",
    mainURL: "",
    publisher: "",
    pages: "",
    volume: "",
    number: "",
    rating: 4,
    flag: false,
    tags: [{ name: "optimization" }],
    folders: [{ name: "Foundations" }],
  },
  {
    id: "krizhevsky2012imagenet",
    title: "ImageNet Classification with Deep Convolutional Neural Networks",
    authors: "Alex Krizhevsky, Ilya Sutskever, Geoffrey E. Hinton",
    abstract:
      "A large, deep convolutional neural network trained on ImageNet achieved substantially higher accuracy than previous methods. The network has 60 million parameters, five convolutional layers, and uses dropout to reduce overfitting.",
    note: "",
    publication: "Advances in Neural Information Processing Systems",
    pubTime: "2012",
    pubType: 1,
    doi: "10.1145/3065386",
    arxiv: "",
    mainURL: "",
    publisher: "Curran Associates, Inc.",
    pages: "1097-1105",
    volume: "25",
    number: "",
    rating: 5,
    flag: false,
    tags: [{ name: "vision" }, { name: "cnn" }],
    folders: [{ name: "Vision" }],
  },
];
