const collocations: Record<string, string[]> = {
  accept: ["accept advice", "accept an offer", "accept responsibility", "accept the result"],
  add: ["add details", "add information", "add a comment", "add value"],
  achieve: ["achieve a goal", "achieve balance", "achieve success", "achieve results"],
  ask: ["ask a question", "ask for help", "ask for advice", "ask permission"],
  avoid: ["avoid conflict", "avoid delays", "avoid mistakes", "avoid risk"],
  be: ["be careful", "be ready", "be aware of", "be in charge of"],
  become: ["become clear", "become available", "become difficult", "become more common"],
  begin: ["begin a project", "begin work", "begin a task", "begin to improve"],
  break: ["break a promise", "break a record", "break the law", "break the silence"],
  bring: ["bring attention to", "bring back memories", "bring change", "bring results"],
  build: ["build confidence", "build a habit", "build a relationship", "build trust"],
  buy: ["buy time", "buy a ticket", "buy groceries", "buy a house"],
  call: ["call a meeting", "call for action", "call someone back", "call attention to"],
  carry: ["carry a bag", "carry out a plan", "carry out research", "carry a load"],
  change: ["change plans", "change direction", "change habits", "change the settings"],
  check: ["check details", "check the facts", "check the answer", "check for errors"],
  choose: ["choose a path", "choose a name", "choose a solution", "choose between options"],
  clean: ["clean the house", "clean the kitchen", "clean the room", "clean up"],
  close: ["close a deal", "close the door", "close a gap", "close a case"],
  collect: ["collect data", "collect information", "collect samples", "collect feedback"],
  come: ["come back", "come to an agreement", "come to mind", "come into effect"],
  complete: ["complete a form", "complete a task", "complete the process", "complete a course"],
  connect: ["connect the device", "connect the cables", "connect with people", "connect ideas"],
  consider: ["consider options", "consider the cost", "consider a change", "consider the evidence"],
  create: ["create a plan", "create a file", "create an account", "create value"],
  cut: ["cut costs", "cut ties", "cut the price", "cut the cake"],
  decide: ["decide quickly", "decide on a plan", "decide the next step", "decide the outcome"],
  develop: ["develop a skill", "develop a habit", "develop a plan", "develop a product"],
  do: ["do homework", "do business", "do research", "do the dishes"],
  draw: ["draw attention", "draw a conclusion", "draw a line", "draw inspiration from"],
  drive: ["drive a car", "drive sales", "drive growth", "drive results"],
  enjoy: ["enjoy the process", "enjoy the day", "enjoy your meal", "enjoy the experience"],
  enter: ["enter a room", "enter the data", "enter the market", "enter a competition"],
  explore: ["explore options", "explore ideas", "explore the area", "explore a topic"],
  extend: ["extend a deadline", "extend the offer", "extend support", "extend a contract"],
  face: ["face a challenge", "face a problem", "face the facts", "face the truth"],
  find: ["find a solution", "find out", "find a balance", "find your way"],
  follow: ["follow the rules", "follow instructions", "follow up", "follow a path"],
  forget: ["forget a name", "forget the details", "forget the deadline", "forget the rest"],
  gain: ["gain experience", "gain confidence", "gain support", "gain access"],
  generate: ["generate ideas", "generate interest", "generate revenue", "generate demand"],
  get: ["get married", "get started", "get permission", "get the job done"],
  give: ["give advice", "give a speech", "give permission", "give support"],
  go: ["go abroad", "go bankrupt", "go missing", "go wrong"],
  have: ["have a meeting", "have breakfast", "have trouble", "have a chance"],
  handle: ["handle a request", "handle a problem", "handle pressure", "handle the situation"],
  help: ["help a customer", "help with the work", "help someone succeed", "help the team"],
  hold: ["hold a meeting", "hold a conversation", "hold your breath", "hold a position"],
  improve: ["improve results", "improve performance", "improve skills", "improve the process"],
  include: ["include details", "include examples", "include a summary", "include the price"],
  increase: ["increase sales", "increase efficiency", "increase the budget", "increase awareness"],
  join: ["join a team", "join a meeting", "join the group", "join the conversation"],
  keep: ["keep a promise", "keep in touch", "keep a secret", "keep things simple"],
  know: ["know the difference", "know by heart", "know the answer", "know what to expect"],
  learn: ["learn a lesson", "learn by doing", "learn a language", "learn the basics"],
  leave: ["leave a message", "leave early", "leave room for", "leave the door open"],
  look: ["look ahead", "look closely", "look for evidence", "look after someone"],
  make: ["make a decision", "make progress", "make an effort", "make a mistake"],
  manage: ["manage time", "manage expectations", "manage a team", "manage costs"],
  meet: ["meet a deadline", "meet expectations", "meet in person", "meet the requirements"],
  move: ["move forward", "move house", "move quickly", "move to a new role"],
  open: ["open a file", "open a door", "open a business", "open an account"],
  organize: ["organize a meeting", "organize files", "organize a trip", "organize your time"],
  pay: ["pay attention", "pay a bill", "pay a visit", "pay the price"],
  play: ["play a role", "play a game", "play music", "play a part"],
  prepare: ["prepare a meal", "prepare a report", "prepare for a meeting", "prepare a plan"],
  provide: ["provide support", "provide information", "provide access", "provide feedback"],
  put: ["put pressure on", "put together", "put at risk", "put into practice"],
  reduce: ["reduce costs", "reduce stress", "reduce waste", "reduce risk"],
  review: ["review the document", "review the results", "review the plan", "review the notes"],
  run: ["run a business", "run a test", "run late", "run out of time"],
  save: ["save time", "save money", "save a file", "save energy"],
  say: ["say goodbye", "say thank you", "say no", "say something clearly"],
  search: ["search for answers", "search the web", "search the area", "search for evidence"],
  see: ["see a difference", "see the point", "see progress", "see someone again"],
  set: ["set a goal", "set a deadline", "set an example", "set the table"],
  share: ["share information", "share a link", "share an idea", "share a meal"],
  start: ["start a business", "start a conversation", "start a project", "start over"],
  stop: ["stop a process", "stop the car", "stop doing that", "stop a service"],
  study: ["study a subject", "study the results", "study abroad", "study hard"],
  suggest: ["suggest a solution", "suggest a change", "suggest an idea", "suggest a time"],
  support: ["support a decision", "support a cause", "support a team", "support a claim"],
  take: ["take a break", "take a risk", "take responsibility", "take notes"],
  tell: ["tell the truth", "tell a story", "tell the difference", "tell someone apart"],
  think: ["think carefully", "think ahead", "think out loud", "think twice"],
  try: ["try your best", "try again", "try a new approach", "try to improve"],
  turn: ["turn around", "turn out well", "turn into", "turn your attention to"],
  understand: ["understand the problem", "understand the difference", "understand the process", "understand the need"],
  update: ["update software", "update the record", "update the file", "update the system"],
  use: ["use common sense", "use a tool", "use your imagination", "use evidence"],
  visit: ["visit a website", "visit a friend", "visit a doctor", "visit a place"],
  watch: ["watch a movie", "watch closely", "watch the news", "watch for signs"],
  win: ["win a prize", "win an argument", "win support", "win the game"],
  work: ["work hard", "work remotely", "work on a project", "work well together"],
  write: ["write a report", "write an email", "write down", "write a review"],
};

export function getCommonCollocations(verb: string) {
  return collocations[verb] ?? [];
}
