// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("opiniao")}
      searchBarPlaceholder="Search Opinion…"
      errorToastTitle="Unable to load Opinion"
      emptyTitle="No Opinion articles right now"
      emptyDescription="Check back soon. Opinion articles from Público will appear here."
    />
  );
}
