// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("parlamento")}
      searchBarPlaceholder="Search Parliament…"
      errorToastTitle="Unable to load Parliament"
      emptyTitle="No Parliament articles right now"
      emptyDescription="Check back soon. Parliament articles from Público will appear here."
    />
  );
}
