// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("europa")}
      searchBarPlaceholder="Search Europe…"
      errorToastTitle="Unable to load Europe"
      emptyTitle="No Europe articles right now"
      emptyDescription="Check back soon. Europe articles from Público will appear here."
    />
  );
}
