// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("brasil")}
      searchBarPlaceholder="Search Brazil…"
      errorToastTitle="Unable to load Brazil"
      emptyTitle="No Brazil articles right now"
      emptyDescription="Check back soon. Brazil articles from Público will appear here."
    />
  );
}
