// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("tecnologia")}
      searchBarPlaceholder="Search Technology…"
      errorToastTitle="Unable to load Technology"
      emptyTitle="No Technology articles right now"
      emptyDescription="Check back soon. Technology articles from Público will appear here."
    />
  );
}
