// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("sociedade")}
      searchBarPlaceholder="Search Society…"
      errorToastTitle="Unable to load Society"
      emptyTitle="No Society articles right now"
      emptyDescription="Check back soon. Society articles from Público will appear here."
    />
  );
}
