// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("viagens")}
      searchBarPlaceholder="Search Travel…"
      errorToastTitle="Unable to load Travel"
      emptyTitle="No Travel articles right now"
      emptyDescription="Check back soon. Travel articles from Público will appear here."
    />
  );
}
