// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("ciencia")}
      searchBarPlaceholder="Search Science…"
      errorToastTitle="Unable to load Science"
      emptyTitle="No Science articles right now"
      emptyDescription="Check back soon. Science articles from Público will appear here."
    />
  );
}
