// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("media")}
      searchBarPlaceholder="Search Media…"
      errorToastTitle="Unable to load Media"
      emptyTitle="No Media articles right now"
      emptyDescription="Check back soon. Media articles from Público will appear here."
    />
  );
}
