// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("saude")}
      searchBarPlaceholder="Search Health…"
      errorToastTitle="Unable to load Health"
      emptyTitle="No Health articles right now"
      emptyDescription="Check back soon. Health articles from Público will appear here."
    />
  );
}
