// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("multimedia")}
      searchBarPlaceholder="Search Multimedia…"
      errorToastTitle="Unable to load Multimedia"
      emptyTitle="No Multimedia articles right now"
      emptyDescription="Check back soon. Multimedia articles from Público will appear here."
    />
  );
}
