// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("gente")}
      searchBarPlaceholder="Search People…"
      errorToastTitle="Unable to load People"
      emptyTitle="No People articles right now"
      emptyDescription="Check back soon. People articles from Público will appear here."
    />
  );
}
