// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("podcasts")}
      searchBarPlaceholder="Search Podcasts…"
      errorToastTitle="Unable to load Podcasts"
      emptyTitle="No Podcasts articles right now"
      emptyDescription="Check back soon. Podcasts articles from Público will appear here."
    />
  );
}
