// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("ecosfera")}
      searchBarPlaceholder="Search Ecosfera…"
      errorToastTitle="Unable to load Ecosfera"
      emptyTitle="No Ecosfera articles right now"
      emptyDescription="Check back soon. Ecosfera articles from Público will appear here."
    />
  );
}
