// Generated by scripts/generate-sections.mjs. Do not edit by hand.
import { fetchSection } from "./api/client";
import { NewsListView } from "./components/NewsListView";

export default function Command() {
  return (
    <NewsListView
      fetchFn={() => fetchSection("impar")}
      searchBarPlaceholder="Search Ímpar…"
      errorToastTitle="Unable to load Ímpar"
      emptyTitle="No Ímpar articles right now"
      emptyDescription="Check back soon. Ímpar articles from Público will appear here."
    />
  );
}
