/**
 * Represents a shade category for HTML colors
 */
export type ShadeCategory =
  | "pink"
  | "red"
  | "orange"
  | "yellow"
  | "brown"
  | "green"
  | "white"
  | "black and gray"
  | "purple, violet and magenta"
  | "blue"
  | "cyan";

/**
 * Static order of shade categories for consistent sorting
 */
export const SHADE_ORDER: ShadeCategory[] = [
  "pink",
  "red",
  "orange",
  "yellow",
  "brown",
  "green",
  "white",
  "black and gray",
  "purple, violet and magenta",
  "blue",
  "cyan",
];

/**
 * Represents a color with its various formats and category information
 */
export type Color = {
  name: string;
  hex: string;
  rgb: string;
  category: "basic" | "extended";
  format: "hex" | "rgb" | "name";
  id: string;
  shade: ShadeCategory;
};

/**
 * Collection of basic HTML colors with their hex, rgb, and name values
 */
export const basicColors: Color[] = [
  {
    name: "Black",
    hex: "#000000",
    rgb: "rgb(0, 0, 0)",
    category: "basic",
    format: "name",
    id: "black",
    shade: "black and gray",
  },
  {
    name: "Silver",
    hex: "#C0C0C0",
    rgb: "rgb(192, 192, 192)",
    category: "basic",
    format: "name",
    id: "silver",
    shade: "black and gray",
  },
  {
    name: "Gray",
    hex: "#808080",
    rgb: "rgb(128, 128, 128)",
    category: "basic",
    format: "name",
    id: "gray",
    shade: "black and gray",
  },
  {
    name: "White",
    hex: "#FFFFFF",
    rgb: "rgb(255, 255, 255)",
    category: "basic",
    format: "name",
    id: "white",
    shade: "white",
  },
  {
    name: "Maroon",
    hex: "#800000",
    rgb: "rgb(128, 0, 0)",
    category: "basic",
    format: "name",
    id: "maroon",
    shade: "red",
  },
  { name: "Red", hex: "#FF0000", rgb: "rgb(255, 0, 0)", category: "basic", format: "name", id: "red", shade: "red" },
  {
    name: "Purple",
    hex: "#800080",
    rgb: "rgb(128, 0, 128)",
    category: "basic",
    format: "name",
    id: "purple",
    shade: "purple, violet and magenta",
  },
  {
    name: "Fuchsia",
    hex: "#FF00FF",
    rgb: "rgb(255, 0, 255)",
    category: "basic",
    format: "name",
    id: "fuchsia",
    shade: "purple, violet and magenta",
  },
  {
    name: "Green",
    hex: "#008000",
    rgb: "rgb(0, 128, 0)",
    category: "basic",
    format: "name",
    id: "green",
    shade: "green",
  },
  {
    name: "Lime",
    hex: "#00FF00",
    rgb: "rgb(0, 255, 0)",
    category: "basic",
    format: "name",
    id: "lime",
    shade: "green",
  },
  {
    name: "Olive",
    hex: "#808000",
    rgb: "rgb(128, 128, 0)",
    category: "basic",
    format: "name",
    id: "olive",
    shade: "green",
  },
  {
    name: "Yellow",
    hex: "#FFFF00",
    rgb: "rgb(255, 255, 0)",
    category: "basic",
    format: "name",
    id: "yellow",
    shade: "yellow",
  },
  { name: "Navy", hex: "#000080", rgb: "rgb(0, 0, 128)", category: "basic", format: "name", id: "navy", shade: "blue" },
  { name: "Blue", hex: "#0000FF", rgb: "rgb(0, 0, 255)", category: "basic", format: "name", id: "blue", shade: "blue" },
  {
    name: "Teal",
    hex: "#008080",
    rgb: "rgb(0, 128, 128)",
    category: "basic",
    format: "name",
    id: "teal",
    shade: "cyan",
  },
  {
    name: "Aqua",
    hex: "#00FFFF",
    rgb: "rgb(0, 255, 255)",
    category: "basic",
    format: "name",
    id: "aqua",
    shade: "cyan",
  },
];

/**
 * Collection of extended HTML colors with their hex, rgb, and name values
 */
export const extendedColors: Color[] = [
  {
    name: "AliceBlue",
    hex: "#F0F8FF",
    rgb: "rgb(240, 248, 255)",
    category: "extended",
    format: "name",
    id: "aliceblue",
    shade: "white",
  },
  {
    name: "AntiqueWhite",
    hex: "#FAEBD7",
    rgb: "rgb(250, 235, 215)",
    category: "extended",
    format: "name",
    id: "antiquewhite",
    shade: "white",
  },
  {
    name: "Aqua",
    hex: "#00FFFF",
    rgb: "rgb(0, 255, 255)",
    category: "extended",
    format: "name",
    id: "aqua",
    shade: "cyan",
  },
  {
    name: "Aquamarine",
    hex: "#7FFFD4",
    rgb: "rgb(127, 255, 212)",
    category: "extended",
    format: "name",
    id: "aquamarine",
    shade: "cyan",
  },
  {
    name: "Azure",
    hex: "#F0FFFF",
    rgb: "rgb(240, 255, 255)",
    category: "extended",
    format: "name",
    id: "azure",
    shade: "white",
  },
  {
    name: "Beige",
    hex: "#F5F5DC",
    rgb: "rgb(245, 245, 220)",
    category: "extended",
    format: "name",
    id: "beige",
    shade: "white",
  },
  {
    name: "Bisque",
    hex: "#FFE4C4",
    rgb: "rgb(255, 228, 196)",
    category: "extended",
    format: "name",
    id: "bisque",
    shade: "brown",
  },
  {
    name: "Black",
    hex: "#000000",
    rgb: "rgb(0, 0, 0)",
    category: "extended",
    format: "name",
    id: "black",
    shade: "black and gray",
  },
  {
    name: "BlanchedAlmond",
    hex: "#FFEBCD",
    rgb: "rgb(255, 235, 205)",
    category: "extended",
    format: "name",
    id: "blanchedalmond",
    shade: "brown",
  },
  {
    name: "Blue",
    hex: "#0000FF",
    rgb: "rgb(0, 0, 255)",
    category: "extended",
    format: "name",
    id: "blue",
    shade: "blue",
  },
  {
    name: "BlueViolet",
    hex: "#8A2BE2",
    rgb: "rgb(138, 43, 226)",
    category: "extended",
    format: "name",
    id: "blueviolet",
    shade: "purple, violet and magenta",
  },
  {
    name: "Brown",
    hex: "#A52A2A",
    rgb: "rgb(165, 42, 42)",
    category: "extended",
    format: "name",
    id: "brown",
    shade: "brown",
  },
  {
    name: "BurlyWood",
    hex: "#DEB887",
    rgb: "rgb(222, 184, 135)",
    category: "extended",
    format: "name",
    id: "burlywood",
    shade: "brown",
  },
  {
    name: "CadetBlue",
    hex: "#5F9EA0",
    rgb: "rgb(95, 158, 160)",
    category: "extended",
    format: "name",
    id: "cadetblue",
    shade: "cyan",
  },
  {
    name: "Chartreuse",
    hex: "#7FFF00",
    rgb: "rgb(127, 255, 0)",
    category: "extended",
    format: "name",
    id: "chartreuse",
    shade: "green",
  },
  {
    name: "Chocolate",
    hex: "#D2691E",
    rgb: "rgb(210, 105, 30)",
    category: "extended",
    format: "name",
    id: "chocolate",
    shade: "brown",
  },
  {
    name: "Coral",
    hex: "#FF7F50",
    rgb: "rgb(255, 127, 80)",
    category: "extended",
    format: "name",
    id: "coral",
    shade: "orange",
  },
  {
    name: "CornflowerBlue",
    hex: "#6495ED",
    rgb: "rgb(100, 149, 237)",
    category: "extended",
    format: "name",
    id: "cornflowerblue",
    shade: "blue",
  },
  {
    name: "Cornsilk",
    hex: "#FFF8DC",
    rgb: "rgb(255, 248, 220)",
    category: "extended",
    format: "name",
    id: "cornsilk",
    shade: "brown",
  },
  {
    name: "Crimson",
    hex: "#DC143C",
    rgb: "rgb(220, 20, 60)",
    category: "extended",
    format: "name",
    id: "crimson",
    shade: "red",
  },
  {
    name: "Cyan",
    hex: "#00FFFF",
    rgb: "rgb(0, 255, 255)",
    category: "extended",
    format: "name",
    id: "cyan",
    shade: "cyan",
  },
  {
    name: "DarkBlue",
    hex: "#00008B",
    rgb: "rgb(0, 0, 139)",
    category: "extended",
    format: "name",
    id: "darkblue",
    shade: "blue",
  },
  {
    name: "DarkCyan",
    hex: "#008B8B",
    rgb: "rgb(0, 139, 139)",
    category: "extended",
    format: "name",
    id: "darkcyan",
    shade: "cyan",
  },
  {
    name: "DarkGoldenrod",
    hex: "#B8860B",
    rgb: "rgb(184, 134, 11)",
    category: "extended",
    format: "name",
    id: "darkgoldenrod",
    shade: "brown",
  },
  {
    name: "DarkGray",
    hex: "#A9A9A9",
    rgb: "rgb(169, 169, 169)",
    category: "extended",
    format: "name",
    id: "darkgray",
    shade: "black and gray",
  },
  {
    name: "DarkGreen",
    hex: "#006400",
    rgb: "rgb(0, 100, 0)",
    category: "extended",
    format: "name",
    id: "darkgreen",
    shade: "green",
  },
  {
    name: "DarkKhaki",
    hex: "#BDB76B",
    rgb: "rgb(189, 183, 107)",
    category: "extended",
    format: "name",
    id: "darkkhaki",
    shade: "yellow",
  },
  {
    name: "DarkMagenta",
    hex: "#8B008B",
    rgb: "rgb(139, 0, 139)",
    category: "extended",
    format: "name",
    id: "darkmagenta",
    shade: "purple, violet and magenta",
  },
  {
    name: "DarkOliveGreen",
    hex: "#556B2F",
    rgb: "rgb(85, 107, 47)",
    category: "extended",
    format: "name",
    id: "darkolivegreen",
    shade: "green",
  },
  {
    name: "DarkOrange",
    hex: "#FF8C00",
    rgb: "rgb(255, 140, 0)",
    category: "extended",
    format: "name",
    id: "darkorange",
    shade: "orange",
  },
  {
    name: "DarkOrchid",
    hex: "#9932CC",
    rgb: "rgb(153, 50, 204)",
    category: "extended",
    format: "name",
    id: "darkorchid",
    shade: "purple, violet and magenta",
  },
  {
    name: "DarkRed",
    hex: "#8B0000",
    rgb: "rgb(139, 0, 0)",
    category: "extended",
    format: "name",
    id: "darkred",
    shade: "red",
  },
  {
    name: "DarkSalmon",
    hex: "#E9967A",
    rgb: "rgb(233, 150, 122)",
    category: "extended",
    format: "name",
    id: "darksalmon",
    shade: "red",
  },
  {
    name: "DarkSeaGreen",
    hex: "#8FBC8F",
    rgb: "rgb(143, 188, 143)",
    category: "extended",
    format: "name",
    id: "darkseagreen",
    shade: "green",
  },
  {
    name: "DarkSlateBlue",
    hex: "#483D8B",
    rgb: "rgb(72, 61, 139)",
    category: "extended",
    format: "name",
    id: "darkslateblue",
    shade: "purple, violet and magenta",
  },
  {
    name: "DarkSlateGray",
    hex: "#2F4F4F",
    rgb: "rgb(47, 79, 79)",
    category: "extended",
    format: "name",
    id: "darkslategray",
    shade: "black and gray",
  },
  {
    name: "DarkTurquoise",
    hex: "#00CED1",
    rgb: "rgb(0, 206, 209)",
    category: "extended",
    format: "name",
    id: "darkturquoise",
    shade: "cyan",
  },
  {
    name: "DarkViolet",
    hex: "#9400D3",
    rgb: "rgb(148, 0, 211)",
    category: "extended",
    format: "name",
    id: "darkviolet",
    shade: "purple, violet and magenta",
  },
  {
    name: "DeepPink",
    hex: "#FF1493",
    rgb: "rgb(255, 20, 147)",
    category: "extended",
    format: "name",
    id: "deeppink",
    shade: "pink",
  },
  {
    name: "DeepSkyBlue",
    hex: "#00BFFF",
    rgb: "rgb(0, 191, 255)",
    category: "extended",
    format: "name",
    id: "deepskyblue",
    shade: "blue",
  },
  {
    name: "DimGray",
    hex: "#696969",
    rgb: "rgb(105, 105, 105)",
    category: "extended",
    format: "name",
    id: "dimgray",
    shade: "black and gray",
  },
  {
    name: "DodgerBlue",
    hex: "#1E90FF",
    rgb: "rgb(30, 144, 255)",
    category: "extended",
    format: "name",
    id: "dodgerblue",
    shade: "blue",
  },
  {
    name: "FireBrick",
    hex: "#B22222",
    rgb: "rgb(178, 34, 34)",
    category: "extended",
    format: "name",
    id: "firebrick",
    shade: "red",
  },
  {
    name: "FloralWhite",
    hex: "#FFFAF0",
    rgb: "rgb(255, 250, 240)",
    category: "extended",
    format: "name",
    id: "floralwhite",
    shade: "white",
  },
  {
    name: "ForestGreen",
    hex: "#228B22",
    rgb: "rgb(34, 139, 34)",
    category: "extended",
    format: "name",
    id: "forestgreen",
    shade: "green",
  },
  {
    name: "Fuchsia",
    hex: "#FF00FF",
    rgb: "rgb(255, 0, 255)",
    category: "extended",
    format: "name",
    id: "fuchsia",
    shade: "purple, violet and magenta",
  },
  {
    name: "Gainsboro",
    hex: "#DCDCDC",
    rgb: "rgb(220, 220, 220)",
    category: "extended",
    format: "name",
    id: "gainsboro",
    shade: "black and gray",
  },
  {
    name: "GhostWhite",
    hex: "#F8F8FF",
    rgb: "rgb(248, 248, 255)",
    category: "extended",
    format: "name",
    id: "ghostwhite",
    shade: "white",
  },
  {
    name: "Gold",
    hex: "#FFD700",
    rgb: "rgb(255, 215, 0)",
    category: "extended",
    format: "name",
    id: "gold",
    shade: "yellow",
  },
  {
    name: "Goldenrod",
    hex: "#DAA520",
    rgb: "rgb(218, 165, 32)",
    category: "extended",
    format: "name",
    id: "goldenrod",
    shade: "brown",
  },
  {
    name: "Gray",
    hex: "#808080",
    rgb: "rgb(128, 128, 128)",
    category: "extended",
    format: "name",
    id: "gray",
    shade: "black and gray",
  },
  {
    name: "Green",
    hex: "#008000",
    rgb: "rgb(0, 128, 0)",
    category: "extended",
    format: "name",
    id: "green",
    shade: "green",
  },
  {
    name: "GreenYellow",
    hex: "#ADFF2F",
    rgb: "rgb(173, 255, 47)",
    category: "extended",
    format: "name",
    id: "greenyellow",
    shade: "green",
  },
  {
    name: "Honeydew",
    hex: "#F0FFF0",
    rgb: "rgb(240, 255, 240)",
    category: "extended",
    format: "name",
    id: "honeydew",
    shade: "white",
  },
  {
    name: "HotPink",
    hex: "#FF69B4",
    rgb: "rgb(255, 105, 180)",
    category: "extended",
    format: "name",
    id: "hotpink",
    shade: "pink",
  },
  {
    name: "IndianRed",
    hex: "#CD5C5C",
    rgb: "rgb(205, 92, 92)",
    category: "extended",
    format: "name",
    id: "indianred",
    shade: "red",
  },
  {
    name: "Indigo",
    hex: "#4B0082",
    rgb: "rgb(75, 0, 130)",
    category: "extended",
    format: "name",
    id: "indigo",
    shade: "purple, violet and magenta",
  },
  {
    name: "Ivory",
    hex: "#FFFFF0",
    rgb: "rgb(255, 255, 240)",
    category: "extended",
    format: "name",
    id: "ivory",
    shade: "white",
  },
  {
    name: "Khaki",
    hex: "#F0E68C",
    rgb: "rgb(240, 230, 140)",
    category: "extended",
    format: "name",
    id: "khaki",
    shade: "yellow",
  },
  {
    name: "Lavender",
    hex: "#E6E6FA",
    rgb: "rgb(230, 230, 250)",
    category: "extended",
    format: "name",
    id: "lavender",
    shade: "purple, violet and magenta",
  },
  {
    name: "LavenderBlush",
    hex: "#FFF0F5",
    rgb: "rgb(255, 240, 245)",
    category: "extended",
    format: "name",
    id: "lavenderblush",
    shade: "white",
  },
  {
    name: "LawnGreen",
    hex: "#7CFC00",
    rgb: "rgb(124, 252, 0)",
    category: "extended",
    format: "name",
    id: "lawngreen",
    shade: "green",
  },
  {
    name: "LemonChiffon",
    hex: "#FFFACD",
    rgb: "rgb(255, 250, 205)",
    category: "extended",
    format: "name",
    id: "lemonchiffon",
    shade: "yellow",
  },
  {
    name: "LightBlue",
    hex: "#ADD8E6",
    rgb: "rgb(173, 216, 230)",
    category: "extended",
    format: "name",
    id: "lightblue",
    shade: "blue",
  },
  {
    name: "LightCoral",
    hex: "#F08080",
    rgb: "rgb(240, 128, 128)",
    category: "extended",
    format: "name",
    id: "lightcoral",
    shade: "red",
  },
  {
    name: "LightCyan",
    hex: "#E0FFFF",
    rgb: "rgb(224, 255, 255)",
    category: "extended",
    format: "name",
    id: "lightcyan",
    shade: "cyan",
  },
  {
    name: "LightGoldenrodYellow",
    hex: "#FAFAD2",
    rgb: "rgb(250, 250, 210)",
    category: "extended",
    format: "name",
    id: "lightgoldenrodyellow",
    shade: "yellow",
  },
  {
    name: "LightGray",
    hex: "#D3D3D3",
    rgb: "rgb(211, 211, 211)",
    category: "extended",
    format: "name",
    id: "lightgray",
    shade: "black and gray",
  },
  {
    name: "LightGreen",
    hex: "#90EE90",
    rgb: "rgb(144, 238, 144)",
    category: "extended",
    format: "name",
    id: "lightgreen",
    shade: "green",
  },
  {
    name: "LightPink",
    hex: "#FFB6C1",
    rgb: "rgb(255, 182, 193)",
    category: "extended",
    format: "name",
    id: "lightpink",
    shade: "pink",
  },
  {
    name: "LightSalmon",
    hex: "#FFA07A",
    rgb: "rgb(255, 160, 122)",
    category: "extended",
    format: "name",
    id: "lightsalmon",
    shade: "red",
  },
  {
    name: "LightSeaGreen",
    hex: "#20B2AA",
    rgb: "rgb(32, 178, 170)",
    category: "extended",
    format: "name",
    id: "lightseagreen",
    shade: "cyan",
  },
  {
    name: "LightSkyBlue",
    hex: "#87CEFA",
    rgb: "rgb(135, 206, 250)",
    category: "extended",
    format: "name",
    id: "lightskyblue",
    shade: "blue",
  },
  {
    name: "LightSlateGray",
    hex: "#778899",
    rgb: "rgb(119, 136, 153)",
    category: "extended",
    format: "name",
    id: "lightslategray",
    shade: "black and gray",
  },
  {
    name: "LightSteelBlue",
    hex: "#B0C4DE",
    rgb: "rgb(176, 196, 222)",
    category: "extended",
    format: "name",
    id: "lightsteelblue",
    shade: "blue",
  },
  {
    name: "LightYellow",
    hex: "#FFFFE0",
    rgb: "rgb(255, 255, 224)",
    category: "extended",
    format: "name",
    id: "lightyellow",
    shade: "yellow",
  },
  {
    name: "Lime",
    hex: "#00FF00",
    rgb: "rgb(0, 255, 0)",
    category: "extended",
    format: "name",
    id: "lime",
    shade: "green",
  },
  {
    name: "LimeGreen",
    hex: "#32CD32",
    rgb: "rgb(50, 205, 50)",
    category: "extended",
    format: "name",
    id: "limegreen",
    shade: "green",
  },
  {
    name: "Linen",
    hex: "#FAF0E6",
    rgb: "rgb(250, 240, 230)",
    category: "extended",
    format: "name",
    id: "linen",
    shade: "white",
  },
  {
    name: "Magenta",
    hex: "#FF00FF",
    rgb: "rgb(255, 0, 255)",
    category: "extended",
    format: "name",
    id: "magenta",
    shade: "purple, violet and magenta",
  },
  {
    name: "Maroon",
    hex: "#800000",
    rgb: "rgb(128, 0, 0)",
    category: "extended",
    format: "name",
    id: "maroon",
    shade: "brown",
  },
  {
    name: "MediumAquamarine",
    hex: "#66CDAA",
    rgb: "rgb(102, 205, 170)",
    category: "extended",
    format: "name",
    id: "mediumaquamarine",
    shade: "green",
  },
  {
    name: "MediumBlue",
    hex: "#0000CD",
    rgb: "rgb(0, 0, 205)",
    category: "extended",
    format: "name",
    id: "mediumblue",
    shade: "blue",
  },
  {
    name: "MediumOrchid",
    hex: "#BA55D3",
    rgb: "rgb(186, 85, 211)",
    category: "extended",
    format: "name",
    id: "mediumorchid",
    shade: "purple, violet and magenta",
  },
  {
    name: "MediumPurple",
    hex: "#9370DB",
    rgb: "rgb(147, 112, 219)",
    category: "extended",
    format: "name",
    id: "mediumpurple",
    shade: "purple, violet and magenta",
  },
  {
    name: "MediumSeaGreen",
    hex: "#3CB371",
    rgb: "rgb(60, 179, 113)",
    category: "extended",
    format: "name",
    id: "mediumseagreen",
    shade: "green",
  },
  {
    name: "MediumSlateBlue",
    hex: "#7B68EE",
    rgb: "rgb(123, 104, 238)",
    category: "extended",
    format: "name",
    id: "mediumslateblue",
    shade: "purple, violet and magenta",
  },
  {
    name: "MediumSpringGreen",
    hex: "#00FA9A",
    rgb: "rgb(0, 250, 154)",
    category: "extended",
    format: "name",
    id: "mediumspringgreen",
    shade: "green",
  },
  {
    name: "MediumTurquoise",
    hex: "#48D1CC",
    rgb: "rgb(72, 209, 204)",
    category: "extended",
    format: "name",
    id: "mediumturquoise",
    shade: "cyan",
  },
  {
    name: "MediumVioletRed",
    hex: "#C71585",
    rgb: "rgb(199, 21, 133)",
    category: "extended",
    format: "name",
    id: "mediumvioletred",
    shade: "pink",
  },
  {
    name: "MidnightBlue",
    hex: "#191970",
    rgb: "rgb(25, 25, 112)",
    category: "extended",
    format: "name",
    id: "midnightblue",
    shade: "blue",
  },
  {
    name: "MintCream",
    hex: "#F5FFFA",
    rgb: "rgb(245, 255, 250)",
    category: "extended",
    format: "name",
    id: "mintcream",
    shade: "white",
  },
  {
    name: "MistyRose",
    hex: "#FFE4E1",
    rgb: "rgb(255, 228, 225)",
    category: "extended",
    format: "name",
    id: "mistyrose",
    shade: "white",
  },
  {
    name: "Moccasin",
    hex: "#FFE4B5",
    rgb: "rgb(255, 228, 181)",
    category: "extended",
    format: "name",
    id: "moccasin",
    shade: "yellow",
  },
  {
    name: "NavajoWhite",
    hex: "#FFDEAD",
    rgb: "rgb(255, 222, 173)",
    category: "extended",
    format: "name",
    id: "navajowhite",
    shade: "brown",
  },
  {
    name: "Navy",
    hex: "#000080",
    rgb: "rgb(0, 0, 128)",
    category: "extended",
    format: "name",
    id: "navy",
    shade: "blue",
  },
  {
    name: "OldLace",
    hex: "#FDF5E6",
    rgb: "rgb(253, 245, 230)",
    category: "extended",
    format: "name",
    id: "oldlace",
    shade: "white",
  },
  {
    name: "Olive",
    hex: "#808000",
    rgb: "rgb(128, 128, 0)",
    category: "extended",
    format: "name",
    id: "olive",
    shade: "yellow",
  },
  {
    name: "OliveDrab",
    hex: "#6B8E23",
    rgb: "rgb(107, 142, 35)",
    category: "extended",
    format: "name",
    id: "olivedrab",
    shade: "green",
  },
  {
    name: "Orange",
    hex: "#FFA500",
    rgb: "rgb(255, 165, 0)",
    category: "extended",
    format: "name",
    id: "orange",
    shade: "orange",
  },
  {
    name: "OrangeRed",
    hex: "#FF4500",
    rgb: "rgb(255, 69, 0)",
    category: "extended",
    format: "name",
    id: "orangered",
    shade: "orange",
  },
  {
    name: "Orchid",
    hex: "#DA70D6",
    rgb: "rgb(218, 112, 214)",
    category: "extended",
    format: "name",
    id: "orchid",
    shade: "purple, violet and magenta",
  },
  {
    name: "PaleGoldenrod",
    hex: "#EEE8AA",
    rgb: "rgb(238, 232, 170)",
    category: "extended",
    format: "name",
    id: "palegoldenrod",
    shade: "yellow",
  },
  {
    name: "PaleGreen",
    hex: "#98FB98",
    rgb: "rgb(152, 251, 152)",
    category: "extended",
    format: "name",
    id: "palegreen",
    shade: "green",
  },
  {
    name: "PaleTurquoise",
    hex: "#AFEEEE",
    rgb: "rgb(175, 238, 238)",
    category: "extended",
    format: "name",
    id: "paleturquoise",
    shade: "cyan",
  },
  {
    name: "PaleVioletRed",
    hex: "#DB7093",
    rgb: "rgb(219, 112, 147)",
    category: "extended",
    format: "name",
    id: "palevioletred",
    shade: "pink",
  },
  {
    name: "PapayaWhip",
    hex: "#FFEFD5",
    rgb: "rgb(255, 239, 213)",
    category: "extended",
    format: "name",
    id: "papayawhip",
    shade: "yellow",
  },
  {
    name: "PeachPuff",
    hex: "#FFDAB9",
    rgb: "rgb(255, 218, 185)",
    category: "extended",
    format: "name",
    id: "peachpuff",
    shade: "yellow",
  },
  {
    name: "Peru",
    hex: "#CD853F",
    rgb: "rgb(205, 133, 63)",
    category: "extended",
    format: "name",
    id: "peru",
    shade: "brown",
  },
  {
    name: "Pink",
    hex: "#FFC0CB",
    rgb: "rgb(255, 192, 203)",
    category: "extended",
    format: "name",
    id: "pink",
    shade: "pink",
  },
  {
    name: "Plum",
    hex: "#DDA0DD",
    rgb: "rgb(221, 160, 221)",
    category: "extended",
    format: "name",
    id: "plum",
    shade: "purple, violet and magenta",
  },
  {
    name: "PowderBlue",
    hex: "#B0E0E6",
    rgb: "rgb(176, 224, 230)",
    category: "extended",
    format: "name",
    id: "powderblue",
    shade: "blue",
  },
  {
    name: "Purple",
    hex: "#800080",
    rgb: "rgb(128, 0, 128)",
    category: "extended",
    format: "name",
    id: "purple",
    shade: "purple, violet and magenta",
  },
  { name: "Red", hex: "#FF0000", rgb: "rgb(255, 0, 0)", category: "extended", format: "name", id: "red", shade: "red" },
  {
    name: "RosyBrown",
    hex: "#BC8F8F",
    rgb: "rgb(188, 143, 143)",
    category: "extended",
    format: "name",
    id: "rosybrown",
    shade: "brown",
  },
  {
    name: "RoyalBlue",
    hex: "#4169E1",
    rgb: "rgb(65, 105, 225)",
    category: "extended",
    format: "name",
    id: "royalblue",
    shade: "blue",
  },
  {
    name: "SaddleBrown",
    hex: "#8B4513",
    rgb: "rgb(139, 69, 19)",
    category: "extended",
    format: "name",
    id: "saddlebrown",
    shade: "brown",
  },
  {
    name: "Salmon",
    hex: "#FA8072",
    rgb: "rgb(250, 128, 114)",
    category: "extended",
    format: "name",
    id: "salmon",
    shade: "red",
  },
  {
    name: "SandyBrown",
    hex: "#F4A460",
    rgb: "rgb(244, 164, 96)",
    category: "extended",
    format: "name",
    id: "sandybrown",
    shade: "brown",
  },
  {
    name: "SeaGreen",
    hex: "#2E8B57",
    rgb: "rgb(46, 139, 87)",
    category: "extended",
    format: "name",
    id: "seagreen",
    shade: "green",
  },
  {
    name: "Seashell",
    hex: "#FFF5EE",
    rgb: "rgb(255, 245, 238)",
    category: "extended",
    format: "name",
    id: "seashell",
    shade: "white",
  },
  {
    name: "Sienna",
    hex: "#A0522D",
    rgb: "rgb(160, 82, 45)",
    category: "extended",
    format: "name",
    id: "sienna",
    shade: "brown",
  },
  {
    name: "Silver",
    hex: "#C0C0C0",
    rgb: "rgb(192, 192, 192)",
    category: "extended",
    format: "name",
    id: "silver",
    shade: "black and gray",
  },
  {
    name: "SkyBlue",
    hex: "#87CEEB",
    rgb: "rgb(135, 206, 235)",
    category: "extended",
    format: "name",
    id: "skyblue",
    shade: "blue",
  },
  {
    name: "SlateBlue",
    hex: "#6A5ACD",
    rgb: "rgb(106, 90, 205)",
    category: "extended",
    format: "name",
    id: "slateblue",
    shade: "purple, violet and magenta",
  },
  {
    name: "SlateGray",
    hex: "#708090",
    rgb: "rgb(112, 128, 144)",
    category: "extended",
    format: "name",
    id: "slategray",
    shade: "black and gray",
  },
  {
    name: "Snow",
    hex: "#FFFAFA",
    rgb: "rgb(255, 250, 250)",
    category: "extended",
    format: "name",
    id: "snow",
    shade: "white",
  },
  {
    name: "SpringGreen",
    hex: "#00FF7F",
    rgb: "rgb(0, 255, 127)",
    category: "extended",
    format: "name",
    id: "springgreen",
    shade: "green",
  },
  {
    name: "SteelBlue",
    hex: "#4682B4",
    rgb: "rgb(70, 130, 180)",
    category: "extended",
    format: "name",
    id: "steelblue",
    shade: "blue",
  },
  {
    name: "Tan",
    hex: "#D2B48C",
    rgb: "rgb(210, 180, 140)",
    category: "extended",
    format: "name",
    id: "tan",
    shade: "brown",
  },
  {
    name: "Teal",
    hex: "#008080",
    rgb: "rgb(0, 128, 128)",
    category: "extended",
    format: "name",
    id: "teal",
    shade: "cyan",
  },
  {
    name: "Thistle",
    hex: "#D8BFD8",
    rgb: "rgb(216, 191, 216)",
    category: "extended",
    format: "name",
    id: "thistle",
    shade: "purple, violet and magenta",
  },
  {
    name: "Tomato",
    hex: "#FF6347",
    rgb: "rgb(255, 99, 71)",
    category: "extended",
    format: "name",
    id: "tomato",
    shade: "orange",
  },
  {
    name: "Turquoise",
    hex: "#40E0D0",
    rgb: "rgb(64, 224, 208)",
    category: "extended",
    format: "name",
    id: "turquoise",
    shade: "cyan",
  },
  {
    name: "Violet",
    hex: "#EE82EE",
    rgb: "rgb(238, 130, 238)",
    category: "extended",
    format: "name",
    id: "violet",
    shade: "purple, violet and magenta",
  },
  {
    name: "Wheat",
    hex: "#F5DEB3",
    rgb: "rgb(245, 222, 179)",
    category: "extended",
    format: "name",
    id: "wheat",
    shade: "brown",
  },
  {
    name: "White",
    hex: "#FFFFFF",
    rgb: "rgb(255, 255, 255)",
    category: "extended",
    format: "name",
    id: "white",
    shade: "white",
  },
  {
    name: "WhiteSmoke",
    hex: "#F5F5F5",
    rgb: "rgb(245, 245, 245)",
    category: "extended",
    format: "name",
    id: "whitesmoke",
    shade: "white",
  },
  {
    name: "Yellow",
    hex: "#FFFF00",
    rgb: "rgb(255, 255, 0)",
    category: "extended",
    format: "name",
    id: "yellow",
    shade: "yellow",
  },
  {
    name: "YellowGreen",
    hex: "#9ACD32",
    rgb: "rgb(154, 205, 50)",
    category: "extended",
    format: "name",
    id: "yellowgreen",
    shade: "green",
  },
];
