// GENERATED by raycast/generate.sh from `rcc --help` — do not edit by hand.

export type RccCommand = {
	/** Slug, e.g. "audit-deep". */
	id: string;
	/** Argv passed to rcc, e.g. ["audit", "deep"]. */
	args: string[];
	title: string;
	description: string;
	/** Calls sudo, so rcc will raise a Touch ID prompt. Still runs inside Raycast. */
	needsRoot: boolean;
};

export const COMMANDS: RccCommand[] = [
	{
		id: "upgrade",
		args: ["upgrade"],
		title: "Upgrade",
		description: "Update packages",
		needsRoot: true,
	},
	{
		id: "apps",
		args: ["apps"],
		title: "Apps",
		description: "Update GUI apps (App Store + casks)",
		needsRoot: true,
	},
	{
		id: "audit",
		args: ["audit"],
		title: "Audit",
		description: "Security audit (quick)",
		needsRoot: true,
	},
	{
		id: "audit-deep",
		args: ["audit", "deep"],
		title: "Audit Deep",
		description: "Security audit (full)",
		needsRoot: true,
	},
	{
		id: "network",
		args: ["network"],
		title: "Network",
		description: "Network info",
		needsRoot: false,
	},
	{
		id: "wifi",
		args: ["wifi"],
		title: "Wifi",
		description: "Wi-Fi and passwords",
		needsRoot: false,
	},
	{
		id: "disk",
		args: ["disk"],
		title: "Disk",
		description: "Disk space",
		needsRoot: false,
	},
	{
		id: "memory",
		args: ["memory"],
		title: "Memory",
		description: "Memory usage",
		needsRoot: false,
	},
	{
		id: "audit-quiet",
		args: ["audit", "quiet"],
		title: "Audit Quiet",
		description: "audit --quiet",
		needsRoot: true,
	},
	{
		id: "audit-fix",
		args: ["audit", "fix"],
		title: "Audit Fix",
		description: "audit --fix",
		needsRoot: true,
	},
	{
		id: "audit-json",
		args: ["audit", "json"],
		title: "Audit Json",
		description: "audit --json",
		needsRoot: true,
	},
	{
		id: "audit-history",
		args: ["audit", "history"],
		title: "Audit History",
		description: "audit --history",
		needsRoot: true,
	},
	{
		id: "audit-watch",
		args: ["audit", "watch"],
		title: "Audit Watch",
		description: "audit --watch",
		needsRoot: true,
	},
	{
		id: "fleet",
		args: ["fleet"],
		title: "Fleet",
		description: "Audit Mac fleet via SSH",
		needsRoot: true,
	},
	{
		id: "ssh",
		args: ["ssh"],
		title: "Ssh",
		description: "SSH keys",
		needsRoot: false,
	},
	{
		id: "git",
		args: ["git"],
		title: "Git",
		description: "Git repos",
		needsRoot: false,
	},
	{
		id: "ports",
		args: ["ports"],
		title: "Ports",
		description: "Open ports",
		needsRoot: false,
	},
	{
		id: "battery",
		args: ["battery"],
		title: "Battery",
		description: "Battery health",
		needsRoot: false,
	},
	{
		id: "backup",
		args: ["backup"],
		title: "Backup",
		description: "Time Machine",
		needsRoot: false,
	},
	{
		id: "env",
		args: ["env"],
		title: "Env",
		description: "Environment",
		needsRoot: false,
	},
	{
		id: "overlap",
		args: ["overlap"],
		title: "Overlap",
		description: "PATH package-manager map",
		needsRoot: false,
	},
	{
		id: "startup",
		args: ["startup"],
		title: "Startup",
		description: "Launch agents",
		needsRoot: false,
	},
	{
		id: "trash",
		args: ["trash"],
		title: "Trash",
		description: "Trash",
		needsRoot: false,
	},
	{
		id: "fonts",
		args: ["fonts"],
		title: "Fonts",
		description: "Fonts",
		needsRoot: false,
	},
	{
		id: "history",
		args: ["history"],
		title: "History",
		description: "Shell history",
		needsRoot: false,
	},
	{
		id: "certs",
		args: ["certs"],
		title: "Certs",
		description: "SSL certificates",
		needsRoot: false,
	},
	{
		id: "docker",
		args: ["docker"],
		title: "Docker",
		description: "Docker",
		needsRoot: false,
	},
	{
		id: "xcode",
		args: ["xcode"],
		title: "Xcode",
		description: "Xcode",
		needsRoot: false,
	},
];

export function findCommand(id: string): RccCommand {
	const found = COMMANDS.find((c) => c.id === id);
	if (!found) throw new Error(`Unknown rcc command: ${id}`);
	return found;
}
