/**
 * List of programming languages extracted from GitHub's advanced code search page.
 *
 * @summary A list of programming languages.
 * @type {Array<{name: string, value: string}>}
 * @see https://github.com/search/advanced
 */
export const languages = [
  { name: "Any language", value: "" },
  // Popular
  { name: "C", value: "C" },
  { name: "C#", value: "C#" },
  { name: "C++", value: "C++" },
  { name: "CoffeeScript", value: "CoffeeScript" },
  { name: "CSS", value: "CSS" },
  { name: "Dart", value: "Dart" },
  { name: "DM", value: "DM" },
  { name: "Elixir", value: "Elixir" },
  { name: "Go", value: "Go" },
  { name: "Groovy", value: "Groovy" },
  { name: "HTML", value: "HTML" },
  { name: "Java", value: "Java" },
  { name: "JavaScript", value: "JavaScript" },
  { name: "Kotlin", value: "Kotlin" },
  { name: "Objective-C", value: "Objective-C" },
  { name: "Perl", value: "Perl" },
  { name: "PHP", value: "PHP" },
  { name: "PowerShell", value: "PowerShell" },
  { name: "Python", value: "Python" },
  { name: "Ruby", value: "Ruby" },
  { name: "Rust", value: "Rust" },
  { name: "Scala", value: "Scala" },
  { name: "Shell", value: "Shell" },
  { name: "Swift", value: "Swift" },
  { name: "TypeScript", value: "TypeScript" },
  // Anything else
  { name: "1C Enterprise", value: "1C Enterprise" },
  { name: "2-Dimensional Array", value: "2-Dimensional Array" },
  { name: "4D", value: "4D" },
  { name: "ABAP", value: "ABAP" },
  { name: "ABAP CDS", value: "ABAP CDS" },
  { name: "ABNF", value: "ABNF" },
  { name: "ActionScript", value: "ActionScript" },
  { name: "Ada", value: "Ada" },
  { name: "Adblock Filter List", value: "Adblock Filter List" },
  { name: "Adobe Font Metrics", value: "Adobe Font Metrics" },
  { name: "Agda", value: "Agda" },
  { name: "AGS Script", value: "AGS Script" },
  { name: "AIDL", value: "AIDL" },
  { name: "AL", value: "AL" },
  { name: "Alloy", value: "Alloy" },
  { name: "Alpine Abuild", value: "Alpine Abuild" },
  { name: "Altium Designer", value: "Altium Designer" },
  { name: "AMPL", value: "AMPL" },
  { name: "AngelScript", value: "AngelScript" },
  { name: "Ant Build System", value: "Ant Build System" },
  { name: "Antlers", value: "Antlers" },
  { name: "ANTLR", value: "ANTLR" },
  { name: "ApacheConf", value: "ApacheConf" },
  { name: "Apex", value: "Apex" },
  { name: "API Blueprint", value: "API Blueprint" },
  { name: "APL", value: "APL" },
  { name: "Apollo Guidance Computer", value: "Apollo Guidance Computer" },
  { name: "AppleScript", value: "AppleScript" },
  { name: "Arc", value: "Arc" },
  { name: "AsciiDoc", value: "AsciiDoc" },
  { name: "ASL", value: "ASL" },
  { name: "ASN.1", value: "ASN.1" },
  { name: "ASP.NET", value: "ASP.NET" },
  { name: "AspectJ", value: "AspectJ" },
  { name: "Assembly", value: "Assembly" },
  { name: "Astro", value: "Astro" },
  { name: "Asymptote", value: "Asymptote" },
  { name: "ATS", value: "ATS" },
  { name: "Augeas", value: "Augeas" },
  { name: "AutoHotkey", value: "AutoHotkey" },
  { name: "AutoIt", value: "AutoIt" },
  { name: "Avro IDL", value: "Avro IDL" },
  { name: "Awk", value: "Awk" },
  { name: "Ballerina", value: "Ballerina" },
  { name: "BASIC", value: "BASIC" },
  { name: "Batchfile", value: "Batchfile" },
  { name: "Beef", value: "Beef" },
  { name: "Befunge", value: "Befunge" },
  { name: "Berry", value: "Berry" },
  { name: "BibTeX", value: "BibTeX" },
  { name: "Bicep", value: "Bicep" },
  { name: "Bikeshed", value: "Bikeshed" },
  { name: "Bison", value: "Bison" },
  { name: "BitBake", value: "BitBake" },
  { name: "Blade", value: "Blade" },
  { name: "BlitzBasic", value: "BlitzBasic" },
  { name: "BlitzMax", value: "BlitzMax" },
  { name: "Bluespec", value: "Bluespec" },
  { name: "Bluespec BH", value: "Bluespec BH" },
  { name: "Boo", value: "Boo" },
  { name: "Boogie", value: "Boogie" },
  { name: "Brainfuck", value: "Brainfuck" },
  { name: "BrighterScript", value: "BrighterScript" },
  { name: "Brightscript", value: "Brightscript" },
  { name: "Browserslist", value: "Browserslist" },
  { name: "C-ObjDump", value: "C-ObjDump" },
  { name: "C2hs Haskell", value: "C2hs Haskell" },
  { name: "Cabal Config", value: "Cabal Config" },
  { name: "Cadence", value: "Cadence" },
  { name: "Cairo", value: "Cairo" },
  { name: "CameLIGO", value: "CameLIGO" },
  { name: "CAP CDS", value: "CAP CDS" },
  { name: "Cap'n Proto", value: "Cap'n Proto" },
  { name: "CartoCSS", value: "CartoCSS" },
  { name: "Ceylon", value: "Ceylon" },
  { name: "Chapel", value: "Chapel" },
  { name: "Charity", value: "Charity" },
  { name: "Checksums", value: "Checksums" },
  { name: "ChucK", value: "ChucK" },
  { name: "CIL", value: "CIL" },
  { name: "Circom", value: "Circom" },
  { name: "Cirru", value: "Cirru" },
  { name: "Clarion", value: "Clarion" },
  { name: "Clarity", value: "Clarity" },
  { name: "Classic ASP", value: "Classic ASP" },
  { name: "Clean", value: "Clean" },
  { name: "Click", value: "Click" },
  { name: "CLIPS", value: "CLIPS" },
  { name: "Clojure", value: "Clojure" },
  { name: "Closure Templates", value: "Closure Templates" },
  { name: "Cloud Firestore Security Rules", value: "Cloud Firestore Security Rules" },
  { name: "CMake", value: "CMake" },
  { name: "COBOL", value: "COBOL" },
  { name: "CODEOWNERS", value: "CODEOWNERS" },
  { name: "CodeQL", value: "CodeQL" },
  { name: "ColdFusion", value: "ColdFusion" },
  { name: "ColdFusion CFC", value: "ColdFusion CFC" },
  { name: "COLLADA", value: "COLLADA" },
  { name: "Common Lisp", value: "Common Lisp" },
  { name: "Common Workflow Language", value: "Common Workflow Language" },
  { name: "Component Pascal", value: "Component Pascal" },
  { name: "CoNLL-U", value: "CoNLL-U" },
  { name: "Cool", value: "Cool" },
  { name: "Coq", value: "Coq" },
  { name: "Cpp-ObjDump", value: "Cpp-ObjDump" },
  { name: "Creole", value: "Creole" },
  { name: "Crystal", value: "Crystal" },
  { name: "CSON", value: "CSON" },
  { name: "Csound", value: "Csound" },
  { name: "Csound Document", value: "Csound Document" },
  { name: "Csound Score", value: "Csound Score" },
  { name: "CSV", value: "CSV" },
  { name: "Cuda", value: "Cuda" },
  { name: "CUE", value: "CUE" },
  { name: "Cue Sheet", value: "Cue Sheet" },
  { name: "cURL Config", value: "cURL Config" },
  { name: "Curry", value: "Curry" },
  { name: "CWeb", value: "CWeb" },
  { name: "Cycript", value: "Cycript" },
  { name: "Cypher", value: "Cypher" },
  { name: "Cython", value: "Cython" },
  { name: "D", value: "D" },
  { name: "D-ObjDump", value: "D-ObjDump" },
  { name: "D2", value: "D2" },
  { name: "Dafny", value: "Dafny" },
  { name: "Darcs Patch", value: "Darcs Patch" },
  { name: "DataWeave", value: "DataWeave" },
  { name: "Debian Package Control File", value: "Debian Package Control File" },
  { name: "DenizenScript", value: "DenizenScript" },
  { name: "desktop", value: "desktop" },
  { name: "Dhall", value: "Dhall" },
  { name: "Diff", value: "Diff" },
  { name: "DIGITAL Command Language", value: "DIGITAL Command Language" },
  { name: "dircolors", value: "dircolors" },
  { name: "DirectX 3D File", value: "DirectX 3D File" },
  { name: "DNS Zone", value: "DNS Zone" },
  { name: "Dockerfile", value: "Dockerfile" },
  { name: "Dogescript", value: "Dogescript" },
  { name: "Dotenv", value: "Dotenv" },
  { name: "DTrace", value: "DTrace" },
  { name: "Dylan", value: "Dylan" },
  { name: "E", value: "E" },
  { name: "E-mail", value: "E-mail" },
  { name: "Eagle", value: "Eagle" },
  { name: "Earthly", value: "Earthly" },
  { name: "Easybuild", value: "Easybuild" },
  { name: "EBNF", value: "EBNF" },
  { name: "eC", value: "eC" },
  { name: "Ecere Projects", value: "Ecere Projects" },
  { name: "ECL", value: "ECL" },
  { name: "ECLiPSe", value: "ECLiPSe" },
  { name: "Ecmarkup", value: "Ecmarkup" },
  { name: "EdgeQL", value: "EdgeQL" },
  { name: "EditorConfig", value: "EditorConfig" },
  { name: "Edje Data Collection", value: "Edje Data Collection" },
  { name: "edn", value: "edn" },
  { name: "Eiffel", value: "Eiffel" },
  { name: "EJS", value: "EJS" },
  { name: "Elm", value: "Elm" },
  { name: "Elvish", value: "Elvish" },
  { name: "Elvish Transcript", value: "Elvish Transcript" },
  { name: "Emacs Lisp", value: "Emacs Lisp" },
  { name: "EmberScript", value: "EmberScript" },
  { name: "EQ", value: "EQ" },
  { name: "Erlang", value: "Erlang" },
  { name: "Euphoria", value: "Euphoria" },
  { name: "F#", value: "F#" },
  { name: "F*", value: "F*" },
  { name: "Factor", value: "Factor" },
  { name: "Fancy", value: "Fancy" },
  { name: "Fantom", value: "Fantom" },
  { name: "Faust", value: "Faust" },
  { name: "Fennel", value: "Fennel" },
  { name: "FIGlet Font", value: "FIGlet Font" },
  { name: "Filebench WML", value: "Filebench WML" },
  { name: "Filterscript", value: "Filterscript" },
  { name: "fish", value: "fish" },
  { name: "Fluent", value: "Fluent" },
  { name: "FLUX", value: "FLUX" },
  { name: "Formatted", value: "Formatted" },
  { name: "Forth", value: "Forth" },
  { name: "Fortran", value: "Fortran" },
  { name: "Fortran Free Form", value: "Fortran Free Form" },
  { name: "FreeBasic", value: "FreeBasic" },
  { name: "FreeMarker", value: "FreeMarker" },
  { name: "Frege", value: "Frege" },
  { name: "Futhark", value: "Futhark" },
  { name: "G-code", value: "G-code" },
  { name: "Game Maker Language", value: "Game Maker Language" },
  { name: "GAML", value: "GAML" },
  { name: "GAMS", value: "GAMS" },
  { name: "GAP", value: "GAP" },
  { name: "GCC Machine Description", value: "GCC Machine Description" },
  { name: "GDB", value: "GDB" },
  { name: "GDScript", value: "GDScript" },
  { name: "GEDCOM", value: "GEDCOM" },
  { name: "Gemfile.lock", value: "Gemfile.lock" },
  { name: "Gemini", value: "Gemini" },
  { name: "Genero 4gl", value: "Genero 4gl" },
  { name: "Genero per", value: "Genero per" },
  { name: "Genie", value: "Genie" },
  { name: "Genshi", value: "Genshi" },
  { name: "Gentoo Ebuild", value: "Gentoo Ebuild" },
  { name: "Gentoo Eclass", value: "Gentoo Eclass" },
  { name: "Gerber Image", value: "Gerber Image" },
  { name: "Gettext Catalog", value: "Gettext Catalog" },
  { name: "Gherkin", value: "Gherkin" },
  { name: "Git Attributes", value: "Git Attributes" },
  { name: "Git Config", value: "Git Config" },
  { name: "Git Revision List", value: "Git Revision List" },
  { name: "Gleam", value: "Gleam" },
  { name: "Glimmer JS", value: "Glimmer JS" },
  { name: "GLSL", value: "GLSL" },
  { name: "Glyph", value: "Glyph" },
  { name: "Glyph Bitmap Distribution Format", value: "Glyph Bitmap Distribution Format" },
  { name: "GN", value: "GN" },
  { name: "Gnuplot", value: "Gnuplot" },
  { name: "Go Checksums", value: "Go Checksums" },
  { name: "Go Module", value: "Go Module" },
  { name: "Go Workspace", value: "Go Workspace" },
  { name: "Godot Resource", value: "Godot Resource" },
  { name: "Golo", value: "Golo" },
  { name: "Gosu", value: "Gosu" },
  { name: "Grace", value: "Grace" },
  { name: "Gradle", value: "Gradle" },
  { name: "Gradle Kotlin DSL", value: "Gradle Kotlin DSL" },
  { name: "Grammatical Framework", value: "Grammatical Framework" },
  { name: "Graph Modeling Language", value: "Graph Modeling Language" },
  { name: "GraphQL", value: "GraphQL" },
  { name: "Graphviz (DOT)", value: "Graphviz (DOT)" },
  { name: "Groovy Server Pages", value: "Groovy Server Pages" },
  { name: "GSC", value: "GSC" },
  { name: "Hack", value: "Hack" },
  { name: "Haml", value: "Haml" },
  { name: "Handlebars", value: "Handlebars" },
  { name: "HAProxy", value: "HAProxy" },
  { name: "Harbour", value: "Harbour" },
  { name: "Haskell", value: "Haskell" },
  { name: "Haxe", value: "Haxe" },
  { name: "HCL", value: "HCL" },
  { name: "HiveQL", value: "HiveQL" },
  { name: "HLSL", value: "HLSL" },
  { name: "HOCON", value: "HOCON" },
  { name: "HolyC", value: "HolyC" },
  { name: "hoon", value: "hoon" },
  { name: "Hosts File", value: "Hosts File" },
  { name: "HTML+ECR", value: "HTML+ECR" },
  { name: "HTML+EEX", value: "HTML+EEX" },
  { name: "HTML+ERB", value: "HTML+ERB" },
  { name: "HTML+PHP", value: "HTML+PHP" },
  { name: "HTML+Razor", value: "HTML+Razor" },
  { name: "HTTP", value: "HTTP" },
  { name: "HXML", value: "HXML" },
  { name: "Hy", value: "Hy" },
  { name: "HyPhy", value: "HyPhy" },
  { name: "IDL", value: "IDL" },
  { name: "Idris", value: "Idris" },
  { name: "Ignore List", value: "Ignore List" },
  { name: "IGOR Pro", value: "IGOR Pro" },
  { name: "ImageJ Macro", value: "ImageJ Macro" },
  { name: "Imba", value: "Imba" },
  { name: "Inform 7", value: "Inform 7" },
  { name: "INI", value: "INI" },
  { name: "Ink", value: "Ink" },
  { name: "Inno Setup", value: "Inno Setup" },
  { name: "Io", value: "Io" },
  { name: "Ioke", value: "Ioke" },
  { name: "IRC log", value: "IRC log" },
  { name: "Isabelle", value: "Isabelle" },
  { name: "Isabelle ROOT", value: "Isabelle ROOT" },
  { name: "J", value: "J" },
  { name: "Janet", value: "Janet" },
  { name: "JAR Manifest", value: "JAR Manifest" },
  { name: "Jasmin", value: "Jasmin" },
  { name: "Java Properties", value: "Java Properties" },
  { name: "Java Server Pages", value: "Java Server Pages" },
  { name: "JavaScript+ERB", value: "JavaScript+ERB" },
  { name: "JCL", value: "JCL" },
  { name: "Jest Snapshot", value: "Jest Snapshot" },
  { name: "JetBrains MPS", value: "JetBrains MPS" },
  { name: "JFlex", value: "JFlex" },
  { name: "Jinja", value: "Jinja" },
  { name: "Jison", value: "Jison" },
  { name: "Jison Lex", value: "Jison Lex" },
  { name: "Jolie", value: "Jolie" },
  { name: "jq", value: "jq" },
  { name: "JSON", value: "JSON" },
  { name: "JSON with Comments", value: "JSON with Comments" },
  { name: "JSON5", value: "JSON5" },
  { name: "JSONiq", value: "JSONiq" },
  { name: "JSONLD", value: "JSONLD" },
  { name: "Jsonnet", value: "Jsonnet" },
  { name: "Julia", value: "Julia" },
  { name: "Jupyter Notebook", value: "Jupyter Notebook" },
  { name: "Just", value: "Just" },
  { name: "Kaitai Struct", value: "Kaitai Struct" },
  { name: "KakouneScript", value: "KakouneScript" },
  { name: "KerboScript", value: "KerboScript" },
  { name: "KiCad Layout", value: "KiCad Layout" },
  { name: "KiCad Legacy Layout", value: "KiCad Legacy Layout" },
  { name: "KiCad Schematic", value: "KiCad Schematic" },
  { name: "Kickstart", value: "Kickstart" },
  { name: "Kit", value: "Kit" },
  { name: "KRL", value: "KRL" },
  { name: "Kusto", value: "Kusto" },
  { name: "kvlang", value: "kvlang" },
  { name: "LabVIEW", value: "LabVIEW" },
  { name: "Lark", value: "Lark" },
  { name: "Lasso", value: "Lasso" },
  { name: "Latte", value: "Latte" },
  { name: "Lean", value: "Lean" },
  { name: "Lean 4", value: "Lean 4" },
  { name: "Less", value: "Less" },
  { name: "Lex", value: "Lex" },
  { name: "LFE", value: "LFE" },
  { name: "LigoLANG", value: "LigoLANG" },
  { name: "LilyPond", value: "LilyPond" },
  { name: "Limbo", value: "Limbo" },
  { name: "Linker Script", value: "Linker Script" },
  { name: "Linux Kernel Module", value: "Linux Kernel Module" },
  { name: "Liquid", value: "Liquid" },
  { name: "Literate Agda", value: "Literate Agda" },
  { name: "Literate CoffeeScript", value: "Literate CoffeeScript" },
  { name: "Literate Haskell", value: "Literate Haskell" },
  { name: "LiveScript", value: "LiveScript" },
  { name: "LLVM", value: "LLVM" },
  { name: "Logos", value: "Logos" },
  { name: "Logtalk", value: "Logtalk" },
  { name: "LOLCODE", value: "LOLCODE" },
  { name: "LookML", value: "LookML" },
  { name: "LoomScript", value: "LoomScript" },
  { name: "LSL", value: "LSL" },
  { name: "LTspice Symbol", value: "LTspice Symbol" },
  { name: "Lua", value: "Lua" },
  { name: "M", value: "M" },
  { name: "M4", value: "M4" },
  { name: "M4Sugar", value: "M4Sugar" },
  { name: "Macaulay2", value: "Macaulay2" },
  { name: "Makefile", value: "Makefile" },
  { name: "Mako", value: "Mako" },
  { name: "Markdown", value: "Markdown" },
  { name: "Marko", value: "Marko" },
  { name: "Mask", value: "Mask" },
  { name: "Mathematica", value: "Mathematica" },
  { name: "MATLAB", value: "MATLAB" },
  { name: "Maven POM", value: "Maven POM" },
  { name: "Max", value: "Max" },
  { name: "MAXScript", value: "MAXScript" },
  { name: "mcfunction", value: "mcfunction" },
  { name: "MDX", value: "MDX" },
  { name: "Mercury", value: "Mercury" },
  { name: "Mermaid", value: "Mermaid" },
  { name: "Meson", value: "Meson" },
  { name: "Metal", value: "Metal" },
  { name: "Microsoft Developer Studio Project", value: "Microsoft Developer Studio Project" },
  { name: "Microsoft Visual Studio Solution", value: "Microsoft Visual Studio Solution" },
  { name: "MiniD", value: "MiniD" },
  { name: "MiniYAML", value: "MiniYAML" },
  { name: "Mint", value: "Mint" },
  { name: "Mirah", value: "Mirah" },
  { name: "mIRC Script", value: "mIRC Script" },
  { name: "MLIR", value: "MLIR" },
  { name: "Modelica", value: "Modelica" },
  { name: "Modula-2", value: "Modula-2" },
  { name: "Modula-3", value: "Modula-3" },
  { name: "Module Management System", value: "Module Management System" },
  { name: "Monkey", value: "Monkey" },
  { name: "Monkey C", value: "Monkey C" },
  { name: "Moocode", value: "Moocode" },
  { name: "MoonScript", value: "MoonScript" },
  { name: "Motoko", value: "Motoko" },
  { name: "Motorola 68K Assembly", value: "Motorola 68K Assembly" },
  { name: "Move", value: "Move" },
  { name: "MQL4", value: "MQL4" },
  { name: "MQL5", value: "MQL5" },
  { name: "MTML", value: "MTML" },
  { name: "MUF", value: "MUF" },
  { name: "mupad", value: "mupad" },
  { name: "Muse", value: "Muse" },
  { name: "Mustache", value: "Mustache" },
  { name: "Myghty", value: "Myghty" },
  { name: "nanorc", value: "nanorc" },
  { name: "Nasal", value: "Nasal" },
  { name: "NASL", value: "NASL" },
  { name: "NCL", value: "NCL" },
  { name: "Nearley", value: "Nearley" },
  { name: "Nemerle", value: "Nemerle" },
  { name: "NEON", value: "NEON" },
  { name: "nesC", value: "nesC" },
  { name: "NetLinx", value: "NetLinx" },
  { name: "NetLinx+ERB", value: "NetLinx+ERB" },
  { name: "NetLogo", value: "NetLogo" },
  { name: "NewLisp", value: "NewLisp" },
  { name: "Nextflow", value: "Nextflow" },
  { name: "Nginx", value: "Nginx" },
  { name: "Nim", value: "Nim" },
  { name: "Ninja", value: "Ninja" },
  { name: "Nit", value: "Nit" },
  { name: "Nix", value: "Nix" },
  { name: "NL", value: "NL" },
  { name: "NPM Config", value: "NPM Config" },
  { name: "NSIS", value: "NSIS" },
  { name: "Nu", value: "Nu" },
  { name: "NumPy", value: "NumPy" },
  { name: "Nunjucks", value: "Nunjucks" },
  { name: "Nushell", value: "Nushell" },
  { name: "NWScript", value: "NWScript" },
  { name: "OASv2-json", value: "OASv2-json" },
  { name: "OASv2-yaml", value: "OASv2-yaml" },
  { name: "OASv3-json", value: "OASv3-json" },
  { name: "OASv3-yaml", value: "OASv3-yaml" },
  { name: "ObjDump", value: "ObjDump" },
  { name: "Object Data Instance Notation", value: "Object Data Instance Notation" },
  { name: "Objective-C++", value: "Objective-C++" },
  { name: "Objective-J", value: "Objective-J" },
  { name: "ObjectScript", value: "ObjectScript" },
  { name: "OCaml", value: "OCaml" },
  { name: "Odin", value: "Odin" },
  { name: "Omgrofl", value: "Omgrofl" },
  { name: "ooc", value: "ooc" },
  { name: "Opa", value: "Opa" },
  { name: "Opal", value: "Opal" },
  { name: "Open Policy Agent", value: "Open Policy Agent" },
  { name: "OpenAPI Specification v2", value: "OpenAPI Specification v2" },
  { name: "OpenAPI Specification v3", value: "OpenAPI Specification v3" },
  { name: "OpenCL", value: "OpenCL" },
  { name: "OpenEdge ABL", value: "OpenEdge ABL" },
  { name: "OpenQASM", value: "OpenQASM" },
  { name: "OpenRC runscript", value: "OpenRC runscript" },
  { name: "OpenSCAD", value: "OpenSCAD" },
  { name: "OpenStep Property List", value: "OpenStep Property List" },
  { name: "OpenType Feature File", value: "OpenType Feature File" },
  { name: "Option List", value: "Option List" },
  { name: "Org", value: "Org" },
  { name: "Ox", value: "Ox" },
  { name: "Oxygene", value: "Oxygene" },
  { name: "Oz", value: "Oz" },
  { name: "P4", value: "P4" },
  { name: "Pact", value: "Pact" },
  { name: "Pan", value: "Pan" },
  { name: "Papyrus", value: "Papyrus" },
  { name: "Parrot", value: "Parrot" },
  { name: "Parrot Assembly", value: "Parrot Assembly" },
  { name: "Parrot Internal Representation", value: "Parrot Internal Representation" },
  { name: "Pascal", value: "Pascal" },
  { name: "Pawn", value: "Pawn" },
  { name: "PDDL", value: "PDDL" },
  { name: "PEG.js", value: "PEG.js" },
  { name: "Pep8", value: "Pep8" },
  { name: "Pic", value: "Pic" },
  { name: "Pickle", value: "Pickle" },
  { name: "PicoLisp", value: "PicoLisp" },
  { name: "PigLatin", value: "PigLatin" },
  { name: "Pike", value: "Pike" },
  { name: "PlantUML", value: "PlantUML" },
  { name: "PLpgSQL", value: "PLpgSQL" },
  { name: "PLSQL", value: "PLSQL" },
  { name: "Pod", value: "Pod" },
  { name: "Pod 6", value: "Pod 6" },
  { name: "PogoScript", value: "PogoScript" },
  { name: "Polar", value: "Polar" },
  { name: "Pony", value: "Pony" },
  { name: "Portugol", value: "Portugol" },
  { name: "PostCSS", value: "PostCSS" },
  { name: "PostScript", value: "PostScript" },
  { name: "POV-Ray SDL", value: "POV-Ray SDL" },
  { name: "PowerBuilder", value: "PowerBuilder" },
  { name: "Praat", value: "Praat" },
  { name: "Prisma", value: "Prisma" },
  { name: "Processing", value: "Processing" },
  { name: "Procfile", value: "Procfile" },
  { name: "Proguard", value: "Proguard" },
  { name: "Prolog", value: "Prolog" },
  { name: "Promela", value: "Promela" },
  { name: "Propeller Spin", value: "Propeller Spin" },
  { name: "Protocol Buffer", value: "Protocol Buffer" },
  { name: "Protocol Buffer Text Format", value: "Protocol Buffer Text Format" },
  { name: "Public Key", value: "Public Key" },
  { name: "Pug", value: "Pug" },
  { name: "Puppet", value: "Puppet" },
  { name: "Pure Data", value: "Pure Data" },
  { name: "PureBasic", value: "PureBasic" },
  { name: "PureScript", value: "PureScript" },
  { name: "Pyret", value: "Pyret" },
  { name: "Python console", value: "Python console" },
  { name: "Python traceback", value: "Python traceback" },
  { name: "q", value: "q" },
  { name: "Q#", value: "Q#" },
  { name: "QMake", value: "QMake" },
  { name: "QML", value: "QML" },
  { name: "Qt Script", value: "Qt Script" },
  { name: "Quake", value: "Quake" },
  { name: "R", value: "R" },
  { name: "Racket", value: "Racket" },
  { name: "Ragel", value: "Ragel" },
  { name: "Raku", value: "Raku" },
  { name: "RAML", value: "RAML" },
  { name: "Rascal", value: "Rascal" },
  { name: "Raw token data", value: "Raw token data" },
  { name: "RBS", value: "RBS" },
  { name: "RDoc", value: "RDoc" },
  { name: "Readline Config", value: "Readline Config" },
  { name: "REALbasic", value: "REALbasic" },
  { name: "Reason", value: "Reason" },
  { name: "ReasonLIGO", value: "ReasonLIGO" },
  { name: "Rebol", value: "Rebol" },
  { name: "Record Jar", value: "Record Jar" },
  { name: "Red", value: "Red" },
  { name: "Redcode", value: "Redcode" },
  { name: "Redirect Rules", value: "Redirect Rules" },
  { name: "Regular Expression", value: "Regular Expression" },
  { name: "Ren'Py", value: "Ren'Py" },
  { name: "RenderScript", value: "RenderScript" },
  { name: "ReScript", value: "ReScript" },
  { name: "reStructuredText", value: "reStructuredText" },
  { name: "REXX", value: "REXX" },
  { name: "Rez", value: "Rez" },
  { name: "Rich Text Format", value: "Rich Text Format" },
  { name: "Ring", value: "Ring" },
  { name: "Riot", value: "Riot" },
  { name: "RMarkdown", value: "RMarkdown" },
  { name: "RobotFramework", value: "RobotFramework" },
  { name: "robots.txt", value: "robots.txt" },
  { name: "Roff", value: "Roff" },
  { name: "Roff Manpage", value: "Roff Manpage" },
  { name: "Rouge", value: "Rouge" },
  { name: "RouterOS Script", value: "RouterOS Script" },
  { name: "RPC", value: "RPC" },
  { name: "RPGLE", value: "RPGLE" },
  { name: "RPM Spec", value: "RPM Spec" },
  { name: "RUNOFF", value: "RUNOFF" },
  { name: "Sage", value: "Sage" },
  { name: "SaltStack", value: "SaltStack" },
  { name: "SAS", value: "SAS" },
  { name: "Sass", value: "Sass" },
  { name: "Scaml", value: "Scaml" },
  { name: "Scenic", value: "Scenic" },
  { name: "Scheme", value: "Scheme" },
  { name: "Scilab", value: "Scilab" },
  { name: "SCSS", value: "SCSS" },
  { name: "sed", value: "sed" },
  { name: "Self", value: "Self" },
  { name: "SELinux Policy", value: "SELinux Policy" },
  { name: "ShaderLab", value: "ShaderLab" },
  { name: "ShellCheck Config", value: "ShellCheck Config" },
  { name: "ShellSession", value: "ShellSession" },
  { name: "Shen", value: "Shen" },
  { name: "Sieve", value: "Sieve" },
  { name: "Simple File Verification", value: "Simple File Verification" },
  { name: "Singularity", value: "Singularity" },
  { name: "Slash", value: "Slash" },
  { name: "Slice", value: "Slice" },
  { name: "Slim", value: "Slim" },
  { name: "Smali", value: "Smali" },
  { name: "Smalltalk", value: "Smalltalk" },
  { name: "Smarty", value: "Smarty" },
  { name: "Smithy", value: "Smithy" },
  { name: "SmPL", value: "SmPL" },
  { name: "SMT", value: "SMT" },
  { name: "Snakemake", value: "Snakemake" },
  { name: "Solidity", value: "Solidity" },
  { name: "Soong", value: "Soong" },
  { name: "SourcePawn", value: "SourcePawn" },
  { name: "SPARQL", value: "SPARQL" },
  { name: "Spline Font Database", value: "Spline Font Database" },
  { name: "SQF", value: "SQF" },
  { name: "SQL", value: "SQL" },
  { name: "SQLPL", value: "SQLPL" },
  { name: "Squirrel", value: "Squirrel" },
  { name: "SRecode Template", value: "SRecode Template" },
  { name: "SSH Config", value: "SSH Config" },
  { name: "Stan", value: "Stan" },
  { name: "Standard ML", value: "Standard ML" },
  { name: "STAR", value: "STAR" },
  { name: "Starlark", value: "Starlark" },
  { name: "Stata", value: "Stata" },
  { name: "STL", value: "STL" },
  { name: "STON", value: "STON" },
  { name: "StringTemplate", value: "StringTemplate" },
  { name: "Stylus", value: "Stylus" },
  { name: "SubRip Text", value: "SubRip Text" },
  { name: "SugarSS", value: "SugarSS" },
  { name: "SuperCollider", value: "SuperCollider" },
  { name: "Svelte", value: "Svelte" },
  { name: "SVG", value: "SVG" },
  { name: "Sway", value: "Sway" },
  { name: "Sweave", value: "Sweave" },
  { name: "SWIG", value: "SWIG" },
  { name: "SystemVerilog", value: "SystemVerilog" },
  { name: "Talon", value: "Talon" },
  { name: "Tcl", value: "Tcl" },
  { name: "Tcsh", value: "Tcsh" },
  { name: "Tea", value: "Tea" },
  { name: "Terra", value: "Terra" },
  { name: "Terraform Template", value: "Terraform Template" },
  { name: "TeX", value: "TeX" },
  { name: "Texinfo", value: "Texinfo" },
  { name: "Text", value: "Text" },
  { name: "Textile", value: "Textile" },
  { name: "TextMate Properties", value: "TextMate Properties" },
  { name: "Thrift", value: "Thrift" },
  { name: "TI Program", value: "TI Program" },
  { name: "TL-Verilog", value: "TL-Verilog" },
  { name: "TLA", value: "TLA" },
  { name: "Toit", value: "Toit" },
  { name: "TOML", value: "TOML" },
  { name: "TSQL", value: "TSQL" },
  { name: "TSV", value: "TSV" },
  { name: "TSX", value: "TSX" },
  { name: "Turing", value: "Turing" },
  { name: "Turtle", value: "Turtle" },
  { name: "Twig", value: "Twig" },
  { name: "TXL", value: "TXL" },
  { name: "Type Language", value: "Type Language" },
  { name: "Typst", value: "Typst" },
  { name: "Unified Parallel C", value: "Unified Parallel C" },
  { name: "Unity3D Asset", value: "Unity3D Asset" },
  { name: "Unix Assembly", value: "Unix Assembly" },
  { name: "Uno", value: "Uno" },
  { name: "UnrealScript", value: "UnrealScript" },
  { name: "UrWeb", value: "UrWeb" },
  { name: "V", value: "V" },
  { name: "Vala", value: "Vala" },
  { name: "Valve Data Format", value: "Valve Data Format" },
  { name: "VBA", value: "VBA" },
  { name: "VBScript", value: "VBScript" },
  { name: "VCL", value: "VCL" },
  { name: "Velocity Template Language", value: "Velocity Template Language" },
  { name: "Verilog", value: "Verilog" },
  { name: "VHDL", value: "VHDL" },
  { name: "Vim Help File", value: "Vim Help File" },
  { name: "Vim Script", value: "Vim Script" },
  { name: "Vim Snippet", value: "Vim Snippet" },
  { name: "Visual Basic .NET", value: "Visual Basic .NET" },
  { name: "Visual Basic 6.0", value: "Visual Basic 6.0" },
  { name: "Volt", value: "Volt" },
  { name: "Vue", value: "Vue" },
  { name: "Vyper", value: "Vyper" },
  { name: "Wavefront Material", value: "Wavefront Material" },
  { name: "Wavefront Object", value: "Wavefront Object" },
  { name: "WDL", value: "WDL" },
  { name: "Web Ontology Language", value: "Web Ontology Language" },
  { name: "WebAssembly", value: "WebAssembly" },
  { name: "WebAssembly Interface Type", value: "WebAssembly Interface Type" },
  { name: "WebIDL", value: "WebIDL" },
  { name: "WebVTT", value: "WebVTT" },
  { name: "Wget Config", value: "Wget Config" },
  { name: "WGSL", value: "WGSL" },
  { name: "Whiley", value: "Whiley" },
  { name: "Wikitext", value: "Wikitext" },
  { name: "Win32 Message File", value: "Win32 Message File" },
  { name: "Windows Registry Entries", value: "Windows Registry Entries" },
  { name: "wisp", value: "wisp" },
  { name: "Witcher Script", value: "Witcher Script" },
  { name: "Wollok", value: "Wollok" },
  { name: "World of Warcraft Addon Data", value: "World of Warcraft Addon Data" },
  { name: "Wren", value: "Wren" },
  { name: "X BitMap", value: "X BitMap" },
  { name: "X Font Directory Index", value: "X Font Directory Index" },
  { name: "X PixMap", value: "X PixMap" },
  { name: "X10", value: "X10" },
  { name: "xBase", value: "xBase" },
  { name: "XC", value: "XC" },
  { name: "XCompose", value: "XCompose" },
  { name: "XML", value: "XML" },
  { name: "XML Property List", value: "XML Property List" },
  { name: "Xojo", value: "Xojo" },
  { name: "Xonsh", value: "Xonsh" },
  { name: "XPages", value: "XPages" },
  { name: "XProc", value: "XProc" },
  { name: "XQuery", value: "XQuery" },
  { name: "XS", value: "XS" },
  { name: "XSLT", value: "XSLT" },
  { name: "Xtend", value: "Xtend" },
  { name: "Yacc", value: "Yacc" },
  { name: "YAML", value: "YAML" },
  { name: "YANG", value: "YANG" },
  { name: "YARA", value: "YARA" },
  { name: "YASnippet", value: "YASnippet" },
  { name: "Yul", value: "Yul" },
  { name: "ZAP", value: "ZAP" },
  { name: "Zeek", value: "Zeek" },
  { name: "ZenScript", value: "ZenScript" },
  { name: "Zephir", value: "Zephir" },
  { name: "Zig", value: "Zig" },
  { name: "ZIL", value: "ZIL" },
  { name: "Zimpl", value: "Zimpl" },
];
