#!/usr/bin/env tsx
/**
 * Generate src/lib/skill-content.generated.ts from skills/<name>/SKILL.md.
 *
 * Raycast's `ray build` bundles src/ and assets/ but not arbitrary repo-root
 * directories, so skill content must be embedded into the JS bundle at build
 * time. This script keeps the bundle in sync with the human-readable
 * `skills/` directory (which doubles as the source-of-truth for Claude Code /
 * other MCP clients that read SKILL.md directly).
 *
 * Run with `npm run sync-skills` (which calls this after fetching upstream) or
 * directly: `tsx scripts/embed-skills.ts`.
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(__dirname, "..");
const SKILLS_DIR = join(ROOT, "skills");
const OUT_FILE = join(ROOT, "src", "lib", "skill-content.generated.ts");

interface SkillFile {
  name: string;
  raw: string;
}

function listSkillFiles(): SkillFile[] {
  const out: SkillFile[] = [];
  for (const entry of readdirSync(SKILLS_DIR)) {
    const dir = join(SKILLS_DIR, entry);
    let isDir = false;
    try {
      isDir = statSync(dir).isDirectory();
    } catch {
      continue;
    }
    if (!isDir) continue;
    const skillPath = join(dir, "SKILL.md");
    try {
      const raw = readFileSync(skillPath, "utf8");
      out.push({ name: entry, raw });
    } catch {
      // Directory without SKILL.md — skip.
    }
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

function escape(content: string): string {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function generate(skills: SkillFile[]): string {
  const entries = skills
    .map((s) => `  ${JSON.stringify(s.name)}: \`${escape(s.raw)}\``)
    .join(",\n");
  return `// AUTO-GENERATED by scripts/embed-skills.ts — do not edit by hand.
// Regenerate after editing skills/*/SKILL.md:  npm run sync-skills

export const SKILL_FILES: Record<string, string> = {
${entries}
};
`;
}

const skills = listSkillFiles();
writeFileSync(OUT_FILE, generate(skills));
console.log(`Embedded ${skills.length} skills → ${OUT_FILE}`);
