import { Clipboard, showHUD, closeMainWindow } from "@raycast/api";

const commitMessages = [
  "¯\\_(ツ)_/¯",
  "Get that shit outta my master.",
  "#GrammarNazi",
  "$(init 0)",
  "$(rm -rvf .)",
  "(O.o)",
  "Bunny approves these changes.",
  "(c) Microsoft 1988",
  "--help",
  "-m \\'So I hear you like commits ...\\'",
  ".",
  "...",
  "/sigh",
  "50/50",
  "640K ought to be enough for anybody",
  "8==========D",
  ":(:(",
  ":q!",
  "??! what the ...",
  "[FIX] asdf",
  "A fix I believe, not like I tested or anything",
  "A full commitment's what I'm thinking of",
  "A long time ago, in a galaxy far far away...",
  "A tale of Dragons, Heroes and Legends...",
  "ALL SORTS OF THINGS",
  "Abandon all hope, ye who enter here.",
  "Actual final build before release",
  "Add Sandbox",
  "Added a banner to the default admin page. Please have mercy on me =(",
  "Added another dependency",
  "Added missing file in previous commit",
  "Added some NullPointerExceptions - Happy easter, you bastards! :D",
  "Added translation.",
  "All your codebase are belong to us.",
  "And a commit that I don't know the reason of...",
  "And if you ask me how I'm feeling",
  "And if thou'rt unwilling, then force I'll employ",
  "Another bug bites the dust",
  "Another commit to keep my CAN streak going.",
  "Apparently works-for-me is a crappy excuse.",
  "Argh! About to give up :(",
  "Arrrrgggg",
  "At times like this I wish I was a Garbage Man.",
  "Automate Accounting",
  "Batman! (this commit has no parents)",
  "Become a programmer, they said. It'll be fun, they said.",
  "Best commit ever",
  "Bit Bucket is down. What should I do now?",
  "Blaming regex.",
  "By works, I meant 'doesnt work'.  Works now..",
  "COMMIT ALL THE FILES!",
  "Can someone review this commit, please ?",
  "Check next commit for message.",
  "Chuck Norris Emailed Me This Patch... I'm Not Going To Question It",
  "Code was clean until manager requested to fuck it up",
  "Commit committed",
  "Commit committed....",
  "Committed some changes",
  "Committing fixes in the dark, seriously, who killed my power!?",
  "Committing in accordance with the prophecy.",
  "Completed with no bugs...",
  "Continued development...",
  "Copy pasta fail. still had a instead of a",
  "Copy-paste to fix previous copy-paste",
  "Corrected mistakes",
  "Crap. Tonight is raid night and I am already late.",
  "DEAL WITH IT",
  "DNS_PROBE_FINISHED_NXDOMAIN",
  "Deleted API file",
  "Derp",
  "Derp search/replace fuckup",
  "Derp, asset redirection in dev mode",
  "Derp. Fix missing constant post rename",
  "Derpy hooves",
  "Do things better, faster, stronger",
  "Does anyone read this? I'll be at the coffee shop accross the street.",
  "Does not work.",
  "Does this work",
  "Don't Ask Me, I Have No Idea Why This Works Either",
  "Don't push this commit",
  "Don't tell me you're too blind to see",
  "Done, to whoever merges this, good luck.",
  "Don’t even try to refactor it.",
  "Don’t mess with Voodoo",
  "Duh",
  "Easteregg",
  "Either Hot Shit or Total Bollocks",
  "Errare humanum est.",
  "FONDLED THE CODE",
  "FOR REAL.",
  "FUCKING XUPPERNAMEX",
  "Feed. You. Stuff. No time.",
  "Final commit, ready for tagging",
  "Fingers crossed!",
  "Finished fondling.",
  "First Blood",
  "Fix PC Load Letter Error",
  "Fix all errors, all errors on the WORLD!!!!",
  "Fix edge, single client, error case",
  "Fix hard-coded [object Object] string (thanks!)",
  "Fix my stupidness",
  "Fix the fixes",
  "Fixed Bug",
  "Fixed a bug cause XNAMEX said to",
  "Fixed a bug in NoteLineCount... not seriously...",
  "Fixed a little bug...",
  "Fixed compilation errors",
  "Fixed errors",
  "Fixed everything.",
  "Fixed mispeling",
  "Fixed so the code compiles",
  "Fixed some shit",
  "Fixed the build.",
  "Fixed the fuck out of #XNUMX!",
  "Fixed unnecessary bug.",
  "Fixed what was broken.",
  "Fixing XNAMEX's bug.",
  "Fixing XNAMEX's bugs.",
  "For great justice.",
  "For real, this time.",
  "For the sake of my sanity, just ignore this...",
  "For the statistics only",
  "Friday 5pm",
  "Fuck it, YOLO!",
  "Fucking egotistical bastard. adds expandtab to vimrc",
  "Fucking submodule bull shit",
  "Fucking templates.",
  "Future self, please forgive me and don't hit me with the baseball bat again!",
  "GIT :/",
  "General commit (no IDs open) - Modifications for bad implementations",
  "Git wants e to commit, I want to sleep. Take me sweet void.",
  "Give me a break, it's 2am.  But it works now.",
  "Glue. Match sticks. Paper. Build script!",
  "Gotta make you understand",
  "Gross hack because XNAMEX doesn't know how to code",
  "Handled a particular error.",
  "Haiyaa",
  "Here be Dragons",
  "Herp derp I left the debug in there and forgot to reset errors.",
  "Herpderp, shoulda check if it does really compile.",
  "Herping the derp",
  "Herping the derp derp (silly scoping error)",
  "Herping the fucking derp right here and now.",
  "Herpy dooves.",
  "Hide those navs, boi!",
  "Hiding API key hahaha",
  "I CAN HAZ COMMENTZ.",
  "I CAN HAZ PYTHON, I CAN HAZ INDENTS",
  "I __ a word",
  "I already said I was sorry",
  "I am Root. We are Root.",
  "I am Spartacus",
  "I am even stupider than I thought",
  "I am sorry",
  "I am the greatest javascript developer in the world.",
  "I can't believe it took so long to fix this.",
  "I cannot believe that it took this long to write a test for this.",
  "I did it for the lulz!",
  "I don't believe it",
  "I don't get paid enough for this shit.",
  "I don't give a damn 'bout my reputation",
  "I don't know what the hell I was thinking.",
  "I don't know what these changes are supposed to accomplish but somebody told me to make them.",
  "I don't know why. Just move on.",
  "I dont know what I am doing",
  "I expected something different.",
  "I forgot to commit... So here you go.",
  "I had a cup of tea and now it's fixed",
  "I hate this fucking language.",
  "I have no idea what I'm doing here.",
  "I honestly wish I could remember what was going on here...",
  "I immediately regret this commit.",
  "I just evaluated random code in my console",
  "I just wanna tell you how I'm feeling",
  "I know what I am doing. Trust me.",
  "I know, I know, this is not how I’m supposed to do it, but I can't think of something better.",
  "I made leetle mistake",
  "I must enjoy torturing myself",
  "I must have been drunk.",
  "I must sleep... it's working... in just three hours...",
  "I really should've committed this when I finished it...",
  "I should get a raise for this.",
  "I should have had a V8 this morning.",
  "I think now it works",
  "I transformed a bug into a feature. Once you learn how, you'll never forget it",
  "I understand that it's an antipattern, but it's convenient.",
  "I was told to leave it alone, but I have this thing called OCD, you see",
  "I was wrong...",
  "I will not apologize for art.",
  "I will run 'terraform fmt' before committing.",
  "I would rather be playing SC2.",
  "I'M PUSHING.",
  "I'll explain this when I'm sober .. or revert it",
  "I'll explain when you're older!",
  "I'll mention this again, if you're git-blaming this, don't come slap me personally. This code straight ported from another project and we WILL refactor this in the future. This is a temporary solution. OK I guess you can slap me for porting this as is, but still.",
  "I'm guessing this may start causing us problems either soon or never.",
  "I'm human",
  "I'm hungry",
  "I'm just a grunt. Don't blame me for this awful PoS.",
  "I'm sorry.",
  "I'm too foo for this bar",
  "I'm too old for this shit!",
  "I'm totally adding this to epic win. +300",
  "ID:10T Error",
  "IEize",
  "If it's hacky and you know it clap you hands (clap clap)!",
  "If it's stupid and it works, it ain't stupid",
  "Improvements",
  "Improving the fix",
  "Insert Commit Message Here",
  "Inside we both know what's been going on",
  "Is there an achievement for this?",
  "Is there an award for this?",
  "Issue #XNUM10X is now Issue #XNUM30X",
  "It Compiles! 50 Points For Gryffindor.",
  "It compiles! Ship it!",
  "It fucking compiles \\:D/",
  "It only compiles every XNUM2,5X tries... good luck.",
  "It was the best of times, it was the worst of times",
  "It worked for me...",
  "It works on my computer",
  "It works!",
  "It'd be nice if type errors caused the compiler to issue a type error",
  "It's 2016; why are we using ColdFusion?!",
  "It's Working!",
  "It's getting hard to keep up with the crap I've trashed",
  "It's possible! you can turn a 50-line code chunk into just 3 lines. Here's how",
  "It's secret!",
  "It's time to go home",
  "Just committing so I can go home",
  "Just stop reading these for a while, ok..",
  "LAST time, XNAMEX, /dev/urandom IS NOT a variable name generator...",
  "LOL!",
  "LOTS of changes. period",
  "Landed.",
  "Last time I said it works? I was kidding.  Try this.",
  "Locating the required gigapixels to render...",
  "Lock S-foils in attack position",
  "Love coding? here's the secret reason why",
  "Low On Caffeine, Please Forgive Coding Style",
  "MOAR BIFURCATION",
  "Made it to compile...",
  "Major fixup.",
  "Make Sure You Are Square With Your God Before Trying To Merge This",
  "Make that it works in 90% of the cases.  3:30.",
  "Merge pull my finger request",
  "Merge pull request #67 from Lazersmoke/fix-andys-shit Fix andys shit",
  "Merging 'WIP: Do Not Merge This Branch' Into Master",
  "Merging the merge",
  "Minor updates",
  "Misc. fixes",
  "Mongo.db was empty, filled now with good stuff",
  "More ignore",
  "Moved something to somewhere... goodnight...",
  "My bad",
  "My boss forced me to build this feature... Pure shit.",
  "NOJIRA: No cry",
  "NSA backdoor - ignore",
  "Never Run This Commit As Root",
  "Never before had a small typo like this one caused so much damage.",
  "Never gonna give you up",
  "Never gonna give, never gonna give",
  "Never gonna let you down",
  "Never gonna make you cry",
  "Never gonna run around and desert you",
  "Never gonna say goodbye",
  "Never gonna tell a lie and hurt you",
  "Next time someone asks you how to fix an infinite loop, remember this commit",
  "Nitpicking about alphabetizing methods, minor OCD thing",
  "No changes after this point.",
  "No changes made",
  "No time to commit.. My people need me!",
  "Nobody had ever created a function like this one before.",
  "Not one conflict, today was a good day.",
  "Not sure why",
  "Nothing to see here, move along",
  "Now added delete for real",
  "Now it's all microservices, I hope the fad persists.",
  "Now we tell you your browser sucks in your native tongue.",
  "Obligatory placeholder commit message",
  "Oh my god what year is it?!",
  "Oh no",
  "Ok",
  "Ok, 5am, it works.  For real.",
  "One does not simply merge into master",
  "One little whitespace gets its very own commit! Oh, life is so erratic!",
  "One more time, but with feeling.",
  "Only Tom Cruise knows why.",
  "Out for vacation... DONT YOU DARE TO CALL ME.",
  "PEBKAC",
  "Peopleware Chapter 8: You Never Get Anything Done around Here between 9 and 5.",
  "Pig",
  "Pipeline goes brrrrrrr",
  "Please enter the commit message for your changes. Lines starting with '#' will be ignored, and an empty message aborts the commit.",
  "Please forgive me",
  "Please no changes this time.",
  "Please our Lord and Savior the Great Linter.",
  "Popping stash",
  "Programming the flux capacitor",
  "Push poorly written test can down the road another ten years",
  "Put everything in its right place",
  "QuickFix.",
  "REALLY FUCKING FIXED",
  "Refactor factories, revisit visitors",
  "Refactored configuration.",
  "Reinventing the wheel. Again.",
  "Removed code.",
  "Removed test case since code didn't pass QA",
  "Removed the 2gb .hprof file from git history",
  "Removing unecessary stuff",
  "Replace all whitespaces with tabs.",
  "Reset error count between rows. herpderp",
  "Reticulating splines...",
  "Revert fuckup.",
  "Revert git please work",
  "Revert just testing, remember to revert",
  "Revert this commit",
  "Rush B!",
  "SEXY RUSSIAN CODES WAITING FOR YOU TO CALL",
  "SHIT ===> GOLD",
  "SOAP is a piece of shit",
  "Saint Pipeline, please give me the green light",
  "Same as last commit with changes",
  "See last commit",
  "Shit code!",
  "Shovelling coal into the server...",
  "So my boss wanted this button ...",
  "Some bugs fixed",
  "Some shit.",
  "Somebody set up us the bomb.",
  "Something fixed",
  "Spinning up the hamster...",
  "Still can't get this right...",
  "Stuff",
  "Switched off unit test XNUM15X because the build had to go out now and there was no time to fix it properly.",
  "TDD: 1, Me: 0",
  "TODO: Fix later",
  "TODO: Replace placeholder code",
  "TODO: Replace stubs",
  "TODO: Tell someone to implement this",
  "TODO: write meaningful commit message",
  "Test commit. Please ignore",
  "Testing in progress ;)",
  "Testing the test",
  "That last commit message about silly mistakes pales in comparision to this one",
  "That's just how I roll",
  "The dog is eating my code",
  "The last time I tried this the monkey didn't survive. Let's hope it works better this time.",
  "The same thing we do every night, Pinky - try to take over the world!",
  "The universe is possible",
  "They came from... Behind",
  "Things went wrong...",
  "This Is Why We Don't Push To Production On Fridays",
  "This branch is so dirty, even your mom can't clean it.",
  "This bug has driven lots of coders completely mad. You won't believe how it ended up being fixed",
  "This bunny should be killed.",
  "This changes nothing, don't look",
  "This commit is a lie",
  "This is a basic implementation that works.",
  "This is my code. My code is amazing.",
  "This is not a commit",
  "This is not the commit message you are looking for",
  "This is supposed to crash",
  "This is the last time we let XNAMEX commit ascii porn in the comments.",
  "This is where it all begins...",
  "This is why git rebase is a horrible horrible thing.",
  "This is why the cat shouldn't sit on my keyboard.",
  "This really should not take 19 minutes to build.",
  "This should work until december 2013.",
  "This solves it.",
  "This was the most stupid bug in the world, fixed in the smartest way ever",
  "This will definitely break in 20XNUM20,89X (TODO)",
  "To be honest, I do not quite remember everything I changed here today. But it is all good, I tell ya.",
  "To those I leave behind, good luck!",
  "Todo!!!",
  "Too lazy to write descriptive message",
  "Too tired to write descriptive message",
  "Transpiled mainframe.",
  "Trust me, I'm an engineer!... What the f*ck did just happened here?",
  "Trust me, it's not badly written. It's just way above your head.",
  "Trying to fake a conflict",
  "Ugh. Bad rebase.",
  "Undoing last comming",
  "Update .gitignore",
  "Update commit_messages.txt",
  "Updated",
  "Updated build targets.",
  "Updated framework to the lattest version",
  "Use a real JS construct, WTF knows why this works in chromium.",
  "Useful text",
  "Version control is awful",
  "WHO THE FUCK CAME UP WITH MAKE?",
  "WIP, always",
  "WIPTF",
  "WTF is this.",
  "We Had To Use Dark Magic To Make This Work",
  "We know the game and we're gonna play it",
  "We should delete this crap before shipping.",
  "We should get someone from Purdue to do this. They are the boilerplaters.",
  "We'll figure it out on Monday",
  "We're no strangers to love",
  "We've known each other for so long",
  "Well the book was obviously wrong.",
  "Well, it's doing something.",
  "What happens in vegas stays in vegas",
  "Whatever will be, will be 8{",
  "Whatever.",
  "Whee, good night.",
  "Whee.",
  "Who Let the Bugs Out??",
  "Who has two thumbs and remembers the rudiments of his linear algebra courses?  Apparently, this guy.",
  "Who knows WTF?!",
  "Who knows...",
  "Why The Fuck?",
  "Working on WIP",
  "Working on tests (haha)",
  "Wubbalubbadubdub!",
  "XNAMEX broke the regex, lame",
  "XNAMEX made me do it",
  "XNAMEX rebase plx?",
  "XNAMEX sucks",
  "XUPPERNAMEX SUCKS",
  "XUPPERNAMEX, WE WENT OVER THIS. C++ IO SUCKS.",
  "XUPPERNAMEX, WE WENT OVER THIS. EXPANDTAB.",
  "Yep, XNAMEX was right on this one.",
  "Yes, I was being sarcastic.",
  "You can't see it, but I'm making a very angry face right now",
  "You know the rules and so do I",
  "You should have trusted me.",
  "You wouldn't get this from any other guy",
  "Your commit is writing checks your merge can't cash.",
  "Your heart's been aching but you're too shy to say it",
  "[Insert your commit message here. Be sure to make it descriptive.]",
  "[no message]",
  "[skip ci] I'll fix the build monday",
  "_",
  "a few bits tried to escape, but we caught them",
  "a lot of shit",
  "accidental commit",
  "add actual words",
  "add dirty scripts from the dark side of the universe",
  "added code",
  "added message",
  "added security.",
  "added some filthy stuff",
  "added super-widget 2.0.",
  "after of this commit remember do a git reset hard",
  "ajax-loader hotness, oh yeah",
  "and a comma",
  "and so the crazy refactoring process sees the sunlight after some months in the dark!",
  "another big bag of changes",
  "apparently i did something…",
  "arrgghh... damn this thing for not working.",
  "arrrggghhhhh fixed!",
  "asdfasdfasdfasdfasdfasdfadsf",
  "assorted changes",
  "bad things happen when you forget about that one little change you made ages ago",
  "bara bra grejjor",
  "better code",
  "better grepping",
  "better ignores",
  "betterer code",
  "bifurcation",
  "bla",
  "breathe, =, breathe",
  "buenas those-things.",
  "bug fix",
  "bugger",
  "bump to 0.0.3-dev:wq",
  "bumping poms",
  "c&p fail",
  "changed things...",
  "changes",
  "ci test",
  "clarify further the brokenness of C++. why the fuck are we using C++?",
  "commented out failing tests",
  "commit",
  "copy and paste is not a design pattern",
  "de-misunderestimating",
  "debug line test",
  "debug suff",
  "debugo",
  "derp, helper method rename",
  "derpherp",
  "diaaaaaazeeeeeeeeeepam",
  "did everything",
  "dirty hack, have a better idea ?",
  "does it work? maybe. will I check? no.",
  "doh.",
  "done. going to bed now.",
  "dope",
  "download half the damn internet to parse a pdf",
  "enabled ultra instinct",
  "epic",
  "eppic fail XNAMEX",
  "extra debug for stuff module",
  "f",
  "fail",
  "features",
  "ffs",
  "final commit.",
  "first blush",
  "fix",
  "fix /sigh",
  "fix bug, for realz",
  "fix some fucking errors",
  "fix tpyo",
  "fixed conflicts (LOL merge -s ours; push -f)",
  "fixed errors in the previous commit",
  "fixed mistaken bug",
  "fixed shit that havent been fixed in last commit",
  "fixed some minor stuff, might need some additional work.",
  "fix that damn sign!!!",
  "fixed the israeli-palestinian conflict",
  "fixes",
  "fixing project shit",
  "foo",
  "forgot a contact page woops haha",
  "forgot to save that file",
  "forgot we're not using a smart language",
  "formatted all",
  "freemasonry",
  "fuckup.",
  "gave up and used tables.",
  "giggle.",
  "git + ipynb = :(",
  "git please work",
  "git stash *",
  "god help us all",
  "grmbl",
  "grrrr",
  "hacky sack",
  "haha yes it works now",
  "happy monday _ bleh _",
  "harharhar",
  "he knows.",
  "herpderp",
  "herpderp (redux)",
  "hey, look over there!",
  "hey, what's that over there?!",
  "hmmm",
  "holy shit it's functional",
  "hoo boy",
  "hopefully going to get a successful build got damn it",
  "i dunno, maybe this works",
  "i hid an easter egg in the code. can you find it?",
  "i need therapy",
  "i think i fixed a bug...",
  "if you're not using et, fuck off",
  "implemented missing semicolon",
  "improved function",
  "include shit",
  "increased loading time by a bit",
  "it is hump day _^_",
  "it's friday",
  "jobs... steve jobs",
  "just checking if git is working properly...",
  "just shoot me",
  "just trolling the repo",
  "last hope failed, maybe now",
  "last minute fixes.",
  "less french words",
  "lets drink beer",
  "lol",
  "lol digg",
  "lolwhat?",
  "lots and lots of changes",
  "lots of changes after a lot of time",
  "magic, have no clue but it works",
  "making code less cancer",
  "making this thing actually usable.",
  "marks",
  "mergeconflix is the new hottest Gaul on the block",
  "mergederp",
  "minor changes",
  "more debug... who overwrote!",
  "more fixes",
  "more ignored words",
  "more ignores",
  "more stuff",
  "move your body every every body",
  "need another beer",
  "needs more cow bell",
  "omg what have I done?",
  "omgsosorry",
  "oops",
  "oops - thought I got that one.",
  "oops!",
  "oops, forgot to add the file",
  "oopsie B|",
  "pam anderson is going to love me.",
  "pay no attention to the man behind the curtain",
  "pep8 - cause I fell like doing a barrel roll",
  "pep8 fixer",
  "perfect...",
  "permanent hack, do not revert",
  "pgsql is being a pain",
  "pgsql is more strict, increase the hackiness up to 11",
  "pointless limitation",
  "pr is failing but merging anyways, because I am an admin",
  "project lead is allergic to changes...",
  "put code that worked where the code that didn't used to be",
  "rats",
  "really ignore ignored worsd",
  "refuckulated the carbonator",
  "remove certain things and added stuff",
  "remove debug, all good",
  "removed echo and die statements, lolz.",
  "removed tests since i can't make them green",
  "removing unit tests",
  "restored deleted entities just to be sure",
  "s/import/include/",
  "should get thru ci now",
  "should work I guess...",
  "should work now.",
  "small is a real HTML tag, who knew.",
  "some brief changes",
  "some stuff working haha",
  "somebody keeps erasing my changes.",
  "someday I gonna kill someone for this shit...",
  "someone fails and it isn't me",
  "sometimes you just herp the derp so hard it herpderps",
  "speling is difikult",
  "squash me",
  "starting the service is always better",
  "still trying to render a damn cube",
  "stopped caring XNUM8,23X commits ago",
  "stuff",
  "syntax",
  "tagging release w.t.f.",
  "that coulda been bad",
  "that's all folks",
  "the magic is real",
  "these confounded tests drive me nuts",
  "these guys are flipped",
  "things occurred",
  "third time's a charm",
  "this doesn't really make things faster, but I tried",
  "this is Spartaaaaaaaa",
  "this is how we generate our shit.",
  "this is my quickfix branch and i will use to do my quickfixes",
  "this is why docs are important",
  "this should fix it",
  "tl;dr",
  "totally more readable",
  "touched...",
  "try our sister game minceraft!",
  "trying to do something right!",
  "tunning",
  "typo",
  "uhhhhhh",
  "unh",
  "unionfind is no longer being molested.",
  "various changes",
  "well crap.",
  "what the hell happened here",
  "what is estonia up to now ...",
  "whatthecommit.com’s server IP address could not be found.",
  "who has two thumbs and is a genius? not this guy!",
  "who hurt you",
  "whooooooooooooooooooooooooooo",
  "why is everything broken",
  "wip",
  "woa!! this one was really HARD!",
  "work in progress",
  "workaround for ant being a pile of fail",
  "wrapping should work properly. Probably.",
  "yet another quality commit",
  "yo recipes",
  "yolo push",
  "you do wanna make me cry and i wanna say goodbye",
  "- Temporary commit.",
];

export default async function Command() {
  await Clipboard.copy(commitMessages[Math.floor(Math.random() * commitMessages.length)]);
  await closeMainWindow({ clearRootSearch: true });
  await showHUD("Random message copied!");
}
