daysUntilStale: 50
daysUntilClose: 10
exemptLabels:
  - api
  - documentation
  - dev tools
  - app
staleLabel: wontfix
markComment: >
  This issue/pull request has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs in the next 7 days to
  keep our backlog clean. Thanks for your contributions.
closeComment: false
