"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.enablePFBlocking = enablePFBlocking;
exports.disablePFBlocking = disablePFBlocking;
exports.isPFBlockingActive = isPFBlockingActive;
const child_process_1 = require("child_process");
const util_1 = require("util");
const fs = __importStar(require("fs/promises"));
const biometricAuth_1 = require("./biometricAuth");
const execAsync = (0, util_1.promisify)(child_process_1.exec);
const PF_ANCHOR_NAME = "com.webblocker.blocking";
const PF_RULES_FILE = "/tmp/webblocker.pf.rules";
const PF_CONF = "/etc/pf.conf";
function extractDomain(input) {
    let domain = input.toLowerCase().trim();
    domain = domain.replace(/^[a-z]+:\/\//, "");
    domain = domain.split("/")[0];
    domain = domain.split("?")[0];
    domain = domain.split("#")[0];
    domain = domain.split(":")[0];
    return domain;
}
async function generatePFRules(domains) {
    const expandedDomains = [];
    domains.forEach((domain) => {
        const cleanDomain = extractDomain(domain);
        if (!cleanDomain)
            return;
        expandedDomains.push(cleanDomain);
        if (!cleanDomain.startsWith("www.")) {
            expandedDomains.push(`www.${cleanDomain}`);
        }
        else {
            expandedDomains.push(cleanDomain.replace(/^www\./, ""));
        }
    });
    const uniqueDomains = Array.from(new Set(expandedDomains));
    let rules = `# WebBlocker PF Rules
# Generated by Raycast WebBlocker Extension
# Anchor: ${PF_ANCHOR_NAME}

# Block outgoing connections to blocked domains
`;
    rules += `table <webblocker_blocked> persist\n\n`;
    rules += `block drop out quick from any to <webblocker_blocked>\n`;
    rules += `block drop in quick from <webblocker_blocked> to any\n\n`;
    rules += `# Blocked domains: ${uniqueDomains.join(", ")}\n`;
    return rules;
}
async function resolveDomains(domains) {
    const ips = new Set();
    for (const domain of domains) {
        try {
            const { stdout } = await execAsync(`dig +short ${domain} A ${domain} AAAA 2>/dev/null || true`);
            const resolvedIPs = stdout.split("\n").filter((line) => {
                const trimmed = line.trim();
                return (trimmed &&
                    !trimmed.endsWith(".") &&
                    (trimmed.match(/^\d+\.\d+\.\d+\.\d+$/) ||
                        trimmed.match(/^[0-9a-f:]+$/i)));
            });
            resolvedIPs.forEach((ip) => ips.add(ip));
        }
        catch (error) {
            console.error(`Failed to resolve ${domain}:`, error);
        }
    }
    return Array.from(ips);
}
async function isPFEnabled() {
    try {
        const { stdout } = await execAsync("sudo pfctl -s info 2>/dev/null || true");
        return stdout.includes("Status: Enabled");
    }
    catch {
        return false;
    }
}
async function enablePFBlocking(domains) {
    if (!domains || domains.length === 0) {
        return {
            success: false,
            message: "No domains provided to block",
        };
    }
    try {
        console.log(`🔥 Enabling PF firewall blocking for ${domains.length} domains...`);
        console.log("🔍 Resolving domains to IP addresses...");
        const expandedDomains = [];
        domains.forEach((domain) => {
            const cleanDomain = extractDomain(domain);
            if (cleanDomain) {
                expandedDomains.push(cleanDomain);
                if (!cleanDomain.startsWith("www.")) {
                    expandedDomains.push(`www.${cleanDomain}`);
                }
            }
        });
        const ips = await resolveDomains(expandedDomains);
        console.log(`✅ Resolved ${ips.length} IP addresses`);
        const rules = await generatePFRules(domains);
        await fs.writeFile(PF_RULES_FILE, rules);
        const scriptContent = `#!/bin/bash
set +e

echo "🔥 Setting up PF firewall blocking..."

# Check if PF anchor already exists in pf.conf
if ! grep -q "${PF_ANCHOR_NAME}" "${PF_CONF}" 2>/dev/null; then
  echo "📝 Adding WebBlocker anchor to pf.conf..."
  echo "" >> "${PF_CONF}"
  echo "# WebBlocker anchor - DO NOT REMOVE" >> "${PF_CONF}"
  echo "anchor \\"${PF_ANCHOR_NAME}\\"" >> "${PF_CONF}"
  echo "load anchor \\"${PF_ANCHOR_NAME}\\" from \\"${PF_RULES_FILE}\\"" >> "${PF_CONF}"
fi

# Populate the webblocker_blocked table with IPs
echo "📋 Populating blocked IPs table..."
pfctl -t webblocker_blocked -T flush 2>/dev/null || true

${ips.map((ip) => `pfctl -t webblocker_blocked -T add ${ip} 2>/dev/null || true`).join("\n")}

# Load rules into the anchor
echo "🔧 Loading firewall rules..."
pfctl -a "${PF_ANCHOR_NAME}" -f "${PF_RULES_FILE}" 2>/dev/null || true

# Enable PF if not already enabled
if ! pfctl -s info 2>/dev/null | grep -q "Status: Enabled"; then
  echo "🚀 Enabling PF firewall..."
  pfctl -e 2>/dev/null || true
fi

# Kill existing connections to blocked IPs
echo "🔪 Killing existing connections to blocked sites..."
${ips.map((ip) => `pfctl -k ${ip} 2>/dev/null || true`).join("\n")}

# Flush state table to drop existing connections
pfctl -F state 2>/dev/null || true

echo "✅ PF firewall blocking enabled!"
echo "Blocking ${domains.length} domains (${ips.length} IPs)"
`;
        const tempScriptPath = "/tmp/webblocker_pf_enable.sh";
        await fs.writeFile(tempScriptPath, scriptContent);
        await execAsync(`chmod +x ${tempScriptPath}`);
        console.log("🔐 Requesting authentication...");
        const execResult = await (0, biometricAuth_1.executeScriptWithAuth)(tempScriptPath, "WebBlocker needs to configure firewall rules to block websites");
        if (!execResult.success) {
            await execAsync(`rm -f ${tempScriptPath}`);
            return {
                success: false,
                message: execResult.error || "Authentication failed",
            };
        }
        await execAsync(`rm -f ${tempScriptPath}`);
        return {
            success: true,
            message: `PF firewall blocking enabled for ${domains.length} domain(s) - blocks are instant!`,
        };
    }
    catch (error) {
        console.error("PF blocking error:", error);
        return {
            success: false,
            message: `Failed to enable PF blocking: ${error.message}`,
        };
    }
}
async function disablePFBlocking() {
    try {
        console.log("🔥 Disabling PF firewall blocking...");
        const scriptContent = `#!/bin/bash
set +e

echo "🔥 Removing PF firewall blocking..."

# Flush the anchor rules
pfctl -a "${PF_ANCHOR_NAME}" -F all 2>/dev/null || true

# Clear the blocked IPs table
pfctl -t webblocker_blocked -T flush 2>/dev/null || true
pfctl -t webblocker_blocked -T kill 2>/dev/null || true

# Remove anchor from pf.conf
if grep -q "${PF_ANCHOR_NAME}" "${PF_CONF}" 2>/dev/null; then
  echo "📝 Removing WebBlocker anchor from pf.conf..."
  sed -i.bak "/${PF_ANCHOR_NAME}/d" "${PF_CONF}" 2>/dev/null || true
  sed -i.bak "/# WebBlocker anchor/d" "${PF_CONF}" 2>/dev/null || true
fi

# Clean up rules file
rm -f "${PF_RULES_FILE}" 2>/dev/null || true

# Reload PF configuration
pfctl -f "${PF_CONF}" 2>/dev/null || true

echo "✅ PF firewall blocking disabled!"
`;
        const tempScriptPath = "/tmp/webblocker_pf_disable.sh";
        await fs.writeFile(tempScriptPath, scriptContent);
        await execAsync(`chmod +x ${tempScriptPath}`);
        console.log("🔐 Requesting authentication...");
        const execResult = await (0, biometricAuth_1.executeScriptWithAuth)(tempScriptPath, "WebBlocker needs to remove firewall rules to unblock websites");
        if (!execResult.success) {
            await execAsync(`rm -f ${tempScriptPath}`);
            return {
                success: false,
                message: execResult.error || "Authentication failed",
            };
        }
        await execAsync(`rm -f ${tempScriptPath}`);
        return {
            success: true,
            message: "PF firewall blocking disabled - all sites accessible",
        };
    }
    catch (error) {
        console.error("PF disable error:", error);
        return {
            success: false,
            message: `Failed to disable PF blocking: ${error.message}`,
        };
    }
}
async function isPFBlockingActive() {
    try {
        const { stdout } = await execAsync(`sudo pfctl -a "${PF_ANCHOR_NAME}" -sr 2>/dev/null || echo ""`);
        return stdout.includes("webblocker_blocked");
    }
    catch {
        return false;
    }
}
//# sourceMappingURL=pfFirewallManager.js.map