export function cleanString(str: string): string {
  // Define a mapping of special characters to their ASCII counterparts
  const charMap: Record<string, string> = {
    á: "a",
    é: "e",
    í: "i",
    ó: "o",
    ú: "u",
    Á: "A",
    É: "E",
    Í: "I",
    Ó: "O",
    Ú: "U",
    à: "a",
    è: "e",
    ì: "i",
    ò: "o",
    ù: "u",
    À: "A",
    È: "E",
    Ì: "I",
    Ò: "O",
    Ù: "U",
    ã: "a",
    ẽ: "e",
    ĩ: "i",
    õ: "o",
    ũ: "u",
    Ã: "A",
    Ẽ: "E",
    Ĩ: "I",
    Õ: "O",
    Ũ: "U",
    ç: "c",
    Ç: "C",
    ñ: "n",
    Ñ: "N",
    Ê: "E",
    ê: "e",
    Â: "A",
    â: "a",
    Ô: "O",
    ô: "o",
    Î: "I",
    î: "i",
    Û: "U",
    û: "u",
    Ü: "U",
  };

  // Use a regular expression to replace all special characters in the input string
  return str.replace(/[^a-zA-Z0-9\s]/g, (match) => charMap[match] ?? match);
}
