// src/data.ts

// An object that holds all our data arrays.
// This makes it easy to access the correct list of snippets using a key.
export const DATA = {
  voorstelling: [
    "Hallo, ik ben Ahmed uit Diest. Ik ben 56 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben An uit Mechelen. Ik ben 49 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben Bert uit Oostende. Ik ben 41 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben Carla uit Tienen. Ik ben 70 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben David uit Dendermonde. Ik ben 77 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben Fatima, 38 jaar en alleenstaande mama van drie kinderen. Mijn jongste zoon heeft een motorische beperking en zit in het buitengewoon onderwijs. We wonen in een rijhuis in Genk, vlak bij het stadscentrum. Ik probeer werk en zorg te combineren, wat niet altijd evident is.",
    "Hallo, ik ben Koen, 50 jaar en woon in Hasselt. Ik heb een spierziekte waardoor ik hulp nodig heb bij verplaatsingen. Ik probeer actief te blijven en ga regelmatig naar de kinesist. Mijn sociale kring is klein, maar ik ben goedlachs en positief.",
    "Hallo, ik ben Lien uit Halle. Ik ben 65 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben Mireille uit Turnhout. Ik ben 58 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben Rik uit Gent. Ik ben 68 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben Sam (26) uit Sint-Niklaas. Door mijn autisme vind ik een drukke planning soms overweldigend. Ik ben volledig zelfstandig, maar wat hulp bij het structureren van mijn week zou me enorm veel rust geven.",
    "Hallo, ik ben Sofia (45) uit Antwerpen. Ik heb een visuele beperking en red me prima, maar hulp bij administratie of het vergezellen naar nieuwe plekken zou erg welkom zijn om mijn zelfstandigheid te vergroten.",
    "Hallo, ik ben Sofie uit Leuven. Ik ben 54 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben Tom uit Zottegem. Ik ben 79 jaar oud en woon hier al mijn hele leven. Ik heb een beperking waardoor dagelijkse taken lastig zijn. Toch probeer ik mijn zelfstandigheid zoveel mogelijk te behouden.",
    "Hallo, ik ben Wouter uit Mechelen. Ik ben 68 en herstel van een heupoperatie waardoor ik minder mobiel ben. Zaken als boodschappen doen zijn een uitdaging. Een beetje tijdelijke hulp zou me enorm vooruithelpen in mijn herstel.",
    "Ik ben Elise uit Leuven, 31 jaar en een jonge mama van een tweeling. Ik geniet enorm, maar het is ook best pittig. Ik zoek iemand die af en toe kan helpen met een klusje, zodat ik even op adem kan komen.",
    "Ik ben Elke, 43 jaar, en ik woon zelfstandig in Roeselare. Ik heb een fysieke beperking waardoor ik moeilijk kan stappen. Ik ben graag creatief bezig, maar praktische dingen zijn lastig. Vooral koken en boodschappen doen zijn een uitdaging.",
    "Ik ben Gerard, 85 jaar, uit Brugge. Sinds ik niet meer mag rijden, voelt mijn wereld kleiner. Ik zoek iemand die me af en toe kan vervoeren, zodat ik mijn wekelijkse uitstapjes en sociale contacten niet hoef op te geven.",
    "Ik ben Greta, 74 jaar en woon in Kortrijk. Door mijn reuma zijn sommige dingen in huis te moeilijk geworden. Ik krijg al hulp bij het poetsen, maar niet bij kleine herstellingen. Toch wil ik mijn huis graag netjes en veilig houden.",
    "Ik ben Isabelle, 60 jaar, en zorg voor mijn moeder van 89. We wonen samen in een rustige buurt in Brugge. Mijn moeder heeft Alzheimer en kan niet meer alleen zijn. Ze is nog mobiel maar snel verward.",
    "Ik ben Lotte, 38 jaar, en woon in Kortrijk. Leven met chronische pijn maakt mijn energie onvoorspelbaar. Hulp bij de zwaardere huishoudelijke taken op moeilijke dagen zou een enorme opluchting zijn.",
    "Ik ben Louis, 65 jaar en gepensioneerd leerkracht biologie. Door ernstige rugklachten kan ik niet meer in mijn tuin werken. Ik woon in Aalst in een huis met een vrij grote tuin. Die tuin is mijn trots, maar hij groeit me letterlijk boven het hoofd.",
    "Ik ben Marc, 71 jaar oud, en woon samen met mijn vrouw in Sint-Niklaas. Zij lijdt aan jongdementie en ik ben haar hoofdverzorger. We wonen in een gelijkvloers huis met een kleine tuin. Ik ben graag bezig in huis, maar heb af en toe een pauze nodig.",
    "Ik ben Paul, 56 jaar en woon in Lokeren. Vroeger werkte ik als vrachtwagenchauffeur, tot een ongeval me in een rolstoel deed belanden. Ik woon alleen in een rustig appartement met zicht op het park. Mijn dagen zijn meestal rustig, maar het huishouden stapelt zich snel op.",
    "Mijn naam is Aisha uit Turnhout, 35 jaar en een alleenstaande moeder van twee. Een extra paar handen tijdens het drukke spitsuur na school zou me de ademruimte geven om alles in balans te houden.",
    "Mijn naam is Amina, ik ben 33 en woon in een studio in Antwerpen. Ik heb een licht verstandelijke beperking en krijg ondersteuning via het VAPH. Ik probeer zoveel mogelijk zelfstandig te zijn. Structuur aanbrengen in mijn dag is voor mij niet altijd vanzelfsprekend.",
    "Mijn naam is Jeroen, ik ben 27 jaar en woon zelfstandig in Herentals. Ik heb autisme en werk deeltijds in een beschutte werkplaats. Sociale situaties en planning zijn moeilijk voor mij. Ik hou van strips en ben goed met cijfers.",
    "Mijn naam is Johan, ik ben 81 en woon in Hasselt. Sinds mijn vrouw er niet meer is, valt de stilte in huis me zwaar. Ik kan wel een steuntje gebruiken voor een babbel of wat praktische taken in huis.",
    "Mijn naam is Leo, ik ben 88 jaar en woon in Aalst. Ik ben altijd zelfstandig geweest, maar door mijn leeftijd wordt koken een hele inspanning. Ik zoek iemand die me kan helpen met het bereiden van een verse maaltijd.",
    "Mijn naam is Paul, ik ben 78 jaar en kom uit Gent. Ik zorg met veel liefde voor mijn vrouw die Parkinson heeft, maar soms raakt mijn eigen batterij leeg. Een paar uurtjes hulp per week zou me de ademruimte geven om weer op te laden.",
  ],
  hulpvraag: [
    "Hulp bij het huishouden: ik zoek een betrouwbare poetshulp voor mijn appartement, tweemaal per week. Taken zoals grondig stofzuigen, dweilen en het reinigen van de badkamer krijg ik niet meer zelf gedaan. Een vaste hulp op dinsdag en vrijdag zou ideaal zijn voor mij.",
    "Een helpende hand in de tuin: ik ben op zoek naar iemand met groene vingers die me een halve dag per week kan helpen met het onderhoud van mijn tuin. Het maaien van het gras, het snoeien van de struiken en het verwijderen van onkruid zijn de belangrijkste taken die ik zelf niet meer kan uitvoeren.",
    "Handige klusjesman of -vrouw gevraagd: ik ben op zoek naar iemand die me kan bijstaan met kleine reparaties en klusjes in huis. Denk aan het vervangen van een lamp, het herstellen van een losse kastplank of het ophangen van een schilderij. Tweewekelijks langskomen zou perfect zijn.",
    "Ondersteuning bij boodschappen en koken: wie helpt mij met het doen van de wekelijkse boodschappen en het voorbereiden van maaltijden? Ik zou graag samen een boodschappenlijstje maken en de maaltijden voor de week plannen. Een uur per week zou al een wereld van verschil maken.",
    "Hulp bij administratie en planning: ik zou graag iemand vinden die me kan helpen met mijn papierwerk en het structureren van mijn huishoudelijke taken. Samen brieven sorteren, afspraken maken en een weekplanning opstellen is wat ik nodig heb om overzicht te houden.",
    "Een helpende hand bij structuur en administratie: wie helpt me wekelijks om mijn week te plannen, afspraken te beheren en te assisteren bij het beantwoorden van brieven en het plegen van telefoontjes? Geduld en een helpende hand zijn welkom om me op weg te helpen.",
    "Schoolvervoer en begeleiding: mijn zoon heeft een begeleider nodig die hem dagelijks naar school kan brengen en ophalen. Hij heeft extra hulp nodig bij het in- en uitstappen uit de auto en het dragen van zijn schoolspullen, omdat hij een motorische beperking heeft.",
    "Gezelschap voor mijn partner: ik zou graag iemand vinden die één namiddag per week met haar op stap wil gaan of bij haar blijft. Een rustige wandeling in het park of samen naar muziek luisteren doet haar goed. Zo heb ik zelf ook even wat tijd voor mezelf om op adem te komen.",
    "Oppas en gezelschap: ik zoek iemand die één of twee keer per week een paar uur bij mijn partner kan blijven. Gewoon wat wandelen, een boekje lezen of samen tv kijken. Het is een uitgelezen kans voor mij om even te ontspannen en mijn eigen batterijen op te laden.",
    "Vervoer naar kinesitherapie: ik heb betrouwbaar vervoer nodig naar mijn kinesitherapie, tweemaal per week. Hulp bij het aan- en uitkleden voor en na de sessie en eventueel kleine huishoudelijke taken nadien zijn ook gewenst.",
    "Zoek jij een extra zakcentje? Ik zoek een vaste poetshulp voor de wekelijkse schoonmaak van mijn woning. Van het grondig stofzuigen en dweilen van de vloeren tot het reinigen van de badkamer, alles moet spic en span zijn. Een betrouwbaar en punctueel persoon is wat ik zoek.",
    "Een helpende hand in de tuin: ik ben op zoek naar iemand voor wekelijks tuinonderhoud. De taken omvatten het maaien van het gras, het snoeien van de hagen en het wieden van onkruid in de bloembedden. Liefst iemand met groene vingers die het werk graag doet.",
    "Vrijwilliger gevraagd voor kleine klusjes: ik zoek iemand die me kan helpen met kleine reparaties en klusjes in huis. Het gaat om tweewekelijkse bezoeken van een paar uur. Ervaring met het monteren van meubels of het vastzetten van losse onderdelen is zeker een pluspunt.",
    "Wie helpt mij met de maaltijden? Ik zoek hulp bij het plannen en voorbereiden van maaltijden voor de week en het doen van de boodschappen. Een wekelijkse hulp zou al een groot verschil maken in mijn dagelijks leven.",
    "Assistentie met papierwerk: ik zoek iemand om me te helpen met de papierwinkel en de administratie. Samen brieven openen en sorteren, en afspraken beheren. Het gaat om het creëren van overzicht en het verminderen van stress.",
    "Coaching voor planning en administratie: ik zoek wekelijks overleg om mijn taken en afspraken te organiseren. Een geduldige en helpende hand is welkom om me te helpen mijn dagelijkse leven weer op de rails te krijgen.",
    "Wie kan mijn kind naar school brengen? Ik zoek een chauffeur om mijn dochter dagelijks naar school te brengen en op te halen. Ze heeft een beperking en heeft hulp nodig bij het in- en uitstappen uit de auto.",
    "Een maatje gezocht voor oudere dame: ik zoek iemand die een namiddag per week met mijn moeder wil doorbrengen. Ze houdt van muziek en een wandeling in de buurt, maar het gezelschap is het allerbelangrijkste.",
    "Ik kan even niet meer: ik zoek iemand die een dag per week bij mijn partner kan blijven. Om wat te wandelen, een boekje te lezen en een praatje te maken. Zo kan ik even op adem komen en tijd voor mezelf nemen.",
    "Hulp en vervoer voor medische afspraken: ik zoek iemand die me kan begeleiden naar mijn doktersafspraken, twee keer per week. Hulp bij het aan- en uitkleden en eventueel kleine huishoudelijke taken nadien is ook gewenst.",
    "Poetshulp gevraagd: ik ben op zoek naar een hulp in de huishouding voor drie uur per week, liefst op maandagochtend. Badkamer, keuken en stofzuigen zijn de belangrijkste taken die ik graag uit handen geef.",
    "Hulp in de tuin gezocht: ik zoek een vrijwilliger die me kan helpen met het onderhoud van mijn tuin. Het gaat om gras maaien en de borders bijhouden. Graag iemand die van aanpakken weet en de handen uit de mouwen steekt.",
    "Wie kan me helpen met kleine herstellingen? Ik zoek iemand die handig is met kleine klusjes in huis. Denk aan een lekkende kraan of een losse plank. Twee keer per maand zou genoeg zijn.",
    "Boodschappen en kookhulp: ik zoek wekelijks iemand die me helpt met de boodschappen en me helpt bij het bereiden van maaltijden. Het gaat om een paar uurtjes per week, flexibel in te plannen.",
    "Hulp bij administratie: ik zoek iemand die me kan helpen met het sorteren van papieren en het invullen van formulieren. Wekelijks een uurtje samenwerken zou al een grote opluchting zijn.",
    "Begeleiding bij administratie en afspraken: ik zoek een coach die me helpt met de wekelijkse planning en het beheren van mijn agenda. Geduld en structuur zijn belangrijk, omdat ik het overzicht snel verlies.",
    "Vervoer van en naar school: ik zoek iemand om mijn kind dagelijks naar school te brengen en op te halen. Hij heeft extra hulp nodig met het uit de auto stappen en heeft specifieke zorgbehoeften.",
    "Gezelschap voor oudere dame: ik zoek iemand die een namiddag per week bij mijn moeder kan blijven. Ze houdt van muziek en een wandeling, maar heeft vooral behoefte aan sociaal contact en een goed gesprek.",
    "Oppas gezocht: ik zoek iemand die een paar uur per week bij mijn partner kan blijven voor gezelschap en toezicht. Zo kan ik even ontspannen en mijn eigen energie weer aanvullen.",
    "Vervoer en assistentie: ik zoek iemand die me kan begeleiden naar mijn doktersafspraken en me helpt bij het aan- en uitkleden. Twee keer per week, liefst iemand die ervaring heeft met zorgtaken.",
    "Poetshulp voor wekelijkse schoonmaak: ik ben op zoek naar een poetshulp voor een vast dagdeel per week. Taken: stofzuigen, dweilen, badkamer en keuken poetsen. Het gaat om een langdurige samenwerking.",
    "Hulp bij tuinonderhoud: ik zoek hulp bij het onderhouden van mijn tuin. Gras maaien, snoeien en onkruid wieden. Ik kan zelf niet meer op mijn knieën zitten en de grond bewerken.",
    "Handige klusjesman: ik zoek iemand die twee keer per maand langs kan komen voor kleine herstellingen en klusjes. Een lekvrije kraan, een nieuwe lamp of een piepende deur, alles is welkom.",
    "Hulp bij boodschappen en koken: ik zoek hulp bij de wekelijkse boodschappen en maaltijdbereiding. Het gaat om het plannen en inkopen van ingrediënten, en samen een maaltijd koken.",
    "Administratieve hulp: ik zoek iemand die me kan helpen met het sorteren van brieven en het invullen van formulieren. Het overzicht bewaren is voor mij een grote uitdaging.",
    "Planning en structuur: ik zoek iemand die me wekelijks helpt met het opstellen van een weekplanning en het bijhouden van de administratie. Zodat ik mijn taken en afspraken niet vergeet.",
    "Vervoer naar school: ik zoek iemand die mijn zoon naar school kan brengen en ophalen. Hij heeft extra hulp nodig bij het in- en uitstappen en het dragen van zijn schooltas.",
    "Gezelschap: ik zoek iemand die een namiddag per week bij mijn moeder kan blijven. Ze houdt van wandelen en tv-kijken, maar heeft vooral behoefte aan een praatje en gezelschap.",
    "Oppas voor partner: ik zoek iemand die een paar uur per week bij mijn partner kan blijven. Om wat te wandelen en te lezen, zodat ik even kan rusten en op adem kan komen.",
    "Vervoer en assistentie: ik zoek vervoer naar mijn kinesitherapie en hulp bij het aan- en uitkleden. Twee keer per week, liefst iemand met ervaring in de zorg.",
    "Poetshulp gezocht voor vast dagdeel per week, drie uur lang, voor algemene schoonmaak en netheid van het huis. Ik kan zelf niet meer goed bukken of zware spullen optillen.",
    "Tuinhulp gevraagd: gras maaien en snoeien. Mijn tuin heeft dringend onderhoud nodig, maar ik ben zelf niet meer in staat om dit te doen. Een helpende hand is zeer welkom.",
    "Klusjesman/vrouw: voor kleine herstellingen in huis. Een lekke kraan of een kapotte lamp, het zijn de kleine dingen die me frustreren en waar ik hulp bij nodig heb.",
    "Hulp bij boodschappen en maaltijdbereiding: ik zoek iemand die me wekelijks kan helpen met het plannen, inkopen en bereiden van gezonde maaltijden.",
    "Administratieve ondersteuning: ik zoek iemand die me wekelijks kan helpen met het doornemen van brieven en het invullen van formulieren. Een paar uurtjes per week zouden al een groot verschil maken.",
    "Planning en structuur: ik zoek iemand die me wekelijks kan helpen met het opstellen van een weekplanning en het overzicht bewaren van mijn afspraken en taken.",
    "Vervoer van en naar school: voor mijn zoon met extra zorgbehoeften, die hulp nodig heeft bij het in- en uitstappen en het dragen van zijn spullen.",
    "Gezelschap voor oudere dame: een rustige wandeling of een praatje. Mijn moeder heeft behoefte aan sociaal contact en iemand die naar haar wil luisteren.",
    "Oppas voor partner: zodat ik zelf even tijd heb om een boodschap te doen of te ontspannen. Een paar uur per week zou al veel betekenen.",
    "Vervoer naar afspraken: met assistentie bij aan- en uitkleden. Ik zoek iemand die me kan rijden naar mijn medische afspraken en me kan ondersteunen.",
    "Poetshulp tweemaal per week voor volledige woning, inclusief sanitair en keuken. Mijn huis is te groot om zelf schoon te houden.",
    "Hulp bij tuinonderhoud: gras, snoeien, onkruid. Mijn tuin verwildert en ik kan het zelf niet meer bijhouden. Graag iemand die de handen uit de mouwen steekt.",
    "Klusjesman/vrouw: tweewekelijks voor kleine herstellingen. Een handige persoon die de kleine problemen in huis kan oplossen.",
    "Hulp bij boodschappen en koken: wekelijks. Het plannen en bereiden van maaltijden is een zware taak geworden.",
    "Administratieve hulp: wekelijks papieren sorteren. De stapel groeit en ik kan het overzicht niet meer bewaren.",
    "Planning en structuur: wekelijkse planning opstellen. Ik heb moeite met het organiseren van mijn dag en heb hier hulp bij nodig.",
    "Vervoer naar school: voor mijn kind met beperking. Ik kan zelf niet rijden en zoek iemand die hem veilig kan vervoeren.",
    "Gezelschap voor mantelzorger: een namiddag per week. Mijn partner zorgt voor mij en ik wil hem de kans geven om even te rusten en tijd voor zichzelf te nemen.",
    "Oppas voor partner: twee keer per week, zodat ik kan rusten. Ik ben chronisch ziek en heb de zorg voor mijn partner niet meer alleen in de hand.",
    "Vervoer naar kinesitherapie en assistentie. Ik zoek iemand die me kan rijden en me kan helpen bij het aan- en uitkleden.",
    "Schoonmaakhulp gezocht voor vast moment per week. Ik kan zelf niet meer goed bukken of zware spullen optillen.",
    "Tuinhulp voor een halve dag per week. Mijn tuin heeft dringend onderhoud nodig.",
    "Klusjesdienst: kleine herstellingen tweewekelijks. Een handige Harry is van harte welkom.",
    "Maaltijdservice aan huis: hulp bij boodschappen en koken. Gezonde maaltijden bereiden is een uitdaging geworden.",
    "Hulp bij administratie en planning: wekelijks. Ik ben het overzicht kwijt en zoek iemand die me kan helpen.",
    "Structurele ondersteuning: wekelijkse planning en administratie. Ik heb moeite met het organiseren van mijn leven.",
    "Vervoer van en naar school met assistentie. Mijn kind heeft speciale behoeften en kan niet alleen reizen.",
    "Gezelschap voor oudere dame: rustige activiteiten. Ze voelt zich eenzaam en ik wil dat ze sociaal contact heeft.",
    "Oppas en gezelschap voor partner met dementie. Ik zoek iemand die haar gezelschap kan houden en kan toezien op haar welzijn.",
    "Vervoer en assistentie bij medische afspraken. Ik zoek iemand die me kan rijden en me kan ondersteunen tijdens mijn afspraken.",
    "Poetshulp voor wekelijkse schoonmaak. Ik kan zelf de huishouding niet meer doen.",
    "Hulp bij tuinonderhoud en snoeien. Mijn tuin is overwoekerd en ik kan er zelf niet meer voor zorgen.",
    "Klusjesman voor kleine herstellingen. Het gaat om eenmalige of terugkerende klusjes.",
    "Boodschappen en kookhulp aan huis. Ik kan zelf niet meer naar de winkel en heb hulp nodig bij het bereiden van maaltijden.",
    "Hulp bij administratie en planning. Ik zoek iemand die me helpt mijn leven weer op de rails te krijgen.",
    "Structurele hulp bij wekelijkse taken. Ik zoek een vaste hulp die me helpt met de huishouding en boodschappen.",
    "Vervoer naar school: ophalen en brengen. Mijn zoon heeft extra zorg nodig bij het vervoer.",
    "Gezelschap voor partner met Alzheimer. Ik zoek iemand die haar gezelschap kan houden en kan toezien op haar welzijn.",
    "Oppas voor moeder: zodat ik kan ontspannen. De zorg is zwaar en ik heb tijd voor mezelf nodig.",
    "Vervoer naar fysiotherapie met assistentie. Ik zoek iemand die me kan rijden en me kan helpen bij het aan- en uitkleden.",
    "Hulp bij poetsen en schoonmaakwerk. Ik kan de zware taken niet meer aan.",
    "Tuinhulp gevraagd: gras maaien en snoeien. Mijn tuin is dringend aan onderhoud toe.",
    "Klusjesdienst: tweewekelijks kleine herstellingen. Een handige persoon die me kan helpen met de kleine mankementen in huis.",
    "Boodschappen en kookhulp wekelijks. Ik kan zelf niet meer naar de supermarkt en heb hulp nodig bij het koken.",
    "Hulp bij administratie en papierwerk. De stapel groeit en ik kan het niet meer aan.",
    "Wekelijkse planning en structuur. Ik heb moeite met het organiseren van mijn leven en zoek hulp.",
    "Vervoer naar school met assistentie. Mijn kind kan niet alleen reizen en heeft een vaste begeleider nodig.",
    "Gezelschap voor oudere persoon. Hij voelt zich eenzaam en heeft behoefte aan sociaal contact.",
    "Oppas voor partner met dementie. Ik zoek iemand die hem gezelschap kan houden, zodat ik even kan rusten.",
    "Vervoer naar doktersafspraken met begeleiding. Ik kan zelf niet meer rijden en heb iemand nodig die me kan begeleiden.",
    "Schoonmaakhulp gezocht voor wekelijks onderhoud. Mijn huis is te groot om zelf schoon te houden.",
    "Hulp bij tuinonderhoud. Mijn tuin is verwaarloosd en ik zoek iemand die me kan helpen met het onderhoud.",
    "Handige Harry/Henriette voor klusjes. Iemand die me kan helpen met de kleine problemen in huis.",
    "Hulp bij boodschappen. Ik kan zelf niet meer naar de winkel en zoek iemand die me kan helpen.",
    "Administratieve hulp. Ik ben het overzicht kwijt en zoek iemand die me kan helpen met mijn papierwerk.",
    "Wekelijkse planning. Ik heb moeite met het organiseren van mijn leven en zoek hulp bij het plannen van mijn taken.",
    "Schoolvervoer. Ik zoek iemand die mijn kind naar school kan brengen en ophalen.",
    "Gezelschap. Ik voel me eenzaam en zoek iemand voor een praatje en een wandeling.",
    "Oppas. Ik zoek iemand die een paar uur per week bij mijn partner kan blijven, zodat ik even kan rusten.",
    "Vervoer naar kinesist. Ik kan zelf niet rijden en zoek iemand die me kan vervoeren.",
    "Poetshulp voor wekelijks schoonmaak. Ik kan zelf de huishouding niet meer aan.",
    "Tuinhulp voor gras maaien. Mijn tuin heeft dringend onderhoud nodig.",
    "Klusjesman/vrouw voor kleine herstellingen. Een handige persoon die me kan helpen.",
    "Hulp bij boodschappen en koken. Ik heb moeite met de dagelijkse taken en zoek hulp.",
    "Administratieve ondersteuning. Ik ben het overzicht kwijt en zoek hulp.",
    "Hulp bij weekplanning. Ik zoek iemand die me kan helpen mijn taken te organiseren.",
    "Vervoer naar school. Ik kan zelf niet rijden en zoek iemand die mijn kind kan vervoeren.",
    "Gezelschap voor oudere. Hij voelt zich eenzaam en zoekt contact.",
    "Oppas voor partner. Ik zoek iemand die me kan ondersteunen in de zorg.",
    "Vervoer naar afspraken. Ik zoek iemand die me kan rijden en me kan begeleiden.",
    "Hulp bij het poetsen. Ik kan de zware taken niet meer aan.",
    "Tuinonderhoud. Mijn tuin is verwaarloosd en ik zoek hulp.",
    "Kleine herstellingen. Ik zoek iemand die me kan helpen met de kleine klusjes in huis.",
    "Hulp bij boodschappen en maaltijden. Ik heb moeite met de dagelijkse taken en zoek hulp.",
    "Hulp bij administratie. Ik ben het overzicht kwijt en zoek hulp.",
    "Hulp bij planning. Ik zoek iemand die me helpt mijn taken te organiseren.",
    "Schoolvervoer en begeleiding. Ik zoek een chauffeur die mijn kind kan vervoeren en begeleiden.",
    "Gezelschap voor een namiddag. Ik voel me eenzaam en zoek gezelschap.",
    "Oppas voor partner met Alzheimer. Ik zoek iemand die me kan ondersteunen in de zorg.",
    "Vervoer naar afspraken met assistentie. Ik zoek iemand die me kan rijden en begeleiden.",
  ],
  titel: [
    "Hulp bij huishoudelijke taken gezocht",
    "Ondersteuning voor senioren in de schoonmaak",
    "Onderhoud en klusjes in huis gevraagd",
    "Zoek hulp bij tuinieren en groenonderhoud",
    "Boodschappenassistentie gevraagd",
    "Gezelschap en wandelmaatje voor oudere persoon",
    "Zoek een compagnon voor partner met dementie",
    "Begeleiding bij dagelijkse bezigheden nodig",
    "Een praatje en wandeling voor mama met Alzheimer",
    "Vrijwilliger gezocht voor sociale ondersteuning",
    "Vervoer en begeleiding naar afspraken",
    "Hulp bij verplaatsingen en buitenactiviteiten",
    "Begeleiding bij bezoek aan het ziekenhuis",
    "Zoek een chauffeur voor medische afspraken",
    "Gezelschap en vervoer naar een dagcentrum",
    "Ondersteuning bij de dagelijkse planning",
    "Administratieve hulp en structuur nodig",
    "Zoek hulp bij papierwerk en financiën",
    "Coaching en ondersteuning gevraagd",
    "Praktische hulp bij de weekplanning",
    "Poetshulp voor een wekelijkse schoonmaakbeurt",
    "Hulp bij ramen lappen en algemeen onderhoud",
    "Strijkwerk en huishoudelijke karweitjes",
    "Hulp bij tuinieren en planten verzorgen",
    "Ondersteuning bij het doen van boodschappen",
    "Hulp bij opruimen en organisatie",
    "Persoonlijke begeleiding tijdens wandelingen",
    "Gezelschap voor avondwandelingen",
    "Hulp bij voorlezen en gezelschap houden",
    "Zoek een wandelgenoot voor partner",
    "Oppas en gezelschap voor senioren",
    "Hulp bij aan- en uitkleden",
    "Begeleiding naar de dokter",
    "Vervoer naar supermarkt met assistentie",
    "Hulp bij verplaatsen in en rond huis",
    "Wekelijks gezelschap gezocht",
    "Ondersteuning bij dagelijkse routines",
    "Hulp bij kleine klusjes in de tuin",
    "Zoek een helpende hand voor in huis",
    "Hulp bij de bereiding van maaltijden",
    "Gezelschap voor koffie en een goed gesprek",
    "Hulp bij administratieve taken thuis",
    "Ondersteuning bij de weekplanning",
    "Hulp bij het huishouden gezocht",
    "Schoonmaak en opruimhulp",
    "Hulp bij tuinonderhoud en snoeiwerk",
    "Begeleiding naar ziekenhuisafspraken",
    "Hulp bij de wekelijkse boodschappen",
    "Gezelschap en wandelingen in de buurt",
    "Persoonlijke begeleiding voor oudere dame",
    "Hulp bij koken en maaltijden",
    "Ondersteuning bij medicatiebeheer",
    "Begeleiding naar de fysiotherapeut",
    "Hulp bij het onderhouden van de woning",
    "Zoek een luisterend oor en gezelschap",
    "Hulp bij het invullen van formulieren",
    "Structurele ondersteuning gezocht",
    "Ondersteuning bij de dagindeling",
    "Hulp bij kleine klusjes en herstellingen",
    "Oppas voor oudere met dementie",
    "Gezelschap voor partner met Alzheimer",
    "Hulp bij het aanleren van nieuwe routines",
    "Ondersteuning bij het omgaan met dementie",
    "Begeleiding bij de dagelijkse verzorging",
    "Hulp bij hobby's en vrijetijdsbesteding",
    "Zoek een zorgzame begeleider",
    "Hulp bij het aankopen van benodigdheden",
    "Begeleiding bij uitstapjes",
    "Hulp bij het regelen van afspraken",
    "Ondersteuning bij de administratie",
    "Hulp bij de wekelijkse huishouding",
    "Schoonmaak en organisatie",
    "Hulp bij tuinwerkzaamheden",
    "Begeleiding naar de huisarts",
    "Hulp bij het vervoer van en naar school",
    "Gezelschap en steun voor oudere heer",
    "Hulp bij het bereiden van maaltijden",
    "Ondersteuning bij de dagelijkse taken",
    "Begeleiding naar de tandarts",
    "Hulp bij het opruimen van de garage",
    "Zoek een betrouwbare hulp",
    "Hulp bij het uitzoeken van papieren",
    "Structuur en organisatie in huis",
    "Ondersteuning bij het dagelijks leven",
    "Hulp bij verplaatsingen en klusjes",
    "Hulp bij het wassen van kleding",
    "Ondersteuning bij het opruimen van kasten",
    "Hulp bij het verzorgen van de tuin",
    "Begeleiding naar de kapper",
    "Hulp bij het doen van boodschappen",
    "Gezelschap voor een praatje",
    "Ondersteuning bij het opstarten van de dag",
    "Hulp bij het structureren van taken",
    "Begeleiding bij doktersbezoeken",
    "Hulp bij het uitzoeken van kleding",
    "Hulp bij het verplaatsen van meubels",
    "Ondersteuning bij administratie en planning",
    "Hulp bij het opruimen van de kelder",
    "Begeleiding bij het winkelen",
    "Hulp bij het vervoeren van spullen",
  ],
};

// This is a clever TypeScript trick. It creates a type that can ONLY be
// one of the keys from our DATA object ("voorstelling", "hulpvraag", or "titel").
export type Category = keyof typeof DATA;
