import { Color } from "@raycast/api";

/* =============================== IMAGES =============================== */

// Supported icon image extensions
export const VALID_ICON_EXTENSIONS = [".png", ".icns", ".jpg", ".jpeg", ".tiff", ".tif", ".gif", ".webp"];

/** Supported background image extensions */
export const VALID_IMAGE_EXTENSIONS = [...VALID_ICON_EXTENSIONS, ".bmp", ".heic", ".heif"];

/* =========================== BACKGROUND ============================ */

// Special value for default folder color (no tinting)
export const DEFAULT_FOLDER_COLOR = "default";

// Solid colors based on Raycast's color palette
export const SOLID_COLORS = [
  { title: "Blue", value: "#007AFF", color: Color.Blue },
  { title: "Green", value: "#34C759", color: Color.Green },
  { title: "Magenta", value: "#FF2D55", color: Color.Magenta },
  { title: "Orange", value: "#FF9500", color: Color.Orange },
  { title: "Purple", value: "#AF52DE", color: Color.Purple },
  { title: "Red", value: "#FF3B30", color: Color.Red },
  { title: "Yellow", value: "#FFCC00", color: Color.Yellow },
];

// Gradient presets (beautiful combinations)
export const GRADIENT_PRESETS = [
  { title: "Sunset", value: "gradient:#FF512F,#DD2476", colors: ["#FF512F", "#DD2476"] },
  { title: "Ocean", value: "gradient:#2193b0,#6dd5ed", colors: ["#2193b0", "#6dd5ed"] },
  { title: "Purple Haze", value: "gradient:#7F00FF,#E100FF", colors: ["#7F00FF", "#E100FF"] },
  { title: "Emerald", value: "gradient:#11998e,#38ef7d", colors: ["#11998e", "#38ef7d"] },
  { title: "Peach", value: "gradient:#ED4264,#FFEDBC", colors: ["#ED4264", "#FFEDBC"] },
  { title: "Royal", value: "gradient:#141E30,#243B55", colors: ["#141E30", "#243B55"] },
  { title: "Citrus", value: "gradient:#FDC830,#F37335", colors: ["#FDC830", "#F37335"] },
  { title: "Berry", value: "gradient:#8E2DE2,#4A00E0", colors: ["#8E2DE2", "#4A00E0"] },
  { title: "Midnight", value: "gradient:#4a4d50,#6b7075", colors: ["#4a4d50", "#6b7075"] },
  { title: "Coral", value: "gradient:#ffb088,#ff7a7f", colors: ["#ffb088", "#ff7a7f"] },
  { title: "Sky", value: "gradient:#56CCF2,#2F80ED", colors: ["#56CCF2", "#2F80ED"] },
  { title: "Forest", value: "gradient:#134E5E,#71B280", colors: ["#134E5E", "#71B280"] },
];

/* ============================= EMOJIS =============================== */

// Spritesheet configuration (64px sheet)
export const SHEET_SIZE = 64;
export const SHEET_PADDING = 1;
export const NO_EMOJI = "";

// Curated list of popular emojis by category - subset for better UX
// Using short_name from emoji-datasource
export const CURATED_EMOJIS: Record<string, string[]> = {
  Smileys: [
    "grinning",
    "smile",
    "joy",
    "heart_eyes",
    "sunglasses",
    "thinking_face",
    "rolling_on_the_floor_laughing",
    "star-struck",
    "partying_face",
    "nerd_face",
    "fire",
    "sparkles",
    "star",
    "zap",
    "100",
    "boom",
  ],
  People: [
    "wave",
    "+1",
    "-1",
    "clap",
    "raised_hands",
    "pray",
    "muscle",
    "point_up",
    "ok_hand",
    "v",
    "fist",
    "heart_hands",
    "eyes",
    "brain",
  ],
  Animals: [
    "dog",
    "cat",
    "lion_face",
    "unicorn_face",
    "bear",
    "panda_face",
    "koala",
    "fox_face",
    "rabbit",
    "bird",
    "penguin",
    "butterfly",
    "bee",
    "snail",
    "octopus",
    "whale",
    "dolphin",
    "fish",
    "dragon",
    "t-rex",
  ],
  Nature: [
    "cherry_blossom",
    "rose",
    "sunflower",
    "four_leaf_clover",
    "seedling",
    "evergreen_tree",
    "palm_tree",
    "cactus",
    "mushroom",
    "leaves",
    "rainbow",
    "sunny",
    "cloud",
    "snowflake",
    "ocean",
    "droplet",
  ],
  Food: [
    "apple",
    "lemon",
    "watermelon",
    "strawberry",
    "cherries",
    "grapes",
    "avocado",
    "carrot",
    "corn",
    "pizza",
    "hamburger",
    "coffee",
    "beer",
    "cake",
    "cookie",
    "ice_cream",
    "honey_pot",
    "chocolate_bar",
  ],
  Activities: [
    "soccer",
    "basketball",
    "football",
    "baseball",
    "tennis",
    "golf",
    "dart",
    "8ball",
    "video_game",
    "game_die",
    "trophy",
    "medal",
    "musical_note",
    "guitar",
    "microphone",
    "headphones",
    "art",
    "camera",
  ],
  Travel: [
    "car",
    "airplane",
    "rocket",
    "bike",
    "bus",
    "train",
    "ship",
    "house",
    "office",
    "hospital",
    "school",
    "church",
    "camping",
    "beach_with_umbrella",
    "mountain",
    "earth_americas",
    "japan",
  ],
  Objects: [
    "iphone",
    "computer",
    "keyboard",
    "desktop_computer",
    "printer",
    "bulb",
    "flashlight",
    "wrench",
    "hammer",
    "gear",
    "lock",
    "key",
    "package",
    "gift",
    "envelope",
    "books",
    "pencil2",
    "scissors",
    "briefcase",
    "file_folder",
    "clipboard",
    "calendar",
  ],
  Symbols: [
    "heart",
    "orange_heart",
    "yellow_heart",
    "green_heart",
    "blue_heart",
    "purple_heart",
    "black_heart",
    "broken_heart",
    "peace_symbol",
    "checkered_flag",
    "warning",
    "no_entry",
    "recycle",
    "white_check_mark",
    "x",
    "question",
    "exclamation",
    "copyright",
    "tm",
  ],
};
