import { Color, Icon, Image } from "@raycast/api";
import { Item } from "../core/models";

/**
 * Raycast has no text-color API — `MenuBarExtra.Item` takes only `title`,
 * `subtitle` and `icon` — so the unread signal rides entirely on the icon
 * tint: green for unread, faded for seen.
 */
const UNSEEN = Color.Green;
const SEEN = Color.SecondaryText;

export function itemIcon(item: Item, seen: boolean): Image {
  const source = item.kind === "pullRequest" ? Icon.CodeBlock : Icon.Circle;
  // There is no tertiary color here, so the draft marker moved into the row
  // text instead (see rows.tsx).
  return { source, tintColor: seen ? SEEN : UNSEEN };
}

export function groupIcon(unseen: boolean): Image {
  return { source: Icon.Folder, tintColor: unseen ? UNSEEN : SEEN };
}

export function avatarIcon(url: string): Image {
  return { source: url, mask: Image.Mask.Circle };
}

/** The gauge changes color where the number becomes actionable. */
export function gaugeIcon(fraction: number): Image {
  const tintColor = fraction < 0.1 ? Color.Red : fraction < 0.25 ? Color.Orange : Color.SecondaryText;
  return { source: Icon.Gauge, tintColor };
}

/**
 * Monochrome glyph generated by `tools/makeicon.py`. One file is enough — no
 * `@dark` variant — because `tintColor` paints every non-transparent pixel and
 * Raycast applies it per the menu bar's light/dark appearance.
 *
 * Row icons stay Raycast's own on purpose: the menu bar should look like
 * GHBar, the rows inside it should look like Raycast.
 */
export const MENU_BAR_ICON: Image.ImageLike = {
  source: "menubar-icon.png",
  tintColor: Color.PrimaryText,
};
