export const defaultCommands = {
  "Compose Tweet":
    '{"minNumFiles":"1","useAudioDetails":true,"acceptedFileExtensions":"","useBarcodeDetection":true,"name":"Compose Tweet","useMetadata":false,"icon":"bird-16","prompt":"Compose a tweet based on the following files:","useSubjectClassification":true,"useSoundClassification":true,"useRectangleDetection":false,"useFaceDetection":false}',
  "Identify Selected Files":
    '{"prompt":"Identify the file type and most significant features of the following files based on their content. Discuss the primary purpose of the file based on its content. Categorize the content into relevant topics. Provide an assessment of the file\'s utility as well a list of relevant links and brief descriptions of them. Format the response as a markdown list using \\"## File Type\\", \\"## Topics\\", \\"## Defining Features\\", \\"## Purpose and Potential Usage\\", and \\"## Relevant Links\\" as headings.","minNumFiles":"1","name":"Identify Selected Files","acceptedFileExtensions":"","useSubjectClassification":true,"useMetadata":true,"useFaceDetection":true,"useSoundClassification":true,"useAudioDetails":true,"useBarcodeDetection":true,"icon":"blank-document-16","useRectangleDetection":true}',
  "Make Jingle":
    '{"useMetadata":false,"useSubjectClassification":true,"prompt":"Create short, memorable jingles summarizing the main ideas in each of the following files, using the file names as headings.","useFaceDetection":true,"name":"Make Jingle","acceptedFileExtensions":"","minNumFiles":"1","useAudioDetails":true,"useBarcodeDetection":false,"icon":"music-16","useRectangleDetection":false,"useSoundClassification":true}',
  "Create Action Items":
    '{"icon":"calendar-16","useAudioDetails":true,"useMetadata":false,"useSoundClassification":true,"useRectangleDetection":false,"acceptedFileExtensions":"","minNumFiles":"1","useBarcodeDetection":true,"useFaceDetection":false,"useSubjectClassification":true,"name":"Create Action Items","prompt":"Generate a markdown list of action items from the following files, using a unique identifier for each item as bold headings. If there are any errors in the files, make actions items to fix them. In a sublist of each item, provide a description, priority, estimated level of difficulty, reasonable duration for the task, and due date based on the the duration and today\'s date, \\"{{date}}\\". Here are the files:"}',
  "Extract URLs":
    '{"useRectangleDetection":false,"useBarcodeDetection":true,"prompt":"Extract URLs from the following files and list them as markdown links","useMetadata":false,"icon":"link-16","minNumFiles":"1","useSubjectClassification":false,"useFaceDetection":false,"useSoundClassification":false,"name":"Extract URLs","acceptedFileExtensions":"","useAudioDetails":true}',
  "Metadata Analysis":
    '{"acceptedFileExtensions":"","minNumFiles":"1","name":"Metadata Analysis","prompt":"I want you to give several insights about files based on their metadata and file type. Do not summarize the file content, but instead relate the metadata to the content in a meaningful way. Use metadata to suggest improvements to the content. Provide detailed explanations for your suggestions. Format your response as a paragraph summary. Use the file names as headings.\\nHere\'s the metadata:\\n{{metadata}}\\n\\nHere are the files:","useSubjectClassification":true,"useMetadata":true,"useFaceDetection":true,"useSoundClassification":true,"useAudioDetails":true,"useBarcodeDetection":true,"icon":"magnifying-glass-16","useRectangleDetection":true}',
  "Identify Gaps":
    '{"acceptedFileExtensions":"","icon":"arrows-expand-16","useBarcodeDetection":true,"minNumFiles":"1","name":"Identify Gaps","prompt":"Identify any gaps in understanding or content that occur in the following files. Use the file names as headings. Provide content to fill in the gaps.","useAudioDetails":true,"useRectangleDetection":false,"useFaceDetection":false,"useSoundClassification":false,"useMetadata":false,"useSubjectClassification":false}',
  "Today's Agenda":
    '{"acceptedFileExtensions":"","useSoundClassifications":false,"prompt":"Make an agenda for my day using the following list of events. Format the output as friendly paragraph, directed at my, explaining when there is time for breaks or other activities that you recommend. Use today\'s date ({{date}}) as a markdown header. Here are the events:\\n\\n###\\n{{todayEvents}}\\n###","icon":"calendar-16","minNumFiles":"0","useFileMetadata":false,"name":"Today\'s Agenda"}',
  "Pattern Analysis":
    '{"useRectangleDetection":true,"icon":"line-chart-16","acceptedFileExtensions":"","name":"Pattern Analysis","minNumFiles":"1","useMetadata":true,"useSubjectClassification":true,"useAudioDetails":true,"useBarcodeDetection":true,"useSoundClassification":true,"prompt":"Identify and describe any patterns or trends in the content of the following files. Use the file names as headers.","useFaceDetection":true}',
  "Write Caption":
    '{"useAudioDetails":true,"useRectangleDetection":false,"acceptedFileExtensions":"","icon":"text-cursor-16","useBarcodeDetection":true,"name":"Write Caption","useSoundClassification":true,"minNumFiles":"1","useMetadata":false,"prompt":"Write a two-sentence caption for these files in the style of a typical image caption, based on their contents. Use the file names as headings. The caption should summarize the content and describe its overall purpose and significance.","useFaceDetection":false,"useSubjectClassification":true}',
  "Extract Visible Text":
    '{"useBarcodeDetection":true,"prompt":"I will give you information about files, including their contents, and I want you to output the text content. Preserve the original format of the content as best as possible. Always output something.","useSoundClassification":false,"name":"Extract Visible Text","minNumFiles":"1","useMetadata":false,"useSubjectClassification":false,"useAudioDetails":false,"icon":"text-16","useRectangleDetection":false,"acceptedFileExtensions":"","useFaceDetection":false}',
  "Compare Selected Files":
    '{"useFaceDetection":true,"prompt":"Compare and contrast the content, purpose, and significance of the following files. What are the similarities and differences between them? Format the response as one markdown paragraph.","useMetadata":true,"name":"Compare Selected Files","useAudioDetails":true,"useBarcodeDetection":true,"acceptedFileExtensions":"","useSoundClassification":true,"icon":"contrast-16","useSubjectClassification":true,"minNumFiles":"2","useRectangleDetection":true}',
  "Suggest File AI Commands":
    '{"minNumFiles":"0","icon":"desktop-16","name":"Suggest File AI Commands","prompt":"Based on my current commands for the File AI extension, suggest new commands to create. Provide suggestions for titles as well prompts. The prompts must be relevant to an AI that can read the content of files, get information about the system, and get outside  data such as calendar events. The commands must be unique. Format the response as a single markdown list. Here are the commands I currently have: {{fileAICommands}}","useSoundClassifications":false,"useFileMetadata":false,"acceptedFileExtensions":""}',
  "Assess Academic Validity":
    '{"name":"Assess Academic Validity","minNumFiles":"1","useBarcodeDetection":false,"useFaceDetection":false,"icon":"book-16","prompt":"Assess the academic validity of the following files based on their contents, the methodologies described within, and any results obtained. Use the file names as headings.","useAudioDetails":true,"acceptedFileExtensions":"","useMetadata":false,"useSubjectClassification":true,"useSoundClassification":false,"useRectangleDetection":false}',
  "Extract Vocabulary":
    '{"useBarcodeDetection":true,"prompt":"Extract the most difficult vocabulary words from the following files and define them. Format the response as a markdown list.","useSoundClassification":false,"name":"Extract Vocabulary","minNumFiles":"1","useMetadata":false,"useSubjectClassification":false,"useAudioDetails":true,"icon":"book-16","useRectangleDetection":false,"acceptedFileExtensions":"","useFaceDetection":false}',
  "Suggest Related File AI Prompts":
    '{"useRectangleDetection":false,"useBarcodeDetection":true,"minNumFiles":"1","useMetadata":false,"icon":"paragraph-16","prompt":"Suggest a list of 5 prompts for an AI that can read the content of selected files. The AI can\'t modify or create files. Give prompts based on the topic and structure of the following files. Don\'t refer to the AI. Prompts must be more than retrieving contents. Each prompt must be different. Each prompt must operate on selected files. Don\'t use the file names in the prompts. Give a paragraph identifying key relationships between your prompts and the topics of the provided files.","useSubjectClassification":true,"useFaceDetection":false,"useSoundClassification":true,"name":"Suggest Related File AI Prompts","acceptedFileExtensions":"","useAudioDetails":true}',
  "Meeting Agenda":
    '{"icon":"app-window-list-16","useAudioDetails":true,"useMetadata":false,"useSoundClassification":false,"useRectangleDetection":false,"acceptedFileExtensions":"","minNumFiles":"1","useBarcodeDetection":false,"useFaceDetection":false,"useSubjectClassification":false,"name":"Meeting Agenda","prompt":"Create a meeting agenda covering the contents of the following files. Use today\'s date and time, {{date}}, to provide headings and structure to the agenda."}',
  "Respond To Last Email":
    '{"prompt":"Generate a response to the following email:\\n###\\n{{lastEmail}}\\n###","useFileMetadata":false,"minNumFiles":"0","icon":"envelope-16","acceptedFileExtensions":"","name":"Respond To Last Email","useSoundClassifications":false}',
  "Create Notes":
    '{"useRectangleDetection":false,"useBarcodeDetection":true,"icon":"bullet-points-16","minNumFiles":"1","useMetadata":false,"prompt":"I want you to act as a notetaker. I will provide file names and their contents, and you will respond with a multi-level markdown list of well-structured, concise notes. The notes should be in your own words and should make connections between topics and ideas. Each list item should be at most 20 words long. Minimize the notes as much as possible. Here are the files:","useSubjectClassification":true,"useFaceDetection":false,"useSoundClassification":true,"name":"Create Notes","acceptedFileExtensions":"","useAudioDetails":true}',
  "Recently Headlines From 68k News":
    '{"useFileMetadata":false,"minNumFiles":"0","acceptedFileExtensions":"","prompt":"Discuss the recent headlines from 68k News:\\n###\\n{{http://68k.news}}\\n###","name":"Recent Headlines from 68k News","useSoundClassifications":false,"icon":"important-01-16"}',
  "Generate Questions":
    '{"useAudioDetails":true,"useSubjectClassification":true,"useRectangleDetection":true,"useFaceDetection":true,"minNumFiles":"1","useBarcodeDetection":true,"useMetadata":true,"acceptedFileExtensions":"","prompt":"Generate questions based on the content of each of the following files, their metadata, filename, type, and other information. Format the response as a markdown list.","icon":"question-mark-circle-16","name":"Generate Questions","useSoundClassification":true}',
  "Suggest Improvements":
    '{"useSubjectClassification":true,"useRectangleDetection":true,"useAudioDetails":true,"useMetadata":true,"prompt":"Suggest improvements to the content of the following files. Use the file names as headings. Format the response as a markdown list.","minNumFiles":"1","useSoundClassification":true,"name":"Suggest Improvements","acceptedFileExtensions":"","useBarcodeDetection":true,"useFaceDetection":true,"icon":"stars-16"}',
  "Create Slides":
    '{"minNumFiles":"1","prompt":"Generate 3 or more slideshow slides for each of the following files based on their content. Each slide should have 3 or 4 meaningful bullet points. Organize the slides by topic. Format the slides as markdown lists with \'---\' separating each slide. Describe an image to include with each slide. Suggest links related to each slide\'s content. Provide an appropriate title for the slideshow at the beginning of the response.","useMetadata":false,"icon":"play-16","useAudioDetails":true,"useRectangleDetection":false,"acceptedFileExtensions":"","useSoundClassification":true,"useBarcodeDetection":true,"useFaceDetection":false,"name":"Create Slides","useSubjectClassification":true}',
  "Write Introduction":
    '{"useBarcodeDetection":true,"name":"Write Introduction","acceptedFileExtensions":"","useAudioDetails":true,"useFaceDetection":false,"icon":"text-cursor-16","useRectangleDetection":false,"useSoundClassification":true,"useMetadata":false,"prompt":"Write improved introduction sections for the following files in the style of an academic research paper. Use the file names as headings. The introductions must be at least 3 paragraphs long and describe what the file\'s contents are about, in future tense, as well as provide background information and a summary of the results. If the introduction includes a list, briefly describe the list instead of listing all elements.","minNumFiles":"1","useSubjectClassification":true}',
  "Translate To English":
    '{"useRectangleDetection":false,"useBarcodeDetection":true,"icon":"text-16","useMetadata":false,"minNumFiles":"1","prompt":"Translate the following files to English, using the file names as headings. Reword the translations so that they make sense in plain English. If the phrase is well known in either English or the source language, use the most commonly accepted translation.","useSubjectClassification":false,"useFaceDetection":false,"useSoundClassification":false,"name":"Translate To English","acceptedFileExtensions":"","useAudioDetails":true}',
  "Identify Relationships":
    '{"acceptedFileExtensions":"","icon":"box-16","useBarcodeDetection":true,"minNumFiles":"2","name":"Identify Relationships","prompt":"In one paragraph, identify any relationships that might exist between the following files based on their content and the topics they mention. Always identify some relationship, even if it is very general. Explain a use for the files together that none of them have individually.","useAudioDetails":true,"useRectangleDetection":true,"useFaceDetection":false,"useSoundClassification":true,"useMetadata":true,"useSubjectClassification":true}',
  "Detect Bias":
    '{"prompt":"Identify and explain the significance of any biases in the content of the following files. Discuss what the risks and dangers of those biases are, and discuss how those risks could be minimized.","name":"Detect Bias","useRectangleDetection":false,"useMetadata":false,"acceptedFileExtensions":"","icon":"chevron-right-16","useSoundClassification":false,"useAudioDetails":true,"useFaceDetection":false,"minNumFiles":"1","useBarcodeDetection":false,"useSubjectClassification":false}',
  "Summarize Spoken Audio":
    '{"acceptedFileExtensions":"","useRectangleDetection":false,"useMetadata":false,"minNumFiles":"1","useSoundClassification":false,"useBarcodeDetection":false,"prompt":"Summarize and assess the the following audio files using the file names as headings. Discuss the transcribed text\'s purpose and significance. Here are the audio transcriptions:","useFaceDetection":false,"name":"Summarize Spoken Audio","useAudioDetails":true,"useSubjectClassification":false,"icon":"speaker-on-16"}',
  "Find Errors":
    '{"minNumFiles":"1","useMetadata":false,"name":"Find Errors","useSubjectClassification":false,"useAudioDetails":true,"useFaceDetection":false,"icon":"bug-16","useSoundClassification":false,"useRectangleDetection":false,"acceptedFileExtensions":"","prompt":"What errors and inconsistencies in the following files, why are they significant, and how can I fix them? Format the response as markdown list of sentences with the file names in bold. Use the file names as headings.","useBarcodeDetection":true}',
  "Summarize Clipboard":
    '{"prompt":"Summarize the following text, providing specific details.\\n###\\n{{clipboardText}}\\n###","name":"Summarize Clipboard","useFaceDetection":false,"useSubjectClassification":false,"icon":"copy-clipboard-16","useMetadata":false,"useSoundClassification":false,"acceptedFileExtensions":"","useRectangleDetection":false,"minNumFiles":"0","useAudioDetails":false,"useBarcodeDetection":false}',
  "Extract Named Entities":
    '{"prompt":"What are the named entities in the following files, and what are their meanings and purpose? Clarify any abbreviations. Format the response as markdown list of sentences with the entity terms in bold. Use the file names as headings.","useAudioDetails":true,"useMetadata":false,"useSoundClassification":false,"useRectangleDetection":false,"minNumFiles":"1","acceptedFileExtensions":"","useBarcodeDetection":true,"useFaceDetection":false,"useSubjectClassification":false,"name":"Extract Named Entities","icon":"person-lines-16"}',
  "Recommend Apps":
    '{"useSoundClassification":false,"name":"Recommend Apps","icon":"app-window-grid-3x3-16","acceptedFileExtensions":"","useBarcodeDetection":false,"useFaceDetection":false,"minNumFiles":"0","useRectangleDetection":false,"useMetadata":false,"useAudioDetails":false,"prompt":"Based on the list of apps I have installed, recommend 10 additional macOS applications that I might enjoy. Explain the significance of the relationship between each recommendation and my installed apps. Use any knowledge you have about the apps to inform your suggestions. Format the output as a markdown list. At the start, provide a paragraph analyzing common themes of my apps, directed at me.\\n\\nHere is the list of apps I have installed:\\n###\\n{{installedApps}}\\n###","useSubjectClassification":false}',
  "Compose Response":
    '{"acceptedFileExtensions":"","icon":"text-cursor-16","useBarcodeDetection":true,"minNumFiles":"1","prompt":"Compose a response to the following files in the style of an email. Sign the email with the name \\"{{user}}\\"","name":"Compose Response","useAudioDetails":true,"useRectangleDetection":false,"useFaceDetection":false,"useSoundClassification":true,"useMetadata":false,"useSubjectClassification":true}',
  "Extract Phone Numbers":
    '{"prompt":"Identify all phone numbers in the following files and list them using markdown. Include anything that might be a phone number. If possible, provide the name of the person or company to which the phone number belongs.","name":"Extract Phone Numbers","useRectangleDetection":false,"useMetadata":false,"acceptedFileExtensions":"","icon":"phone-16","useSoundClassification":false,"useAudioDetails":true,"useFaceDetection":false,"minNumFiles":"1","useBarcodeDetection":true,"useSubjectClassification":false}',
  "Extend File":
    '{"useRectangleDetection":false,"useBarcodeDetection":false,"minNumFiles":"1","useMetadata":false,"icon":"arrows-expand-16","prompt":"Generate new content for the following files using the same style as the rest of the file\'s content. Explain how the new content fits with the rest. Do not repeat the current content. Use the file names as headings.","useSubjectClassification":false,"useFaceDetection":false,"useSoundClassification":false,"name":"Extend File","acceptedFileExtensions":"","useAudioDetails":true}',
  "Suggest Hashtags":
    '{"useRectangleDetection":false,"useBarcodeDetection":true,"prompt":"Suggest hashtags for the following files based on their contents. Use the file names as markdown headings.","minNumFiles":"1","useMetadata":false,"icon":"hashtag-16","useSubjectClassification":true,"useFaceDetection":true,"useSoundClassification":true,"name":"Suggest Hashtags","acceptedFileExtensions":"","useAudioDetails":true}',
  "Write Conclusion":
    '{"prompt":"Write conclusions for the following files in the style of the rest of their content, using the file names as headers. The conclusion should wrap up the meaning, purpose, significance, pitfalls, room to improvement, and suggest plans for future work.","useMetadata":false,"useRectangleDetection":false,"useSubjectClassification":true,"acceptedFileExtensions":"","icon":"text-cursor-16","name":"Write Conclusion","useBarcodeDetection":true,"minNumFiles":"1","useSoundClassification":true,"useAudioDetails":true,"useFaceDetection":false}',
  "Historical Context":
    '{"minNumFiles":"1","useMetadata":false,"name":"Historical Context","useSubjectClassification":true,"useAudioDetails":true,"useFaceDetection":false,"icon":"rewind-16","useSoundClassification":true,"useRectangleDetection":false,"prompt":"Based on the topics mentioned in the following files, provide a list of the top 5 most significant relevant historical facts. Ensure all facts are truthful. Do not make up anything. Additionally, provide a paragraph discussing a historical fact that relates to the entire content of the file.","acceptedFileExtensions":"","useBarcodeDetection":true}',
  "Create Flashcards":
    '{"useRectangleDetection":false,"icon":"blank-document-16","acceptedFileExtensions":"","name":"Create Flashcards","minNumFiles":"1","useMetadata":false,"useSubjectClassification":true,"useAudioDetails":true,"useBarcodeDetection":true,"useSoundClassification":true,"prompt":"Create 3 Anki flashcards based on the content of the following files. Format the response as markdown with the bold questions and plaintext answers. Separate each entry with \'---\'.","useFaceDetection":false}',
  "Extract Code":
    '{"useMetadata":false,"name":"Extract Code","icon":"code-16","useSubjectClassification":false,"useBarcodeDetection":false,"minNumFiles":"1","useRectangleDetection":false,"useFaceDetection":false,"acceptedFileExtensions":"","useSoundClassification":false,"useAudioDetails":false,"prompt":"Extract lines of code written in programming languages from the following files. Format the response as markdown code blocks. Place the programming language used in each block as the heading above it. Provide a brief description of what the code does below each block. Do not provide any other commentary."}',
  "Summarize Current Tab":
    '{"icon":"app-window-16","useSoundClassifications":false,"useFileMetadata":false,"name":"Summarize Current Tab","acceptedFileExtensions":"","minNumFiles":"0","prompt":"Based on the following text obtained from the active browser tab, what am I looking at? In your answer, discuss the content and meaning of the website. If the URL or the text are blank, report an error. For context, here is the url: {{currentURL}}:\\n\\nAnd here is the text:\\n###\\n{{currentTabText}}\\n###"}',
  "Assess File Overlap":
    '{"useSubjectClassification":true,"useMetadata":false,"useFaceDetection":false,"minNumFiles":"2","prompt":"What overlaps in content or ideas exists between the following files? What are the similarities?","useSoundClassification":true,"useAudioDetails":true,"name":"Assess File Overlap","useBarcodeDetection":true,"icon":"contrast-16","useRectangleDetection":false,"acceptedFileExtensions":""}',
  "Location Significance":
    '{"useMetadata":false,"useSubjectClassification":false,"prompt":"What is the significance and history of {{location}}? Format your response as a friendly paragraph.","useFaceDetection":false,"name":"Location Significance","acceptedFileExtensions":"","minNumFiles":"0","useAudioDetails":false,"useBarcodeDetection":false,"icon":"geopin-16","useRectangleDetection":false,"useSoundClassification":false}',
  "Suggest Project Ideas":
    '{"prompt":"I want you to act as a project idea generator. I will provide file names and their contents, and you will response with a list of project ideas based on the content of each file. Format the response as a markdown list. Use the file names as headings. Here are the files:","useMetadata":false,"useRectangleDetection":false,"useSubjectClassification":true,"acceptedFileExtensions":"","icon":"hammer-16","name":"Suggest Project Ideas","useBarcodeDetection":true,"minNumFiles":"1","useSoundClassification":true,"useAudioDetails":true,"useFaceDetection":true}',
  "Write Discussion":
    '{"useAudioDetails":true,"useSubjectClassification":true,"useSoundClassification":true,"acceptedFileExtensions":"","name":"Write Discussion","icon":"text-cursor-16","useMetadata":false,"useBarcodeDetection":true,"useRectangleDetection":false,"prompt":"Write a new discussion section for each of the following files in the style of an academic research paper. The discussion should be past tense and highlight the paper\'s successes. Use the file names as headings.","minNumFiles":"1","useFaceDetection":false}',
  "Weather Forecast":
    '{"minNumFiles":"0","acceptedFileExtensions":"","name":"Weather Forecast","prompt":"Provide a weather report based on the following forecast data for the next 7 days in {{location}}: ###{{weather}}###\\n\\nDiscuss how this might affect my events over the next week. Consider the purpose and type of each event. My events are: ###{{weekEvents}}###","useSoundClassifications":false,"useFileMetadata":false,"icon":"cloud-sun-16"}',
  "Condense File":
    '{"useAudioDetails":true,"useSubjectClassification":false,"useSoundClassification":false,"name":"Condense File","acceptedFileExtensions":"","useMetadata":false,"icon":"arrows-contract-16","useBarcodeDetection":false,"useRectangleDetection":false,"prompt":"Condense the content of the following files as much as possible. Summarize sentences. Use abbreviations where possible. If the response includes any lists, remove them and briefly describe them instead. Condense clarifying language as much as possible. Use the file names as headings.","minNumFiles":"1","useFaceDetection":false}',
  "Summarize Last Email":
    '{"minNumFiles":"0","icon":"envelope-16","name":"Summarize Last Email","prompt":"Summarize my most recent email and discuss its significance. I am the recipient. Format the response as a paragraph directed to me. Here is the email:\\n###\\n{{lastEmail}}\\n###","useSoundClassifications":false,"useFileMetadata":false,"acceptedFileExtensions":""}',
  "Write Abstract":
    '{"useSubjectClassification":true,"minNumFiles":"1","useSoundClassification":true,"acceptedFileExtensions":"","prompt":"Write an abstract for the following files in the style of an academic research paper. Use the file names as headings. If the abstract includes a list, briefly describe it instead of listing all elements.","useRectangleDetection":false,"useMetadata":false,"name":"Write Abstract","useBarcodeDetection":true,"useFaceDetection":false,"useAudioDetails":true,"icon":"text-cursor-16"}',
  "Suggest Title":
    '{"prompt":"Suggest new titles for the following files based on their content and topics mentioned. Use the file names as headings.","name":"Suggest Title","useRectangleDetection":false,"useMetadata":false,"acceptedFileExtensions":"","icon":"text-16","useSoundClassification":true,"useAudioDetails":true,"useFaceDetection":false,"minNumFiles":"1","useBarcodeDetection":true,"useSubjectClassification":true}',
  "Table Of Contents":
    '{"useSoundClassification":true,"useBarcodeDetection":true,"useRectangleDetection":false,"useFaceDetection":false,"acceptedFileExtensions":"","useSubjectClassification":true,"minNumFiles":"1","icon":"bullet-points-16","useAudioDetails":true,"useMetadata":false,"name":"Table Of Contents","prompt":"Generate a table of contents for each of the following files based on their content. Use the file names as headings. For each item in the table, provide an percent estimation of how far into the document the associated content occurs. Format the response as a markdown list."}',
  "What Is This?":
    '{"useRectangleDetection":true,"useBarcodeDetection":true,"useMetadata":true,"icon":"question-mark-circle-16","prompt":"Based on the content of the following files, answer this question: What is this? Use the file names as headings.","minNumFiles":"1","useSubjectClassification":true,"useFaceDetection":true,"useSoundClassification":true,"name":"What Is This?","acceptedFileExtensions":"","useAudioDetails":true}',
  "Make Poem":
    '{"useAudioDetails":true,"useSubjectClassification":true,"useSoundClassification":true,"acceptedFileExtensions":"","name":"Make Poem","icon":"short-paragraph-16","useMetadata":false,"useBarcodeDetection":true,"useRectangleDetection":false,"prompt":"Make rhyming poems about the the following files. Be creative and include references to the content and purpose of the file in unexpected ways. Do not summarize the file. Make each poem at least 3 stanzas long, but longer for longer files. Use the file names as markdown headings.","minNumFiles":"1","useFaceDetection":true}',
  "Suggest Tools":
    '{"useRectangleDetection":false,"useBarcodeDetection":true,"useMetadata":true,"icon":"wrench-screwdriver-16","prompt":"Suggest tools to use based on the topics discussed in the following files. Explain why each tool is relevant. Use the file names as headings. Do not provide any commentary other than the list of tools and their explanations.","minNumFiles":"1","useSubjectClassification":true,"useFaceDetection":false,"useSoundClassification":true,"name":"Suggest Tools","acceptedFileExtensions":"","useAudioDetails":true}',
  "Make Song":
    '{"acceptedFileExtensions":"","icon":"music-16","useBarcodeDetection":true,"minNumFiles":"1","prompt":"Make a song based on the content of the following files. Provide a name for the song.","name":"Make Song","useAudioDetails":true,"useRectangleDetection":false,"useFaceDetection":true,"useSoundClassification":true,"useMetadata":false,"useSubjectClassification":true}',
  "Extract Email Addresses":
    '{"useRectangleDetection":false,"icon":"envelope-16","acceptedFileExtensions":"","name":"Extract Email Addresses","minNumFiles":"1","useMetadata":false,"useSubjectClassification":false,"useAudioDetails":false,"useBarcodeDetection":false,"useSoundClassification":false,"prompt":"Extract email addresses from the following files and list them as markdown links:","useFaceDetection":false}',
};
