/** A catalog entry uses the company's public website as its logo lookup key. */
export type Company = {
  /** Display name; does not need to match the website hostname. */
  name: string;
  /** Bare public hostname, without a protocol or path. */
  domain: string;
  /** Extra search terms for product names and common aliases. */
  keywords?: string[];
};

/** Curated discovery catalog; users can also look up any public domain. */
export const companies: Company[] = [
  { name: "Apple", domain: "apple.com", keywords: ["iphone", "mac"] },
  { name: "Google", domain: "google.com", keywords: ["alphabet"] },
  {
    name: "Microsoft",
    domain: "microsoft.com",
    keywords: ["windows", "office"],
  },
  { name: "OpenAI", domain: "openai.com", keywords: ["chatgpt"] },
  { name: "Anthropic", domain: "anthropic.com", keywords: ["claude"] },
  { name: "Figma", domain: "figma.com" },
  { name: "Notion", domain: "notion.so" },
  { name: "Linear", domain: "linear.app" },
  { name: "Slack", domain: "slack.com" },
  { name: "Stripe", domain: "stripe.com" },
  { name: "GitHub", domain: "github.com" },
  { name: "Vercel", domain: "vercel.com" },
  { name: "Raycast", domain: "raycast.com" },
  { name: "Spotify", domain: "spotify.com" },
  { name: "Airbnb", domain: "airbnb.com" },
  { name: "Amazon", domain: "amazon.com", keywords: ["aws"] },
  { name: "Adobe", domain: "adobe.com", keywords: ["photoshop"] },
  { name: "Asana", domain: "asana.com" },
  {
    name: "Atlassian",
    domain: "atlassian.com",
    keywords: ["jira", "confluence"],
  },
  { name: "Canva", domain: "canva.com" },
  { name: "Cloudflare", domain: "cloudflare.com" },
  { name: "Cursor", domain: "cursor.com" },
  { name: "Datadog", domain: "datadoghq.com" },
  { name: "Discord", domain: "discord.com" },
  { name: "Dropbox", domain: "dropbox.com" },
  { name: "Duolingo", domain: "duolingo.com" },
  { name: "Framer", domain: "framer.com" },
  { name: "GitLab", domain: "gitlab.com" },
  { name: "HubSpot", domain: "hubspot.com" },
  { name: "Instagram", domain: "instagram.com" },
  { name: "Intercom", domain: "intercom.com" },
  { name: "LinkedIn", domain: "linkedin.com" },
  { name: "Loom", domain: "loom.com" },
  { name: "Meta", domain: "meta.com", keywords: ["facebook"] },
  { name: "Miro", domain: "miro.com" },
  { name: "Monday", domain: "monday.com" },
  { name: "Netflix", domain: "netflix.com" },
  { name: "Nike", domain: "nike.com" },
  { name: "NVIDIA", domain: "nvidia.com" },
  { name: "PayPal", domain: "paypal.com" },
  { name: "Perplexity", domain: "perplexity.ai" },
  { name: "Pinterest", domain: "pinterest.com" },
  { name: "PostHog", domain: "posthog.com" },
  { name: "Reddit", domain: "reddit.com" },
  { name: "Resend", domain: "resend.com" },
  { name: "Revolut", domain: "revolut.com" },
  { name: "Salesforce", domain: "salesforce.com" },
  { name: "Samsung", domain: "samsung.com" },
  { name: "Sentry", domain: "sentry.io" },
  { name: "Shopify", domain: "shopify.com" },
  { name: "Snapchat", domain: "snapchat.com" },
  { name: "Square", domain: "squareup.com" },
  { name: "Supabase", domain: "supabase.com" },
  { name: "Tesla", domain: "tesla.com" },
  { name: "TikTok", domain: "tiktok.com" },
  { name: "Twitch", domain: "twitch.tv" },
  { name: "Uber", domain: "uber.com" },
  { name: "Webflow", domain: "webflow.com" },
  { name: "WhatsApp", domain: "whatsapp.com" },
  { name: "Wise", domain: "wise.com" },
  { name: "X", domain: "x.com", keywords: ["twitter"] },
  { name: "YouTube", domain: "youtube.com" },
  { name: "Zapier", domain: "zapier.com" },
  { name: "Zoom", domain: "zoom.us" },
];
