exports.icondir = "icons";

exports.logos = [
  "amazon",
  "aws",
  "authy",
  "bitcoin",
  "circle",
  "cloudflare",
  "coinbase",
  "dashlane",
  "digitalocean",
  "discord",
  "dropbox",
  "ea",
  "evernote",
  "facebook",
  "github",
  "gmail",
  "google",
  "heroku",
  "hootsuite",
  "hubspot",
  "ifttt",
  "kickstarter",
  "lastpass",
  "linode",
  "logmein",
  "mailchimp",
  "microsoft",
  "okta",
  "salesforce",
  "slack",
  "snapchat",
  "stripe",
  "teamviewer",
  "tumblr",
  "twitch",
  "twitter",
  "wordpress",
  "amazon",
  "aws",
  "authy",
  "bitcoin",
  "circle",
  "cloudflare",
  "coinbase",
  "dashlane",
  "digitalocean",
  "discord",
  "dropbox",
  "ea",
  "evernote",
  "facebook",
  "github",
  "gmail",
  "google",
  "heroku",
  "hootsuite",
  "hubspot",
  "ifttt",
  "kickstarter",
  "lastpass",
  "linode",
  "logmein",
  "mailchimp",
  "microsoft",
  "okta",
  "salesforce",
  "slack",
  "snapchat",
  "stripe",
  "teamviewer",
  "tumblr",
  "twitch",
  "twitter",
  "wordpress",
];

exports.genericColors = [
  { name: "black", value: "#464646" },
  { name: "blue", value: "#098FCE" },
  { name: "green", value: "#3DA329" },
  { name: "orange", value: "#F59E27" },
  { name: "purple", value: "#7408B4" },
  { name: "red", value: "#DF1112" },
];

exports.icons = ["key"];
