/**
 * Shared Saturn search tokenizer — turns raw text into index/query terms.
 *
 * Mirrored in the Saturn app (main/saturn/tokenize.ts) and the saturn-raycast
 * extension (src/lib/tokenize.ts). Keep both copies byte-identical; parity is
 * enforced by saturn-raycast/test/tokenizer-parity.mjs.
 */

/** Unicode letters/numbers — CJK-safe, keeps accents; punctuation/whitespace split. */
const TOKEN_RE = /[\p{L}\p{N}]+/gu;

/** Cap on body tokens per document so a huge page can't bloat the index. */
export const BODY_TOKEN_CAP = 15000;

/**
 * Common English function words — high DF, low discriminative value.
 * Dropped from both the inverted index and queries so sizes stay small and
 * AND search isn't bloated by "the"/"a"/etc.
 */
const STOP_WORDS = new Set([
  "a",
  "about",
  "above",
  "after",
  "again",
  "against",
  "all",
  "am",
  "an",
  "and",
  "any",
  "are",
  "aren't",
  "as",
  "at",
  "be",
  "because",
  "been",
  "before",
  "being",
  "below",
  "between",
  "both",
  "but",
  "by",
  "can",
  "can't",
  "cannot",
  "could",
  "couldn't",
  "did",
  "didn't",
  "do",
  "does",
  "doesn't",
  "doing",
  "don't",
  "down",
  "during",
  "each",
  "few",
  "for",
  "from",
  "further",
  "had",
  "hadn't",
  "has",
  "hasn't",
  "have",
  "haven't",
  "having",
  "he",
  "he'd",
  "he'll",
  "he's",
  "her",
  "here",
  "here's",
  "hers",
  "herself",
  "him",
  "himself",
  "his",
  "how",
  "how's",
  "i",
  "i'd",
  "i'll",
  "i'm",
  "i've",
  "if",
  "in",
  "into",
  "is",
  "isn't",
  "it",
  "it's",
  "its",
  "itself",
  "let's",
  "me",
  "more",
  "most",
  "mustn't",
  "my",
  "myself",
  "no",
  "nor",
  "not",
  "of",
  "off",
  "on",
  "once",
  "only",
  "or",
  "other",
  "ought",
  "our",
  "ours",
  "ourselves",
  "out",
  "over",
  "own",
  "same",
  "shan't",
  "she",
  "she'd",
  "she'll",
  "she's",
  "should",
  "shouldn't",
  "so",
  "some",
  "such",
  "than",
  "that",
  "that's",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "there",
  "there's",
  "these",
  "they",
  "they'd",
  "they'll",
  "they're",
  "they've",
  "this",
  "those",
  "through",
  "to",
  "too",
  "under",
  "until",
  "up",
  "very",
  "was",
  "wasn't",
  "we",
  "we'd",
  "we'll",
  "we're",
  "we've",
  "were",
  "weren't",
  "what",
  "what's",
  "when",
  "when's",
  "where",
  "where's",
  "which",
  "while",
  "who",
  "who's",
  "whom",
  "why",
  "why's",
  "with",
  "won't",
  "would",
  "wouldn't",
  "you",
  "you'd",
  "you'll",
  "you're",
  "you've",
  "your",
  "yours",
  "yourself",
  "yourselves",
]);

/** Keep content terms; drop stop words and lone Latin letters from contractions. */
function keepToken(token: string): boolean {
  if (STOP_WORDS.has(token)) return false;
  // "it's" / "don't" → leftover "s" / "t" after punctuation split
  if (token.length === 1 && token >= "a" && token <= "z") return false;
  return true;
}

/** Lowercases (NFC), splits into terms, and drops English stop words. */
export function tokenize(text: string): string[] {
  const raw = text.normalize("NFC").toLowerCase().match(TOKEN_RE) ?? [];
  return raw.filter(keepToken);
}

/** Tokenize long-form body text, capped at BODY_TOKEN_CAP terms. */
export function tokenizeBody(text: string): string[] {
  return tokenize(text).slice(0, BODY_TOKEN_CAP);
}
