export const typesAndTitles = {
  // ASN
  asn: { type: "number", title: "ASN" },
  descr: { type: "string", title: "Description" },
  country: { type: "string", title: "Country" },
  active: { type: "boolean", title: "Active" },
  org: { type: "string", title: "Organization" },
  domain: { type: "link", title: "Domain" },
  abuse: { type: "email", title: "Abuse" },
  type: { type: "string", title: "Type" },
  created: { type: "string", title: "Created" },
  updated: { type: "string", title: "Updated" },
  rir: { type: "string", title: "Regional Internet Registry" },
  whois: { type: "link", title: "WHOIS" },
  prefixes: { type: "array", title: "Prefixes" },
  prefixesIPv6: { type: "array", title: "Prefixes IPv6" },
  // IP
  is_bogon: { type: "boolean", title: "Bogon (Non Routable)" },
  is_mobile: { type: "boolean", title: "Mobile ISP" },
  is_crawler: { type: "boolean", title: "Crawler" },
  is_datacenter: { type: "boolean", title: "Datacenter" },
  is_tor: { type: "boolean", title: "TOR Exit Node" },
  is_proxy: { type: "boolean", title: "Proxy Exit Node" },
  is_vpn: { type: "boolean", title: "VPN Exit Node" },
  is_abuser: { type: "boolean", title: "Abuser" },
  // MISC
  elapsed_ms: { type: "number", title: "Time Elapsed (ms)" },
  ip: { type: "string", title: "IP" },
  // Location
  latitude: { type: "number", title: "Latitude" },
  longitude: { type: "number", title: "Longitude" },
  local_time: { type: "number", title: "Local Time" },
  local_time_unix: { type: "number", title: "Local Time (UNIX)" },
  is_dst: { type: "boolean", title: "Daylight Saving Time" },
};
