import type { VoiceConfig } from "../api/types";

type VoiceRow = readonly [id: string, name: string, gender: VoiceConfig["gender"], category: string];

const OFFICIAL_TTS_20_VOICE_ROWS = [
  ["zh_female_vv_uranus_bigtts", "Vivi 2.0", "female", "通用场景 2.0"],
  ["zh_female_xiaohe_uranus_bigtts", "小何 2.0", "female", "通用场景 2.0"],
  ["zh_male_m191_uranus_bigtts", "云舟 2.0", "male", "通用场景 2.0"],
  ["zh_male_taocheng_uranus_bigtts", "小天 2.0", "male", "通用场景 2.0"],
  ["zh_male_liufei_uranus_bigtts", "刘飞 2.0", "male", "通用场景 2.0"],
  ["zh_female_sophie_uranus_bigtts", "魅力苏菲 2.0", "female", "通用场景 2.0"],
  ["zh_female_qingxinnvsheng_uranus_bigtts", "清新女声 2.0", "female", "通用场景 2.0"],
  ["zh_female_tianmeixiaoyuan_uranus_bigtts", "甜美小源 2.0", "female", "通用场景 2.0"],
  ["zh_female_tianmeitaozi_uranus_bigtts", "甜美桃子 2.0", "female", "通用场景 2.0"],
  ["zh_female_shuangkuaisisi_uranus_bigtts", "爽快思思 2.0", "female", "通用场景 2.0"],
  ["zh_female_linjianvhai_uranus_bigtts", "邻家女孩 2.0", "female", "通用场景 2.0"],
  ["zh_male_shaonianzixin_uranus_bigtts", "少年梓辛 / Brayan 2.0", "male", "通用场景 2.0"],
  ["zh_female_meilinvyou_uranus_bigtts", "魅力女友 2.0", "female", "通用场景 2.0"],
  ["zh_female_wenroumama_uranus_bigtts", "温柔妈妈 2.0", "female", "通用场景 2.0"],
  ["zh_male_jieshuoxiaoming_uranus_bigtts", "解说小明 2.0", "male", "通用场景 2.0"],
  ["zh_female_tvbnv_uranus_bigtts", "TVB女声 2.0", "female", "通用场景 2.0"],
  ["zh_male_yizhipiannan_uranus_bigtts", "译制片男 2.0", "male", "通用场景 2.0"],
  ["zh_female_qiaopinv_uranus_bigtts", "俏皮女声 2.0", "female", "通用场景 2.0"],
  ["zh_male_linjiananhai_uranus_bigtts", "邻家男孩 2.0", "male", "通用场景 2.0"],
  ["zh_male_ruyaqingnian_uranus_bigtts", "儒雅青年 2.0", "male", "通用场景 2.0"],
  ["zh_male_wennuanahu_uranus_bigtts", "温暖阿虎 / Alvin 2.0", "male", "通用场景 2.0"],
  ["zh_male_naiqimengwa_uranus_bigtts", "奶气萌娃 2.0", "child", "通用场景 2.0"],
  ["zh_female_popo_uranus_bigtts", "婆婆 2.0", "female", "通用场景 2.0"],
  ["zh_female_gaolengyujie_uranus_bigtts", "高冷御姐 2.0", "female", "通用场景 2.0"],
  ["zh_male_aojiaobazong_uranus_bigtts", "傲娇霸总 2.0", "male", "通用场景 2.0"],
  ["zh_male_fanjuanqingnian_uranus_bigtts", "反卷青年 2.0", "male", "通用场景 2.0"],
  ["zh_female_wenroushunv_uranus_bigtts", "温柔淑女 2.0", "female", "通用场景 2.0"],
  ["zh_male_huolixiaoge_uranus_bigtts", "活力小哥 2.0", "male", "通用场景 2.0"],
  ["zh_female_mengyatou_uranus_bigtts", "萌丫头 / Cutey 2.0", "female", "通用场景 2.0"],
  ["zh_female_tiexinnvsheng_uranus_bigtts", "贴心女声 / Candy 2.0", "female", "通用场景 2.0"],
  ["zh_female_jitangmei_uranus_bigtts", "鸡汤妹妹 / Hope 2.0", "female", "通用场景 2.0"],
  ["zh_male_cixingjieshuonan_uranus_bigtts", "磁性解说男声 / Morgan 2.0", "male", "通用场景 2.0"],
  ["zh_male_liangsangmengzai_uranus_bigtts", "亮嗓萌仔 2.0", "child", "通用场景 2.0"],
  ["zh_female_kailangjiejie_uranus_bigtts", "开朗姐姐 2.0", "female", "通用场景 2.0"],
  ["zh_male_gaolengchenwen_uranus_bigtts", "高冷沉稳 2.0", "male", "通用场景 2.0"],
  ["zh_male_shenyeboke_uranus_bigtts", "深夜播客 2.0", "male", "通用场景 2.0"],
  ["zh_female_jiaochuannv_uranus_bigtts", "娇喘女声 2.0", "female", "通用场景 2.0"],
  ["zh_male_kailangdidi_uranus_bigtts", "开朗弟弟 2.0", "male", "通用场景 2.0"],
  ["zh_female_chanmeinv_uranus_bigtts", "谄媚女声 2.0", "female", "通用场景 2.0"],
  ["zh_female_qinqienv_uranus_bigtts", "亲切女声 2.0", "female", "通用场景 2.0"],
  ["zh_male_kuailexiaodong_uranus_bigtts", "快乐小东 2.0", "male", "通用场景 2.0"],
  ["zh_male_kailangxuezhang_uranus_bigtts", "开朗学长 2.0", "male", "通用场景 2.0"],
  ["zh_male_youyoujunzi_uranus_bigtts", "悠悠君子 2.0", "male", "通用场景 2.0"],
  ["zh_female_wenjingmaomao_uranus_bigtts", "文静毛毛 2.0", "female", "通用场景 2.0"],
  ["zh_female_zhixingnv_uranus_bigtts", "知性女声 2.0", "female", "通用场景 2.0"],
  ["zh_male_qingshuangnanda_uranus_bigtts", "清爽男大 2.0", "male", "通用场景 2.0"],
  ["zh_male_yuanboxiaoshu_uranus_bigtts", "渊博小叔 2.0", "male", "通用场景 2.0"],
  ["zh_male_yangguangqingnian_uranus_bigtts", "阳光青年 2.0", "male", "通用场景 2.0"],
  ["zh_female_qingchezizi_uranus_bigtts", "清澈梓梓 2.0", "female", "通用场景 2.0"],
  ["zh_female_tianmeiyueyue_uranus_bigtts", "甜美悦悦 2.0", "female", "通用场景 2.0"],
  ["zh_female_xinlingjitang_uranus_bigtts", "心灵鸡汤 2.0", "female", "通用场景 2.0"],
  ["zh_male_wenrouxiaoge_uranus_bigtts", "温柔小哥 2.0", "male", "通用场景 2.0"],
  ["zh_female_roumeinvyou_uranus_bigtts", "柔美女友 2.0", "female", "通用场景 2.0"],
  ["zh_male_dongfanghaoran_uranus_bigtts", "东方浩然 2.0", "male", "通用场景 2.0"],
  ["zh_female_wenrouxiaoya_uranus_bigtts", "温柔小雅 2.0", "female", "通用场景 2.0"],
  ["zh_male_tiancaitongsheng_uranus_bigtts", "天才童声 2.0", "child", "通用场景 2.0"],
  ["zh_male_guanggaojieshuo_uranus_bigtts", "广告解说 2.0", "male", "通用场景 2.0"],

  ["zh_female_cancan_uranus_bigtts", "知性灿灿 2.0", "female", "角色扮演 2.0"],
  ["zh_female_sajiaoxuemei_uranus_bigtts", "撒娇学妹 2.0", "female", "角色扮演 2.0"],
  ["zh_female_zhishuaiyingzi_uranus_bigtts", "直率英子 2.0", "female", "角色扮演 2.0"],
  ["zh_male_silang_uranus_bigtts", "四郎 2.0", "male", "角色扮演 2.0"],
  ["zh_male_qingcang_uranus_bigtts", "擎苍 2.0", "male", "角色扮演 2.0"],
  ["zh_male_xionger_uranus_bigtts", "熊二 2.0", "male", "角色扮演 2.0"],
  ["zh_female_yingtaowanzi_uranus_bigtts", "樱桃丸子 2.0", "female", "角色扮演 2.0"],
  ["zh_male_lanyinmianbao_uranus_bigtts", "懒音绵宝 2.0", "male", "角色扮演 2.0"],
  ["zh_female_gufengshaoyu_uranus_bigtts", "古风少御 2.0", "female", "角色扮演 2.0"],
  ["zh_male_lubanqihao_uranus_bigtts", "鲁班七号 2.0", "child", "角色扮演 2.0"],
  ["zh_female_linxiao_uranus_bigtts", "林潇 2.0", "female", "角色扮演 2.0"],
  ["zh_female_lingling_uranus_bigtts", "玲玲姐姐 2.0", "female", "角色扮演 2.0"],
  ["zh_female_chunribu_uranus_bigtts", "春日部姐姐 2.0", "female", "角色扮演 2.0"],
  ["zh_male_tangseng_uranus_bigtts", "唐僧 2.0", "male", "角色扮演 2.0"],
  ["zh_male_zhuangzhou_uranus_bigtts", "庄周 2.0", "male", "角色扮演 2.0"],
  ["zh_male_zhubajie_uranus_bigtts", "猪八戒 2.0", "male", "角色扮演 2.0"],
  ["zh_female_ganmaodianyin_uranus_bigtts", "感冒电音姐姐 2.0", "female", "角色扮演 2.0"],
  ["zh_female_nvleishen_uranus_bigtts", "女雷神 2.0", "female", "角色扮演 2.0"],
  ["zh_female_wuzetian_uranus_bigtts", "武则天 2.0", "female", "角色扮演 2.0"],
  ["zh_female_gujie_uranus_bigtts", "顾姐 2.0", "female", "角色扮演 2.0"],
  ["saturn_zh_female_tiaopigongzhu_tob", "调皮公主", "female", "角色扮演 2.0"],
  ["saturn_zh_female_keainvsheng_tob", "可爱女生", "female", "角色扮演 2.0"],
  ["saturn_zh_male_shuanglangshaonian_tob", "爽朗少年", "male", "角色扮演 2.0"],
  ["saturn_zh_male_tiancaitongzhuo_tob", "天才同桌", "male", "角色扮演 2.0"],
  ["saturn_zh_female_cancan_tob", "知性灿灿", "female", "角色扮演 2.0"],

  ["zh_female_peiqi_uranus_bigtts", "佩奇猪 2.0", "child", "视频配音 2.0"],
  ["zh_male_sunwukong_uranus_bigtts", "猴哥 2.0", "male", "视频配音 2.0"],
  ["zh_male_dayi_uranus_bigtts", "大壹 2.0", "male", "视频配音 2.0"],
  ["zh_female_mizai_uranus_bigtts", "黑猫侦探社咪仔 2.0", "female", "视频配音 2.0"],
  ["zh_female_jitangnv_uranus_bigtts", "鸡汤女 2.0", "female", "视频配音 2.0"],
  ["zh_female_liuchangnv_uranus_bigtts", "流畅女声 2.0", "female", "视频配音 2.0"],
  ["zh_male_ruyayichen_uranus_bigtts", "儒雅逸辰 2.0", "male", "视频配音 2.0"],

  ["zh_female_xiaoxue_uranus_bigtts", "儿童绘本 2.0", "child", "有声阅读 2.0"],
  ["zh_male_baqiqingshu_uranus_bigtts", "霸气青叔 2.0", "male", "有声阅读 2.0"],
  ["zh_male_xuanyijieshuo_uranus_bigtts", "悬疑解说 2.0", "male", "有声阅读 2.0"],
  ["zh_female_shaoergushi_uranus_bigtts", "少儿故事 2.0", "child", "有声阅读 2.0"],

  ["zh_female_yingyujiaoxue_uranus_bigtts", "Tina老师 2.0", "female", "教育场景 2.0"],

  ["zh_female_kefunvsheng_uranus_bigtts", "暖阳女声 2.0", "female", "客服场景 2.0"],
  ["saturn_zh_female_qingyingduoduo_cs_tob", "轻盈朵朵 2.0", "female", "客服场景 2.0"],
  ["saturn_zh_female_wenwanshanshan_cs_tob", "温婉珊珊 2.0", "female", "客服场景 2.0"],
  ["saturn_zh_female_reqingaina_cs_tob", "热情艾娜 2.0", "female", "客服场景 2.0"],
  ["saturn_zh_male_qingxinmumu_cs_tob", "清新沐沐 2.0", "male", "客服场景 2.0"],

  ["en_male_tim_uranus_bigtts", "Tim", "male", "多语种 2.0"],
  ["en_female_dacey_uranus_bigtts", "Dacey", "female", "多语种 2.0"],
  ["en_female_stokie_uranus_bigtts", "Stokie", "female", "多语种 2.0"],
] satisfies VoiceRow[];

const OFFICIAL_TTS_20_VOICES: VoiceConfig[] = OFFICIAL_TTS_20_VOICE_ROWS.map(([id, name, gender, category]) => ({
  id,
  name,
  gender,
  category,
  free: false,
  model: "seed-tts-2.0",
}));

export const VOICES: VoiceConfig[] = [
  ...OFFICIAL_TTS_20_VOICES,

  // ========== TTS 1.0 通用场景 (mars) ==========
  {
    id: "zh_female_cancan_mars_bigtts",
    name: "灿灿",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_vv_mars_bigtts",
    name: "Vivi",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_qingyiyuxuan_mars_bigtts",
    name: "阳光阿辰",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_tianmeitaozi_mars_bigtts",
    name: "甜美桃子",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_qingxinnvsheng_mars_bigtts",
    name: "清新女声",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_zhixingnvsheng_mars_bigtts",
    name: "知性女声",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_qingshuangnanda_mars_bigtts",
    name: "清爽男大",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_wenrouxiaoge_mars_bigtts",
    name: "温柔小哥",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 通用场景 (moon) ==========
  {
    id: "zh_female_qinqienvsheng_moon_bigtts",
    name: "亲切女声",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_linjianvhai_moon_bigtts",
    name: "邻家女孩",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_yuanboxiaoshu_moon_bigtts",
    name: "渊博小叔",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_yangguangqingnian_moon_bigtts",
    name: "阳光青年",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_tianmeixiaoyuan_moon_bigtts",
    name: "甜美小源",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_qingchezizi_moon_bigtts",
    name: "清澈梓梓",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 通用场景 (wvae 对话) ==========
  {
    id: "zh_male_xudong_conversation_wvae_bigtts",
    name: "快乐小东",
    gender: "male",
    category: "对话",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_sophie_conversation_wvae_bigtts",
    name: "魅力苏菲",
    gender: "female",
    category: "对话",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_maomao_conversation_wvae_bigtts",
    name: "文静毛毛",
    gender: "female",
    category: "对话",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_M100_conversation_wvae_bigtts",
    name: "悠悠君子",
    gender: "male",
    category: "对话",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 有声阅读 (mars) ==========
  {
    id: "zh_male_qingcang_mars_bigtts",
    name: "擎苍",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_ruyaqingnian_mars_bigtts",
    name: "儒雅青年",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_baqiqingshu_mars_bigtts",
    name: "霸气青叔",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_gufengshaoyu_mars_bigtts",
    name: "古风少御",
    gender: "female",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_wenroushunv_mars_bigtts",
    name: "温柔淑女",
    gender: "female",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_fanjuanqingnian_mars_bigtts",
    name: "反卷青年",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_changtianyi_mars_bigtts",
    name: "悬疑解说",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 视频配音 (mars) ==========
  {
    id: "zh_male_jieshuonansheng_mars_bigtts",
    name: "磁性解说男声",
    gender: "male",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_jitangmeimei_mars_bigtts",
    name: "鸡汤妹妹",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_tiexinnvsheng_mars_bigtts",
    name: "贴心女声",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_mengyatou_mars_bigtts",
    name: "萌丫头",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_naiqimengwa_mars_bigtts",
    name: "奶气萌娃",
    gender: "child",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_chunhui_mars_bigtts",
    name: "广告解说",
    gender: "male",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_shaoergushi_mars_bigtts",
    name: "少儿故事",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_qiaopinvsheng_mars_bigtts",
    name: "俏皮女声",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 趣味口音 ==========
  {
    id: "zh_male_beijingxiaoye_moon_bigtts",
    name: "北京小爷",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_jingqiangkanye_moon_bigtts",
    name: "京腔侃爷",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_daimengchuanmei_moon_bigtts",
    name: "呆萌川妹",
    gender: "female",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_guangxiyuanzhou_moon_bigtts",
    name: "广西远舟",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_guozhoudege_moon_bigtts",
    name: "广州德哥",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_wanwanxiaohe_moon_bigtts",
    name: "湾湾小何",
    gender: "female",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_yuzhouzixuan_moon_bigtts",
    name: "豫州子轩",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 角色扮演 (ICL) ==========
  {
    id: "ICL_zh_female_wenrounvshen_239eff5e8ffa_tob",
    name: "温柔女神",
    gender: "female",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_male_shenmi_v1_tob",
    name: "机灵小伙",
    gender: "male",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_female_wuxi_tob",
    name: "元气甜妹",
    gender: "female",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_female_wenyinvsheng_v1_tob",
    name: "知心姐姐",
    gender: "female",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_male_lengkugege_v1_tob",
    name: "冷酷哥哥",
    gender: "male",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_female_yuxin_v1_tob",
    name: "初恋女友",
    gender: "female",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_male_BV705_streaming_cs_tob",
    name: "炀炀",
    gender: "male",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 教育 ==========
  {
    id: "zh_female_yingyujiaoyu_mars_bigtts",
    name: "Tina老师",
    gender: "female",
    category: "教育",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 英语 (mars/moon) ==========
  {
    id: "en_female_lauren_moon_bigtts",
    name: "Lauren",
    gender: "female",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_male_adam_mars_bigtts",
    name: "Adam",
    gender: "male",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_female_amanda_mars_bigtts",
    name: "Amanda",
    gender: "female",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_male_jackson_mars_bigtts",
    name: "Jackson",
    gender: "male",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_female_emily_mars_bigtts",
    name: "Emily",
    gender: "female",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_male_bruce_moon_bigtts",
    name: "Bruce",
    gender: "male",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_female_nara_moon_bigtts",
    name: "Nara",
    gender: "female",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 日语 ==========
  {
    id: "multi_zh_male_youyoujunzi_moon_bigtts",
    name: "ひかる（光）",
    gender: "male",
    category: "日语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "multi_female_gaolengyujie_moon_bigtts",
    name: "あけみ（朱美）",
    gender: "female",
    category: "日语",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== 多情感 (emo mars) ==========
  {
    id: "zh_female_gaolengyujie_emo_v2_mars_bigtts",
    name: "高冷御姐（多情感）",
    gender: "female",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_lengkugege_emo_v2_mars_bigtts",
    name: "冷酷哥哥（多情感）",
    gender: "male",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_roumeinvyou_emo_v2_mars_bigtts",
    name: "柔美女友（多情感）",
    gender: "female",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_yangguangqingnian_emo_v2_mars_bigtts",
    name: "阳光青年（多情感）",
    gender: "male",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_shenyeboke_emo_v2_mars_bigtts",
    name: "深夜播客（多情感）",
    gender: "male",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_male_sylus_emo_v2_mars_bigtts",
    name: "Sylus",
    gender: "male",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_female_candice_emo_v2_mars_bigtts",
    name: "Candice",
    gender: "female",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
];

export const VOICE_CATEGORIES = [
  "通用场景 2.0",
  "角色扮演 2.0",
  "视频配音 2.0",
  "有声阅读 2.0",
  "教育场景 2.0",
  "客服场景 2.0",
  "多语种 2.0",
  "通用 1.0",
  "对话",
  "有声阅读",
  "视频配音",
  "趣味口音",
  "角色扮演",
  "教育",
  "英语",
  "日语",
  "多情感",
] as const;

export function getVoicesByCategory(category: string): VoiceConfig[] {
  return VOICES.filter((v) => v.category === category);
}

export function getVoiceById(id: string): VoiceConfig | undefined {
  return VOICES.find((v) => v.id === id);
}
