import type { VoiceConfig } from "../api/types";

export const VOICES: VoiceConfig[] = [
  // ========== TTS 2.0 通用场景 (uranus) ==========
  {
    id: "zh_female_vv_uranus_bigtts",
    name: "Vivi 2.0",
    gender: "female",
    category: "通用 2.0",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "zh_female_xiaohe_uranus_bigtts",
    name: "小何 2.0",
    gender: "female",
    category: "通用 2.0",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "zh_male_m191_uranus_bigtts",
    name: "云舟 2.0",
    gender: "male",
    category: "通用 2.0",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "zh_male_taocheng_uranus_bigtts",
    name: "小天 2.0",
    gender: "male",
    category: "通用 2.0",
    free: false,
    model: "seed-tts-2.0",
  },

  // ========== TTS 2.0 有声阅读/视频配音 (saturn) ==========
  {
    id: "zh_female_xueayi_saturn_bigtts",
    name: "儿童绘本",
    gender: "female",
    category: "2.0 配音",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "zh_male_dayi_saturn_bigtts",
    name: "大壹",
    gender: "male",
    category: "2.0 配音",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "zh_female_jitangnv_saturn_bigtts",
    name: "鸡汤女",
    gender: "female",
    category: "2.0 配音",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "zh_female_meilinvyou_saturn_bigtts",
    name: "魅力女友",
    gender: "female",
    category: "2.0 配音",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "zh_female_santongyongns_saturn_bigtts",
    name: "流畅女声",
    gender: "female",
    category: "2.0 配音",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "zh_male_ruyayichen_saturn_bigtts",
    name: "儒雅逸辰",
    gender: "male",
    category: "2.0 配音",
    free: false,
    model: "seed-tts-2.0",
  },

  // ========== TTS 2.0 角色扮演 (saturn) ==========
  {
    id: "saturn_zh_female_cancan_tob",
    name: "知性灿灿",
    gender: "female",
    category: "2.0 角色",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "saturn_zh_female_keainvsheng_tob",
    name: "可爱女生 2.0",
    gender: "female",
    category: "2.0 角色",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "saturn_zh_female_tiaopigongzhu_tob",
    name: "调皮公主 2.0",
    gender: "female",
    category: "2.0 角色",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "saturn_zh_male_shuanglangshaonian_tob",
    name: "爽朗少年 2.0",
    gender: "male",
    category: "2.0 角色",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "saturn_zh_male_tiancaitongzhuo_tob",
    name: "天才同桌 2.0",
    gender: "male",
    category: "2.0 角色",
    free: false,
    model: "seed-tts-2.0",
  },

  // ========== TTS 2.0 英语 (uranus) ==========
  {
    id: "en_male_tim_uranus_bigtts",
    name: "Tim",
    gender: "male",
    category: "2.0 英语",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "en_female_dacey_uranus_bigtts",
    name: "Dacey",
    gender: "female",
    category: "2.0 英语",
    free: false,
    model: "seed-tts-2.0",
  },
  {
    id: "en_female_stokie_uranus_bigtts",
    name: "Stokie",
    gender: "female",
    category: "2.0 英语",
    free: false,
    model: "seed-tts-2.0",
  },

  // ========== TTS 1.0 通用场景 (mars) ==========
  {
    id: "zh_female_cancan_mars_bigtts",
    name: "灿灿",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_vv_mars_bigtts",
    name: "Vivi",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_qingyiyuxuan_mars_bigtts",
    name: "阳光阿辰",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_tianmeitaozi_mars_bigtts",
    name: "甜美桃子",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_qingxinnvsheng_mars_bigtts",
    name: "清新女声",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_zhixingnvsheng_mars_bigtts",
    name: "知性女声",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_qingshuangnanda_mars_bigtts",
    name: "清爽男大",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_wenrouxiaoge_mars_bigtts",
    name: "温柔小哥",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 通用场景 (moon) ==========
  {
    id: "zh_female_qinqienvsheng_moon_bigtts",
    name: "亲切女声",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_linjianvhai_moon_bigtts",
    name: "邻家女孩",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_yuanboxiaoshu_moon_bigtts",
    name: "渊博小叔",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_yangguangqingnian_moon_bigtts",
    name: "阳光青年",
    gender: "male",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_tianmeixiaoyuan_moon_bigtts",
    name: "甜美小源",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_qingchezizi_moon_bigtts",
    name: "清澈梓梓",
    gender: "female",
    category: "通用 1.0",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 通用场景 (wvae 对话) ==========
  {
    id: "zh_male_xudong_conversation_wvae_bigtts",
    name: "快乐小东",
    gender: "male",
    category: "对话",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_sophie_conversation_wvae_bigtts",
    name: "魅力苏菲",
    gender: "female",
    category: "对话",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_maomao_conversation_wvae_bigtts",
    name: "文静毛毛",
    gender: "female",
    category: "对话",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_M100_conversation_wvae_bigtts",
    name: "悠悠君子",
    gender: "male",
    category: "对话",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 有声阅读 (mars) ==========
  {
    id: "zh_male_qingcang_mars_bigtts",
    name: "擎苍",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_ruyaqingnian_mars_bigtts",
    name: "儒雅青年",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_baqiqingshu_mars_bigtts",
    name: "霸气青叔",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_gufengshaoyu_mars_bigtts",
    name: "古风少御",
    gender: "female",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_wenroushunv_mars_bigtts",
    name: "温柔淑女",
    gender: "female",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_fanjuanqingnian_mars_bigtts",
    name: "反卷青年",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_changtianyi_mars_bigtts",
    name: "悬疑解说",
    gender: "male",
    category: "有声阅读",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 视频配音 (mars) ==========
  {
    id: "zh_male_jieshuonansheng_mars_bigtts",
    name: "磁性解说男声",
    gender: "male",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_jitangmeimei_mars_bigtts",
    name: "鸡汤妹妹",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_tiexinnvsheng_mars_bigtts",
    name: "贴心女声",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_mengyatou_mars_bigtts",
    name: "萌丫头",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_naiqimengwa_mars_bigtts",
    name: "奶气萌娃",
    gender: "child",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_chunhui_mars_bigtts",
    name: "广告解说",
    gender: "male",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_shaoergushi_mars_bigtts",
    name: "少儿故事",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_qiaopinvsheng_mars_bigtts",
    name: "俏皮女声",
    gender: "female",
    category: "视频配音",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 趣味口音 ==========
  {
    id: "zh_male_beijingxiaoye_moon_bigtts",
    name: "北京小爷",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_jingqiangkanye_moon_bigtts",
    name: "京腔侃爷",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_daimengchuanmei_moon_bigtts",
    name: "呆萌川妹",
    gender: "female",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_guangxiyuanzhou_moon_bigtts",
    name: "广西远舟",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_guozhoudege_moon_bigtts",
    name: "广州德哥",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_wanwanxiaohe_moon_bigtts",
    name: "湾湾小何",
    gender: "female",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_yuzhouzixuan_moon_bigtts",
    name: "豫州子轩",
    gender: "male",
    category: "趣味口音",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 角色扮演 (ICL) ==========
  {
    id: "ICL_zh_female_wenrounvshen_239eff5e8ffa_tob",
    name: "温柔女神",
    gender: "female",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_male_shenmi_v1_tob",
    name: "机灵小伙",
    gender: "male",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_female_wuxi_tob",
    name: "元气甜妹",
    gender: "female",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_female_wenyinvsheng_v1_tob",
    name: "知心姐姐",
    gender: "female",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_male_lengkugege_v1_tob",
    name: "冷酷哥哥",
    gender: "male",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_female_yuxin_v1_tob",
    name: "初恋女友",
    gender: "female",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "ICL_zh_male_BV705_streaming_cs_tob",
    name: "炀炀",
    gender: "male",
    category: "角色扮演",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 教育 ==========
  {
    id: "zh_female_yingyujiaoyu_mars_bigtts",
    name: "Tina老师",
    gender: "female",
    category: "教育",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 英语 (mars/moon) ==========
  {
    id: "en_female_lauren_moon_bigtts",
    name: "Lauren",
    gender: "female",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_male_adam_mars_bigtts",
    name: "Adam",
    gender: "male",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_female_amanda_mars_bigtts",
    name: "Amanda",
    gender: "female",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_male_jackson_mars_bigtts",
    name: "Jackson",
    gender: "male",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_female_emily_mars_bigtts",
    name: "Emily",
    gender: "female",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_male_bruce_moon_bigtts",
    name: "Bruce",
    gender: "male",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_female_nara_moon_bigtts",
    name: "Nara",
    gender: "female",
    category: "英语",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== TTS 1.0 日语 ==========
  {
    id: "multi_zh_male_youyoujunzi_moon_bigtts",
    name: "ひかる（光）",
    gender: "male",
    category: "日语",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "multi_female_gaolengyujie_moon_bigtts",
    name: "あけみ（朱美）",
    gender: "female",
    category: "日语",
    free: false,
    model: "seed-tts-1.0",
  },

  // ========== 多情感 (emo mars) ==========
  {
    id: "zh_female_gaolengyujie_emo_v2_mars_bigtts",
    name: "高冷御姐（多情感）",
    gender: "female",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_lengkugege_emo_v2_mars_bigtts",
    name: "冷酷哥哥（多情感）",
    gender: "male",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_female_roumeinvyou_emo_v2_mars_bigtts",
    name: "柔美女友（多情感）",
    gender: "female",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_yangguangqingnian_emo_v2_mars_bigtts",
    name: "阳光青年（多情感）",
    gender: "male",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "zh_male_shenyeboke_emo_v2_mars_bigtts",
    name: "深夜播客（多情感）",
    gender: "male",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_male_sylus_emo_v2_mars_bigtts",
    name: "Sylus",
    gender: "male",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
  {
    id: "en_female_candice_emo_v2_mars_bigtts",
    name: "Candice",
    gender: "female",
    category: "多情感",
    free: false,
    model: "seed-tts-1.0",
  },
];

export const VOICE_CATEGORIES = [
  "通用 2.0",
  "2.0 配音",
  "2.0 角色",
  "2.0 英语",
  "通用 1.0",
  "对话",
  "有声阅读",
  "视频配音",
  "趣味口音",
  "角色扮演",
  "教育",
  "英语",
  "日语",
  "多情感",
] as const;

export function getVoicesByCategory(category: string): VoiceConfig[] {
  return VOICES.filter((v) => v.category === category);
}

export function getVoiceById(id: string): VoiceConfig | undefined {
  return VOICES.find((v) => v.id === id);
}
