export interface FormulaDoc {
  name: string;
  category: string;
  description: string;
  syntax: string;
  example: string;
}

export const FORMULAS_DOCUMENTATION: Record<string, FormulaDoc> = {
  SUM: {
    name: "SUM",
    category: "Basic",
    description: "Adds values together",
    syntax: "SUM(number1, [number2], ...)",
    example: "=SUM(A1:A10)",
  },
  AVERAGE: {
    name: "AVERAGE",
    category: "Basic",
    description: "Calculates the average of values",
    syntax: "AVERAGE(number1, [number2], ...)",
    example: "=AVERAGE(B1:B10)",
  },
  COUNT: {
    name: "COUNT",
    category: "Basic",
    description: "Counts the number of cells with numbers",
    syntax: "COUNT(value1, [value2], ...)",
    example: "=COUNT(A1:A100)",
  },
  COUNTA: {
    name: "COUNTA",
    category: "Basic",
    description: "Counts non-empty cells",
    syntax: "COUNTA(value1, [value2], ...)",
    example: "=COUNTA(A1:A100)",
  },
  MAX: {
    name: "MAX",
    category: "Basic",
    description: "Returns the maximum value",
    syntax: "MAX(number1, [number2], ...)",
    example: "=MAX(A1:A10)",
  },
  MIN: {
    name: "MIN",
    category: "Basic",
    description: "Returns the minimum value",
    syntax: "MIN(number1, [number2], ...)",
    example: "=MIN(A1:A10)",
  },
  IF: {
    name: "IF",
    category: "Conditional",
    description: "Returns one value if a condition is true, another if false",
    syntax: "IF(logical_test, [value_if_true], [value_if_false])",
    example: '=IF(A1>100, "High", "Low")',
  },
  IFERROR: {
    name: "IFERROR",
    category: "Conditional",
    description: "Returns a specified value if a formula results in an error",
    syntax: "IFERROR(value, value_if_error)",
    example: '=IFERROR(A1/B1, "N/A")',
  },
  IFS: {
    name: "IFS",
    category: "Conditional",
    description: "Checks multiple conditions and returns the corresponding value",
    syntax: "IFS(condition1, value1, [condition2, value2], ...)",
    example: '=IFS(A1>100, "High", A1>50, "Medium", "Low")',
  },
  VLOOKUP: {
    name: "VLOOKUP",
    category: "Lookup",
    description: "Searches for a value in the first column of a range and returns a value in the same row",
    syntax: "VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])",
    example: "=VLOOKUP(E1, Sheet1!A:B, 2, FALSE)",
  },
  INDEX: {
    name: "INDEX",
    category: "Lookup",
    description: "Returns a value from a range at a specified position",
    syntax: "INDEX(array, row_num, [column_num])",
    example: "=INDEX(A1:B10, 3, 2)",
  },
  MATCH: {
    name: "MATCH",
    category: "Lookup",
    description: "Returns the position of an item in a range",
    syntax: "MATCH(lookup_value, lookup_array, [match_type])",
    example: '=MATCH("Apples", A1:A10, 0)',
  },
  CONCATENATE: {
    name: "CONCATENATE",
    category: "Text",
    description: "Joins multiple text strings together",
    syntax: "CONCATENATE(text1, [text2], ...)",
    example: '=CONCATENATE("Hello", " ", "World")',
  },
  UPPER: {
    name: "UPPER",
    category: "Text",
    description: "Converts text to uppercase",
    syntax: "UPPER(text)",
    example: '=UPPER("hello")',
  },
  LOWER: {
    name: "LOWER",
    category: "Text",
    description: "Converts text to lowercase",
    syntax: "LOWER(text)",
    example: '=LOWER("HELLO")',
  },
  TRIM: {
    name: "TRIM",
    category: "Text",
    description: "Removes leading and trailing spaces",
    syntax: "TRIM(text)",
    example: '=TRIM(" hello ")',
  },
  LEN: {
    name: "LEN",
    category: "Text",
    description: "Returns the length of a text string",
    syntax: "LEN(text)",
    example: '=LEN("hello")',
  },
  ROUND: {
    name: "ROUND",
    category: "Math",
    description: "Rounds a number to a specified number of digits",
    syntax: "ROUND(number, num_digits)",
    example: "=ROUND(3.14159, 2)",
  },
  ABS: {
    name: "ABS",
    category: "Math",
    description: "Returns the absolute value of a number",
    syntax: "ABS(number)",
    example: "=ABS(-10)",
  },
  SQRT: {
    name: "SQRT",
    category: "Math",
    description: "Returns the square root of a number",
    syntax: "SQRT(number)",
    example: "=SQRT(16)",
  },
  TODAY: {
    name: "TODAY",
    category: "Date",
    description: "Returns the current date",
    syntax: "TODAY()",
    example: "=TODAY()",
  },
  NOW: {
    name: "NOW",
    category: "Date",
    description: "Returns the current date and time",
    syntax: "NOW()",
    example: "=NOW()",
  },
  DATE: {
    name: "DATE",
    category: "Date",
    description: "Creates a date from year, month, and day",
    syntax: "DATE(year, month, day)",
    example: "=DATE(2024, 11, 13)",
  },
  AND: {
    name: "AND",
    category: "Logical",
    description: "Returns TRUE if all conditions are true",
    syntax: "AND(logical1, [logical2], ...)",
    example: "=AND(A1>10, B1<20)",
  },
  OR: {
    name: "OR",
    category: "Logical",
    description: "Returns TRUE if any condition is true",
    syntax: "OR(logical1, [logical2], ...)",
    example: "=OR(A1=5, B1=10)",
  },
  NOT: {
    name: "NOT",
    category: "Logical",
    description: "Reverses the logical value of an argument",
    syntax: "NOT(logical)",
    example: "=NOT(A1=TRUE)",
  },
  IFNA: {
    name: "IFNA",
    category: "Conditional",
    description: "Returns a value if a formula results in #N/A error, otherwise returns the formula result",
    syntax: "IFNA(value, value_if_na)",
    example: '=IFNA(VLOOKUP(E1, A:B, 2), "Not Found")',
  },
  ISERROR: {
    name: "ISERROR",
    category: "Logical",
    description: "Returns TRUE if the value is any type of error",
    syntax: "ISERROR(value)",
    example: "=ISERROR(A1/B1)",
  },
  ISNA: {
    name: "ISNA",
    category: "Logical",
    description: "Returns TRUE if the value is #N/A error",
    syntax: "ISNA(value)",
    example: "=ISNA(VLOOKUP(E1, A:B, 2))",
  },
  ISBLANK: {
    name: "ISBLANK",
    category: "Logical",
    description: "Returns TRUE if the cell is empty",
    syntax: "ISBLANK(value)",
    example: "=ISBLANK(A1)",
  },
  ISNUMBER: {
    name: "ISNUMBER",
    category: "Logical",
    description: "Returns TRUE if the value is a number",
    syntax: "ISNUMBER(value)",
    example: "=ISNUMBER(A1)",
  },
  ISTEXT: {
    name: "ISTEXT",
    category: "Logical",
    description: "Returns TRUE if the value is text",
    syntax: "ISTEXT(value)",
    example: "=ISTEXT(A1)",
  },
  SUMIF: {
    name: "SUMIF",
    category: "Math",
    description: "Sums values that meet a single condition",
    syntax: "SUMIF(range, criteria, [sum_range])",
    example: '=SUMIF(A1:A10, ">100", B1:B10)',
  },
  SUMIFS: {
    name: "SUMIFS",
    category: "Math",
    description: "Sums values that meet multiple criteria",
    syntax: "SUMIFS(sum_range, criteria_range1, criteria1, ...)",
    example: '=SUMIFS(C1:C10, A1:A10, "North", B1:B10, ">50")',
  },
  SUMPRODUCT: {
    name: "SUMPRODUCT",
    category: "Math",
    description: "Multiplies arrays element-by-element and returns the sum",
    syntax: "SUMPRODUCT(array1, [array2], ...)",
    example: "=SUMPRODUCT(A1:A5, B1:B5)",
  },
  AVERAGEIF: {
    name: "AVERAGEIF",
    category: "Math",
    description: "Calculates the average of values that meet a single criterion",
    syntax: "AVERAGEIF(range, criteria, [average_range])",
    example: '=AVERAGEIF(A1:A10, ">50", B1:B10)',
  },
  AVERAGEIFS: {
    name: "AVERAGEIFS",
    category: "Math",
    description: "Calculates the average of values that meet multiple criteria",
    syntax: "AVERAGEIFS(average_range, criteria_range1, criteria1, ...)",
    example: '=AVERAGEIFS(C1:C10, A1:A10, "North", B1:B10, ">50")',
  },
  COUNTBLANK: {
    name: "COUNTBLANK",
    category: "Math",
    description: "Counts empty cells in a range",
    syntax: "COUNTBLANK(range)",
    example: "=COUNTBLANK(A1:A100)",
  },
  COUNTIF: {
    name: "COUNTIF",
    category: "Math",
    description: "Counts cells that meet a single criterion",
    syntax: "COUNTIF(range, criteria)",
    example: '=COUNTIF(A1:A10, "Apple")',
  },
  COUNTIFS: {
    name: "COUNTIFS",
    category: "Math",
    description: "Counts cells that meet multiple criteria",
    syntax: "COUNTIFS(criteria_range1, criteria1, ...)",
    example: '=COUNTIFS(A1:A10, "North", B1:B10, ">50")',
  },
  MAXA: {
    name: "MAXA",
    category: "Math",
    description: "Returns the maximum value including text and logical values",
    syntax: "MAXA(value1, [value2], ...)",
    example: "=MAXA(A1:A10)",
  },
  MINA: {
    name: "MINA",
    category: "Math",
    description: "Returns the minimum value including text and logical values",
    syntax: "MINA(value1, [value2], ...)",
    example: "=MINA(A1:A10)",
  },
  MEDIAN: {
    name: "MEDIAN",
    category: "Math",
    description: "Returns the median (middle value) of a set of numbers",
    syntax: "MEDIAN(number1, [number2], ...)",
    example: "=MEDIAN(A1:A10)",
  },
  MODE: {
    name: "MODE",
    category: "Math",
    description: "Returns the most frequently occurring value in a dataset",
    syntax: "MODE(number1, [number2], ...)",
    example: "=MODE(A1:A10)",
  },
  STDEV: {
    name: "STDEV",
    category: "Math",
    description: "Calculates the standard deviation of a sample",
    syntax: "STDEV(number1, [number2], ...)",
    example: "=STDEV(A1:A10)",
  },
  VAR: {
    name: "VAR",
    category: "Math",
    description: "Calculates the variance of a sample",
    syntax: "VAR(number1, [number2], ...)",
    example: "=VAR(A1:A10)",
  },
  ROUNDUP: {
    name: "ROUNDUP",
    category: "Math",
    description: "Rounds a number up to a specified number of digits",
    syntax: "ROUNDUP(number, num_digits)",
    example: "=ROUNDUP(3.14, 1)",
  },
  ROUNDDOWN: {
    name: "ROUNDDOWN",
    category: "Math",
    description: "Rounds a number down to a specified number of digits",
    syntax: "ROUNDDOWN(number, num_digits)",
    example: "=ROUNDDOWN(3.99, 0)",
  },
  CEILING: {
    name: "CEILING",
    category: "Math",
    description: "Rounds a number up to the nearest multiple of significance",
    syntax: "CEILING(number, significance)",
    example: "=CEILING(2.5, 1)",
  },
  FLOOR: {
    name: "FLOOR",
    category: "Math",
    description: "Rounds a number down to the nearest multiple of significance",
    syntax: "FLOOR(number, significance)",
    example: "=FLOOR(2.9, 1)",
  },
  TRUNC: {
    name: "TRUNC",
    category: "Math",
    description: "Truncates a number to an integer by removing decimal part",
    syntax: "TRUNC(number, [num_digits])",
    example: "=TRUNC(3.14159, 2)",
  },
  INT: {
    name: "INT",
    category: "Math",
    description: "Rounds a number down to the nearest integer",
    syntax: "INT(number)",
    example: "=INT(3.9)",
  },
  POWER: {
    name: "POWER",
    category: "Math",
    description: "Raises a number to a specified power",
    syntax: "POWER(number, power)",
    example: "=POWER(2, 3)",
  },
  EXP: {
    name: "EXP",
    category: "Math",
    description: "Returns e raised to the power of a number",
    syntax: "EXP(number)",
    example: "=EXP(1)",
  },
  LN: {
    name: "LN",
    category: "Math",
    description: "Returns the natural logarithm of a number",
    syntax: "LN(number)",
    example: "=LN(10)",
  },
  LOG: {
    name: "LOG",
    category: "Math",
    description: "Returns the logarithm of a number to a specified base",
    syntax: "LOG(number, [base])",
    example: "=LOG(100, 10)",
  },
  LOG10: {
    name: "LOG10",
    category: "Math",
    description: "Returns the base-10 logarithm of a number",
    syntax: "LOG10(number)",
    example: "=LOG10(100)",
  },
  MOD: {
    name: "MOD",
    category: "Math",
    description: "Returns the remainder of a division",
    syntax: "MOD(number, divisor)",
    example: "=MOD(10, 3)",
  },
  RAND: {
    name: "RAND",
    category: "Math",
    description: "Returns a random number between 0 and 1",
    syntax: "RAND()",
    example: "=RAND()",
  },
  RANDBETWEEN: {
    name: "RANDBETWEEN",
    category: "Math",
    description: "Returns a random integer between two specified numbers",
    syntax: "RANDBETWEEN(bottom, top)",
    example: "=RANDBETWEEN(1, 100)",
  },
  HLOOKUP: {
    name: "HLOOKUP",
    category: "Lookup",
    description: "Searches for a value in the first row of a range and returns a value in the same column",
    syntax: "HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])",
    example: '=HLOOKUP("Product", A1:D10, 3, FALSE)',
  },
  XLOOKUP: {
    name: "XLOOKUP",
    category: "Lookup",
    description: "Searches for a value in an array and returns a corresponding value from another array",
    syntax: "XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])",
    example: "=XLOOKUP(E1, A:A, B:B)",
  },
  LOOKUP: {
    name: "LOOKUP",
    category: "Lookup",
    description: "Searches for a value in a range and returns a corresponding value",
    syntax: "LOOKUP(lookup_value, lookup_array, [return_array])",
    example: "=LOOKUP(E1, A1:A10, B1:B10)",
  },
  CHOOSE: {
    name: "CHOOSE",
    category: "Lookup",
    description: "Returns a value from a list based on a position number",
    syntax: "CHOOSE(index_num, value1, [value2], ...)",
    example: '=CHOOSE(2, "Red", "Green", "Blue")',
  },
  INDIRECT: {
    name: "INDIRECT",
    category: "Lookup",
    description: "Returns a reference to a cell specified by a text string",
    syntax: "INDIRECT(ref_text, [a1])",
    example: '=INDIRECT("A" & ROW())',
  },
  OFFSET: {
    name: "OFFSET",
    category: "Lookup",
    description: "Returns a reference to a range that is a specified number of rows and columns from a cell",
    syntax: "OFFSET(reference, rows, cols, [height], [width])",
    example: "=OFFSET(A1, 1, 2, 3, 1)",
  },
  ROW: {
    name: "ROW",
    category: "Lookup",
    description: "Returns the row number of a reference",
    syntax: "ROW([reference])",
    example: "=ROW(A5)",
  },
  COLUMN: {
    name: "COLUMN",
    category: "Lookup",
    description: "Returns the column number of a reference",
    syntax: "COLUMN([reference])",
    example: "=COLUMN(C5)",
  },
  ROWS: {
    name: "ROWS",
    category: "Lookup",
    description: "Returns the number of rows in a range",
    syntax: "ROWS(array)",
    example: "=ROWS(A1:A100)",
  },
  COLUMNS: {
    name: "COLUMNS",
    category: "Lookup",
    description: "Returns the number of columns in a range",
    syntax: "COLUMNS(array)",
    example: "=COLUMNS(A1:D10)",
  },
  CONCAT: {
    name: "CONCAT",
    category: "Text",
    description: "Joins text from multiple ranges or strings",
    syntax: "CONCAT(text1, [text2], ...)",
    example: '=CONCAT("Hello", " ", "World")',
  },
  TEXTJOIN: {
    name: "TEXTJOIN",
    category: "Text",
    description: "Combines text from multiple ranges with a delimiter",
    syntax: "TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)",
    example: '=TEXTJOIN(", ", TRUE, A1:A10)',
  },
  LEFT: {
    name: "LEFT",
    category: "Text",
    description: "Returns the leftmost characters from a text string",
    syntax: "LEFT(text, [num_chars])",
    example: '=LEFT("Hello", 3)',
  },
  RIGHT: {
    name: "RIGHT",
    category: "Text",
    description: "Returns the rightmost characters from a text string",
    syntax: "RIGHT(text, [num_chars])",
    example: '=RIGHT("Hello", 2)',
  },
  MID: {
    name: "MID",
    category: "Text",
    description: "Returns a specific number of characters from a text string, starting at a specified position",
    syntax: "MID(text, start_num, num_chars)",
    example: '=MID("Hello", 2, 3)',
  },
  FIND: {
    name: "FIND",
    category: "Text",
    description: "Finds one text string within another (case-sensitive)",
    syntax: "FIND(find_text, within_text, [start_num])",
    example: '=FIND("l", "Hello")',
  },
  SEARCH: {
    name: "SEARCH",
    category: "Text",
    description: "Searches for one text string within another (case-insensitive)",
    syntax: "SEARCH(find_text, within_text, [start_num])",
    example: '=SEARCH("llo", "Hello")',
  },
  SUBSTITUTE: {
    name: "SUBSTITUTE",
    category: "Text",
    description: "Replaces old text with new text in a text string",
    syntax: "SUBSTITUTE(text, old_text, new_text, [instance_num])",
    example: '=SUBSTITUTE("Hello World", "World", "Excel")',
  },
  REPLACE: {
    name: "REPLACE",
    category: "Text",
    description: "Replaces part of a text string with a different text string",
    syntax: "REPLACE(old_text, start_num, num_chars, new_text)",
    example: '=REPLACE("Hello", 2, 2, "a")',
  },
  PROPER: {
    name: "PROPER",
    category: "Text",
    description: "Capitalizes the first letter of each word in a text string",
    syntax: "PROPER(text)",
    example: '=PROPER("hello world")',
  },
  CLEAN: {
    name: "CLEAN",
    category: "Text",
    description: "Removes non-printable characters from text",
    syntax: "CLEAN(text)",
    example: "=CLEAN(A1)",
  },
  VALUE: {
    name: "VALUE",
    category: "Text",
    description: "Converts a text string that represents a number to a number",
    syntax: "VALUE(text)",
    example: '=VALUE("1000")',
  },
  TEXT: {
    name: "TEXT",
    category: "Text",
    description: "Formats a number as text using a specific number format",
    syntax: "TEXT(value, format_text)",
    example: '=TEXT(1234.5, "$#,##0.00")',
  },
  CHAR: {
    name: "CHAR",
    category: "Text",
    description: "Returns the character specified by a code number",
    syntax: "CHAR(number)",
    example: "=CHAR(65)",
  },
  CODE: {
    name: "CODE",
    category: "Text",
    description: "Returns a numeric code for the first character in a text string",
    syntax: "CODE(text)",
    example: '=CODE("A")',
  },
  EXACT: {
    name: "EXACT",
    category: "Text",
    description: "Compares two text strings and returns TRUE if they are exactly the same",
    syntax: "EXACT(text1, text2)",
    example: '=EXACT("hello", "HELLO")',
  },
  TIME: {
    name: "TIME",
    category: "Date",
    description: "Creates a time from hour, minute, and second",
    syntax: "TIME(hour, minute, second)",
    example: "=TIME(14, 30, 0)",
  },
  YEAR: {
    name: "YEAR",
    category: "Date",
    description: "Returns the year of a date",
    syntax: "YEAR(serial_number)",
    example: "=YEAR(TODAY())",
  },
  MONTH: {
    name: "MONTH",
    category: "Date",
    description: "Returns the month of a date",
    syntax: "MONTH(serial_number)",
    example: "=MONTH(TODAY())",
  },
  DAY: {
    name: "DAY",
    category: "Date",
    description: "Returns the day of a date",
    syntax: "DAY(serial_number)",
    example: "=DAY(TODAY())",
  },
  HOUR: {
    name: "HOUR",
    category: "Date",
    description: "Returns the hour of a time",
    syntax: "HOUR(serial_number)",
    example: "=HOUR(NOW())",
  },
  MINUTE: {
    name: "MINUTE",
    category: "Date",
    description: "Returns the minute of a time",
    syntax: "MINUTE(serial_number)",
    example: "=MINUTE(NOW())",
  },
  SECOND: {
    name: "SECOND",
    category: "Date",
    description: "Returns the second of a time",
    syntax: "SECOND(serial_number)",
    example: "=SECOND(NOW())",
  },
  WEEKDAY: {
    name: "WEEKDAY",
    category: "Date",
    description: "Returns the day of the week as a number",
    syntax: "WEEKDAY(serial_number, [return_type])",
    example: "=WEEKDAY(TODAY())",
  },
  WEEKNUM: {
    name: "WEEKNUM",
    category: "Date",
    description: "Returns the week number of the year",
    syntax: "WEEKNUM(serial_number, [return_type])",
    example: "=WEEKNUM(TODAY())",
  },
  WORKDAY: {
    name: "WORKDAY",
    category: "Date",
    description: "Returns a date that is a specified number of working days before or after a start date",
    syntax: "WORKDAY(start_date, days, [holidays])",
    example: "=WORKDAY(TODAY(), 5)",
  },
  NETWORKDAYS: {
    name: "NETWORKDAYS",
    category: "Date",
    description: "Returns the number of working days between two dates",
    syntax: "NETWORKDAYS(start_date, end_date, [holidays])",
    example: "=NETWORKDAYS(A1, A2)",
  },
  EDATE: {
    name: "EDATE",
    category: "Date",
    description: "Returns the date that is a specified number of months before or after a given date",
    syntax: "EDATE(start_date, months)",
    example: "=EDATE(TODAY(), 3)",
  },
  EOMONTH: {
    name: "EOMONTH",
    category: "Date",
    description: "Returns the last day of the month specified",
    syntax: "EOMONTH(start_date, months)",
    example: "=EOMONTH(TODAY(), 0)",
  },
  DATEDIF: {
    name: "DATEDIF",
    category: "Date",
    description: "Calculates the difference between two dates",
    syntax: "DATEDIF(start_date, end_date, unit)",
    example: '=DATEDIF(A1, A2, "D")',
  },
  DATEVALUE: {
    name: "DATEVALUE",
    category: "Date",
    description: "Converts a date stored as text to a date value",
    syntax: "DATEVALUE(date_text)",
    example: '=DATEVALUE("2024-11-13")',
  },
  TIMEVALUE: {
    name: "TIMEVALUE",
    category: "Date",
    description: "Converts a time stored as text to a time value",
    syntax: "TIMEVALUE(time_text)",
    example: '=TIMEVALUE("14:30:00")',
  },
  PMT: {
    name: "PMT",
    category: "Financial",
    description: "Calculates the payment for a loan based on constant payments",
    syntax: "PMT(rate, nper, pv, [fv], [type])",
    example: "=PMT(0.06/12, 360, 200000)",
  },
  PV: {
    name: "PV",
    category: "Financial",
    description: "Returns the present value of an investment",
    syntax: "PV(rate, nper, pmt, [fv], [type])",
    example: "=PV(0.08, 10, -100)",
  },
  FV: {
    name: "FV",
    category: "Financial",
    description: "Returns the future value of an investment",
    syntax: "FV(rate, nper, pmt, [pv], [type])",
    example: "=FV(0.08, 10, -100)",
  },
  RATE: {
    name: "RATE",
    category: "Financial",
    description: "Returns the interest rate per period",
    syntax: "RATE(nper, pmt, pv, [fv], [type], [guess])",
    example: "=RATE(360, -665.30, 200000)",
  },
  NPER: {
    name: "NPER",
    category: "Financial",
    description: "Returns the number of periods for an investment",
    syntax: "NPER(rate, pmt, pv, [fv], [type])",
    example: "=NPER(0.06/12, -200, 5000)",
  },
  NPV: {
    name: "NPV",
    category: "Financial",
    description: "Returns the net present value of an investment",
    syntax: "NPV(rate, value1, [value2], ...)",
    example: "=NPV(0.1, -1000, 300, 400, 500)",
  },
  IRR: {
    name: "IRR",
    category: "Financial",
    description: "Returns the internal rate of return for a series of cash flows",
    syntax: "IRR(values, [guess])",
    example: "=IRR(A1:A10)",
  },
  XIRR: {
    name: "XIRR",
    category: "Financial",
    description: "Returns the internal rate of return for a series of cash flows that are not periodic",
    syntax: "XIRR(values, dates, [guess])",
    example: "=XIRR(A1:A10, B1:B10)",
  },
  XNPV: {
    name: "XNPV",
    category: "Financial",
    description: "Returns the net present value for a series of cash flows with different dates",
    syntax: "XNPV(rate, values, dates)",
    example: "=XNPV(0.1, A1:A10, B1:B10)",
  },
  DSUM: {
    name: "DSUM",
    category: "Database",
    description: "Sums values in a database based on specified criteria",
    syntax: "DSUM(database, field, criteria)",
    example: '=DSUM(A1:C10, "Amount", E1:E2)',
  },
  DAVERAGE: {
    name: "DAVERAGE",
    category: "Database",
    description: "Calculates the average of values in a database based on specified criteria",
    syntax: "DAVERAGE(database, field, criteria)",
    example: '=DAVERAGE(A1:C10, "Amount", E1:E2)',
  },
  DCOUNT: {
    name: "DCOUNT",
    category: "Database",
    description: "Counts cells containing numbers in a database based on specified criteria",
    syntax: "DCOUNT(database, field, criteria)",
    example: '=DCOUNT(A1:C10, "Amount", E1:E2)',
  },
  DCOUNTA: {
    name: "DCOUNTA",
    category: "Database",
    description: "Counts non-empty cells in a database based on specified criteria",
    syntax: "DCOUNTA(database, field, criteria)",
    example: '=DCOUNTA(A1:C10, "Name", E1:E2)',
  },
  DMAX: {
    name: "DMAX",
    category: "Database",
    description: "Returns the maximum value in a database based on specified criteria",
    syntax: "DMAX(database, field, criteria)",
    example: '=DMAX(A1:C10, "Amount", E1:E2)',
  },
  DMIN: {
    name: "DMIN",
    category: "Database",
    description: "Returns the minimum value in a database based on specified criteria",
    syntax: "DMIN(database, field, criteria)",
    example: '=DMIN(A1:C10, "Amount", E1:E2)',
  },
  CONVERT: {
    name: "CONVERT",
    category: "Engineering",
    description: "Converts a number from one measurement system to another",
    syntax: "CONVERT(number, from_unit, to_unit)",
    example: '=CONVERT(100, "kg", "lb")',
  },
  FILTER: {
    name: "FILTER",
    category: "Array",
    description: "Filters an array based on specified criteria",
    syntax: "FILTER(array, include, [if_empty])",
    example: "=FILTER(A1:B10, A1:A10>50)",
  },
  SORT: {
    name: "SORT",
    category: "Array",
    description: "Sorts the contents of a range or array",
    syntax: "SORT(array, [sort_index], [sort_order], [by_col])",
    example: "=SORT(A1:B10)",
  },
  SORTBY: {
    name: "SORTBY",
    category: "Array",
    description: "Sorts the contents of a range based on another range or array",
    syntax: "SORTBY(array, by_array1, [order1], ...)",
    example: "=SORTBY(A1:B10, A1:A10, -1)",
  },
  UNIQUE: {
    name: "UNIQUE",
    category: "Array",
    description: "Returns unique values from a list",
    syntax: "UNIQUE(array, [by_col], [occurs_once])",
    example: "=UNIQUE(A1:A10)",
  },
  SEQUENCE: {
    name: "SEQUENCE",
    category: "Array",
    description: "Generates a list of sequential numbers in an array",
    syntax: "SEQUENCE(rows, [columns], [start], [step])",
    example: "=SEQUENCE(5, 1, 1, 1)",
  },
  TRANSPOSE: {
    name: "TRANSPOSE",
    category: "Array",
    description: "Transposes an array (rows become columns and vice versa)",
    syntax: "TRANSPOSE(array)",
    example: "=TRANSPOSE(A1:B10)",
  },
  LAMBDA: {
    name: "LAMBDA",
    category: "Advanced",
    description: "Creates a custom function that can be reused",
    syntax: "LAMBDA([parameter1, parameter2], calculation)",
    example: "=LAMBDA(x, x*2)",
  },
  LET: {
    name: "LET",
    category: "Advanced",
    description: "Assigns names to calculation results to simplify formulas",
    syntax: "LET(name1, value1, [name2, value2], calculation)",
    example: "=LET(x, A1:A10, SUM(x))",
  },
  MAKEARRAY: {
    name: "MAKEARRAY",
    category: "Array",
    description: "Creates an array by applying a calculation to each element",
    syntax: "MAKEARRAY(rows, cols, function)",
    example: "=MAKEARRAY(3, 3, LAMBDA(r,c, r*c))",
  },
  MAP: {
    name: "MAP",
    category: "Array",
    description: "Maps each value in an array to a new value by applying a calculation",
    syntax: "MAP(array, function)",
    example: "=MAP(A1:A10, LAMBDA(x, x*2))",
  },
  REDUCE: {
    name: "REDUCE",
    category: "Array",
    description: "Reduces an array to a single value by applying a calculation",
    syntax: "REDUCE(initial_value, array, function)",
    example: "=REDUCE(0, A1:A10, LAMBDA(a,v, a+v))",
  },
  SCAN: {
    name: "SCAN",
    category: "Array",
    description: "Scans an array and returns intermediate results",
    syntax: "SCAN(initial_value, array, function)",
    example: "=SCAN(0, A1:A10, LAMBDA(a,v, a+v))",
  },
  RANDARRAY: {
    name: "RANDARRAY",
    category: "Array",
    description: "Creates an array of random numbers",
    syntax: "RANDARRAY([rows], [cols], [min], [max], [decimal_places])",
    example: "=RANDARRAY(5, 1, 1, 100)",
  },
  SWITCH: {
    name: "SWITCH",
    category: "Logical",
    description: "Evaluates an expression against a list of values and returns a corresponding result",
    syntax: "SWITCH(expression, value1, result1, [value2, result2], [default])",
    example: '=SWITCH(A1, 1, "One", 2, "Two", "Other")',
  },
  AGGREGATE: {
    name: "AGGREGATE",
    category: "Math",
    description: "Calculates an aggregate value, ignoring errors and hidden rows",
    syntax: "AGGREGATE(function_num, option, ref, [k])",
    example: "=AGGREGATE(9, 6, A1:A10)",
  },
  SUBTOTAL: {
    name: "SUBTOTAL",
    category: "Math",
    description: "Calculates subtotals, typically used with filtered data",
    syntax: "SUBTOTAL(function_num, ref1, [ref2], ...)",
    example: "=SUBTOTAL(9, A1:A10)",
  },
  FORECAST: {
    name: "FORECAST",
    category: "Statistical",
    description: "Predicts a value using linear regression",
    syntax: "FORECAST(x, known_y's, known_x's)",
    example: "=FORECAST(30, B2:B10, A2:A10)",
  },
  TREND: {
    name: "TREND",
    category: "Statistical",
    description: "Returns predicted values based on linear regression",
    syntax: "TREND(known_y's, [known_x's], [new_x's], [const])",
    example: "=TREND(B2:B10, A2:A10)",
  },
  LINEST: {
    name: "LINEST",
    category: "Statistical",
    description: "Returns statistics for a linear regression",
    syntax: "LINEST(known_y's, [known_x's], [const], [stats])",
    example: "=LINEST(B2:B10, A2:A10)",
  },
  LOGEST: {
    name: "LOGEST",
    category: "Statistical",
    description: "Returns statistics for an exponential regression",
    syntax: "LOGEST(known_y's, [known_x's], [const], [stats])",
    example: "=LOGEST(B2:B10, A2:A10)",
  },
  GROWTH: {
    name: "GROWTH",
    category: "Statistical",
    description: "Returns predicted values based on exponential regression",
    syntax: "GROWTH(known_y's, [known_x's], [new_x's], [const])",
    example: "=GROWTH(B2:B10, A2:A10)",
  },
  PERCENTILE: {
    name: "PERCENTILE",
    category: "Statistical",
    description: "Returns the k-th percentile of values",
    syntax: "PERCENTILE(array, k)",
    example: "=PERCENTILE(A1:A10, 0.5)",
  },
  QUARTILE: {
    name: "QUARTILE",
    category: "Statistical",
    description: "Returns the quartile of a dataset",
    syntax: "QUARTILE(array, quart)",
    example: "=QUARTILE(A1:A10, 2)",
  },
  RANK: {
    name: "RANK",
    category: "Statistical",
    description: "Returns the rank of a value in a dataset",
    syntax: "RANK(number, ref, [order])",
    example: "=RANK(A1, A1:A10)",
  },
  PERCENTRANK: {
    name: "PERCENTRANK",
    category: "Statistical",
    description: "Returns the percentile rank of a value in a dataset",
    syntax: "PERCENTRANK(array, value)",
    example: "=PERCENTRANK(A1:A10, A1)",
  },
  SKEW: {
    name: "SKEW",
    category: "Statistical",
    description: "Returns the skewness of a distribution",
    syntax: "SKEW(number1, [number2], ...)",
    example: "=SKEW(A1:A10)",
  },
  KURT: {
    name: "KURT",
    category: "Statistical",
    description: "Returns the kurtosis of a distribution",
    syntax: "KURT(number1, [number2], ...)",
    example: "=KURT(A1:A10)",
  },
  COVAR: {
    name: "COVAR",
    category: "Statistical",
    description: "Returns the covariance of two data sets",
    syntax: "COVAR(array1, array2)",
    example: "=COVAR(A1:A10, B1:B10)",
  },
  CORREL: {
    name: "CORREL",
    category: "Statistical",
    description: "Returns the correlation between two data sets",
    syntax: "CORREL(array1, array2)",
    example: "=CORREL(A1:A10, B1:B10)",
  },
  RSQ: {
    name: "RSQ",
    category: "Statistical",
    description: "Returns the R-squared value of a linear regression",
    syntax: "RSQ(known_y's, known_x's)",
    example: "=RSQ(B1:B10, A1:A10)",
  },
  INTERCEPT: {
    name: "INTERCEPT",
    category: "Statistical",
    description: "Returns the y-intercept of a linear regression line",
    syntax: "INTERCEPT(known_y's, known_x's)",
    example: "=INTERCEPT(B1:B10, A1:A10)",
  },
  SLOPE: {
    name: "SLOPE",
    category: "Statistical",
    description: "Returns the slope of a linear regression line",
    syntax: "SLOPE(known_y's, known_x's)",
    example: "=SLOPE(B1:B10, A1:A10)",
  },
  STANDARDIZE: {
    name: "STANDARDIZE",
    category: "Statistical",
    description: "Returns a normalized value from a distribution",
    syntax: "STANDARDIZE(x, mean, standard_dev)",
    example: "=STANDARDIZE(100, 50, 10)",
  },
  PROB: {
    name: "PROB",
    category: "Statistical",
    description: "Returns the probability of values in a range",
    syntax: "PROB(x_range, prob_range, [lower_limit], [upper_limit])",
    example: "=PROB(A1:A10, B1:B10, 1, 3)",
  },
  POISSON: {
    name: "POISSON",
    category: "Statistical",
    description: "Returns the Poisson distribution",
    syntax: "POISSON(x, mean, cumulative)",
    example: "=POISSON(5, 2.5, FALSE)",
  },
  BINOMIAL: {
    name: "BINOMIAL",
    category: "Statistical",
    description: "Returns the binomial distribution probability",
    syntax: "BINOMIAL(number_s, trials, probability_s, [cumulative])",
    example: "=BINOMIAL(6, 10, 0.5, FALSE)",
  },
  COMBIN: {
    name: "COMBIN",
    category: "Math",
    description: "Returns the number of combinations for a given number of items",
    syntax: "COMBIN(number, number_chosen)",
    example: "=COMBIN(10, 3)",
  },
  PERMUT: {
    name: "PERMUT",
    category: "Math",
    description: "Returns the number of permutations of objects",
    syntax: "PERMUT(number, number_chosen)",
    example: "=PERMUT(10, 3)",
  },
  GEOMEAN: {
    name: "GEOMEAN",
    category: "Statistical",
    description: "Returns the geometric mean of a dataset",
    syntax: "GEOMEAN(number1, [number2], ...)",
    example: "=GEOMEAN(A1:A10)",
  },
  HARMEAN: {
    name: "HARMEAN",
    category: "Statistical",
    description: "Returns the harmonic mean of a dataset",
    syntax: "HARMEAN(number1, [number2], ...)",
    example: "=HARMEAN(A1:A10)",
  },
  TRIMMEAN: {
    name: "TRIMMEAN",
    category: "Statistical",
    description: "Returns the mean of a dataset excluding top and bottom values",
    syntax: "TRIMMEAN(array, percent)",
    example: "=TRIMMEAN(A1:A10, 0.2)",
  },
  SMALL: {
    name: "SMALL",
    category: "Statistical",
    description: "Returns the k-th smallest value in a dataset",
    syntax: "SMALL(array, k)",
    example: "=SMALL(A1:A10, 2)",
  },
  LARGE: {
    name: "LARGE",
    category: "Statistical",
    description: "Returns the k-th largest value in a dataset",
    syntax: "LARGE(array, k)",
    example: "=LARGE(A1:A10, 2)",
  },
  COUNTUNIQUE: {
    name: "COUNTUNIQUE",
    category: "Math",
    description: "Counts unique values in a range",
    syntax: "COUNTUNIQUE(value1, [value2], ...)",
    example: "=COUNTUNIQUE(A1:A10)",
  },
  BYROW: {
    name: "BYROW",
    category: "Array",
    description: "Applies a calculation to each row of an array",
    syntax: "BYROW(array, function)",
    example: "=BYROW(A1:D10, LAMBDA(r, SUM(r)))",
  },
  BYCOL: {
    name: "BYCOL",
    category: "Array",
    description: "Applies a calculation to each column of an array",
    syntax: "BYCOL(array, function)",
    example: "=BYCOL(A1:D10, LAMBDA(c, SUM(c)))",
  },
  CONFIDENCE: {
    name: "CONFIDENCE",
    category: "Statistical",
    description: "Returns the confidence interval for a population mean",
    syntax: "CONFIDENCE(alpha, standard_dev, size)",
    example: "=CONFIDENCE(0.05, 2.5, 50)",
  },
  DEVSQ: {
    name: "DEVSQ",
    category: "Statistical",
    description: "Returns the sum of squared deviations from the mean",
    syntax: "DEVSQ(number1, [number2], ...)",
    example: "=DEVSQ(A1:A10)",
  },
  AVEDEV: {
    name: "AVEDEV",
    category: "Statistical",
    description: "Returns the average deviation from the mean",
    syntax: "AVEDEV(number1, [number2], ...)",
    example: "=AVEDEV(A1:A10)",
  },
  STDEVP: {
    name: "STDEVP",
    category: "Statistical",
    description: "Calculates the standard deviation of an entire population",
    syntax: "STDEVP(number1, [number2], ...)",
    example: "=STDEVP(A1:A10)",
  },
  STDEVS: {
    name: "STDEVS",
    category: "Statistical",
    description: "Calculates the standard deviation of a sample",
    syntax: "STDEVS(number1, [number2], ...)",
    example: "=STDEVS(A1:A10)",
  },
  VARP: {
    name: "VARP",
    category: "Statistical",
    description: "Calculates the variance of an entire population",
    syntax: "VARP(number1, [number2], ...)",
    example: "=VARP(A1:A10)",
  },
  VARS: {
    name: "VARS",
    category: "Statistical",
    description: "Calculates the variance of a sample",
    syntax: "VARS(number1, [number2], ...)",
    example: "=VARS(A1:A10)",
  },
  AVERAGEA: {
    name: "AVERAGEA",
    category: "Math",
    description: "Calculates the average including text and logical values",
    syntax: "AVERAGEA(value1, [value2], ...)",
    example: "=AVERAGEA(A1:A10)",
  },
  PRODUCT: {
    name: "PRODUCT",
    category: "Math",
    description: "Multiplies values together",
    syntax: "PRODUCT(number1, [number2], ...)",
    example: "=PRODUCT(A1:A10)",
  },
  SUMSQ: {
    name: "SUMSQ",
    category: "Math",
    description: "Returns the sum of squares of the arguments",
    syntax: "SUMSQ(number1, [number2], ...)",
    example: "=SUMSQ(A1:A10)",
  },
  SUMX2MY2: {
    name: "SUMX2MY2",
    category: "Math",
    description: "Returns the sum of the difference of squares of corresponding values",
    syntax: "SUMX2MY2(array_x, array_y)",
    example: "=SUMX2MY2(A1:A10, B1:B10)",
  },
  SUMX2PY2: {
    name: "SUMX2PY2",
    category: "Math",
    description: "Returns the sum of the sum of squares of corresponding values",
    syntax: "SUMX2PY2(array_x, array_y)",
    example: "=SUMX2PY2(A1:A10, B1:B10)",
  },
  SUMXMY2: {
    name: "SUMXMY2",
    category: "Math",
    description: "Returns the sum of squares of differences of corresponding values",
    syntax: "SUMXMY2(array_x, array_y)",
    example: "=SUMXMY2(A1:A10, B1:B10)",
  },
  MINVERSE: {
    name: "MINVERSE",
    category: "Math",
    description: "Returns the inverse of a matrix",
    syntax: "MINVERSE(array)",
    example: "=MINVERSE(A1:B2)",
  },
  MMULT: {
    name: "MMULT",
    category: "Math",
    description: "Returns the matrix product of two arrays",
    syntax: "MMULT(array1, array2)",
    example: "=MMULT(A1:B2, B1:C2)",
  },
  MDETERM: {
    name: "MDETERM",
    category: "Math",
    description: "Returns the determinant of a matrix",
    syntax: "MDETERM(array)",
    example: "=MDETERM(A1:B2)",
  },
  TTEST: {
    name: "TTEST",
    category: "Statistical",
    description: "Returns the probability associated with a t-test",
    syntax: "TTEST(array1, array2, tails, type)",
    example: "=TTEST(A1:A10, B1:B10, 2, 1)",
  },
  "T.TEST": {
    name: "T.TEST",
    category: "Statistical",
    description: "Returns the probability associated with a t-test (newer version)",
    syntax: "T.TEST(array1, array2, tails, type)",
    example: "=T.TEST(A1:A10, B1:B10, 2, 1)",
  },
  FTEST: {
    name: "FTEST",
    category: "Statistical",
    description: "Returns the result of an F-test",
    syntax: "FTEST(array1, array2)",
    example: "=FTEST(A1:A10, B1:B10)",
  },
  F_TEST: {
    name: "F.TEST",
    category: "Statistical",
    description: "Returns the result of an F-test (newer version)",
    syntax: "F.TEST(array1, array2)",
    example: "=F.TEST(A1:A10, B1:B10)",
  },
  CHI_TEST: {
    name: "CHI.TEST",
    category: "Statistical",
    description: "Returns the result of a chi-square test",
    syntax: "CHI.TEST(actual_range, expected_range)",
    example: "=CHI.TEST(A1:A10, B1:B10)",
  },
  ZTEST: {
    name: "ZTEST",
    category: "Statistical",
    description: "Returns the one-tailed probability-value of a z-test",
    syntax: "ZTEST(array, x, [sigma])",
    example: "=ZTEST(A1:A10, 50)",
  },
  ZTEST_ALT: {
    name: "Z.TEST",
    category: "Statistical",
    description: "Returns the one-tailed probability-value of a z-test (newer version)",
    syntax: "Z.TEST(array, x, [sigma])",
    example: "=Z.TEST(A1:A10, 50)",
  },
  CHITEST: {
    name: "CHITEST",
    category: "Statistical",
    description: "Returns the test for independence",
    syntax: "CHITEST(actual_range, expected_range)",
    example: "=CHITEST(A1:A10, B1:B10)",
  },
  CHIINV: {
    name: "CHIINV",
    category: "Statistical",
    description: "Returns the inverse of the chi-square distribution",
    syntax: "CHIINV(probability, deg_freedom)",
    example: "=CHIINV(0.05, 5)",
  },
  INVERSE_LOI_KHIDEUX: {
    name: "INVERSE.LOI.KHIDEUX",
    category: "Statistical",
    description: "Returns the inverse of the chi-square distribution (French)",
    syntax: "INVERSE.LOI.KHIDEUX(probability, deg_freedom)",
    example: "=INVERSE.LOI.KHIDEUX(0.05, 5)",
  },
  TINV: {
    name: "TINV",
    category: "Statistical",
    description: "Returns the inverse of the t-distribution",
    syntax: "TINV(probability, deg_freedom)",
    example: "=TINV(0.05, 10)",
  },
  INVERSE_LOI_T: {
    name: "INVERSE.LOI.T",
    category: "Statistical",
    description: "Returns the inverse of the t-distribution (French)",
    syntax: "INVERSE.LOI.T(probability, deg_freedom)",
    example: "=INVERSE.LOI.T(0.05, 10)",
  },
  FINV: {
    name: "FINV",
    category: "Statistical",
    description: "Returns the inverse of the F-distribution",
    syntax: "FINV(probability, deg_freedom1, deg_freedom2)",
    example: "=FINV(0.05, 5, 10)",
  },
  INVERSE_LOI_F: {
    name: "INVERSE.LOI.F",
    category: "Statistical",
    description: "Returns the inverse of the F-distribution (French)",
    syntax: "INVERSE.LOI.F(probability, deg_freedom1, deg_freedom2)",
    example: "=INVERSE.LOI.F(0.05, 5, 10)",
  },
  TDIST: {
    name: "TDIST",
    category: "Statistical",
    description: "Returns the t-distribution",
    syntax: "TDIST(x, deg_freedom, tails)",
    example: "=TDIST(1.5, 10, 2)",
  },
  LOI_T: {
    name: "LOI.T",
    category: "Statistical",
    description: "Returns the t-distribution (French)",
    syntax: "LOI.T(x, deg_freedom, tails)",
    example: "=LOI.T(1.5, 10, 2)",
  },
  FDIST: {
    name: "FDIST",
    category: "Statistical",
    description: "Returns the F-distribution",
    syntax: "FDIST(x, deg_freedom1, deg_freedom2)",
    example: "=FDIST(1.5, 5, 10)",
  },
  LOI_F: {
    name: "LOI.F",
    category: "Statistical",
    description: "Returns the F-distribution (French)",
    syntax: "LOI.F(x, deg_freedom1, deg_freedom2)",
    example: "=LOI.F(1.5, 5, 10)",
  },
  NORMSINV: {
    name: "NORMSINV",
    category: "Statistical",
    description: "Returns the inverse of the standard normal distribution",
    syntax: "NORMSINV(probability)",
    example: "=NORMSINV(0.975)",
  },
  LOI_NORMALE_STANDARD_INVERSE: {
    name: "LOI.NORMALE.STANDARD.INVERSE",
    category: "Statistical",
    description: "Returns the inverse of the standard normal distribution (French)",
    syntax: "LOI.NORMALE.STANDARD.INVERSE(probability)",
    example: "=LOI.NORMALE.STANDARD.INVERSE(0.975)",
  },
  NORMSDIST: {
    name: "NORMSDIST",
    category: "Statistical",
    description: "Returns the standard normal cumulative distribution",
    syntax: "NORMSDIST(z)",
    example: "=NORMSDIST(1.5)",
  },
  LOI_NORMALE_STANDARD: {
    name: "LOI.NORMALE.STANDARD",
    category: "Statistical",
    description: "Returns the standard normal cumulative distribution (French)",
    syntax: "LOI.NORMALE.STANDARD(z)",
    example: "=LOI.NORMALE.STANDARD(1.5)",
  },
  NORMINV: {
    name: "NORMINV",
    category: "Statistical",
    description: "Returns the inverse of the normal distribution",
    syntax: "NORMINV(probability, mean, standard_dev)",
    example: "=NORMINV(0.975, 50, 10)",
  },
  LOI_NORMALE_INVERSE: {
    name: "LOI.NORMALE.INVERSE",
    category: "Statistical",
    description: "Returns the inverse of the normal distribution (French)",
    syntax: "LOI.NORMALE.INVERSE(probability, mean, standard_dev)",
    example: "=LOI.NORMALE.INVERSE(0.975, 50, 10)",
  },
  HYPGEOM: {
    name: "HYPGEOM",
    category: "Statistical",
    description: "Returns the hypergeometric distribution",
    syntax: "HYPGEOM(sample_s, number_sample, population_s, number_pop)",
    example: "=HYPGEOM(4, 20, 10, 50)",
  },
  LOGNORM: {
    name: "LOGNORM",
    category: "Statistical",
    description: "Returns the lognormal distribution",
    syntax: "LOGNORM(x, mean, standard_dev, [cumulative])",
    example: "=LOGNORM(4, 2, 0.5)",
  },
  WEIBULL: {
    name: "WEIBULL",
    category: "Statistical",
    description: "Returns the Weibull distribution",
    syntax: "WEIBULL(x, alpha, beta, [cumulative])",
    example: "=WEIBULL(5, 2, 1)",
  },
  GAMMA: {
    name: "GAMMA",
    category: "Statistical",
    description: "Returns the gamma distribution",
    syntax: "GAMMA(x, alpha, beta, [cumulative])",
    example: "=GAMMA(5, 2, 1)",
  },
  BETA: {
    name: "BETA",
    category: "Statistical",
    description: "Returns the beta distribution",
    syntax: "BETA(x, alpha, beta, [a], [b])",
    example: "=BETA(0.5, 2, 3)",
  },
};

export function getFormulaDoc(formulaName: string): FormulaDoc | undefined {
  return FORMULAS_DOCUMENTATION[formulaName.toUpperCase()];
}

export function getAllFormulasInCategory(category: string): FormulaDoc[] {
  return Object.values(FORMULAS_DOCUMENTATION).filter((doc) => doc.category === category);
}

export function getAllCategories(): string[] {
  const categories = new Set(Object.values(FORMULAS_DOCUMENTATION).map((doc) => doc.category));
  return Array.from(categories).sort();
}
