// Excel Formula Types Enumeration

export enum FormulaTypes {
  // Logical functions (English)
  IF = "IF",
  IFS = "IFS",
  AND = "AND",
  OR = "OR",
  NOT = "NOT",
  IFERROR = "IFERROR",
  IFNA = "IFNA",
  ISERROR = "ISERROR",
  ISNA = "ISNA",
  ISBLANK = "ISBLANK",
  ISNUMBER = "ISNUMBER",
  ISTEXT = "ISTEXT",

  // Logical functions (French)
  SI = "SI",
  SIS = "SIS",
  ET = "ET",
  OU = "OU",
  NON = "NON",
  SIERREUR = "SIERREUR",
  SINA = "SINA",
  ESTERREUR = "ESTERREUR",
  ESTNA = "ESTNA",
  ESTVIDE = "ESTVIDE",
  ESTNUM = "ESTNUM",
  ESTTEXTE = "ESTTEXTE",

  // Math and statistical functions (English)
  SUM = "SUM",
  SUMIF = "SUMIF",
  SUMIFS = "SUMIFS",
  SUMPRODUCT = "SUMPRODUCT",
  AVERAGE = "AVERAGE",
  AVERAGEIF = "AVERAGEIF",
  AVERAGEIFS = "AVERAGEIFS",
  COUNT = "COUNT",
  COUNTA = "COUNTA",
  COUNTBLANK = "COUNTBLANK",
  COUNTIF = "COUNTIF",
  COUNTIFS = "COUNTIFS",
  MAX = "MAX",
  MAXA = "MAXA",
  MIN = "MIN",
  MINA = "MINA",
  MEDIAN = "MEDIAN",
  MODE = "MODE",
  STDEV = "STDEV",
  VAR = "VAR",

  // Math and statistical functions (French)
  SOMME = "SOMME",
  SOMME_SI = "SOMME.SI",
  SOMME_SI_ENS = "SOMME.SI.ENS",
  SOMMEPROD = "SOMMEPROD",
  MOYENNE = "MOYENNE",
  MOYENNE_SI = "MOYENNE.SI",
  MOYENNE_SI_ENS = "MOYENNE.SI.ENS",
  NB = "NB",
  NBVAL = "NBVAL",
  NB_VIDE = "NB.VIDE",
  NB_SI = "NB.SI",
  NB_SI_ENS = "NB.SI.ENS",
  MEDIANE = "MEDIANE",
  ECARTYPE = "ECARTYPE",

  // Math functions (English)
  ROUND = "ROUND",
  ROUNDUP = "ROUNDUP",
  ROUNDDOWN = "ROUNDDOWN",
  CEILING = "CEILING",
  FLOOR = "FLOOR",
  TRUNC = "TRUNC",
  INT = "INT",
  ABS = "ABS",
  SQRT = "SQRT",
  POWER = "POWER",
  EXP = "EXP",
  LN = "LN",
  LOG = "LOG",
  LOG10 = "LOG10",
  MOD = "MOD",
  RAND = "RAND",
  RANDBETWEEN = "RANDBETWEEN",

  // Math functions (French)
  ARRONDI = "ARRONDI",
  ARRONDI_SUP = "ARRONDI.SUP",
  ARRONDI_INF = "ARRONDI.INF",
  PLAFOND = "PLAFOND",
  PLANCHER = "PLANCHER",
  TRONQUE = "TRONQUE",
  ENT = "ENT",
  RACINE = "RACINE",
  PUISSANCE = "PUISSANCE",
  ALEA = "ALEA",
  ALEA_ENTRE_BORNES = "ALEA.ENTRE.BORNES",

  // Lookup and reference functions (English)
  VLOOKUP = "VLOOKUP",
  HLOOKUP = "HLOOKUP",
  XLOOKUP = "XLOOKUP",
  LOOKUP = "LOOKUP",
  INDEX = "INDEX",
  MATCH = "MATCH",
  CHOOSE = "CHOOSE",
  INDIRECT = "INDIRECT",
  OFFSET = "OFFSET",
  ROW = "ROW",
  COLUMN = "COLUMN",
  ROWS = "ROWS",
  COLUMNS = "COLUMNS",

  // Lookup and reference functions (French)
  RECHERCHEV = "RECHERCHEV",
  RECHERCHEH = "RECHERCHEH",
  RECHERCHEX = "RECHERCHEX",
  RECHERCHE = "RECHERCHE",
  EQUIV = "EQUIV",
  CHOISIR = "CHOISIR",
  DECALER = "DECALER",
  LIGNE = "LIGNE",
  COLONNE = "COLONNE",
  LIGNES = "LIGNES",
  COLONNES = "COLONNES",

  // Text functions (English)
  CONCATENATE = "CONCATENATE",
  CONCAT = "CONCAT",
  TEXTJOIN = "TEXTJOIN",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  MID = "MID",
  LEN = "LEN",
  FIND = "FIND",
  SEARCH = "SEARCH",
  SUBSTITUTE = "SUBSTITUTE",
  REPLACE = "REPLACE",
  UPPER = "UPPER",
  LOWER = "LOWER",
  PROPER = "PROPER",
  TRIM = "TRIM",
  CLEAN = "CLEAN",
  VALUE = "VALUE",
  TEXT = "TEXT",
  CHAR = "CHAR",
  CODE = "CODE",
  EXACT = "EXACT",

  // Text functions (French)
  CONCATENER = "CONCATENER",
  JOINDRE_TEXTE = "JOINDRE.TEXTE",
  GAUCHE = "GAUCHE",
  DROITE = "DROITE",
  STXT = "STXT",
  NBCAR = "NBCAR",
  CHERCHE = "CHERCHE",
  TROUVE = "TROUVE",
  SUBSTITUE = "SUBSTITUE",
  REMPLACER = "REMPLACER",
  MAJUSCULE = "MAJUSCULE",
  MINUSCULE = "MINUSCULE",
  NOMPROPRE = "NOMPROPRE",
  SUPPRESPACE = "SUPPRESPACE",
  EPURAGE = "EPURAGE",
  CNUM = "CNUM",
  TEXTE = "TEXTE",
  CAR = "CAR",

  // Date and time functions (English)
  TODAY = "TODAY",
  NOW = "NOW",
  DATE = "DATE",
  TIME = "TIME",
  YEAR = "YEAR",
  MONTH = "MONTH",
  DAY = "DAY",
  HOUR = "HOUR",
  MINUTE = "MINUTE",
  SECOND = "SECOND",
  WEEKDAY = "WEEKDAY",
  WEEKNUM = "WEEKNUM",
  WORKDAY = "WORKDAY",
  NETWORKDAYS = "NETWORKDAYS",
  EDATE = "EDATE",
  EOMONTH = "EOMONTH",
  DATEDIF = "DATEDIF",
  DATEVALUE = "DATEVALUE",
  TIMEVALUE = "TIMEVALUE",

  // Date and time functions (French)
  AUJOURDHUI = "AUJOURDHUI",
  MAINTENANT = "MAINTENANT",
  TEMPS = "TEMPS",
  ANNEE = "ANNEE",
  MOIS = "MOIS",
  JOUR = "JOUR",
  HEURE = "HEURE",
  SECONDE = "SECONDE",
  JOURSEM = "JOURSEM",
  NO_SEMAINE = "NO.SEMAINE",
  SERIE_JOUR_OUVRE = "SERIE.JOUR.OUVRE",
  NB_JOURS_OUVRES = "NB.JOURS.OUVRES",
  MOIS_DECALER = "MOIS.DECALER",
  FIN_MOIS = "FIN.MOIS",
  DATEVAL = "DATEVAL",
  TEMPSVAL = "TEMPSVAL",

  // Financial functions (English)
  PMT = "PMT",
  PV = "PV",
  FV = "FV",
  RATE = "RATE",
  NPER = "NPER",
  NPV = "NPV",
  IRR = "IRR",
  XIRR = "XIRR",
  XNPV = "XNPV",

  // Financial functions (French)
  VPM = "VPM",
  VA = "VA",
  VC = "VC",
  TAUX = "TAUX",
  NPM = "NPM",
  VAN = "VAN",
  TRI = "TRI",
  TRID = "TRID",
  VAND = "VAND",

  // Database functions (English)
  DSUM = "DSUM",
  DAVERAGE = "DAVERAGE",
  DCOUNT = "DCOUNT",
  DCOUNTA = "DCOUNTA",
  DMAX = "DMAX",
  DMIN = "DMIN",

  // Database functions (French)
  BDSOMME = "BDSOMME",
  BDMOYENNE = "BDMOYENNE",
  BDNB = "BDNB",
  BDNBVAL = "BDNBVAL",
  BDMAX = "BDMAX",
  BDMIN = "BDMIN",

  // Engineering functions (English)
  CONVERT = "CONVERT",

  // Array functions (newer Excel - English)
  FILTER = "FILTER",
  SORT = "SORT",
  SORTBY = "SORTBY",
  UNIQUE = "UNIQUE",
  SEQUENCE = "SEQUENCE",
  TRANSPOSE = "TRANSPOSE",

  // Array functions (newer Excel - French)
  FILTRE = "FILTRE",
  TRIER = "TRIER",
  TRIER_PAR = "TRIER.PAR",
}
