export const colors = ["candy", "breeze", "crimson", "falcon", "meadow", "midnight", "mono", "raindrop", "sunset"];

export const languages = [
  { label: "Auto-Detect", value: "auto" },
  { label: "Bash", value: "bash" },
  { label: "C#", value: "csharp" },
  { label: "Clojure", value: "Clojure" },
  { label: "CoffeeScript", value: "coffeescript" },
  { label: "Crystal", value: "crystal" },
  { label: "CSS", value: "css" },
  { label: "D", value: "d" },
  { label: "Dart", value: "dart" },
  { label: "Diff", value: "diff" },
  { label: "Docker", value: "dockerfile" },
  { label: "Elm", value: "elm" },
  { label: "Erlang", value: "erlang" },
  { label: "Fortran", value: "fortran" },
  { label: "Gherkin", value: "gherkin" },
  { label: "Go", value: "Go" },
  { label: "Groovy", value: "groovy" },
  { label: "Haskell", value: "haskell" },
  { label: "Java", value: "java" },
  { label: "Javascript", value: "javascript" },
  { label: "JSON", value: "json" },
  { label: "JSX", value: "jsx" },
  { label: "Julia", value: "julia" },
  { label: "Kotlin", value: "kotlin" },
  { label: "LaTeX", value: "latex" },
  { label: "Lisp", value: "lisp" },
  { label: "Lua", value: "lua" },
  { label: "Markdown", value: "markdown" },
  { label: "MATLAB/Octave", value: "octave" },
  { label: "NGINX", value: "nginx" },
  { label: "Objective C", value: "objectivec" },
  { label: "OCaml", value: "ocaml" },
  { label: "Perl", value: "perl" },
  { label: "PHP", value: "php" },
  { label: "Powershell", value: "powershell" },
  { label: "Python", value: "python" },
  { label: "R", value: "r" },
  { label: "Ruby", value: "ruby" },
  { label: "Rust", value: "rust" },
  { label: "Scala", value: "scala" },
  { label: "Smalltalk", value: "smalltalk" },
  { label: "Swift", value: "swift" },
  { label: "Typescript", value: "typescript" },
  { label: "Twig", value: "twig" },
  { label: "Verilog", value: "verilog" },
  { label: "VHDL", value: "vhdl" },
  { label: "XQuery", value: "xquery" },
  { label: "YAML", value: "yaml" },
];
