export const colors = [
  { title: "Candy", value: "candy" },
  { title: "Breeze", value: "breeze" },
  { title: "Crimson", value: "crimson" },
  { title: "Falcon", value: "falcon" },
  { title: "Meadow", value: "meadow" },
  { title: "Midnight", value: "midnight" },
  { title: "Mono", value: "mono" },
  { title: "Evil Rabbit", value: "rabbit" },
  { title: "Raindrop", value: "raindrop" },
  { title: "Sunset", value: "sunset" },
  { title: "Vercel", value: "vercel" },
];

export const languages = [
  { label: "Auto-Detect", value: "auto" },
  { label: "Astro", value: "astro" },
  { label: "Bash", value: "shell" },
  { label: "C#", value: "csharp" },
  { label: "C++", value: "cpp" },
  { label: "Clojure", value: "Clojure" },
  { label: "Crystal", value: "crystal" },
  { label: "CSS", value: "css" },
  { label: "Diff", value: "diff" },
  { label: "Docker", value: "dockerfile" },
  { label: "Elixir", value: "elixir" },
  { label: "Elm", value: "elm" },
  { label: "Erlang", value: "erlang" },
  { label: "Go", value: "Go" },
  { label: "GraphQL", value: "graphql" },
  { label: "Haskell", value: "haskell" },
  { label: "HTML", value: "html" },
  { label: "Java", value: "java" },
  { label: "Javascript", value: "javascript" },
  { label: "JSON", value: "json" },
  { label: "JSX", value: "jsx" },
  { label: "Julia", value: "julia" },
  { label: "Kotlin", value: "kotlin" },
  { label: "LaTeX", value: "latex" },
  { label: "Lisp", value: "lisp" },
  { label: "Lua", value: "lua" },
  { label: "Markdown", value: "markdown" },
  { label: "MATLAB", value: "matlab" },
  { label: "Objective C", value: "objectivec" },
  { label: "OCaml", value: "ocaml" },
  { label: "PHP", value: "php" },
  { label: "Plaintext", value: "plaintext" },
  { label: "Powershell", value: "powershell" },
  { label: "Python", value: "python" },
  { label: "R", value: "r" },
  { label: "Ruby", value: "ruby" },
  { label: "Rust", value: "rust" },
  { label: "Scala", value: "scala" },
  { label: "SCSS", value: "scss" },
  { label: "Solidity", value: "solidity" },
  { label: "SQL", value: "sql" },
  { label: "Svelte", value: "svelte" },
  { label: "Swift", value: "swift" },
  { label: "TOML", value: "toml" },
  { label: "TSX", value: "tsx" },
  { label: "Typescript", value: "typescript" },
  { label: "Vue", value: "vue" },
  { label: "XML", value: "xml" },
  { label: "YAML", value: "yaml" },
];
