export interface Hexagram {
  number: number;
  name: string;
  pinyin: string;
  meaning: string;
  description: string;
}

export const hexagrams: Hexagram[] = [
  {
    number: 1,
    name: "乾",
    pinyin: "Qián",
    meaning: "天",
    description: "The Creative, Strength, Perseverance",
  },
  {
    number: 2,
    name: "坤",
    pinyin: "Kūn",
    meaning: "地",
    description: "The Receptive, Devotion, Nurturing",
  },
  {
    number: 3,
    name: "屯",
    pinyin: "Zhūn",
    meaning: "水雷",
    description: "Difficulty at the Beginning, Perseverance needed",
  },
  {
    number: 4,
    name: "蒙",
    pinyin: "Méng",
    meaning: "山水",
    description: "Youthful Folly, Education, Learning required",
  },
  {
    number: 5,
    name: "需",
    pinyin: "Xū",
    meaning: "水天",
    description: "Waiting, Patience, Timing not yet right",
  },
  {
    number: 6,
    name: "訟",
    pinyin: "Sòng",
    meaning: "天水",
    description: "Conflict, Dispute, Mediation needed",
  },
  {
    number: 7,
    name: "師",
    pinyin: "Shī",
    meaning: "地水",
    description: "The Army, Discipline, Organization needed",
  },
  {
    number: 8,
    name: "比",
    pinyin: "Bǐ",
    meaning: "水地",
    description: "Union, Solidarity, Mutual support",
  },
  {
    number: 9,
    name: "小畜",
    pinyin: "Xiǎo Xù",
    meaning: "風天",
    description: "Small Accumulation, Moderation needed",
  },
  {
    number: 10,
    name: "履",
    pinyin: "Lǚ",
    meaning: "天澤",
    description: "Treading, Practice, Caution required",
  },
  {
    number: 11,
    name: "泰",
    pinyin: "Tài",
    meaning: "天地",
    description: "Peace, Smoothness, Harmony",
  },
  {
    number: 12,
    name: "否",
    pinyin: "Pǐ",
    meaning: "地天",
    description: "Standstill, Obstruction, Change needed",
  },
  {
    number: 13,
    name: "同人",
    pinyin: "Tóng Rén",
    meaning: "天火",
    description: "Fellowship, Cooperation, Common goals",
  },
  {
    number: 14,
    name: "大有",
    pinyin: "Dà Yǒu",
    meaning: "火天",
    description: "Great Possession, Abundance, Success",
  },
  {
    number: 15,
    name: "謙",
    pinyin: "Qiān",
    meaning: "地山",
    description: "Modesty, Humility, Stay humble",
  },
  {
    number: 16,
    name: "豫",
    pinyin: "Yù",
    meaning: "雷地",
    description: "Enthusiasm, Preparation, Active action",
  },
  {
    number: 17,
    name: "隨",
    pinyin: "Suí",
    meaning: "澤雷",
    description: "Following, Adaptation, Flexibility",
  },
  {
    number: 18,
    name: "蠱",
    pinyin: "Gǔ",
    meaning: "山風",
    description: "Decay, Reform, Restructuring needed",
  },
  {
    number: 19,
    name: "臨",
    pinyin: "Lín",
    meaning: "地澤",
    description: "Approach, Oversight, Attention needed",
  },
  {
    number: 20,
    name: "觀",
    pinyin: "Guān",
    meaning: "風地",
    description: "Contemplation, Observation, Reflection needed",
  },
  {
    number: 21,
    name: "噬嗑",
    pinyin: "Shì Kè",
    meaning: "火雷",
    description: "Biting Through, Resolution, Decisiveness needed",
  },
  {
    number: 22,
    name: "賁",
    pinyin: "Bì",
    meaning: "山火",
    description: "Grace, Adornment, Focus on appearance",
  },
  {
    number: 23,
    name: "剝",
    pinyin: "Bō",
    meaning: "山地",
    description: "Splitting Apart, Decline, Protection needed",
  },
  {
    number: 24,
    name: "復",
    pinyin: "Fù",
    meaning: "地雷",
    description: "Return, Recovery, New beginning",
  },
  {
    number: 25,
    name: "無妄",
    pinyin: "Wú Wàng",
    meaning: "天雷",
    description: "Innocence, Truth, Avoid delusion",
  },
  {
    number: 26,
    name: "大畜",
    pinyin: "Dà Xù",
    meaning: "山天",
    description: "Great Accumulation, Reserve needed",
  },
  {
    number: 27,
    name: "頤",
    pinyin: "Yí",
    meaning: "山雷",
    description: "Nourishment, Cultivation, Maintenance needed",
  },
  {
    number: 28,
    name: "大過",
    pinyin: "Dà Guò",
    meaning: "澤風",
    description: "Great Exceeding, Excess, Adjustment needed",
  },
  {
    number: 29,
    name: "坎",
    pinyin: "Kǎn",
    meaning: "水",
    description: "The Abysmal Water, Danger, Caution needed",
  },
  {
    number: 30,
    name: "離",
    pinyin: "Lí",
    meaning: "火",
    description: "The Clinging Fire, Clarity, Attachment needed",
  },
  {
    number: 31,
    name: "咸",
    pinyin: "Xián",
    meaning: "澤山",
    description: "Influence, Interaction, Communication needed",
  },
  {
    number: 32,
    name: "恆",
    pinyin: "Héng",
    meaning: "雷風",
    description: "Duration, Persistence, Perseverance needed",
  },
  {
    number: 33,
    name: "遯",
    pinyin: "Dùn",
    meaning: "天山",
    description: "Retreat, Withdrawal, Waiting needed",
  },
  {
    number: 34,
    name: "大壯",
    pinyin: "Dà Zhuàng",
    meaning: "雷天",
    description: "Great Power, Strength, Moderation needed",
  },
  {
    number: 35,
    name: "晉",
    pinyin: "Jìn",
    meaning: "火地",
    description: "Progress, Advancement, Positive upward movement",
  },
  {
    number: 36,
    name: "明夷",
    pinyin: "Míng Yí",
    meaning: "地火",
    description: "Darkening of the Light, Injury, Endurance needed",
  },
  {
    number: 37,
    name: "家人",
    pinyin: "Jiā Rén",
    meaning: "風火",
    description: "The Family, Household, Focus on harmony",
  },
  {
    number: 38,
    name: "睽",
    pinyin: "Kuí",
    meaning: "火澤",
    description: "Opposition, Divergence, Coordination needed",
  },
  {
    number: 39,
    name: "蹇",
    pinyin: "Jiǎn",
    meaning: "水山",
    description: "Obstruction, Difficulty, Patience needed",
  },
  {
    number: 40,
    name: "解",
    pinyin: "Jiě",
    meaning: "雷水",
    description: "Deliverance, Resolution, Difficulties removed",
  },
  {
    number: 41,
    name: "損",
    pinyin: "Sǔn",
    meaning: "山澤",
    description: "Decrease, Loss, Moderation needed",
  },
  {
    number: 42,
    name: "益",
    pinyin: "Yì",
    meaning: "風雷",
    description: "Increase, Gain, Favorable development",
  },
  {
    number: 43,
    name: "夬",
    pinyin: "Guài",
    meaning: "澤天",
    description: "Breakthrough, Decisiveness, Decision needed",
  },
  {
    number: 44,
    name: "姤",
    pinyin: "Gòu",
    meaning: "天風",
    description: "Coming to Meet, Encounter, New beginning",
  },
  {
    number: 45,
    name: "萃",
    pinyin: "Cuì",
    meaning: "澤地",
    description: "Gathering Together, Convergence, Unity needed",
  },
  {
    number: 46,
    name: "升",
    pinyin: "Shēng",
    meaning: "地風",
    description: "Pushing Upward, Ascension, Continuous progress",
  },
  {
    number: 47,
    name: "困",
    pinyin: "Kùn",
    meaning: "澤水",
    description: "Oppression, Exhaustion, Perseverance needed",
  },
  {
    number: 48,
    name: "井",
    pinyin: "Jǐng",
    meaning: "水風",
    description: "The Well, Nourishment, Cultivation needed",
  },
  {
    number: 49,
    name: "革",
    pinyin: "Gé",
    meaning: "澤火",
    description: "Revolution, Reform, Change needed",
  },
  {
    number: 50,
    name: "鼎",
    pinyin: "Dǐng",
    meaning: "火風",
    description: "The Cauldron, Stability, Consolidation needed",
  },
  {
    number: 51,
    name: "震",
    pinyin: "Zhèn",
    meaning: "雷",
    description: "The Arousing Thunder, Shock, Alertness needed",
  },
  {
    number: 52,
    name: "艮",
    pinyin: "Gèn",
    meaning: "山",
    description: "Keeping Still, Mountain, Stop needed",
  },
  {
    number: 53,
    name: "漸",
    pinyin: "Jiàn",
    meaning: "風山",
    description: "Development, Gradual progress, Patience needed",
  },
  {
    number: 54,
    name: "歸妹",
    pinyin: "Guī Mèi",
    meaning: "雷澤",
    description: "The Marrying Maiden, Marriage, Adaptation needed",
  },
  {
    number: 55,
    name: "豐",
    pinyin: "Fēng",
    meaning: "雷火",
    description: "Abundance, Greatness, Maintenance needed",
  },
  {
    number: 56,
    name: "旅",
    pinyin: "Lǚ",
    meaning: "火山",
    description: "The Wanderer, Travel, Adaptation needed",
  },
  {
    number: 57,
    name: "巽",
    pinyin: "Xùn",
    meaning: "風",
    description: "The Gentle Wind, Penetration, Submission needed",
  },
  {
    number: 58,
    name: "兌",
    pinyin: "Duì",
    meaning: "澤",
    description: "The Joyous Lake, Joy, Communication needed",
  },
  {
    number: 59,
    name: "渙",
    pinyin: "Huàn",
    meaning: "風水",
    description: "Dispersion, Scattering, Cohesion needed",
  },
  {
    number: 60,
    name: "節",
    pinyin: "Jié",
    meaning: "水澤",
    description: "Limitation, Restraint, Control needed",
  },
  {
    number: 61,
    name: "中孚",
    pinyin: "Zhōng Fú",
    meaning: "風澤",
    description: "Inner Truth, Sincerity, Authenticity needed",
  },
  {
    number: 62,
    name: "小過",
    pinyin: "Xiǎo Guò",
    meaning: "雷山",
    description: "Small Exceeding, Minor error, Caution needed",
  },
  {
    number: 63,
    name: "既濟",
    pinyin: "Jì Jì",
    meaning: "水火",
    description: "After Completion, Accomplishment, Maintenance needed",
  },
  {
    number: 64,
    name: "未濟",
    pinyin: "Wèi Jì",
    meaning: "火水",
    description: "Before Completion, Incomplete, Effort needed",
  },
];
