import type { TweakDefinition } from "../types";

export const animationsTweaks: TweakDefinition[] = [
  {
    id: "animations-disable-window",
    title: "Disable Window Animations",
    description: "Disable the smooth animation when opening and closing windows",
    category: "animations",
    domain: "NSGlobalDomain",
    key: "NSAutomaticWindowAnimationsEnabled",
    type: "boolean",
    defaultValue: true,
    risk: "safe",
    tags: ["window", "open", "close"],
  },
  {
    id: "animations-mission-control-speed",
    title: "Mission Control Animation Speed",
    description: "Control the speed of the Mission Control animation",
    category: "animations",
    domain: "com.apple.dock",
    key: "expose-animation-duration",
    type: "enum",
    defaultValue: 0.5,
    options: [
      { title: "Instant (0s)", value: 0 },
      { title: "Very Fast (0.1s)", value: 0.1 },
      { title: "Fast (0.25s)", value: 0.25 },
      { title: "Default (0.5s)", value: 0.5 },
      { title: "Slow (1s)", value: 1 },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["mission control", "speed"],
  },
  {
    id: "animations-disable-launchpad",
    title: "Launchpad Animation Speed",
    description: "Control the speed of Launchpad show/hide animations (0 disables them)",
    category: "animations",
    domain: "com.apple.dock",
    key: "springboard-show-duration",
    type: "enum",
    defaultValue: 0.5,
    options: [
      { title: "Instant (disabled)", value: 0 },
      { title: "Fast (0.2s)", value: 0.2 },
      { title: "Default (0.5s)", value: 0.5 },
    ],
    extraDefaults: [{ domain: "com.apple.dock", key: "springboard-hide-duration", mirrorPrimary: true }],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["launchpad"],
  },
  {
    id: "animations-disable-smooth-scrolling",
    title: "Disable Smooth Scrolling",
    description: "Disable smooth inertial scrolling system-wide",
    category: "animations",
    domain: "NSGlobalDomain",
    key: "NSScrollAnimationEnabled",
    type: "boolean",
    defaultValue: true,
    risk: "safe",
    tags: ["scroll"],
  },
  {
    id: "animations-window-resize-speed",
    title: "Window Resize Speed",
    description: "Control the speed of window resize animations in Cocoa apps",
    category: "animations",
    domain: "NSGlobalDomain",
    key: "NSWindowResizeTime",
    type: "enum",
    defaultValue: 0.2,
    options: [
      { title: "Instant", value: 0.001 },
      { title: "Fast (0.1s)", value: 0.1 },
      { title: "Default (0.2s)", value: 0.2 },
      { title: "Slow (0.5s)", value: 0.5 },
    ],
    risk: "safe",
    tags: ["resize", "speed"],
  },
  {
    id: "animations-disable-finder",
    title: "Disable All Finder Animations",
    description: "Disable all Finder animations (opening folders, Get Info, etc.)",
    category: "animations",
    domain: "com.apple.finder",
    key: "DisableAllAnimations",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["finder"],
  },
];
