import type { TweakDefinition } from "../types";

export const appsTweaks: TweakDefinition[] = [
  {
    id: "apps-textedit-plain-text",
    title: "TextEdit: Default to Plain Text",
    description: "Open new TextEdit documents in plain text mode instead of rich text",
    category: "apps",
    domain: "com.apple.TextEdit",
    key: "RichText",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "TextEdit",
    risk: "safe",
    tags: ["textedit", "plain text"],
  },
  {
    id: "apps-textedit-utf8",
    title: "TextEdit: Default Encoding",
    description: "Set the default plain text encoding in TextEdit",
    category: "apps",
    domain: "com.apple.TextEdit",
    key: "PlainTextEncoding",
    type: "enum",
    defaultValue: 0,
    options: [
      { title: "Automatic", value: 0 },
      { title: "UTF-8", value: 4 },
      { title: "Western (Mac OS Roman)", value: 30 },
    ],
    extraDefaults: [{ domain: "com.apple.TextEdit", key: "PlainTextEncodingForWrite", mirrorPrimary: true }],
    requiresRestart: "TextEdit",
    risk: "safe",
    tags: ["textedit", "encoding", "utf8"],
  },
  {
    id: "apps-activity-monitor-all-processes",
    title: "Activity Monitor: Show All Processes",
    description: "Show all processes by default instead of just your own",
    category: "apps",
    domain: "com.apple.ActivityMonitor",
    key: "ShowCategory",
    type: "enum",
    defaultValue: 100,
    options: [
      { title: "All Processes", value: 0 },
      { title: "My Processes", value: 100 },
      { title: "System Processes", value: 101 },
      { title: "Other User Processes", value: 102 },
    ],
    requiresRestart: "Activity Monitor",
    risk: "safe",
    tags: ["activity monitor", "processes"],
  },
];
