import type { TweakDefinition } from "../types";

export const desktopTweaks: TweakDefinition[] = [
  {
    id: "desktop-disable-mru-spaces",
    title: "Disable Auto-Rearrange Spaces",
    description: "Prevent macOS from automatically rearranging Spaces based on most recent use",
    category: "desktop",
    domain: "com.apple.dock",
    key: "mru-spaces",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["spaces", "mission control"],
  },
  {
    id: "desktop-show-icons",
    title: "Show Desktop Icons",
    description: "Show icons on the Desktop (disabling hides them, files still exist in ~/Desktop)",
    category: "desktop",
    domain: "com.apple.finder",
    key: "CreateDesktop",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["icons", "clean"],
  },
  {
    id: "desktop-hot-corner-top-left",
    title: "Hot Corner — Top Left",
    description: "Set the action for the top-left hot corner",
    category: "desktop",
    domain: "com.apple.dock",
    key: "wvous-tl-corner",
    type: "enum",
    defaultValue: 0,
    options: [
      { title: "None", value: 0 },
      { title: "Mission Control", value: 2 },
      { title: "Application Windows", value: 3 },
      { title: "Desktop", value: 4 },
      { title: "Screen Saver", value: 5 },
      { title: "Disable Screen Saver", value: 6 },
      { title: "Put Display to Sleep", value: 10 },
      { title: "Launchpad", value: 11 },
      { title: "Notification Center", value: 12 },
      { title: "Lock Screen", value: 13 },
      { title: "Quick Note", value: 14 },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["hot corner"],
  },
  {
    id: "desktop-hot-corner-top-right",
    title: "Hot Corner — Top Right",
    description: "Set the action for the top-right hot corner",
    category: "desktop",
    domain: "com.apple.dock",
    key: "wvous-tr-corner",
    type: "enum",
    defaultValue: 0,
    options: [
      { title: "None", value: 0 },
      { title: "Mission Control", value: 2 },
      { title: "Application Windows", value: 3 },
      { title: "Desktop", value: 4 },
      { title: "Screen Saver", value: 5 },
      { title: "Disable Screen Saver", value: 6 },
      { title: "Put Display to Sleep", value: 10 },
      { title: "Launchpad", value: 11 },
      { title: "Notification Center", value: 12 },
      { title: "Lock Screen", value: 13 },
      { title: "Quick Note", value: 14 },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["hot corner"],
  },
  {
    id: "desktop-hot-corner-bottom-left",
    title: "Hot Corner — Bottom Left",
    description: "Set the action for the bottom-left hot corner",
    category: "desktop",
    domain: "com.apple.dock",
    key: "wvous-bl-corner",
    type: "enum",
    defaultValue: 0,
    options: [
      { title: "None", value: 0 },
      { title: "Mission Control", value: 2 },
      { title: "Application Windows", value: 3 },
      { title: "Desktop", value: 4 },
      { title: "Screen Saver", value: 5 },
      { title: "Disable Screen Saver", value: 6 },
      { title: "Put Display to Sleep", value: 10 },
      { title: "Launchpad", value: 11 },
      { title: "Notification Center", value: 12 },
      { title: "Lock Screen", value: 13 },
      { title: "Quick Note", value: 14 },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["hot corner"],
  },
  {
    id: "desktop-hot-corner-bottom-right",
    title: "Hot Corner — Bottom Right",
    description: "Set the action for the bottom-right hot corner",
    category: "desktop",
    domain: "com.apple.dock",
    key: "wvous-br-corner",
    type: "enum",
    defaultValue: 0,
    options: [
      { title: "None", value: 0 },
      { title: "Mission Control", value: 2 },
      { title: "Application Windows", value: 3 },
      { title: "Desktop", value: 4 },
      { title: "Screen Saver", value: 5 },
      { title: "Disable Screen Saver", value: 6 },
      { title: "Put Display to Sleep", value: 10 },
      { title: "Launchpad", value: 11 },
      { title: "Notification Center", value: 12 },
      { title: "Lock Screen", value: 13 },
      { title: "Quick Note", value: 14 },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["hot corner"],
  },
];
