import type { TweakDefinition } from "../types";

export const dockTweaks: TweakDefinition[] = [
  {
    id: "dock-autohide",
    title: "Auto-Hide Dock",
    description: "Automatically hide and show the Dock",
    category: "dock",
    domain: "com.apple.dock",
    key: "autohide",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["autohide"],
  },
  {
    id: "dock-autohide-delay",
    title: "Auto-Hide Delay",
    description: "Delay in seconds before the Dock appears when hovering the screen edge",
    category: "dock",
    domain: "com.apple.dock",
    key: "autohide-delay",
    type: "enum",
    defaultValue: 0.5,
    options: [
      { title: "Instant (0s)", value: 0 },
      { title: "Fast (0.2s)", value: 0.2 },
      { title: "Default (0.5s)", value: 0.5 },
      { title: "Slow (1s)", value: 1 },
      { title: "Very Slow (2s)", value: 2 },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["autohide", "animation", "delay"],
  },
  {
    id: "dock-autohide-speed",
    title: "Auto-Hide Animation Speed",
    description: "How fast the Dock slides in and out (lower is faster, 0 is instant)",
    category: "dock",
    domain: "com.apple.dock",
    key: "autohide-time-modifier",
    type: "enum",
    defaultValue: 0.5,
    options: [
      { title: "Instant (0s)", value: 0 },
      { title: "Fast (0.15s)", value: 0.15 },
      { title: "Normal (0.3s)", value: 0.3 },
      { title: "Default (0.5s)", value: 0.5 },
      { title: "Slow (1s)", value: 1 },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["autohide", "animation", "speed"],
  },
  {
    id: "dock-icon-size",
    title: "Dock Icon Size",
    description: "Set the Dock icon size in pixels",
    category: "dock",
    domain: "com.apple.dock",
    key: "tilesize",
    type: "enum",
    defaultValue: 48,
    options: [
      { title: "Tiny (16px)", value: 16 },
      { title: "Small (32px)", value: 32 },
      { title: "Default (48px)", value: 48 },
      { title: "Large (64px)", value: 64 },
      { title: "Extra Large (96px)", value: 96 },
      { title: "Huge (128px)", value: 128 },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["size", "icons"],
  },
  {
    id: "dock-orientation",
    title: "Dock Position",
    description: "Move the Dock to a different screen edge",
    category: "dock",
    domain: "com.apple.dock",
    key: "orientation",
    type: "enum",
    defaultValue: "bottom",
    options: [
      { title: "Bottom", value: "bottom" },
      { title: "Left", value: "left" },
      { title: "Right", value: "right" },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["position", "layout"],
  },
  {
    id: "dock-minimize-effect",
    title: "Minimize Effect",
    description: "Change the window minimize animation style",
    category: "dock",
    domain: "com.apple.dock",
    key: "mineffect",
    type: "enum",
    defaultValue: "genie",
    options: [
      { title: "Genie", value: "genie" },
      { title: "Scale", value: "scale" },
      { title: "Suck", value: "suck" },
    ],
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["animation", "minimize"],
  },
  {
    id: "dock-show-indicators",
    title: "Show Open App Indicators",
    description: "Show a small dot below Dock icons of running apps",
    category: "dock",
    domain: "com.apple.dock",
    key: "show-process-indicators",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["indicators", "running"],
  },
  {
    id: "dock-show-recents",
    title: "Show Recent Applications",
    description: "Show the recent applications section at the right end of the Dock",
    category: "dock",
    domain: "com.apple.dock",
    key: "show-recents",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["recents"],
  },
  {
    id: "dock-minimize-to-app",
    title: "Minimize Into Application Icon",
    description: "Minimize windows into their app's Dock icon instead of a separate section",
    category: "dock",
    domain: "com.apple.dock",
    key: "minimize-to-application",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["minimize"],
  },
  {
    id: "dock-scroll-to-open",
    title: "Scroll to Open App Expose",
    description: "Use a scroll gesture on a Dock icon to show all its windows",
    category: "dock",
    domain: "com.apple.dock",
    key: "scroll-to-open",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Dock",
    risk: "safe",
    tags: ["expose", "scroll"],
  },
];
