import type { TweakDefinition } from "../types";

export const finderTweaks: TweakDefinition[] = [
  {
    id: "finder-show-hidden-files",
    title: "Show Hidden Files",
    description: "Show files and folders starting with a dot in Finder",
    category: "finder",
    domain: "com.apple.finder",
    key: "AppleShowAllFiles",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["dotfiles", "hidden"],
  },
  {
    id: "finder-show-all-extensions",
    title: "Show All File Extensions",
    description: "Always show file extensions in Finder, overriding per-file settings",
    category: "finder",
    domain: "NSGlobalDomain",
    key: "AppleShowAllExtensions",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["extensions", "files"],
  },
  {
    id: "finder-show-path-bar",
    title: "Show Path Bar",
    description: "Show the full path bar at the bottom of Finder windows",
    category: "finder",
    domain: "com.apple.finder",
    key: "ShowPathbar",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["navigation", "path"],
  },
  {
    id: "finder-show-status-bar",
    title: "Show Status Bar",
    description: "Show the status bar with item count and available disk space",
    category: "finder",
    domain: "com.apple.finder",
    key: "ShowStatusBar",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["status", "disk"],
  },
  {
    id: "finder-default-view-style",
    title: "Default View Style",
    description: "Set the default view for new Finder windows",
    category: "finder",
    domain: "com.apple.finder",
    key: "FXPreferredViewStyle",
    type: "enum",
    defaultValue: "icnv",
    options: [
      { title: "Icon", value: "icnv" },
      { title: "List", value: "Nlsv" },
      { title: "Column", value: "clmv" },
      { title: "Gallery", value: "glyv" },
    ],
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["view", "layout"],
  },
  {
    id: "finder-search-current-folder",
    title: "Search Current Folder by Default",
    description: "Search the current folder instead of the entire Mac when using Finder search",
    category: "finder",
    domain: "com.apple.finder",
    key: "FXDefaultSearchScope",
    type: "enum",
    defaultValue: "SCev",
    options: [
      { title: "Current Folder", value: "SCcf" },
      { title: "Previous Scope", value: "SCsp" },
      { title: "This Mac", value: "SCev" },
    ],
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["search"],
  },
  {
    id: "finder-disable-extension-change-warning",
    title: "Disable Extension Change Warning",
    description: "Skip the confirmation dialog when changing a file extension",
    category: "finder",
    domain: "com.apple.finder",
    key: "FXEnableExtensionChangeWarning",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["dialog", "extensions"],
  },
  {
    id: "finder-disable-empty-trash-warning",
    title: "Disable Empty Trash Warning",
    description: "Skip the confirmation dialog when emptying the Trash",
    category: "finder",
    domain: "com.apple.finder",
    key: "WarnOnEmptyTrash",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["dialog", "trash"],
  },
  {
    id: "finder-posix-path-in-title",
    title: "Show Full Path in Title Bar",
    description: "Replace the folder name in the title bar with the full POSIX path",
    category: "finder",
    domain: "com.apple.finder",
    key: "_FXShowPosixPathInTitle",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["path", "title"],
  },
  {
    id: "finder-folders-on-top",
    title: "Keep Folders on Top",
    description: "Keep folders grouped at the top when sorting by name",
    category: "finder",
    domain: "com.apple.finder",
    key: "_FXSortFoldersFirst",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["sort", "folders"],
  },
  {
    id: "finder-folders-on-top-desktop",
    title: "Keep Folders on Top (Desktop)",
    description: "Keep folders grouped at the top on the Desktop",
    category: "finder",
    domain: "com.apple.finder",
    key: "_FXSortFoldersFirstOnDesktop",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["sort", "folders", "desktop"],
  },
  {
    id: "finder-no-ds-store-network",
    title: "Disable .DS_Store on Network Volumes",
    description: "Prevent Finder from creating .DS_Store files on network volumes",
    category: "finder",
    domain: "com.apple.desktopservices",
    key: "DSDontWriteNetworkStores",
    type: "boolean",
    defaultValue: false,
    risk: "safe",
    tags: ["ds_store", "network"],
  },
  {
    id: "finder-no-ds-store-usb",
    title: "Disable .DS_Store on USB Volumes",
    description: "Prevent Finder from creating .DS_Store files on USB drives",
    category: "finder",
    domain: "com.apple.desktopservices",
    key: "DSDontWriteUSBStores",
    type: "boolean",
    defaultValue: false,
    risk: "safe",
    tags: ["ds_store", "usb"],
  },
  {
    id: "finder-new-window-target",
    title: "New Finder Window Opens To",
    description: "Set what new Finder windows open to by default",
    category: "finder",
    domain: "com.apple.finder",
    key: "NewWindowTarget",
    type: "enum",
    defaultValue: "PfHm",
    options: [
      { title: "Home", value: "PfHm" },
      { title: "Desktop", value: "PfDe" },
      { title: "Documents", value: "PfDo" },
      { title: "Computer", value: "PfCm" },
      { title: "Volume", value: "PfVo" },
    ],
    requiresRestart: "Finder",
    risk: "safe",
    tags: ["window", "default"],
  },
  {
    id: "finder-expand-save-panel",
    title: "Expand Save Panel by Default",
    description: "Automatically expand the Save dialog to show the full file browser",
    category: "finder",
    domain: "NSGlobalDomain",
    key: "NSNavPanelExpandedStateForSaveMode",
    type: "boolean",
    defaultValue: false,
    extraDefaults: [{ domain: "NSGlobalDomain", key: "NSNavPanelExpandedStateForSaveMode2", value: true }],
    risk: "safe",
    tags: ["save", "dialog"],
  },
  {
    id: "finder-expand-print-panel",
    title: "Expand Print Panel by Default",
    description: "Automatically expand the Print dialog to show all options",
    category: "finder",
    domain: "NSGlobalDomain",
    key: "PMPrintingExpandedStateForPrint",
    type: "boolean",
    defaultValue: false,
    extraDefaults: [{ domain: "NSGlobalDomain", key: "PMPrintingExpandedStateForPrint2", value: true }],
    risk: "safe",
    tags: ["print", "dialog"],
  },
];
