import type { TweakDefinition } from "../types";

export const keyboardTweaks: TweakDefinition[] = [
  {
    id: "keyboard-repeat-rate",
    title: "Key Repeat Rate",
    description: "How fast keys repeat when held down (lower number is faster)",
    category: "keyboard",
    domain: "NSGlobalDomain",
    key: "KeyRepeat",
    type: "enum",
    defaultValue: 6,
    options: [
      { title: "Fastest (1)", value: 1 },
      { title: "Fast (2)", value: 2 },
      { title: "Default (6)", value: 6 },
      { title: "Slow (12)", value: 12 },
    ],
    risk: "safe",
    tags: ["repeat", "speed"],
  },
  {
    id: "keyboard-initial-repeat-delay",
    title: "Initial Key Repeat Delay",
    description: "Delay before key repeat starts when holding a key",
    category: "keyboard",
    domain: "NSGlobalDomain",
    key: "InitialKeyRepeat",
    type: "enum",
    defaultValue: 25,
    options: [
      { title: "Shortest (10)", value: 10 },
      { title: "Short (15)", value: 15 },
      { title: "Default (25)", value: 25 },
      { title: "Long (68)", value: 68 },
      { title: "Longest (120)", value: 120 },
    ],
    risk: "safe",
    tags: ["repeat", "delay"],
  },
  {
    id: "keyboard-disable-autocorrect",
    title: "Disable Auto-Correct",
    description: "Disable automatic spelling correction system-wide",
    category: "keyboard",
    domain: "NSGlobalDomain",
    key: "NSAutomaticSpellingCorrectionEnabled",
    type: "boolean",
    defaultValue: true,
    risk: "safe",
    tags: ["autocorrect", "spelling"],
  },
  {
    id: "keyboard-disable-autocapitalize",
    title: "Disable Auto-Capitalization",
    description: "Disable automatic capitalization of the first letter",
    category: "keyboard",
    domain: "NSGlobalDomain",
    key: "NSAutomaticCapitalizationEnabled",
    type: "boolean",
    defaultValue: true,
    risk: "safe",
    tags: ["capitalization"],
  },
  {
    id: "keyboard-disable-smart-quotes",
    title: "Disable Smart Quotes & Dashes",
    description: "Prevent auto-converting straight quotes to curly quotes and hyphens to em-dashes",
    category: "keyboard",
    domain: "NSGlobalDomain",
    key: "NSAutomaticQuoteSubstitutionEnabled",
    type: "boolean",
    defaultValue: true,
    extraDefaults: [{ domain: "NSGlobalDomain", key: "NSAutomaticDashSubstitutionEnabled", value: false }],
    risk: "safe",
    tags: ["quotes", "dashes", "developer"],
  },
  {
    id: "keyboard-press-and-hold",
    title: "Press-and-Hold Key Repeat",
    description:
      "Repeat the character on long press instead of showing the accent picker. Required for Vim and game key-repeat",
    category: "keyboard",
    domain: "NSGlobalDomain",
    key: "ApplePressAndHoldEnabled",
    type: "boolean",
    defaultValue: true,
    risk: "safe",
    tags: ["repeat", "accents", "vim"],
  },
  {
    id: "keyboard-full-access",
    title: "Full Keyboard Access",
    description: "Use Tab to move focus through all controls in dialogs, not just text boxes and lists",
    category: "keyboard",
    domain: "NSGlobalDomain",
    key: "AppleKeyboardUIMode",
    type: "enum",
    defaultValue: 0,
    options: [
      { title: "Text Boxes and Lists Only", value: 0 },
      { title: "All Controls", value: 2 },
      { title: "All Controls + Tab", value: 3 },
    ],
    risk: "safe",
    tags: ["accessibility", "tab", "navigation"],
  },
  {
    id: "keyboard-double-space-period",
    title: "Double-Space to Period",
    description: "Insert a period when you type two spaces in a row",
    category: "keyboard",
    domain: "NSGlobalDomain",
    key: "NSAutomaticPeriodSubstitutionEnabled",
    type: "boolean",
    defaultValue: true,
    risk: "safe",
    tags: ["text", "substitution"],
  },
];
