import type { TweakDefinition } from "../types";

export const menubarTweaks: TweakDefinition[] = [
  {
    id: "menubar-flash-separators",
    title: "Flash Clock Separators",
    description: "Make the colon in the menu bar clock blink every second",
    category: "menubar",
    domain: "com.apple.menuextra.clock",
    key: "FlashDateSeparators",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["clock", "blink"],
  },
  {
    id: "menubar-clock-format",
    title: "Clock Format",
    description: "Set the menu bar clock format",
    category: "menubar",
    domain: "com.apple.menuextra.clock",
    key: "DateFormat",
    type: "enum",
    defaultValue: "h:mm a",
    options: [
      { title: "12h (1:30 PM)", value: "h:mm a" },
      { title: "24h (13:30)", value: "HH:mm" },
      { title: "24h with seconds (13:30:00)", value: "HH:mm:ss" },
      { title: "Date + 24h (Apr 12 13:30)", value: "MMM d HH:mm" },
    ],
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["clock", "time", "format"],
  },
  {
    id: "menubar-show-bluetooth",
    title: "Show Bluetooth in Menu Bar",
    description: "Show the Bluetooth icon in the menu bar",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "NSStatusItem Visible Bluetooth",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["bluetooth", "icon"],
  },
  {
    id: "menubar-menu-action-images",
    title: "Show Icons in Menus",
    description: "Show the icons next to menu items (e.g. File › New Folder in Finder). Introduced in macOS Tahoe.",
    category: "menubar",
    domain: "NSGlobalDomain",
    key: "NSMenuEnableActionImages",
    type: "boolean",
    defaultValue: true,
    minMacOS: "26.0",
    risk: "safe",
    tags: ["menu", "icons", "tahoe"],
  },
];
