import type { TweakDefinition } from "../types";

export const menubarTweaks: TweakDefinition[] = [
  {
    id: "menubar-flash-separators",
    title: "Flash Clock Separators",
    description: "Make the colon in the menu bar clock blink every second",
    category: "menubar",
    domain: "com.apple.menuextra.clock",
    key: "FlashDateSeparators",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["clock", "blink"],
  },
  {
    id: "menubar-clock-format",
    title: "Clock Format",
    description: "Set the menu bar clock format",
    category: "menubar",
    domain: "com.apple.menuextra.clock",
    key: "DateFormat",
    type: "enum",
    defaultValue: "h:mm a",
    options: [
      { title: "12h (1:30 PM)", value: "h:mm a" },
      { title: "24h (13:30)", value: "HH:mm" },
      { title: "24h with seconds (13:30:00)", value: "HH:mm:ss" },
      { title: "Date + 24h (Apr 12 13:30)", value: "MMM d HH:mm" },
    ],
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["clock", "time", "format"],
  },
  {
    id: "menubar-show-bluetooth",
    title: "Show Bluetooth in Menu Bar",
    description: "Show the Bluetooth icon in the menu bar",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "NSStatusItem Visible Bluetooth",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["bluetooth", "icon"],
  },
  {
    id: "menubar-menu-action-images",
    title: "Show Icons in Menus",
    description: "Show the icons next to menu items (e.g. File › New Folder in Finder). Introduced in macOS Tahoe.",
    category: "menubar",
    domain: "NSGlobalDomain",
    key: "NSMenuEnableActionImages",
    type: "boolean",
    defaultValue: true,
    minMacOS: "26.0",
    risk: "safe",
    tags: ["menu", "icons", "tahoe"],
  },
  {
    id: "menubar-show-sound",
    title: "Show Sound in Menu Bar",
    description: "Show the volume / sound icon in the menu bar",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "NSStatusItem Visible Sound",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["sound", "volume", "icon"],
  },
  {
    id: "menubar-battery-percentage",
    title: "Show Battery Percentage",
    description: "Show the battery percentage next to the menu bar battery icon",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "BatteryShowPercentage",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["battery", "percent"],
  },
  {
    id: "menubar-show-airdrop",
    title: "Show AirDrop in Menu Bar",
    description: "Show the AirDrop icon in the menu bar",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "NSStatusItem Visible AirDrop",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["airdrop", "icon"],
  },
  {
    id: "menubar-show-screen-mirroring",
    title: "Show Screen Mirroring in Menu Bar",
    description: "Show the Screen Mirroring icon in the menu bar",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "NSStatusItem Visible ScreenMirroring",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["screen mirroring", "airplay", "icon"],
  },
  {
    id: "menubar-show-focus",
    title: "Show Focus in Menu Bar",
    description: "Show the Focus modes icon in the menu bar",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "NSStatusItem Visible FocusModes",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["focus", "do not disturb", "icon"],
  },
  {
    id: "menubar-show-now-playing",
    title: "Show Now Playing in Menu Bar",
    description: "Show the Now Playing icon in the menu bar",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "NSStatusItem Visible NowPlaying",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["now playing", "music", "icon"],
  },
  {
    id: "menubar-show-fast-user-switching",
    title: "Show Fast User Switching in Menu Bar",
    description: "Show the user-switching icon in the menu bar",
    category: "menubar",
    domain: "com.apple.controlcenter",
    key: "NSStatusItem Visible UserSwitcher",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "ControlCenter",
    risk: "safe",
    tags: ["user switcher", "icon"],
  },
];
