import type { TweakDefinition } from "../types";

export const miscTweaks: TweakDefinition[] = [
  {
    id: "misc-disable-crash-reporter",
    title: "Disable Crash Reporter Dialog",
    description: "Suppress the crash reporter dialog when an app crashes",
    category: "misc",
    domain: "com.apple.CrashReporter",
    key: "DialogType",
    type: "enum",
    defaultValue: "prompt",
    options: [
      { title: "Disabled", value: "none" },
      { title: "Prompt (Default)", value: "prompt" },
      { title: "Send Automatically", value: "server" },
    ],
    risk: "safe",
    tags: ["crash", "dialog"],
  },
  {
    id: "misc-skip-dmg-verification",
    title: "Skip Disk Image Verification",
    description: "Skip checksum verification when mounting .dmg files (faster opening)",
    category: "misc",
    domain: "com.apple.frameworks.diskimages",
    key: "skip-verify",
    type: "boolean",
    defaultValue: false,
    extraDefaults: [
      { domain: "com.apple.frameworks.diskimages", key: "skip-verify-locked", value: true },
      { domain: "com.apple.frameworks.diskimages", key: "skip-verify-remote", value: true },
    ],
    risk: "moderate",
    tags: ["dmg", "verification", "speed"],
  },
  {
    id: "misc-spring-loading-delay",
    title: "Spring Loading Delay",
    description: "Set the delay for spring-loaded folders (hover to open while dragging)",
    category: "misc",
    domain: "NSGlobalDomain",
    key: "com.apple.springing.delay",
    type: "enum",
    defaultValue: 0.5,
    options: [
      { title: "Instant (0s)", value: 0 },
      { title: "Fast (0.2s)", value: 0.2 },
      { title: "Default (0.5s)", value: 0.5 },
      { title: "Slow (1s)", value: 1 },
    ],
    risk: "safe",
    tags: ["spring loading", "folders", "drag"],
  },
  {
    id: "misc-save-to-disk",
    title: "Save to Disk by Default",
    description: "Default to saving files to local disk instead of iCloud in Save dialogs",
    category: "misc",
    domain: "NSGlobalDomain",
    key: "NSDocumentSaveNewDocumentsToCloud",
    type: "boolean",
    defaultValue: true,
    risk: "safe",
    tags: ["save", "icloud", "local"],
  },
];
