import type { TweakDefinition } from "../types";

export const safariTweaks: TweakDefinition[] = [
  {
    id: "safari-show-full-url",
    title: "Show Full URL",
    description: "Show the complete URL in the address bar instead of just the domain",
    category: "safari",
    domain: "com.apple.Safari",
    key: "ShowFullURLInSmartSearchField",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Safari",
    risk: "safe",
    tags: ["url", "address bar"],
  },
  {
    id: "safari-develop-menu",
    title: "Enable Develop Menu",
    description: "Show the Develop menu in Safari's menu bar for web development tools",
    category: "safari",
    domain: "com.apple.Safari",
    key: "IncludeDevelopMenu",
    type: "boolean",
    defaultValue: false,
    extraDefaults: [
      { domain: "com.apple.Safari", key: "WebKitDeveloperExtrasEnabledPreferenceKey", value: true },
      {
        domain: "com.apple.Safari",
        key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled",
        value: true,
      },
    ],
    requiresRestart: "Safari",
    risk: "safe",
    tags: ["develop", "web", "inspector"],
  },
  {
    id: "safari-disable-auto-open",
    title: "Disable Auto-Open Safe Downloads",
    description: "Prevent Safari from automatically opening files it considers safe after download",
    category: "safari",
    domain: "com.apple.Safari",
    key: "AutoOpenSafeDownloads",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "Safari",
    risk: "safe",
    tags: ["downloads", "security"],
  },
  {
    id: "safari-status-bar",
    title: "Show Status Bar on Hover",
    description: "Show a status bar overlay with URL previews when hovering over links",
    category: "safari",
    domain: "com.apple.Safari",
    key: "ShowOverlayStatusBar",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Safari",
    risk: "safe",
    tags: ["status bar", "links"],
  },
  {
    id: "safari-backspace-navigation",
    title: "Enable Backspace Key Navigation",
    description: "Re-enable the Delete (Backspace) key as a back navigation shortcut",
    category: "safari",
    domain: "com.apple.Safari",
    key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "Safari",
    risk: "safe",
    tags: ["navigation", "backspace"],
  },
];
