import type { TweakDefinition } from "../types";

export const screenshotsTweaks: TweakDefinition[] = [
  {
    id: "screenshots-save-location",
    title: "Screenshot Save Location",
    description: "Change where screenshots are saved",
    category: "screenshots",
    domain: "com.apple.screencapture",
    key: "location",
    type: "enum",
    defaultValue: "~/Desktop",
    options: [
      { title: "Desktop", value: "~/Desktop" },
      { title: "Documents", value: "~/Documents" },
      { title: "Pictures/Screenshots", value: "~/Pictures/Screenshots" },
      { title: "Downloads", value: "~/Downloads" },
    ],
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["location", "path"],
  },
  {
    id: "screenshots-format",
    title: "Screenshot File Format",
    description: "Change the default screenshot file format",
    category: "screenshots",
    domain: "com.apple.screencapture",
    key: "type",
    type: "enum",
    defaultValue: "png",
    options: [
      { title: "PNG", value: "png" },
      { title: "JPEG", value: "jpg" },
      { title: "GIF", value: "gif" },
      { title: "TIFF", value: "tiff" },
      { title: "BMP", value: "bmp" },
      { title: "PDF", value: "pdf" },
    ],
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["format", "image"],
  },
  {
    id: "screenshots-disable-shadow",
    title: "Disable Window Screenshot Shadow",
    description: "Remove the drop shadow from window screenshots (Cmd+Shift+4, then Space)",
    category: "screenshots",
    domain: "com.apple.screencapture",
    key: "disable-shadow",
    type: "boolean",
    defaultValue: false,
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["shadow"],
  },
  {
    id: "screenshots-include-date",
    title: "Include Date in Filename",
    description: "Include the timestamp in screenshot filenames",
    category: "screenshots",
    domain: "com.apple.screencapture",
    key: "include-date",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["filename", "date"],
  },
  {
    id: "screenshots-show-thumbnail",
    title: "Show Thumbnail Preview",
    description: "Show the floating thumbnail in the corner after taking a screenshot",
    category: "screenshots",
    domain: "com.apple.screencapture",
    key: "show-thumbnail",
    type: "boolean",
    defaultValue: true,
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["thumbnail", "preview"],
  },
  {
    id: "screenshots-filename-prefix",
    title: "Screenshot Filename Prefix",
    description: 'Change the prefix used in screenshot filenames (e.g. "Screen 2026-01-01 at 10.00.00.png")',
    category: "screenshots",
    domain: "com.apple.screencapture",
    key: "name",
    type: "enum",
    defaultValue: "Screenshot",
    options: [
      { title: "Screenshot (default)", value: "Screenshot" },
      { title: "Screen", value: "Screen" },
      { title: "Capture", value: "Capture" },
      { title: "Snap", value: "Snap" },
      { title: "Shot", value: "Shot" },
    ],
    requiresRestart: "SystemUIServer",
    risk: "safe",
    tags: ["filename", "prefix"],
  },
];
