import type { TweakDefinition } from "../types";

export const trackpadTweaks: TweakDefinition[] = [
  {
    id: "trackpad-tap-to-click",
    title: "Tap to Click",
    description: "Enable tap-to-click on the trackpad instead of requiring a physical press",
    category: "trackpad",
    domain: "com.apple.AppleMultitouchTrackpad",
    key: "Clicking",
    type: "boolean",
    defaultValue: false,
    extraDefaults: [{ domain: "com.apple.driver.AppleBluetoothMultitouch.trackpad", key: "Clicking", value: true }],
    risk: "safe",
    tags: ["tap", "click"],
  },
  {
    id: "trackpad-three-finger-drag",
    title: "Three-Finger Drag",
    description: "Enable dragging windows with three fingers on the trackpad",
    category: "trackpad",
    domain: "com.apple.AppleMultitouchTrackpad",
    key: "TrackpadThreeFingerDrag",
    type: "boolean",
    defaultValue: false,
    extraDefaults: [
      {
        domain: "com.apple.driver.AppleBluetoothMultitouch.trackpad",
        key: "TrackpadThreeFingerDrag",
        value: true,
      },
    ],
    risk: "safe",
    tags: ["drag", "three finger"],
  },
  {
    id: "trackpad-tracking-speed",
    title: "Tracking Speed",
    description: "Set the trackpad cursor tracking speed (higher is faster)",
    category: "trackpad",
    domain: "NSGlobalDomain",
    key: "com.apple.trackpad.scaling",
    type: "enum",
    defaultValue: 1.0,
    options: [
      { title: "Very Slow (0.5)", value: 0.5 },
      { title: "Default (1.0)", value: 1.0 },
      { title: "Fast (2.0)", value: 2.0 },
      { title: "Very Fast (3.0)", value: 3.0 },
    ],
    risk: "safe",
    tags: ["speed", "cursor"],
  },
  {
    id: "trackpad-natural-scroll",
    title: "Natural Scroll Direction",
    description: "Use natural (reversed) scroll direction",
    category: "trackpad",
    domain: "NSGlobalDomain",
    key: "com.apple.swipescrolldirection",
    type: "boolean",
    defaultValue: true,
    risk: "safe",
    tags: ["scroll", "direction"],
  },
];
