import type { TweakDefinition } from "../types";

export const windowsTweaks: TweakDefinition[] = [
  {
    id: "windows-click-wallpaper-to-show-desktop",
    title: "Click Wallpaper to Show Desktop",
    description:
      "Clicking the wallpaper moves every window aside to reveal the desktop. Turn this off to only reveal the desktop while in Stage Manager",
    category: "windows",
    domain: "com.apple.WindowManager",
    key: "EnableStandardClickToShowDesktop",
    type: "boolean",
    defaultValue: true,
    minMacOS: "14.0",
    risk: "safe",
    tags: ["desktop", "wallpaper", "click", "sonoma"],
  },
  {
    id: "windows-stage-manager",
    title: "Stage Manager",
    description: "Keep the frontmost window centred and the other apps in a strip along the side of the screen",
    category: "windows",
    domain: "com.apple.WindowManager",
    key: "GloballyEnabled",
    type: "boolean",
    defaultValue: false,
    minMacOS: "13.0",
    risk: "safe",
    tags: ["stage manager", "windows"],
  },
  {
    id: "windows-stage-manager-auto-hide",
    title: "Auto-Hide the Stage Manager Strip",
    description: "Hide the strip of recent apps until the pointer reaches the edge of the screen",
    category: "windows",
    domain: "com.apple.WindowManager",
    key: "AutoHide",
    type: "boolean",
    defaultValue: false,
    minMacOS: "13.0",
    risk: "safe",
    tags: ["stage manager", "autohide", "strip"],
  },
  {
    id: "windows-app-window-grouping",
    title: "Show Windows From an Application",
    description: "In Stage Manager, whether clicking an app brings up all of its windows at once or one at a time",
    category: "windows",
    domain: "com.apple.WindowManager",
    key: "AppWindowGroupingBehavior",
    type: "enum",
    defaultValue: 1,
    options: [
      { title: "One at a Time", value: 0 },
      { title: "All at Once", value: 1 },
    ],
    minMacOS: "13.0",
    risk: "safe",
    tags: ["stage manager", "windows", "grouping"],
  },
  {
    id: "windows-hide-desktop-icons",
    title: "Hide Desktop Icons",
    description: "Hide every item on the desktop. The files stay in the Desktop folder and are still there in Finder",
    category: "windows",
    domain: "com.apple.WindowManager",
    key: "StandardHideDesktopIcons",
    type: "boolean",
    defaultValue: false,
    minMacOS: "14.0",
    risk: "safe",
    tags: ["desktop", "icons", "clutter"],
  },
  {
    id: "windows-hide-desktop-widgets",
    title: "Hide Desktop Widgets",
    description: "Hide the widgets placed on the desktop",
    category: "windows",
    domain: "com.apple.WindowManager",
    key: "StandardHideWidgets",
    type: "boolean",
    defaultValue: false,
    minMacOS: "14.0",
    risk: "safe",
    tags: ["desktop", "widgets"],
  },
  {
    id: "windows-stage-manager-hide-widgets",
    title: "Hide Desktop Widgets in Stage Manager",
    description: "Hide the desktop widgets while Stage Manager is on, independently of the setting above",
    category: "windows",
    domain: "com.apple.WindowManager",
    key: "StageManagerHideWidgets",
    type: "boolean",
    defaultValue: false,
    minMacOS: "14.0",
    risk: "safe",
    tags: ["stage manager", "widgets"],
  },
  {
    id: "windows-tiled-margins",
    title: "Margins Between Tiled Windows",
    description: "Leave a gap around windows snapped side by side. Turn this off to have them meet edge to edge",
    category: "windows",
    domain: "com.apple.WindowManager",
    key: "EnableTiledWindowMargins",
    type: "boolean",
    defaultValue: true,
    minMacOS: "15.0",
    risk: "safe",
    tags: ["tiling", "windows", "margins", "sequoia"],
  },
  {
    id: "windows-double-click-title-bar",
    title: "Double-Click a Window's Title Bar",
    description: "What a double-click on the title bar does — fill the screen, zoom, or minimise the window",
    category: "windows",
    domain: "NSGlobalDomain",
    key: "AppleActionOnDoubleClick",
    type: "enum",
    defaultValue: "Fill",
    options: [
      { title: "Fill", value: "Fill" },
      { title: "Zoom", value: "Maximize" },
      { title: "Minimize", value: "Minimize" },
      { title: "Do Nothing", value: "None" },
    ],
    risk: "safe",
    tags: ["window", "title bar", "double click", "zoom"],
  },
];
