export const coders = [
  {
    id: "build_in_1647439541774",
    info: {
      name: "Base64 Encode",
      id: "build_in_1647439541774",
      icon: "terminal-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Coder"],
    },
    tactions: [{ type: "Encode & Decode", content: ["Encoder Base64"] }],
  },
  {
    id: "build_in_1647439470039",
    info: {
      name: "Base64 Decode",
      id: "build_in_1647439470039",
      icon: "terminal-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Coder"],
    },
    tactions: [{ type: "Encode & Decode", content: ["Decoder Base64"] }],
  },
  {
    id: "build_in_1647439572311",
    info: {
      name: "URL Encode",
      id: "build_in_1647439572311",
      icon: "link-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Coder"],
    },
    tactions: [{ type: "Encode & Decode", content: ["Encoder URL"] }],
  },
  {
    id: "build_in_1647439593389",
    info: {
      name: "URL Decode",
      id: "build_in_1647439593389",
      icon: "link-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Coder"],
    },
    tactions: [{ type: "Encode & Decode", content: ["Decoder URL"] }],
  },
  {
    id: "build_in_1733249491187",
    info: {
      name: "URL Encode Component",
      id: "build_in_1733249491187",
      icon: "link-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Coder"],
    },
    tactions: [{ type: "Encode & Decode Component", content: ["Encoder URL Component"] }],
  },
  {
    id: "build_in_1733249508004",
    info: {
      name: "URL Decode Component",
      id: "build_in_1733249508004",
      icon: "link-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Coder"],
    },
    tactions: [{ type: "Encode & Decode Component", content: ["Decoder URL Component"] }],
  },
  {
    id: "build_in_1733250735290",
    info: {
      name: "MD5",
      id: "build_in_1733250735290",
      icon: "hashtag-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Coder"],
    },
    tactions: [{ type: "Encode & Decode", content: ["Encoder MD5"] }],
  },
];

export const CODERS_SHORTCUTS = JSON.stringify(coders);
