export const markdowns = [
  {
    id: "build_in_1647443203978",
    info: {
      name: "Heading 1",
      id: "build_in_1647443203978",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["# $TEXT$", "$TEXT$"] }],
  },
  {
    id: "build_in_1647443221801",
    info: {
      name: "Heading 2",
      id: "build_in_1647443221801",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["## $TEXT$", "$TEXT$"] }],
  },
  {
    id: "build_in_1647443240284",
    info: {
      name: "Heading 3",
      id: "build_in_1647443240284",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["### $TEXT$", "$TEXT$"] }],
  },
  {
    id: "build_in_1647443150475",
    info: {
      name: "Horizontal Line",
      id: "build_in_1647443150475",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["------"] }],
  },
  {
    id: "build_in_1647440706193",
    info: {
      name: "Strong",
      id: "build_in_1647440706193",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["**$TEXT$**", "$TEXT$"] }],
  },
  {
    id: "build_in_1647440760358",
    info: {
      name: "Emphasis",
      id: "build_in_1647440760358",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["*$TEXT$*", "$TEXT$"] }],
  },
  {
    id: "build_in_1647440802239",
    info: {
      name: "Strong&Emphasis",
      id: "build_in_1647440802239",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["***$TEXT$***", "$TEXT$"] }],
  },
  {
    id: "build_in_1647441893669",
    info: {
      name: "Highlight",
      id: "build_in_1647441893669",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["==$TEXT$==", "$TEXT$"] }],
  },
  {
    id: "build_in_1647441950187",
    info: {
      name: "Strike",
      id: "build_in_1647441950187",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["~~$TEXT$~~", "$TEXT$"] }],
  },
  {
    id: "build_in_1647442258487",
    info: {
      name: "Underline",
      id: "build_in_1647442258487",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["<u>$TEXT$</u>", "$TEXT$"] }],
  },
  {
    id: "build_in_1647440897610",
    info: {
      name: "List Ordered",
      id: "build_in_1647440897610",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["1. $LINE$", "$LINE$"] }],
  },
  {
    id: "build_in_1647440921890",
    info: {
      name: "List Unordered",
      id: "build_in_1647440921890",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["- $LINE$", "$LINE$"] }],
  },
  {
    id: "build_in_1647443032167",
    info: {
      name: "Task List",
      id: "build_in_1647443032167",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["- [ ] $LINE$", "$LINE$"] }],
  },
  {
    id: "build_in_1647441000319",
    info: {
      name: "Image",
      id: "build_in_1647441000319",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["![$TEXT$]()", "$TEXT$"] }],
  },
  {
    id: "build_in_1647442293304",
    info: {
      name: "Code",
      id: "build_in_1647442293304",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["`$TEXT$`", "$TEXT$"] }],
  },
  {
    id: "build_in_1647441093441",
    info: {
      name: "Code Fences",
      id: "build_in_1647441093441",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["```\n$TEXT$\n```", "$TEXT$"] }],
  },
  {
    id: "build_in_1647441516972",
    info: {
      name: "Hyperlink",
      id: "build_in_1647441516972",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["[$TEXT$]()", "$TEXT$"] }],
  },
  {
    id: "build_in_1647441619992",
    info: {
      name: "Table",
      id: "build_in_1647441619992",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [
      {
        type: "Live Template",
        content: [
          "|      |      |      |\n| ---- | ---- | ---- |\n|      |      |      |\n|      |      |      |\n|      |      |      |\n",
        ],
      },
    ],
  },
  {
    id: "build_in_1647441750956",
    info: {
      name: "Comment",
      id: "build_in_1647441750956",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["<!--$TEXT$-->", "$TEXT$"] }],
  },

  {
    id: "build_in_1647442341516",
    info: {
      name: "Inline Math",
      id: "build_in_1647442341516",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["$$TEXT$$", "$TEXT$"] }],
  },
  {
    id: "build_in_1647442414040",
    info: {
      name: "Superscript",
      id: "build_in_1647442414040",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["^$TEXT$^", "$TEXT$"] }],
  },
  {
    id: "build_in_1647442448465",
    info: {
      name: "Subscript",
      id: "build_in_1647442448465",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["~$TEXT$~", "$TEXT$"] }],
  },
  {
    id: "build_in_1647442850830",
    info: {
      name: "Math Block",
      id: "build_in_1647442850830",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["$$\n$TEXT$\n$$", "$TEXT$"] }],
  },
  {
    id: "build_in_1647442953342",
    info: {
      name: "Quote",
      id: "build_in_1647442953342",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["> $LINE$", "$LINE$"] }],
  },

  {
    id: "build_in_1647443479565",
    info: {
      name: "Footnotes",
      id: "build_in_1647443479565",
      icon: "quote-block-16",
      iconColor: "raycast-secondary-text",
      source: "Build-in",
      visibility: true,
      tag: ["Markdown"],
    },
    tactions: [{ type: "Live Template", content: ["[^1]: $TEXT$", "$TEXT$"] }],
  },
];
export const MARKDOWNS_SHORTCUTS = JSON.stringify(markdowns);
