export type Platform = "macOS" | "Windows" | "Linux";

export interface Shortcut {
  title: string;
  keys: Record<Platform, string>;
  category: string;
}

export const CATEGORIES = [
  "Tools",
  "View",
  "Zoom",
  "Text",
  "Shape",
  "Selection",
  "Cursor",
  "Edit",
  "Transform",
  "Arrange",
  "Components",
  "Auto Layout",
] as const;

export const shortcuts: Shortcut[] = [
  // Tools
  { title: "Move", keys: { macOS: "V", Windows: "V", Linux: "V" }, category: "Tools" },
  { title: "Scale", keys: { macOS: "K", Windows: "K", Linux: "K" }, category: "Tools" },
  { title: "Frame", keys: { macOS: "F or A", Windows: "F or A", Linux: "F or A" }, category: "Tools" },
  { title: "Section", keys: { macOS: "⇧ S", Windows: "⇧ S", Linux: "⇧ S" }, category: "Tools" },
  { title: "Slice", keys: { macOS: "S", Windows: "S", Linux: "S" }, category: "Tools" },
  { title: "Rectangle", keys: { macOS: "R", Windows: "R", Linux: "R" }, category: "Tools" },
  { title: "Line", keys: { macOS: "L", Windows: "L", Linux: "L" }, category: "Tools" },
  { title: "Arrow", keys: { macOS: "⇧ L", Windows: "⇧ L", Linux: "⇧ L" }, category: "Tools" },
  { title: "Ellipse", keys: { macOS: "O", Windows: "O", Linux: "O" }, category: "Tools" },
  { title: "Place image", keys: { macOS: "⇧ ⌘ K", Windows: "⇧ Ctrl K", Linux: "⇧ Ctrl K" }, category: "Tools" },
  { title: "Pen", keys: { macOS: "P", Windows: "P", Linux: "P" }, category: "Tools" },
  { title: "Pencil", keys: { macOS: "⇧ P", Windows: "⇧ P", Linux: "⇧ P" }, category: "Tools" },
  { title: "Text", keys: { macOS: "T", Windows: "T", Linux: "T" }, category: "Tools" },
  { title: "Resources", keys: { macOS: "⇧ I", Windows: "⇧ I", Linux: "⇧ I" }, category: "Tools" },
  { title: "Hand", keys: { macOS: "H", Windows: "H", Linux: "H" }, category: "Tools" },
  { title: "Add comment", keys: { macOS: "C", Windows: "C", Linux: "C" }, category: "Tools" },
  { title: "Pick color", keys: { macOS: "I or Ctrl C", Windows: "I or Ctrl C", Linux: "I or Ctrl C" }, category: "Tools" },
  { title: "Quick actions", keys: { macOS: "⌘ / or ⌘ P", Windows: "Ctrl / or Ctrl P", Linux: "Ctrl / or Ctrl P" }, category: "Tools" },
  { title: "Run last plugin", keys: { macOS: "⌥ ⌘ P", Windows: "Alt Ctrl P", Linux: "Alt Ctrl P" }, category: "Tools" },

  // View
  { title: "Show/Hide UI", keys: { macOS: "\\ or ⌘ .", Windows: "\\ or Ctrl .", Linux: "\\ or Ctrl ." }, category: "View" },
  { title: "Minimize UI", keys: { macOS: "⇧ ⌘ \\", Windows: "⇧ Ctrl \\", Linux: "⇧ Ctrl \\" }, category: "View" },
  { title: "Multiplayer cursors", keys: { macOS: "⌥ ⌘ \\", Windows: "Alt Ctrl \\", Linux: "Alt Ctrl \\" }, category: "View" },
  { title: "Rulers", keys: { macOS: "⇧ R", Windows: "⇧ R", Linux: "⇧ R" }, category: "View" },
  { title: "Show outlines", keys: { macOS: "⇧ O or ⌘ Y", Windows: "Ctrl Y", Linux: "Ctrl Y" }, category: "View" },
  { title: "Pixel preview", keys: { macOS: "⌘ ⇧ P", Windows: "Ctrl ⇧ P", Linux: "Ctrl ⇧ P" }, category: "View" },
  { title: "Layout grids", keys: { macOS: "⇧ G", Windows: "⇧ G", Linux: "⇧ G" }, category: "View" },
  { title: "Pixel grid", keys: { macOS: "⇧ ' or ⌘ '", Windows: "Ctrl '", Linux: "Ctrl '" }, category: "View" },
  { title: "Collapse layers", keys: { macOS: "⌥ L", Windows: "Alt L", Linux: "Alt L" }, category: "View" },
  { title: "Layers panel", keys: { macOS: "⌥ 1", Windows: "Alt 1", Linux: "Alt 1" }, category: "View" },
  { title: "Assets panel", keys: { macOS: "⌥ 2", Windows: "Alt 2", Linux: "Alt 2" }, category: "View" },
  { title: "Find and replace", keys: { macOS: "⌘ F", Windows: "Ctrl F", Linux: "Ctrl F" }, category: "View" },
  { title: "Libraries", keys: { macOS: "⌥ 3", Windows: "Alt 3", Linux: "Alt 3" }, category: "View" },
  { title: "Design panel", keys: { macOS: "⌥ 8", Windows: "Alt 8", Linux: "Alt 8" }, category: "View" },
  { title: "Prototype panel", keys: { macOS: "⌥ 9", Windows: "Alt 9", Linux: "Alt 9" }, category: "View" },
  { title: "Inspect panel", keys: { macOS: "⌥ 0", Windows: "Alt 0", Linux: "Alt 0" }, category: "View" },
  { title: "Toggle design/prototype panel", keys: { macOS: "⇧ E", Windows: "⇧ E", Linux: "⇧ E" }, category: "View" },
  { title: "Show/Hide comments", keys: { macOS: "⇧ C", Windows: "⇧ C", Linux: "⇧ C" }, category: "View" },
  { title: "Show/Hide left panel", keys: { macOS: "⇧ ⌘ \\", Windows: "⇧ Ctrl \\", Linux: "⇧ Ctrl \\" }, category: "View" },
  { title: "Present (play the prototype)", keys: { macOS: "⌥ ⌘ Enter", Windows: "Alt Ctrl Enter", Linux: "Alt Ctrl Enter" }, category: "View" },
  { title: "Preview (play prototype on canvas)", keys: { macOS: "⇧ Space", Windows: "⇧ Space", Linux: "⇧ Space" }, category: "View" },
  { title: "Switch between files", keys: { macOS: "⌥ ⌘ ← →", Windows: "Alt Ctrl ← →", Linux: "Alt Ctrl ← →" }, category: "View" },
  { title: "Switch between pages", keys: { macOS: "fn ↓ ↑", Windows: "PgUp / PgDown", Linux: "PgUp / PgDown" }, category: "View" },
  { title: "Dev mode/Design mode", keys: { macOS: "⇧ D", Windows: "⇧ D", Linux: "⇧ D" }, category: "View" },

  // Zoom
  { title: "Zoom in", keys: { macOS: "+", Windows: "+", Linux: "+" }, category: "Zoom" },
  { title: "Zoom out", keys: { macOS: "-", Windows: "-", Linux: "-" }, category: "Zoom" },
  { title: "Zoom to 100%", keys: { macOS: "⌘ 0", Windows: "Ctrl 0", Linux: "Ctrl 0" }, category: "Zoom" },
  { title: "Zoom to fit", keys: { macOS: "⇧ 1", Windows: "⇧ 1", Linux: "⇧ 1" }, category: "Zoom" },
  { title: "Zoom to selection", keys: { macOS: "⇧ 2", Windows: "⇧ 2", Linux: "⇧ 2" }, category: "Zoom" },
  { title: "Zoom to previous frame", keys: { macOS: "⇧ N", Windows: "⇧ N", Linux: "⇧ N" }, category: "Zoom" },
  { title: "Zoom to next frame", keys: { macOS: "N", Windows: "N", Linux: "N" }, category: "Zoom" },

  // Text
  { title: "Bold", keys: { macOS: "⌘ B", Windows: "Ctrl B", Linux: "Ctrl B" }, category: "Text" },
  { title: "Italic", keys: { macOS: "⌘ I", Windows: "Ctrl I", Linux: "Ctrl I" }, category: "Text" },
  { title: "Underline", keys: { macOS: "⌘ U", Windows: "Ctrl U", Linux: "Ctrl U" }, category: "Text" },
  { title: "Strikethrough", keys: { macOS: "⇧ ⌘ X", Windows: "⇧ Ctrl X", Linux: "⇧ Ctrl X" }, category: "Text" },
  { title: "Create link", keys: { macOS: "⇧ ⌘ U", Windows: "⇧ Ctrl U", Linux: "⇧ Ctrl U" }, category: "Text" },
  { title: "Bulleted list", keys: { macOS: "⇧ ⌘ 8", Windows: "⇧ Ctrl 8", Linux: "⇧ Ctrl 8" }, category: "Text" },
  { title: "Numbered list", keys: { macOS: "⇧ ⌘ 7", Windows: "⇧ Ctrl 7", Linux: "⇧ Ctrl 7" }, category: "Text" },
  { title: "Text align left", keys: { macOS: "⌥ ⌘ L", Windows: "Alt Ctrl L", Linux: "Alt Ctrl L" }, category: "Text" },
  { title: "Text align center", keys: { macOS: "⌥ ⌘ T", Windows: "Alt Ctrl T", Linux: "Alt Ctrl T" }, category: "Text" },
  { title: "Text align right", keys: { macOS: "⌥ ⌘ R", Windows: "Alt Ctrl R", Linux: "Alt Ctrl R" }, category: "Text" },
  { title: "Text align justified", keys: { macOS: "⌥ ⌘ J", Windows: "Alt Ctrl J", Linux: "Alt Ctrl J" }, category: "Text" },
  { title: "Increase indentation", keys: { macOS: "⌘ ]", Windows: "Ctrl ]", Linux: "Ctrl ]" }, category: "Text" },
  { title: "Decrease indentation", keys: { macOS: "⌘ [", Windows: "Ctrl [", Linux: "Ctrl [" }, category: "Text" },
  { title: "Increase font size", keys: { macOS: "⇧ ⌘ > or ⇧ ⌘ .", Windows: "⇧ Ctrl > or ⇧ Ctrl .", Linux: "⇧ Ctrl > or ⇧ Ctrl ." }, category: "Text" },
  { title: "Decrease font size", keys: { macOS: "⇧ ⌘ < or ⇧ ⌘ ,", Windows: "⇧ Ctrl <", Linux: "⇧ Ctrl <" }, category: "Text" },
  { title: "Increase font weight", keys: { macOS: "⌥ ⌘ > or ⌥ ⌘ .", Windows: "Alt Ctrl > or Alt Ctrl .", Linux: "Alt Ctrl > or Alt Ctrl ." }, category: "Text" },
  { title: "Decrease font weight", keys: { macOS: "⌥ ⌘ < or ⌥ ⌘ ,", Windows: "Alt Ctrl < or Alt Ctrl ,", Linux: "Alt Ctrl < or Alt Ctrl ," }, category: "Text" },
  { title: "Increase line height", keys: { macOS: "⌥ ⇧ >", Windows: "Alt ⇧ >", Linux: "Alt ⇧ >" }, category: "Text" },
  { title: "Decrease line height", keys: { macOS: "⌥ ⇧ <", Windows: "Alt ⇧ <", Linux: "Alt ⇧ <" }, category: "Text" },
  { title: "Increase letter spacing", keys: { macOS: "⌥ > or ⌥ .", Windows: "Alt > or Alt .", Linux: "Alt > or Alt ." }, category: "Text" },
  { title: "Decrease letter spacing", keys: { macOS: "⌥ < or ⌥ ,", Windows: "Alt < or Alt ,", Linux: "Alt < or Alt ," }, category: "Text" },

  // Shape
  { title: "Paint bucket", keys: { macOS: "B", Windows: "B", Linux: "B" }, category: "Shape" },
  { title: "Bend tool", keys: { macOS: "⌘", Windows: "Ctrl", Linux: "Ctrl" }, category: "Shape" },
  { title: "Remove fill", keys: { macOS: "⌥ /", Windows: "Alt /", Linux: "Alt /" }, category: "Shape" },
  { title: "Remove stroke", keys: { macOS: "⇧ / or ⇧ '", Windows: "⇧ / or ⇧ '", Linux: "⇧ / or ⇧ '" }, category: "Shape" },
  { title: "Swap fill and stroke", keys: { macOS: "⇧ X", Windows: "⇧ X", Linux: "⇧ X" }, category: "Shape" },
  { title: "Join selection", keys: { macOS: "⌘ J", Windows: "Ctrl J", Linux: "Ctrl J" }, category: "Shape" },
  { title: "Smooth join selection", keys: { macOS: "⇧ ⌘ J", Windows: "⇧ Ctrl J", Linux: "⇧ Ctrl J" }, category: "Shape" },
  { title: "Delete and heal selection", keys: { macOS: "⇧ Delete", Windows: "⇧ Delete", Linux: "⇧ Delete" }, category: "Shape" },
  { title: "Flatten selection", keys: { macOS: "⌘ E", Windows: "Ctrl E", Linux: "Ctrl E" }, category: "Shape" },

  // Selection
  { title: "Deep select", keys: { macOS: "⌘ Click", Windows: "Ctrl Click", Linux: "Ctrl Click" }, category: "Selection" },
  { title: "Deep select with rectangle", keys: { macOS: "⌘ Drag", Windows: "Ctrl Drag", Linux: "Ctrl Drag" }, category: "Selection" },
  { title: "Select layer menu", keys: { macOS: "⌘ Right click", Windows: "Ctrl Right click", Linux: "Ctrl Right click" }, category: "Selection" },
  { title: "Select all", keys: { macOS: "⌘ A", Windows: "Ctrl A", Linux: "Ctrl A" }, category: "Selection" },
  { title: "Select inverse", keys: { macOS: "⇧ ⌘ A", Windows: "⇧ Ctrl A", Linux: "⇧ Ctrl A" }, category: "Selection" },
  { title: "Select none", keys: { macOS: "Esc", Windows: "Esc", Linux: "Esc" }, category: "Selection" },
  { title: "Select children", keys: { macOS: "Enter", Windows: "Enter", Linux: "Enter" }, category: "Selection" },
  { title: "Select parent", keys: { macOS: "\\ or ⇧ Enter", Windows: "\\ or ⇧ Enter", Linux: "\\ or ⇧ Enter" }, category: "Selection" },
  { title: "Select next sibling", keys: { macOS: "Tab", Windows: "Tab", Linux: "Tab" }, category: "Selection" },
  { title: "Select previous sibling", keys: { macOS: "⇧ Tab", Windows: "⇧ Tab", Linux: "⇧ Tab" }, category: "Selection" },
  { title: "Select all matching layers", keys: { macOS: "⌥ ⌘ A", Windows: "Alt Ctrl A", Linux: "Alt Ctrl A" }, category: "Selection" },
  { title: "Group selection", keys: { macOS: "⌘ G", Windows: "Ctrl G", Linux: "Ctrl G" }, category: "Selection" },
  { title: "Ungroup selection", keys: { macOS: "⇧ ⌘ G", Windows: "⇧ Ctrl G", Linux: "⇧ Ctrl G" }, category: "Selection" },
  { title: "Frame selection", keys: { macOS: "⌥ ⌘ G", Windows: "Alt Ctrl G", Linux: "Alt Ctrl G" }, category: "Selection" },
  { title: "Show/Hide selection", keys: { macOS: "⇧ ⌘ H", Windows: "⇧ Ctrl H", Linux: "⇧ Ctrl H" }, category: "Selection" },
  { title: "Lock/Unlock selection", keys: { macOS: "⇧ ⌘ L", Windows: "⇧ Ctrl L", Linux: "⇧ Ctrl L" }, category: "Selection" },

  // Cursor
  { title: "Measure to selection", keys: { macOS: "⌥ (hold)", Windows: "Alt (hold)", Linux: "Alt (hold)" }, category: "Cursor" },
  { title: "Duplicate selection", keys: { macOS: "⌥ (while moving)", Windows: "Alt (while moving)", Linux: "Alt (while moving)" }, category: "Cursor" },
  { title: "Resize from center", keys: { macOS: "⌥ (while resizing)", Windows: "Alt (while resizing)", Linux: "Alt (while resizing)" }, category: "Cursor" },
  { title: "Resize proportionally", keys: { macOS: "⇧ (while resizing)", Windows: "⇧ (while resizing)", Linux: "⇧ (while resizing)" }, category: "Cursor" },
  { title: "Crop image", keys: { macOS: "⌘ (while resizing)", Windows: "Ctrl (while resizing)", Linux: "Ctrl (while resizing)" }, category: "Cursor" },
  { title: "Ignore constraints/frames", keys: { macOS: "⌘ (while resizing)", Windows: "Ctrl (while resizing)", Linux: "Ctrl (while resizing)" }, category: "Cursor" },
  { title: "Move while resizing", keys: { macOS: "Space (while dragging)", Windows: "Space (while dragging)", Linux: "Space (while dragging)" }, category: "Cursor" },

  // Edit
  { title: "Copy", keys: { macOS: "⌘ C", Windows: "Ctrl C", Linux: "Ctrl C" }, category: "Edit" },
  { title: "Cut", keys: { macOS: "⌘ X", Windows: "Ctrl X", Linux: "Ctrl X" }, category: "Edit" },
  { title: "Paste", keys: { macOS: "⌘ V", Windows: "Ctrl V", Linux: "Ctrl V" }, category: "Edit" },
  { title: "Paste to replace", keys: { macOS: "⇧ ⌘ R", Windows: "⇧ Ctrl R", Linux: "⇧ Ctrl R" }, category: "Edit" },
  { title: "Paste over selection", keys: { macOS: "⇧ ⌘ V", Windows: "⇧ Ctrl V", Linux: "⇧ Ctrl V" }, category: "Edit" },
  { title: "Duplicate", keys: { macOS: "⌘ D", Windows: "Ctrl D", Linux: "Ctrl D" }, category: "Edit" },
  { title: "Rename", keys: { macOS: "⌘ R", Windows: "Ctrl R", Linux: "Ctrl R" }, category: "Edit" },
  { title: "Export", keys: { macOS: "⇧ ⌘ E", Windows: "⇧ Ctrl E", Linux: "⇧ Ctrl E" }, category: "Edit" },
  { title: "Copy as PNG", keys: { macOS: "⇧ ⌘ C", Windows: "⇧ Ctrl C", Linux: "⇧ Ctrl C" }, category: "Edit" },
  { title: "Copy properties", keys: { macOS: "⌥ ⌘ C", Windows: "Alt Ctrl C", Linux: "Alt Ctrl C" }, category: "Edit" },
  { title: "Paste properties", keys: { macOS: "⌥ ⌘ V", Windows: "Alt Ctrl V", Linux: "Alt Ctrl V" }, category: "Edit" },

  // Transform
  { title: "Flip horizontal", keys: { macOS: "⇧ H", Windows: "⇧ H", Linux: "⇧ H" }, category: "Transform" },
  { title: "Flip vertical", keys: { macOS: "⇧ V", Windows: "⇧ V", Linux: "⇧ V" }, category: "Transform" },
  { title: "Use as mask", keys: { macOS: "⌃ ⌘ M", Windows: "⌃ Ctrl M", Linux: "⌃ Ctrl M" }, category: "Transform" },
  { title: "Edit shape or image", keys: { macOS: "Enter", Windows: "Enter", Linux: "Enter" }, category: "Transform" },
  { title: "Resize the frame to fit", keys: { macOS: "⌥ ⇧ ⌘ R", Windows: "Alt ⇧ Ctrl R", Linux: "Alt ⇧ Ctrl R" }, category: "Transform" },
  { title: "Set opacity to 0%", keys: { macOS: "0", Windows: "0", Linux: "0" }, category: "Transform" },
  { title: "Set opacity to 10%", keys: { macOS: "1", Windows: "1", Linux: "1" }, category: "Transform" },
  { title: "Set opacity to 20%", keys: { macOS: "2", Windows: "2", Linux: "2" }, category: "Transform" },
  { title: "Set opacity to 30%", keys: { macOS: "3", Windows: "3", Linux: "3" }, category: "Transform" },
  { title: "Set opacity to 40%", keys: { macOS: "4", Windows: "4", Linux: "4" }, category: "Transform" },
  { title: "Set opacity to 50%", keys: { macOS: "5", Windows: "5", Linux: "5" }, category: "Transform" },
  { title: "Set opacity to 60%", keys: { macOS: "6", Windows: "6", Linux: "6" }, category: "Transform" },
  { title: "Set opacity to 70%", keys: { macOS: "7", Windows: "7", Linux: "7" }, category: "Transform" },
  { title: "Set opacity to 80%", keys: { macOS: "8", Windows: "8", Linux: "8" }, category: "Transform" },
  { title: "Set opacity to 90%", keys: { macOS: "9", Windows: "9", Linux: "9" }, category: "Transform" },
  { title: "Set opacity to 100%", keys: { macOS: "0 0", Windows: "0 0", Linux: "0 0" }, category: "Transform" },

  // Arrange
  { title: "Align left", keys: { macOS: "⌥ A", Windows: "Alt A", Linux: "Alt A" }, category: "Arrange" },
  { title: "Align horizontal centers", keys: { macOS: "⌥ H", Windows: "Alt H", Linux: "Alt H" }, category: "Arrange" },
  { title: "Align right", keys: { macOS: "⌥ D", Windows: "Alt D", Linux: "Alt D" }, category: "Arrange" },
  { title: "Align top", keys: { macOS: "⌥ W", Windows: "Alt W", Linux: "Alt W" }, category: "Arrange" },
  { title: "Align vertical centers", keys: { macOS: "⌥ V", Windows: "Alt V", Linux: "Alt V" }, category: "Arrange" },
  { title: "Align bottom", keys: { macOS: "⌥ S", Windows: "Alt S", Linux: "Alt S" }, category: "Arrange" },
  { title: "Tidy up", keys: { macOS: "⌃ ⌥ T", Windows: "Ctrl Alt T", Linux: "Ctrl Alt T" }, category: "Arrange" },
  { title: "Distribute horizontal spacing", keys: { macOS: "⌃ ⌥ H", Windows: "Ctrl Alt H", Linux: "Ctrl Alt H" }, category: "Arrange" },
  { title: "Distribute vertical spacing", keys: { macOS: "⌃ ⌥ V", Windows: "Ctrl Alt V", Linux: "Ctrl Alt V" }, category: "Arrange" },
  { title: "Bring to front", keys: { macOS: "⌥ ⌘ ]", Windows: "Ctrl ⇧ ]", Linux: "Ctrl ⇧ ]" }, category: "Arrange" },
  { title: "Bring forward", keys: { macOS: "⌘ ]", Windows: "Ctrl ]", Linux: "Ctrl ]" }, category: "Arrange" },
  { title: "Send backward", keys: { macOS: "⌘ [", Windows: "Ctrl [", Linux: "Ctrl [" }, category: "Arrange" },
  { title: "Send to back", keys: { macOS: "⌥ ⌘ [", Windows: "Ctrl ⇧ [", Linux: "Ctrl ⇧ [" }, category: "Arrange" },

  // Components
  { title: "Show assets", keys: { macOS: "⌥ 2", Windows: "Alt 2", Linux: "Alt 2" }, category: "Components" },
  { title: "Libraries", keys: { macOS: "⌥ ⌘ O", Windows: "Alt Ctrl O", Linux: "Alt Ctrl O" }, category: "Components" },
  { title: "Create component", keys: { macOS: "⌥ ⌘ K", Windows: "Alt Ctrl K", Linux: "Alt Ctrl K" }, category: "Components" },
  { title: "Detach instance", keys: { macOS: "⌥ ⌘ B", Windows: "Alt Ctrl B", Linux: "Alt Ctrl B" }, category: "Components" },
  { title: "Swap component instance", keys: { macOS: "⌥ (while inserting)", Windows: "Alt (while inserting)", Linux: "Alt (while inserting)" }, category: "Components" },
  { title: "Go to main component", keys: { macOS: "⌃ ⌥ ⌘ K", Windows: "⇧ Alt Ctrl K", Linux: "⇧ Alt Ctrl K" }, category: "Components" },

  // Auto Layout
  { title: "Add auto layout", keys: { macOS: "⇧ A", Windows: "⇧ A", Linux: "⇧ A" }, category: "Auto Layout" },
  { title: "Remove auto layout", keys: { macOS: "⌥ ⇧ A", Windows: "Alt ⇧ A", Linux: "Alt ⇧ A" }, category: "Auto Layout" },
  { title: "Suggest auto layout", keys: { macOS: "⌃ ⇧ A", Windows: "Ctrl Alt ⇧ A", Linux: "Ctrl Alt ⇧ A" }, category: "Auto Layout" },
  { title: "Drag padding/spacing with big nudge", keys: { macOS: "⇧ Drag", Windows: "⇧ Drag", Linux: "⇧ Drag" }, category: "Auto Layout" },
  { title: "Drag padding from both sides", keys: { macOS: "⌥ Drag", Windows: "Alt Drag", Linux: "Alt Drag" }, category: "Auto Layout" },
  { title: "Drag padding from all sides", keys: { macOS: "⌥ ⇧ Drag", Windows: "Alt ⇧ Drag", Linux: "Alt ⇧ Drag" }, category: "Auto Layout" },
  { title: "Edit both padding sides", keys: { macOS: "⌥ Click", Windows: "Alt Click", Linux: "Alt Click" }, category: "Auto Layout" },
  { title: "Edit all padding sides", keys: { macOS: "⌥ ⇧ Click", Windows: "Alt ⇧ Click", Linux: "Alt ⇧ Click" }, category: "Auto Layout" },
  { title: "Single padding field", keys: { macOS: "⌘ (click padding field)", Windows: "Ctrl (click padding field)", Linux: "Ctrl (click padding field)" }, category: "Auto Layout" },
  { title: "Set hug contents", keys: { macOS: "Double click edge", Windows: "Double click edge", Linux: "Double click edge" }, category: "Auto Layout" },
  { title: "Set fill container", keys: { macOS: "⌥ Double click edge", Windows: "Alt Double click edge", Linux: "Alt Double click edge" }, category: "Auto Layout" },
  { title: "Set alignment stepwise", keys: { macOS: "↓ → ↑ ←", Windows: "↓ → ↑ ←", Linux: "↓ → ↑ ←" }, category: "Auto Layout" },
  { title: "Set alignment to edge", keys: { macOS: "W A S D", Windows: "W A S D", Linux: "W A S D" }, category: "Auto Layout" },
  { title: "Set alignment to center", keys: { macOS: "V H", Windows: "V H", Linux: "V H" }, category: "Auto Layout" },
  { title: "Toggle text baseline alignment", keys: { macOS: "B", Windows: "B", Linux: "B" }, category: "Auto Layout" },
  { title: "Toggle space between/packed", keys: { macOS: "X or Double click widget", Windows: "X or Double click widget", Linux: "X or Double click widget" }, category: "Auto Layout" },
  { title: "Open menu to toggle Width/Height", keys: { macOS: "⌘ ↓", Windows: "Ctrl ↓", Linux: "Ctrl ↓" }, category: "Auto Layout" },
];
