sonar.projectKey=thaw-app_raycast-extension
sonar.organization=thaw-app

sonar.projectName=raycast-extension
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**, **/assets/**, **/metadata/**, **/dist/**, **/build/**, **/coverage/**, **/*.json, **/*.md
sonar.coverage.exclusions=**/*.tsx,**/test/**
sonar.cpd.exclusions=eslint.config.js, .prettierrc

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.node.maxspace=4096
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
