export const colorValues = {
  gray: {
    bgLight: "#FAF8F5",
    textLight: "#44403B",
    borderLight: "#E7E2D7",
    bgDark: "#282E36",
    textDark: "#FFFFFF",
    borderDark: "#313844",
  },
  rose: {
    bgLight: "#FFEAEC",
    textLight: "#881337",
    borderLight: "#FDA4AF",
    bgDark: "#4B2D38",
    textDark: "#FFFFFF",
    borderDark: "#FB7185",
  },
  pink: {
    bgLight: "#FDEDF7",
    textLight: "#831743",
    borderLight: "#F9A9D4",
    bgDark: "#4A2E43",
    textDark: "#FFFFFF",
    borderDark: "#F471B5",
  },
  fuchsia: {
    bgLight: "#FBEEFF",
    textLight: "#701975",
    borderLight: "#F0ABFD",
    bgDark: "#462D54",
    textDark: "#FFFFFF",
    borderDark: "#E979FA",
  },
  purple: {
    bgLight: "#F7EEFF",
    textLight: "#581C87",
    borderLight: "#D8B4FE",
    bgDark: "#3B3057",
    textDark: "#FFFFFF",
    borderDark: "#C084FC",
  },
  violet: {
    bgLight: "#F1EFFE",
    textLight: "#4C1D95",
    borderLight: "#C3B6FE",
    bgDark: "#353157",
    textDark: "#FFFFFF",
    borderDark: "#A88BFB",
  },
  indigo: {
    bgLight: "#E8EDFF",
    textLight: "#302E82",
    borderLight: "#A5B4FD",
    bgDark: "#2D3255",
    textDark: "#FFFFFF",
    borderDark: "#818CF9",
  },
  blue: {
    bgLight: "#E4EFFE",
    textLight: "#1F3A8A",
    borderLight: "#92C5FE",
    bgDark: "#263956",
    textDark: "#FFFFFF",
    borderDark: "#60A5FB",
  },
  sky: {
    bgLight: "#E7F5FE",
    textLight: "#0C4A6E",
    borderLight: "#7DD3FC",
    bgDark: "#224053",
    textDark: "#FFFFFF",
    borderDark: "#38BDF9",
  },
  cyan: {
    bgLight: "#DBFBFE",
    textLight: "#164E63",
    borderLight: "#67E8FA",
    bgDark: "#22434F",
    textDark: "#FFFFFF",
    borderDark: "#24D3EE",
  },
  teal: {
    bgLight: "#D9FCF6",
    textLight: "#124E4B",
    borderLight: "#5EEAD5",
    bgDark: "#244346",
    textDark: "#FFFFFF",
    borderDark: "#2DD4BF",
  },
  emerald: {
    bgLight: "#DDFBEB",
    textLight: "#064E3B",
    borderLight: "#6EE7B8",
    bgDark: "#24433F",
    textDark: "#FFFFFF",
    borderDark: "#34D399",
  },
  green: {
    bgLight: "#E4FDED",
    textLight: "#14532F",
    borderLight: "#87EFAD",
    bgDark: "#254638",
    textDark: "#FFFFFF",
    borderDark: "#49DE80",
  },
  lime: {
    bgLight: "#F1FCD9",
    textLight: "#365315",
    borderLight: "#BFF164",
    bgDark: "#34472F",
    textDark: "#FFFFFF",
    borderDark: "#A3E634",
  },
  yellow: {
    bgLight: "#FFFBD2",
    textLight: "#713F13",
    borderLight: "#FDE047",
    bgDark: "#48422E",
    textDark: "#FFFFFF",
    borderDark: "#FACC14",
  },
  amber: {
    bgLight: "#FFF6D6",
    textLight: "#78350F",
    borderLight: "#FBD34C",
    bgDark: "#4B3D2E",
    textDark: "#FFFFFF",
    borderDark: "#FBBF24",
  },
  orange: {
    bgLight: "#FFF2E0",
    textLight: "#7C2D14",
    borderLight: "#FDBA75",
    bgDark: "#4B362E",
    textDark: "#FFFFFF",
    borderDark: "#FB923C",
  },
  red: {
    bgLight: "#FFE9EA",
    textLight: "#7F1C1E",
    borderLight: "#FDA5A5",
    bgDark: "#4A2D33",
    textDark: "#FFFFFF",
    borderDark: "#F87171",
  },
};

export type ColorKey = keyof typeof colorValues;
