// iOS Human Interface Guidelines Font Sizes by Dynamic Type sizes from https://developer.apple.com/design/human-interface-guidelines/foundations/typography/
export default {
  ExtraLarge: [
    {
      name: "Large Title",
      size: 36,
      weight: "Regular",
      leading: 43,
    },
    {
      name: "Title 1",
      size: 30,
      weight: "Regular",
      leading: 37,
    },
    {
      name: "Title 2",
      size: 24,
      weight: "Regular",
      leading: 30,
    },
    {
      name: "Title 3",
      size: 22,
      weight: "Regular",
      leading: 28,
    },
    {
      name: "Headline",
      size: 19,
      weight: "Semibold",
      leading: 24,
    },
    {
      name: "Body",
      size: 19,
      weight: "Regular",
      leading: 24,
    },
    {
      name: "Callout",
      size: 18,
      weight: "Regular",
      leading: 23,
    },
    {
      name: "Subhead",
      size: 17,
      weight: "Regular",
      leading: 22,
    },
    {
      name: "Footnote",
      size: 15,
      weight: "Regular",
      leading: 20,
    },
    {
      name: "Caption 1",
      size: 14,
      weight: "Regular",
      leading: 19,
    },
    {
      name: "Caption 2",
      size: 13,
      weight: "Regular",
      leading: 18,
    },
  ],
  Large: [
    {
      name: "Large Title",
      weight: "Regular",
      size: 34,
      leading: 41,
    },
    {
      name: "Title 1",
      weight: "Regular",
      size: 28,
      leading: 34,
    },
    {
      name: "Title 2",
      weight: "Regular",
      size: 22,
      leading: 28,
    },
    {
      name: "Title 3",
      weight: "Regular",
      size: 20,
      leading: 25,
    },
    {
      name: "Headline",
      weight: "Semibold",
      size: 17,
      leading: 22,
    },
    {
      name: "Body",
      weight: "Regular",
      size: 17,
      leading: 22,
    },
    {
      name: "Callout",
      weight: "Regular",
      size: 16,
      leading: 21,
    },
    {
      name: "Subhead",
      weight: "Regular",
      size: 15,
      leading: 20,
    },
    {
      name: "Footnote",
      weight: "Regular",
      size: 13,
      leading: 18,
    },
    {
      name: "Caption 1",
      weight: "Regular",
      size: 12,
      leading: 16,
    },
    {
      name: "Caption 2",
      weight: "Regular",
      size: 11,
      leading: 13,
    },
  ],
  Medium: [
    {
      name: "Large Title",
      weight: "Regular",
      size: 30,
      leading: 36,
    },
    {
      name: "Title 1",
      weight: "Regular",
      size: 24,
      leading: 30,
    },
    {
      name: "Title 2",
      weight: "Regular",
      size: 20,
      leading: 24,
    },
    {
      name: "Title 3",
      weight: "Regular",
      size: 17,
      leading: 22,
    },
    {
      name: "Headline",
      weight: "Semibold",
      size: 15,
      leading: 20,
    },
    {
      name: "Body",
      weight: "Regular",
      size: 15,
      leading: 20,
    },
    {
      name: "Callout",
      weight: "Regular",
      size: 14,
      leading: 18,
    },
    {
      name: "Subhead",
      weight: "Regular",
      size: 13,
      leading: 18,
    },
    {
      name: "Footnote",
      weight: "Regular",
      size: 12,
      leading: 16,
    },
    {
      name: "Caption 1",
      weight: "Regular",
      size: 11,
      leading: 14,
    },
    {
      name: "Caption 2",
      weight: "Regular",
      size: 10,
      leading: 12,
    },
  ],
  Small: [
    {
      name: "Large Title",
      weight: "Regular",
      size: 26,
      leading: 32,
    },
    {
      name: "Title 1",
      weight: "Regular",
      size: 21,
      leading: 26,
    },
    {
      name: "Title 2",
      weight: "Regular",
      size: 17,
      leading: 22,
    },
    {
      name: "Title 3",
      weight: "Regular",
      size: 15,
      leading: 20,
    },
    {
      name: "Headline",
      weight: "Semibold",
      size: 13,
      leading: 18,
    },
    {
      name: "Body",
      weight: "Regular",
      size: 13,
      leading: 18,
    },
    {
      name: "Callout",
      weight: "Regular",
      size: 12,
      leading: 16,
    },
    {
      name: "Subhead",
      weight: "Regular",
      size: 11,
      leading: 16,
    },
    {
      name: "Footnote",
      weight: "Regular",
      size: 11,
      leading: 14,
    },
    {
      name: "Caption 1",
      weight: "Regular",
      size: 10,
      leading: 12,
    },
    {
      name: "Caption 2",
      weight: "Regular",
      size: 9,
      leading: 11,
    },
  ],
  ExtraSmall: [
    {
      name: "Large Title",
      weight: "Regular",
      size: 22,
      leading: 28,
    },
    {
      name: "Title 1",
      weight: "Regular",
      size: 18,
      leading: 22,
    },
    {
      name: "Title 2",
      weight: "Regular",
      size: 15,
      leading: 20,
    },
    {
      name: "Title 3",
      weight: "Regular",
      size: 13,
      leading: 18,
    },
    {
      name: "Headline",
      weight: "Semibold",
      size: 11,
      leading: 14,
    },
    {
      name: "Body",
      weight: "Regular",
      size: 11,
      leading: 14,
    },
    {
      name: "Callout",
      weight: "Regular",
      size: 11,
      leading: 14,
    },
    {
      name: "Subhead",
      weight: "Regular",
      size: 10,
      leading: 12,
    },
    {
      name: "Footnote",
      weight: "Regular",
      size: 10,
      leading: 12,
    },
    {
      name: "Caption 1",
      weight: "Regular",
      size: 9,
      leading: 11,
    },
    {
      name: "Caption 2",
      weight: "Regular",
      size: 9,
      leading: 11,
    },
  ],
};
