import { showToast, Toast, open, getPreferenceValues } from "@raycast/api";
import { generateMermaidDiagram } from "../utils/diagram";
import { cleanupTempFile } from "../utils/files";
import { Preferences } from "../types";
import { logOperationalError, logOperationalEvent } from "../utils/logger";
import { showActionFailureToast } from "../utils/notifications";
import { copyDiagramImage } from "../utils/preview-actions";
import { resolveSvgCopyAsset } from "../utils/preview-assets";
import { renderSvgPreviewRasterWithStrategy } from "../utils/svg-preview-raster";
import { copyRasterImageToClipboard } from "../utils/macos-image-tools";
import { generateAiDiagramArtifact } from "./ai-diagram-service";
/**
 * Define the input parameters required by the AI tool
 */
type MermaidToolInput = {
  /**
   * A complete and valid Mermaid syntax string that needs to be converted into an image.
   * This is usually generated by the AI at user request, or provided directly by the user.
   * For example: 'graph TD\\nA --> B' or 'sequenceDiagram\\nAlice->>Bob: Hi!'
   */
  mermaidSyntax: string;
};
/**
 * @raycast AI Tool
 * @name generateMermaidImageTool
 * @description Generates a Mermaid diagram and opens in Preview
 * @param {object} input - Tool input
 * @param {string} input.mermaidSyntax - Mermaid syntax
 * @returns {Promise<string>} - Success message with preview link
 */
export default async function generateMermaidImageTool(input?: MermaidToolInput): Promise<string> {
  const mermaidSyntax = input?.mermaidSyntax;

  if (!mermaidSyntax?.trim()) {
    throw new Error("Mermaid syntax was not provided or is empty.");
  }

  const tempFileRef = { current: null as string | null };

  try {
    const toast = await showToast({
      style: Toast.Style.Animated,
      title: "Generating diagram...",
    });

    // Generate high-quality image
    const preferences = getPreferenceValues<Preferences>();
    const rawScale = preferences.scale;
    const parsedScale = typeof rawScale === "number" ? rawScale : Number(rawScale);
    const finalScale = Number.isFinite(parsedScale) && parsedScale > 0 ? parsedScale : 4;

    const result = await generateAiDiagramArtifact(
      {
        mermaidSyntax,
        tempFileRef,
        scale: finalScale,
        width: 2400,
      },
      {
        generateDiagram: generateMermaidDiagram,
        copyGeneratedImage: async ({ format, imagePath, svgRasterStrategy }) =>
          copyDiagramImage({
            format,
            imagePath,
            previewRasterPath: null,
            copyRasterImage: copyRasterImageToClipboard,
            resolveSvgCopy: ({ svgPath, previewRasterPath }) =>
              resolveSvgCopyAsset({
                svgPath,
                previewRasterPath,
                baseName: `mermaid-ai-svg-copy-${Date.now()}`,
                renderSvgPreview: ({ materializedSvgContent, baseName }) =>
                  renderSvgPreviewRasterWithStrategy({
                    strategy: svgRasterStrategy ?? "macos",
                    materializedSvgContent,
                    baseName,
                  }),
              }),
            cleanupTempPath: cleanupTempFile,
          }),
        openInPreview: async (imagePath) => open(imagePath, "com.apple.Preview"),
      },
    );

    logOperationalEvent("ai-diagram-generated", {
      renderer: result.engine,
      format: result.format,
    });

    toast.style = Toast.Style.Success;
    toast.title = "Diagram ready!";

    return result.message;
  } catch (error) {
    logOperationalError("ai-diagram-generation-failed", error, {
      renderer: "auto",
      format: "hybrid",
    });
    const errorMessage = error instanceof Error ? error.message : String(error);

    await showActionFailureToast(error, "Failed to generate diagram", errorMessage);

    throw new Error(`Diagram generation failed: ${errorMessage}`);
  } finally {
    if (tempFileRef.current) {
      cleanupTempFile(tempFileRef.current);
    }
  }
}
