export const STRINGS = {
  searchBooksPlaceholder: "Search books",
  searchPeoplePlaceholder: "Search people",
  showDetails: "Show details",
  copyUrl: "Copy URL",
  copyTitle: "Copy title",
  authorLabel: "Author",
  formatLabel: "Format",
  publishedLabel: "Published",
  communityReviews: "Community reviews",
  languageLabel: "Language",
  toggleMetadata: "Toggle metadata",
  genresLabel: "Genres",
  somethingWentWrong: "Something went wrong",
  tryAgain: "Please try again",
  retry: "Retry",
  born: "Born",
  website: "Website",
  twitter: "Twitter",
  rating: "Rating",
  searchResults: "Search Results",
  recentBooks: "Recent Books",
  removeFromRecent: "Remove from Recent",
  clearAllRecent: "Clear all Recent Views",
};
