#!/bin/sh

PWD=$(osascript -e 'display dialog "To deal with encrypted volumes, the extension requires elevated \"sudo\" permissions in order to access the system keychain.\n\nEnter login password:" default answer "" with hidden answer with icon file "System:Library:Frameworks:SecurityInterface.framework:Versions:A:Resources:Lock_Locked State@2x.png" with title "Raycast Disk Utility Extension"' | cut -d: -f3)

BUNDLE_IDENTIFIER=$RAYCAST_BUNDLE
if [ ! -z $BUNDLE_IDENTIFIER ] ; then
    open -b $BUNDLE_IDENTIFIER
fi

echo $PWD
