// Common ways people ask for an emoji beyond its official name, GitHub
// shortcode, and emojilib keywords. Keep these specific: a broad alias
// can otherwise make an unrelated emoji rank above a more literal result.
export const EXTRA_ALIASES: Record<string, string[]> = {
  // Faces and reactions
  "😀": ["big smile", "happy face"],
  "😄": ["happy", "smiling", "grinning"],
  "😂": ["laughing crying", "crying laughing", "laughing so hard", "lol", "hilarious"],
  "🤣": ["rofl", "rolling laughing", "dying laughing", "lmao"],
  "🥲": ["happy tears", "bittersweet", "smiling through tears"],
  "😭": ["ugly crying", "bawling", "sobbing", "crying hard"],
  "🥹": ["happy cry", "emotional", "moved", "touched", "teary eyed"],
  "🥺": ["puppy eyes", "pleading", "begging", "pretty please"],
  "😅": ["nervous laugh", "awkward laugh", "close call", "phew"],
  "😬": ["awkward", "yikes", "cringe", "nervous grin"],
  "🙃": ["sarcasm", "sarcastic", "passive aggressive", "upside down smile"],
  "😏": ["smug", "flirty", "smirk"],
  "😌": ["at peace", "content", "relieved"],
  "🫠": ["melting", "melt", "overwhelmed", "awkward smile"],
  "😵‍💫": ["dizzy", "confused", "disoriented", "spinning"],
  "🤯": ["mind blown", "blown away", "mind blowing"],
  "😱": ["terrified", "horror", "screaming", "scared"],
  "😨": ["frightened", "worried", "fear"],
  "😰": ["stressed", "anxious", "panicking", "nervous sweat"],
  "😴": ["sleep", "asleep", "bedtime", "go to sleep"],
  "🥱": ["bored", "yawn", "sleepy"],
  "😤": ["frustrated", "fed up", "huffing"],
  "😠": ["angry", "mad", "annoyed"],
  "🤬": ["furious", "swearing", "cursing", "rage"],
  "🤢": ["gross", "disgusted", "nauseous"],
  "🤮": ["puke", "vomit", "throw up"],
  "🤧": ["sneeze", "allergies", "sniffle"],
  "🤒": ["fever", "ill", "unwell"],
  "🤕": ["hurt", "injured", "head injury"],
  "😷": ["mask", "face mask", "sick"],
  "🤔": ["hmm", "pondering", "thinking", "curious"],
  "🤨": ["skeptical", "suspicious", "doubtful", "raised eyebrow"],
  "🧐": ["inspect", "scrutinize", "investigate"],
  "😎": ["cool", "chill", "sunglasses"],
  "🥳": ["party face", "birthday party", "celebrating"],
  "🤩": ["star struck", "impressed", "amazed"],
  "😍": ["in love", "adore", "heart eyes"],
  "😘": ["blowing kiss", "xoxo", "sending kisses"],
  "😇": ["innocent", "blessed", "angelic"],
  "😈": ["mischievous", "naughty", "devilish"],
  "👻": ["spooky", "ghosting", "halloween"],
  "💀": ["i am dead", "dead laughing", "dark humor"],
  "🤡": ["fool", "foolish", "clowning"],
  "👀": ["watching", "lurking", "eyes on", "looking"],

  // Gestures and people
  "🙏": ["thank you", "thanks", "grateful", "praying", "please"],
  "👏": ["good job", "well done", "congratulations", "applause", "bravo"],
  "🙌": ["hooray", "hands up", "yay", "praise"],
  "🫶": ["heart hands", "love you", "appreciation"],
  "🤝": ["deal", "agreement", "agreed", "shake on it"],
  "🤞": ["good luck", "fingers crossed", "hope it works"],
  "👍": ["good job", "well done", "yes", "agree", "approved", "sounds good", "okay"],
  "👎": ["no", "disagree", "rejected", "bad"],
  "🫡": ["roger that", "understood", "acknowledged", "will do", "respect"],
  "👋": ["hello", "hi", "goodbye", "bye", "wave"],
  "🤦": ["facepalm", "oh no", "disappointed"],
  "🤷": ["idk", "i don't know", "whatever", "shrug"],
  "🙅": ["no way", "not allowed"],
  "🙆": ["all good", "okay", "ok"],
  "💪": ["strength", "strong", "workout", "you got this"],
  "👊": ["fist bump", "pound it"],
  "🤙": ["call me", "hang loose", "shaka"],
  "👌": ["perfect", "okay", "ok", "spot on"],
  "🤌": ["chef's kiss", "chefs kiss", "delicious", "italian hand"],

  // Affection, celebrations, and signals
  "❤️": ["love", "affection", "i love you"],
  "💔": ["heartbreak", "breakup", "broken heart"],
  "💯": ["hundred percent", "exactly", "nailed it", "perfect score"],
  "🔥": ["lit", "awesome", "on fire", "trending"],
  "✨": ["sparkle", "sparkles", "shiny", "special"],
  "🎉": ["congrats", "congratulations", "celebrate", "woohoo", "party"],
  "🎊": ["confetti", "party", "celebration"],
  "🎂": ["happy birthday", "birthday cake", "bday"],
  "🎁": ["gift", "present", "surprise"],
  "🏆": ["winner", "victory", "champion", "first place"],
  "🥇": ["gold medal", "first place", "winner"],
  "✅": ["done", "complete", "approved", "check", "yes"],
  "❌": ["wrong", "cancel", "rejected", "no"],
  "⚠️": ["caution", "heads up", "alert", "warning"],
  "🚨": ["urgent", "emergency", "siren", "red alert"],
  "❗": ["important", "attention", "exclamation"],

  // Work, communication, and everyday objects
  "💡": ["idea", "aha moment", "inspiration", "lightbulb"],
  "📌": ["pin", "pinned", "remember"],
  "📍": ["location", "map pin", "you are here"],
  "🔗": ["link", "url", "hyperlink"],
  "📝": ["notes", "write", "draft", "jot down"],
  "📋": ["clipboard", "checklist", "copy"],
  "📚": ["books", "studying", "reading"],
  "📖": ["read", "open book", "reading"],
  "🔍": ["search", "find", "look up", "investigate"],
  "📅": ["meeting", "appointment", "deadline", "schedule", "date"],
  "🗓️": ["meeting", "appointment", "deadline", "calendar", "planner"],
  "⏰": ["alarm", "reminder", "wake up"],
  "⏳": ["waiting", "time running out", "countdown"],
  "🚀": ["ship it", "blast off", "startup", "product launch"],
  "💻": ["laptop", "coding", "computer", "work"],
  "🖥️": ["desktop", "computer", "monitor"],
  "⌨️": ["keyboard", "typing"],
  "📱": ["phone", "mobile", "smartphone"],
  "📞": ["call", "telephone", "phone call"],
  "📧": ["email", "mail", "inbox"],
  "✉️": ["email", "letter", "message"],
  "💬": ["chat", "message", "talk", "conversation"],
  "📣": ["announce", "announcement", "shout"],
  "🔔": ["notification", "bell", "alert"],
  "🔕": ["mute", "silent", "do not disturb"],
  "🔒": ["private", "secure", "locked", "password"],
  "🔓": ["unlocked", "open", "access"],
  "🔑": ["key", "password", "access"],
  "🛠️": ["fix", "repair", "tools", "build"],
  "🔧": ["wrench", "fix", "repair"],
  "⚙️": ["settings", "configure", "gear"],
  "🐛": ["bug", "issue", "defect"],
  "🧹": ["clean up", "cleanup", "tidy", "sweep"],
  "🗑️": ["trash", "delete", "remove"],

  // Nature, places, and travel
  "♻️": ["recycle", "reuse", "sustainability"],
  "🌱": ["growth", "new beginnings", "plant"],
  "☀️": ["sunny", "sunshine", "good morning"],
  "🌙": ["good night", "nighttime", "moon"],
  "🌈": ["rainbow", "pride", "colorful"],
  "⭐": ["favorite", "favourite", "important"],
  "💤": ["sleep", "zzz", "bedtime"],
  "🏠": ["home", "house", "at home"],
  "🏡": ["home", "house", "cozy"],
  "🏢": ["office", "workplace", "work"],
  "🏖️": ["vacation", "beach holiday", "on holiday"],
  "✈️": ["travel", "flight", "plane"],
  "🚗": ["car", "drive", "road trip"],
  "🚕": ["taxi", "cab", "ride"],
  "🚌": ["bus", "public transit"],
  "🚲": ["bike", "bicycle", "cycling"],
  "🏃": ["run", "running", "exercise"],
  "🚶": ["walk", "walking"],
  "🧘": ["meditate", "mindfulness", "yoga"],
  "🏋️": ["gym", "weightlifting", "workout"],

  // Food, hobbies, and animals
  "☕": ["coffee", "caffeine", "morning coffee"],
  "🍵": ["tea", "matcha"],
  "🍕": ["pizza", "slice"],
  "🍔": ["burger", "hamburger"],
  "🥑": ["avocado", "avo"],
  "🍞": ["bread", "toast"],
  "🍿": ["popcorn", "movie night"],
  "🍫": ["chocolate", "candy"],
  "🍷": ["wine", "cheers"],
  "🍺": ["beer", "cheers"],
  "🥂": ["cheers", "toast", "celebration"],
  "🍽️": ["dinner", "meal", "eat"],
  "⚽": ["soccer", "football", "sport"],
  "🏀": ["basketball", "hoops"],
  "🎮": ["gaming", "video games", "game"],
  "🎬": ["movie", "film", "cinema"],
  "🎵": ["music", "song", "tune"],
  "🎧": ["headphones", "listening", "podcast"],
  "📸": ["photo", "picture", "camera"],
  "🎨": ["art", "design", "painting"],
  "🪄": ["magic", "wizard", "spell"],
  "🐶": ["dog", "puppy"],
  "🐱": ["cat", "kitty"],

  // More reactions and body language
  "😐": ["deadpan", "straight face", "neutral reaction"],
  "😑": ["meh", "blank stare", "no comment"],
  "😒": ["unimpressed", "side eye", "not amused"],
  "😔": ["feeling down", "bummed out", "sad"],
  "😢": ["cry", "single tear", "sad crying"],
  "😳": ["embarrassed", "blushing", "flustered"],
  "😮": ["wow", "surprised", "mouth open"],
  "😲": ["omg", "astonished", "shocked"],
  "🫣": ["peek", "peeking", "can't look", "shy"],
  "🫢": ["oops", "gasp", "covering mouth"],
  "🤭": ["giggle", "secret", "teehee"],
  "🤫": ["shh", "quiet please", "keep it secret"],
  "🤥": ["lying", "liar", "pinocchio"],
  "🥴": ["woozy", "drunk", "out of it"],
  "🫨": ["shook", "shaken", "stunned"],
  "🤑": ["money eyes", "rich", "cash money"],
  "🤤": ["drooling", "mouth watering", "yummy"],
  "🤪": ["goofy", "silly", "wacky"],
  "😜": ["just kidding", "playful", "teasing"],
  "🥰": ["feeling loved", "affectionate", "warm and fuzzy"],
  "🤗": ["hug", "virtual hug", "sending hugs"],
  "🫂": ["hug", "embrace", "comforting"],
  "🫰": ["finger heart", "tiny heart", "korean heart"],
  "🫵": ["you", "pointing at you", "your turn"],
  "✋": ["high five", "hold on", "raised hand"],
  "✌️": ["peace", "victory", "two fingers"],
  "🤘": ["rock on", "heavy metal", "devil horns"],
  "🤟": ["i love you hand", "ily sign", "love you gesture"],
  "🧠": ["brain", "smart", "thinking hard"],
  "💭": ["thought bubble", "daydreaming", "thinking about"],

  // More messages, devices, and office work
  "📢": ["megaphone", "public announcement", "broadcast"],
  "📥": ["inbox", "incoming", "received"],
  "📤": ["outbox", "sent", "upload"],
  "📁": ["folder", "directory", "files"],
  "🗃️": ["archive", "filing cabinet", "stored files"],
  "💾": ["save", "floppy disk", "save file"],
  "🧾": ["receipt", "bill", "expense"],
  "💳": ["credit card", "payment card", "pay by card"],
  "💰": ["money bag", "cash", "wealth"],
  "💸": ["spending money", "money flying away", "expensive"],
  "📈": ["growth chart", "trending up", "stock gains"],
  "📉": ["decline", "trending down", "losses"],
  "📊": ["analytics", "bar chart", "data"],
  "🧮": ["calculate", "math", "abacus"],
  "🔄": ["refresh", "reload", "sync"],
  "🔁": ["repeat", "loop", "again"],
  "🔀": ["shuffle", "randomize", "random"],
  "⏸️": ["pause", "hold", "take a break"],
  "▶️": ["play", "start video", "resume"],
  "⏭️": ["skip", "next track", "fast forward"],
  "🚫": ["forbidden", "not allowed", "prohibited"],
  "🛑": ["stop", "halt", "stop sign"],
  "❓": ["question", "help", "what"],
  "🤖": ["ai", "bot", "artificial intelligence", "robot assistant"],
  "🧑‍💻": ["developer", "programmer", "coder", "software engineer"],
  "🖨️": ["printer", "print", "hard copy"],
  "📺": ["tv", "television", "watching tv"],
  "🎙️": ["podcast mic", "recording", "microphone"],
  "🎤": ["karaoke", "singing", "microphone"],
  "🔋": ["charged", "battery full", "power"],
  "🪫": ["low battery", "battery empty", "out of power"],
  "🔌": ["plug in", "charging", "power outlet"],
  "🛜": ["wifi", "wi fi", "wireless internet"],

  // Weather, outdoors, and getting around
  "🌧️": ["rainy", "rainy day", "raining"],
  "⛈️": ["thunderstorm", "stormy", "lightning storm"],
  "🌨️": ["snowing", "snowy day", "snowfall"],
  "❄️": ["cold", "winter", "freezing"],
  "🌊": ["ocean", "sea", "surf", "wave"],
  "🌍": ["earth", "world", "globe"],
  "🗺️": ["map", "directions", "world map"],
  "🧭": ["navigation", "find my way", "compass"],
  "🏔️": ["mountains", "hiking", "mountain trip"],
  "🏕️": ["camping", "campsite", "outdoors"],
  "🌳": ["tree", "forest", "woods"],
  "💐": ["flowers", "bouquet", "thank you flowers"],
  "🍁": ["autumn", "fall season", "maple leaf"],
  "🌸": ["spring", "cherry blossom", "pink flower"],
  "🛫": ["departure", "taking off", "flight out"],
  "🛬": ["arrival", "landing", "flight in"],
  "🚆": ["train", "railway", "commuter rail"],
  "🚇": ["subway", "metro", "underground train"],
  "🚅": ["bullet train", "high speed rail", "shinkansen"],
  "🚢": ["ship", "boat trip", "at sea"],
  "🛳️": ["cruise", "cruise ship", "ocean liner"],
  "🏨": ["hotel", "lodging", "accommodation"],
  "🏥": ["hospital", "medical care", "emergency room"],
  "🛒": ["shopping cart", "groceries", "checkout"],
  "🛍️": ["shopping", "retail therapy", "shopping bags"],

  // More food, activities, and creatures
  "🥞": ["pancakes", "breakfast", "flapjacks"],
  "🥓": ["bacon", "breakfast meat"],
  "🥗": ["salad", "healthy lunch", "greens"],
  "🍣": ["sushi", "raw fish", "japanese food"],
  "🌮": ["taco", "taco tuesday", "mexican food"],
  "🥐": ["croissant", "pastry", "french breakfast"],
  "🍪": ["cookie", "biscuit", "chocolate chip"],
  "🍩": ["donut", "doughnut", "sweet treat"],
  "🍦": ["ice cream", "soft serve", "dessert"],
  "🍉": ["watermelon", "summer fruit"],
  "🧋": ["boba", "bubble tea", "milk tea"],
  "🥤": ["soda", "soft drink", "takeout drink"],
  "🍾": ["champagne", "popping bottles", "celebration drink"],
  "🧀": ["cheese", "cheesy", "cheese wedge"],
  "🧩": ["puzzle", "piece of the puzzle", "jigsaw"],
  "♟️": ["chess", "strategy game", "pawn"],
  "🎯": ["bullseye", "target", "nailed it"],
  "🎲": ["dice", "board games", "roll the dice"],
  "🏈": ["american football", "nfl", "touchdown"],
  "⚾": ["baseball", "home run", "ballgame"],
  "🏊": ["swim", "swimming", "pool"],
  "💃": ["dance", "dancing", "let's dance"],
  "🪩": ["disco", "dance party", "disco ball"],
  "🐈‍⬛": ["black cat", "spooky cat"],
  "🧸": ["teddy bear", "stuffed animal", "plushie"],
  "🐼": ["panda", "panda bear"],
  "🦊": ["fox", "sly fox"],
  "🐸": ["frog", "ribbit"],
  "🐝": ["bee", "buzz", "honeybee"],
  "🦋": ["butterfly", "flutter"],
  "🐙": ["octopus", "eight arms"],
  "🦄": ["unicorn", "magical horse"],
  "🦖": ["t rex", "tyrannosaurus", "dinosaur"],
  "🐢": ["turtle", "slow and steady"],
  "🦉": ["owl", "night owl"],
  "🐧": ["penguin", "antarctic bird"],
  "🐬": ["dolphin", "sea mammal"],
  "🦈": ["shark", "jaws"],
};
