export const OIDS = {
  // Page Counts
  TOTAL_PAGES: "1.3.6.1.4.1.253.8.53.13.2.1.6.1.20.1",
  BLACK_PAGES: "1.3.6.1.4.1.253.8.53.13.2.1.6.1.20.34",
  COLOR_PAGES: "1.3.6.1.4.1.253.8.53.13.2.1.6.1.20.33",

  // Ink Levels (Current)
  INK_BLACK_CURRENT: "1.3.6.1.2.1.43.11.1.1.9.1.1",
  INK_YELLOW_CURRENT: "1.3.6.1.2.1.43.11.1.1.9.1.2",
  INK_MAGENTA_CURRENT: "1.3.6.1.2.1.43.11.1.1.9.1.3",
  INK_CYAN_CURRENT: "1.3.6.1.2.1.43.11.1.1.9.1.4",

  // Ink Levels (Max)
  INK_BLACK_MAX: "1.3.6.1.2.1.43.11.1.1.8.1.1",
  INK_YELLOW_MAX: "1.3.6.1.2.1.43.11.1.1.8.1.2",
  INK_MAGENTA_MAX: "1.3.6.1.2.1.43.11.1.1.8.1.3",
  INK_CYAN_MAX: "1.3.6.1.2.1.43.11.1.1.8.1.4",

  // General Info
  MODEL_NAME: "1.3.6.1.2.1.1.1.0",
  SERIAL_NUMBER: "1.3.6.1.2.1.43.5.1.1.17.1",
  PRINTER_NAME: "1.3.6.1.2.1.1.5.0",

  // Status (Console Display)
  CONSOLE_DISPLAY: "1.3.6.1.2.1.43.16.5.1.2.1.1",
} as const;

export const INK_COLORS = {
  BLACK: "black",
  CYAN: "cyan",
  MAGENTA: "magenta",
  YELLOW: "yellow",
} as const;

export const LABELS = {
  en: {
    sectionGeneral: "General Information",
    status: "Status",
    copyStatus: "Copy Status",
    ipAddress: "IP Address",
    copyIp: "Copy IP",
    networkName: "Network Name",
    copyName: "Copy Name",
    model: "Model",
    copyModel: "Copy Model",
    serialNumber: "Serial Number",
    copySerial: "Copy Serial Number",
    sectionPageCounts: "Page Counts",
    total: "Total",
    copyTotal: "Copy Total",
    blackWhite: "Black & White",
    copyTotalBlack: "Copy Total Black",
    color: "Color",
    copyTotalColor: "Copy Total Color",
    sectionInkLevels: "Ink Levels",
    black: "Black",
    copyBlackLevel: "Copy Black Level",
    cyan: "Cyan",
    copyCyanLevel: "Copy Cyan Level",
    magenta: "Magenta",
    copyMagentaLevel: "Copy Magenta Level",
    yellow: "Yellow",
    copyYellowLevel: "Copy Yellow Level",
    pages: "pages",
  },
  fr: {
    sectionGeneral: "Informations Générales",
    status: "État",
    copyStatus: "Copier L'État",
    ipAddress: "Adresse IP",
    copyIp: "Copier L'IP",
    networkName: "Nom Réseau",
    copyName: "Copier Le Nom",
    model: "Modèle",
    copyModel: "Copier Le Modèle",
    serialNumber: "Numéro de Série",
    copySerial: "Copier Le Numéro De Série",
    sectionPageCounts: "Compteurs de Pages",
    total: "Total",
    copyTotal: "Copier Le Total",
    blackWhite: "Noir & Blanc",
    copyTotalBlack: "Copier Le Total Noir",
    color: "Couleur",
    copyTotalColor: "Copier Le Total Couleur",
    sectionInkLevels: "Niveaux d'Encre",
    black: "Noir",
    copyBlackLevel: "Copier Le Niveau Noir",
    cyan: "Cyan",
    copyCyanLevel: "Copier Le Niveau Cyan",
    magenta: "Magenta",
    copyMagentaLevel: "Copier Le Niveau Magenta",
    yellow: "Jaune",
    copyYellowLevel: "Copier Le Niveau Jaune",
    pages: "pages",
  },
  de: {
    sectionGeneral: "Allgemeine Informationen",
    status: "Status",
    copyStatus: "Status kopieren",
    ipAddress: "IP-Adresse",
    copyIp: "IP kopieren",
    networkName: "Netzwerkname",
    copyName: "Name kopieren",
    model: "Modell",
    copyModel: "Modell kopieren",
    serialNumber: "Seriennummer",
    copySerial: "Seriennummer kopieren",
    sectionPageCounts: "Seitenzähler",
    total: "Gesamt",
    copyTotal: "Gesamt kopieren",
    blackWhite: "Schwarz-Weiß",
    copyTotalBlack: "Gesamt Schwarz kopieren",
    color: "Farbe",
    copyTotalColor: "Gesamt Farbe kopieren",
    sectionInkLevels: "Tintenfüllstände",
    black: "Schwarz",
    copyBlackLevel: "Schwarz Füllstand kopieren",
    cyan: "Cyan",
    copyCyanLevel: "Cyan Füllstand kopieren",
    magenta: "Magenta",
    copyMagentaLevel: "Magenta Füllstand kopieren",
    yellow: "Gelb",
    copyYellowLevel: "Gelb Füllstand kopieren",
    pages: "Seiten",
  },
  es: {
    sectionGeneral: "Información General",
    status: "Estado",
    copyStatus: "Copiar Estado",
    ipAddress: "Dirección IP",
    copyIp: "Copiar IP",
    networkName: "Nombre de Red",
    copyName: "Copiar Nombre",
    model: "Modelo",
    copyModel: "Copiar Modelo",
    serialNumber: "Número de Serie",
    copySerial: "Copiar Número de Serie",
    sectionPageCounts: "Contadores de Página",
    total: "Total",
    copyTotal: "Copiar Total",
    blackWhite: "Blanco y Negro",
    copyTotalBlack: "Copiar Total Negro",
    color: "Color",
    copyTotalColor: "Copiar Total Color",
    sectionInkLevels: "Niveles de Tinta",
    black: "Negro",
    copyBlackLevel: "Copiar Nivel Negro",
    cyan: "Cian",
    copyCyanLevel: "Copiar Nivel Cian",
    magenta: "Magenta",
    copyMagentaLevel: "Copiar Nivel Magenta",
    yellow: "Amarillo",
    copyYellowLevel: "Copiar Nivel Amarillo",
    pages: "páginas",
  },
} as const;
