export const colorEmojiMap: Record<string, string> = {
  "#FF5733": "🟥", // Vivid Red (Solid Red Square)
  "#FF6F61": "🟧", // Soft Orange (Solid Orange Square)
  "#FFD700": "🟨", // Bright Yellow (Solid Yellow Square)
  "#33FF57": "🟩", // Vibrant Green (Solid Green Square)
  "#2ECC71": "🟢", // Warm Green (Solid Green Circle)
  "#1E90FF": "🟦", // Sky Blue (Solid Blue Square)
  "#4B0082": "🟪", // Deep Purple (Solid Purple Square)
  "#8B4513": "🟫", // Brown (Solid Brown Square)
  "#CCCCCC": "⬜️", // Light Gray (White Square)
  "#000000": "⬛️", // Black (Black Square)
  "#FF69B4": "🩷", // Pink Blossom (Solid Pink Heart)
  "#FFDAB9": "🟧", // Peach Pink (Closest Match: Orange Square)
  "#ADD8E6": "🔵", // Light Blue (Solid Blue Circle)
  "#FF4500": "🟠", // Orange Red Flame (Solid Orange Circle)
  "#FFFFE0": "🟡", // Pale Yellow Star (Solid Yellow Circle)
  "#98FB98": "🟢", // Mint Green Clover (Solid Green Circle)
  "#FFB6C1": "🩷", // Light Pink Heart (Solid Pink Heart)
  "#8A2BE2": "🟪", // Purple Swirl (Solid Purple Square)
};
