/**
 * Country VAT format catalog.
 *
 * Each entry knows how to build the body of a VAT number (everything after the
 * prefix) so the full number passes the country's check-digit algorithm.
 */

import * as gen from "./generators";

export type Tier = "checksum" | "format";

export interface Country {
  /** Stable id, also used for the example region label. */
  code: string;
  name: string;
  flag: string;
  /** VAT prefix shown/prepended to the body (may be empty for some regions). */
  prefix: string;
  region: string;
  tier: Tier;
  /** Returns the VAT body (without the prefix). */
  body: () => string;
  /** Human-readable description of the format. */
  format: string;
}

export const COUNTRIES: Country[] = [
  // ----- EU: checksum-correct -----
  {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    prefix: "NL",
    region: "EU",
    tier: "checksum",
    body: gen.nl,
    format: "9 digits + B + 2 digits",
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    prefix: "DE",
    region: "EU",
    tier: "checksum",
    body: gen.de,
    format: "9 digits",
  },
  {
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    prefix: "BE",
    region: "EU",
    tier: "checksum",
    body: gen.be,
    format: "10 digits",
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    prefix: "FR",
    region: "EU",
    tier: "checksum",
    body: gen.fr,
    format: "2-char key + 9-digit SIREN",
  },
  {
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    prefix: "IT",
    region: "EU",
    tier: "checksum",
    body: gen.it,
    format: "11 digits",
  },
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    prefix: "ES",
    region: "EU",
    tier: "checksum",
    body: gen.es,
    format: "letter + 8 chars (CIF)",
  },
  {
    code: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
    prefix: "LU",
    region: "EU",
    tier: "checksum",
    body: gen.lu,
    format: "8 digits",
  },
  {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    prefix: "PL",
    region: "EU",
    tier: "checksum",
    body: gen.pl,
    format: "10 digits",
  },
  {
    code: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    prefix: "SE",
    region: "EU",
    tier: "checksum",
    body: gen.se,
    format: "12 digits",
  },
  {
    code: "FI",
    name: "Finland",
    flag: "🇫🇮",
    prefix: "FI",
    region: "EU",
    tier: "checksum",
    body: gen.fi,
    format: "8 digits",
  },
  {
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    prefix: "DK",
    region: "EU",
    tier: "checksum",
    body: gen.dk,
    format: "8 digits",
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    prefix: "PT",
    region: "EU",
    tier: "checksum",
    body: gen.pt,
    format: "9 digits",
  },

  // ----- EU: checksum-correct (continued) -----
  {
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    prefix: "AT",
    region: "EU",
    tier: "checksum",
    body: gen.at,
    format: "U + 8 digits",
  },
  {
    code: "BG",
    name: "Bulgaria",
    flag: "🇧🇬",
    prefix: "BG",
    region: "EU",
    tier: "checksum",
    body: gen.bg,
    format: "9-digit legal entity",
  },
  {
    code: "HR",
    name: "Croatia",
    flag: "🇭🇷",
    prefix: "HR",
    region: "EU",
    tier: "checksum",
    body: gen.hr,
    format: "11 digits",
  },
  {
    code: "CY",
    name: "Cyprus",
    flag: "🇨🇾",
    prefix: "CY",
    region: "EU",
    tier: "checksum",
    body: gen.cy,
    format: "8 digits + 1 letter",
  },
  {
    code: "CZ",
    name: "Czechia",
    flag: "🇨🇿",
    prefix: "CZ",
    region: "EU",
    tier: "checksum",
    body: gen.cz,
    format: "8-digit legal entity",
  },
  {
    code: "EE",
    name: "Estonia",
    flag: "🇪🇪",
    prefix: "EE",
    region: "EU",
    tier: "checksum",
    body: gen.ee,
    format: "9 digits (starts with 10)",
  },
  {
    code: "GR",
    name: "Greece",
    flag: "🇬🇷",
    prefix: "EL",
    region: "EU",
    tier: "checksum",
    body: gen.gr,
    format: "9 digits",
  },
  {
    code: "HU",
    name: "Hungary",
    flag: "🇭🇺",
    prefix: "HU",
    region: "EU",
    tier: "checksum",
    body: gen.hu,
    format: "8 digits",
  },
  {
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    prefix: "IE",
    region: "EU",
    tier: "checksum",
    body: gen.ie,
    format: "7 digits + check letter",
  },
  {
    code: "LV",
    name: "Latvia",
    flag: "🇱🇻",
    prefix: "LV",
    region: "EU",
    tier: "checksum",
    body: gen.lv,
    format: "11-digit legal entity",
  },
  {
    code: "LT",
    name: "Lithuania",
    flag: "🇱🇹",
    prefix: "LT",
    region: "EU",
    tier: "checksum",
    body: gen.lt,
    format: "9-digit legal person",
  },
  {
    code: "MT",
    name: "Malta",
    flag: "🇲🇹",
    prefix: "MT",
    region: "EU",
    tier: "checksum",
    body: gen.mt,
    format: "8 digits",
  },
  {
    code: "RO",
    name: "Romania",
    flag: "🇷🇴",
    prefix: "RO",
    region: "EU",
    tier: "checksum",
    body: gen.ro,
    format: "10-digit CIF",
  },
  {
    code: "SK",
    name: "Slovakia",
    flag: "🇸🇰",
    prefix: "SK",
    region: "EU",
    tier: "checksum",
    body: gen.sk,
    format: "10 digits",
  },
  {
    code: "SI",
    name: "Slovenia",
    flag: "🇸🇮",
    prefix: "SI",
    region: "EU",
    tier: "checksum",
    body: gen.si,
    format: "8 digits",
  },

  // ----- Other Europe (non-EU) -----
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    prefix: "GB",
    region: "Europe",
    tier: "checksum",
    body: gen.gb,
    format: "9 digits",
  },
  {
    code: "AD",
    name: "Andorra",
    flag: "🇦🇩",
    prefix: "AD",
    region: "Europe",
    tier: "checksum",
    body: gen.ad,
    format: "letter + 6 digits + letter",
  },
  {
    code: "RS",
    name: "Serbia",
    flag: "🇷🇸",
    prefix: "RS",
    region: "Europe",
    tier: "checksum",
    body: gen.rs,
    format: "9 digits",
  },
  {
    code: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    prefix: "CHE",
    region: "Europe",
    tier: "checksum",
    body: gen.ch,
    format: "CHE + 9 digits",
  },
  {
    code: "NO",
    name: "Norway",
    flag: "🇳🇴",
    prefix: "NO",
    region: "Europe",
    tier: "checksum",
    body: gen.no,
    format: "9 digits + MVA",
  },

  // ----- United States (EIN, not VAT) -----
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    prefix: "",
    region: "US",
    tier: "format",
    body: gen.us,
    format: "9-digit EIN (XX-XXXXXXX)",
  },
];

/** Build a full VAT number string for a country. */
export function generateVat(country: Country): string {
  return `${country.prefix}${country.body()}`;
}
