/**
 * Country VAT format catalog.
 *
 * Each entry knows how to build the body of a VAT number (everything after the
 * prefix). Entries are either:
 *   - tier "checksum": the generated number satisfies the country's documented
 *     check-digit algorithm, or
 *   - tier "format":   the number matches the country's length/pattern only.
 */

import * as gen from "./generators";

export type Tier = "checksum" | "format";

export interface Country {
  /** Stable id, also used for the example region label. */
  code: string;
  name: string;
  flag: string;
  /** VAT prefix shown/prepended to the body (may be empty for some regions). */
  prefix: string;
  region: string;
  tier: Tier;
  /** Returns the VAT body (without the prefix). */
  body: () => string;
  /** Human-readable description of the format. */
  format: string;
}

const fmt =
  (pattern: string): (() => string) =>
  () =>
    gen.formatBody(pattern);

export const COUNTRIES: Country[] = [
  // ----- EU: checksum-correct -----
  {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    prefix: "NL",
    region: "EU",
    tier: "checksum",
    body: gen.nl,
    format: "9 digits + B + 2 digits",
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    prefix: "DE",
    region: "EU",
    tier: "checksum",
    body: gen.de,
    format: "9 digits",
  },
  {
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    prefix: "BE",
    region: "EU",
    tier: "checksum",
    body: gen.be,
    format: "10 digits",
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    prefix: "FR",
    region: "EU",
    tier: "checksum",
    body: gen.fr,
    format: "2-char key + 9-digit SIREN",
  },
  {
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    prefix: "IT",
    region: "EU",
    tier: "checksum",
    body: gen.it,
    format: "11 digits",
  },
  {
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    prefix: "ES",
    region: "EU",
    tier: "checksum",
    body: gen.es,
    format: "letter + 8 chars (CIF)",
  },
  {
    code: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
    prefix: "LU",
    region: "EU",
    tier: "checksum",
    body: gen.lu,
    format: "8 digits",
  },
  {
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    prefix: "PL",
    region: "EU",
    tier: "checksum",
    body: gen.pl,
    format: "10 digits",
  },
  {
    code: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    prefix: "SE",
    region: "EU",
    tier: "checksum",
    body: gen.se,
    format: "12 digits",
  },
  {
    code: "FI",
    name: "Finland",
    flag: "🇫🇮",
    prefix: "FI",
    region: "EU",
    tier: "checksum",
    body: gen.fi,
    format: "8 digits",
  },
  {
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    prefix: "DK",
    region: "EU",
    tier: "checksum",
    body: gen.dk,
    format: "8 digits",
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    prefix: "PT",
    region: "EU",
    tier: "checksum",
    body: gen.pt,
    format: "9 digits",
  },

  // ----- EU: format-valid only -----
  {
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    prefix: "AT",
    region: "EU",
    tier: "format",
    body: fmt("U99999999"),
    format: "U + 8 digits",
  },
  {
    code: "BG",
    name: "Bulgaria",
    flag: "🇧🇬",
    prefix: "BG",
    region: "EU",
    tier: "format",
    body: fmt("999999999"),
    format: "9-10 digits",
  },
  {
    code: "HR",
    name: "Croatia",
    flag: "🇭🇷",
    prefix: "HR",
    region: "EU",
    tier: "format",
    body: fmt("99999999999"),
    format: "11 digits",
  },
  {
    code: "CY",
    name: "Cyprus",
    flag: "🇨🇾",
    prefix: "CY",
    region: "EU",
    tier: "format",
    body: fmt("99999999A"),
    format: "8 digits + 1 letter",
  },
  {
    code: "CZ",
    name: "Czechia",
    flag: "🇨🇿",
    prefix: "CZ",
    region: "EU",
    tier: "format",
    body: fmt("99999999"),
    format: "8-10 digits",
  },
  {
    code: "EE",
    name: "Estonia",
    flag: "🇪🇪",
    prefix: "EE",
    region: "EU",
    tier: "format",
    body: fmt("999999999"),
    format: "9 digits",
  },
  {
    code: "GR",
    name: "Greece",
    flag: "🇬🇷",
    prefix: "EL",
    region: "EU",
    tier: "format",
    body: fmt("999999999"),
    format: "9 digits",
  },
  {
    code: "HU",
    name: "Hungary",
    flag: "🇭🇺",
    prefix: "HU",
    region: "EU",
    tier: "format",
    body: fmt("99999999"),
    format: "8 digits",
  },
  {
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    prefix: "IE",
    region: "EU",
    tier: "format",
    body: fmt("9999999AA"),
    format: "7 digits + 1-2 letters",
  },
  {
    code: "LV",
    name: "Latvia",
    flag: "🇱🇻",
    prefix: "LV",
    region: "EU",
    tier: "format",
    body: fmt("99999999999"),
    format: "11 digits",
  },
  {
    code: "LT",
    name: "Lithuania",
    flag: "🇱🇹",
    prefix: "LT",
    region: "EU",
    tier: "format",
    body: fmt("999999999"),
    format: "9 or 12 digits",
  },
  {
    code: "MT",
    name: "Malta",
    flag: "🇲🇹",
    prefix: "MT",
    region: "EU",
    tier: "format",
    body: fmt("99999999"),
    format: "8 digits",
  },
  {
    code: "RO",
    name: "Romania",
    flag: "🇷🇴",
    prefix: "RO",
    region: "EU",
    tier: "format",
    body: fmt("999999999"),
    format: "2-10 digits",
  },
  {
    code: "SK",
    name: "Slovakia",
    flag: "🇸🇰",
    prefix: "SK",
    region: "EU",
    tier: "format",
    body: fmt("9999999999"),
    format: "10 digits",
  },
  {
    code: "SI",
    name: "Slovenia",
    flag: "🇸🇮",
    prefix: "SI",
    region: "EU",
    tier: "format",
    body: fmt("99999999"),
    format: "8 digits",
  },

  // ----- Rest of the world: format-valid only -----
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    prefix: "GB",
    region: "World",
    tier: "format",
    body: fmt("999999999"),
    format: "9 digits",
  },
  {
    code: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    prefix: "CHE",
    region: "World",
    tier: "format",
    body: fmt("999999999"),
    format: "CHE + 9 digits",
  },
  {
    code: "NO",
    name: "Norway",
    flag: "🇳🇴",
    prefix: "NO",
    region: "World",
    tier: "format",
    body: fmt("999999999MVA"),
    format: "9 digits + MVA",
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("99999999999"),
    format: "11-digit ABN",
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("999999999RT0001"),
    format: "9 digits + RT0001",
  },
  {
    code: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("999999999"),
    format: "9-digit GST/IRD",
  },
  {
    code: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("4999999999"),
    format: "10 digits (starts with 4)",
  },
  {
    code: "RU",
    name: "Russia",
    flag: "🇷🇺",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("9999999999"),
    format: "10 or 12-digit INN",
  },
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("99AAAAA9999A9ZX"),
    format: "15-char GSTIN",
  },
  {
    code: "JP",
    name: "Japan",
    flag: "🇯🇵",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("T9999999999999"),
    format: "T + 13 digits",
  },
  {
    code: "KR",
    name: "South Korea",
    flag: "🇰🇷",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("9999999999"),
    format: "10-digit BRN",
  },
  {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("M99999999A"),
    format: "GST registration",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("999999999999999"),
    format: "15-digit TRN",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("999999999999999"),
    format: "15-digit VAT",
  },
  {
    code: "MX",
    name: "Mexico",
    flag: "🇲🇽",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("AAA999999XXX"),
    format: "12-13 char RFC",
  },
  {
    code: "BR",
    name: "Brazil",
    flag: "🇧🇷",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("99999999999999"),
    format: "14-digit CNPJ",
  },
  {
    code: "TR",
    name: "Turkey",
    flag: "🇹🇷",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("9999999999"),
    format: "10-digit VKN",
  },
  {
    code: "UA",
    name: "Ukraine",
    flag: "🇺🇦",
    prefix: "",
    region: "World",
    tier: "format",
    body: fmt("999999999999"),
    format: "12 digits",
  },
];

/** Build a full VAT number string for a country. */
export function generateVat(country: Country): string {
  return `${country.prefix}${country.body()}`;
}
