export type Preset = {
  id: string;
  name: string;
  emoji?: string;
  exts: string[];
};

export const SEED_PRESETS: Preset[] = [
  {
    id: "pivot:dev",
    name: "Developer",
    emoji: "💻",
    exts: [
      // source
      "ts",
      "tsx",
      "js",
      "jsx",
      "mjs",
      "cjs",
      "py",
      "pyi",
      "ipynb",
      "rb",
      "go",
      "rs",
      "java",
      "kt",
      "kts",
      "scala",
      "groovy",
      "swift",
      "m",
      "mm",
      "c",
      "h",
      "cpp",
      "cc",
      "cxx",
      "hpp",
      "hh",
      "cs",
      "fs",
      "vb",
      "php",
      "lua",
      "pl",
      "r",
      "jl",
      "ex",
      "exs",
      "erl",
      "hrl",
      "clj",
      "cljs",
      "dart",
      "elm",
      "hs",
      "ml",
      "nim",
      "zig",
      "v",
      "coffee",
      "tcl",
      "cr",
      "purs",
      "d",
      "gleam",
      "scm",
      "rkt",
      // markup / docs
      "md",
      "mdx",
      "markdown",
      "txt",
      "rst",
      "adoc",
      "tex",
      "bib",
      "sty",
      "cls",
      "org",
      // config
      "json",
      "json5",
      "jsonc",
      "jsonl",
      "ndjson",
      "yaml",
      "yml",
      "toml",
      "ini",
      "env",
      "xml",
      "conf",
      "cfg",
      "properties",
      "lock",
      "cue",
      "dhall",
      "nix",
      // web
      "html",
      "htm",
      "css",
      "scss",
      "sass",
      "less",
      "styl",
      "stylus",
      "postcss",
      "pcss",
      "vue",
      "svelte",
      "astro",
      "ejs",
      "hbs",
      "handlebars",
      "mustache",
      "liquid",
      "njk",
      "pug",
      "twig",
      // shell
      "sh",
      "bash",
      "zsh",
      "fish",
      "ps1",
      "bat",
      "cmd",
      // build / infra
      "dockerfile",
      "containerfile",
      "makefile",
      "mk",
      "gradle",
      "tf",
      "tfvars",
      "hcl",
      "bzl",
      "bazel",
      "cmake",
      "ninja",
      // .NET
      "csproj",
      "sln",
      "props",
      "targets",
      // ruby / iOS specs
      "gemspec",
      "podspec",
      "rake",
      // apple / xcode
      "plist",
      "xcconfig",
      "entitlements",
      "pbxproj",
      "xib",
      "storyboard",
      "metal",
      // editor
      "vim",
      "el",
      // shaders
      "glsl",
      "wgsl",
      "hlsl",
      "vert",
      "frag",
      "comp",
      // data
      "csv",
      "tsv",
      "sql",
      "graphql",
      "gql",
      "proto",
      // misc
      "log",
      "patch",
      "diff",
    ],
  },
];

export function normalizeExt(input: string): string {
  return input.trim().toLowerCase().replace(/^\./, "");
}
