export const REPOS = "repos"
export const PRS_DETAILS = "prsDetails"
export const PRS_CHECKS = "prsChecks"
export const PRS_REVIEWS = "prsReviews"
export const PRS_REVIEW_COMMENTS = "prsReviewComments"
