const { defineConfig } = require("eslint/config");
const tsPlugin = require("@typescript-eslint/eslint-plugin");
const tsParser = require("@typescript-eslint/parser");
const raycastConfig = require("@raycast/eslint-config");
const promise = require("eslint-plugin-promise");
const react = require("eslint-plugin-react");
const reactHooks = require("eslint-plugin-react-hooks");
const reactRefreshModule = require("eslint-plugin-react-refresh");
const unicornModule = require("eslint-plugin-unicorn");
const vitest = require("@vitest/eslint-plugin");

const reactRefresh = reactRefreshModule.default ?? reactRefreshModule;
const unicorn = unicornModule.default ?? unicornModule;

const typescriptFiles = ["**/*.ts", "**/*.tsx"];
const testFiles = ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"];

module.exports = defineConfig([
  ...raycastConfig,
  {
    ...react.configs.flat["jsx-runtime"],
    files: typescriptFiles,
  },
  {
    ...reactHooks.configs.flat.recommended,
    files: typescriptFiles,
  },
  {
    ignores: ["dist/**", "node_modules/**"],
  },
  {
    files: typescriptFiles,
    languageOptions: {
      globals: {
        Preferences: "readonly",
      },
      parser: tsParser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      promise,
      "react-refresh": reactRefresh,
      unicorn,
      vitest,
    },
    rules: {
      "array-callback-return": "error",
      "capitalized-comments": "error",
      complexity: "error",
      curly: "error",
      "default-case-last": "error",
      "default-param-last": "error",
      eqeqeq: "error",
      "func-style": ["error", "expression"],
      "max-lines-per-function": "error",
      "no-alert": "error",
      "no-console": "warn",
      "no-continue": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "error",
      "no-empty": "error",
      "no-fallthrough": "error",
      "no-implicit-coercion": "error",
      "no-inner-declarations": "error",
      "no-inline-comments": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-multi-str": "error",
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-param-reassign": "error",
      "no-return-assign": "error",
      "no-sequences": "error",
      "no-self-compare": "error",
      "no-shadow": "error",
      "no-template-curly-in-string": "error",
      "no-undef": "error",
      "no-unmodified-loop-condition": "error",
      "no-undefined": "error",
      "no-unneeded-ternary": "error",
      "no-use-before-define": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "object-shorthand": "error",
      "prefer-const": "error",
      "prefer-object-has-own": "error",
      "prefer-template": "error",
      "sort-keys": "error",
      yoda: "error",
      "no-restricted-exports": [
        "error",
        {
          restrictedNamedExports: ["default"],
        },
      ],
      "@typescript-eslint/array-type": [
        "error",
        {
          default: "array-simple",
        },
      ],
      "@typescript-eslint/ban-tslint-comment": "error",
      "@typescript-eslint/consistent-generic-constructors": "error",
      "@typescript-eslint/consistent-type-assertions": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/explicit-function-return-type": "error",
      "@typescript-eslint/explicit-module-boundary-types": "error",
      "@typescript-eslint/no-confusing-non-null-assertion": "error",
      "@typescript-eslint/no-dynamic-delete": "error",
      "@typescript-eslint/no-empty-object-type": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-import-type-side-effects": "error",
      "@typescript-eslint/no-invalid-void-type": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-namespace": "error",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-require-imports": "error",
      "@typescript-eslint/no-unnecessary-type-constraint": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/no-unsafe-function-type": "error",
      "@typescript-eslint/no-var-requires": "error",
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/prefer-find": "error",
      "@typescript-eslint/prefer-for-of": "error",
      "@typescript-eslint/prefer-function-type": "error",
      "@typescript-eslint/prefer-includes": "error",
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/prefer-ts-expect-error": "error",
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/restrict-plus-operands": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "promise/always-return": "error",
      "promise/avoid-new": "error",
      "promise/catch-or-return": "error",
      "promise/no-multiple-resolved": "error",
      "promise/no-new-statics": "error",
      "promise/no-promise-in-callback": "error",
      "promise/no-return-in-finally": "error",
      "promise/no-return-wrap": "error",
      "promise/param-names": "error",
      "promise/prefer-catch": "error",
      "promise/valid-params": "error",
      "react-hooks/rules-of-hooks": "error",
      "react-refresh/only-export-components": "error",
      "unicorn/consistent-assert": "error",
      "unicorn/consistent-date-clone": "error",
      "unicorn/consistent-existence-index-check": "error",
      "unicorn/empty-brace-spaces": "error",
      "unicorn/escape-case": "error",
      "unicorn/explicit-length-check": "error",
      "unicorn/no-await-in-promise-methods": "error",
      "unicorn/no-unnecessary-await": "error",
      "unicorn/no-unreadable-iife": "error",
      "unicorn/no-useless-fallback-in-spread": "error",
      "unicorn/no-useless-length-check": "error",
      "unicorn/no-useless-promise-resolve-reject": "error",
      "unicorn/no-useless-switch-case": "error",
      "unicorn/no-useless-undefined": "error",
      "unicorn/no-zero-fractions": "error",
      "unicorn/prefer-array-flat-map": "error",
      "unicorn/prefer-array-index-of": "error",
      "unicorn/prefer-array-some": "error",
      "unicorn/prefer-at": "error",
      "unicorn/prefer-bigint-literals": "error",
      "unicorn/prefer-classlist-toggle": "error",
      "unicorn/prefer-date-now": "error",
      "unicorn/prefer-dom-node-append": "error",
      "unicorn/prefer-dom-node-dataset": "error",
      "unicorn/prefer-dom-node-remove": "error",
      "unicorn/prefer-dom-node-text-content": "error",
      "unicorn/prefer-keyboard-event-key": "error",
      "unicorn/prefer-math-min-max": "error",
      "unicorn/prefer-optional-catch-binding": "error",
      "unicorn/prefer-regexp-test": "error",
      "unicorn/prefer-set-size": "error",
      "unicorn/prefer-spread": "error",
      "unicorn/prefer-string-raw": "error",
      "unicorn/prefer-string-replace-all": "error",
      "unicorn/prefer-string-slice": "error",
      "unicorn/prefer-string-starts-ends-with": "error",
      "unicorn/prefer-string-trim-start-end": "error",
      "unicorn/prefer-type-error": "error",
      "unicorn/require-array-join-separator": "error",
      "unicorn/require-number-to-fixed-digits-argument": "error",
      "unicorn/switch-case-braces": "error",
      "unicorn/text-encoding-identifier-case": "error",
      "unicorn/throw-new-error": "error",
      "unicorn/filename-case": [
        "error",
        {
          case: "kebabCase",
        },
      ],
    },
  },
  {
    files: ["src/**/*.{ts}"],
    rules: {
      "max-lines": ["error", 350],
    },
  },
  {
    files: testFiles,
    rules: {
      "vitest/expect-expect": "error",
      "vitest/hoisted-apis-on-top": "error",
      "vitest/no-commented-out-tests": "error",
      "vitest/no-conditional-expect": "error",
      "vitest/no-conditional-tests": "error",
      "vitest/no-disabled-tests": "error",
      "vitest/no-focused-tests": "error",
      "vitest/no-identical-title": "error",
      "vitest/no-import-node-test": "error",
      "vitest/no-standalone-expect": "error",
      "vitest/require-awaited-expect-poll": "error",
      "vitest/require-local-test-context-for-concurrent-snapshots": "error",
      "vitest/require-mock-type-parameters": "error",
      "vitest/require-to-throw-message": "error",
      "vitest/valid-describe-callback": "error",
      "vitest/valid-expect": "error",
      "vitest/valid-expect-in-promise": "error",
      "vitest/valid-title": "error",
      "vitest/warn-todo": "error",
    },
  },
]);
