openapi: 3.0.0
info:
  contact:
    name: Canva Developer Community
    url: https://community.canva.dev/
  description: API for building integrations with Canva via a REST api
  license:
    name: ©2023 All Rights Reserved
  termsOfService: https://www.canva.com/trust/legal/
  title: Canva Connect API
  version: latest
servers:
  - description: Canva Connect API
    url: https://api.canva.com/rest
tags:
  - name: app
  - name: asset
  - name: autofill
  - name: brand_template
  - name: comment
  - name: connect
  - name: design
  - name: design_import
  - name: export
  - name: folder
  - name: oauth
  - name: user
paths:
  /v1/apps/{appId}/jwks:
    get:
      description: |-
        Returns the Json Web Key Set (public keys) of an app. These keys are used to
        verify JWTs sent to app backends.
      operationId: getAppJwks
      tags:
        - app
  /v1/assets/{assetId}:
    delete:
      description: |-
        You can delete an asset by specifying its `assetId`. This operation mirrors the behavior
        in the Canva UI. Deleting an item moves it to the trash.
        Deleting an asset doesn't remove it from designs that already use it.
      operationId: deleteAsset
      security:
        - oauthAuthCode:
            - asset:write
      tags:
        - asset
      x-rate-limit-per-client-user: 30
    get:
      description: You can retrieve the metadata of an asset by specifying its `assetId`.
      operationId: getAsset
      security:
        - oauthAuthCode:
            - asset:read
      tags:
        - asset
      x-rate-limit-per-client-user: 100
    patch:
      description: |-
        You can update the name and tags of an asset by specifying its `assetId`. Updating the tags
        replaces all existing tags of the asset.
      operationId: updateAsset
      security:
        - oauthAuthCode:
            - asset:write
      tags:
        - asset
      x-rate-limit-per-client-user: 30
  /v1/asset-uploads:
    post:
      description: |-
        Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to upload an asset to the user's content library. Supported file types for assets are listed in the [Assets API overview](https://www.canva.dev/docs/connect/api-reference/assets/).

        The request format for this endpoint is an `application/octet-stream` body of bytes. Attach
        information about the upload using an `Asset-Upload-Metadata` header.


        <Note>

        For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of asset upload jobs created with this API using the [Get asset upload job API](https://www.canva.dev/docs/connect/api-reference/assets/get-asset-upload-job/).

        </Note>
      operationId: CreateAssetUploadJob
      security:
        - oauthAuthCode:
            - asset:write
      tags:
        - asset
      x-rate-limit-per-client-user: 30
  /v1/asset-uploads/{jobId}:
    get:
      description: |-
        Get the result of an asset upload job that was created using the [Create asset upload job API](https://www.canva.dev/docs/connect/api-reference/assets/create-asset-upload-job/).

        You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
      operationId: GetAssetUploadJob
      security:
        - oauthAuthCode:
            - asset:read
      tags:
        - asset
      x-rate-limit-per-client-user: 180
  /v1/autofills:
    post:
      description: |-
        <Warning>

        Later this year, we'll be updating all brand template IDs. If your integration stores brand template IDs, you'll need to migrate to the new IDs. Once we implement this change, you'll have 6 months to update the IDs.

        </Warning>

        <Note>

        To use this API, your integration must act on behalf of a user that's a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.

        </Note>

        Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to autofill a Canva design using a brand template and input data.

        To get a list of input data fields, use the [Get brand template dataset
        API](https://www.canva.dev/docs/connect/api-reference/brand-templates/get-brand-template-dataset/).

        Available data field types to autofill include:

        - Images
        - Text
        - Charts

          WARNING: Chart data fields are a [preview feature](https://www.canva.dev/docs/connect/#preview-apis). There might be unannounced breaking changes to this feature which won't produce a new API version.

        <Note>

        For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of autofill jobs created with this API using the [Get design autofill job API](https://www.canva.dev/docs/connect/api-reference/autofills/get-design-autofill-job/).

        </Note>
      operationId: createDesignAutofillJob
      security:
        - oauthAuthCode:
            - design:content:write
      tags:
        - autofill
      x-rate-limit-per-client-user: 10
  /v1/autofills/{jobId}:
    get:
      description: |-
        <Note>

        To use this API, your integration must act on behalf of a user that's a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.

        </Note>

        Get the result of a design autofill job that was created using the [Create design autofill job
        API](https://www.canva.dev/docs/connect/api-reference/autofills/create-design-autofill-job/).

        You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
      operationId: getDesignAutofillJob
      security:
        - oauthAuthCode:
            - design:meta:read
      tags:
        - autofill
      x-rate-limit-per-client-user: 60
  /v1/brand-templates:
    get:
      description: |-
        <Warning>

        Later this year, we'll be updating all brand template IDs. If your integration stores brand template IDs, you'll need to migrate to the new IDs. Once we implement this change, you'll have 6 months to update the IDs.

        </Warning>

        <Note>

        To use this API, your integration must act on behalf of a user that's a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.

        </Note>

        Get a list of the [brand templates](https://www.canva.com/help/publish-team-template/) the user has access to.
      operationId: listBrandTemplates
      security:
        - oauthAuthCode:
            - brandtemplate:meta:read
      tags:
        - brand_template
      x-rate-limit-per-client-user: 100
  /v1/brand-templates/{brandTemplateId}:
    get:
      description: |-
        <Warning>

        Later this year, we'll be updating all brand template IDs. If your integration stores brand template IDs, you'll need to migrate to the new IDs. Once we implement this change, you'll have 6 months to update the IDs.

        </Warning>

        <Note>

        To use this API, your integration must act on behalf of a user that's a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.

        </Note>

        Retrieves the metadata for a brand template.
      operationId: getBrandTemplate
      security:
        - oauthAuthCode:
            - brandtemplate:meta:read
      tags:
        - brand_template
      x-rate-limit-per-client-user: 100
  /v1/brand-templates/{brandTemplateId}/dataset:
    get:
      description: |-
        <Warning>

        Later this year, we'll be updating all brand template IDs. If your integration stores brand template IDs, you'll need to migrate to the new IDs. Once we implement this change, you'll have 6 months to update the IDs.

        </Warning>

        <Note>

        To use this API, your integration must act on behalf of a user that's a member of a [Canva Enterprise](https://www.canva.com/enterprise/) organization.

        </Note>

        Gets the dataset definition of a brand template. If the brand
        template contains autofill data fields, this API returns an object with the data field
        names and the type of data they accept.

        Available data field types include:

        - Images
        - Text
        - Charts

        You can autofill a brand template using the [Create a design autofill job
        API](https://www.canva.dev/docs/connect/api-reference/autofills/create-design-autofill-job/).

        WARNING: Chart data fields are a [preview feature](https://www.canva.dev/docs/connect/#preview-apis). There might be unannounced breaking changes to this feature which won't produce a new API version.
      operationId: getBrandTemplateDataset
      security:
        - oauthAuthCode:
            - brandtemplate:content:read
      tags:
        - brand_template
      x-rate-limit-per-client-user: 100
  /v1/comments:
    post:
      description: |-
        <Warning>

        This API is currently provided as a preview. Be aware of the following:

        - There might be unannounced breaking changes.
        - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
        - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.

        </Warning>

        Create a new top-level comment on a design.
        For information on comments and how they're used in the Canva UI, see the
        [Canva Help Center](https://www.canva.com/help/comments/). A design can have a maximum
        of 1000 comments.
      operationId: createComment
      security:
        - oauthAuthCode:
            - comment:write
      tags:
        - comment
      x-rate-limit-per-client-user: 20
  /v1/comments/{commentId}/replies:
    post:
      description: |-
        <Warning>

        This API is currently provided as a preview. Be aware of the following:

        - There might be unannounced breaking changes.
        - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
        - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.

        </Warning>

        Creates a reply to a comment in a design.
        To reply to an existing thread of comments, you can use either the `id` of the parent
        (original) comment, or the `thread_id` of a comment in the thread. Each comment can
        have a maximum of 100 replies created for it.

        For information on comments and how they're used in the Canva UI, see the
        [Canva Help Center](https://www.canva.com/help/comments/).
      operationId: createReply
      security:
        - oauthAuthCode:
            - comment:write
      tags:
        - comment
      x-rate-limit-per-client-user: 20
  /v1/designs/{designId}/comments/{commentId}:
    get:
      description: |-
        <Warning>

        This API is currently provided as a preview. Be aware of the following:

        - There might be unannounced breaking changes.
        - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
        - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.

        </Warning>

        Gets a comment.
        For information on comments and how they're used in the Canva UI, see the
        [Canva Help Center](https://www.canva.com/help/comments/).
      operationId: getComment
      security:
        - oauthAuthCode:
            - comment:read
      tags:
        - comment
      x-rate-limit-per-client-user: 100
  /v1/connect/keys:
    get:
      description: |-
        <Warning>

        This API is currently provided as a preview. Be aware of the following:

        - There might be unannounced breaking changes.
        - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
        - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.

        </Warning>

        The Keys API (`connect/keys`) is a security measure you can use to verify the authenticity
        of webhooks you receive from Canva Connect. The Keys API returns a
        [JSON Web Key (JWK)](https://www.rfc-editor.org/rfc/rfc7517#section-2), which you can use to
        decrypt the webhook signature and verify it came from Canva and not a potentially malicious
        actor. This helps to protect your systems from
        [Replay attacks](https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/).

        The keys returned by the Keys API can rotate. We recommend you cache the keys you receive
        from this API where possible, and only access this API when you receive a webhook signed
        with an unrecognized key. This allows you to verify webhooks quicker than accessing this API
        every time you receive a webhook.
      operationId: getSigningPublicKeys
      tags:
        - connect
  /v1/designs:
    get:
      description: |-
        Lists metadata for all the designs in a Canva user's
        [projects](https://www.canva.com/help/find-designs-and-folders/). You can also:

        - Use search terms to filter the listed designs.
        - Show designs either created by, or shared with the user.
        - Sort the results.
      operationId: listDesigns
      security:
        - oauthAuthCode:
            - design:meta:read
      tags:
        - design
      x-rate-limit-per-client-user: 100
    post:
      description: |-
        Creates a new Canva design. To create a new design, you can either:

        - Use a preset design type.
        - Set height and width dimensions for a custom design.

        Additionally, you can also provide the `asset_id` of an asset in the user's [projects](https://www.canva.com/help/find-designs-and-folders/) to add to the new design. Currently, this only supports image assets. To list the assets in a folder in the user's projects, use the [List folder items API](https://www.canva.dev/docs/connect/api-reference/folders/list-folder-items/).
      operationId: createDesign
      security:
        - oauthAuthCode:
            - design:content:write
      tags:
        - design
      x-rate-limit-per-client-user: 20
  /v1/designs/{designId}:
    get:
      description:
        "Gets the metadata for a design. This includes owner information,\
        \ URLs for editing and viewing, and thumbnail information."
      operationId: getDesign
      security:
        - oauthAuthCode:
            - design:meta:read
      tags:
        - design
      x-rate-limit-per-client-user: 100
  /v1/designs/{designId}/pages:
    get:
      description: |-
        <Warning>

        This API is currently provided as a preview. Be aware of the following:

        - There might be unannounced breaking changes.
        - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
        - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.

        </Warning>

        Lists metadata for pages in a design, such as page-specific thumbnails.

        For the specified design, you can provide `offset` and `limit` values to specify the range of pages to return.

        NOTE: Some design types don't have pages (for example, Canva docs).
      operationId: getDesignPages
      security:
        - oauthAuthCode:
            - design:content:read
      tags:
        - design
      x-rate-limit-per-client-user: 100
  /v1/designs/{designId}/export-formats:
    get:
      description: |-
        <Warning>

        This API is currently provided as a preview. Be aware of the following:

        - There might be unannounced breaking changes.
        - Any breaking changes to preview APIs won't produce a new [API version](https://www.canva.dev/docs/connect/versions/).
        - Public integrations that use preview APIs will not pass the review process, and can't be made available to all Canva users.

        </Warning>

        Lists the available file formats for [exporting a design](https://www.canva.dev/docs/connect/api-reference/exports/create-design-export-job/).
      operationId: getDesignExportFormats
      security:
        - oauthAuthCode:
            - design:content:read
      tags:
        - design
      x-rate-limit-per-client-user: 100
  /v1/imports:
    post:
      description: |-
        Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to import an external file as a new design in Canva.

        The request format for this endpoint has an `application/octet-stream` body of bytes,
        and the information about the import is provided using an `Import-Metadata` header.

        Supported file types for imports are listed in [Design imports overview](https://www.canva.dev/docs/connect/api-reference/design-imports/#supported-file-types).

        <Note>

        For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of design import jobs created with this API using the [Get design import job API](https://www.canva.dev/docs/connect/api-reference/design-imports/get-design-import-job/).

        </Note>
      operationId: createDesignImportJob
      security:
        - oauthAuthCode:
            - design:content:write
      tags:
        - design_import
      x-rate-limit-per-client-user: 20
  /v1/imports/{jobId}:
    get:
      description: |-
        Gets the result of a design import job created using the [Create design import job API](https://www.canva.dev/docs/connect/api-reference/design-imports/create-design-import-job/).

        You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
      operationId: getDesignImportJob
      security:
        - oauthAuthCode:
            - design:content:write
      tags:
        - design_import
      x-rate-limit-per-client-user: 120
  /v1/exports:
    post:
      description: |-
        Starts a new [asynchronous job](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints) to export a file from Canva. Once the exported file is generated, you can download
        it using the link(s) provided.

        The request requires the design ID and the exported file format type.

        Supported file formats (and export file type values): PDF (`pdf`), JPG (`jpg`), PNG (`png`), GIF (`gif`), Microsoft PowerPoint (`pptx`), and MP4 (`mp4`).

        <Note>

        For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints). You can check the status and get the results of export jobs created with this API using the [Get design export job API](https://www.canva.dev/docs/connect/api-reference/exports/get-design-export-job/).

        </Note>
      operationId: createDesignExportJob
      security:
        - oauthAuthCode:
            - design:content:read
      tags:
        - export
      x-rate-limit-per-client-user: 20
  /v1/exports/{exportId}:
    get:
      description: |-
        Gets the result of a design export job that was created using the [Create design export job API](https://www.canva.dev/docs/connect/api-reference/exports/create-design-export-job/).

        If the job is successful, the response includes an array
        of download links for each page of the design.

        You might need to make multiple requests to this endpoint until you get a `success` or `failed` status. For more information on the workflow for using asynchronous jobs, see [API requests and responses](https://www.canva.dev/docs/connect/api-requests-responses/#asynchronous-job-endpoints).
      operationId: getDesignExportJob
      security:
        - oauthAuthCode:
            - design:content:read
      tags:
        - export
      x-rate-limit-per-client-user: 120
  /v1/folders/{folderId}:
    delete:
      description: |-
        Deletes a folder with the specified `folderID`.
        Deleting a folder moves the user's content in the folder to the
        [Trash](https://www.canva.com/help/deleted-designs/) and content owned by
        other users is moved to the top level of the owner's
        [projects](https://www.canva.com/help/find-designs-and-folders/).
      operationId: deleteFolder
      security:
        - oauthAuthCode:
            - folder:write
      tags:
        - folder
      x-rate-limit-per-client-user: 20
    get:
      description: Gets the name and other details of a folder using a folder's `folderID`.
      operationId: getFolder
      security:
        - oauthAuthCode:
            - folder:read
      tags:
        - folder
      x-rate-limit-per-client-user: 100
    patch:
      description: |-
        Updates a folder's details using its `folderID`.
        Currently, you can only update a folder's name.
      operationId: updateFolder
      security:
        - oauthAuthCode:
            - folder:write
      tags:
        - folder
      x-rate-limit-per-client-user: 20
  /v1/folders/{folderId}/items:
    get:
      description: |-
        Lists the items in a folder, including each item's `type`.

        Folders can contain:

        - Other folders.
        - Designs, such as Instagram posts, Presentations, and Documents ([Canva Docs](https://www.canva.com/create/documents/)).
        - Image assets.

        Currently, video assets are not returned in the response.
      operationId: listFolderItems
      security:
        - oauthAuthCode:
            - folder:read
      tags:
        - folder
      x-rate-limit-per-client-user: 100
  /v1/folders/move:
    post:
      description: |-
        Moves an item to another folder. You must specify the folder ID of the destination folder, as well as the ID of the item you want to move.

        NOTE: In some situations, a single item can exist in multiple folders. If you attempt to move an item that exists in multiple folders, the API returns an `item_in_multiple_folders` error. In this case, you must use the Canva UI to move the item to another folder.
      operationId: moveFolderItem
      security:
        - oauthAuthCode:
            - folder:write
      tags:
        - folder
      x-rate-limit-per-client-user: 100
  /v1/folders:
    post:
      description: |-
        Creates a folder in either the top level of a Canva user's
        [projects](https://www.canva.com/help/find-designs-and-folders/) (using the ID `root`), or
        another folder (using the parent folder's ID). When a folder is successfully created, the
        endpoint returns its folder ID, along with other information.
      operationId: createFolder
      security:
        - oauthAuthCode:
            - folder:write
      tags:
        - folder
      x-rate-limit-per-client-user: 20
  /v1/oauth/token:
    post:
      description: |-
        This endpoint implements the OAuth 2.0 `token` endpoint, as part of the Authorization Code flow with Proof Key for Code Exchange (PKCE). For more information, see [Authentication](https://www.canva.dev/docs/connect/authentication/).

        To generate an access token, you must provide one of the following:

        - An authorization code
        - A refresh token

        Generating a token using either an authorization code or a refresh token allows your integration to act on behalf of a user. You must first [obtain user authorization and get an authorization code](https://www.canva.dev/docs/connect/authentication/#obtain-user-authorization).

        Access tokens may be up to 4 KB in size, and are only valid for a specified period of time. The expiry time (currently 4 hours) is shown in the endpoint response and is subject to change.

        **Endpoint authentication**

        Requests to this endpoint require authentication with your client ID and client secret, using _one_ of the following methods:

        - **Basic access authentication** (Recommended): For [basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), the `{credentials}` string must be a Base64 encoded value of `{client id}:{client secret}`.
        - **Body parameters**: Provide your integration's credentials using the `client_id` and `client_secret` body parameters.

        This endpoint can't be called from a user's web-browser client because it uses client authentication with client secrets. Requests must come from your integration's backend, otherwise they'll be blocked by Canva's [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy.

        **Generate an access token using an authorization code**

        To generate an access token with an authorization code, you must:

        - Set `grant_type` to `authorization_code`.
        - Provide the `code_verifier` value that you generated when creating the user authorization URL.
        - Provide the authorization code you received after the user authorized the integration.

        **Generate an access token using a refresh token**

        Using the `refresh_token` value from a previous user token request, you can get a new access token with the same or smaller scope as the previous one, but with a refreshed expiry time. You will also receive a new refresh token that you can use to refresh the access token again.

        To refresh an existing access token, you must:

        - Set `grant_type` to `refresh_token`.
        - Provide the `refresh_token` from a previous token request.
      operationId: exchangeAccessToken
      security:
        - {}
        - basicAuth: []
      tags:
        - oauth
  /v1/oauth/introspect:
    post:
      description: |-
        Introspect an access token to see whether it is valid and active. You can also verify some token properties, such as its claims, scopes, and validity times.

        Requests to this endpoint require authentication with your client ID and client secret, using _one_ of the following methods:

        - **Basic access authentication** (Recommended): For [basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), the `{credentials}` string must be a Base64 encoded value of `{client id}:{client secret}`.
        - **Body parameters**: Provide your integration's credentials using the `client_id` and `client_secret` body parameters.

        This endpoint can't be called from a user's web-browser client because it uses client authentication with client secrets. Requests must come from your integration's backend, otherwise they'll be blocked by Canva's [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy.
      operationId: introspectToken
      security:
        - {}
        - basicAuth: []
      tags:
        - oauth
  /v1/oauth/revoke:
    post:
      description: |-
        Revoke an access token or a refresh token.

        If you revoke a _refresh token_, be aware that:

        - The refresh token's lineage is also revoked. This means that access tokens created from that refresh token are also revoked.
        - The user's consent for your integration is also revoked. This means that the user must go through the OAuth process again to use your integration.

        Requests to this endpoint require authentication with your client ID and client secret, using _one_ of the following methods:

        - **Basic access authentication** (Recommended): For [basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), the `{credentials}` string must be a Base64 encoded value of `{client id}:{client secret}`.
        - **Body parameters**: Provide your integration's credentials using the `client_id` and `client_secret` body parameters.

        This endpoint can't be called from a user's web-browser client because it uses client authentication with client secrets. Requests must come from your integration's backend, otherwise they'll be blocked by Canva's [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy.
      operationId: revokeTokens
      security:
        - {}
        - basicAuth: []
      tags:
        - oauth
  /v1/users/me:
    get:
      description: |-
        Returns the User ID, Team ID, and display name of the user
        account associated with the provided access token.
      operationId: usersMe
      security:
        - oauthAuthCode: []
      tags:
        - user
      x-rate-limit-per-client-user: 10
  /v1/users/me/profile:
    get:
      description:
        "Currently, this returns the display name of the user account associated\
        \ with the provided access token. More user information is expected to be\
        \ included in the future."
      operationId: getUserProfile
      security:
        - oauthAuthCode:
            - profile:read
      tags:
        - user
      x-rate-limit-per-client-user: 10
components:
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http
    oauthAuthCode:
      flows:
        authorizationCode:
          authorizationUrl: https://www.canva.com/api/oauth/authorize
          scopes:
            app:read:
              "View [Canva app](https://www.canva.dev/docs/connect/canva-concepts/#canva-apps)\
              \ metadata."
            app:write:
              "Create, update, or remove [Canva apps](https://www.canva.dev/docs/connect/canva-concepts/#canva-apps)\
              \ on the user's behalf."
            design:content:read: View the contents of the user's designs.
            design:meta:read: View the metadata of the user's designs.
            design:content:write: Create designs on the user's behalf.
            design:permission:read: View the permissions assigned to a user's designs.
            design:permission:write:
              "Set, update, or remove the permissions assigned\
              \ to the user's designs."
            folder:read: |-
              View the metadata and contents of the user's folders, including their **Projects**
              folder.
            folder:write: |-
              Add, move, or remove the user's folders. It also lets you edit folder metadata,
              such as the folder's name.
            folder:permission:read: View permissions assigned to a user's folders.
            folder:permission:write:
              "Set, update, or remove permissions assigned\
              \ to the user's folders."
            asset:read:
              "View the metadata for the user's assets, such as uploaded\
              \ images."
            asset:write: "Upload, update, or delete assets on the user's behalf."
            comment:read:
              "View the comments on the user's designs, and the associated\
              \ metadata."
            comment:write: Create comments and replies on the user's designs.
            collaboration:event:
              Receive webhook notifications about events relevant
              to the user.
            brandtemplate:meta:read:
              View the metadata of the brand templates associated
              with the user's brand.
            brandtemplate:content:read:
              Read the content of the brand templates associated
              with the user's brand.
            profile:read: Read a user's profile and account information.
          tokenUrl: https://api.canva.com/rest/v1/oauth/token
      type: oauth2