import type { AICommand } from "./types";

// Commands that ship with the extension. Users can edit them; "Reset" brings
// the original back. Ids are stable so hotkeys and quicklinks keep working.
const t = 0;

const NO_FLUFF = "Reply with the resulting text only. No preamble, no explanation, no quotes, no code fences.";

export const PRESETS: AICommand[] = [
  {
    id: "fix-spelling",
    title: "Fix Spelling and Grammar",
    icon: "Check",
    provider: "openai",
    mode: "preview",
    preset: true,
    createdAt: t,
    updatedAt: t,
    prompt: [
      "Fix spelling, grammar and punctuation in the text.",
      "Keep the original meaning, tone, language, and formatting (line breaks, markdown, lists).",
      "Do not rewrite sentences unless it is needed to fix an error.",
      NO_FLUFF,
      "",
      "Text:",
      "{selection}",
    ].join("\n"),
  },
  {
    id: "improve-writing",
    title: "Improve Writing",
    icon: "Wand",
    provider: "openai",
    mode: "preview",
    preset: true,
    createdAt: t,
    updatedAt: t,
    prompt: [
      "Act as a spelling corrector, content writer, and text improver/editor. Reply to each message only with the rewritten text",
      "",
      "Strictly follow these rules:",
      "- Correct spelling, grammar, and punctuation errors in the given text",
      "- Enhance clarity and conciseness without altering the original meaning",
      "- Divide lengthy sentences into shorter, more readable ones",
      "- Eliminate unnecessary repetition while preserving important points",
      "- Prioritize active voice over passive voice for a more engaging tone",
      "- Opt for simpler, more accessible vocabulary when possible",
      "- ALWAYS ensure the original meaning and intention of the given text",
      "- ALWAYS detect and maintain the original language of the text",
      "- ALWAYS maintain the existing tone of voice and style, e.g. formal, casual, polite, etc.",
      "- NEVER surround the improved text with quotes or any additional formatting",
      "- STRICTLY DON'T use em dashes in the sentences nor semicolon.",
      "- If the text is already well-written and requires no improvement, don't change the given text",
      "",
      "Text to improve:",
      "{selection}",
    ].join("\n"),
  },
  {
    id: "rewrite",
    title: "Rewrite",
    icon: "Pencil",
    provider: "openai",
    mode: "preview",
    preset: true,
    createdAt: t,
    updatedAt: t,
    prompt: [
      "Act as a spelling corrector, content writer, and text improver/editor. Reply to each message only with the rewritten text",
      "- Rewrite/Paraphrase the below given text",
      "- Correct spelling, grammar, and punctuation errors in the given text",
      "- Enhance clarity and conciseness without altering the original meaning",
      "- Prioritize active voice over passive voice for a more engaging tone",
      "- NEVER surround the improved text with quotes or any additional formatting",
      "- ALWAYS maintain the existing tone of voice and style, e.g. formal, casual, polite, etc.",
      "",
      "Text:",
      "{selection}",
    ].join("\n"),
  },
  {
    id: "clean-text",
    title: "Clean Text",
    icon: "Eraser",
    provider: "anthropic",
    mode: "preview",
    preset: true,
    createdAt: t,
    updatedAt: t,
    prompt: [
      "Revise the writing of {selection}. Add text where necessary, correct spelling errors, eliminate unnecessary words and phrases, and combine sentences where effective for conciseness. Generate the revised version without quotations or explanations.",
      "STRICTLY don't use em dash in your response",
    ].join("\n"),
  },
  {
    id: "make-shorter",
    title: "Make Shorter",
    icon: "ShortParagraph",
    provider: "openai",
    mode: "preview",
    preset: true,
    createdAt: t,
    updatedAt: t,
    prompt: [
      "Make the text shorter. Keep the key points, the tone and the language. Remove filler.",
      NO_FLUFF,
      "",
      "Text:",
      "{selection}",
    ].join("\n"),
  },
  {
    id: "make-longer",
    title: "Make Longer",
    icon: "Paragraph",
    provider: "openai",
    mode: "preview",
    preset: true,
    createdAt: t,
    updatedAt: t,
    prompt: [
      "Expand the text with more detail and context. Keep the tone, the language and the intent.",
      NO_FLUFF,
      "",
      "Text:",
      "{selection}",
    ].join("\n"),
  },
  {
    id: "summarize",
    title: "Summarize",
    icon: "BulletPoints",
    provider: "openai",
    mode: "preview",
    preset: true,
    createdAt: t,
    updatedAt: t,
    prompt: [
      "Summarize the text in one short paragraph followed by up to five bullet points with the key facts.",
      "Use the same language as the text.",
      "",
      "Text:",
      "{selection}",
    ].join("\n"),
  },
  {
    id: "explain",
    title: "Explain This",
    icon: "LightBulb",
    provider: "openai",
    mode: "preview",
    preset: true,
    createdAt: t,
    updatedAt: t,
    prompt: [
      "Explain the text in simple words, like to a smart friend who is new to the topic. Be short.",
      "",
      "Text:",
      "{selection}",
    ].join("\n"),
  },
];

export function presetById(id: string): AICommand | undefined {
  return PRESETS.find((p) => p.id === id);
}
