import { Icon } from "@raycast/api";

const icons = {
  AppWindowLeft: Icon.AppWindowSidebarLeft,
  AppWindowRight: Icon.AppWindowSidebarRight,
  AppWindowGrid: Icon.AppWindowGrid2x2,
  AppWindowList: Icon.AppWindowList,
  ArrowLeft: Icon.ArrowLeftCircleFilled,
  ArrowRight: Icon.ArrowRightCircleFilled,
  ArrowUp: Icon.ArrowUpCircleFilled,
  ArrowDown: Icon.ArrowDownCircleFilled,
  Bluetooth: Icon.Bluetooth,
  Brightness: Icon.Sun,
  Clipboard: Icon.Clipboard,
  Close: Icon.XMarkCircleFilled,
  Code: Icon.CodeBlock,
  Contrast: Icon.Contrast,
  Desktop: Icon.Desktop,
  Dot: Icon.Dot,
  Eject: Icon.Eject,
  EyeDisabled: Icon.EyeDisabled,
  Ellipsis: Icon.Ellipsis,
  Finder: Icon.Finder,
  Forward: Icon.ForwardFilled,
  Gear: Icon.Gear,
  Image: Icon.Image,
  Info: Icon.Info,
  Keyboard: Icon.Keyboard,
  House: Icon.House,
  Link: Icon.Link,
  Logout: Icon.Logout,
  Lock: Icon.Lock,
  LockUnlocked: Icon.LockUnlocked,
  Maximize: Icon.Maximize,
  Microphone: Icon.Microphone,
  MicrophoneDisabled: Icon.MicrophoneDisabled,
  Minimize: Icon.Minimize,
  Minus: Icon.Minus,
  Monitor: Icon.Monitor,
  Mouse: Icon.Mouse,
  Moon: Icon.Moon,
  Pause: Icon.Pause,
  Play: Icon.Play,
  Plus: Icon.Plus,
  Redo: Icon.Redo,
  Rewind: Icon.RewindFilled,
  Sleep: Icon.Moon,
  Stop: Icon.Stop,
  Terminal: Icon.Terminal,
  Trash: Icon.Trash,
  VolumeDown: Icon.SpeakerDown,
  VolumeUp: Icon.SpeakerUp,
  Window: Icon.Window,
};

export default icons;
