export interface VariableDefinition {
  category: "Context" | "Dynamic" | "Persistent";
  description?: string;
  name: string;
  persistent: boolean;
  readOnly: boolean;
}

const DYNAMIC_VARIABLES = [
  "selected_text",
  "BTTActiveWindowTitle",
  "ActiveSpace",
  "OutputVolume",
  "BuiltInDisplayBrightness",
  "BTTCurrentlyPlaying",
  "BTTNowPlayingInfoArtist",
  "BTTNowPlayingInfoTitle",
  "BTTNowPlayingInfoAlbum",
  "BTTNowPlayingInfoDuration",
  "BTTNowPlayingInfoTrackNumber",
  "BTTTouchBarVisible",
  "BTTCurrentlyPlayingApp",
  "BTTInternalNightShiftState",
  "SystemDoNotDisturbState",
  "BTTActiveAppBundleIdentifier",
  "BTTActiveWindowNumber",
  "BTTTouchBarHasPhysicalESCKey",
  "BTTLastTriggeredAction",
  "BTTLastTriggeredUUID",
  "BTTLastTriggerTime",
];

const CONTEXT_VARIABLES = [
  "color_under_cursor",
  "focused_element_role",
  "focused_element_subrole",
  "connected_wifi_name",
  "active_website_url",
  "focused_window_title",
  "focused_window_app_name",
  "active_app_name",
  "active_app_bundle_identifier",
  "left_mouse_down",
  "middle_mouse_down",
  "right_mouse_down",
  "currently_pressed_mouse_buttons",
  "currently_pressed_keyboard_keys",
  "trackpad_id",
  "fingers_touching_trackpad",
  "trackpad_touch_duration",
  "thumb_recognized",
  "thumb_x_percent",
  "thumb_y_percent",
  "leftmost_touch_x",
  "leftmost_touch_y",
  "rightmost_touch_x",
  "rightmost_touch_y",
  "leftmost_rightmost_touch_distance_percent",
  "fingers_touching_magic_mouse",
  "magic_mouse_touch_duration",
  "leftmost_mouse_touch_x",
  "leftmost_mouse_touch_y",
  "rightmost_mouse_touch_x",
  "rightmost_mouse_touch_y",
  "leftmost_rightmost_mouse_touch_distance_percent",
  "mouse_position_x",
  "mouse_position_y",
  "mouse_pos_percent_x",
  "mouse_pos_percent_y",
  "window_titlebar_hovered",
  "dist_x_active_win_top_left",
  "dist_y_active_win_top_left",
  "dist_x_active_win_top_right",
  "dist_y_active_win_top_right",
  "dist_x_active_win_bottom_left",
  "dist_y_active_win_bottom_left",
  "dist_x_active_win_bottom_right",
  "dist_y_active_win_bottom_right",
  "percent_x_active_win_btm_left",
  "percent_y_active_win_btm_left",
  "percent_x_hovered_win_btm_left",
  "percent_y_hovered_win_btm_left",
  "mouse_screen_x",
  "mouse_screen_y",
  "mouse_screen_width",
  "mouse_screen_height",
  "focused_screen_x",
  "focused_screen_y",
  "focused_screen_width",
  "focused_screen_height",
  "focused_window_x",
  "focused_window_y",
  "focused_window_width",
  "focused_window_height",
  "hovered_floating_menu_identifier",
  "visible_floating_menu_identifiers",
  "hovered_app_bundle_identifier",
  "hovered_app_name",
  "fullscreen_active",
  "active_screen_resolutions",
  "missioncontrol_active",
  "currently_blocking_keyboard",
  "power_source",
  "battery_level",
  "active_space",
  "darkmode_active",
  "ignore_builtin_trackpad_active",
  "current_minute",
  "current_hour",
  "current_day",
  "current_weekday",
  "runningProcesses",
  "appExecutablePath",
  "activeTouchBarGroup",
  "currentlyPressedStreamDeckButtonIdentifiers",
  "mouseBehindNotch",
  "pinned_window_ids",
  "BTTLastTerminalCommandResult",
  "BTTMagicMouseTouchpadModeActive",
  "BTTSiriRemoteMouseModeActive",
  "BTTFinderContextMenuTriggeredUUID",
  "BTTFinderContextMenuTargetPath",
  "BTTFinderContextMenuSelectedItemPaths",
  "CurrentKeyboardInputSource",
];

const WRITABLE_VARIABLES = new Set(["OutputVolume", "BuiltInDisplayBrightness", "SystemDoNotDisturbState"]);

const DESCRIPTIONS: Record<string, string> = {
  selected_text: "Currently selected text",
  BTTActiveWindowTitle: "Title of the active window",
  ActiveSpace: "ID of the active Space",
  OutputVolume: "Current system output volume",
  BuiltInDisplayBrightness: "Brightness of the built-in display",
  BTTCurrentlyPlaying: "Whether the system is currently playing media",
  BTTCurrentlyPlayingApp: "Bundle identifier of the app currently playing media",
  BTTActiveAppBundleIdentifier: "Bundle identifier of the active app",
  SystemDoNotDisturbState: "Current Do Not Disturb state",
  battery_level: "Current battery level",
  connected_wifi_name: "Name of the connected Wi-Fi network",
  darkmode_active: "Whether macOS Dark Mode is active",
};

export const STANDARD_VARIABLES: VariableDefinition[] = [
  ...DYNAMIC_VARIABLES.map((name): VariableDefinition => ({
    name,
    category: "Dynamic",
    description: DESCRIPTIONS[name],
    persistent: false,
    readOnly: !WRITABLE_VARIABLES.has(name),
  })),
  ...CONTEXT_VARIABLES.map((name): VariableDefinition => ({
    name,
    category: "Context",
    description: DESCRIPTIONS[name],
    persistent: false,
    readOnly: true,
  })),
];
