export function htmlToMarkdown(rawHtml: any, title: any) {
  const formattedContent = rawHtml
    .replaceAll("<div>", "")
    .replaceAll('<div class="">', "")
    .replaceAll("</div>", "")
    .replaceAll("<p>", "\n")
    .replaceAll("</p>", "\n")
    .replaceAll("<code>", "`")
    .replaceAll("</code>", "`")
    .replaceAll("<pre>", "``` ")
    .replaceAll("</pre>", "```  ")
    .replaceAll("<h1>", "# ")
    .replaceAll("</h1>", "\n\n")
    .replaceAll("<h2>", "## ")
    .replaceAll("</h2>", "\n\n")
    .replaceAll("<h3>", "### ")
    .replaceAll("</h3>", "\n\n")
    .replaceAll("<h4>", "#### ")
    .replaceAll("</h4>", "\n\n")
    .replaceAll("<h5>", "##### ")
    .replaceAll("</h5>", "\n\n")
    .replaceAll("<h6>", "###### ")
    .replaceAll("</h6>", "\n\n")
    .replaceAll("<strong>", "**")
    .replaceAll("</strong>", "**")
    .replaceAll("<em>", "_")
    .replaceAll("</em>", "_")
    .replaceAll("New:", "\n New:")
    .replaceAll("Old:", "\n Old:")
    .replaceAll(/<a.*?href="(.*?)".*?>(.*?)<\/a>/g, "[$2]($1)");
  return `## ${title}\n\n  ---  ${formattedContent}`;
}
