import type { Icon } from "@raycast/api";

// Semantic aliases from raycast/raycast-clients#8496, with the subsequent keyword cleanup.
// Keys use SDK asset values because public names can differ (e.g. Bubble uses speech-bubble).
// Keep these aliases in sync when updating the SDK icon catalog. Number icons have no aliases.
export const iconKeywords: Record<Icon, string[]> = {
  "add-person-16": ["invite", "user", "contact"],
  "airplane-16": ["flight", "travel", "aviation"],
  "airplane-filled-16": ["flight", "travel", "aviation"],
  "airplane-landing-16": ["arrival", "flight", "travel"],
  "airplane-takeoff-16": ["departure", "flight", "travel"],
  "airpods-16": ["earbuds", "headphones", "audio"],
  "alarm-16": ["reminder", "wake up", "timer"],
  "alarm-ringing-16": ["reminder", "wake up", "timer"],
  "align-centre-16": ["center", "text alignment"],
  "align-left-16": ["text alignment", "paragraph"],
  "align-right-16": ["text alignment", "paragraph"],
  "american-football-16": ["sport", "nfl", "rugby"],
  "anchor-16": ["nautical", "harbor", "ship"],
  "app-window-16": ["application", "desktop", "layout"],
  "app-window-grid-2x2-16": ["application", "desktop", "layout"],
  "app-window-grid-3x3-16": ["application", "desktop", "layout"],
  "app-window-list-16": ["application", "desktop", "layout"],
  "app-window-sidebar-left-16": ["application", "desktop", "layout"],
  "app-window-sidebar-right-16": ["application", "desktop", "layout"],
  "arrow-clockwise-16": ["refresh", "reload", "rotate"],
  "arrow-counter-clockwise-16": ["history", "undo", "restore"],
  "arrow-down-16": ["south", "descend", "below"],
  "arrow-down-circle-16": ["south", "descend", "below"],
  "arrow-down-circle-filled-16": ["south", "descend", "below"],
  "arrow-left-16": ["back", "previous", "west"],
  "arrow-left-circle-16": ["back", "previous", "west"],
  "arrow-left-circle-filled-16": ["back", "previous", "west"],
  "arrow-ne-16": ["northeast", "diagonal", "external"],
  "arrow-right-16": ["next", "forward", "east"],
  "arrow-right-circle-16": ["next", "forward", "east"],
  "arrow-right-circle-filled-16": ["next", "forward", "east"],
  "arrow-up-16": ["north", "ascend", "above"],
  "arrow-up-circle-16": ["north", "ascend", "above"],
  "arrow-up-circle-filled-16": ["north", "ascend", "above"],
  "arrows-contract-16": ["collapse", "minimize", "shrink"],
  "arrows-expand-16": ["fullscreen", "maximize", "resize"],
  "at-symbol-16": ["email", "mention", "address"],
  "band-aid-16": ["plaster", "first aid", "healing"],
  "bank-note-16": ["cash", "money", "currency"],
  "bar-chart-16": ["analytics", "statistics", "graph"],
  "bar-code-16": ["barcode", "scan"],
  "bath-tub-16": ["bathroom", "wash", "shower"],
  "battery-16": ["power", "energy", "charge"],
  "battery-charging-16": ["power", "energy", "charge"],
  "battery-disabled-16": ["power", "energy", "charge"],
  "bell-16": ["notification", "alert", "reminder"],
  "bell-disabled-16": ["mute", "silent", "do not disturb"],
  "bike-16": ["bicycle", "cycling", "transport"],
  "binoculars-16": ["explore", "discover", "look"],
  "bird-16": ["animal", "wildlife", "flying"],
  "blank-document-16": ["file", "page", "paper"],
  "bluetooth-16": ["wireless", "pairing", "connection"],
  "boat-16": ["ship", "sailing", "transport"],
  "bold-16": ["font", "typography", "formatting"],
  "bolt-16": ["lightning", "electricity", "energy"],
  "bolt-disabled-16": ["lightning", "electricity", "energy"],
  "book-16": ["read", "library", "documentation"],
  "bookmark-16": ["save", "favorite", "reading"],
  "box-16": ["package", "parcel", "storage"],
  "brush-16": ["paint", "art", "drawing"],
  "speech-bubble-16": ["chat", "message", "conversation"],
  "bug-16": ["issue", "error", "debugging"],
  "building-16": ["office", "company", "city"],
  "bullet-points-16": ["unordered list", "text", "formatting"],
  "bulls-eye-16": ["target", "aim", "goal"],
  "bulls-eye-missed-16": ["target", "failure", "aim"],
  "buoy-16": ["help", "support", "rescue"],
  "calculator-16": ["math", "arithmetic", "calculation"],
  "calendar-16": ["date", "event", "schedule"],
  "camera-16": ["photography", "capture"],
  "car-16": ["vehicle", "driving", "transport"],
  "cart-16": ["shopping", "basket", "checkout"],
  "cd-16": ["disc", "disk", "music"],
  "center-16": ["centre", "align", "position"],
  "check-16": ["done", "complete", "tick"],
  "check-circle-16": ["done", "complete", "tick"],
  "check-list-16": ["todo", "tasks", "checklist"],
  "check-rosette-16": ["verified", "badge", "certificate"],
  "checkmark-16": ["done", "complete", "tick"],
  "chess-piece-16": ["game", "strategy", "pawn"],
  "chevron-down-16": ["expand", "dropdown", "disclosure"],
  "chevron-down-small-16": ["expand", "dropdown", "disclosure"],
  "chevron-left-16": ["back", "previous", "navigation"],
  "chevron-left-small-16": ["back", "previous", "navigation"],
  "chevron-right-16": ["next", "forward", "disclosure"],
  "chevron-right-small-16": ["next", "forward", "disclosure"],
  "chevron-up-16": ["collapse", "navigation"],
  "chevron-up-down-16": ["sort", "dropdown", "select"],
  "chevron-up-small-16": ["collapse", "navigation"],
  "circle-16": ["round", "shape", "ring"],
  "circle-disabled-16": ["prohibited", "banned", "no"],
  "circle-ellipsis-16": ["more", "options", "menu"],
  "circle-filled-16": ["round", "shape", "ring"],
  "circle-progress-16": ["loading", "status", "completion"],
  "circle-progress-100-16": ["loading", "status", "completion"],
  "circle-progress-25-16": ["loading", "status", "completion"],
  "circle-progress-50-16": ["loading", "status", "completion"],
  "circle-progress-75-16": ["loading", "status", "completion"],
  "clear-formatting-16": ["plain text", "reset", "typography"],
  "copy-clipboard-16": ["copy", "paste", "clipboard"],
  "clock-16": ["time", "history", "recent"],
  "cloud-16": ["weather", "online", "storage"],
  "cloud-lightning-16": ["thunderstorm", "weather"],
  "cloud-rain-16": ["rainy", "weather", "precipitation"],
  "cloud-snow-16": ["snowy", "winter", "weather"],
  "cloud-sun-16": ["partly cloudy", "weather"],
  "code-16": ["programming", "developer", "source"],
  "code-block-16": ["programming", "syntax", "snippet"],
  "cog-16": ["settings", "preferences", "gear"],
  "coin-16": ["money", "currency", "payment"],
  "coins-16": ["money", "currency", "credits"],
  "command-symbol-16": ["cmd", "keyboard", "shortcut"],
  "compass-16": ["navigation", "direction", "explore"],
  "computer-chip-16": ["cpu", "processor", "hardware"],
  "contrast-16": ["appearance", "brightness", "display"],
  "credit-card-16": ["payment", "billing", "bank"],
  "cricket-ball-16": ["sport", "cricket", "game"],
  "crop-16": ["resize", "trim", "image"],
  "crown-16": ["royal", "premium", "king"],
  "crypto-16": ["cryptocurrency", "bitcoin", "blockchain"],
  "delete-document-16": ["remove file", "erase", "page"],
  "desktop-16": ["computer", "screen", "workspace"],
  "devices-16": ["hardware", "computer", "phone"],
  "dna-16": ["genetics", "biology", "science"],
  "dot-16": ["point", "bullet", "status"],
  "download-16": ["save", "transfer", "receive"],
  "droplets-16": ["water", "liquid", "rain"],
  "duplicate-16": ["copy", "clone", "repeat"],
  "edit-shape-16": ["vector", "drawing", "design"],
  "eject-16": ["unmount", "disconnect", "remove disk"],
  "ellipsis-16": ["more", "options", "menu"],
  "ellipsis-vertical-16": ["more", "options", "menu"],
  "emoji-16": ["smiley", "happy", "face"],
  "emoji-sad-16": ["unhappy", "frown", "face"],
  "envelope-16": ["email", "message", "letter"],
  "eraser-16": ["erase", "remove", "clear"],
  "important-01-16": ["priority", "alert", "attention"],
  "exclamationmark-16": ["alert", "important", "attention"],
  "exclamationmark-2-16": ["alert", "important", "attention"],
  "exclamationmark-3-16": ["alert", "important", "attention"],
  "eye-16": ["visible", "preview"],
  "eye-disabled-16": ["hidden", "invisible", "hide"],
  "eye-dropper-16": ["color picker", "colour", "sample"],
  "female-16": ["woman", "gender", "venus"],
  "film-strip-16": ["movie", "cinema", "video"],
  "filter-16": ["funnel", "refine", "narrow"],
  "finder-16": ["files", "file manager", "macos"],
  "fingerprint-16": ["biometric", "authentication", "identity"],
  "flag-16": ["mark", "report", "milestone"],
  "folder-16": ["directory", "files", "organization"],
  "footprints-16": ["walking", "steps", "trail"],
  "forward-16": ["fast forward", "media", "skip"],
  "forward-filled-16": ["fast forward", "media", "skip"],
  "fountain-tip-16": ["pen", "writing", "calligraphy"],
  "full-signal-16": ["reception", "connection", "strength"],
  "game-controller-16": ["gaming", "joystick", "console"],
  "gauge-16": ["speed", "performance", "meter"],
  "geopin-16": ["location", "map", "place", "address"],
  "germ-16": ["bacteria", "virus", "infection"],
  "gift-16": ["present", "birthday", "reward"],
  "glasses-16": ["reading", "spectacles", "vision"],
  "globe-01-16": ["world", "earth", "international", "web"],
  "goal-16": ["target", "objective", "milestone"],
  "hammer-16": ["build", "tools", "construction"],
  "hard-drive-16": ["disk", "storage", "backup"],
  "hashtag-16": ["number sign", "tag", "channel"],
  "heading-16": ["title", "typography", "formatting"],
  "headphones-16": ["audio", "music", "listening"],
  "heart-16": ["love", "favorite", "like"],
  "heart-disabled-16": ["unfavorite", "unlike", "broken heart"],
  "heartbeat-16": ["pulse", "health", "cardiology"],
  "highlight-16": ["marker", "emphasize", "text"],
  "hourglass-16": ["waiting", "time", "pending"],
  "house-16": ["home", "residence", "start"],
  "humidity-16": ["moisture", "weather", "water"],
  "image-16": ["photo", "picture", "landscape"],
  "info-01-16": ["information", "about", "help"],
  "italics-16": ["italic", "typography", "formatting"],
  "key-16": ["password", "access", "credential"],
  "keyboard-16": ["typing", "hotkey", "shortcut"],
  "layers-16": ["stack", "design", "overlay"],
  "leaderboard-16": ["ranking", "score", "competition"],
  "leaf-16": ["nature", "plant", "environment"],
  "signal-2-16": ["reception", "connection", "strength"],
  "light-bulb-16": ["idea", "inspiration", "lighting"],
  "light-bulb-off-16": ["dark", "lighting", "idea"],
  "line-chart-16": ["analytics", "trend", "graph"],
  "link-16": ["url", "hyperlink", "chain"],
  "livestream-01-16": ["broadcast", "live", "streaming"],
  "livestream-disabled-01-16": ["broadcast", "live", "streaming"],
  "lock-16": ["security", "privacy", "password"],
  "lock-disabled-16": ["insecure", "protection off"],
  "lock-unlocked-16": ["unlock", "access", "open"],
  "logout-16": ["sign out", "exit", "leave"],
  "lorry-16": ["truck", "delivery", "transport"],
  "lowercase-16": ["small letters", "text", "typography"],
  "magnifying-glass-16": ["search", "find", "lookup"],
  "male-16": ["man", "gender", "mars"],
  "map-16": ["navigation", "directions", "geography"],
  "mask-16": ["theater", "disguise", "anonymous"],
  "maximize-16": ["fullscreen", "expand", "enlarge"],
  "medical-support-16": ["health", "hospital", "first aid"],
  "megaphone-16": ["announcement", "broadcast", "marketing"],
  "memory-stick-16": ["usb", "flash drive", "storage"],
  "microphone-16": ["mic", "recording", "dictation"],
  "microphone-disabled-16": ["mute", "mic off", "silent"],
  "minimize-16": ["shrink", "collapse", "window"],
  "minus-16": ["subtract", "remove", "decrease"],
  "minus-circle-16": ["subtract", "remove", "decrease"],
  "minus-circle-filled-16": ["subtract", "remove", "decrease"],
  "mobile-16": ["smartphone", "iphone"],
  "monitor-16": ["display", "screen", "computer"],
  "moon-16": ["night", "dark mode", "sleep"],
  "moon-down-16": ["moonset", "night", "astronomy"],
  "moon-up-16": ["moonrise", "night", "astronomy"],
  "moonrise-16": ["night", "astronomy", "horizon"],
  "mountain-16": ["hiking", "outdoors", "landscape"],
  "mouse-16": ["cursor", "click", "peripheral"],
  "move-16": ["drag", "reposition", "pan"],
  "mug-16": ["cup", "coffee", "tea"],
  "mug-steam-16": ["hot drink", "coffee", "tea"],
  "multiply-16": ["times", "math", "multiplication"],
  "music-16": ["song", "audio", "melody"],
  "network-16": ["connection", "nodes", "internet"],
  "new-document-16": ["create file", "add page"],
  "new-folder-16": ["create directory", "add folder"],
  "number-00-16": [],
  "number-01-16": [],
  "number-02-16": [],
  "number-03-16": [],
  "number-04-16": [],
  "number-05-16": [],
  "number-06-16": [],
  "number-07-16": [],
  "number-08-16": [],
  "number-09-16": [],
  "number-10-16": [],
  "number-11-16": [],
  "number-12-16": [],
  "number-13-16": [],
  "number-14-16": [],
  "number-15-16": [],
  "number-16-16": [],
  "number-17-16": [],
  "number-18-16": [],
  "number-19-16": [],
  "number-20-16": [],
  "number-21-16": [],
  "number-22-16": [],
  "number-23-16": [],
  "number-24-16": [],
  "number-25-16": [],
  "number-26-16": [],
  "number-27-16": [],
  "number-28-16": [],
  "number-29-16": [],
  "number-30-16": [],
  "number-31-16": [],
  "number-32-16": [],
  "number-33-16": [],
  "number-34-16": [],
  "number-35-16": [],
  "number-36-16": [],
  "number-37-16": [],
  "number-38-16": [],
  "number-39-16": [],
  "number-40-16": [],
  "number-41-16": [],
  "number-42-16": [],
  "number-43-16": [],
  "number-44-16": [],
  "number-45-16": [],
  "number-46-16": [],
  "number-47-16": [],
  "number-48-16": [],
  "number-49-16": [],
  "number-50-16": [],
  "number-51-16": [],
  "number-52-16": [],
  "number-53-16": [],
  "number-54-16": [],
  "number-55-16": [],
  "number-56-16": [],
  "number-57-16": [],
  "number-58-16": [],
  "number-59-16": [],
  "number-60-16": [],
  "number-61-16": [],
  "number-62-16": [],
  "number-63-16": [],
  "number-64-16": [],
  "number-65-16": [],
  "number-66-16": [],
  "number-67-16": [],
  "number-68-16": [],
  "number-69-16": [],
  "number-70-16": [],
  "number-71-16": [],
  "number-72-16": [],
  "number-73-16": [],
  "number-74-16": [],
  "number-75-16": [],
  "number-76-16": [],
  "number-77-16": [],
  "number-78-16": [],
  "number-79-16": [],
  "number-80-16": [],
  "number-81-16": [],
  "number-82-16": [],
  "number-83-16": [],
  "number-84-16": [],
  "number-85-16": [],
  "number-86-16": [],
  "number-87-16": [],
  "number-88-16": [],
  "number-89-16": [],
  "number-90-16": [],
  "number-91-16": [],
  "number-92-16": [],
  "number-93-16": [],
  "number-94-16": [],
  "number-95-16": [],
  "number-96-16": [],
  "number-97-16": [],
  "number-98-16": [],
  "number-99-16": [],
  "number-list-16": ["ordered list", "numbered list", "formatting"],
  "paperclip-16": ["attachment", "file"],
  "paragraph-16": ["text", "writing", "formatting"],
  "patch-16": ["repair", "fix", "update"],
  "pause-16": ["media", "suspend", "wait"],
  "pause-filled-16": ["media", "suspend", "wait"],
  "pencil-16": ["edit", "write", "compose"],
  "person-16": ["user", "account", "profile"],
  "person-circle-16": ["user", "account", "profile"],
  "person-lines-16": ["contact", "profile", "details"],
  "phone-16": ["call", "telephone", "communication"],
  "phone-ringing-16": ["call", "telephone", "communication"],
  "pie-chart-16": ["analytics", "statistics", "proportions"],
  "pill-16": ["medicine", "medication", "health"],
  "pin-16": ["pinned", "save", "favorite"],
  "pin-disabled-16": ["unpin", "remove pin"],
  "play-16": ["start", "run", "media"],
  "play-filled-16": ["start", "run", "media"],
  "plug-16": ["electricity", "power", "connection"],
  "plus-16": ["add", "create", "new"],
  "plus-circle-16": ["add", "create", "new"],
  "plus-circle-filled-16": ["add", "create", "new"],
  "plus-minus-divide-multiply-16": ["calculator", "math", "arithmetic"],
  "plus-square-16": ["add", "create", "new"],
  "plus-top-right-square-16": ["add", "create", "new"],
  "power-16": ["shutdown", "restart", "on off"],
  "print-16": ["printer", "paper", "document"],
  "question-mark-circle-16": ["help", "faq", "unknown"],
  "quicklink-16": ["shortcut", "url", "bookmark"],
  "quotation-marks-16": ["quote", "citation", "speech"],
  "quote-block-16": ["blockquote", "citation", "text"],
  "racket-16": ["tennis", "badminton", "sport"],
  "raindrop-16": ["water", "rain", "weather"],
  "raycast-logo-neg-16": ["launcher", "raycast"],
  "raycast-logo-pos-16": ["launcher", "raycast"],
  "receipt-16": ["invoice", "expense", "purchase"],
  "redo-16": ["repeat action", "forward", "restore"],
  "remove-person-16": ["delete user", "contact", "uninvite"],
  "repeat-16": ["loop", "again", "recurring"],
  "replace-16": ["substitute", "text", "find and replace"],
  "replace-one-16": ["substitute", "text", "find and replace"],
  "reply-16": ["respond", "answer", "email"],
  "rewind-16": ["media", "backward", "previous"],
  "rewind-filled-16": ["media", "backward", "previous"],
  "rocket-16": ["launch", "startup", "space"],
  "rosette-16": ["badge", "award", "certificate"],
  "rotate-anti-clockwise-16": ["counterclockwise", "turn left", "rotation"],
  "rotate-clockwise-16": ["turn right", "rotation"],
  "rss-16": ["feed", "subscription", "news"],
  "ruler-16": ["measure", "length", "dimensions"],
  "save-document-16": ["save file", "disk", "document"],
  "shield-01-16": ["security", "protection", "privacy"],
  "short-paragraph-16": ["text", "summary", "formatting"],
  "shuffle-16": ["random", "mix", "reorder"],
  "signal-0-16": ["reception", "connection", "strength"],
  "signal-1-16": ["reception", "connection", "strength"],
  "signal-3-16": ["reception", "connection", "strength"],
  "snippets-16": ["text expansion", "template", "abbreviation"],
  "snowflake-16": ["cold", "winter", "snow"],
  "soccer-ball-16": ["football", "sport", "game"],
  "speaker-16": ["audio", "sound", "volume"],
  "speaker-down-16": ["audio", "sound", "volume"],
  "speaker-high-16": ["audio", "sound", "volume"],
  "speaker-low-16": ["audio", "sound", "volume"],
  "speaker-off-16": ["mute", "silent", "volume"],
  "speaker-on-16": ["audio", "sound", "volume"],
  "speaker-up-16": ["audio", "sound", "volume"],
  "speech-bubble-active-16": ["chat", "message", "conversation"],
  "speech-bubble-important-16": ["chat", "message", "conversation"],
  "square-ellipsis-16": ["more", "options", "menu"],
  "stacked-bars-1-16": ["levels", "hierarchy", "bars"],
  "stacked-bars-2-16": ["levels", "hierarchy", "bars"],
  "stacked-bars-3-16": ["levels", "hierarchy", "bars"],
  "stacked-bars-4-16": ["levels", "hierarchy", "bars"],
  "star-16": ["favorite", "rating", "bookmark"],
  "star-circle-16": ["favorite", "rating", "bookmark"],
  "star-disabled-16": ["unfavorite", "remove favorite"],
  "stars-16": ["sparkles", "magic"],
  "stop-16": ["halt", "cancel", "square"],
  "stop-filled-16": ["halt", "cancel", "square"],
  "stopwatch-16": ["timer", "duration", "elapsed"],
  "store-16": ["shop", "marketplace", "extensions"],
  "strike-through-16": ["strikethrough", "crossed out", "formatting"],
  "sun-16": ["day", "brightness", "light mode"],
  "sunrise-16": ["dawn", "morning", "weather"],
  "swatch-16": ["palette", "color", "colour"],
  "switch-16": ["toggle", "on off", "control"],
  "syringe-16": ["vaccine", "injection", "medicine"],
  "tack-16": ["pinned", "thumbtack"],
  "tack-disabled-16": ["unpin", "remove pin"],
  "tag-16": ["label", "category", "metadata"],
  "temperature-16": ["thermometer", "degrees", "weather"],
  "tennis-ball-16": ["sport", "tennis", "game"],
  "terminal-16": ["console", "shell", "command line"],
  "text-16": ["font", "typography", "writing"],
  "text-cursor-16": ["caret", "insertion", "typing"],
  "text-input-16": ["field", "form", "typing"],
  "text-selection-16": ["highlight", "selected text"],
  "thumbs-down-16": ["dislike", "disapprove", "feedback"],
  "thumbs-down-filled-16": ["dislike", "disapprove", "feedback"],
  "thumbs-up-16": ["like", "approve", "feedback"],
  "thumbs-up-filled-16": ["like", "approve", "feedback"],
  "ticket-16": ["pass", "admission", "event"],
  "torch-16": ["flashlight", "illumination"],
  "train-16": ["railway", "transport", "subway"],
  "trash-16": ["delete", "bin", "remove"],
  "tray-16": ["inbox", "incoming", "mail"],
  "tree-16": ["nature", "forest", "plant"],
  "trophy-16": ["award", "winner", "achievement"],
  "two-people-16": ["team", "group", "users"],
  "umbrella-16": ["rain", "weather", "protection"],
  "underline-16": ["text", "typography", "formatting"],
  "undo-16": ["revert", "back", "restore"],
  "upload-16": ["send", "transfer", "publish"],
  "uppercase-16": ["capital letters", "text", "typography"],
  "video-16": ["movie", "camera", "recording"],
  "video-disabled-16": ["camera off", "recording off"],
  "wallet-16": ["money", "payment", "finance"],
  "wand-16": ["magic", "effects", "automatic"],
  "warning-16": ["caution", "alert", "danger"],
  "waveform-16": ["audio", "sound", "recording"],
  "weights-16": ["gym", "fitness", "workout"],
  "wifi-16": ["wireless", "internet", "network"],
  "wifi-disabled-16": ["offline", "disconnected", "wireless"],
  "wind-16": ["weather", "breeze", "air"],
  "windsock-16": ["wind direction", "weather", "aviation"],
  "wrench-screwdriver-16": ["tools", "repair", "maintenance"],
  "wrist-watch-16": ["time", "clock", "wearable"],
  "x-mark-circle-16": ["close", "cancel", "remove"],
  "x-mark-circle-filled-16": ["close", "cancel", "remove"],
  "x-mark-circle-half-dash-16": ["close", "cancel", "remove"],
  "x-mark-top-right-square-16": ["close", "cancel", "remove"],
  "xmark-16": ["close", "cancel", "dismiss"],
};
