export const countryFlags: Record<string, string> = {
  Bahrain: "bh",
  "Saudi Arabia": "sa",
  Australia: "au",
  Japan: "jp",
  China: "cn",
  USA: "us",
  Italy: "it",
  Monaco: "mc",
  Spain: "es",
  Canada: "ca",
  Austria: "at",
  UK: "gb",
  Hungary: "hu",
  Belgium: "be",
  Netherlands: "nl",
  Azerbaijan: "az",
  Singapore: "sg",
  Mexico: "mx",
  Brazil: "br",
  Qatar: "qa",
  UAE: "ae",
};

export const nationalityFlags: Record<string, string> = {
  British: "gb",
  German: "de",
  Spanish: "es",
  Finnish: "fi",
  Japanese: "jp",
  French: "fr",
  Polish: "pl",
  Brazilian: "br",
  Italian: "it",
  Australian: "au",
  Austrian: "at",
  American: "us",
  Dutch: "nl",
  Colombian: "co",
  Portuguese: "pt",
  Canadian: "ca",
  Indian: "in",
  Hungarian: "hu",
  Irish: "ie",
  Danish: "dk",
  Argentine: "ar",
  Czech: "cz",
  Malaysian: "my",
  Swiss: "ch",
  Belgian: "be",
  Monegasque: "mc",
  Swedish: "se",
  Venezuelan: "ve",
  "New Zealander": "nz",
  Chilean: "cl",
  Mexican: "mx",
  "South African": "za",
  Liechtensteiner: "li",
  Rhodesian: "zw",
  Uruguayan: "uy",
  Thai: "th",
  Russian: "ru",
  Chinese: "cn",
  Indonesian: "id",
};

export const historicCountryFlags: Record<string, string> = {
  Argentina: "ar",
  Australia: "au",
  Austria: "at",
  Azerbaijan: "az",
  Bahrain: "bh",
  Belgium: "be",
  Brazil: "br",
  Canada: "ca",
  China: "cn",
  France: "fr",
  Germany: "de",
  Hungary: "hu",
  India: "in",
  Italy: "it",
  Japan: "jp",
  Korea: "kr",
  Malaysia: "my",
  Mexico: "mx",
  Monaco: "mc",
  Morocco: "ma",
  Netherlands: "nl",
  Portugal: "pt",
  Qatar: "qa",
  Russia: "ru",
  "Saudi Arabia": "sa",
  Singapore: "sg",
  "South Africa": "za",
  Spain: "es",
  Sweden: "se",
  Switzerland: "ch",
  Turkey: "tr",
  UAE: "ae",
  UK: "gb",
  USA: "us",
};

export const teamColors: Record<string, string> = {
  "Red Bull": "#3671C6",
  Mercedes: "#27F4D2",
  Ferrari: "#E8002D",
  McLaren: "#FF8000",
  "Aston Martin": "#229971",
  "Alpine F1 Team": "#F596C8",
  Williams: "#64C4FF",
  "RB F1 Team": "#6692FF",
  Audi: "#FF1E00",
  "Haas F1 Team": "#FFFFFF",
  "Cadillac F1 Team": "#A9A9A9",
  Renault: "#FFF500",
  Brawn: "#B8FD10",
  "Lotus F1": "#FFB800",
  Benetton: "#0088CE",
};

/**
 * Normalizes team names from various APIs to ensure correct colors are displayed.
 */
export const getTeamColor = (apiName: string): string => {
  if (apiName.includes("Sauber") || apiName.includes("Audi"))
    return teamColors["Audi"];
  if (apiName.includes("Haas") || apiName.includes("Toyota"))
    return teamColors["Haas F1 Team"];
  if (apiName.includes("Visa") || apiName.includes("RB"))
    return teamColors["RB F1 Team"];
  return teamColors[apiName] || "#808080";
};
