export const feelings = {
  afraid: { title: "Afraid", icon: "😨", id: "afraid" },
  worried: { title: "Worried", icon: "😟", id: "worried" },
  overwhelmed: { title: "Overwhelmed", icon: "🤯", id: "overwhelmed" },
  lonely: { title: "Lonely", icon: "🫥", id: "lonely" },
  jealous: { title: "Jealous", icon: "😒", id: "jealous" },
  frustrated: { title: "Frustrated", icon: "🙄", id: "frustrated" },
  angry: { title: "Angry", icon: "😡", id: "angry" },
  hungry: { title: "Hungry", icon: "😋", id: "hungry" },
  embarrassed: { title: "Embarrassed", icon: "😳", id: "embarrassed" },
  tired: { title: "Tired", icon: "🥱", id: "tired" },
  bored: { title: "Bored", icon: "😒", id: "bored" },
  nervous: { title: "Nervous", icon: "😬", id: "nervous" },
  sad: { title: "Sad", icon: "😞", id: "sad" },
  guilty: { title: "Guilty", icon: "😔", id: "guilty" },
  confused: { title: "Confused", icon: "😵‍💫", id: "confused" },
  excited: { title: "Excited", icon: "🤩", id: "excited" },
  insecure: { title: "Insecure", icon: "🤔", id: "insecure" },
  anxious: { title: "Anxious", icon: "😰", id: "anxious" },
  pressured: { title: "Pressured", icon: "🏃‍➡️", id: "pressured" },
  resentful: { title: "Resentful", icon: "😠", id: "resentful" },
} as const;
