name: "🛠 💎 Dev Tools Feature Request"
description: Suggest new features or improvements related to dev tools used to create extensions
labels: ["dev tools", "feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Do not forget to update the title above to consisely describe the issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a clear and concise description of your idea. Consider adding examples, screenshots, and references to similar features in other products.
    validations:
      required: true
