name: 🧩 🐞 Extension Bug Report
description: Report a reproducible bug or regression related to extension(s) published in the Store
title: "[Extension Name] ..."
labels: [extension, bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Do not forget to update the title above to consisely describe the issue.
  - type: input
    id: extension-url
    attributes:
      label: Extension
      description: |
        Please add a link to the extension concerned by the bug.
        You can search for it in the store: https://raycast.com/store
      placeholder: ex. https://raycast.com/author/extension
    validations:
      required: true
  - type: input
    id: raycast-version
    attributes:
      label: Raycast Version
      description: |
        Please provide the version of Raycast you are using.
        You can find it in the Raycast menu > About Raycast.
      placeholder: ex. 1.73.2
    validations:
      required: true
  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      description: |
        Please provide the version of macOS you are using.
        You can find it in the Apple menu > About This Mac.
      placeholder: ex. 14.4.1
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a clear and concise description of what the bug is. Include screenshots if needed. Please make sure you are using the latest version of the extension and Raycast.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps To Reproduce
      description: Your bug will get fixed much faster if the extension author can easily reproduce it. Issues without reproduction steps may be immediately closed as not actionable.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behaviour
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
    validations:
      required: false
