name: 🧩 💎 Extension Feature Request
description: Suggest new Feature or an improvement to existing Extension
title: "[Extension Name] ..."
labels: [extension, feature request]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Do not forget to update the title above to consisely describe the feature request.
  - type: input
    id: extension-url
    attributes:
      label: Extension
      description: |
        Please add a link to the extension concerned by the bug.
        You can search for it in the store: https://raycast.com/store
      placeholder: ex. https://raycast.com/author/extension
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature and the current behavior/state.
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Who will benefit from this feature?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
