export const STRINGS = {
  searchMoviesPlaceholder: "Search Movies",
  startSearching: "Search for a Movie",
  startSearchingDescription: "Type a title to search Letterboxd",
  noMoviesFound: "No Movies Found",
  noMoviesFoundDescription: "Try another title",
  recentSearches: "Recent Searches",
  clearRecentSearches: "Clear Recent Searches",
  showDetails: "Show Details",
  copyUrl: "Copy URL",
  copyTitle: "Copy Title",
  copyMarkdownLink: "Copy Markdown Link",
  releasedLabel: "Released",
  runtimeLabel: "Runtime",
  runtimeUnit: "minutes",
  somethingWentWrong: "Something went wrong",
  tryAgain: "Please try again",
  retry: "Retry",
  directorLabel: "Director",
  languageLabel: "Language",
  countriesLabel: "Countries",
  castLabel: "Cast",
  productionCompaniesLabel: "Production Companies",
  genresLabel: "Genres",
};
