import { Item, ItemDetail, Vault } from "./types";

export const MOCK_VAULTS: Vault[] = [
  { shareId: "vault-1", name: "Personal", itemCount: 12, role: "owner" },
  { shareId: "vault-2", name: "Work", itemCount: 8, role: "owner" },
  { shareId: "vault-3", name: "Family", itemCount: 5, role: "manager" },
  { shareId: "vault-4", name: "Shared Projects", itemCount: 3, role: "editor" },
];

export const MOCK_ITEMS: Item[] = [
  {
    shareId: "vault-1",
    itemId: "item-1",
    title: "GitHub",
    type: "login",
    vaultName: "Personal",
    username: "johndoe",
    email: "john@example.com",
    hasTotp: true,
  },
  {
    shareId: "vault-1",
    itemId: "item-2",
    title: "Netflix",
    type: "login",
    vaultName: "Personal",
    email: "john@example.com",
    hasTotp: false,
  },
  {
    shareId: "vault-1",
    itemId: "item-3",
    title: "AWS Console",
    type: "login",
    vaultName: "Personal",
    username: "admin@company.io",
    hasTotp: true,
  },
  {
    shareId: "vault-1",
    itemId: "item-4",
    title: "Private Notes",
    type: "note",
    vaultName: "Personal",
    hasTotp: false,
  },
  {
    shareId: "vault-1",
    itemId: "item-5",
    title: "Visa •••• 4242",
    type: "credit_card",
    vaultName: "Personal",
    hasTotp: false,
  },
  {
    shareId: "vault-2",
    itemId: "item-6",
    title: "Slack",
    type: "login",
    vaultName: "Work",
    email: "john@company.io",
    hasTotp: true,
  },
  {
    shareId: "vault-2",
    itemId: "item-7",
    title: "Jira",
    type: "login",
    vaultName: "Work",
    email: "john@company.io",
    hasTotp: false,
  },
  {
    shareId: "vault-2",
    itemId: "item-8",
    title: "Linear",
    type: "login",
    vaultName: "Work",
    email: "john@company.io",
    hasTotp: true,
  },
  {
    shareId: "vault-2",
    itemId: "item-9",
    title: "Server SSH Key",
    type: "ssh_key",
    vaultName: "Work",
    hasTotp: false,
  },
  {
    shareId: "vault-3",
    itemId: "item-10",
    title: "Disney+",
    type: "login",
    vaultName: "Family",
    email: "family@example.com",
    hasTotp: false,
  },
  {
    shareId: "vault-3",
    itemId: "item-11",
    title: "Home WiFi",
    type: "wifi",
    vaultName: "Family",
    hasTotp: false,
  },
  {
    shareId: "vault-4",
    itemId: "item-12",
    title: "Vercel",
    type: "login",
    vaultName: "Shared Projects",
    email: "team@project.io",
    hasTotp: true,
  },
];

export const MOCK_ITEM_DETAILS: Record<string, ItemDetail> = {
  "item-1": {
    shareId: "vault-1",
    itemId: "item-1",
    title: "GitHub",
    type: "login",
    vaultName: "Personal",
    username: "johndoe",
    email: "john@example.com",
    password: "mock-password-1",
    urls: ["https://github.com", "https://github.com/login"],
    hasTotp: true,
    note: "Main development account",
  },
  "item-2": {
    shareId: "vault-1",
    itemId: "item-2",
    title: "Netflix",
    type: "login",
    vaultName: "Personal",
    email: "john@example.com",
    password: "mock-password-2",
    urls: ["https://netflix.com"],
    hasTotp: false,
  },
  "item-3": {
    shareId: "vault-1",
    itemId: "item-3",
    title: "AWS Console",
    type: "login",
    vaultName: "Personal",
    username: "admin@company.io",
    password: "mock-password-3",
    urls: ["https://console.aws.amazon.com"],
    hasTotp: true,
    customFields: [
      { name: "Account ID", value: "123456789012", type: "text" },
      { name: "MFA Device", value: "Virtual", type: "text" },
    ],
  },
  "item-6": {
    shareId: "vault-2",
    itemId: "item-6",
    title: "Slack",
    type: "login",
    vaultName: "Work",
    email: "john@company.io",
    password: "mock-password-4",
    urls: ["https://company.slack.com"],
    hasTotp: true,
  },
};

export const MOCK_TOTP_CODES: Record<string, string> = {
  "item-1": "123456",
  "item-3": "654321",
  "item-6": "789012",
  "item-8": "345678",
  "item-12": "901234",
};

export function useMockData(): boolean {
  return process.env.NODE_ENV === "development";
}
