export const READING_STYLES_PROMPTS = {
  autoDetect: `
  Analyze the details of the provided content to automatically determine the most suitable type of script. 
  Then, generate a script in one of the following formats, optimized for a natural and smooth reading experience:

  Audiobook: Narrate the story with emotion and appropriate tone, ensuring a captivating storytelling experience.
  Educational Material: Focus on clarity and effectiveness in teaching, with explanations or summaries where necessary.
  Code Explanation: Clearly articulate the functions, structures, and logic of the code, making it understandable even for those not familiar with the programming language.
  Code Review: Provide a balanced assessment of the code, highlighting strengths, weaknesses, and suggestions for improvement in a clear manner.
  News: Present the information factually and concisely, maintaining a neutral tone throughout.
  Podcast: Engage the listener with a conversational and dynamic style, appropriate for a podcast format.
  Spark Notes: Concisely summarize the key points and essential information, making it easy to grasp the core concepts quickly.
  If the content doesn't fit these categories, create a script that best matches the unique characteristics of the content, always aiming for a human-like, engaging narration and using only verified, relevant details about the content's nature and authorship.
  `.trim(),
  summary: `highly condensed script for text-to-speech, focusing exclusively on summarizing the key points. The script should distill the essential information into a brief, clear, and direct format, ensuring that the author's main messages are conveyed succinctly and effectively without any extraneous details or embellishments.`,
  detailed: `This script for text-to-speech starts with an explanation of the content's plot from a third-person perspective. The script will then provide a detailed summary of the main points, ensuring comprehensive coverage in a clear and concise manner. It is structured logically and coherently, allowing the listener to easily follow the narrative and understand the key messages as if an observer is recounting the events.`,
  audioBook: `script for text-to-speech that begins with a natural introduction of the author and the book. After the introduction, seamlessly transition into reading the main content. The script should emulate an audiobook style, being straightforward and engaging, and emphasize key points with minimal embellishments. The narrative should be clear and concise, effectively conveying essential information as if the author is personally addressing the audience.`,
  educational: `script for text-to-speech designed for educational content. The script should start with a clear definition of the topic, followed by a structured explanation of the main concepts. It should break down complex information into digestible parts, using examples and analogies where appropriate. The style should be informative and didactic, aiming to teach the listener in a way that is both engaging and easy to follow.`,
  explainCode: `script for text-to-speech aimed at demystifying code, crafted as if narrated by an expert specializing in code explanation. It begins with a brief overview of the programming language used and the primary purpose of the code. The script then methodically deconstructs the code's structure and logic, elucidating the roles of crucial components and their interactions. The delivery is clear and precise, structured to assist listeners in grasping the code's fundamentals as though they are being guided by a seasoned programmer.`,
  codeReview: `script for text-to-speech designed for code review sessions. The script should start with an overview of the code being reviewed, followed by a systematic analysis of the code's structure, logic, and potential improvements. It should provide clear and constructive feedback, highlighting both strengths and areas for enhancement. The style should be collaborative and educational, fostering a positive environment for learning and development while ensuring the code's functionality and efficiency are thoroughly evaluated.`,
  news: `script for text-to-speech that begins with a natural introduction of the author and the article. After the introduction, seamlessly transition into reading the main content. The script should emulate a news style, being straightforward and engaging, and emphasize key points with minimal embellishments. The narrative should be clear and concise, effectively conveying essential information as if the author is personally addressing the audience.`,
  podcast: `script for text-to-speech that begins with a natural introduction of either the author or the company associated with the article. After the introduction, seamlessly transition into reading the main content. The script should emulate a podcast style, being straightforward and engaging, and emphasize key points with minimal embellishments. The narrative should be clear and concise, effectively conveying essential information as if the author or a representative of the company is personally addressing the audience.`,
  sparkNotes: `script for text-to-speech tailored for SparkNotes content. The script should begin by naturally introducing the topic or the title of the work being summarized. It should then transition seamlessly into a detailed summary and analysis, capturing the essence of the SparkNotes content. The style should be informative and educational, with a focus on clarity and precision to facilitate understanding of literary themes and concepts. The script should effectively articulate key insights and analyses, maintaining the integrity and depth of the original literary work, making it suitable for students and literature enthusiasts seeking a comprehensive understanding of the text.`,
  tweet: `script for text-to-speech that replicates the tweet as if being spoken by the author themselves. Mention the author and the time the tweet was posted only when such information is available, then proceed with a direct quotation of the tweet's content. It should preserve the original tone and intent of the author, avoiding any unnecessary interpretation. The style should be succinct and engaging, effectively capturing the tweet's essence and delivering it in a manner that resonates with the listener.`,
};

export const MIN_TEXT_QUE_SENTENCE_LENGTH = 10; // set the minimum sentence length to 10 characters
