/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A serializable status row for `pixtuoid sources --json` — the STABLE wire
 * contract the Raycast extension parses (pinned by `source_status_json_shape`).
 * Deliberately a flat DTO, NOT the internal `ConnectionRow` (whose shape is a
 * UI concern free to change).
 */
export interface SourceStatus {
  cli_present: boolean;
  connected: boolean;
  display_name: string;
  /**
   * A health/issue summary (install-broken / decode-drift), or `null` when n/a.
   */
  health?: string | null;
  id: string;
}
