/** HL7 v2.5 names for common segments. Each field is [name, data type]. Index 0 is field 1. */
type FieldDef = [name: string, type: string];

export const SEGMENT_NAMES: Record<string, string> = {
  MSH: "Message Header",
  EVN: "Event Type",
  PID: "Patient Identification",
  PD1: "Patient Additional Demographic",
  NK1: "Next of Kin",
  PV1: "Patient Visit",
  PV2: "Patient Visit – Additional Info",
  ORC: "Common Order",
  OBR: "Observation Request",
  OBX: "Observation / Result",
  NTE: "Notes and Comments",
  SPM: "Specimen",
  TQ1: "Timing / Quantity",
  AL1: "Patient Allergy Information",
  DG1: "Diagnosis",
  IN1: "Insurance",
  GT1: "Guarantor",
  MSA: "Message Acknowledgment",
  ERR: "Error",
  FHS: "File Header",
  FTS: "File Trailer",
  BHS: "Batch Header",
  BTS: "Batch Trailer",
  SCH: "Scheduling Activity Information",
  TXA: "Transcription Document Header",
  MRG: "Merge Patient Information",
};

const HEADER: FieldDef[] = [
  ["Field Separator", "ST"],
  ["Encoding Characters", "ST"],
  ["Sending Application", "HD"],
  ["Sending Facility", "HD"],
  ["Receiving Application", "HD"],
  ["Receiving Facility", "HD"],
  ["Date/Time of Message", "TS"],
  ["Security", "ST"],
];

export const FIELDS: Record<string, FieldDef[]> = {
  MSH: [
    ...HEADER,
    ["Message Type", "MSG"],
    ["Message Control ID", "ST"],
    ["Processing ID", "PT"],
    ["Version ID", "VID"],
    ["Sequence Number", "NM"],
    ["Continuation Pointer", "ST"],
    ["Accept Acknowledgment Type", "ID"],
    ["Application Acknowledgment Type", "ID"],
    ["Country Code", "ID"],
    ["Character Set", "ID"],
    ["Principal Language of Message", "CE"],
    ["Alternate Character Set Handling Scheme", "ID"],
    ["Message Profile Identifier", "EI"],
  ],
  FHS: [
    ...HEADER,
    ["File Name/ID", "ST"],
    ["File Header Comment", "ST"],
    ["File Control ID", "ST"],
    ["Reference File Control ID", "ST"],
  ],
  BHS: [
    ...HEADER,
    ["Batch Name/ID/Type", "ST"],
    ["Batch Comment", "ST"],
    ["Batch Control ID", "ST"],
    ["Reference Batch Control ID", "ST"],
  ],
  FTS: [
    ["File Batch Count", "NM"],
    ["File Trailer Comment", "ST"],
  ],
  BTS: [
    ["Batch Message Count", "ST"],
    ["Batch Comment", "ST"],
    ["Batch Totals", "NM"],
  ],
  EVN: [
    ["Event Type Code", "ID"],
    ["Recorded Date/Time", "TS"],
    ["Date/Time Planned Event", "TS"],
    ["Event Reason Code", "IS"],
    ["Operator ID", "XCN"],
    ["Event Occurred", "TS"],
    ["Event Facility", "HD"],
  ],
  PID: [
    ["Set ID", "SI"],
    ["Patient ID", "CX"],
    ["Patient Identifier List", "CX"],
    ["Alternate Patient ID", "CX"],
    ["Patient Name", "XPN"],
    ["Mother's Maiden Name", "XPN"],
    ["Date/Time of Birth", "TS"],
    ["Administrative Sex", "IS"],
    ["Patient Alias", "XPN"],
    ["Race", "CE"],
    ["Patient Address", "XAD"],
    ["County Code", "IS"],
    ["Phone Number – Home", "XTN"],
    ["Phone Number – Business", "XTN"],
    ["Primary Language", "CE"],
    ["Marital Status", "CE"],
    ["Religion", "CE"],
    ["Patient Account Number", "CX"],
    ["SSN Number", "ST"],
    ["Driver's License Number", "DLN"],
    ["Mother's Identifier", "CX"],
    ["Ethnic Group", "CE"],
    ["Birth Place", "ST"],
    ["Multiple Birth Indicator", "ID"],
    ["Birth Order", "NM"],
    ["Citizenship", "CE"],
    ["Veterans Military Status", "CE"],
    ["Nationality", "CE"],
    ["Patient Death Date and Time", "TS"],
    ["Patient Death Indicator", "ID"],
    ["Identity Unknown Indicator", "ID"],
    ["Identity Reliability Code", "IS"],
    ["Last Update Date/Time", "TS"],
    ["Last Update Facility", "HD"],
    ["Species Code", "CE"],
    ["Breed Code", "CE"],
    ["Strain", "ST"],
    ["Production Class Code", "CE"],
    ["Tribal Citizenship", "CWE"],
  ],
  NK1: [
    ["Set ID", "SI"],
    ["Name", "XPN"],
    ["Relationship", "CE"],
    ["Address", "XAD"],
    ["Phone Number", "XTN"],
    ["Business Phone Number", "XTN"],
    ["Contact Role", "CE"],
    ["Start Date", "DT"],
    ["End Date", "DT"],
  ],
  PV1: [
    ["Set ID", "SI"],
    ["Patient Class", "IS"],
    ["Assigned Patient Location", "PL"],
    ["Admission Type", "IS"],
    ["Preadmit Number", "CX"],
    ["Prior Patient Location", "PL"],
    ["Attending Doctor", "XCN"],
    ["Referring Doctor", "XCN"],
    ["Consulting Doctor", "XCN"],
    ["Hospital Service", "IS"],
    ["Temporary Location", "PL"],
    ["Preadmit Test Indicator", "IS"],
    ["Re-admission Indicator", "IS"],
    ["Admit Source", "IS"],
    ["Ambulatory Status", "IS"],
    ["VIP Indicator", "IS"],
    ["Admitting Doctor", "XCN"],
    ["Patient Type", "IS"],
    ["Visit Number", "CX"],
    ["Financial Class", "FC"],
    ["Charge Price Indicator", "IS"],
    ["Courtesy Code", "IS"],
    ["Credit Rating", "IS"],
    ["Contract Code", "IS"],
    ["Contract Effective Date", "DT"],
    ["Contract Amount", "NM"],
    ["Contract Period", "NM"],
    ["Interest Code", "IS"],
    ["Transfer to Bad Debt Code", "IS"],
    ["Transfer to Bad Debt Date", "DT"],
    ["Bad Debt Agency Code", "IS"],
    ["Bad Debt Transfer Amount", "NM"],
    ["Bad Debt Recovery Amount", "NM"],
    ["Delete Account Indicator", "IS"],
    ["Delete Account Date", "DT"],
    ["Discharge Disposition", "IS"],
    ["Discharged to Location", "DLD"],
    ["Diet Type", "CE"],
    ["Servicing Facility", "IS"],
    ["Bed Status", "IS"],
    ["Account Status", "IS"],
    ["Pending Location", "PL"],
    ["Prior Temporary Location", "PL"],
    ["Admit Date/Time", "TS"],
    ["Discharge Date/Time", "TS"],
    ["Current Patient Balance", "NM"],
    ["Total Charges", "NM"],
    ["Total Adjustments", "NM"],
    ["Total Payments", "NM"],
    ["Alternate Visit ID", "CX"],
    ["Visit Indicator", "IS"],
    ["Other Healthcare Provider", "XCN"],
  ],
  ORC: [
    ["Order Control", "ID"],
    ["Placer Order Number", "EI"],
    ["Filler Order Number", "EI"],
    ["Placer Group Number", "EI"],
    ["Order Status", "ID"],
    ["Response Flag", "ID"],
    ["Quantity/Timing", "TQ"],
    ["Parent", "EIP"],
    ["Date/Time of Transaction", "TS"],
    ["Entered By", "XCN"],
    ["Verified By", "XCN"],
    ["Ordering Provider", "XCN"],
    ["Enterer's Location", "PL"],
    ["Call Back Phone Number", "XTN"],
    ["Order Effective Date/Time", "TS"],
    ["Order Control Code Reason", "CE"],
    ["Entering Organization", "CE"],
    ["Entering Device", "CE"],
    ["Action By", "XCN"],
    ["Advanced Beneficiary Notice Code", "CE"],
    ["Ordering Facility Name", "XON"],
    ["Ordering Facility Address", "XAD"],
    ["Ordering Facility Phone Number", "XTN"],
    ["Ordering Provider Address", "XAD"],
    ["Order Status Modifier", "CWE"],
  ],
  OBR: [
    ["Set ID", "SI"],
    ["Placer Order Number", "EI"],
    ["Filler Order Number", "EI"],
    ["Universal Service Identifier", "CE"],
    ["Priority", "ID"],
    ["Requested Date/Time", "TS"],
    ["Observation Date/Time", "TS"],
    ["Observation End Date/Time", "TS"],
    ["Collection Volume", "CQ"],
    ["Collector Identifier", "XCN"],
    ["Specimen Action Code", "ID"],
    ["Danger Code", "CE"],
    ["Relevant Clinical Information", "ST"],
    ["Specimen Received Date/Time", "TS"],
    ["Specimen Source", "SPS"],
    ["Ordering Provider", "XCN"],
    ["Order Callback Phone Number", "XTN"],
    ["Placer Field 1", "ST"],
    ["Placer Field 2", "ST"],
    ["Filler Field 1", "ST"],
    ["Filler Field 2", "ST"],
    ["Results Rpt/Status Chng – Date/Time", "TS"],
    ["Charge to Practice", "MOC"],
    ["Diagnostic Serv Sect ID", "ID"],
    ["Result Status", "ID"],
    ["Parent Result", "PRL"],
    ["Quantity/Timing", "TQ"],
    ["Result Copies To", "XCN"],
    ["Parent", "EIP"],
    ["Transportation Mode", "ID"],
    ["Reason for Study", "CE"],
    ["Principal Result Interpreter", "NDL"],
    ["Assistant Result Interpreter", "NDL"],
    ["Technician", "NDL"],
    ["Transcriptionist", "NDL"],
    ["Scheduled Date/Time", "TS"],
    ["Number of Sample Containers", "NM"],
    ["Transport Logistics of Collected Sample", "CE"],
    ["Collector's Comment", "CE"],
    ["Transport Arrangement Responsibility", "CE"],
    ["Transport Arranged", "ID"],
    ["Escort Required", "ID"],
    ["Planned Patient Transport Comment", "CE"],
    ["Procedure Code", "CE"],
    ["Procedure Code Modifier", "CE"],
    ["Placer Supplemental Service Information", "CE"],
    ["Filler Supplemental Service Information", "CE"],
    ["Medically Necessary Duplicate Procedure Reason", "CWE"],
    ["Result Handling", "IS"],
  ],
  OBX: [
    ["Set ID", "SI"],
    ["Value Type", "ID"],
    ["Observation Identifier", "CE"],
    ["Observation Sub-ID", "ST"],
    ["Observation Value", "*"],
    ["Units", "CE"],
    ["References Range", "ST"],
    ["Abnormal Flags", "IS"],
    ["Probability", "NM"],
    ["Nature of Abnormal Test", "ID"],
    ["Observation Result Status", "ID"],
    ["Effective Date of Reference Range", "TS"],
    ["User Defined Access Checks", "ST"],
    ["Date/Time of the Observation", "TS"],
    ["Producer's ID", "CE"],
    ["Responsible Observer", "XCN"],
    ["Observation Method", "CE"],
    ["Equipment Instance Identifier", "EI"],
    ["Date/Time of the Analysis", "TS"],
  ],
  NTE: [
    ["Set ID", "SI"],
    ["Source of Comment", "ID"],
    ["Comment", "FT"],
    ["Comment Type", "CE"],
  ],
  SPM: [
    ["Set ID", "SI"],
    ["Specimen ID", "EIP"],
    ["Specimen Parent IDs", "EIP"],
    ["Specimen Type", "CWE"],
    ["Specimen Type Modifier", "CWE"],
    ["Specimen Additives", "CWE"],
    ["Specimen Collection Method", "CWE"],
    ["Specimen Source Site", "CWE"],
    ["Specimen Source Site Modifier", "CWE"],
    ["Specimen Collection Site", "CWE"],
    ["Specimen Role", "CWE"],
    ["Specimen Collection Amount", "CQ"],
    ["Grouped Specimen Count", "NM"],
    ["Specimen Description", "ST"],
    ["Specimen Handling Code", "CWE"],
    ["Specimen Risk Code", "CWE"],
    ["Specimen Collection Date/Time", "DR"],
    ["Specimen Received Date/Time", "TS"],
    ["Specimen Expiration Date/Time", "TS"],
    ["Specimen Availability", "ID"],
    ["Specimen Reject Reason", "CWE"],
    ["Specimen Quality", "CWE"],
    ["Specimen Appropriateness", "CWE"],
    ["Specimen Condition", "CWE"],
    ["Specimen Current Quantity", "CQ"],
    ["Number of Specimen Containers", "NM"],
    ["Container Type", "CWE"],
    ["Container Condition", "CWE"],
    ["Specimen Child Role", "CWE"],
  ],
  TQ1: [
    ["Set ID", "SI"],
    ["Quantity", "CQ"],
    ["Repeat Pattern", "RPT"],
    ["Explicit Time", "TM"],
    ["Relative Time and Units", "CQ"],
    ["Service Duration", "CQ"],
    ["Start Date/Time", "TS"],
    ["End Date/Time", "TS"],
    ["Priority", "CWE"],
  ],
  AL1: [
    ["Set ID", "SI"],
    ["Allergen Type Code", "CE"],
    ["Allergen Code/Mnemonic/Description", "CE"],
    ["Allergy Severity Code", "CE"],
    ["Allergy Reaction Code", "ST"],
    ["Identification Date", "DT"],
  ],
  DG1: [
    ["Set ID", "SI"],
    ["Diagnosis Coding Method", "ID"],
    ["Diagnosis Code", "CE"],
    ["Diagnosis Description", "ST"],
    ["Diagnosis Date/Time", "TS"],
    ["Diagnosis Type", "IS"],
  ],
  IN1: [
    ["Set ID", "SI"],
    ["Insurance Plan ID", "CE"],
    ["Insurance Company ID", "CX"],
    ["Insurance Company Name", "XON"],
    ["Insurance Company Address", "XAD"],
    ["Insurance Co Contact Person", "XPN"],
    ["Insurance Co Phone Number", "XTN"],
    ["Group Number", "ST"],
    ["Group Name", "XON"],
    ["Insured's Group Emp ID", "CX"],
    ["Insured's Group Emp Name", "XON"],
    ["Plan Effective Date", "DT"],
    ["Plan Expiration Date", "DT"],
    ["Authorization Information", "AUI"],
    ["Plan Type", "IS"],
    ["Name of Insured", "XPN"],
    ["Insured's Relationship to Patient", "CE"],
    ["Insured's Date of Birth", "TS"],
    ["Insured's Address", "XAD"],
  ],
  MSA: [
    ["Acknowledgment Code", "ID"],
    ["Message Control ID", "ST"],
    ["Text Message", "ST"],
    ["Expected Sequence Number", "NM"],
    ["Delayed Acknowledgment Type", "ID"],
    ["Error Condition", "CE"],
  ],
  ERR: [
    ["Error Code and Location", "ELD"],
    ["Error Location", "ERL"],
    ["HL7 Error Code", "CWE"],
    ["Severity", "ID"],
    ["Application Error Code", "CWE"],
    ["Application Error Parameter", "ST"],
    ["Diagnostic Information", "TX"],
    ["User Message", "TX"],
  ],
  MRG: [
    ["Prior Patient Identifier List", "CX"],
    ["Prior Alternate Patient ID", "CX"],
    ["Prior Patient Account Number", "CX"],
    ["Prior Patient ID", "CX"],
    ["Prior Visit Number", "CX"],
    ["Prior Alternate Visit ID", "CX"],
    ["Prior Patient Name", "XPN"],
  ],
};

const CODED = ["Identifier", "Text", "Coding System", "Alt Identifier", "Alt Text", "Alt Coding System"];

/** Component names per data type. */
export const COMPONENTS: Record<string, string[]> = {
  CE: CODED,
  CWE: CODED,
  CNE: CODED,
  HD: ["Namespace ID", "Universal ID", "Universal ID Type"],
  EI: ["Entity Identifier", "Namespace ID", "Universal ID", "Universal ID Type"],
  EIP: ["Placer Assigned Identifier", "Filler Assigned Identifier"],
  MSG: ["Message Code", "Trigger Event", "Message Structure"],
  PT: ["Processing ID", "Processing Mode"],
  VID: ["Version ID", "Internationalization Code", "International Version ID"],
  TS: ["Time", "Degree of Precision"],
  XPN: ["Family Name", "Given Name", "Middle Names", "Suffix", "Prefix", "Degree", "Name Type Code"],
  XCN: [
    "ID Number",
    "Family Name",
    "Given Name",
    "Middle Names",
    "Suffix",
    "Prefix",
    "Degree",
    "Source Table",
    "Assigning Authority",
  ],
  CX: [
    "ID Number",
    "Check Digit",
    "Check Digit Scheme",
    "Assigning Authority",
    "Identifier Type Code",
    "Assigning Facility",
  ],
  XAD: [
    "Street Address",
    "Other Designation",
    "City",
    "State or Province",
    "Zip or Postal Code",
    "Country",
    "Address Type",
  ],
  XTN: [
    "Telephone Number",
    "Use Code",
    "Equipment Type",
    "Email Address",
    "Country Code",
    "Area/City Code",
    "Local Number",
    "Extension",
  ],
  XON: ["Organization Name", "Name Type Code", "ID Number", "Check Digit", "Check Digit Scheme", "Assigning Authority"],
  PL: ["Point of Care", "Room", "Bed", "Facility", "Location Status", "Person Location Type", "Building", "Floor"],
  SPS: [
    "Specimen Source",
    "Additives",
    "Specimen Collection Method",
    "Body Site",
    "Site Modifier",
    "Collection Method Modifier",
    "Specimen Role",
  ],
  CQ: ["Quantity", "Units"],
  FC: ["Financial Class Code", "Effective Date"],
  PRL: ["Parent Observation Identifier", "Parent Observation Sub-ID", "Parent Observation Value Descriptor"],
  NDL: ["Name", "Start Date/Time", "End Date/Time", "Point of Care", "Room", "Bed", "Facility"],
};

/** Readable meanings for common coded values, keyed by "SEG-n". */
export const TABLES: Record<string, Record<string, string>> = {
  "MSH-11": { P: "Production", T: "Training / Test", D: "Debugging" },
  "MSH-15": { AL: "Always", NE: "Never", ER: "Error only", SU: "Success only" },
  "MSH-16": { AL: "Always", NE: "Never", ER: "Error only", SU: "Success only" },
  "PID-8": { F: "Female", M: "Male", O: "Other", U: "Unknown", A: "Ambiguous", N: "Not applicable" },
  "PV1-2": {
    E: "Emergency",
    I: "Inpatient",
    O: "Outpatient",
    P: "Preadmit",
    R: "Recurring",
    B: "Obstetrics",
    N: "Not applicable",
    U: "Unknown",
  },
  "ORC-1": {
    NW: "New order",
    OK: "Order accepted",
    CA: "Cancel order",
    CR: "Canceled as requested",
    DC: "Discontinue order",
    XO: "Change order",
    SC: "Status changed",
    RE: "Observations to follow",
    SN: "Send order number",
    NA: "Number assigned",
    UA: "Unable to accept",
    OC: "Order canceled",
    HD: "Hold order",
    RL: "Release hold",
  },
  "ORC-5": {
    CM: "Completed",
    IP: "In process",
    SC: "Scheduled",
    CA: "Canceled",
    HD: "On hold",
    A: "Some results available",
    DC: "Discontinued",
    ER: "Error",
  },
  "OBR-5": { S: "Stat", A: "ASAP", R: "Routine", P: "Preop", T: "Timing critical" },
  "OBR-25": {
    O: "Order received",
    I: "No results yet",
    S: "Scheduled",
    A: "Partial",
    P: "Preliminary",
    C: "Correction",
    R: "Not verified",
    F: "Final",
    X: "Canceled",
  },
  "OBX-2": {
    NM: "Numeric",
    ST: "String",
    TX: "Text",
    FT: "Formatted text",
    CE: "Coded entry",
    CWE: "Coded with exceptions",
    SN: "Structured numeric",
    DT: "Date",
    TS: "Timestamp",
    ED: "Encapsulated data",
  },
  "OBX-8": {
    L: "Below low normal",
    H: "Above high normal",
    LL: "Below lower panic limit",
    HH: "Above upper panic limit",
    N: "Normal",
    A: "Abnormal",
    AA: "Very abnormal",
    "<": "Below absolute low",
    ">": "Above absolute high",
    S: "Susceptible",
    R: "Resistant",
    I: "Intermediate",
    POS: "Positive",
    NEG: "Negative",
  },
  "OBX-11": {
    F: "Final",
    P: "Preliminary",
    C: "Correction",
    R: "Not verified",
    I: "Pending",
    X: "Cannot be obtained",
    D: "Delete",
    W: "Wrong",
  },
  "MSA-1": {
    AA: "Accepted",
    AE: "Error",
    AR: "Rejected",
    CA: "Commit accept",
    CE: "Commit error",
    CR: "Commit reject",
  },
  "NTE-2": { L: "Ancillary (filler)", P: "Orderer (placer)", O: "Other system" },
};

export function fieldDef(segment: string, position: number): { name?: string; type?: string } {
  const def = FIELDS[segment]?.[position - 1];
  return def ? { name: def[0], type: def[1] } : {};
}
