export type DocsV4ItemHeading = string | { title: string; headings?: DocsV4ItemHeading[] };

export type DocsV4Item = { title: string; slug: string; headings?: DocsV4ItemHeading[] };

export const docsV4 = [
  {
    title: "Intro",
    slug: "",
    headings: [
      "Introduction",
      "Features",
      "Installation",
      { title: "Requirements", headings: ['"strict"'] },
      "Ecosystem",
      { title: "Sponsors", headings: ["Platinum", "Gold", "Silver", "Bronze"] },
    ],
  },
  {
    title: "Basic usage",
    slug: "basics",
    headings: ["Defining a schema", "Parsing data", "Handling errors", "Inferring types"],
  },
  {
    title: "Defining schemas",
    slug: "api",
    headings: [
      { title: "Primitives", headings: ["Coercion"] },
      "Literals",
      "Strings",
      {
        title: "String formats",
        headings: [
          "Emails",
          "UUIDs",
          "URLs",
          "Phone numbers",
          "ISO datetimes",
          "ISO dates",
          "ISO times",
          "IP addresses",
          "IP blocks (CIDR)",
          "MAC Addresses",
          "JWTs",
          "Hashes",
          "Custom formats",
        ],
      },
      "Template literals",
      "Numbers",
      "Integers",
      "BigInts",
      "Booleans",
      "Dates",
      { title: "Enums", headings: [".enum", ".exclude()", ".extract()"] },
      "Stringbools",
      "Optionals",
      "Nullables",
      "Nullish",
      "Unknown",
      "Never",
      {
        title: "Objects",
        headings: [
          "z.strictObject",
          "z.looseObject",
          ".catchall()",
          ".shape",
          ".keyof()",
          ".extend()",
          ".safeExtend()",
          ".pick()",
          ".omit()",
          ".partial()",
          ".required()",
        ],
      },
      { title: "Recursive objects", headings: ["Circularity errors"] },
      "Arrays",
      "Tuples",
      "Unions",
      "Exclusive unions (XOR)",
      "Discriminated unions",
      "Intersections",
      { title: "Records", headings: ["z.record", "z.partialRecord", "z.looseRecord"] },
      "Maps",
      "Sets",
      "Files",
      "Promises",
      { title: "Instanceof", headings: ["Property"] },
      {
        title: "Refinements",
        headings: [{ title: ".refine()", headings: ["error", "abort", "path", "when"] }, ".superRefine()", ".check()"],
      },
      "Codecs",
      "Pipes",
      { title: "Transforms", headings: [".transform()", ".preprocess()"] },
      "Defaults",
      "Prefaults",
      "Catch",
      "Branded types",
      "Readonly",
      "JSON",
      "Functions",
      "Custom",
      "Apply",
    ],
  },
  {
    title: "Customizing errors",
    slug: "error-customization",
    headings: [
      "The error param",
      { title: "Per-parse error customization", headings: ["Include input in issues"] },
      "Global error customization",
      { title: "Internationalization", headings: ["Locales"] },
      "Error precedence",
    ],
  },
  {
    title: "Formatting errors",
    slug: "error-formatting",
    headings: ["z.treeifyError()", "z.prettifyError()", "z.formatError()", "z.flattenError()"],
  },
  {
    title: "Metadata and registries",
    slug: "metadata",
    headings: [
      { title: "Registries", headings: [".register()"] },
      { title: "Metadata", headings: ["z.globalRegistry", ".meta()", ".describe()"] },
      { title: "Custom registries", headings: ["Referencing inferred types", "Constraining schema types"] },
    ],
  },
  {
    title: "JSON Schema",
    slug: "json-schema",
    headings: [
      "z.fromJSONSchema()",
      {
        title: "z.toJSONSchema()",
        headings: ["io", "target", "metadata", "unrepresentable", "cycles", "reused", "override"],
      },
      {
        title: "Conversion",
        headings: ["String formats", "Numeric types", "Object schemas", "File schemas", "Nullability"],
      },
      "Registries",
    ],
  },
  {
    title: "Codecs",
    slug: "codecs",
    headings: [
      "Inverting codecs",
      "Composability",
      "Type-safe inputs",
      "Async and safe variants",
      {
        title: "How encoding works",
        headings: ["Codecs", "Pipes", "Refinements", "Defaults and prefaults", "Catch", "Stringbool", "Transforms"],
      },
      {
        title: "Useful codecs",
        headings: [
          "stringToNumber",
          "stringToInt",
          "stringToBigInt",
          "numberToBigInt",
          "isoDatetimeToDate",
          "epochSecondsToDate",
          "epochMillisToDate",
          "json(schema)",
          "utf8ToBytes",
          "bytesToUtf8",
          "base64ToBytes",
          "base64urlToBytes",
          "hexToBytes",
          "stringToURL",
          "stringToHttpURL",
          "uriComponent",
        ],
      },
    ],
  },
  {
    title: "Ecosystem",
    slug: "ecosystem",
    headings: [
      "Resources",
      "API Libraries",
      "Form Integrations",
      "Zod to X",
      "X to Zod",
      "Mocking Libraries",
      "Powered by Zod",
      "Zod Utilities",
    ],
  },
  {
    title: "For library authors",
    slug: "library-authors",
    headings: [
      "Do I need to depend on Zod?",
      "How to configure peer dependencies?",
      "How to support Zod 4?",
      "Do I need to publish a new major version?",
      "How to support Zod 3 and Zod 4 simultaneously?",
      "How to support Zod and Zod Mini simultaneously?",
      "How to accept user-defined schemas?",
    ],
  },
  { title: "Zod", slug: "packages/zod" },
  {
    title: "Zod Mini",
    slug: "packages/mini",
    headings: [
      "Tree-shaking",
      { title: "When (not) to use Zod Mini", headings: ["DX", "Backend development", "Internet speed"] },
      { title: "ZodMiniType", headings: [".parse", ".check()", ".register()", ".brand()", ".clone(def)"] },
      "No default locale",
    ],
  },
  {
    title: "Zod Core",
    slug: "packages/core",
    headings: ["Schemas", "Internals", "Parsing", "Checks", "Errors", "Issues"],
  },
  {
    title: "Release notes",
    slug: "v4",
    headings: [
      "Versioning",
      "Why a new major version?",
      {
        title: "Benchmarks",
        headings: ["14x faster string parsing", "7x faster array parsing", "6.5x faster object parsing"],
      },
      "100x reduction in tsc instantiations",
      "2x reduction in core bundle size",
      { title: "Introducing Zod Mini", headings: ["6.6x reduction in core bundle size"] },
      { title: "Metadata", headings: ["The global registry", ".meta()"] },
      "JSON Schema conversion",
      "Recursive objects",
      "File schemas",
      "Internationalization",
      "Error pretty-printing",
      { title: "Top-level string formats", headings: ["Custom email regex"] },
      "Template literal types",
      "Number formats",
      "Stringbool",
      "Simplified error customization",
      "Upgraded z.discriminatedUnion()",
      "Multiple values in z.literal()",
      { title: "Refinements live inside schemas", headings: [".overwrite()"] },
      "An extensible foundation: zod/v4/core",
      "Wrapping up",
    ],
  },
  {
    title: "Migration guide",
    slug: "v4/changelog",
    headings: [
      {
        title: "Error customization",
        headings: ["deprecates message parameter", "drops invalid_type_error and required_error", "drops errorMap"],
      },
      {
        title: "ZodError",
        headings: [
          "changes to .message",
          "updates issue formats",
          "changes error map precedence",
          "deprecates .format()",
          "deprecates .flatten()",
          "drops .formErrors",
          "drops .errors",
          "deprecates .addIssue() and .addIssues()",
        ],
      },
      {
        title: "z.number()",
        headings: ["no infinite values", ".safe() no longer accepts floats", ".int() accepts safe integers only"],
      },
      {
        title: "z.string() updates",
        headings: [
          "deprecates .email() etc",
          "stricter .uuid()",
          "no padding in .base64url()",
          "drops z.string().ip()",
          "updates z.string().ipv6()",
          "drops z.string().cidr()",
        ],
      },
      "z.coerce updates",
      ".default() updates",
      {
        title: "z.object()",
        headings: [
          "defaults applied within optional fields",
          "deprecates .strict() and .passthrough()",
          "deprecates .strip()",
          "drops .nonstrict()",
          "drops .deepPartial()",
          "changes z.unknown() optionality",
          "deprecates .merge()",
        ],
      },
      "z.nativeEnum() deprecated",
      { title: "z.array()", headings: ["changes .nonempty() type"] },
      "z.promise() deprecated",
      { title: "z.function()", headings: ["adds .implementAsync()"] },
      {
        title: ".refine()",
        headings: ["ignores type predicates", "drops ctx.path", "drops function as second argument"],
      },
      "z.ostring(), etc dropped",
      { title: "z.literal()", headings: ["drops symbol support"] },
      "static .create() factories dropped",
      { title: "z.record()", headings: ["drops single argument usage", "improves enum support"] },
      { title: "z.intersection()", headings: ["throws Error on merge conflict"] },
      {
        title: "Internal changes",
        headings: [
          "updates generics",
          "adds z.core",
          "moves ._def",
          "drops ZodEffects",
          "adds ZodTransform",
          "drops ZodPreprocess",
          "drops ZodBranded",
        ],
      },
    ],
  },
  {
    title: "Versioning",
    slug: "v4/versioning",
    headings: [
      "**Update — July 8th, 2025**",
      "Versioning in Zod 4",
      { title: "Why?", headings: ["Why can't libraries just support v3 and v4 simultaneously?"] },
    ],
  },
] satisfies DocsV4Item[];
