export const languages = [
  { value: "ge", label: "Allemand", keywords: ["German"] },
  { value: "af", label: "Afrikaans" },
  { value: "ak", label: "Akan" },
  { value: "sq", label: "Albanais" },
  { value: "am", label: "Amharique" },
  { value: "en-GB", label: "Anglais (GB)", keywords: ["English"] },
  { value: "en-US", label: "Anglais (USA)", keywords: ["English"] },
  { value: "ar", label: "Arabe‎" },
  { value: "hy", label: "Arménien" },
  { value: "as", label: "Assamais" },
  { value: "az", label: "Azéri" },
  { value: "bm", label: "Bambara" },
  { value: "eu", label: "Basque" },
  { value: "bn", label: "Bengali" },
  { value: "my", label: "Birman (Myanmar)" },
  { value: "be", label: "Biélorusse" },
  { value: "bs", label: "Bosniaque" },
  { value: "bg", label: "Bulgare" },
  { value: "ca", label: "Catalan" },
  { value: "zh-Hans", label: "Chinois (simplifié)" },
  { value: "zh-Hant", label: "Chinois (traditionnel)" },
  { value: "si", label: "Cingalais" },
  { value: "co", label: "Corse" },
  { value: "ko", label: "Coréen" },
  { value: "hr", label: "Croate" },
  { value: "ht", label: "Créole haïtien" },
  { value: "da", label: "Danois" },
  { value: "dv", label: "Divehi‎" },
  { value: "es", label: "Espagnol", keywords: ["Spanish"] },
  { value: "eo", label: "Espéranto" },
  { value: "et", label: "Estonien" },
  { value: "ee", label: "Ewe" },
  { value: "fil", label: "Filipino" },
  { value: "fi", label: "Finnois" },
  { value: "fr", label: "Français", keywords: ["French", "Francais"] },
  { value: "fy", label: "Frison" },
  { value: "gl", label: "Galicien" },
  { value: "cy", label: "Gallois" },
  { value: "gd", label: "Gaélique écossais" },
  { value: "el", label: "Grec" },
  { value: "gn", label: "Guarani" },
  { value: "gu", label: "Gujarati" },
  { value: "ka", label: "Géorgien" },
  { value: "ha", label: "Haoussa" },
  { value: "hi", label: "Hindi" },
  { value: "hu", label: "Hongrois" },
  { value: "he", label: "Hébreu‎" },
  { value: "ig", label: "Igbo" },
  { value: "id", label: "Indonésien" },
  { value: "ga", label: "Irlandais" },
  { value: "xh", label: "IsiXhosa" },
  { value: "zu", label: "IsiZulu" },
  { value: "is", label: "Islandais" },
  { value: "it", label: "Italien" },
  { value: "ja", label: "Japonais" },
  { value: "jv", label: "Javanais" },
  { value: "kn", label: "Kannada" },
  { value: "kk", label: "Kazakh" },
  { value: "km", label: "Khmer" },
  { value: "rw", label: "Kinyarwanda" },
  { value: "ky", label: "Kirghize" },
  { value: "sw", label: "Kiswahili" },
  { value: "lo", label: "Laotien" },
  { value: "lv", label: "Letton" },
  { value: "ln", label: "Lingala" },
  { value: "lt", label: "Lituanien" },
  { value: "lg", label: "Luganda" },
  { value: "lb", label: "Luxembourgeois" },
  { value: "mk", label: "Macédonien" },
  { value: "ms", label: "Malais" },
  { value: "ml", label: "Malayalam" },
  { value: "mg", label: "Malgache" },
  { value: "mt", label: "Maltais" },
  { value: "mi", label: "Maori" },
  { value: "mr", label: "Marathi" },
  { value: "mn", label: "Mongol" },
  { value: "nl", label: "Néerlandais", keywords: ["Dutch", "Neerlandais"] },
  { value: "no", label: "Norvégien" },
  { value: "ny", label: "Nyanja (Chichewa)" },
  { value: "ne", label: "Népalais" },
  { value: "or", label: "Oriya" },
  { value: "om", label: "Oromo" },
  { value: "ur", label: "Ourdou‎" },
  { value: "uz", label: "Ouzbek" },
  { value: "ug", label: "Ouïghour" },
  { value: "ps", label: "Pachto" },
  { value: "pa", label: "Pendjabi" },
  { value: "fa", label: "Persan‎" },
  { value: "pl", label: "Polonais" },
  { value: "pt", label: "Portugais" },
  { value: "qu", label: "Quechua" },
  { value: "ro", label: "Roumain" },
  { value: "ru", label: "Russe" },
  { value: "sa", label: "Sanskrit" },
  { value: "sr", label: "Serbe (cyrillique)" },
  { value: "sr-Latn-SP", label: "Serbe (latin)" },
  { value: "sn", label: "Shona" },
  { value: "sd", label: "Sindhi" },
  { value: "sk", label: "Slovaque" },
  { value: "sl", label: "Slovène" },
  { value: "so", label: "Somali" },
  { value: "st", label: "Sotho" },
  { value: "nso", label: "Sotho du Nord" },
  { value: "su", label: "Soundanais" },
  { value: "sv", label: "Suédois" },
  { value: "tg", label: "Tadjik" },
  { value: "tl", label: "Tagalog" },
  { value: "ta", label: "Tamoul" },
  { value: "tt", label: "Tatar" },
  { value: "cs", label: "Tchèque" },
  { value: "te", label: "Telugu" },
  { value: "th", label: "Thaï" },
  { value: "ti", label: "Tigrigna" },
  { value: "ts", label: "Tsonga" },
  { value: "tr", label: "Turc" },
  { value: "tk", label: "Turkmène" },
  { value: "uk", label: "Ukrainien" },
  { value: "vi", label: "Vietnamien" },
  { value: "yo", label: "Yoruba" },
];
