// GENERATED by scripts/cache-schema.mjs — do not edit.
//
// A fingerprint of the cached payload's types and every file they are built
// from, used as the cache key version. It changes whenever the cached shape
// does, which is what makes a forgotten version bump impossible rather than
// merely discouraged. Regenerate with `npm run cache-schema`; `npm run lint`
// fails when it is stale.
//
// It does NOT change for a semantic correction that leaves the types alone —
// bump CACHE_SALT in config.ts for those. See the header of the generator.
//
// Sources:
//   src/types/index.ts
//   src/utils/wellKnownCatalog.ts
export const CACHE_SCHEMA = "e9c3d8c3aa";
