/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const BigNumberish = t.union("string", "number", "bigint");

export const RawArgs = t.union("RawArgsObject", "RawArgsArray");

export const RawArgsObject = t.iface([], {
  [t.indexKey]: t.union("MultiType", t.array("MultiType"), "RawArgs"),
});

export const RawArgsArray = t.array(t.union("MultiType", t.array("MultiType"), "RawArgs"));

export const MultiType = t.union("BigNumberish", "Uint256", "object", "boolean");

export const Uint256 = t.iface([], {
  low: "BigNumberish",
  high: "BigNumberish",
});

export const StarknetChainId = t.enumtype({
  SN_MAIN: "0x534e5f4d41494e",
  SN_GOERLI: "0x534e5f474f45524c49",
  SN_GOERLI2: "0x534e5f474f45524c4932",
});

export const RawCalldata = t.array("BigNumberish");

export const TransactionHashPrefix = t.enumtype({
  DECLARE: "0x6465636c617265",
  DEPLOY: "0x6465706c6f79",
  DEPLOY_ACCOUNT: "0x6465706c6f795f6163636f756e74",
  INVOKE: "0x696e766f6b65",
  L1_HANDLER: "0x6c315f68616e646c6572",
});

export const LegacyContractClass = t.iface([], {
  entry_points_by_type: "EntryPointsByType",
  abi: "Abi",
});

export const LegacyCompiledContract = t.iface([], {
  program: "Program",
});

export const CompressedProgram = t.name("string");

export const EntryPointsByType = t.iface([], {
  CONSTRUCTOR: t.array("ContractEntryPointFields"),
  EXTERNAL: t.array("ContractEntryPointFields"),
  L1_HANDLER: t.array("ContractEntryPointFields"),
});

export const Abi = t.array(t.union("FunctionAbi", "EventAbi", "StructAbi"));

export const AbiEntry = t.iface([], {
  name: "string",
  type: t.union(t.lit("felt"), t.lit("felt*"), "string"),
});

export const FunctionAbiType = t.enumtype({
  function: 0,
  l1_handler: 1,
  constructor: 2,
});

export const FunctionAbi = t.iface([], {
  inputs: t.array("AbiEntry"),
  name: "string",
  outputs: t.array("AbiEntry"),
  stateMutability: t.opt(t.lit("view")),
  state_mutability: t.opt("string"),
  type: "FunctionAbiType",
});

export const AbiStructs = t.iface([], {
  [t.indexKey]: "StructAbi",
});

export const StructAbi = t.iface([], {
  members: t.array(
    t.intersection(
      "AbiEntry",
      t.iface([], {
        offset: "number",
      })
    )
  ),
  name: "string",
  size: "number",
  type: t.lit("struct"),
});

export const EventAbi = t.name("any");

export const Program = t.iface([], {
  builtins: t.array("string"),
  data: t.array("string"),
});

export const ContractEntryPointFields = t.iface([], {
  selector: "string",
  offset: "string",
  builtins: t.opt("Builtins"),
});

export const Builtins = t.array("string");

export const CompiledSierra = t.name("SierraContractClass");

export const CompiledSierraCasm = t.name("CairoAssembly");

export const SierraContractClass = t.iface([], {
  sierra_program: "ByteCode",
  sierra_program_debug_info: "SierraProgramDebugInfo",
  contract_class_version: "string",
  entry_points_by_type: "SierraEntryPointsByType",
  abi: "Abi",
});

export const CairoAssembly = t.iface([], {
  prime: "string",
  compiler_version: "string",
  bytecode: "ByteCode",
  hints: t.array("any"),
  pythonic_hints: "PythonicHints",
  entry_points_by_type: "EntryPointsByType",
});

export const ByteCode = t.array("string");

export const PythonicHints = t.array(t.tuple("number", t.array("string")));

export const SierraProgramDebugInfo = t.iface([], {
  type_names: t.array(t.tuple("number", "string")),
  libfunc_names: t.array(t.tuple("number", "string")),
  user_func_names: t.array(t.tuple("number", "string")),
});

export const SierraEntryPointsByType = t.iface([], {
  CONSTRUCTOR: t.array("SierraContractEntryPointFields"),
  EXTERNAL: t.array("SierraContractEntryPointFields"),
  L1_HANDLER: t.array("SierraContractEntryPointFields"),
});

export const SierraContractEntryPointFields = t.iface([], {
  selector: "string",
  function_idx: "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  BigNumberish,
  RawArgs,
  RawArgsObject,
  RawArgsArray,
  MultiType,
  Uint256,
  StarknetChainId,
  RawCalldata,
  TransactionHashPrefix,
  LegacyContractClass,
  LegacyCompiledContract,
  CompressedProgram,
  EntryPointsByType,
  Abi,
  AbiEntry,
  FunctionAbiType,
  FunctionAbi,
  AbiStructs,
  StructAbi,
  EventAbi,
  Program,
  ContractEntryPointFields,
  Builtins,
  CompiledSierra,
  CompiledSierraCasm,
  SierraContractClass,
  CairoAssembly,
  ByteCode,
  PythonicHints,
  SierraProgramDebugInfo,
  SierraEntryPointsByType,
  SierraContractEntryPointFields,
};
export default exportedTypeSuite;
