export interface daisyUIColor {
  name: string;
  cssVariable: string;
  description: string;
  lightOklch: string;
  darkOklch: string;
  lightHex: string;
  lightBgHex: string;
  darkHex: string;
  darkBgHex: string;
  section: string;
}

// Base colors for backgrounds when not specified
const baseLightBgHex = "#ffffff"; // base-100 light
const baseDarkBgHex = "#1d232a"; // base-100 dark

export const Colors: daisyUIColor[] = [
  {
    name: "primary",
    cssVariable: "--color-primary",
    description: "Primary brand color, the main color of your brand",
    lightHex: "#422ad5",
    darkHex: "#605dff",
    lightOklch: "oklch(45% 0.24 277.023)",
    darkOklch: "oklch(58% 0.233 277.117)",
    lightBgHex: baseLightBgHex, // From primary-content
    darkBgHex: baseDarkBgHex,
    section: "Primary",
  },
  {
    name: "primary-content",
    cssVariable: "--color-primary-content",
    description: "Foreground content color to use on primary color",
    lightHex: "#e0e7ff",
    darkHex: "#edf1fe",
    lightOklch: "oklch(93% 0.034 272.788)",
    darkOklch: "oklch(96% 0.018 272.314)",
    lightBgHex: "#422ad5", // Background is primary
    darkBgHex: "#605dff",
    section: "Primary",
  },
  {
    name: "secondary",
    cssVariable: "--color-secondary",
    description: "Secondary brand color, the optional, secondary color of your brand",
    lightHex: "#f43098",
    darkHex: "#f43098",
    lightOklch: "oklch(65% 0.241 354.308)",
    darkOklch: "oklch(65% 0.241 354.308)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Secondary",
  },
  {
    name: "secondary-content",
    cssVariable: "--color-secondary-content",
    description: "Foreground content color to use on secondary color",
    lightHex: "#f9e4f0",
    darkHex: "#f9e4f0",
    lightOklch: "oklch(94% 0.028 342.258)",
    darkOklch: "oklch(94% 0.028 342.258)",
    lightBgHex: "#f43098", // Background is secondary
    darkBgHex: "#f43098",
    section: "Secondary",
  },
  {
    name: "accent",
    cssVariable: "--color-accent",
    description: "Accent brand color, the optional, accent color of your brand",
    lightHex: "#00d3bb",
    darkHex: "#00d3bb",
    lightOklch: "oklch(77% 0.152 181.912)",
    darkOklch: "oklch(77% 0.152 181.912)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Accent",
  },
  {
    name: "accent-content",
    cssVariable: "--color-accent-content",
    description: "Foreground content color to use on accent color",
    lightHex: "#084d49",
    darkHex: "#084d49",
    lightOklch: "oklch(38% 0.063 188.416)",
    darkOklch: "oklch(38% 0.063 188.416)",
    lightBgHex: "#00d3bb", // Background is accent
    darkBgHex: "#00d3bb",
    section: "Accent",
  },
  {
    name: "neutral",
    cssVariable: "--color-neutral",
    description: "Neutral dark color, for not-saturated parts of UI",
    lightHex: "#09090b",
    darkHex: "#09090b",
    lightOklch: "oklch(14% 0.005 285.823)",
    darkOklch: "oklch(14% 0.005 285.823)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Neutral",
  },
  {
    name: "neutral-content",
    cssVariable: "--color-neutral-content",
    description: "Foreground content color to use on neutral color",
    lightHex: "#e4e4e7",
    darkHex: "#e4e4e7",
    lightOklch: "oklch(92% 0.004 286.32)",
    darkOklch: "oklch(92% 0.004 286.32)",
    lightBgHex: "#09090b", // Background is neutral
    darkBgHex: "#09090b",
    section: "Neutral",
  },
  {
    name: "base-100",
    cssVariable: "--color-base-100",
    description: "Base surface color of page, used for blank backgrounds",
    lightHex: baseLightBgHex,
    darkHex: baseDarkBgHex,
    lightOklch: "oklch(100% 0 0)",
    darkOklch: "oklch(25.33% 0.016 252.42)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Base",
  },
  {
    name: "base-200",
    cssVariable: "--color-base-200",
    description: "Base color, darker shade, to create elevations",
    lightHex: "#f8f8f8",
    darkHex: "#191e24",
    lightOklch: "oklch(98% 0 0)",
    darkOklch: "oklch(23.26% 0.014 253.1)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Base",
  },
  {
    name: "base-300",
    cssVariable: "--color-base-300",
    description: "Base color, even more darker shade, to create elevations",
    lightHex: "#f8f8f8",
    darkHex: "#191e24",
    lightOklch: "oklch(98% 0 0)",
    darkOklch: "oklch(23.26% 0.014 253.1)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Base",
  },
  {
    name: "base-content",
    cssVariable: "--color-base-content",
    description: "Foreground content color to use on base color",
    lightHex: "#18181b",
    darkHex: "#ecf9ff",
    lightOklch: "oklch(21% 0.006 285.885)",
    darkOklch: "oklch(23.26% 0.014 253.1)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Base",
  },
  {
    name: "info",
    cssVariable: "--color-info",
    description: "Info color, For informative/helpful messages",
    lightHex: "#00bafe",
    darkHex: "#00bafe",
    lightOklch: "oklch(74% 0.16 232.661)",
    darkOklch: "oklch(74% 0.16 232.661)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Info",
  },
  {
    name: "info-content",
    cssVariable: "--color-info-content",
    description: "Info color, For informative/helpful messages",
    lightHex: "#042e49",
    darkHex: "#042e49",
    lightOklch: "oklch(29% 0.066 243.157)",
    darkOklch: "oklch(29% 0.066 243.157)",
    lightBgHex: "#00bafe",
    darkBgHex: "#00bafe",
    section: "Info",
  },
  {
    name: "success",
    cssVariable: "--color-success",
    description: "Success color, For success/safe messages",
    lightHex: "#00d390",
    darkHex: "#00d390",
    lightOklch: "oklch(76% 0.177 163.223)",
    darkOklch: "oklch(76% 0.177 163.223)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Success",
  },
  {
    name: "success-content",
    cssVariable: "--color-success-content",
    description: "Foreground content color to use on success color",
    lightHex: "#004c39",
    darkHex: "#004c39",
    lightOklch: "oklch(37% 0.077 168.94)",
    darkOklch: "oklch(37% 0.077 168.94)",
    lightBgHex: "#00d390",
    darkBgHex: "#00d390",
    section: "Success",
  },
  {
    name: "warning",
    cssVariable: "--color-warning",
    description: "Warning color, For warning/caution messages",
    lightHex: "#fcb700",
    darkHex: "#fcb700",
    lightOklch: "oklch(82% 0.189 84.429)",
    darkOklch: "oklch(82% 0.189 84.429)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Warning",
  },
  {
    name: "warning-content",
    cssVariable: "--color-warning-content",
    description: "Foreground content color to use on warning color",
    lightHex: "#793205",
    darkHex: "#793205",
    lightOklch: "oklch(41% 0.112 45.904)",
    darkOklch: "oklch(41% 0.112 45.904)",
    lightBgHex: "#fcb700",
    darkBgHex: "#fcb700",
    section: "Warning",
  },
  {
    name: "error",
    cssVariable: "--color-error",
    description: "Error color, for error/danger/destructive messages",
    lightHex: "#ff637d",
    darkHex: "#ff637d",
    lightOklch: "oklch(71% 0.194 13.428)",
    darkOklch: "oklch(71% 0.194 13.428)",
    lightBgHex: baseLightBgHex,
    darkBgHex: baseDarkBgHex,
    section: "Error",
  },
  {
    name: "error-content",
    cssVariable: "--color-error-content",
    description: "Foreground content color to use on error color",
    lightHex: "#4d0218",
    darkHex: "#4d0218",
    lightOklch: "oklch(27% 0.105 12.094)",
    darkOklch: "oklch(27% 0.105 12.094)",
    lightBgHex: "#ff637d",
    darkBgHex: "#ff637d",
    section: "Error",
  },
];
