export enum L {
  Original_Text = "Original text",
  Translated_text = "Translated text",
  Saved_search_results = "Saved search results",
  History = "History",
  Setting = "Settings",
  Register_API_Key = "Register API Key",
  View = "View",
  Save = "Save",
  Copy = "Copy",
  Delete = "Delete",
  Google = "Google",
  Papago = "Papago",
  Issue_Papago_token = "Issue Papago token",
  Issue_a_token_from_the_bottom_menu = "Issue a token from the bottom menu",
  It_does_not_have_translated_text = "It does not have translated text",
  Disabled = "Disabled",
  Invalid_input = "Invalid input",
  Fail_to_save = "Fail to save",
  Fail = "Fail",
  Saved = "Saved",
};
