import {
  VMGuestPowerAction,
  VmPowerState,
  VMPowerAction,
  VmStoragePolicyComplianceStatus,
  HostPowerState,
} from "./types";
import { Color, Icon, Image } from "@raycast/api";

export const PowerModeIcons = new Map<VmPowerState, Image.ImageLike>([
  [VmPowerState.POWERED_ON, { source: "icons/vm/vm_running.svg" }],
  [VmPowerState.POWERED_OFF, { source: "icons/vm/vm.svg" }],
  [VmPowerState.SUSPENDED, { source: "icons/vm/vm_paused.svg" }],
]);
export const PowerModeIconsMetadata = new Map<VmPowerState, Image.ImageLike>([
  [VmPowerState.POWERED_ON, { source: "icons/vm/vm_running.svg" }],
  [VmPowerState.POWERED_OFF, { source: "icons/vm/vm.svg" }],
  [VmPowerState.SUSPENDED, { source: "icons/vm/vm_paused.svg" }],
]);
export const PowerModeTextMetadata = new Map<VmPowerState, string>([
  [VmPowerState.POWERED_ON, "Powered On"],
  [VmPowerState.POWERED_OFF, "Powered Off"],
  [VmPowerState.SUSPENDED, "Suspended"],
]);

export const VMGuestPowerActionIcons = new Map<VMGuestPowerAction, Image.ImageLike>([
  [VMGuestPowerAction.REBOOT, { source: "icons/power/reset.svg" }],
  [VMGuestPowerAction.STANDBUY, { source: "icons/power/suspend.svg" }],
  [VMGuestPowerAction.SHUTDOWN, { source: "icons/power/poweroff.svg" }],
]);
export const VMPowerActionIcons = new Map<VMPowerAction, Image.ImageLike>([
  [VMPowerAction.RESET, { source: "icons/power/reset.svg" }],
  [VMPowerAction.SUSPEND, { source: "icons/power/suspend.svg" }],
  [VMPowerAction.STOP, { source: "icons/power/poweroff.svg" }],
  [VMPowerAction.START, { source: "icons/power/poweron.svg" }],
]);

export const VMStoragePolicyComplianceText = new Map<VmStoragePolicyComplianceStatus, string>([
  [VmStoragePolicyComplianceStatus.COMPLIANT, "Compliant"],
  [VmStoragePolicyComplianceStatus.NON_COMPLIANT, "Non Compliant"],
  [VmStoragePolicyComplianceStatus.NOT_APPLICABLE, "Not Applicable"],
  [VmStoragePolicyComplianceStatus.OUT_OF_DATE, "Out of Date"],
  [VmStoragePolicyComplianceStatus.UNKNOWN_COMPLIANCE, "Compliance"],
]);
export const VMStoragePolicyComplianceIcon = new Map<VmStoragePolicyComplianceStatus, Image.ImageLike>([
  [VmStoragePolicyComplianceStatus.COMPLIANT, Icon.CheckCircle],
  [VmStoragePolicyComplianceStatus.NON_COMPLIANT, Icon.XMarkCircle],
  [VmStoragePolicyComplianceStatus.NOT_APPLICABLE, Icon.Warning],
  [VmStoragePolicyComplianceStatus.OUT_OF_DATE, Icon.Warning],
  [VmStoragePolicyComplianceStatus.UNKNOWN_COMPLIANCE, Icon.Warning],
]);
export const VMStoragePolicyComplianceColor = new Map<VmStoragePolicyComplianceStatus, Color>([
  [VmStoragePolicyComplianceStatus.COMPLIANT, Color.Green],
  [VmStoragePolicyComplianceStatus.NON_COMPLIANT, Color.Red],
  [VmStoragePolicyComplianceStatus.NOT_APPLICABLE, Color.PrimaryText],
  [VmStoragePolicyComplianceStatus.OUT_OF_DATE, Color.Yellow],
  [VmStoragePolicyComplianceStatus.UNKNOWN_COMPLIANCE, Color.Yellow],
]);

export const OsTextMetadata = new Map<string, string>([
  ["DOS", "MS-DOS"],
  ["WIN_31", "Windows 3.1"],
  ["WIN_95", "Windows 95"],
  ["WIN_98", "Windows 98"],
  ["WIN_ME", "Windows Millennium Edition"],
  ["WIN_NT", "Windows NT 4"],
  ["WIN_2000_PRO", "Windows 2000 Professional"],
  ["WIN_2000_SERV", "Windows 2000 Server"],
  ["WIN_2000_ADV_SERV", "Windows 2000 Advanced Server"],
  ["WIN_XP_HOME", "Windows XP Home Edition"],
  ["WIN_XP_PRO", "Windows XP Professional"],
  ["WIN_XP_PRO_64", "Windows XP Professional Edition (64 bit)"],
  ["WIN_NET_WEB", "Windows Server 2003, Web Edition"],
  ["WIN_NET_STANDARD", "Windows Server 2003, Standard Edition"],
  ["WIN_NET_ENTERPRISE", "Windows Server 2003, Enterprise Edition"],
  ["WIN_NET_DATACENTER", "Windows Server 2003, Datacenter Edition"],
  ["WIN_NET_BUSINESS", "Windows Small Business Server 2003"],
  ["WIN_NET_STANDARD_64", "Windows Server 2003, Standard Edition (64 bit)"],
  ["WIN_NET_ENTERPRISE_64", "Windows Server 2003, Enterprise Edition (64 bit)"],
  ["WIN_LONGHORN", "Windows Longhorn (experimental)"],
  ["WIN_LONGHORN_64", "Windows Longhorn (64 bit) (experimental)"],
  ["WIN_NET_DATACENTER_64", "Windows Server 2003, Datacenter Edition (64 bit) (experimental)"],
  ["WIN_VISTA", "Windows Vista"],
  ["WIN_VISTA_64", "Windows Vista (64 bit)"],
  ["WINDOWS_7", "Windows 7"],
  ["WINDOWS_7_64", "Windows 7 (64 bit)"],
  ["WINDOWS_7_SERVER_64", "Windows Server 2008 R2 (64 bit)"],
  ["WINDOWS_8", "Windows 8"],
  ["WINDOWS_8_64", "Windows 8 (64 bit)"],
  ["WINDOWS_8_SERVER_64", "Windows 8 Server (64 bit)"],
  ["WINDOWS_9", "Windows 10"],
  ["WINDOWS_9_64", "Windows 10 (64 bit)"],
  ["WINDOWS_9_SERVER_64", "Windows 10 Server (64 bit)"],
  ["WINDOWS_11_64", "Windows 11 (64 bit)"],
  ["WINDOWS_12_64", "Windows 12 (64 bit)"],
  ["WINDOWS_HYPERV", "Windows Hyper-V"],
  ["WINDOWS_SERVER_2019", "Windows Server 2019"],
  ["WINDOWS_SERVER_2021", "Windows Server 2022"],
  ["WINDOWS_SERVER_2025", "Windows Server 2025"],
  ["FREEBSD", "FreeBSD 10 or earlier"],
  ["FREEBSD_64", "FreeBSD 10 x64 or earlier"],
  ["FREEBSD_11", "FreeBSD 11"],
  ["FREEBSD_12", "FreeBSD 12"],
  ["FREEBSD_13", "FreeBSD 13 or later"],
  ["FREEBSD_11_64", "FreeBSD 11 x64"],
  ["FREEBSD_12_64", "FreeBSD 12 x64"],
  ["FREEBSD_13_64", "FreeBSD 13 x64 or later"],
  ["FREEBSD_14_64", "FreeBSD 14 x64 or later"],
  ["REDHAT", "Red Hat Linux 2.1"],
  ["RHEL_2", "Red Hat Enterprise Linux 2"],
  ["RHEL_3", "Red Hat Enterprise Linux 3"],
  ["RHEL_3_64", "Red Hat Enterprise Linux 3 (64 bit)"],
  ["RHEL_4", "Red Hat Enterprise Linux 4"],
  ["RHEL_4_64", "Red Hat Enterprise Linux 4 (64 bit)"],
  ["RHEL_5", "Red Hat Enterprise Linux 5"],
  ["RHEL_5_64", "Red Hat Enterprise Linux 5 (64 bit) (experimental)"],
  ["RHEL_6", "Red Hat Enterprise Linux 6"],
  ["RHEL_6_64", "Red Hat Enterprise Linux 6 (64 bit)"],
  ["RHEL_7", "Red Hat Enterprise Linux 7"],
  ["RHEL_7_64", "Red Hat Enterprise Linux 7 (64 bit)"],
  ["RHEL_8_64", "Red Hat Enterprise Linux 8 (64 bit)"],
  ["RHEL_9_64", "Red Hat Enterprise Linux 9 (64 bit)"],
  ["CENTOS", "CentOS 4⁄5"],
  ["CENTOS_64", "CentOS 4⁄5 (64-bit)"],
  ["CENTOS_6", "CentOS 6"],
  ["CENTOS_6_64", "CentOS 6 (64-bit)"],
  ["CENTOS_7", "CentOS 7"],
  ["CENTOS_7_64", "CentOS 7 (64-bit)"],
  ["CENTOS_8_64", "CentOS 8 (64-bit)"],
  ["CENTOS_9_64", "CentOS 9 (64-bit)"],
  ["ORACLE_LINUX", "Oracle Linux 4⁄5"],
  ["ORACLE_LINUX_64", "Oracle Linux 4⁄5 (64-bit)"],
  ["ORACLE_LINUX_6", "Oracle Linux 6"],
  ["ORACLE_LINUX_6_64", "Oracle Linux 6 (64-bit)"],
  ["ORACLE_LINUX_7", "Oracle Linux 7"],
  ["ORACLE_LINUX_7_64", "Oracle Linux 7 (64-bit)"],
  ["ORACLE_LINUX_8_64", "Oracle Linux 8 (64-bit)"],
  ["ORACLE_LINUX_9_64", "Oracle Linux 9 (64-bit)"],
  ["SUSE", "Suse Linux"],
  ["SUSE_64", "Suse Linux (64 bit)"],
  ["SLES", "Suse Linux Enterprise Server 9"],
  ["SLES_64", "Suse Linux Enterprise Server 9 (64 bit)"],
  ["SLES_10", "Suse linux Enterprise Server 10"],
  ["SLES_10_64", "Suse Linux Enterprise Server 10 (64 bit) (experimental)"],
  ["SLES_11", "Suse linux Enterprise Server 11"],
  ["SLES_11_64", "Suse Linux Enterprise Server 11 (64 bit)"],
  ["SLES_12", "Suse linux Enterprise Server 12"],
  ["SLES_12_64", "Suse Linux Enterprise Server 12 (64 bit)"],
  ["SLES_15_64", "Suse Linux Enterprise Server 15 (64 bit)"],
  ["SLES_16_64", "Suse Linux Enterprise Server 16 (64 bit)"],
  ["NLD_9", "Novell Linux Desktop 9"],
  ["OES", "Open Enterprise Server"],
  ["SJDS", "Sun Java Desktop System"],
  ["MANDRAKE", "Mandrake Linux"],
  ["MANDRIVA", "Mandriva Linux"],
  ["MANDRIVA_64", "Mandriva Linux (64 bit)"],
  ["TURBO_LINUX", "Turbolinux"],
  ["TURBO_LINUX_64", "Turbolinux (64 bit)"],
  ["UBUNTU", "Ubuntu Linux"],
  ["UBUNTU_64", "Ubuntu Linux (64 bit)"],
  ["DEBIAN_4", "Debian GNU/Linux 4"],
  ["DEBIAN_4_64", "Debian GNU/Linux 4 (64 bit)"],
  ["DEBIAN_5", "Debian GNU/Linux 5"],
  ["DEBIAN_5_64", "Debian GNU/Linux 5 (64 bit)"],
  ["DEBIAN_6", "Debian GNU/Linux 6"],
  ["DEBIAN_6_64", "Debian GNU/Linux 6 (64 bit)"],
  ["DEBIAN_7", "Debian GNU/Linux 7"],
  ["DEBIAN_7_64", "Debian GNU/Linux 7 (64 bit)"],
  ["DEBIAN_8", "Debian GNU/Linux 8"],
  ["DEBIAN_8_64", "Debian GNU/Linux 8 (64 bit)"],
  ["DEBIAN_9", "Debian GNU/Linux 9"],
  ["DEBIAN_9_64", "Debian GNU/Linux 9 (64 bit)"],
  ["DEBIAN_10", "Debian GNU/Linux 10"],
  ["DEBIAN_10_64", "Debian GNU/Linux 10 (64 bit)"],
  ["DEBIAN_11", "Debian GNU/Linux 11"],
  ["DEBIAN_11_64", "Debian GNU/Linux 11 (64 bit)"],
  ["DEBIAN_12", "Debian GNU/Linux 12"],
  ["DEBIAN_12_64", "Debian GNU/Linux 12 (64 bit)"],
  ["ASIANUX_3", "Asianux Server 3"],
  ["ASIANUX_3_64", "Asianux Server 3 (64 bit)"],
  ["ASIANUX_4", "Asianux Server 4"],
  ["ASIANUX_4_64", "Asianux Server 4 (64 bit)"],
  ["ASIANUX_5_64", "Asianux Server 5 (64 bit)"],
  ["ASIANUX_7_64", "Asianux Server 7 (64 bit)"],
  ["ASIANUX_8_64", "Asianux Server 8 (64 bit)"],
  ["ASIANUX_9_64", "Asianux Server 9 (64 bit)"],
  ["OPENSUSE", "OpenSUSE Linux"],
  ["OPENSUSE_64", "OpenSUSE Linux (64 bit)"],
  ["FEDORA", "Fedora Linux"],
  ["FEDORA_64", "Fedora Linux (64 bit)"],
  ["COREOS_64", "CoreOS Linux (64 bit)"],
  ["VMWARE_PHOTON_64", "VMware Photon (64 bit)"],
  ["OTHER_24X_LINUX", "Linux 2.4x Kernel"],
  ["OTHER_24X_LINUX_64", "Linux 2.4x Kernel (64 bit) (experimental)"],
  ["OTHER_26X_LINUX", "Linux 2.6x Kernel"],
  ["OTHER_26X_LINUX_64", "Linux 2.6x Kernel (64 bit) (experimental)"],
  ["OTHER_3X_LINUX", "Linux 3.x Kernel"],
  ["OTHER_3X_LINUX_64", "Linux 3.x Kernel (64 bit)"],
  ["OTHER_4X_LINUX", "Linux 4.x Kernel"],
  ["OTHER_4X_LINUX_64", "Linux 4.x Kernel (64 bit)"],
  ["OTHER_5X_LINUX", "Linux 5.x Kernel"],
  ["OTHER_5X_LINUX_64", "Linux 5.x Kernel (64 bit)"],
  ["OTHER_6X_LINUX", "Linux 6.x Kernel"],
  ["OTHER_6X_LINUX_64", "Linux 6.x Kernel (64 bit)"],
  ["OTHER_LINUX", "Linux 2.2x Kernel"],
  ["GENERIC_LINUX", "Other Linux"],
  ["OTHER_LINUX_64", "Linux (64 bit) (experimental)"],
  ["SOLARIS_6", "Solaris 6"],
  ["SOLARIS_7", "Solaris 7"],
  ["SOLARIS_8", "Solaris 8"],
  ["SOLARIS_9", "Solaris 9"],
  ["SOLARIS_10", "Solaris 10 (32 bit) (experimental)"],
  ["SOLARIS_10_64", "Solaris 10 (64 bit) (experimental)"],
  ["SOLARIS_11_64", "Solaris 11 (64 bit)"],
  ["OS2", "OS/2"],
  ["ECOMSTATION", "eComStation 1.x"],
  ["ECOMSTATION_2", "eComStation 2.0"],
  ["NETWARE_4", "Novell NetWare 4"],
  ["NETWARE_5", "Novell NetWare 5.1"],
  ["NETWARE_6", "Novell NetWare 6.x"],
  ["OPENSERVER_5", "SCO OpenServer 5"],
  ["OPENSERVER_6", "SCO OpenServer 6"],
  ["UNIXWARE_7", "SCO UnixWare 7"],
  ["DARWIN", "Mac OS 10.5"],
  ["DARWIN_64", "Mac OS 10.5 (64 bit)"],
  ["DARWIN_10", "Mac OS 10.6"],
  ["DARWIN_10_64", "Mac OS 10.6 (64 bit)"],
  ["DARWIN_11", "Mac OS 10.7"],
  ["DARWIN_11_64", "Mac OS 10.7 (64 bit)"],
  ["DARWIN_12_64", "Mac OS 10.8 (64 bit)"],
  ["DARWIN_13_64", "Mac OS 10.9 (64 bit)"],
  ["DARWIN_14_64", "Mac OS 10.10 (64 bit)"],
  ["DARWIN_15_64", "Mac OS 10.11 (64 bit)"],
  ["DARWIN_16_64", "Mac OS 10.12 (64 bit)"],
  ["DARWIN_17_64", "Mac OS 10.13 (64 bit)"],
  ["DARWIN_18_64", "Mac OS 10.14 (64 bit)"],
  ["DARWIN_19_64", "Mac OS 10.15 (64 bit)"],
  ["DARWIN_20_64", "Mac OS 11 (64 bit)"],
  ["DARWIN_21_64", "Mac OS 12 (64 bit)"],
  ["DARWIN_22_64", "Mac OS 13 (64 bit)"],
  ["DARWIN_23_64", "Mac OS 14 (64 bit)"],
  ["VMKERNEL", "VMware ESX 4"],
  ["VMKERNEL_5", "VMware ESX 5"],
  ["VMKERNEL_6", "VMware ESX 6"],
  ["VMKERNEL_65", "VMware ESX 6.5"],
  ["VMKERNEL_7", "VMware ESX 7"],
  ["VMKERNEL_8", "VMware ESX 8"],
  ["AMAZONLINUX2_64", "Amazon Linux 2 (64 bit)"],
  ["AMAZONLINUX3_64", "Amazon Linux 3 (64 bit)"],
  ["CRXPOD_1", "CRX Pod 1"],
  ["ROCKYLINUX_64", "Rocky Linux (64-bit)"],
  ["ALMALINUX_64", "AlmaLinux (64-bit)"],
  ["OTHER", "Other Operating System"],
  ["OTHER_64", "Other Operating System (64 bit) (experimental)"],
]);
export const OsIconsMetadata = new Map<string, Image.ImageLike>([
  ["DOS", "icons/os/windows.png"],
  ["WIN_31", "icons/os/windows.png"],
  ["WIN_95", "icons/os/windows.png"],
  ["WIN_98", "icons/os/windows.png"],
  ["WIN_ME", "icons/os/windows.png"],
  ["WIN_NT", "icons/os/windows.png"],
  ["WIN_2000_PRO", "icons/os/windows.png"],
  ["WIN_2000_SERV", "icons/os/windows.png"],
  ["WIN_2000_ADV_SERV", "icons/os/windows.png"],
  ["WIN_XP_HOME", "icons/os/windows.png"],
  ["WIN_XP_PRO", "icons/os/windows.png"],
  ["WIN_XP_PRO_64", "icons/os/windows.png"],
  ["WIN_NET_WEB", "icons/os/windows.png"],
  ["WIN_NET_STANDARD", "icons/os/windows.png"],
  ["WIN_NET_ENTERPRISE", "icons/os/windows.png"],
  ["WIN_NET_DATACENTER", "icons/os/windows.png"],
  ["WIN_NET_BUSINESS", "icons/os/windows.png"],
  ["WIN_NET_STANDARD_64", "icons/os/windows.png"],
  ["WIN_NET_ENTERPRISE_64", "icons/os/windows.png"],
  ["WIN_LONGHORN", "icons/os/windows.png"],
  ["WIN_LONGHORN_64", "icons/os/windows.png"],
  ["WIN_NET_DATACENTER_64", "icons/os/windows.png"],
  ["WIN_VISTA", "icons/os/windows.png"],
  ["WIN_VISTA_64", "icons/os/windows.png"],
  ["WINDOWS_7", "icons/os/windows.png"],
  ["WINDOWS_7_64", "icons/os/windows.png"],
  ["WINDOWS_7_SERVER_64", "icons/os/windows.png"],
  ["WINDOWS_8", "icons/os/windows.png"],
  ["WINDOWS_8_64", "icons/os/windows.png"],
  ["WINDOWS_8_SERVER_64", "icons/os/windows.png"],
  ["WINDOWS_9", "icons/os/windows.png"],
  ["WINDOWS_9_64", "icons/os/windows.png"],
  ["WINDOWS_9_SERVER_64", "icons/os/windows.png"],
  ["WINDOWS_11_64", "icons/os/windows.png"],
  ["WINDOWS_12_64", "icons/os/windows.png"],
  ["WINDOWS_HYPERV", "icons/os/windows.png"],
  ["WINDOWS_SERVER_2019", "icons/os/windows.png"],
  ["WINDOWS_SERVER_2021", "icons/os/windows.png"],
  ["WINDOWS_SERVER_2025", "icons/os/windows.png"],
  ["FREEBSD", "icons/os/bsd.png"],
  ["FREEBSD_64", "icons/os/bsd.png"],
  ["FREEBSD_11", "icons/os/bsd.png"],
  ["FREEBSD_12", "icons/os/bsd.png"],
  ["FREEBSD_13", "icons/os/bsd.png"],
  ["FREEBSD_11_64", "icons/os/bsd.png"],
  ["FREEBSD_12_64", "icons/os/bsd.png"],
  ["FREEBSD_13_64", "icons/os/bsd.png"],
  ["FREEBSD_14_64", "icons/os/bsd.png"],
  ["REDHAT", "icons/os/linux.png"],
  ["RHEL_2", "icons/os/linux.png"],
  ["RHEL_3", "icons/os/linux.png"],
  ["RHEL_3_64", "icons/os/linux.png"],
  ["RHEL_4", "icons/os/linux.png"],
  ["RHEL_4_64", "icons/os/linux.png"],
  ["RHEL_5", "icons/os/linux.png"],
  ["RHEL_5_64", "icons/os/linux.png"],
  ["RHEL_6", "icons/os/linux.png"],
  ["RHEL_6_64", "icons/os/linux.png"],
  ["RHEL_7", "icons/os/linux.png"],
  ["RHEL_7_64", "icons/os/linux.png"],
  ["RHEL_8_64", "icons/os/linux.png"],
  ["RHEL_9_64", "icons/os/linux.png"],
  ["CENTOS", "icons/os/linux.png"],
  ["CENTOS_64", "icons/os/linux.png"],
  ["CENTOS_6", "icons/os/linux.png"],
  ["CENTOS_6_64", "icons/os/linux.png"],
  ["CENTOS_7", "icons/os/linux.png"],
  ["CENTOS_7_64", "icons/os/linux.png"],
  ["CENTOS_8_64", "icons/os/linux.png"],
  ["CENTOS_9_64", "icons/os/linux.png"],
  ["ORACLE_LINUX", "icons/os/linux.png"],
  ["ORACLE_LINUX_64", "icons/os/linux.png"],
  ["ORACLE_LINUX_6", "icons/os/linux.png"],
  ["ORACLE_LINUX_6_64", "icons/os/linux.png"],
  ["ORACLE_LINUX_7", "icons/os/linux.png"],
  ["ORACLE_LINUX_7_64", "icons/os/linux.png"],
  ["ORACLE_LINUX_8_64", "icons/os/linux.png"],
  ["ORACLE_LINUX_9_64", "icons/os/linux.png"],
  ["SUSE", "icons/os/linux.png"],
  ["SUSE_64", "icons/os/linux.png"],
  ["SLES", "icons/os/linux.png"],
  ["SLES_64", "icons/os/linux.png"],
  ["SLES_10", "icons/os/linux.png"],
  ["SLES_10_64", "icons/os/linux.png"],
  ["SLES_11", "icons/os/linux.png"],
  ["SLES_11_64", "icons/os/linux.png"],
  ["SLES_12", "icons/os/linux.png"],
  ["SLES_12_64", "icons/os/linux.png"],
  ["SLES_15_64", "icons/os/linux.png"],
  ["SLES_16_64", "icons/os/linux.png"],
  ["NLD_9", ""],
  ["OES", ""],
  ["SJDS", ""],
  ["MANDRAKE", "icons/os/linux.png"],
  ["MANDRIVA", "icons/os/linux.png"],
  ["MANDRIVA_64", "icons/os/linux.png"],
  ["TURBO_LINUX", "icons/os/linux.png"],
  ["TURBO_LINUX_64", "icons/os/linux.png"],
  ["UBUNTU", "icons/os/linux.png"],
  ["UBUNTU_64", "icons/os/linux.png"],
  ["DEBIAN_4", "icons/os/linux.png"],
  ["DEBIAN_4_64", "icons/os/linux.png"],
  ["DEBIAN_5", "icons/os/linux.png"],
  ["DEBIAN_5_64", "icons/os/linux.png"],
  ["DEBIAN_6", "icons/os/linux.png"],
  ["DEBIAN_6_64", "icons/os/linux.png"],
  ["DEBIAN_7", "icons/os/linux.png"],
  ["DEBIAN_7_64", "icons/os/linux.png"],
  ["DEBIAN_8", "icons/os/linux.png"],
  ["DEBIAN_8_64", "icons/os/linux.png"],
  ["DEBIAN_9", "icons/os/linux.png"],
  ["DEBIAN_9_64", "icons/os/linux.png"],
  ["DEBIAN_10", "icons/os/linux.png"],
  ["DEBIAN_10_64", "icons/os/linux.png"],
  ["DEBIAN_11", "icons/os/linux.png"],
  ["DEBIAN_11_64", "icons/os/linux.png"],
  ["DEBIAN_12", "icons/os/linux.png"],
  ["DEBIAN_12_64", "icons/os/linux.png"],
  ["ASIANUX_3", "icons/os/linux.png"],
  ["ASIANUX_3_64", "icons/os/linux.png"],
  ["ASIANUX_4", "icons/os/linux.png"],
  ["ASIANUX_4_64", "icons/os/linux.png"],
  ["ASIANUX_5_64", "icons/os/linux.png"],
  ["ASIANUX_7_64", "icons/os/linux.png"],
  ["ASIANUX_8_64", "icons/os/linux.png"],
  ["ASIANUX_9_64", "icons/os/linux.png"],
  ["OPENSUSE", "icons/os/linux.png"],
  ["OPENSUSE_64", "icons/os/linux.png"],
  ["FEDORA", "icons/os/linux.png"],
  ["FEDORA_64", "icons/os/linux.png"],
  ["COREOS_64", "icons/os/linux.png"],
  ["VMWARE_PHOTON_64", "icons/os/linux.png"],
  ["OTHER_24X_LINUX", "icons/os/linux.png"],
  ["OTHER_24X_LINUX_64", "icons/os/linux.png"],
  ["OTHER_26X_LINUX", "icons/os/linux.png"],
  ["OTHER_26X_LINUX_64", "icons/os/linux.png"],
  ["OTHER_3X_LINUX", "icons/os/linux.png"],
  ["OTHER_3X_LINUX_64", "icons/os/linux.png"],
  ["OTHER_4X_LINUX", "icons/os/linux.png"],
  ["OTHER_4X_LINUX_64", "icons/os/linux.png"],
  ["OTHER_5X_LINUX", "icons/os/linux.png"],
  ["OTHER_5X_LINUX_64", "icons/os/linux.png"],
  ["OTHER_6X_LINUX", "icons/os/linux.png"],
  ["OTHER_6X_LINUX_64", "icons/os/linux.png"],
  ["OTHER_LINUX", "icons/os/linux.png"],
  ["GENERIC_LINUX", "icons/os/linux.png"],
  ["OTHER_LINUX_64", "icons/os/linux.png"],
  ["SOLARIS_6", ""],
  ["SOLARIS_7", ""],
  ["SOLARIS_8", ""],
  ["SOLARIS_9", ""],
  ["SOLARIS_10", ""],
  ["SOLARIS_10_64", ""],
  ["SOLARIS_11_64", ""],
  ["OS2", ""],
  ["ECOMSTATION", ""],
  ["ECOMSTATION_2", ""],
  ["NETWARE_4", ""],
  ["NETWARE_5", ""],
  ["NETWARE_6", ""],
  ["OPENSERVER_5", ""],
  ["OPENSERVER_6", ""],
  ["UNIXWARE_7", ""],
  ["DARWIN", "icons/os/macos.png"],
  ["DARWIN_64", "icons/os/macos.png"],
  ["DARWIN_10", "icons/os/macos.png"],
  ["DARWIN_10_64", "icons/os/macos.png"],
  ["DARWIN_11", "icons/os/macos.png"],
  ["DARWIN_11_64", "icons/os/macos.png"],
  ["DARWIN_12_64", "icons/os/macos.png"],
  ["DARWIN_13_64", "icons/os/macos.png"],
  ["DARWIN_14_64", "icons/os/macos.png"],
  ["DARWIN_15_64", "icons/os/macos.png"],
  ["DARWIN_16_64", "icons/os/macos.png"],
  ["DARWIN_17_64", "icons/os/macos.png"],
  ["DARWIN_18_64", "icons/os/macos.png"],
  ["DARWIN_19_64", "icons/os/macos.png"],
  ["DARWIN_20_64", "icons/os/macos.png"],
  ["DARWIN_21_64", "icons/os/macos.png"],
  ["DARWIN_22_64", "icons/os/macos.png"],
  ["DARWIN_23_64", "icons/os/macos.png"],
  ["VMKERNEL", ""],
  ["VMKERNEL_5", ""],
  ["VMKERNEL_6", ""],
  ["VMKERNEL_65", ""],
  ["VMKERNEL_7", ""],
  ["VMKERNEL_8", ""],
  ["AMAZONLINUX2_64", "icons/os/linux.png"],
  ["AMAZONLINUX3_64", "icons/os/linux.png"],
  ["CRXPOD_1", ""],
  ["ROCKYLINUX_64", "icons/os/linux.png"],
  ["ALMALINUX_64", "icons/os/linux.png"],
  ["OTHER", ""],
  ["OTHER_64", ""],
]);

export const HostPowerStateIcon = new Map<HostPowerState, Image.ImageLike>([
  [HostPowerState.POWERED_ON, { source: "icons/host/host_on.svg" }],
  [HostPowerState.POWERED_OFF, { source: "icons/host/host_off.svg" }],
  [HostPowerState.STANDBY, { source: "icons/host/host_off.svg" }],
]);
export const HostPowerStateIconMetadata = new Map<HostPowerState, Image.ImageLike>([
  [HostPowerState.POWERED_ON, { source: "icons/host/host_on.svg" }],
  [HostPowerState.POWERED_OFF, { source: "icons/host/host_off.svg" }],
  [HostPowerState.STANDBY, { source: "icons/host/host_off.svg" }],
]);
export const HostPowerStateTextMetadata = new Map<HostPowerState, string>([
  [HostPowerState.POWERED_ON, "Powered On"],
  [HostPowerState.POWERED_OFF, "Powered Off"],
  [HostPowerState.STANDBY, "Standby"],
]);
