// Tool metadata lives in `tools.json`, which is generated by
// `npm run generate-tools` and checked in. This module adds types and
// display helpers on top of it.

import { Icon } from "@raycast/api";

import data from "./tools.json";

export interface ToolEntry {
  name: string;
  category: string;
  route: string;
  deepLink: string;
  description: string;
  supportsInput: boolean;
  /** Name of a Raycast `Icon.*` enum member (e.g. "CodeBlock", "Lock"). */
  iconName: string;
  keywords: string[];
}

export const tools: ToolEntry[] = data as ToolEntry[];

const ICON_REGISTRY = Icon as unknown as Record<string, Icon | undefined>;

/**
 * Resolve a tool's `iconName` (a string emitted by `generate-tools.mjs`) to
 * the actual Raycast `Icon` value. Falls back to `Icon.Circle` if the name is
 * unknown (e.g. an icon was removed in a future Raycast release).
 */
export function iconFor(tool: ToolEntry): Icon {
  return ICON_REGISTRY[tool.iconName] ?? Icon.Circle;
}

/**
 * Category display order, matching the in-app grid. Categories not listed
 * here sort alphabetically after the known ones.
 */
export const CATEGORY_ORDER: ReadonlyArray<string> = [
  "Formatters",
  "Utilities",
  "Encoders/Decoders",
  "Converters",
  "Code Converters",
  "Validators",
  "Minifiers",
  "Viewers",
  "Previewers",
  "Cryptography",
  "DateTime Utilities",
  "QR Code",
  "Settings",
];

export function categorySortIndex(category: string): number {
  const idx = CATEGORY_ORDER.indexOf(category);
  return idx === -1 ? Number.MAX_SAFE_INTEGER : idx;
}
