export const PROGRAMMING_LANGUAGES = [
  'Unknown languages',
  '1C Enterprise',
  '2-Dimensional Array',
  '4D',
  'ABAP',
  'ABAP CDS',
  'ABNF',
  'ActionScript',
  'Ada',
  'Adblock Filter List',
  'Adobe Font Metrics',
  'Agda',
  'AGS Script',
  'AIDL',
  'AL',
  'Alloy',
  'Alpine Abuild',
  'Altium Designer',
  'AMPL',
  'AngelScript',
  'Ant Build System',
  'Antlers',
  'ANTLR',
  'ApacheConf',
  'Apex',
  'API Blueprint',
  'APL',
  'Apollo Guidance Computer',
  'AppleScript',
  'Arc',
  'AsciiDoc',
  'ASL',
  'ASN.1',
  'Classic ASP',
  'ASP.NET',
  'AspectJ',
  'Assembly',
  'Astro',
  'Asymptote',
  'ATS',
  'Augeas',
  'AutoHotkey',
  'AutoIt',
  'Avro IDL',
  'Awk',
  'Ballerina',
  'BASIC',
  'Batchfile',
  'Beef',
  'Befunge',
  'Berry',
  'BibTeX',
  'Bicep',
  'Bikeshed',
  'Bison',
  'BitBake',
  'Blade',
  'BlitzBasic',
  'BlitzMax',
  'Bluespec',
  'Boo',
  'Boogie',
  'Brainfuck',
  'BrighterScript',
  'Brightscript',
  'Zeek',
  'Browserslist',
  'C',
  'C#',
  'C++',
  'C-ObjDump',
  'C2hs Haskell',
  'Cabal Config',
  'Cadence',
  'Cairo',
  'CameLIGO',
  'CAP CDS',
  "Cap'n Proto",
  'CartoCSS',
  'Ceylon',
  'Chapel',
  'Charity',
  'Checksums',
  'ChucK',
  'CIL',
  'Cirru',
  'Clarion',
  'Clarity',
  'Classic ASP',
  'Clean',
  'Click',
  'CLIPS',
  'Clojure',
  'Closure Templates',
  'Cloud Firestore Security Rules',
  'CMake',
  'COBOL',
  'CODEOWNERS',
  'CodeQL',
  'CoffeeScript',
  'ColdFusion',
  'ColdFusion CFC',
  'COLLADA',
  'Common Lisp',
  'Common Workflow Language',
  'Component Pascal',
  'CoNLL-U',
  'Cool',
  'Coq',
  'Cpp-ObjDump',
  'Creole',
  'Crystal',
  'CSON',
  'Csound',
  'Csound Document',
  'Csound Score',
  'CSS',
  'CSV',
  'Cuda',
  'CUE',
  'Cue Sheet',
  'cURL Config',
  'Curry',
  'CWeb',
  'Cycript',
  'Cypher',
  'Cython',
  'D',
  'D-ObjDump',
  'Dafny',
  'Darcs Patch',
  'Dart',
  'DataWeave',
  'Debian Package Control File',
  'DenizenScript',
  'desktop',
  'Dhall',
  'Diff',
  'DIGITAL Command Language',
  'dircolors',
  'DirectX 3D File',
  'DM',
  'DNS Zone',
  'Dockerfile',
  'Dogescript',
  'DTrace',
  'Dylan',
  'E',
  'E-mail',
  'Eagle',
  'Earthly',
  'Easybuild',
  'EBNF',
  'eC',
  'Ecere Projects',
  'ECL',
  'ECLiPSe',
  'Ecmarkup',
  'EditorConfig',
  'Edje Data Collection',
  'edn',
  'Eiffel',
  'EJS',
  'Elixir',
  'Elm',
  'Elvish',
  'Emacs Lisp',
  'EmberScript',
  'E-mail',
  'EQ',
  'Erlang',
  'Euphoria',
  'F#',
  'F*',
  'Factor',
  'Fancy',
  'Fantom',
  'Faust',
  'Fennel',
  'FIGlet Font',
  'Filebench WML',
  'Filterscript',
  'fish',
  'Fluent',
  'FLUX',
  'Formatted',
  'Forth',
  'Fortran',
  'Fortran Free Form',
  'FreeBasic',
  'FreeMarker',
  'Frege',
  'Futhark',
  'G-code',
  'Game Maker Language',
  'GAML',
  'GAMS',
  'GAP',
  'GCC Machine Description',
  'GDB',
  'GDScript',
  'GEDCOM',
  'Gemfile.lock',
  'Gemini',
  'Genero',
  'Genero Forms',
  'Genie',
  'Genshi',
  'Gentoo Ebuild',
  'Gentoo Eclass',
  'Gerber Image',
  'Gettext Catalog',
  'Gherkin',
  'Git Attributes',
  'Git Config',
  'Git Revision List',
  'Gleam',
  'GLSL',
  'Glyph',
  'Glyph Bitmap Distribution Format',
  'GN',
  'Gnuplot',
  'Go',
  'Go Checksums',
  'Go Module',
  'Golo',
  'Gosu',
  'Grace',
  'Gradle',
  'Grammatical Framework',
  'Graph Modeling Language',
  'GraphQL',
  'Graphviz (DOT)',
  'Groovy',
  'Groovy Server Pages',
  'GSC',
  'Hack',
  'Haml',
  'Handlebars',
  'HAProxy',
  'Harbour',
  'Haskell',
  'Haxe',
  'HCL',
  'HiveQL',
  'HLSL',
  'HOCON',
  'HolyC',
  'hoon',
  'HTML',
  'Jinja',
  'HTML+ECR',
  'HTML+EEX',
  'HTML+ERB',
  'HTML+PHP',
  'HTML+Razor',
  'HTTP',
  'HXML',
  'Hy',
  'HyPhy',
  'IDL',
  'Idris',
  'Ignore List',
  'IGOR Pro',
  'ImageJ Macro',
  'Imba',
  'Inform 7',
  'INI',
  'Ink',
  'Inno Setup',
  'Io',
  'Ioke',
  'IRC log',
  'Isabelle',
  'Isabelle ROOT',
  'J',
  'Janet',
  'JAR Manifest',
  'Jasmin',
  'Java',
  'Java Properties',
  'Java Server Pages',
  'JavaScript',
  'JavaScript+ERB',
  'Jest Snapshot',
  'JetBrains MPS',
  'JFlex',
  'Jinja',
  'Jison',
  'Jison Lex',
  'Jolie',
  'jq',
  'JSON',
  'JSON with Comments',
  'JSON5',
  'JSONiq',
  'JSONLD',
  'Jsonnet',
  'Julia',
  'Jupyter Notebook',
  'just',
  'Kaitai Struct',
  'KakouneScript',
  'KiCad Layout',
  'KiCad Legacy Layout',
  'KiCad Schematic',
  'Kit',
  'Kotlin',
  'KRL',
  'Kusto',
  'kvlang',
  'LabVIEW',
  'Lark',
  'Lasso',
  'Latte',
  'Lean',
  'Less',
  'Lex',
  'LFE',
  'LigoLANG',
  'LilyPond',
  'Limbo',
  'Linker Script',
  'Linux Kernel Module',
  'Liquid',
  'Literate Agda',
  'Literate CoffeeScript',
  'Literate Haskell',
  'LiveScript',
  'LLVM',
  'Logos',
  'Logtalk',
  'LOLCODE',
  'LookML',
  'LoomScript',
  'LSL',
  'LTspice Symbol',
  'Lua',
  'M',
  'M4',
  'M4Sugar',
  'Macaulay2',
  'Makefile',
  'Mako',
  'Markdown',
  'Marko',
  'Mask',
  'Mathematica',
  'MATLAB',
  'Maven POM',
  'Max',
  'MAXScript',
  'mcfunction',
  'Wikitext',
  'Mercury',
  'Mermaid',
  'Meson',
  'Metal',
  'Microsoft Developer Studio Project',
  'Microsoft Visual Studio Solution',
  'MiniD',
  'MiniYAML',
  'Mint',
  'Mirah',
  'mIRC Script',
  'MLIR',
  'Modelica',
  'Modula-2',
  'Modula-3',
  'Module Management System',
  'Monkey',
  'Monkey C',
  'Moocode',
  'MoonScript',
  'Motoko',
  'Motorola 68K Assembly',
  'Move',
  'MQL4',
  'MQL5',
  'MTML',
  'MUF',
  'mupad',
  'Muse',
  'Mustache',
  'Myghty',
  'nanorc',
  'Nasal',
  'NASL',
  'NCL',
  'Nearley',
  'Nemerle',
  'NEON',
  'nesC',
  'NetLinx',
  'NetLinx+ERB',
  'NetLogo',
  'NewLisp',
  'Nextflow',
  'Nginx',
  'Nim',
  'Ninja',
  'Nit',
  'Nix',
  'NL',
  'NPM Config',
  'NSIS',
  'Nu',
  'NumPy',
  'Nunjucks',
  'NWScript',
  'OASv2-json',
  'OASv2-yaml',
  'OASv3-json',
  'OASv3-yaml',
  'ObjDump',
  'Object Data Instance Notation',
  'Objective-C',
  'Objective-C++',
  'Objective-J',
  'ObjectScript',
  'OCaml',
  'Odin',
  'Omgrofl',
  'ooc',
  'Opa',
  'Opal',
  'Open Policy Agent',
  'OpenAPI Specification v2',
  'OpenAPI Specification v3',
  'OpenCL',
  'OpenEdge ABL',
  'OpenQASM',
  'OpenRC runscript',
  'OpenSCAD',
  'OpenStep Property List',
  'OpenType Feature File',
  'Option List',
  'Org',
  'Ox',
  'Oxygene',
  'Oz',
  'P4',
  'Pan',
  'Papyrus',
  'Parrot',
  'Parrot Assembly',
  'Parrot Internal Representation',
  'Pascal',
  'Pawn',
  'PDDL',
  'PEG.js',
  'Pep8',
  'Perl',
  'PHP',
  'Pic',
  'Pickle',
  'PicoLisp',
  'PigLatin',
  'Pike',
  'PlantUML',
  'PLpgSQL',
  'PLSQL',
  'Pod',
  'Pod 6',
  'PogoScript',
  'Polar',
  'Pony',
  'Portugol',
  'PostCSS',
  'PostScript',
  'POV-Ray SDL',
  'PowerBuilder',
  'PowerShell',
  'Prisma',
  'Processing',
  'Procfile',
  'Proguard',
  'Prolog',
  'Promela',
  'Propeller Spin',
  'Protocol Buffer',
  'Protocol Buffer Text Format',
  'Public Key',
  'Pug',
  'Puppet',
  'Pure Data',
  'PureBasic',
  'PureScript',
  'Python',
  'Python console',
  'Python traceback',
  'q',
  'Q#',
  'QMake',
  'QML',
  'Qt Script',
  'Quake',
  'R',
  'Racket',
  'Ragel',
  'Raku',
  'RAML',
  'Rascal',
  'Raw token data',
  'RDoc',
  'Readline Config',
  'REALbasic',
  'Reason',
  'ReasonLIGO',
  'Rebol',
  'Record Jar',
  'Red',
  'Redcode',
  'Redirect Rules',
  'Regular Expression',
  "Ren'Py",
  'RenderScript',
  'ReScript',
  'reStructuredText',
  'REXX',
  'Rich Text Format',
  'Ring',
  'Riot',
  'RMarkdown',
  'RobotFramework',
  'robots.txt',
  'Roff',
  'Roff Manpage',
  'Rouge',
  'RouterOS Script',
  'RPC',
  'RPGLE',
  'RPM Spec',
  'Ruby',
  'RUNOFF',
  'Rust',
  'Sage',
  'SaltStack',
  'SAS',
  'Sass',
  'Scala',
  'Scaml',
  'Scenic',
  'Scheme',
  'Scilab',
  'SCSS',
  'sed',
  'Self',
  'SELinux Policy',
  'ShaderLab',
  'Shell',
  'ShellCheck Config',
  'ShellSession',
  'Shen',
  'Sieve',
  'Simple File Verification',
  'Singularity',
  'Slash',
  'Slice',
  'Slim',
  'Smali',
  'Smalltalk',
  'Smarty',
  'Smithy',
  'SmPL',
  'SMT',
  'Solidity',
  'Soong',
  'SourcePawn',
  'SPARQL',
  'Spline Font Database',
  'SQF',
  'SQL',
  'SQLPL',
  'Squirrel',
  'SRecode Template',
  'SSH Config',
  'Stan',
  'Standard ML',
  'STAR',
  'Starlark',
  'Stata',
  'STL',
  'STON',
  'StringTemplate',
  'Stylus',
  'SubRip Text',
  'SugarSS',
  'SuperCollider',
  'Svelte',
  'SVG',
  'Swift',
  'SWIG',
  'SystemVerilog',
  'Talon',
  'Tcl',
  'Tcsh',
  'Tea',
  'Terra',
  'TeX',
  'Texinfo',
  'Text',
  'Textile',
  'TextMate Properties',
  'Thrift',
  'TI Program',
  'TLA',
  'TOML',
  'TSQL',
  'TSV',
  'TSX',
  'Turing',
  'Turtle',
  'Twig',
  'TXL',
  'Type Language',
  'TypeScript',
  'Unified Parallel C',
  'Unity3D Asset',
  'Unix Assembly',
  'Uno',
  'UnrealScript',
  'UrWeb',
  'V',
  'Vala',
  'Valve Data Format',
  'VBA',
  'VBScript',
  'VCL',
  'Velocity Template Language',
  'Verilog',
  'VHDL',
  'Vim Help File',
  'Vim Script',
  'Vim Snippet',
  'Visual Basic .NET',
  'Visual Basic .NET',
  'Visual Basic 6.0',
  'Volt',
  'Vue',
  'Vyper',
  'Wavefront Material',
  'Wavefront Object',
  'wdl',
  'Web Ontology Language',
  'WebAssembly',
  'WebIDL',
  'WebVTT',
  'Wget Config',
  'Whiley',
  'Wikitext',
  'Win32 Message File',
  'Windows Registry Entries',
  'wisp',
  'Witcher Script',
  'Wollok',
  'World of Warcraft Addon Data',
  'Wren',
  'X BitMap',
  'X Font Directory Index',
  'X PixMap',
  'X10',
  'xBase',
  'XC',
  'XCompose',
  'XML',
  'XML Property List',
  'Xojo',
  'Xonsh',
  'XPages',
  'XProc',
  'XQuery',
  'XS',
  'XSLT',
  'Xtend',
  'Yacc',
  'YAML',
  'YANG',
  'YARA',
  'YASnippet',
  'Yul',
  'ZAP',
  'Zeek',
  'ZenScript',
  'Zephir',
  'Zig',
  'ZIL',
  'Zimpl',
]

export const PROGRAMMING_LANGUAGES_COLORS = {
  JavaScript: '#F7DF1E',
  Python: '#3776AB',
  Java: '#007396',
  TypeScript: '#3178C6',
  'C++': '#00599C',
  Go: '#00ADD8',
  Ruby: '#CC342D',
  PHP: '#777BB4',
  Swift: '#FA7343',
  Kotlin: '#F18E33',
  'C#': '#5C2D91',
  Rust: '#000000',
  'Objective-C': '#438EFF',
  Scala: '#DC3220',
  Dart: '#00B4AB',
  Haskell: '#5E5086',
  Perl: '#39457E',
  Lua: '#000080',
  Shell: '#89E051',
  Markdown: '#083FA1',
  C: '#555555',
  Marko: '#42bff2',
  EJS: '#A91E50',
  Elm: '#60B5CC',
  Nim: '#ffc200',
  Nix: '#7e7eff',
  OCaml: '#3be133',
  Makefile: '#427819',
  R: '#198CE7',
  Vue: '#4fc08d',
  CoffeeScript: '#244776',
  Clojure: '#db5855',
  Elixir: '#6e4a7e',
  Erlang: '#B83998',
  'F#': '#b845fc',
  Groovy: '#e69f56',
  Julia: '#a270ba',
  Pascal: '#b0ce4e',
  Racket: '#22228f',
  ReScript: '#ed5051',
  Reason: '#ff5847',
  'Jupyter Notebook': '#DA5B0B',
  TeX: '#3D6117',
  'Vim script': '#199f4b',
  'Visual Basic': '#945db7',
  Less: '#A1D9A6',
  Sass: '#CF649A',
  SCSS: '#C6538C',
  Stylus: '#ff6347',
  YAML: '#cb171e',
  JSON: '#cb171e',
  HTML: '#e34c26',
  CSS: '#563d7c',
  PostCSS: '#dc3a0c',
  PowerShell: '#012456',
  Dockerfile: '#384d54',
  Zig: '#ec915c',
  'Vim Script': '#199f4b',
}

export enum DateRange {
  daily = 'daily',
  weekly = 'weekly',
  monthly = 'monthly',
}

export const DATE_RANGE_OPTIONS = [
  { label: 'Today', value: DateRange.daily, key: 't' },
  { label: 'This Week', value: DateRange.weekly, key: 'w' },
  { label: 'This Month', value: DateRange.monthly, key: 'm' },
]
