export const categories: string[] = [
  "16-bit",
  "1-bit",
  "1GAM",
  "2D",
  "3D",
  "3D Platformer",
  "4X",
  "7dfps",
  "Seven Day Roguelike Challenge",
  "8-Bit",
  "Abstract",
  "Action",
  "Action-Adventure",
  "Action RPG",
  "Adult",
  "Adventure",
  "Aliens",
  "Alternate History",
  "Altgame",
  "Animals",
  "Anime",
  "Arcade",
  "Archery",
  "Art Book",
  "artgame",
  "artificial-intelligence",
  "ascii",
  "Asteroids",
  "atari",
  "Atmospheric",
  "Augmented Reality",
  "Automation",
  "Bara",
  "Barfcade",
  "Beat 'em up",
  "binaural",
  "Bitsy",
  "Black and White",
  "Blender",
  "blocks",
  "Board Game",
  "Boring",
  "Boss battle",
  "Boys' Love",
  "Brain Training",
  "Breakout",
  "Brushes",
  "Bullet Hell",
  "Card Game",
  "Casual",
  "cats",
  "Celtic",
  "Character Customization",
  "Chess",
  "Chicken",
  "chiptune",
  "Christmas",
  "Ciphers",
  "City Builder",
  "Classes",
  "clicker",
  "Colorful",
  "combos",
  "Comedy",
  "Comics",
  "Coming Of Age",
  "Commodore 64",
  "Construct 2",
  "Controller",
  "Co-op",
  "Corona SDK",
  "Cozy",
  "Crafting",
  "Creative",
  "Creepy",
  "Crime",
  "Cult Classic",
  "Cute",
  "Cyberpunk",
  "Dark",
  "Dark Fantasy",
  "Dark Humor",
  "Dating Sim",
  "deathmatch",
  "Deck Building",
  "Demake",
  "Destruction",
  "Detective",
  "Dice",
  "Difficult",
  "Dinosaurs",
  "Dogs",
  "DOS",
  "Dragons",
  "Drawing",
  "Dreams",
  "Driving",
  "DRM Free",
  "Dungeon Crawler",
  "Dystopian",
  "Economy",
  "Educational",
  "Emulator",
  "Endless",
  "Episodic",
  "Eroge",
  "Erotic",
  "Escape Game",
  "Experimental",
  "Exploration",
  "Explosions",
  "Fairy Tale",
  "Fangame",
  "Fantasy",
  "fantasy-console",
  "Farming",
  "Fast-Paced",
  "Feel Good",
  "Female Protagonist",
  "Fighting",
  "First-Person",
  "Fishing",
  "Flappy Bird",
  "flat-shading",
  "Flight",
  "Flying",
  "FMV",
  "Folklore",
  "fonts",
  "Food",
  "Football",
  "Forest",
  "FPS",
  "fps-platformer",
  "Frogs",
  "Funny",
  "Furry",
  "Futuristic",
  "Game Boy",
  "Game Boy Advance",
  "Game Boy ROM",
  "Game Design",
  "Game engine",
  "GameMaker",
  "gamepad",
  "Gardening",
  "Gay",
  "GBJam",
  "Gender",
  "Generator",
  "ggj15",
  "Global Game Jam 2020",
  "Ghosts",
  "GitHub",
  "glitch",
  "Global Game Jam",
  "GM-Less",
  "Game Maker's Toolkit Jam",
  "Golf",
  "Gore",
  "Gothic",
  "Gravity",
  "Grayscale",
  "Hack and Slash",
  "Hacking",
  "Halloween",
  "Hand-drawn",
  "Hex Based",
  "High Score",
  "Historical",
  "Homebrew",
  "Horrible",
  "Horror",
  "HyperCard",
  "Idle",
  "Immersive",
  "incremental",
  "infinite-runner",
  "Instrument",
  "Interactive Fiction",
  "Internet",
  "Isometric",
  "job-system",
  "JRPG",
  "jumping",
  "Kickstarter",
  "kinect",
  "Kinetic Novel",
  "Kung Fu",
  "Leap Motion",
  "Lesbian",
  "Level Editor",
  "LGBT",
  "LGBTQIA",
  "libGDX",
  "Life Simulation",
  "live-action",
  "Local Co-Op",
  "Local multiplayer",
  "Lo-fi",
  "lone-survivor",
  "Loot",
  "LÖVE",
  "Lovecraftian Horror",
  "Low-poly",
  "LOWREZJAM",
  "Ludum Dare",
  "Ludum Dare 29",
  "Ludum Dare 30",
  "Ludum Dare 31",
  "Ludum Dare 32",
  "Ludum Dare 33",
  "Ludum Dare 34",
  "Ludum Dare 35",
  "Ludum Dare 36",
  "Ludum Dare 37",
  "Ludum Dare 38",
  "Ludum Dare 39",
  "Ludum Dare 40",
  "Ludum Dare 41",
  "Ludum Dare 42",
  "Ludum Dare 43",
  "Ludum Dare 44",
  "Ludum Dare 45",
  "Ludum Dare 46",
  "Ludum Dare 47",
  "Ludum Dare 49",
  "Ludum Dare 50",
  "Magic",
  "Magical Realism",
  "Male protagonist",
  "Management",
  "Manga",
  "mashup",
  "Massively multiplayer",
  "Math",
  "maze",
  "Meaningful Choices",
  "Mechs",
  "Medieval",
  "Mega Drive",
  "memoir",
  "Mental Health",
  "Metroidvania",
  "MIDI",
  "mind-bending",
  "minigames",
  "Minimalist",
  "MMORPG",
  "Moddable",
  "moe",
  "Monsters",
  "Mountains",
  "Mouse only",
  "Multiplayer",
  "Multiple Endings",
  "Music",
  "Music Production",
  "My First Game Jam",
  "Mystery",
  "mythology",
  "Narrative",
  "nature",
  "Neon",
  "NES",
  "NES Rom",
  "Ninja",
  "Noir",
  "non-eucledian",
  "Nonlinear",
  "Non violent",
  "Norse",
  "norway",
  "Oculus Quest",
  "Oculus Rift",
  "one-button",
  "one-hit-kill",
  "One-shot",
  "On-Rails Shooter",
  "Open Source",
  "Open World",
  "Otome",
  "Painting",
  "parallax",
  "Parkour",
  "Parody",
  "party-game",
  "pastel",
  "PbtA",
  "Period Piece",
  "Perma Death",
  "Perspective",
  "Photorealistic",
  "Physics",
  "PICO-8",
  "Pirates",
  "Pixel Art",
  "Platformer",
  "Playdate",
  "Point &amp; Click",
  "Post-apocalyptic",
  "Procedural Generation",
  "PROCJAM",
  "PSX",
  "psychedelic",
  "Psychological Horror",
  "Puzzle",
  "Puzzle-Platformer",
  "PuzzleScript",
  "PvP",
  "Queer",
  "Racing",
  "Railroad",
  "Real-Time",
  "Real time strategy",
  "relationship",
  "Relaxing",
  "Remake",
  "renpy",
  "Resource Pack",
  "Retro",
  "Rhythm",
  "Roadtrip",
  "Robots",
  "Roguelike",
  "Roguelite",
  "Romance",
  "Rotation",
  "Role Playing",
  "RPG Maker",
  "Runner",
  "Sailing",
  "Sandbox",
  "satire",
  "Sci-fi",
  "Score Attack",
  "screensaver",
  "secrets",
  "Sega Genesis",
  "SFML",
  "Shadows",
  "SHARECART1000",
  "Shoot 'Em Up",
  "Shooter",
  "Short",
  "Side Scroller",
  "Simulation",
  "Singleplayer",
  "Siren Head",
  "sitting-simulator",
  "Skating",
  "Skeletons",
  "Slasher",
  "Slice Of Life",
  "Slime",
  "Soccer",
  "Soundtoy",
  "sourcecode",
  "Space",
  "Space Sim",
  "Speedrun",
  "Split Screen",
  "Spooky",
  "Spoopy",
  "Sports",
  "sprites",
  "Stealth",
  "Steampunk",
  "Stencyl",
  "stop-motion",
  "Story Rich",
  "Strategy",
  "Strategy RPG",
  "Superhero",
  "supernatural",
  "Superpowers",
  "Surreal",
  "Survival",
  "Survival Horror",
  "suspense",
  "Swords",
  "Synthwave",
  "tablet",
  "Tactical",
  "Tactical RPG",
  "Tanks",
  "Team-Based",
  "Project template",
  "Tennis",
  "Tentacles",
  "Tetris",
  "Text based",
  "Third Person",
  "Third-Person Shooter",
  "Thriller",
  "TIC-80",
  "Tilemap based tools",
  "Tileset",
  "Time Attack",
  "Time Travel",
  "Top-Down",
  "Top Down Adventure",
  "Top down shooter",
  "Touch-Friendly",
  "Touhou",
  "Tower Defense",
  "Trading",
  "Trains",
  "Transgender",
  "Traps",
  "trashcore",
  "Turn-based",
  "Turn-Based Combat",
  "Turn-based Strategy",
  "Tutorial",
  "Twine",
  "Twin Stick Shooter",
  "two-colors",
  "Tycoon",
  "typing",
  "TyranoBuilder",
  "underwater",
  "Unity",
  "Unreal Engine",
  "upgrades",
  "user-interface",
  "Vampire",
  "Vector",
  "Versus",
  "VIC-20",
  "video",
  "Violent",
  "Virtual Pet",
  "Virtual Reality (VR)",
  "Visualization",
  "Visual Novel",
  "Voice Acting",
  "voice-controlled",
  "Voxel",
  "VST",
  "Walking simulator",
  "War",
  "watercolor",
  "weird",
  "Western",
  "Wizards",
  "Wobbly",
  "Word game",
  "World War II",
  "Yaoi",
  "Yuri",
  "Zero Gravity",
  "zine",
  "Zombies",
  "World War I",
  "ZX Spectrum",
];
