// Mock data for demo mode / screenshots
// To enable demo mode: set DEMO_MODE to true below, then run: npm run dev

import { Account, Server, Site, Event } from "./types";

/**
 * Toggle this to enable/disable demo mode for screenshots
 */
const DEMO_MODE = false;

/**
 * Check if demo mode is enabled
 */
export function isDemoMode(): boolean {
  return DEMO_MODE;
}

// ============================================================================
// MOCK ACCOUNTS
// ============================================================================

export const mockAccounts: Account[] = [
  { id: "acc-3", name: "Clients", token: "demo-token-dev" },
  { id: "acc-4", name: "Damien Gorin", token: "demo-token-damien" },
  { id: "acc-5", name: "Digilia", token: "demo-token-digilia" },
];

// ============================================================================
// MOCK SERVERS
// ============================================================================

const baseDate = new Date().toISOString();

export const mockServers: Server[] = [
  {
    id: 1001,
    name: "web-prod-1",
    provider_name: "DigitalOcean",
    ubuntu_version: "22.04",
    ip_address: "167.71.128.42",
    ssh_port: 22,
    timezone: "UTC",
    region: "NYC1",
    size: "8 GB / 2 vCPU",
    disk_space: {
      total: 160 * 1024 * 1024 * 1024,
      available: 120 * 1024 * 1024 * 1024,
      used: 40 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    install_notes: null,
    created_at: "2024-01-15T10:00:00Z",
    status: "provisioned",
  },
  {
    id: 1002,
    name: "web-prod-2",
    provider_name: "AWS",
    ubuntu_version: "22.04",
    ip_address: "52.23.184.91",
    ssh_port: 22,
    timezone: "UTC",
    region: "us-east-1",
    size: "16 GB / 8 vCPU",
    disk_space: {
      total: 320 * 1024 * 1024 * 1024,
      available: 280 * 1024 * 1024 * 1024,
      used: 40 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: true,
    upgrade_required: false,
    install_notes: null,
    created_at: "2024-02-20T14:30:00Z",
    status: "provisioned",
  },
  {
    id: 1004,
    name: "staging-server",
    provider_name: "Vultr",
    ubuntu_version: "22.04",
    ip_address: "45.77.123.89",
    ssh_port: 22,
    timezone: "Europe/Amsterdam",
    region: "Amsterdam",
    size: "4 GB / 2 vCPU",
    disk_space: {
      total: 80 * 1024 * 1024 * 1024,
      available: 60 * 1024 * 1024 * 1024,
      used: 20 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    install_notes: null,
    created_at: "2024-04-05T16:45:00Z",
    status: "provisioned",
  },
  {
    id: 1005,
    name: "dev-server",
    provider_name: "Hetzner",
    ubuntu_version: "22.04",
    ip_address: "138.201.45.67",
    ssh_port: 22,
    timezone: "Europe/Berlin",
    region: "Nuremberg",
    size: "2 GB / 1 vCPU",
    disk_space: {
      total: 40 * 1024 * 1024 * 1024,
      available: 30 * 1024 * 1024 * 1024,
      used: 10 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    install_notes: null,
    created_at: "2024-05-12T11:20:00Z",
    status: "provisioned",
  },
  {
    id: 1006,
    name: "damiengorin-prod",
    provider_name: "AWS",
    ubuntu_version: "22.04",
    ip_address: "54.172.98.45",
    ssh_port: 22,
    timezone: "America/New_York",
    region: "us-east-1",
    size: "8 GB / 4 vCPU",
    disk_space: {
      total: 200 * 1024 * 1024 * 1024,
      available: 150 * 1024 * 1024 * 1024,
      used: 50 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: true,
    upgrade_required: false,
    install_notes: null,
    created_at: "2024-06-01T08:00:00Z",
    status: "provisioned",
  },
  {
    id: 1007,
    name: "digilia-prod",
    provider_name: "DigitalOcean",
    ubuntu_version: "22.04",
    ip_address: "134.209.112.78",
    ssh_port: 22,
    timezone: "America/Montreal",
    region: "TOR1",
    size: "4 GB / 2 vCPU",
    disk_space: {
      total: 80 * 1024 * 1024 * 1024,
      available: 55 * 1024 * 1024 * 1024,
      used: 25 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    install_notes: null,
    created_at: "2024-07-15T13:30:00Z",
    status: "provisioned",
  },
  {
    id: 1008,
    name: "eu-prod",
    provider_name: "Vultr",
    ubuntu_version: "22.04",
    ip_address: "139.180.145.22",
    ssh_port: 22,
    timezone: "Europe/Berlin",
    region: "Frankfurt",
    size: "8 GB / 2 vCPU",
    disk_space: {
      total: 160 * 1024 * 1024 * 1024,
      available: 140 * 1024 * 1024 * 1024,
      used: 20 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    install_notes: null,
    created_at: "2024-08-20T05:45:00Z",
    status: "provisioned",
  },
  {
    id: 1009,
    name: "backup-server",
    provider_name: "AWS",
    ubuntu_version: "22.04",
    ip_address: "3.95.167.234",
    ssh_port: 22,
    timezone: "UTC",
    region: "eu-west-1",
    size: "16 GB / 4 vCPU",
    disk_space: {
      total: 500 * 1024 * 1024 * 1024,
      available: 350 * 1024 * 1024 * 1024,
      used: 150 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    install_notes: null,
    created_at: "2024-09-01T12:00:00Z",
    status: "provisioned",
  },
  {
    id: 1010,
    name: "new-server",
    provider_name: "DigitalOcean",
    ubuntu_version: "24.04",
    ip_address: "159.89.234.56",
    ssh_port: 22,
    timezone: "UTC",
    region: "FRA1",
    size: "4 GB / 2 vCPU",
    disk_space: {
      total: 80 * 1024 * 1024 * 1024,
      available: 78 * 1024 * 1024 * 1024,
      used: 2 * 1024 * 1024 * 1024,
      updated_at: baseDate,
    },
    database: { server: "MySQL 8.0", host: "localhost", port: 3306 },
    ssh_publickey: "ssh-ed25519 AAAA...",
    git_publickey: "ssh-ed25519 AAAA...",
    connection_status: "connected",
    reboot_required: false,
    upgrade_required: false,
    install_notes: null,
    created_at: baseDate,
    status: "provisioning",
  },
];

// ============================================================================
// MOCK SITES
// ============================================================================

const baseSiteData = {
  additional_domains: [],
  site_user: "siteuser",
  public_folder: "/public",
  is_wordpress: true,
  nginx: {
    uploads_directory_protected: true,
    xmlrpc_protected: true,
    subdirectory_rewrite_in_place: false,
  },
  database: { id: 1, user_id: 1, table_prefix: "wp_" },
  backups: {
    files: true,
    database: true,
    paths_to_exclude: "",
    retention_period: 30,
    next_run_time: baseDate,
    storage_provider: { id: 1, region: "us-east-1", bucket: "backups" },
  },
  created_at: baseDate,
  status: "deployed" as const,
};

export const mockSites: Site[] = [
  // Sites with Git
  {
    ...baseSiteData,
    id: 2001,
    server_id: 1001,
    domain: "acme.com",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: {
      repo: "git@github.com:acme/website.git",
      branch: "main",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2002,
    server_id: 1001,
    domain: "blog.acme.com",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: true,
    wp_theme_updates: 2,
    wp_plugin_updates: 5,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2003,
    server_id: 1004,
    domain: "staging.acme.com",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: {
      repo: "git@github.com:acme/website.git",
      branch: "develop",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: true, username: "reviewer" },
  },
  {
    ...baseSiteData,
    id: 2004,
    server_id: 1002,
    domain: "shop.acme.com",
    php_version: "8.2",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 1,
    wp_plugin_updates: 3,
    git: {
      repo: "git@github.com:acme/shop.git",
      branch: "main",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2005,
    server_id: 1001,
    domain: "acme.co.uk",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: {
      repo: "git@github.com:acme/uk-site.git",
      branch: "production",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2006,
    server_id: 1005,
    domain: "dev.acme.com",
    php_version: "8.3",
    page_cache: { enabled: false },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: {
      repo: "git@github.com:acme/website.git",
      branch: "feature/new-design",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: true, username: "developer" },
  },
  // Damien Gorin sites
  {
    ...baseSiteData,
    id: 2007,
    server_id: 1006,
    domain: "damiengorin.com",
    php_version: "8.2",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 2,
    git: {
      repo: "git@github.com:damiengorin/website.git",
      branch: "main",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2008,
    server_id: 1006,
    domain: "blog.damiengorin.com",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  // Digilia sites
  {
    ...baseSiteData,
    id: 2009,
    server_id: 1007,
    domain: "digilia.ca",
    php_version: "8.2",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: true,
    wp_theme_updates: 1,
    wp_plugin_updates: 4,
    git: {
      repo: "git@github.com:digilia/website.git",
      branch: "main",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2010,
    server_id: 1007,
    domain: "staging.digilia.ca",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: {
      repo: "git@github.com:digilia/website.git",
      branch: "develop",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: true, username: "reviewer" },
  },
  // More sites
  {
    ...baseSiteData,
    id: 2011,
    server_id: 1008,
    domain: "asia-store.com",
    php_version: "8.2",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2012,
    server_id: 1008,
    domain: "asia-blog.com",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 2,
    wp_plugin_updates: 1,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2013,
    server_id: 1001,
    domain: "marketing.acme.com",
    php_version: "8.2",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2014,
    server_id: 1002,
    domain: "careers.acme.com",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2015,
    server_id: 1001,
    domain: "support.acme.com",
    php_version: "8.2",
    page_cache: { enabled: false },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2016,
    server_id: 1004,
    domain: "test.acme.com",
    php_version: "8.3",
    page_cache: { enabled: false },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: null,
    basic_auth: { enabled: true, username: "tester" },
  },
  {
    ...baseSiteData,
    id: 2017,
    server_id: 1006,
    domain: "dev.damiengorin.com",
    php_version: "8.2",
    page_cache: { enabled: false },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 1,
    git: {
      repo: "git@github.com:damiengorin/website.git",
      branch: "develop",
      deploy_script: "",
      push_enabled: true,
      deployment_url: "",
    },
    basic_auth: { enabled: true, username: "developer" },
  },
  {
    ...baseSiteData,
    id: 2018,
    server_id: 1007,
    domain: "app.digilia.ca",
    php_version: "8.3",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2019,
    server_id: 1002,
    domain: "partners.acme.com",
    php_version: "8.2",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: false,
    wp_theme_updates: 0,
    wp_plugin_updates: 0,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
  {
    ...baseSiteData,
    id: 2020,
    server_id: 1009,
    domain: "archive.acme.com",
    php_version: "8.1",
    page_cache: { enabled: true },
    https: { enabled: true },
    wp_core_update: true,
    wp_theme_updates: 3,
    wp_plugin_updates: 8,
    git: null,
    basic_auth: { enabled: false, username: "" },
  },
];

// ============================================================================
// MOCK EVENTS
// ============================================================================

export const mockEvents: Event[] = [
  {
    id: 3001,
    initiated_by: "API",
    server_id: 1001,
    name: "Purge Page Cache",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },
  {
    id: 3002,
    initiated_by: "john@acme.com",
    server_id: 1001,
    name: "Restart Nginx",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
  {
    id: 3003,
    initiated_by: "API",
    server_id: 1002,
    name: "Git Deployment",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  },
  {
    id: 3004,
    initiated_by: "sarah@acme.com",
    server_id: 1004,
    name: "Restart PHP-FPM",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 44 * 60 * 1000).toISOString(),
  },
  {
    id: 3005,
    initiated_by: "API",
    server_id: 1001,
    name: "Purge Object Cache",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 59 * 60 * 1000).toISOString(),
  },
  {
    id: 3006,
    initiated_by: "deploy@github.com",
    server_id: 1001,
    name: "Git Deployment",
    status: "failed",
    output: "Build failed: npm install error",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 2 * 60 * 60 * 1000 + 30000).toISOString(),
  },
  {
    id: 3007,
    initiated_by: "damien@damiengorin.com",
    server_id: 1006,
    name: "Restart MySQL",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 3 * 60 * 60 * 1000 + 15000).toISOString(),
  },
  {
    id: 3008,
    initiated_by: "API",
    server_id: 1007,
    name: "Correct File Permissions",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 4 * 60 * 60 * 1000 + 45000).toISOString(),
  },
  {
    id: 3009,
    initiated_by: "john@acme.com",
    server_id: 1002,
    name: "Reboot Server",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 5 * 60 * 60 * 1000 + 120000).toISOString(),
  },
  {
    id: 3010,
    initiated_by: "API",
    server_id: 1008,
    name: "Purge Page Cache",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 6 * 60 * 60 * 1000 + 5000).toISOString(),
  },
  {
    id: 3011,
    initiated_by: "deploy@github.com",
    server_id: 1004,
    name: "Git Deployment",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 8 * 60 * 60 * 1000 + 90000).toISOString(),
  },
  {
    id: 3012,
    initiated_by: "sarah@acme.com",
    server_id: 1005,
    name: "Restart Redis",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 12 * 60 * 60 * 1000 + 8000).toISOString(),
  },
  {
    id: 3013,
    initiated_by: "API",
    server_id: 1001,
    name: "Site Created",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 24 * 60 * 60 * 1000 + 180000).toISOString(),
  },
  {
    id: 3014,
    initiated_by: "admin@digilia.ca",
    server_id: 1007,
    name: "Git Deployment",
    status: "failed",
    output: "Deployment script failed",
    created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 36 * 60 * 60 * 1000 + 60000).toISOString(),
  },
  {
    id: 3015,
    initiated_by: "john@acme.com",
    server_id: 1009,
    name: "Server Provisioned",
    status: "deployed",
    output: null,
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    started_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 48 * 60 * 60 * 1000 + 600000).toISOString(),
  },
];
