import type { IAPIData } from "./types";

export default <IAPIData[]>[
  {
    name: "Apollo",
    icon: "../assets/logo/apollo.png",
    apiKey: "ef1ac4e3c439bc17a8e7572700691efc",
    appId: "Q0CJ63JM7B",
    indexName: "docs",
    homepage: "https://www.apollographql.com/docs",
  },
  {
    name: "Arthas",
    icon: "../assets/logo/arthas.ico",
    apiKey: "03fb4b6577b57b5dafc792d9ddf66508",
    appId: "UX8WBNVHHR",
    indexName: "arthas",
    homepage: "https://arthas.aliyun.com/",
  },
  {
    name: "Bootstrap",
    icon: "../assets/logo/bootstrap.ico",
    apiKey: "5990ad008512000bba2cf951ccf0332f",
    appId: "BH4D9OD16A",
    indexName: "bootstrap",
    homepage: "https://getbootstrap.com/",
    searchParameters: {
      facetFilters: ["version:5.1"],
    },
  },
  {
    name: "Clerk",
    icon: "../assets/logo/clerk.png",
    apiKey: "52385d30a5ca4460564defe5b2d0ffb1",
    appId: "RA7W9NZP4T",
    indexName: "prod_sanity",
    homepage: "https://clerk.dev",
  },
  {
    name: "Dubbo",
    icon: "../assets/logo/dubbo.png",
    apiKey: "364ae307e1da9d02b2335675e9db1eb1",
    appId: "L5F4T9F0I1",
    indexName: "apache_dubbo",
    homepage: "https://dubbo.apache.org/",
  },
  {
    name: "Echarts",
    icon: "../assets/logo/echarts.png",
    apiKey: "6ade5f1ff34e94690f9ea38cddcc2f55",
    appId: "BH4D9OD16A",
    indexName: "apache_echarts",
    homepage: "https://echarts.apache.org/en/index.html",
    searchParameters: {
      facetFilters: ["lang:en"],
    },
  },
  {
    name: "Echarts",
    icon: "../assets/logo/echarts.png",
    apiKey: "6ade5f1ff34e94690f9ea38cddcc2f55",
    appId: "BH4D9OD16A",
    indexName: "apache_echarts",
    homepage: "https://echarts.apache.org/zh/index.html",
    lang: "zh-Hans",
    searchParameters: {
      facetFilters: ["lang:zh"],
    },
  },
  {
    name: "GitBook",
    icon: "../assets/logo/gitbook.png",
    apiKey:
      "MDgxNzdmZGVhM2MzMDJiMjAxMzczZTllMmVmMDAxOGQ1N2YzMjAyM2M0ZWMxZjk5NmFmYjE0ODA0OWUzYzFlMGZpbHRlcnM9KHZpZXdhYmxlQnlQdWJsaWNTcGFjZXMlM0FOa0VHUzdoemVxYTM1c01YUVo0WC0xKSUyMEFORCUyMHByb2plY3RJZCUzQWdpdGJvb2steC1wcm9k",
    appId: "U102FN9U1K",
    indexName: "pages",
    homepage: "https://docs.gitbook.com/",
  },
  {
    name: "Homebrew",
    icon: "../assets/logo/homebrew.png",
    apiKey: "a57ef92bf2adfae863a201ee43d6b5a1",
    appId: "BH4D9OD16A",
    indexName: "brew_all",
    homepage: "https://brew.sh/",
  },
  {
    name: "IPFS",
    icon: "../assets/logo/ipfs.png",
    apiKey: "e56fc7c611806522df45191e22ed15ac",
    appId: "BH4D9OD16A",
    indexName: "ipfs-docs",
    homepage: "https://docs.ipfs.tech/",
  },
  {
    name: "Laravel 9.x",
    icon: "../assets/logo/laravel.png",
    apiKey: "1fa3a8fec06eb1858d6ca137211225c0",
    appId: "E3MIRNPJH5",
    indexName: "laravel",
    homepage: "https://laravel.com/",
    searchParameters: {
      facetFilters: ["version:9.x"],
      highlightPreTag: '<em class: "not-italic bg-red-600 bg-opacity-25">',
      highlightPostTag: "</em>",
    },
  },
  {
    name: "Nuxt",
    icon: "../assets/logo/nuxt.png",
    apiKey: "60a01900a4b726d667eab75b6f337592",
    appId: "1V8G7N9GF0",
    indexName: "nuxtjs",
    homepage: "https://nuxtjs.org/",
    searchParameters: {
      facetFilters: ["language:en-US", "tags:main"],
    },
  },
  {
    name: "Nuxt3",
    icon: "../assets/logo/nuxt.png",
    apiKey: "60a01900a4b726d667eab75b6f337592",
    appId: "1V8G7N9GF0",
    indexName: "nuxtjs",
    homepage: "https://v3.nuxtjs.org/",
    searchParameters: {
      facetFilters: ["language:en-US", "tags:v3"],
    },
  },
  {
    name: "Prettier",
    icon: "../assets/logo/prettier.png",
    apiKey: "9fcdb2a62af4c47cc5eecf3d5a747818",
    appId: "BH4D9OD16A",
    indexName: "prettier",
    homepage: "https://prettier.io/",
  },
  {
    name: "RSSHub",
    icon: "../assets/logo/rsshub.png",
    apiKey: "6247bc0db93150fd9e531b93a3fa4046",
    appId: "BH4D9OD16A",
    indexName: "rsshub",
    homepage: "https://docs.rsshub.app/",
  },
  {
    name: "Raycast",
    icon: "../assets/logo/raycast.png",
    apiKey:
      "YmZlNDIxZTVlYWQyOWQ4ZThhMzdkOGUxOTY0YjU2NGNjZDNkOTA5NjQ3MmZmMjg0MzViYjYzMDI4NTVkMmQ1ZmZpbHRlcnM9KHZpZXdhYmxlQnlQdWJsaWNTcGFjZXMlM0EtTWVfOEEzOXRGaFpnM1VhVm9TTi0yKSUyMEFORCUyMHByb2plY3RJZCUzQWdpdGJvb2steC1wcm9k",
    appId: "U102FN9U1K",
    indexName: "pages",
    homepage: "https://developers.raycast.com/",
  },
  {
    name: "React",
    icon: "../assets/logo/react.ico",
    apiKey: "36221914cce388c46d0420343e0bb32e",
    appId: "BH4D9OD16A",
    indexName: "react",
    homepage: "https://reactjs.org/",
  },
  {
    name: "React",
    icon: "../assets/logo/react.ico",
    apiKey: "72499aaa151dba0828babe727c7b86ee",
    appId: "BH4D9OD16A",
    indexName: "reactjs_zh-hans",
    homepage: "https://zh-hans.reactjs.org/",
    lang: "zh-Hans",
  },
  {
    name: "React Bootstrap",
    icon: "../assets/logo/react_bootstrap.png",
    apiKey: "33985ee571397d832ef243988ff4c891",
    appId: "C38ZI55F9H",
    homepage: "https://react-bootstrap.github.io/",
    indexName: "react_bootstrap_v4",
  },
  {
    name: "React Native",
    icon: "../assets/logo/react.ico",
    apiKey: "83cd239c72f9f8b0ed270a04b1185288",
    appId: "8TDSE0OHGQ",
    indexName: "react-native-v2",
    homepage: "https://reactnative.dev/",
    searchParameters: {
      facetFilters: [
        "language:en",
        [
          "docusaurus_tag:default",
          "docusaurus_tag:docs-default-0.69",
          "docusaurus_tag:docs-contributing-current",
          "docusaurus_tag:docs-architecture-current",
        ],
      ],
    },
  },
  {
    name: "Remix",
    icon: "../assets/logo/remix.png",
    apiKey: "dff56670dbec8494409989d6ec9c8ac2",
    appId: "6OHWJSR8G4",
    homepage: "https://remix.run/",
    indexName: "remix",
  },
  {
    name: "Slidev",
    icon: "../assets/logo/slidev.png",
    apiKey: "1ff173fe73b20edc962c1c24c0b1c160",
    appId: "LCBV6MIFS6",
    indexName: "slidev",
    homepage: "https://sli.dev/",
    searchParameters: {
      facetFilters: ["language:en"],
    },
  },
  {
    name: "Slidev",
    icon: "../assets/logo/slidev.png",
    apiKey: "1a5c5a504139c58f428974c78c55291d",
    appId: "BH4D9OD16A",
    indexName: "slidev",
    homepage: "https://cn.sli.dev/",
    lang: "zh-Hans",
    searchParameters: {
      facetFilters: ["language:cn"],
    },
  },
  {
    name: "Supabase",
    icon: "../assets/logo/supabase.png",
    apiKey: "0424becc4055d51ec60e54cc37df5574",
    appId: "B3Z5XYG8NS",
    indexName: "prod_docs",
    homepage: "https://supabase.com/docs",
  },
  {
    name: "TailwindCSS v3",
    icon: "../assets/logo/tailwindcss.png",
    apiKey: "5fc87cef58bb80203d2207578309fab6",
    appId: "KNPXZI5B0M",
    indexName: "tailwindcss",
    homepage: "https://tailwindcss.com/",
    searchParameters: {
      facetFilters: ["version:v3"],
    },
  },
  {
    name: "Unidata",
    icon: "../assets/logo/unidata.png",
    apiKey: "3f968df846740a9e2b38e89d8e6ce9fa",
    appId: "LNA1UZCPZB",
    indexName: "unidata",
    homepage: "https://unidata.app/",
    searchParameters: {
      facetFilters: ["lang:en-US"],
    },
  },
  {
    name: "Vite",
    icon: "../assets/logo/vite.png",
    apiKey: "b573aa848fd57fb47d693b531297403c",
    appId: "BH4D9OD16A",
    indexName: "vitejs",
    homepage: "https://vitejs.dev/",
  },
  {
    name: "Vite",
    icon: "../assets/logo/vite.png",
    apiKey: "b573aa848fd57fb47d693b531297403c",
    appId: "BH4D9OD16A",
    indexName: "vitejs",
    homepage: "https://cn.vitejs.dev/",
    lang: "zh-Hans",
    searchParameters: {
      facetFilters: ["tags:cn"],
    },
  },
  {
    name: "Vitest",
    icon: "../assets/logo/vitest.png",
    apiKey: "9c3ced6fed60d2670bb36ab7e8bed8bc",
    appId: "ZTF29HGJ69",
    indexName: "vitest",
    homepage: "https://vitest.dev/",
  },
  {
    name: "Vue Router4",
    icon: "../assets/logo/vue.png",
    apiKey: "771d10c8c5cc48f7922f15048b4d931c",
    appId: "BTNTW3I1XP",
    indexName: "next_router_vuejs",
    homepage: "https://router.vuejs.org/",
  },
  {
    name: "Vue3",
    icon: "../assets/logo/vue.png",
    apiKey: "f49cbd92a74532cc55cfbffa5e5a7d01",
    appId: "ML0LEBN7FQ",
    indexName: "vuejs",
    homepage: "https://vuejs.org/",
    searchParameters: {
      facetFilters: ["version:v3"],
    },
  },
  {
    name: "Vue3",
    icon: "../assets/logo/vue.png",
    apiKey: "c23eb8e7895f42daeaf2bf6f63eb4bf6",
    appId: "UURH1MHAF7",
    indexName: "vuejs_cn2",
    lang: "zh-Hans",
    homepage: "https://vuejs.org/",
    searchParameters: {
      facetFilters: ["version:v3"],
    },
  },
  {
    name: "VueUse",
    icon: "../assets/logo/vueuse.png",
    apiKey: "a99ef8de1b2b27949975ce96642149c6",
    appId: "BH4D9OD16A",
    indexName: "vueuse",
    homepage: "https://vueuse.org/",
  },
  {
    name: "Vuepress v1",
    icon: "../assets/logo/vuepress.png",
    apiKey: "3a539aab83105f01761a137c61004d85",
    appId: "BH4D9OD16A",
    indexName: "vuepress",
    homepage: "https://vuepress.vuejs.org/",
  },
  {
    name: "Vuepress v2",
    icon: "../assets/logo/vuepress.png",
    apiKey: "9a9058b8655746634e01071411c366b8",
    appId: "34YFD9IUQ2",
    indexName: "vuepress",
    homepage: "https://v2.vuepress.vuejs.org/",
  },
  {
    name: "pnpm",
    icon: "../assets/logo/pnpm.png",
    apiKey: "a337998a623aa8f80d2a97a79d565086",
    appId: "RAHRBBK2WL",
    indexName: "pnpm",
    homepage: "https://pnpm.io/zh",
    searchParameters: {
      facetFilters: ["language:en"],
    },
  },
  {
    name: "pnpm",
    icon: "../assets/logo/pnpm.png",
    apiKey: "a337998a623aa8f80d2a97a79d565086",
    appId: "RAHRBBK2WL",
    indexName: "pnpm",
    homepage: "https://pnpm.io/zh",
    lang: "zh-Hans",
    searchParameters: {
      facetFilters: ["language:zh"],
    },
  },
];
