import type { IAPIData } from "./types";

export default <IAPIData[]>[
  {
    name: "Arthas",
    icon: "https://arthas.aliyun.com/images/favicon.ico",
    apiKey: "03fb4b6577b57b5dafc792d9ddf66508",
    appId: "UX8WBNVHHR",
    indexName: "arthas",
    homepage: "https://arthas.aliyun.com/",
  },
  {
    name: "Bootstrap",
    icon: "https://getbootstrap.com/docs/5.1/assets/img/favicons/favicon.ico",
    apiKey: "5990ad008512000bba2cf951ccf0332f",
    appId: "BH4D9OD16A",
    indexName: "bootstrap",
    homepage: "https://getbootstrap.com/",
    searchParameters: {
      facetFilters: ["version:5.1"],
    },
  },
  {
    name: "Echarts",
    icon: "https://fastly.jsdelivr.net/gh/apache/echarts-website@asf-site/zh/images/favicon.png",
    apiKey: "6ade5f1ff34e94690f9ea38cddcc2f55",
    appId: "BH4D9OD16A",
    indexName: "apache_echarts",
    homepage: "https://echarts.apache.org/en/index.html",
    searchParameters: {
      facetFilters: ["lang:en"],
    },
  },
  {
    name: "Echarts",
    icon: "https://fastly.jsdelivr.net/gh/apache/echarts-website@asf-site/zh/images/favicon.png",
    apiKey: "6ade5f1ff34e94690f9ea38cddcc2f55",
    appId: "BH4D9OD16A",
    indexName: "apache_echarts",
    homepage: "https://echarts.apache.org/zh/index.html",
    subtitle: "zh-Hans",
    searchParameters: {
      facetFilters: ["lang:zh"],
    },
  },
  {
    name: "Homebrew",
    icon: "https://brew.sh/assets/img/apple-touch-icon.png",
    apiKey: "a57ef92bf2adfae863a201ee43d6b5a1",
    appId: "BH4D9OD16A",
    indexName: "brew_all",
    homepage: "https://brew.sh/",
  },
  {
    name: "Prettier",
    icon: "https://prettier.io/icon.png",
    apiKey: "9fcdb2a62af4c47cc5eecf3d5a747818",
    appId: "BH4D9OD16A",
    indexName: "prettier",
    homepage: "https://prettier.io/",
  },
  {
    name: "React",
    icon: "https://reactjs.org/favicon.ico",
    apiKey: "36221914cce388c46d0420343e0bb32e",
    appId: "BH4D9OD16A",
    indexName: "react",
    homepage: "https://reactjs.org/",
  },
  {
    name: "React",
    icon: "https://zh-hans.reactjs.org/favicon.ico",
    apiKey: "72499aaa151dba0828babe727c7b86ee",
    appId: "BH4D9OD16A",
    indexName: "reactjs_zh-hans",
    homepage: "https://zh-hans.reactjs.org/",
    subtitle: "zh-Hans",
  },
  {
    name: "RSSHub",
    icon: "https://docs.rsshub.app/logo.png",
    apiKey: "6247bc0db93150fd9e531b93a3fa4046",
    appId: "BH4D9OD16A",
    indexName: "rsshub",
    homepage: "https://docs.rsshub.app/",
  },
  {
    name: "Slidev",
    icon: "https://cn.sli.dev/favicon.png",
    apiKey: "1a5c5a504139c58f428974c78c55291d",
    appId: "BH4D9OD16A",
    indexName: "slidev",
    homepage: "https://cn.sli.dev/",
    subtitle: "zh-Hans",
    searchParameters: {
      facetFilters: ["language:cn"],
    },
  },
  {
    name: "TailWindCSS v3",
    icon: "https://tailwindcss.com/favicons/favicon-16x16.png?v=3",
    apiKey: "5fc87cef58bb80203d2207578309fab6",
    appId: "KNPXZI5B0M",
    indexName: "tailwindcss",
    homepage: "https://tailwindcss.com/",
  },
  {
    name: "Unidata",
    icon: "https://unidata.app/images/logo.png",
    apiKey: "3f968df846740a9e2b38e89d8e6ce9fa",
    appId: "LNA1UZCPZB",
    indexName: "unidata",
    homepage: "https://unidata.app/",
    searchParameters: {
      facetFilters: ["lang:en-US"],
    },
  },
  {
    name: "Vite",
    icon: "https://vitejs.dev/logo.svg",
    apiKey: "b573aa848fd57fb47d693b531297403c",
    appId: "BH4D9OD16A",
    indexName: "vitejs",
    homepage: "https://vitejs.dev/",
  },
  {
    name: "Vite",
    icon: "https://vitejs.dev/logo.svg",
    apiKey: "b573aa848fd57fb47d693b531297403c",
    appId: "BH4D9OD16A",
    indexName: "vitejs",
    homepage: "https://cn.vitejs.dev/",
    subtitle: "zh-Hans",
    searchParameters: {
      facetFilters: ["tags:cn"],
    },
  },
  {
    name: "Vitest",
    icon: "https://vitest.dev/logo.svg",
    apiKey: "9c3ced6fed60d2670bb36ab7e8bed8bc",
    appId: "ZTF29HGJ69",
    indexName: "vitest",
    homepage: "https://vitest.dev/",
  },
  {
    name: "Vue3",
    icon: "https://vuejs.org/logo.svg",
    apiKey: "f49cbd92a74532cc55cfbffa5e5a7d01",
    appId: "ML0LEBN7FQ",
    indexName: "vuejs",
    homepage: "https://vuejs.org/",
  },
  {
    name: "VueUse",
    icon: "https://vueuse.org/favicon.svg",
    apiKey: "a99ef8de1b2b27949975ce96642149c6",
    appId: "BH4D9OD16A",
    indexName: "vueuse",
    homepage: "https://vueuse.org/",
  },
  {
    name: "Vuepress v1",
    icon: "https://vuepress.vuejs.org/hero.png",
    apiKey: "3a539aab83105f01761a137c61004d85",
    appId: "BH4D9OD16A",
    indexName: "vuepress",
    homepage: "https://vuepress.vuejs.org/",
  },
  {
    name: "Vuepress v2",
    icon: "https://v2.vuepress.vuejs.org/images/hero.png",
    apiKey: "9a9058b8655746634e01071411c366b8",
    appId: "34YFD9IUQ2",
    indexName: "vuepress",
    homepage: "https://v2.vuepress.vuejs.org/",
  },
];
