// AUTO-GENERATED by apps/raycast/scripts/generate-tools.ts.
// Don't edit by hand — re-run `yarn workspace saasflow-raycast generate-tools`
// (also runs automatically before `dev` and `build`).
import { runEndpoint } from "../lib/runEndpoint.js";

type Input = {
    /** SaaSFlow company id (UUID). Omit to use the currently active company. */
    companyId?: string;
    startDate: string;
    endDate: string;
    limit?: number;
};

export default async function dataTopExpenseVendors(input: Input): Promise<Record<string, unknown>> {
    const { companyId, startDate, endDate, limit } = input;

    return runEndpoint({
        method: "POST",
        pathTemplate: "/companies/{companyId}/data/topExpenseVendors",
        companyId,
        body: { startDate, endDate, limit },
    });
}
