// AUTO-GENERATED by apps/raycast/scripts/generate-tools.ts.
// Don't edit by hand — re-run `yarn workspace saasflow-raycast generate-tools`
// (also runs automatically before `dev` and `build`).
import { runEndpoint } from "../lib/runEndpoint.js";

type Input = {
    /** SaaSFlow company id (UUID). Omit to use the currently active company. */
    companyId?: string;
    month: string;
    horizon?: "monthly" | "annual";
    /** MRR variant. cmrr = committed MRR (CMRR), mrr = recognised MRR. */
    mrrType: "cmrr" | "mrr";
    /** IANA time zone. Defaults to BatchContext.timeZone, then UTC. */
    timeZone?: string;
};

export default async function dataRetentionCohortDetail(input: Input): Promise<Record<string, unknown>> {
    const { companyId, month, horizon, mrrType, timeZone } = input;

    return runEndpoint({
        method: "POST",
        pathTemplate: "/companies/{companyId}/data/retentionCohortDetail",
        companyId,
        body: { month, horizon, mrrType, timeZone },
    });
}
