// AUTO-GENERATED by apps/raycast/scripts/generate-tools.ts.
// Don't edit by hand — re-run `yarn workspace saasflow-raycast generate-tools`
// (also runs automatically before `dev` and `build`).
import { runEndpoint } from '../lib/runEndpoint.js';

type Input = {};

export default async function listCompanies(input: Input): Promise<Record<string, unknown>> {
    return runEndpoint({
        method: 'GET',
        pathTemplate: '/companies',
    });
}
