// AUTO-GENERATED by apps/raycast/scripts/generate-tools.ts.
// Don't edit by hand — re-run `yarn workspace saasflow-raycast generate-tools`
// (also runs automatically before `dev` and `build`).
import { runEndpoint } from "../lib/runEndpoint.js";

type Input = {
    /** SaaSFlow company id (UUID). Omit to use the currently active company. */
    companyId?: string;
    q: string;
};

export default async function search(input: Input): Promise<Record<string, unknown>> {
    const { companyId, q } = input;

    return runEndpoint({
        method: "GET",
        pathTemplate: "/companies/{companyId}/search",
        companyId,
        query: { q },
    });
}
