export const defaultKeyboardOptions = {
  en: {
    label: "English",
    variants: [
      { name: "ABC", type: "ANSI" },
      { name: "ABC \u2013 Extended", type: "ANSI" },
      { name: "ABC \u2013 India", type: "ANSI" },
      { name: "Australian", type: "ANSI" },
      { name: "British", type: "ISO" },
      { name: "British \u2013 PC", type: "ISO" },
      { name: "Canadian English", type: "ANSI" },
      { name: "Colemak", type: "ANSI" },
      { name: "Dvorak", type: "ANSI" },
      { name: "U.S.", type: "ANSI" },
      { name: "U.S. International \u2013 PC", type: "ANSI" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  ar: {
    label: "Arabic",
    variants: [
      { name: "Arabic", type: "ANSI" },
      { name: "Arabic \u2013 123", type: "ANSI" },
      { name: "Arabic \u2013 AZERTY", type: "ANSI" },
      { name: "Arabic \u2013 PC", type: "ANSI" },
      { name: "Arabic \u2013 QWERTY", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  hy: {
    label: "Armenian",
    variants: [
      { name: "Armenian \u2013 HM QWERTY", type: "ANSI" },
      { name: "Armenian \u2013 Western QWERTY", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  az: { label: "Azerbaijani", variants: [{ name: "Azeri", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  nl: {
    label: "Dutch",
    variants: [
      { name: "Dutch", type: "ISO" },
      { name: "Belgian", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  bn: {
    label: "Manipuri (Bangla)",
    variants: [{ name: "Manipuri (Bengali)", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  bg: {
    label: "Bulgarian",
    variants: [
      { name: "Bulgarian", type: "ISO" },
      { name: "Bulgarian \u2013 QWERTY", type: "ISO" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  my: {
    label: "Burmese",
    variants: [
      { name: "Myanmar", type: "ANSI" },
      { name: "Myanmar \u2013 QWERTY", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  cherokee: {
    label: "Cherokee",
    variants: [
      { name: "Cherokee \u2013 Nation", type: "ANSI" },
      { name: "Cherokee \u2013 QWERTY", type: "ANSI" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  zh: {
    label: "Chinese",
    variants: [
      { name: "Pinyin \u2013 Simplified", type: "ANSI" },
      { name: "Cangjie", type: "ANSI" },
      { name: "Pinyin \u2013 Traditional", type: "ANSI" },
      { name: "Stroke \u2013 Traditional", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  hr: {
    label: "Croatian",
    variants: [
      { name: "Croatian", type: "ISO" },
      { name: "Croatian \u2013 PC", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  cs: {
    label: "Czech",
    variants: [
      { name: "Czech", type: "ISO" },
      { name: "Czech \u2013 QWERTY", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  da: { label: "Danish", variants: [{ name: "Danish", type: "ISO" }], addLatinKeys: false, keyVariant: "lower" },
  et: { label: "Estonian", variants: [{ name: "Estonian", type: "ISO" }], addLatinKeys: false, keyVariant: "lower" },
  fi: {
    label: "Finnish",
    variants: [
      { name: "Finnish", type: "ISO" },
      { name: "Finnish \u2013 Extended", type: "ISO" },
      { name: "Finnish Sami \u2013 PC", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  fr: {
    label: "French",
    variants: [
      { name: "ABC \u2013 AZERTY", type: "ISO" },
      { name: "Canadian French \u2013 CSA", type: "ISO" },
      { name: "Canadian French \u2013 PC", type: "ISO" },
      { name: "French", type: "ISO" },
      { name: "French \u2013 Numerical", type: "ISO" },
      { name: "French \u2013 PC", type: "ISO" },
      { name: "Swiss French", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  de: {
    label: "German",
    variants: [
      { name: "ABC \u2013 QWERTZ", type: "ISO" },
      { name: "Austrian", type: "ISO" },
      { name: "German", type: "ISO" },
      { name: "German \u2013 Standard", type: "ISO" },
      { name: "Swiss German", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  ka: {
    label: "Georgian",
    variants: [{ name: "Georgian \u2013 QWERTY", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  el: {
    label: "Greek",
    variants: [
      { name: "Greek", type: "ISO" },
      { name: "Greek \u2013 Polytonic", type: "ISO" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  gu: {
    label: "Gujarati",
    variants: [
      { name: "Gujarati", type: "ANSI" },
      { name: "Gujarati \u2013 QWERTY", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  he: {
    label: "Hebrew",
    variants: [
      { name: "Hebrew", type: "ANSI" },
      { name: "Hebrew \u2013 PC", type: "ANSI" },
      { name: "Hebrew \u2013 QWERTY", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  hi: {
    label: "Hindi",
    variants: [
      { name: "Devanagari \u2013 QWERTY", type: "ANSI" },
      { name: "Hindi", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  hu: { label: "Hungarian", variants: [{ name: "Hungarian", type: "ISO" }], addLatinKeys: false, keyVariant: "lower" },
  is: { label: "Icelandic", variants: [{ name: "Icelandic", type: "ISO" }], addLatinKeys: false, keyVariant: "lower" },
  iu: {
    label: "Inuktitut",
    variants: [
      { name: "Inuktitut \u2013 Nunavut", type: "ANSI" },
      { name: "Inuktitut \u2013 Nutaaq", type: "ANSI" },
      { name: "Inuktitut \u2013 QWERTY", type: "ANSI" },
      { name: "Inuktitut Nunavik", type: "ANSI" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  it: {
    label: "Italian",
    variants: [
      { name: "Italian", type: "ISO" },
      { name: "Italian \u2013 QZERTY", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  ja: {
    label: "Japanese",
    variants: [{ name: "Japanese \u2013 Kana", type: "JIS" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  kk: { label: "Kazakh", variants: [{ name: "Kazakh", type: "ISO" }], addLatinKeys: true, keyVariant: "lower" },
  kh: { label: "Khmer", variants: [{ name: "Khmer", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  ko: {
    label: "Korean",
    variants: [
      { name: "2-Set Korean", type: "ANSI" },
      { name: "3-Set Korean", type: "ANSI" },
      { name: "390 Sebulshik", type: "ANSI" },
      { name: "GongjinCheong Romaja", type: "ANSI" },
      { name: "HNC Romaja", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  ku: {
    label: "Kurdish",
    variants: [{ name: "Kurmanji Kurdish", type: "ANSI" }],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  lv: { label: "Latvian", variants: [{ name: "Latvian", type: "ISO" }], addLatinKeys: false, keyVariant: "lower" },
  lt: {
    label: "Lithuanian",
    variants: [{ name: "Lithuanian", type: "ISO" }],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  mk: { label: "Macedonian", variants: [{ name: "Macedonian", type: "ISO" }], addLatinKeys: true, keyVariant: "lower" },
  ml: {
    label: "Malayalam",
    variants: [
      { name: "Malayalam", type: "ANSI" },
      { name: "Malayalam \u2013 QWERTY", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  mt: { label: "Maltese", variants: [{ name: "Maltese", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  ne: {
    label: "Nepali",
    variants: [
      { name: "Nepali \u2013 India", type: "ANSI" },
      { name: "Nepali \u2013 Remington", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  se: {
    label: "Northern Sami",
    variants: [
      { name: "Northern Sami", type: "ISO" },
      { name: "Sami \u2013 PC", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  nb: {
    label: "Norwegian",
    variants: [
      { name: "Norwegian", type: "ISO" },
      { name: "Norwegian \u2013 Extended", type: "ISO" },
      { name: "Norwegian Sami \u2013 PC", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  oy: {
    label: "Odia",
    variants: [
      { name: "Odia", type: "ANSI" },
      { name: "Odia \u2013 QWERTY", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  ps: { label: "Pashto", variants: [{ name: "Afghan Pashto", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  fa: {
    label: "Persian",
    variants: [
      { name: "Afghan Dari", type: "ANSI" },
      { name: "Persian \u2013 Legacy", type: "ANSI" },
      { name: "Persian \u2013 QWERTY", type: "ANSI" },
      { name: "Persian \u2013 Standard", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  pl: {
    label: "Polish",
    variants: [
      { name: "Polish", type: "ANSI" },
      { name: "Polish \u2013 QWERTZ", type: "ANSI" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  pt: {
    label: "Portuguese",
    variants: [
      { name: "Brazilian", type: "ISO" },
      { name: "Brazilian \u2013 ABNT2", type: "ISO" },
      { name: "Brazilian \u2013 Legacy", type: "ISO" },
      { name: "Portuguese", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  pa: { label: "Punjabi", variants: [{ name: "Gurmukhi", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  ro: {
    label: "Romanian",
    variants: [
      { name: "Romanian", type: "ISO" },
      { name: "Romanian \u2013 Standard", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  ru: {
    label: "Russian",
    variants: [
      { name: "Russian", type: "ISO" },
      { name: "Russian \u2013 PC", type: "ISO" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  sr: {
    label: "Serbian",
    variants: [
      { name: "Serbian", type: "ANSI" },
      { name: "Serbian (Latin)", type: "ISO" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  si: { label: "Sinhala", variants: [{ name: "Sinhala", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  sk: { label: "Slovak", variants: [{ name: "Slovak", type: "ISO" }], addLatinKeys: false, keyVariant: "lower" },
  sl: { label: "Slovenian", variants: [{ name: "Slovenian", type: "ISO" }], addLatinKeys: false, keyVariant: "lower" },
  es: {
    label: "Spanish",
    variants: [
      { name: "Latin American", type: "ISO" },
      { name: "Spanish", type: "ISO" },
      { name: "Spanish \u2013 Legacy", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  sv: {
    label: "Swedish",
    variants: [
      { name: "Swedish", type: "ISO" },
      { name: "Swedish \u2013 Legacy", type: "ISO" },
      { name: "Swedish Sami \u2013 PC", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  ta: { label: "Tamil", variants: [{ name: "Tamil 99", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  th: {
    label: "Thai",
    variants: [
      { name: "Thai", type: "ANSI" },
      { name: "Thai \u2013 Pattachote", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  bo: {
    label: "Tibetan",
    variants: [
      { name: "Tibetan \u2013 Otani", type: "ANSI" },
      { name: "Tibetan \u2013 QWERTY", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  tr: {
    label: "Turkish",
    variants: [
      { name: "Turkish F", type: "ISO" },
      { name: "Turkish F \u2013 Legacy", type: "ISO" },
      { name: "Turkish Q", type: "ISO" },
      { name: "Turkish Q \u2013 Legacy", type: "ISO" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  uk: {
    label: "Ukrainian",
    variants: [
      { name: "Ukrainian", type: "ISO" },
      { name: "Ukrainian \u2013 Legacy", type: "ISO" },
      { name: "Ukrainian \u2013 QWERTY", type: "ISO" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  ur: { label: "Urdu", variants: [{ name: "Urdu", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  ug: { label: "Uyghur", variants: [{ name: "Uyghur", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  uz: {
    label: "Uzbek",
    variants: [
      { name: "Afghan Uzbek", type: "ANSI" },
      { name: "Uzbek (Cyrillic)", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  vi: {
    label: "Vietnamese",
    variants: [{ name: "Vietnamese", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Albanian: {
    label: "Albanian",
    variants: [{ name: "Albanian", type: "ANSI" }],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  Dhivehi: { label: "Dhivehi", variants: [{ name: "Dhivehi", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Dogri: { label: "Dogri", variants: [{ name: "Dogri", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Maori: { label: "Maori", variants: [{ name: "Maori", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  "Hanifi Rohingya": {
    label: "Hanifi Rohingya",
    variants: [{ name: "Hanifi Rohingya", type: "ANSI" }],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  Irish: {
    label: "Irish",
    variants: [
      { name: "Irish \u2013 Extended", type: "ANSI" },
      { name: "Irish", type: "ANSI" },
    ],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  Turkmen: {
    label: "Turkmen",
    variants: [{ name: "Turkmen", type: "ANSI" }],
    addLatinKeys: false,
    keyVariant: "lower",
  },
  Syriac: {
    label: "Syriac",
    variants: [
      { name: "Syriac \u2013 QWERTY", type: "ANSI" },
      { name: "Syriac \u2013 Arabic", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Konkani: { label: "Konkani", variants: [{ name: "Konkani", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Welsh: { label: "Welsh", variants: [{ name: "Welsh", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  Maithili: {
    label: "Maithili",
    variants: [{ name: "Maithili", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Sanskrit: {
    label: "Sanskrit",
    variants: [{ name: "Sanskrit", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  "Kashmiri (Devanagari)": {
    label: "Kashmiri (Devanagari)",
    variants: [{ name: "Kashmiri (Devanagari)", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Assamese: {
    label: "Assamese",
    variants: [{ name: "Assamese", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Jawi: { label: "Jawi", variants: [{ name: "Jawi", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Tajik: {
    label: "Tajik",
    variants: [{ name: "Tajik (Cyrillic)", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Kyrgyz: { label: "Kyrgyz", variants: [{ name: "Kyrgyz", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Navajo: { label: "Navajo", variants: [{ name: "Navajo", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  Belarusian: {
    label: "Belarusian",
    variants: [{ name: "Belarusian", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Igbo: { label: "Igbo", variants: [{ name: "Igbo", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  Bangla: { label: "Bangla", variants: [{ name: "Bangla", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Mongolian: {
    label: "Mongolian",
    variants: [{ name: "Mongolian", type: "ANSI" }],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Adlam: { label: "Adlam", variants: [{ name: "Adlam", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  Hawaii: { label: "Hawaii", variants: [{ name: "Hawaiian", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  Sindhi: { label: "Sindhi", variants: [{ name: "Sindhi", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Tongan: { label: "Tongan", variants: [{ name: "Tongan", type: "ANSI" }], addLatinKeys: false, keyVariant: "lower" },
  Lao: { label: "Lao", variants: [{ name: "Lao", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Marathi: { label: "Marathi", variants: [{ name: "Marathi", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Santali: {
    label: "Santali",
    variants: [
      { name: "Sindhi (Devanagari)", type: "ANSI" },
      { name: "Santali (Devanagari)", type: "ANSI" },
    ],
    addLatinKeys: true,
    keyVariant: "lower",
  },
  Bodo: { label: "Bodo", variants: [{ name: "Bodo", type: "ANSI" }], addLatinKeys: true, keyVariant: "lower" },
  Faroese: {
    label: "Faroese",
    variants: [{ name: "Faroese", type: "ANSI" }],
    addLatinKeys: false,
    keyVariant: "lower",
  },
};

export const keyboardToOptions = Object.entries(defaultKeyboardOptions).reduce((accumulator, [, value]) => {
  return {
    ...accumulator,
    ...value.variants.reduce((variantAccumulator, variant) => {
      return {
        ...variantAccumulator,
        [variant.name]: {
          addLatinKeys: value.addLatinKeys,
          keyVariant: value.keyVariant,
          keyboardID: variant.name,
          keyboardType: variant.type,
        },
      };
    }, {}),
  };
}, {});
