import { List } from "@raycast/api";
import { useCachedState } from "@raycast/utils";
import React, { useEffect, useState } from "react";
import { Course } from "./components/course";
import { Assignment } from "./components/assignment";
import { Announcement } from "./components/announcement";
import { Quiz } from "./components/quiz";
import { EmptyView } from "./components/error-view";
import { checkApi, getCourses, getAnnouncements, getDatedFeed } from "./utils/api";
import { course, announcement, assignment, plannernote, datefeed } from "./utils/types";
import { Error, Icons } from "./utils/utils";

export default function main() {
  const [feedItems, setFeedItems] = useState<datefeed[]>();
  const [courses, setCourses] = useState<course[]>();
  const [filter, setFilter] = useState<string>("all");

  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState(Error.INVALID_API_KEY);

  useEffect(() => {
    const getItems = async () => {
      try {
        const json = await checkApi();
        if (json.status == "unauthenticated" || !(json instanceof Array)) {
          setCourses(undefined);
          setIsLoading(false);
          setError(Error.INVALID_API_KEY);
          return;
        }
        const courses = await getCourses(json, { noAssignments: true });
        setCourses(courses);
        const feedItems = await getDatedFeed(courses);
        setFeedItems(feedItems);
        setIsLoading(false);
      } catch (error) {
        console.error(error);
        setCourses(undefined);
        setIsLoading(false);
        setError(Error.INVALID_DOMAIN);
      }
    };
    getItems();
  }, []);

  return (
    <List
      isLoading={isLoading}
      searchBarAccessory={
        <List.Dropdown tooltip="Select filters" storeValue={true} defaultValue="all" onChange={setFilter}>
          <List.Dropdown.Item title="All items" value="all" />
          <List.Dropdown.Section title="Status">
            <List.Dropdown.Item title="To-do" value="todo" icon={Icons.ToDo} />
            <List.Dropdown.Item title="Done" value="done" icon={Icons.Completed} />
            <List.Dropdown.Item title="Missing" value="missing" icon={Icons.Missing} />
          </List.Dropdown.Section>
          <List.Dropdown.Section title="Type">
            <List.Dropdown.Item title="Announcement" value="announcement" icon={Icons.Announcement} />
            <List.Dropdown.Item title="Assignment" value="assignment" icon={Icons.Assignment} />
            <List.Dropdown.Item title="Quiz" value="quiz" icon={Icons.Quiz} />
          </List.Dropdown.Section>
        </List.Dropdown>
      }
    >
      {feedItems !== undefined ? (
        <React.Fragment>
          {feedItems.map((feedItem: datefeed) => (
            <List.Section
              title={feedItem.pretty_date}
              key={feedItem.pretty_date}
              {...(feedItem.today ? { subtitle: "Today" } : {})}
            >
              {feedItem.items
                .filter(
                  (feedItem: plannernote) =>
                    (filter == "missing" && feedItem.submission.missing) ||
                    (filter == "todo" && !feedItem.submission.submitted && feedItem.custom_type !== "announcement") ||
                    (filter == "done" && feedItem.submission.submitted && feedItem.custom_type !== "announcement") ||
                    (filter == "assignment" && feedItem.custom_type == "assignment") ||
                    (filter == "announcement" && feedItem.custom_type == "announcement") ||
                    (filter == "quiz" && feedItem.custom_type == "quiz") ||
                    filter == "all"
                )
                .filter(
                  (feedItem: plannernote) =>
                    feedItem.custom_type == "announcement" ||
                    feedItem.custom_type == "assignment" ||
                    feedItem.custom_type == "quiz"
                )
                .map((feedItem: plannernote) =>
                  feedItem.custom_type == "announcement" ? (
                    <Announcement
                      key={feedItem.custom_object.id}
                      {...feedItem.announcement}
                      course_color={
                        courses.filter((course: course) => course.id == feedItem.custom_object.course_id)[0].color
                      }
                    />
                  ) : feedItem.custom_type == "assignment" ? (
                    <Assignment
                      submitted={feedItem.submission.submitted}
                      key={feedItem.custom_object.id}
                      special_missing={feedItem.submission.missing}
                      course_color={
                        courses.filter((course: course) => course.id == feedItem.custom_object.course_id)[0].color
                      }
                      {...feedItem.assignment}
                    />
                  ) : (
                    (() => {
                      return (
                        <Quiz
                          submitted={feedItem.submission.submitted}
                          key={feedItem.custom_object.id}
                          special_missing={feedItem.submission.missing}
                          course_color={
                            courses.filter((course: course) => course.id == feedItem.custom_object.course_id)[0].color
                          }
                          {...feedItem.quiz}
                        />
                      );
                    })()
                  )
                )}
            </List.Section>
          ))}
        </React.Fragment>
      ) : (
        <EmptyView error={error} />
      )}
    </List>
  );
}

[
  {
    date: "2022-09-26T23:00:00.000Z",
    today: false,
    items: [
      {
        id: 1284719,
        title: "Women in the French Revolution (U2 Day 5)",
        type: "assignment",
        creation_date: "2022-08-16T18:54:48.000Z",
        due_date: "2022-09-26T23:00:00.000Z",
        plannable_date: "2022-09-26T23:00:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Women in the French Revolution (U2 Day 5)",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284719,
          date: "2022-09-26T23:00:00.000Z",
          pretty_date: "Due by 4:00 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Women in the French Revolution (U2 Day 5)",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284719,
          date: "2022-09-26T23:00:00.000Z",
          pretty_date: "Due by 4:00 PM",
          time: true,
        },
      },
      {
        id: 1318035,
        title: "2.2 Division of Polynomials",
        type: "assignment",
        creation_date: "2022-09-08T18:54:49.000Z",
        due_date: "2022-09-27T06:59:59.000Z",
        plannable_date: "2022-09-27T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "2.2 Division of Polynomials",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 1318035,
          date: "2022-09-27T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "2.2 Division of Polynomials",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 1318035,
          date: "2022-09-27T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
    ],
    pretty_date: "Monday, September 26",
  },
  {
    date: "2022-09-27T19:20:00Z",
    today: false,
    items: [
      {
        id: 1288055,
        title: "Unit 2 Survival The Most Dangerous Game",
        type: "assignment",
        creation_date: "2022-08-16T22:07:00.000Z",
        due_date: "2022-09-28T06:59:00.000Z",
        plannable_date: "2022-09-28T06:59:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival The Most Dangerous Game",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288055,
          date: "2022-09-28T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: true,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: true,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival The Most Dangerous Game",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288055,
          date: "2022-09-28T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1288033,
        title: "Unit 2 Survival  Introduction",
        type: "assignment",
        creation_date: "2022-08-16T22:06:51.000Z",
        due_date: "2022-09-28T06:59:59.000Z",
        plannable_date: "2022-09-28T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival  Introduction",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288033,
          date: "2022-09-28T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: true,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: true,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival  Introduction",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288033,
          date: "2022-09-28T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1288058,
        title: "Unit 2 Survival The Seventh Man Project",
        type: "assignment",
        creation_date: "2022-08-16T22:07:02.000Z",
        due_date: "2022-09-28T06:59:59.000Z",
        plannable_date: "2022-09-28T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival The Seventh Man Project",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288058,
          date: "2022-09-28T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: true,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: true,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival The Seventh Man Project",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288058,
          date: "2022-09-28T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1288059,
        title: "Unit 2 Survival The Seventh Man Summary and Reading",
        type: "assignment",
        creation_date: "2022-08-16T22:07:02.000Z",
        due_date: "2022-09-28T06:59:59.000Z",
        plannable_date: "2022-09-28T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival The Seventh Man Summary and Reading",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288059,
          date: "2022-09-28T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: true,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: true,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival The Seventh Man Summary and Reading",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288059,
          date: "2022-09-28T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 760480,
        title: "HOCO Dance Tickets ON SALE NOW! ",
        type: "announcement",
        creation_date: "2022-09-27T16:40:02.000Z",
        plannable_date: "2022-09-27T19:20:00Z",
        custom_type: "announcement",
        custom_object: {
          title: "HOCO Dance Tickets ON SALE NOW! ",
          course_id: 111439,
          color: "raycast-orange",
          course: "Irvine High School ",
          id: 760480,
          pretty_date: "9:40 AM",
          date: "2022-09-27T16:40:02.000Z",
          time: true,
        },
        submission: false,
        announcement: {
          title: "HOCO Dance Tickets ON SALE NOW! ",
          course_id: 111439,
          color: "raycast-orange",
          course: "Irvine High School ",
          id: 760480,
          pretty_date: "9:40 AM",
          date: "2022-09-27T16:40:02.000Z",
          time: true,
        },
      },
      {
        id: 760546,
        title: "Extra Practice for Unit 2 Exam",
        type: "announcement",
        creation_date: "2022-09-27T21:32:25.000Z",
        plannable_date: "2022-09-27T21:32:25Z",
        custom_type: "announcement",
        custom_object: {
          title: "Extra Practice for Unit 2 Exam",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 760546,
          pretty_date: "2:32 PM",
          date: "2022-09-27T21:32:25.000Z",
          time: true,
        },
        submission: false,
        announcement: {
          title: "Extra Practice for Unit 2 Exam",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 760546,
          pretty_date: "2:32 PM",
          date: "2022-09-27T21:32:25.000Z",
          time: true,
        },
      },
      {
        id: 744818,
        title: "Unit 2 The Seventh Man Discussion Question",
        type: "discussion_topic",
        creation_date: "2022-08-16T22:06:10.000Z",
        due_date: "2022-09-28T06:59:00.000Z",
        plannable_date: "2022-09-28T06:59:00Z",
        submission: {
          submitted: true,
          excused: false,
          graded: true,
          posted_at: "2022-09-23T16:33:57Z",
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
      },
      {
        id: 1321779,
        title: "Interpersonal Interview practice questions",
        type: "assignment",
        creation_date: "2022-09-20T21:45:06.000Z",
        due_date: "2022-09-28T06:59:59.000Z",
        plannable_date: "2022-09-28T06:59:59Z",
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
      },
    ],
    pretty_date: "Tuesday, September 27",
  },
  {
    date: "2022-09-28T15:30:00.000Z",
    today: false,
    items: [
      {
        id: 1288041,
        title: "Unit 2 Survival Argumentative Writing Workshop 2 Hooks, Background Information, Transitions",
        type: "assignment",
        creation_date: "2022-08-16T22:06:53.000Z",
        due_date: "2022-09-29T06:59:00.000Z",
        plannable_date: "2022-09-29T06:59:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival Argumentative Writing Workshop 2 Hooks, Background Information, Transitions",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288041,
          date: "2022-09-29T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival Argumentative Writing Workshop 2 Hooks, Background Information, Transitions",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288041,
          date: "2022-09-29T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1288056,
        title: "Unit 2 Survival The Seventh Man - Concept Vocabulary",
        type: "assignment",
        creation_date: "2022-08-16T22:07:01.000Z",
        due_date: "2022-09-29T06:59:59.000Z",
        plannable_date: "2022-09-29T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival The Seventh Man - Concept Vocabulary",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288056,
          date: "2022-09-29T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: true,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: true,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival The Seventh Man - Concept Vocabulary",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288056,
          date: "2022-09-29T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1319251,
        title: "Prep Work: Ch. 4 Lessons 3 & 4 Review Questions",
        type: "assignment",
        creation_date: "2022-09-12T18:32:39.000Z",
        due_date: "2022-09-28T15:30:00.000Z",
        plannable_date: "2022-09-28T15:30:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Prep Work: Ch. 4 Lessons 3 & 4 Review Questions",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1319251,
          date: "2022-09-28T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
        submission: {
          submitted: true,
          excused: false,
          graded: true,
          posted_at: "2022-09-29T17:55:02Z",
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Prep Work: Ch. 4 Lessons 3 & 4 Review Questions",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1319251,
          date: "2022-09-28T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
      },
      {
        id: 1284595,
        title: "Timeline of the French Revolution (U2 Day 6)",
        type: "assignment",
        creation_date: "2022-08-16T18:54:22.000Z",
        due_date: "2022-09-28T19:05:00.000Z",
        plannable_date: "2022-09-28T19:05:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Timeline of the French Revolution (U2 Day 6)",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284595,
          date: "2022-09-28T19:05:00.000Z",
          pretty_date: "Due by 12:05 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Timeline of the French Revolution (U2 Day 6)",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284595,
          date: "2022-09-28T19:05:00.000Z",
          pretty_date: "Due by 12:05 PM",
          time: true,
        },
      },
      {
        id: 1321436,
        title: "Too Much Time On My Hands #2 (ALL INSTRUMENTAL STUDENTS)",
        type: "assignment",
        creation_date: "2022-09-19T22:09:49.000Z",
        due_date: "2022-09-29T06:59:59.000Z",
        plannable_date: "2022-09-29T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "Too Much Time On My Hands #2 (ALL INSTRUMENTAL STUDENTS)",
          course_id: 106966,
          color: "raycast-yellow",
          course: "Marching Band",
          id: 1321436,
          date: "2022-09-29T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: true,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Too Much Time On My Hands #2 (ALL INSTRUMENTAL STUDENTS)",
          course_id: 106966,
          color: "raycast-yellow",
          course: "Marching Band",
          id: 1321436,
          date: "2022-09-29T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 760442,
        title: "Unit 2 Quiz Corrections Access Code",
        type: "announcement",
        creation_date: "2022-09-27T14:53:26.000Z",
        plannable_date: "2022-09-28T17:00:02Z",
        custom_type: "announcement",
        custom_object: {
          title: "Unit 2 Quiz Corrections Access Code",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 760442,
          pretty_date: "7:53 AM",
          date: "2022-09-27T14:53:26.000Z",
          time: true,
        },
        submission: false,
        announcement: {
          title: "Unit 2 Quiz Corrections Access Code",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 760442,
          pretty_date: "7:53 AM",
          date: "2022-09-27T14:53:26.000Z",
          time: true,
        },
      },
      {
        id: 322533,
        title: "Unit 2.Review Quiz",
        type: "quiz",
        creation_date: "2022-09-09T21:33:33.000Z",
        plannable_date: "2022-09-28T16:55:00Z",
        custom_type: "quiz",
        custom_object: {
          name: "Unit 2.Review Quiz",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 322533,
          date: "2022-09-28T16:55:00.000Z",
          pretty_date: "Due by 9:55 AM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: true,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        quiz: {
          name: "Unit 2.Review Quiz",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 322533,
          date: "2022-09-28T16:55:00.000Z",
          pretty_date: "Due by 9:55 AM",
          time: true,
        },
      },
      {
        id: 1318071,
        title: "2.3 Factoring",
        type: "assignment",
        creation_date: "2022-09-08T20:24:03.000Z",
        due_date: "2022-09-29T06:59:59.000Z",
        plannable_date: "2022-09-29T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "2.3 Factoring",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 1318071,
          date: "2022-09-29T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "2.3 Factoring",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 1318071,
          date: "2022-09-29T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 323476,
        title: "Sp2 Ch1 Prueba de vocabulario versión A",
        type: "quiz",
        creation_date: "2022-09-28T04:32:52.000Z",
        due_date: "2022-09-29T06:59:59.000Z",
        plannable_date: "2022-09-29T06:59:59Z",
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: true,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
      },
      {
        id: 323482,
        title: "Sp2 Ch1 Prueba de vocabulario versión B",
        type: "quiz",
        creation_date: "2022-09-28T06:13:10.000Z",
        due_date: "2022-09-29T06:59:59.000Z",
        plannable_date: "2022-09-29T06:59:59Z",
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: true,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
      },
    ],
    pretty_date: "Wednesday, September 28",
  },
  {
    date: "2022-09-30T06:59:00.000Z",
    today: true,
    items: [
      {
        id: 1288047,
        title: "Unit 2 Survival Moral Logic Conventions",
        type: "assignment",
        creation_date: "2022-08-16T22:06:57.000Z",
        due_date: "2022-09-30T06:59:00.000Z",
        plannable_date: "2022-09-30T06:59:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival Moral Logic Conventions",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288047,
          date: "2022-09-30T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival Moral Logic Conventions",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288047,
          date: "2022-09-30T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1288053,
        title: "Unit 2 Survival The Moral Logic Summary and Reading",
        type: "assignment",
        creation_date: "2022-08-16T22:06:59.000Z",
        due_date: "2022-09-30T06:59:00.000Z",
        plannable_date: "2022-09-30T06:59:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival The Moral Logic Summary and Reading",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288053,
          date: "2022-09-30T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival The Moral Logic Summary and Reading",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288053,
          date: "2022-09-30T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1288054,
        title: "Unit 2 Survival The Moral Logic of Survivor Guilt - Concept Vocabulary",
        type: "assignment",
        creation_date: "2022-08-16T22:07:00.000Z",
        due_date: "2022-09-30T06:59:00.000Z",
        plannable_date: "2022-09-30T06:59:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival The Moral Logic of Survivor Guilt - Concept Vocabulary",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288054,
          date: "2022-09-30T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival The Moral Logic of Survivor Guilt - Concept Vocabulary",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288054,
          date: "2022-09-30T06:59:00.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
    ],
    pretty_date: "Thursday, September 29",
  },
  {
    date: "2022-09-30T15:30:00Z",
    today: false,
    items: [
      {
        id: 1284586,
        title: "Timeline Review & Background to Haitian Revolution (U2 Day 7)",
        type: "assignment",
        creation_date: "2022-08-16T18:54:20.000Z",
        due_date: "2022-09-30T19:05:00.000Z",
        plannable_date: "2022-09-30T19:05:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Timeline Review & Background to Haitian Revolution (U2 Day 7)",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284586,
          date: "2022-09-30T19:05:00.000Z",
          pretty_date: "Due by 12:05 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Timeline Review & Background to Haitian Revolution (U2 Day 7)",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284586,
          date: "2022-09-30T19:05:00.000Z",
          pretty_date: "Due by 12:05 PM",
          time: true,
        },
      },
      {
        id: 1284714,
        title: "Week 7 Reflection",
        type: "assignment",
        creation_date: "2022-08-16T18:54:47.000Z",
        due_date: "2022-10-01T05:00:00.000Z",
        plannable_date: "2022-10-01T05:00:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Week 7 Reflection",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284714,
          date: "2022-10-01T05:00:00.000Z",
          pretty_date: "Due by 10:00 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Week 7 Reflection",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284714,
          date: "2022-10-01T05:00:00.000Z",
          pretty_date: "Due by 10:00 PM",
          time: true,
        },
      },
      {
        id: 322534,
        title: "Unit 2.Review Quiz - Corrections - Access Code: divide",
        type: "quiz",
        creation_date: "2022-09-09T21:33:34.000Z",
        plannable_date: "2022-09-30T15:30:00Z",
        custom_type: "quiz",
        custom_object: {
          name: "Unit 2.Review Quiz - Corrections - Access Code: divide",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 322534,
          date: "2022-09-30T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        quiz: {
          name: "Unit 2.Review Quiz - Corrections - Access Code: divide",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 322534,
          date: "2022-09-30T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
      },
      {
        id: 1322171,
        title: "Unit 2 - Targeted Review",
        type: "assignment",
        creation_date: "2022-09-22T15:17:12.000Z",
        due_date: "2022-10-01T06:59:59.000Z",
        plannable_date: "2022-10-01T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 - Targeted Review",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 1322171,
          date: "2022-10-01T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 - Targeted Review",
          course_id: 107045,
          color: "raycast-green",
          course: "Math",
          id: 1322171,
          date: "2022-10-01T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1324520,
        title: "Sept 28 Workbooks pgs Vocabulario 1&2 ",
        type: "assignment",
        creation_date: "2022-09-28T21:56:11.000Z",
        due_date: "2022-10-01T06:59:59.000Z",
        plannable_date: "2022-10-01T06:59:59Z",
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
      },
    ],
    pretty_date: "Friday, September 30",
  },
  {
    date: "2022-10-04T06:59:59.000Z",
    today: false,
    items: [
      {
        id: 1288063,
        title: "Unit 2 Survival: The Moral Logic Project",
        type: "assignment",
        creation_date: "2022-08-16T22:07:04.000Z",
        due_date: "2022-10-04T06:59:59.000Z",
        plannable_date: "2022-10-04T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Survival: The Moral Logic Project",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288063,
          date: "2022-10-04T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Survival: The Moral Logic Project",
          course_id: 106984,
          color: "raycast-purple",
          course: "English",
          id: 1288063,
          date: "2022-10-04T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
    ],
    pretty_date: "Monday, October 3",
  },
  {
    date: "2022-10-04T15:30:00.000Z",
    today: false,
    items: [
      {
        id: 1284610,
        title: "Prep Work: Ch. 5 Lesson 4 Checking for Understanding Questions",
        type: "assignment",
        creation_date: "2022-08-16T18:54:26.000Z",
        due_date: "2022-10-04T15:30:00.000Z",
        plannable_date: "2022-10-04T15:30:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Prep Work: Ch. 5 Lesson 4 Checking for Understanding Questions",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284610,
          date: "2022-10-04T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Prep Work: Ch. 5 Lesson 4 Checking for Understanding Questions",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284610,
          date: "2022-10-04T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
      },
    ],
    pretty_date: "Tuesday, October 4",
  },
  {
    date: "2022-10-06T15:30:00.000Z",
    today: false,
    items: [
      {
        id: 1323851,
        title: "Derivations Playing Opp #2: 77-93",
        type: "assignment",
        creation_date: "2022-09-26T23:11:45.000Z",
        due_date: "2022-10-07T06:59:59.000Z",
        plannable_date: "2022-10-07T06:59:59Z",
        custom_type: "assignment",
        custom_object: {
          name: "Derivations Playing Opp #2: 77-93",
          course_id: 107154,
          color: "raycast-yellow",
          course: "Concert Band",
          id: 1323851,
          date: "2022-10-07T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Derivations Playing Opp #2: 77-93",
          course_id: 107154,
          color: "raycast-yellow",
          course: "Concert Band",
          id: 1323851,
          date: "2022-10-07T06:59:59.000Z",
          pretty_date: "Due by 11:59 PM",
          time: true,
        },
      },
      {
        id: 1284629,
        title: "Prep Work: Latin American Crash Course",
        type: "assignment",
        creation_date: "2022-08-16T18:54:31.000Z",
        due_date: "2022-10-06T15:30:00.000Z",
        plannable_date: "2022-10-06T15:30:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Prep Work: Latin American Crash Course",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284629,
          date: "2022-10-06T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Prep Work: Latin American Crash Course",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284629,
          date: "2022-10-06T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
      },
    ],
    pretty_date: "Thursday, October 6",
  },
  {
    date: "2022-10-13T15:30:00.000Z",
    today: false,
    items: [
      {
        id: 1284669,
        title: "Unit 2 Reflection",
        type: "assignment",
        creation_date: "2022-08-16T18:54:39.000Z",
        due_date: "2022-10-13T15:30:00.000Z",
        plannable_date: "2022-10-13T15:30:00Z",
        custom_type: "assignment",
        custom_object: {
          name: "Unit 2 Reflection",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284669,
          date: "2022-10-13T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
        submission: {
          submitted: false,
          excused: false,
          graded: false,
          posted_at: null,
          late: false,
          missing: false,
          needs_grading: false,
          has_feedback: false,
          redo_request: false,
        },
        assignment: {
          name: "Unit 2 Reflection",
          course_id: 107105,
          color: "raycast-red",
          course: "History",
          id: 1284669,
          date: "2022-10-13T15:30:00.000Z",
          pretty_date: "Due by 8:30 AM",
          time: true,
        },
      },
    ],
    pretty_date: "Thursday, October 13",
  },
];
