import { Icon } from "@raycast/api";
import { ConfigurationModelDefault, ConfigurationTypeCommunicationDefault } from "./config";
import { HookType, PromiseFunctionNoArgType, PromiseFunctionWithOneArgType } from "./hook";
import { AssistantDefaultTemperature, ITalkAssistant } from "../ai/type";

export const AssistantDefault: ITalkAssistant[] = [
  {
    typeCommunication: ConfigurationTypeCommunicationDefault,
    assistantId: "1",
    title: "anthropic",
    description: "claude-3-opus-20240229",
    emoji: Icon.QuestionMark,
    avatar: "",
    model: "anthropic" + "__" + "claude-3-opus-20240229",
    modelTemperature: AssistantDefaultTemperature,
    promptSystem: "Tell true",
    webhookUrl: undefined,
    additionalData: undefined,
    snippet: undefined,
    isLocal: true,
  },
  {
    typeCommunication: ConfigurationTypeCommunicationDefault,
    assistantId: "2",
    title: "cohere",
    description: "command",
    emoji: Icon.QuestionMark,
    avatar: "",
    model: "cohere" + "__" + "command",
    modelTemperature: AssistantDefaultTemperature,
    promptSystem: "Tell true",
    webhookUrl: undefined,
    additionalData: undefined,
    snippet: undefined,
    isLocal: true,
  },
  {
    typeCommunication: ConfigurationTypeCommunicationDefault,
    assistantId: "3",
    title: "groq",
    description: "llama3-8b-8192",
    emoji: Icon.QuestionMark,
    avatar: "",
    model: "groq" + "__" + "llama3-8b-8192",
    modelTemperature: AssistantDefaultTemperature,
    promptSystem: "Tell true",
    webhookUrl: undefined,
    additionalData: undefined,
    snippet: undefined,
    isLocal: true,
  },
  {
    typeCommunication: ConfigurationTypeCommunicationDefault,
    assistantId: "4",
    title: "ollama",
    description: "llama3",
    emoji: Icon.QuestionMark,
    avatar: "",
    model: "ollama" + "__" + "llama3",
    modelTemperature: AssistantDefaultTemperature,
    promptSystem: "Tell true",
    webhookUrl: undefined,
    additionalData: undefined,
    snippet: undefined,
    isLocal: true,
  },
  {
    typeCommunication: ConfigurationTypeCommunicationDefault,
    assistantId: "5",
    title: "openai",
    description: "gpt-4o",
    emoji: Icon.QuestionMark,
    avatar: "",
    model: "openai" + "__" + "gpt-4o",
    modelTemperature: AssistantDefaultTemperature,
    promptSystem: "Tell true",
    webhookUrl: undefined,
    additionalData: undefined,
    snippet: undefined,
    isLocal: true,
  },
  {
    typeCommunication: ConfigurationTypeCommunicationDefault,
    assistantId: "6",
    title: "perplexity",
    description: "llama-3-sonar-small-32k-online",
    emoji: Icon.QuestionMark,
    avatar: "",
    model: "perplexity" + "__" + "llama-3-sonar-small-32k-online",
    modelTemperature: AssistantDefaultTemperature,
    promptSystem: "Tell true",
    webhookUrl: undefined,
    additionalData: undefined,
    snippet: undefined,
    isLocal: true,
  },
  {
    typeCommunication: ConfigurationTypeCommunicationDefault,
    assistantId: "0bb69d53-0389-49a4-a593-b75124fe25a7",
    title: "Default",
    description: "Chatty, easygoing digital sidekick",
    emoji: Icon.QuestionMark,
    avatar: "",
    model: ConfigurationModelDefault,
    modelTemperature: AssistantDefaultTemperature,
    promptSystem:
      "You are an AI assistant designed for ultra-concise, engaging conversations. Follow these rules: \n\r\n\r - Use the fewest words possible while maintaining clarity, impact and natural language \n\r - Keep a friendly, casual tone with occasional colloquialisms \n\r - Always wrap code with triple backticks and keywords with single backticks \n\r - Ask for clarification to avoid assumptions \n\r - Detect intentions and emotional states to tailor responses perfectly. \n\r - Focus solely on instructions and provide relevant, comprehensive responses \n\r - Never repeat info or mention limitations \n\r - Simplify complex tasks; provide the best output possible \n\r - Prioritize user needs; tailor responses to their context and goals \n\r - When asked for specific content, start response with requested info immediately \n\r - Continuously improve based on user feedback \n\r\n\r Let's keep it ultra-concise and engaging!",
    webhookUrl: undefined,
    additionalData: undefined,
    snippet: undefined,
    isLocal: true,
  },
];

export type AssistantHookType = HookType<ITalkAssistant> & {
  update: PromiseFunctionWithOneArgType<ITalkAssistant>;
  reload: PromiseFunctionNoArgType;
};
