/**
 * Unified alias map for timezone resolution.
 *
 * Maps user-friendly input strings to IANA timezone identifiers.
 * Keys are stored uppercase for case-insensitive matching.
 *
 * This map covers cases NOT already handled by the IANA display name fallback
 * in timezones.ts (which auto-resolves city names like "Tokyo", "London",
 * "Nairobi", etc. by matching against Intl.supportedValuesOf("timeZone")).
 *
 * Covers:
 * - Standard timezone abbreviations (EST, CET, JST, etc.)
 * - Airport/short codes (NYC, LAX, SFO, etc.)
 * - Cities that share an IANA identifier with a different city
 *   (e.g. Houston → America/Chicago, Hanoi → Asia/Bangkok)
 * - Country and region names
 * - Informal and alternate names (SF, LA, DC, etc.)
 */
export const TIMEZONE_ALIASES: ReadonlyMap<string, string> = new Map([
  // ─── North America abbreviations ───────────────────────────────────────────
  ["EST", "America/New_York"],
  ["EDT", "America/New_York"],
  ["ET", "America/New_York"],
  ["EASTERN", "America/New_York"],
  ["CST", "America/Chicago"],
  ["CDT", "America/Chicago"],
  ["CT", "America/Chicago"],
  ["CENTRAL", "America/Chicago"],
  ["MST", "America/Denver"],
  ["MDT", "America/Denver"],
  ["MT", "America/Denver"],
  ["MOUNTAIN", "America/Denver"],
  ["PST", "America/Los_Angeles"],
  ["PDT", "America/Los_Angeles"],
  ["PT", "America/Los_Angeles"],
  ["PACIFIC", "America/Los_Angeles"],
  ["AKST", "America/Anchorage"],
  ["AKDT", "America/Anchorage"],
  ["HST", "Pacific/Honolulu"],
  ["AST", "America/Halifax"],
  ["ADT", "America/Halifax"],
  ["NST", "America/St_Johns"],
  ["NDT", "America/St_Johns"],

  // ─── North America city/short codes ────────────────────────────────────────
  // Note: city names that match IANA display names (Toronto, Vancouver, Denver,
  // etc.) resolve automatically via the IANA fallback — only include those that
  // differ from their timezone's display name.
  ["NYC", "America/New_York"],
  ["NEW YORK", "America/New_York"],
  ["NEW YORK CITY", "America/New_York"],
  ["BOS", "America/New_York"],
  ["BOSTON", "America/New_York"],
  ["ATL", "America/New_York"],
  ["ATLANTA", "America/New_York"],
  ["MIA", "America/New_York"],
  ["MIAMI", "America/New_York"],
  ["PHL", "America/New_York"],
  ["PHILADELPHIA", "America/New_York"],
  ["PHILLY", "America/New_York"],
  ["CLT", "America/New_York"],
  ["CHARLOTTE", "America/New_York"],
  ["JAX", "America/New_York"],
  ["JACKSONVILLE", "America/New_York"],
  ["CMH", "America/New_York"],
  ["COLUMBUS", "America/New_York"],
  ["DC", "America/New_York"],
  ["WASHINGTON", "America/New_York"],
  ["WASHINGTON DC", "America/New_York"],
  ["DTW", "America/Detroit"],
  ["IND", "America/Indiana/Indianapolis"],
  ["LAX", "America/Los_Angeles"],
  ["LOS ANGELES", "America/Los_Angeles"],
  ["LA", "America/Los_Angeles"],
  ["SFO", "America/Los_Angeles"],
  ["SAN FRANCISCO", "America/Los_Angeles"],
  ["SF", "America/Los_Angeles"],
  ["SEA", "America/Los_Angeles"],
  ["SEATTLE", "America/Los_Angeles"],
  ["SAN", "America/Los_Angeles"],
  ["SAN DIEGO", "America/Los_Angeles"],
  ["SJC", "America/Los_Angeles"],
  ["SAN JOSE", "America/Los_Angeles"],
  ["PDX", "America/Los_Angeles"],
  ["PORTLAND", "America/Los_Angeles"],
  ["LAS", "America/Los_Angeles"],
  ["LAS VEGAS", "America/Los_Angeles"],
  ["ORD", "America/Chicago"],
  ["CHI", "America/Chicago"],
  ["DFW", "America/Chicago"],
  ["DALLAS", "America/Chicago"],
  ["ATX", "America/Chicago"],
  ["AUS", "America/Chicago"],
  ["AUSTIN", "America/Chicago"],
  ["HOU", "America/Chicago"],
  ["HOUSTON", "America/Chicago"],
  ["SAT", "America/Chicago"],
  ["SAN ANTONIO", "America/Chicago"],
  ["MSP", "America/Chicago"],
  ["MINNEAPOLIS", "America/Chicago"],
  ["BNA", "America/Chicago"],
  ["NASHVILLE", "America/Chicago"],
  ["OKC", "America/Chicago"],
  ["OKLAHOMA CITY", "America/Chicago"],
  ["FORT WORTH", "America/Chicago"],
  ["DEN", "America/Denver"],
  ["SLC", "America/Denver"],
  ["SALT LAKE CITY", "America/Denver"],
  ["PHX", "America/Phoenix"],
  ["ARIZONA", "America/Phoenix"],
  ["YYZ", "America/Toronto"],
  ["YUL", "America/Montreal"],
  ["MONTREAL", "America/Montreal"],
  ["YVR", "America/Vancouver"],
  ["YYC", "America/Edmonton"],
  ["CALGARY", "America/Edmonton"],
  ["YEG", "America/Edmonton"],
  ["YYJ", "America/Vancouver"],
  ["VICTORIA", "America/Vancouver"],
  ["MEX", "America/Mexico_City"],
  ["MEXICO", "America/Mexico_City"],
  ["HAV", "America/Havana"],
  ["CUBA", "America/Havana"],

  // ─── Europe abbreviations ───────────────────────────────────────────────────
  ["GMT", "Europe/London"],
  ["UTC", "Etc/UTC"],
  ["BST", "Europe/London"],
  ["WET", "Europe/Lisbon"],
  ["WEST", "Europe/Lisbon"],
  ["CET", "Europe/Paris"],
  ["CEST", "Europe/Paris"],
  ["EET", "Europe/Helsinki"],
  ["EEST", "Europe/Helsinki"],
  ["MSK", "Europe/Moscow"],
  ["IST-IE", "Europe/Dublin"],

  // ─── Europe city/short codes ────────────────────────────────────────────────
  ["LHR", "Europe/London"],
  ["LGW", "Europe/London"],
  ["UK", "Europe/London"],
  ["ENGLAND", "Europe/London"],
  ["BHX", "Europe/London"],
  ["BIRMINGHAM", "Europe/London"],
  ["MAN", "Europe/London"],
  ["MANCHESTER", "Europe/London"],
  ["CDG", "Europe/Paris"],
  ["FRANCE", "Europe/Paris"],
  ["FRA", "Europe/Berlin"],
  ["GERMANY", "Europe/Berlin"],
  ["HAM", "Europe/Berlin"],
  ["HAMBURG", "Europe/Berlin"],
  ["MUC", "Europe/Berlin"],
  ["MUNICH", "Europe/Berlin"],
  ["AMS", "Europe/Amsterdam"],
  ["NETHERLANDS", "Europe/Amsterdam"],
  ["MAD", "Europe/Madrid"],
  ["SPAIN", "Europe/Madrid"],
  ["BCN", "Europe/Madrid"],
  ["BARCELONA", "Europe/Madrid"],
  ["AGP", "Europe/Madrid"],
  ["MALAGA", "Europe/Madrid"],
  ["VLC", "Europe/Madrid"],
  ["VALENCIA", "Europe/Madrid"],
  ["SEVILLA", "Europe/Madrid"],
  ["SEVILLE", "Europe/Madrid"],
  ["FCO", "Europe/Rome"],
  ["ITALY", "Europe/Rome"],
  ["MXP", "Europe/Rome"],
  ["MILAN", "Europe/Rome"],
  ["ZRH", "Europe/Zurich"],
  ["SWITZERLAND", "Europe/Zurich"],
  ["GVA", "Europe/Zurich"],
  ["GENEVA", "Europe/Zurich"],
  ["BERN", "Europe/Zurich"],
  ["VIE", "Europe/Vienna"],
  ["AUSTRIA", "Europe/Vienna"],
  ["ARN", "Europe/Stockholm"],
  ["SWEDEN", "Europe/Stockholm"],
  ["OSL", "Europe/Oslo"],
  ["NORWAY", "Europe/Oslo"],
  ["CPH", "Europe/Copenhagen"],
  ["DENMARK", "Europe/Copenhagen"],
  ["HEL", "Europe/Helsinki"],
  ["FINLAND", "Europe/Helsinki"],
  ["WAW", "Europe/Warsaw"],
  ["POLAND", "Europe/Warsaw"],
  ["PRG", "Europe/Prague"],
  ["BUD", "Europe/Budapest"],
  ["ATH", "Europe/Athens"],
  ["GREECE", "Europe/Athens"],
  ["LIS", "Europe/Lisbon"],
  ["PORTUGAL", "Europe/Lisbon"],
  ["BRU", "Europe/Brussels"],
  ["BELGIUM", "Europe/Brussels"],
  ["SVO", "Europe/Moscow"],
  ["RUSSIA", "Europe/Moscow"],
  ["LED", "Europe/Moscow"],
  ["SAINT PETERSBURG", "Europe/Moscow"],
  ["ST PETERSBURG", "Europe/Moscow"],
  ["IST-EU", "Europe/Istanbul"],
  ["TURKEY", "Europe/Istanbul"],
  ["IRELAND", "Europe/Dublin"],
  ["KBP", "Europe/Kyiv"],
  ["KIEV", "Europe/Kyiv"],
  ["UKRAINE", "Europe/Kyiv"],

  // ─── Africa abbreviations ───────────────────────────────────────────────────
  ["EAT", "Africa/Nairobi"],
  ["SAST", "Africa/Johannesburg"],
  ["CAT", "Africa/Harare"],
  ["WAT", "Africa/Lagos"],

  // ─── Africa city/short codes ────────────────────────────────────────────────
  ["JNB", "Africa/Johannesburg"],
  ["SOUTH AFRICA", "Africa/Johannesburg"],
  ["CPT", "Africa/Johannesburg"],
  ["CAPE TOWN", "Africa/Johannesburg"],
  ["DUR", "Africa/Johannesburg"],
  ["DURBAN", "Africa/Johannesburg"],
  ["NBO", "Africa/Nairobi"],
  ["KENYA", "Africa/Nairobi"],
  ["MBA", "Africa/Nairobi"],
  ["MOMBASA", "Africa/Nairobi"],
  ["CAI", "Africa/Cairo"],
  ["EGYPT", "Africa/Cairo"],
  ["LOS", "Africa/Lagos"],
  ["NIGERIA", "Africa/Lagos"],
  ["ACC", "Africa/Accra"],
  ["GHANA", "Africa/Accra"],
  ["CMN", "Africa/Casablanca"],
  ["MOROCCO", "Africa/Casablanca"],
  ["ADD", "Africa/Addis_Ababa"],
  ["ADDIS ABABA", "Africa/Addis_Ababa"],
  ["ETHIOPIA", "Africa/Addis_Ababa"],
  ["DAR ES SALAAM", "Africa/Dar_es_Salaam"],
  ["TANZANIA", "Africa/Dar_es_Salaam"],
  ["ALG", "Africa/Algiers"],
  ["ALGERIA", "Africa/Algiers"],
  ["TIP", "Africa/Tripoli"],
  ["LIBYA", "Africa/Tripoli"],
  ["KRT", "Africa/Khartoum"],
  ["SUDAN", "Africa/Khartoum"],
  ["ABJ", "Africa/Abidjan"],
  ["IVORY COAST", "Africa/Abidjan"],
  ["DKR", "Africa/Dakar"],
  ["SENEGAL", "Africa/Dakar"],
  ["UGANDA", "Africa/Kampala"],
  ["ZIMBABWE", "Africa/Harare"],
  ["ZAMBIA", "Africa/Lusaka"],
  ["TUNISIA", "Africa/Tunis"],

  // ─── Asia abbreviations ─────────────────────────────────────────────────────
  ["IST", "Asia/Kolkata"],
  ["INDIA", "Asia/Kolkata"],
  ["JST", "Asia/Tokyo"],
  ["KST", "Asia/Seoul"],
  ["CST-CN", "Asia/Shanghai"],
  ["HKT", "Asia/Hong_Kong"],
  ["SGT", "Asia/Singapore"],
  ["PHT", "Asia/Manila"],
  ["ICT", "Asia/Bangkok"],
  ["WIB", "Asia/Jakarta"],
  ["GST", "Asia/Dubai"],
  ["PKT", "Asia/Karachi"],
  ["BDT", "Asia/Dhaka"],
  ["NPT", "Asia/Kathmandu"],
  ["MMT", "Asia/Yangon"],

  // ─── Asia city/short codes ──────────────────────────────────────────────────
  ["NRT", "Asia/Tokyo"],
  ["HND", "Asia/Tokyo"],
  ["JAPAN", "Asia/Tokyo"],
  ["OSAKA", "Asia/Tokyo"],
  ["ICN", "Asia/Seoul"],
  ["KOREA", "Asia/Seoul"],
  ["PVG", "Asia/Shanghai"],
  ["PEK", "Asia/Shanghai"],
  ["BEIJING", "Asia/Shanghai"],
  ["CHINA", "Asia/Shanghai"],
  ["HKG", "Asia/Hong_Kong"],
  ["HONG KONG", "Asia/Hong_Kong"],
  ["SIN", "Asia/Singapore"],
  ["BOM", "Asia/Kolkata"],
  ["MUMBAI", "Asia/Kolkata"],
  ["DEL", "Asia/Kolkata"],
  ["DELHI", "Asia/Kolkata"],
  ["NEW DELHI", "Asia/Kolkata"],
  ["BLR", "Asia/Kolkata"],
  ["BANGALORE", "Asia/Kolkata"],
  ["MAA", "Asia/Kolkata"],
  ["CHENNAI", "Asia/Kolkata"],
  ["MADRAS", "Asia/Kolkata"],
  ["HYD", "Asia/Kolkata"],
  ["HYDERABAD", "Asia/Kolkata"],
  ["COK", "Asia/Kolkata"],
  ["MNL", "Asia/Manila"],
  ["PHILIPPINES", "Asia/Manila"],
  ["BKK", "Asia/Bangkok"],
  ["THAILAND", "Asia/Bangkok"],
  ["HAN", "Asia/Bangkok"],
  ["HANOI", "Asia/Bangkok"],
  ["CGK", "Asia/Jakarta"],
  ["INDONESIA", "Asia/Jakarta"],
  ["KUL", "Asia/Kuala_Lumpur"],
  ["MALAYSIA", "Asia/Kuala_Lumpur"],
  ["DXB", "Asia/Dubai"],
  ["UAE", "Asia/Dubai"],
  ["AUH", "Asia/Dubai"],
  ["ABU DHABI", "Asia/Dubai"],
  ["DOH", "Asia/Qatar"],
  ["DOHA", "Asia/Qatar"],
  ["QATAR", "Asia/Qatar"],
  ["RUH", "Asia/Riyadh"],
  ["SAUDI ARABIA", "Asia/Riyadh"],
  ["JED", "Asia/Riyadh"],
  ["JEDDAH", "Asia/Riyadh"],
  ["TLV", "Asia/Jerusalem"],
  ["TEL AVIV", "Asia/Jerusalem"],
  ["ISRAEL", "Asia/Jerusalem"],
  ["KHI", "Asia/Karachi"],
  ["PAKISTAN", "Asia/Karachi"],
  ["ISB", "Asia/Karachi"],
  ["ISLAMABAD", "Asia/Karachi"],
  ["LHE", "Asia/Karachi"],
  ["LAHORE", "Asia/Karachi"],
  ["DAC", "Asia/Dhaka"],
  ["BANGLADESH", "Asia/Dhaka"],
  ["KTM", "Asia/Kathmandu"],
  ["NEPAL", "Asia/Kathmandu"],
  ["CMB", "Asia/Colombo"],
  ["SRI LANKA", "Asia/Colombo"],
  ["RGN", "Asia/Yangon"],
  ["MYANMAR", "Asia/Yangon"],
  ["SGN", "Asia/Ho_Chi_Minh"],
  ["SAIGON", "Asia/Ho_Chi_Minh"],
  ["VIETNAM", "Asia/Ho_Chi_Minh"],
  ["PNH", "Asia/Phnom_Penh"],
  ["CAMBODIA", "Asia/Phnom_Penh"],
  ["VTE", "Asia/Vientiane"],
  ["LAOS", "Asia/Vientiane"],

  // ─── Oceania abbreviations ───────────────────────────────────────────────────
  ["AEST", "Australia/Sydney"],
  ["AEDT", "Australia/Sydney"],
  ["ACST", "Australia/Darwin"],
  ["ACDT", "Australia/Adelaide"],
  ["AWST", "Australia/Perth"],
  ["NZST", "Pacific/Auckland"],
  ["NZDT", "Pacific/Auckland"],

  // ─── Oceania city/short codes ────────────────────────────────────────────────
  ["SYD", "Australia/Sydney"],
  ["AUSTRALIA", "Australia/Sydney"],
  ["CBR", "Australia/Sydney"],
  ["CANBERRA", "Australia/Sydney"],
  ["MEL", "Australia/Melbourne"],
  ["BNE", "Australia/Brisbane"],
  ["PER", "Australia/Perth"],
  ["ADL", "Australia/Adelaide"],
  ["AKL", "Pacific/Auckland"],
  ["NEW ZEALAND", "Pacific/Auckland"],
  ["NZ", "Pacific/Auckland"],
  ["WLG", "Pacific/Auckland"],
  ["WELLINGTON", "Pacific/Auckland"],
  ["CHC", "Pacific/Auckland"],
  ["CHRISTCHURCH", "Pacific/Auckland"],
  ["FIJI", "Pacific/Fiji"],
  ["HAWAII", "Pacific/Honolulu"],

  // ─── South America city/short codes ─────────────────────────────────────────
  ["GRU", "America/Sao_Paulo"],
  ["SAO PAULO", "America/Sao_Paulo"],
  ["BRAZIL", "America/Sao_Paulo"],
  ["GIG", "America/Sao_Paulo"],
  ["RIO", "America/Sao_Paulo"],
  ["RIO DE JANEIRO", "America/Sao_Paulo"],
  ["EZE", "America/Argentina/Buenos_Aires"],
  ["BUENOS AIRES", "America/Argentina/Buenos_Aires"],
  ["ARGENTINA", "America/Argentina/Buenos_Aires"],
  ["SCL", "America/Santiago"],
  ["CHILE", "America/Santiago"],
  ["BOG", "America/Bogota"],
  ["COLOMBIA", "America/Bogota"],
  ["LIM", "America/Lima"],
  ["PERU", "America/Lima"],
  ["UIO", "America/Guayaquil"],
  ["QUITO", "America/Guayaquil"],
  ["ECUADOR", "America/Guayaquil"],
  ["CCS", "America/Caracas"],
  ["CARACAS", "America/Caracas"],
  ["VENEZUELA", "America/Caracas"],
  ["MVD", "America/Montevideo"],
  ["URUGUAY", "America/Montevideo"],
]);
