export const NORTH_AMERICA = [
  // Top 25 Cities by Population
  { displayName: "Mexico City", timezone: "America/Mexico_City" },
  { displayName: "New York City", timezone: "America/New_York" },
  { displayName: "Los Angeles", timezone: "America/Los_Angeles" },
  { displayName: "Toronto", timezone: "America/Toronto" },
  { displayName: "Chicago", timezone: "America/Chicago" },
  { displayName: "Houston", timezone: "America/Chicago" },
  { displayName: "Havana", timezone: "America/Havana" },
  { displayName: "Montreal", timezone: "America/Montreal" },
  { displayName: "Philadelphia", timezone: "America/New_York" },
  { displayName: "Phoenix", timezone: "America/Phoenix" },
  { displayName: "San Antonio", timezone: "America/Chicago" },
  { displayName: "San Diego", timezone: "America/Los_Angeles" },
  { displayName: "Dallas", timezone: "America/Chicago" },
  { displayName: "San Jose", timezone: "America/Los_Angeles" },
  { displayName: "Calgary", timezone: "America/Edmonton" },
  { displayName: "Jacksonville", timezone: "America/New_York" },
  { displayName: "Austin", timezone: "America/Chicago" },
  { displayName: "San Francisco", timezone: "America/Los_Angeles" },
  { displayName: "Columbus", timezone: "America/New_York" },
  { displayName: "Fort Worth", timezone: "America/Chicago" },
  { displayName: "Indianapolis", timezone: "America/Indiana/Indianapolis" },
  { displayName: "Charlotte", timezone: "America/New_York" },
  { displayName: "Seattle", timezone: "America/Los_Angeles" },
  { displayName: "Denver", timezone: "America/Denver" },
  { displayName: "Washington DC", timezone: "America/New_York" },

  // US State Capitals
  { displayName: "Montgomery", timezone: "America/Chicago" },
  { displayName: "Juneau", timezone: "America/Juneau" },
  { displayName: "Phoenix", timezone: "America/Phoenix" },
  { displayName: "Little Rock", timezone: "America/Chicago" },
  { displayName: "Sacramento", timezone: "America/Los_Angeles" },
  { displayName: "Denver", timezone: "America/Denver" },
  { displayName: "Hartford", timezone: "America/New_York" },
  { displayName: "Dover", timezone: "America/New_York" },
  { displayName: "Tallahassee", timezone: "America/New_York" },
  { displayName: "Atlanta", timezone: "America/New_York" },
  { displayName: "Honolulu", timezone: "Pacific/Honolulu" },
  { displayName: "Boise", timezone: "America/Boise" },
  { displayName: "Springfield", timezone: "America/Chicago" },
  { displayName: "Indianapolis", timezone: "America/Indiana/Indianapolis" },
  { displayName: "Des Moines", timezone: "America/Chicago" },
  { displayName: "Topeka", timezone: "America/Chicago" },
  { displayName: "Frankfort", timezone: "America/New_York" },
  { displayName: "Baton Rouge", timezone: "America/Chicago" },
  { displayName: "Augusta", timezone: "America/New_York" },
  { displayName: "Annapolis", timezone: "America/New_York" },
  { displayName: "Boston", timezone: "America/New_York" },
  { displayName: "Lansing", timezone: "America/Detroit" },
  { displayName: "Saint Paul", timezone: "America/Chicago" },
  { displayName: "Jackson", timezone: "America/Chicago" },
  { displayName: "Jefferson City", timezone: "America/Chicago" },
  { displayName: "Helena", timezone: "America/Denver" },
  { displayName: "Lincoln", timezone: "America/Chicago" },
  { displayName: "Carson City", timezone: "America/Los_Angeles" },
  { displayName: "Concord", timezone: "America/New_York" },
  { displayName: "Trenton", timezone: "America/New_York" },
  { displayName: "Santa Fe", timezone: "America/Denver" },
  { displayName: "Albany", timezone: "America/New_York" },
  { displayName: "Raleigh", timezone: "America/New_York" },
  { displayName: "Bismarck", timezone: "America/Chicago" },
  { displayName: "Columbus", timezone: "America/New_York" },
  { displayName: "Oklahoma City", timezone: "America/Chicago" },
  { displayName: "Salem", timezone: "America/Los_Angeles" },
  { displayName: "Harrisburg", timezone: "America/New_York" },
  { displayName: "Providence", timezone: "America/New_York" },
  { displayName: "Columbia", timezone: "America/New_York" },
  { displayName: "Pierre", timezone: "America/Chicago" },
  { displayName: "Nashville", timezone: "America/Chicago" },
  { displayName: "Austin", timezone: "America/Chicago" },
  { displayName: "Salt Lake City", timezone: "America/Denver" },
  { displayName: "Montpelier", timezone: "America/New_York" },
  { displayName: "Richmond", timezone: "America/New_York" },
  { displayName: "Olympia", timezone: "America/Los_Angeles" },
  { displayName: "Charleston", timezone: "America/New_York" },
  { displayName: "Madison", timezone: "America/Chicago" },
  { displayName: "Cheyenne", timezone: "America/Denver" },

  // Canadian Provincial/Territorial Capitals
  { displayName: "Edmonton", timezone: "America/Edmonton" },
  { displayName: "Victoria", timezone: "America/Vancouver" },
  { displayName: "Winnipeg", timezone: "America/Winnipeg" },
  { displayName: "Fredericton", timezone: "America/Halifax" },
  { displayName: "St. John's", timezone: "America/St_Johns" },
  { displayName: "Halifax", timezone: "America/Halifax" },
  { displayName: "Toronto", timezone: "America/Toronto" },
  { displayName: "Charlottetown", timezone: "America/Halifax" },
  { displayName: "Quebec City", timezone: "America/Toronto" },
  { displayName: "Regina", timezone: "America/Regina" },
  { displayName: "Yellowknife", timezone: "America/Yellowknife" },
  { displayName: "Iqaluit", timezone: "America/Iqaluit" },
  { displayName: "Whitehorse", timezone: "America/Whitehorse" },
];
