export const SOUTH_AMERICA = [
  // Top 25 Cities
  { displayName: "São Paulo", timezone: "America/Sao_Paulo" },
  { displayName: "Lima", timezone: "America/Lima" },
  { displayName: "Bogotá", timezone: "America/Bogota" },
  { displayName: "Rio de Janeiro", timezone: "America/Sao_Paulo" },
  { displayName: "Santiago", timezone: "America/Santiago" },
  { displayName: "Caracas", timezone: "America/Caracas" },
  { displayName: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires" },
  { displayName: "Salvador", timezone: "America/Bahia" },
  { displayName: "Brasília", timezone: "America/Sao_Paulo" },
  { displayName: "Fortaleza", timezone: "America/Fortaleza" },
  { displayName: "Guayaquil", timezone: "America/Guayaquil" },
  { displayName: "Quito", timezone: "America/Guayaquil" },
  { displayName: "Belo Horizonte", timezone: "America/Sao_Paulo" },
  { displayName: "Medellín", timezone: "America/Bogota" },
  { displayName: "Cali", timezone: "America/Bogota" },
  { displayName: "Manaus", timezone: "America/Manaus" },
  { displayName: "Curitiba", timezone: "America/Sao_Paulo" },
  { displayName: "Recife", timezone: "America/Recife" },
  { displayName: "Porto Alegre", timezone: "America/Sao_Paulo" },
  { displayName: "La Paz", timezone: "America/La_Paz" },
  { displayName: "Montevideo", timezone: "America/Montevideo" },
  { displayName: "Belém", timezone: "America/Belem" },
  { displayName: "Goiânia", timezone: "America/Sao_Paulo" },
  { displayName: "Guarulhos", timezone: "America/Sao_Paulo" },
  { displayName: "Barranquilla", timezone: "America/Bogota" },
];
