export const TIMEZONE_ALIASES = new Map([
  // North America Time Zones
  ["EST", "America/New_York"],
  ["EDT", "America/New_York"],
  ["CST", "America/Chicago"],
  ["CDT", "America/Chicago"],
  ["MST", "America/Denver"],
  ["MDT", "America/Denver"],
  ["PST", "America/Los_Angeles"],
  ["PDT", "America/Los_Angeles"],
  ["AKST", "America/Anchorage"],
  ["AKDT", "America/Anchorage"],
  ["HST", "Pacific/Honolulu"],
  ["AST", "America/Halifax"],
  ["ADT", "America/Halifax"],
  ["NDT", "America/St_Johns"],
  ["NST", "America/St_Johns"],

  // European Time Zones
  ["GMT", "Europe/London"],
  ["BST", "Europe/London"],
  ["CET", "Europe/Paris"],
  ["CEST", "Europe/Paris"],
  ["EET", "Europe/Kiev"],
  ["EEST", "Europe/Kiev"],
  ["WET", "Europe/Lisbon"],
  ["WEST", "Europe/Lisbon"],

  // Asian Time Zones
  ["IST", "Asia/Kolkata"],
  ["JST", "Asia/Tokyo"],
  ["CST", "Asia/Shanghai"],
  ["KST", "Asia/Seoul"],
  ["PHT", "Asia/Manila"],
  ["ICT", "Asia/Bangkok"],
  ["GST", "Asia/Dubai"],

  // Australian Time Zones
  ["AEST", "Australia/Sydney"],
  ["AEDT", "Australia/Sydney"],
  ["ACST", "Australia/Adelaide"],
  ["ACDT", "Australia/Adelaide"],
  ["AWST", "Australia/Perth"],

  // Common City Abbreviations
  ["NYC", "America/New_York"],
  ["LA", "America/Los_Angeles"],
  ["SF", "America/Los_Angeles"],
  ["CHI", "America/Chicago"],
  ["ATX", "America/Chicago"],
  ["DFW", "America/Chicago"],
  ["YYZ", "America/Toronto"],
  ["MEX", "America/Mexico_City"],
  ["BOG", "America/Bogota"],
  ["GRU", "America/Sao_Paulo"],
  ["LHR", "Europe/London"],
  ["CDG", "Europe/Paris"],
  ["FRA", "Europe/Berlin"],
  ["DXB", "Asia/Dubai"],
  ["HKG", "Asia/Hong_Kong"],
  ["SIN", "Asia/Singapore"],
  ["NRT", "Asia/Tokyo"],
  ["SYD", "Australia/Sydney"],
]);
