export const SupportedApplications = [
  {
    title: "System",
    source: "system",
    icon: "apps/system.png",
  },
  {
    title: "Raycast",
    source: "raycast",
    icon: "apps/raycast.png",
  },
  {
    title: "Adobe Photoshop",
    source: "adobe-photoshop",
    icon: "apps/adobe-photoshop.png",
  },
  {
    title: "Adobe Premiere Pro",
    source: "adobe-premiere-pro",
    icon: "apps/adobe-premiere-pro.png",
  },
  {
    title: "Chrome",
    source: "chrome",
    icon: "apps/chrome.png",
  },
  {
    title: "Discord",
    source: "discord",
    icon: "apps/discord.png",
  },
  {
    title: "Final Cut Pro",
    source: "final-cut-pro",
    icon: "apps/final-cut-pro.png",
  },
  {
    title: "Firefox",
    source: "firefox",
    icon: "apps/firefox.png",
  },
  {
    title: "Neovim",
    source: "neovim",
    icon: "apps/neovim.png",
  },
  {
    title: "Sublime Text",
    source: "sublime-text",
    icon: "apps/sublime-text.png",
  },
  {
    title: "tmux",
    source: "tmux",
    icon: "apps/tmux.png",
  },
  {
    title: "VSCode",
    source: "vscode",
    icon: "apps/vscode.png",
  },
];

export const SupportedLogos = [
  {
    title: "Default-1",
    source: "default-1",
    path: "apps/defaults/default-1.png",
  },
  {
    title: "Default-2",
    source: "default-2",
    path: "apps/defaults/default-2.png",
  },
  {
    title: "Default-3",
    source: "default-3",
    path: "apps/defaults/default-3.png",
  },
  {
    title: "Default-4",
    source: "default-4",
    path: "apps/defaults/default-4.png",
  },
  {
    title: "Default-5",
    source: "default-5",
    path: "apps/defaults/default-5.png",
  },
  {
    title: "Default-6",
    source: "default-6",
    path: "apps/defaults/default-6.png",
  },
];

export const ModifierKeys = ["hyper", "prefix", "leader", "cmd", "ctrl", "opt", "shift"];
export const Keys = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  ".",
  ",",
  ";",
  "=",
  "+",
  "-",
  "[",
  "]",
  "{",
  "}",
  "«",
  "»",
  "(",
  ")",
  "/",
  "\\",
  "'",
  "`",
  "^",
  "@",
  "$",
  "return",
  "delete",
  "tab",
  "arrowUp",
  "arrowDown",
  "arrowLeft",
  "arrowRight",
  "pageUp",
  "pageDown",
  "home",
  "end",
  "space",
  "escape",
  "enter",
  "backspace",
];
