export const operatorData = {
  operators: {
    TOP: {
      description: "Texture Operators - for image processing and manipulation",
      operators: [
        "Add",
        "Analyze",
        "Anti Alias",
        "Blob Track",
        "Bloom",
        "Blur",
        "Cache Select",
        "Cache",
        "Channel Mix",
        "CHOP to TOP",
        "Chroma Key",
        "Circle",
        "Composite",
        "Constant",
        "Convolve",
        "Corner Pin",
        "CPlusPlus",
        "Crop",
        "Cross",
        "Cube Map",
        "Depth",
        "Difference",
        "Direct Display Out",
        "DirectX In",
        "DirectX Out",
        "Displace",
        "Edge",
        "Emboss",
        "Feedback",
        "Fit",
        "Flip",
        "Function",
        "GLSL Multi",
        "GLSL",
        "HSV Adjust",
        "HSV to RGB",
        "Import Select",
        "In",
        "Inside",
        "Layout",
        "Lens Distort",
        "Level",
        "Limit",
        "Lookup",
        "Luma Blur",
        "Luma Level",
        "Math",
        "Matte",
        "Mirror",
        "Monochrome",
        "Movie File In",
        "Movie File Out",
        "MPCDI",
        "Multiply",
        "NDI In",
        "NDI Out",
        "Noise",
        "Normal Map",
        "Null",
        "OP Viewer",
        "OpenColorIO",
        "OpenVR",
        "Optical Flow",
        "Out",
        "Outside",
        "Over",
        "Pack",
        "Point File In",
        "Point Transform",
        "PreFilter Map",
        "Projection",
        "Ramp",
        "Rectangle",
        "Remap",
        "Render Pass",
        "Render Select",
        "Render",
        "Reorder",
        "Resolution",
        "RGB Key",
        "RGB to HSV",
        "Screen Grab",
        "Screen",
        "Script",
        "Select",
        "Shared Mem In",
        "Shared Mem Out",
        "Slope",
        "Spectrum",
        "SSAO",
        "Subtract",
        "SVG",
        "Switch",
        "Text",
        "Texture 3D",
        "Threshold",
        "Tile",
        "Time Machine",
        "Touch In",
        "Touch Out",
        "Transform",
        "Under",
        "Video Device In",
        "Video Device Out",
        "Video Stream In",
        "Video Stream Out",
        "Web Render",
      ],
    },
    CHOP: {
      description: "Channel Operators - for processing motion, audio, math, and data",
      sweet_16: [
        { name: "Constant", purpose: "Create new channels" },
        { name: "LFO", purpose: "Low Frequency Oscillator" },
        { name: "Noise", purpose: "Create semi-random patterns" },
        { name: "Select", purpose: "Grab a channel from any other CHOP" },
        { name: "Merge", purpose: "Merge channels from two or more CHOPs" },
        { name: "Math", purpose: "Add, multiply or scale channels" },
        { name: "Lag", purpose: "Smooth and delay a channel" },
        { name: "Speed", purpose: "Use speed to calculate distance" },
        { name: "Lookup", purpose: "Use one channel to get values from another CHOP" },
        { name: "Trail", purpose: "Watch a time-history of CHOP channels" },
        { name: "Limit", purpose: "Restrict channels to a range or certain step values" },
        { name: "Audio Device In", purpose: "Get audio from input device" },
        { name: "OSC In", purpose: "Open Sound Control, MIDI" },
        { name: "Panel", purpose: "Get state, u, v etc values from any panel gadget" },
        { name: "Timer", purpose: "Run timers, loops, delays and trigger events" },
      ],
    },
    SOP: {
      description: "Surface Operators - for 3D geometry manipulation",
      sweet_16: [
        { name: "Circle", purpose: "Circle, sphere, torus primitives" },
        { name: "Grid", purpose: "Grid, box, rectangle" },
        { name: "Merge", purpose: "Merge and delete" },
        { name: "Copy", purpose: "Copy or replicate" },
        { name: "Switch", purpose: "Switch or blend multi-inputs" },
        { name: "Texture", purpose: "Apply texture coordinated to points or vertices" },
        { name: "Noise", purpose: "Apply noise, twist and deform" },
        { name: "Transform", purpose: "Transform point positions" },
        { name: "DAT to", purpose: "DAT table to SOP points" },
        { name: "CHOP to", purpose: "CHOP channel samples to SOP points" },
        { name: "Line", purpose: "Trace a TOP image to polygons" },
        { name: "Clip", purpose: "Clip and carve" },
        { name: "Facet", purpose: "Facet, subdivide, convert" },
        { name: "Particle", purpose: "Particles" },
        { name: "Sweep", purpose: "Sweep, skin, rails" },
        { name: "Sort", purpose: "Sort and reorder" },
      ],
    },
    MAT: {
      description: "Material Operators - for applying shaders to 3D geometry",
      operators: [
        { name: "Phong", description: "Applies a phong shader with lighting options" },
        { name: "PBR", description: "Applies a PBR shader, works with Environment Light COMP" },
        { name: "Line", description: "Renders geometry edges as lines and points" },
        { name: "Constant", description: "Applies flat color without specular shading" },
        { name: "Depth", description: "Gets depth information for depth-pass render" },
        { name: "GLSL", description: "Applies custom GLSL pixel and vertex shaders" },
        { name: "Point Sprite", description: "Special material for Point Sprite geometry" },
      ],
    },
    COMP: {
      description: "Components - containers that can hold networks of other operators",
      types: {
        object_components: [
          "Ambient Light",
          "Blend",
          "Bone",
          "Camera",
          "Camera Blend",
          "Environment Light",
          "Nvidia Flow Emitter",
          "Geometry",
          "Handle",
          "Light",
          "Null",
          "Shared Mem In",
          "Shared Mem Out",
          "FBX",
          "USD",
        ],
        panel_components: [
          "Button",
          "Container",
          "Field",
          "List",
          "OP Viewer",
          "Parameter",
          "Select",
          "Slider",
          "Table",
          "Widget",
        ],
        misc_components: ["Base", "Engine", "Time", "Animation", "Replicator", "Window"],
      },
    },
  },
};
