import type {
  Card,
  Category,
  CreditAccount,
  Customer,
  Invoice,
  MercuryAccount,
  MercuryEvent,
  Organization,
  Recipient,
  Statement,
  TeamMember,
  Transaction,
  TreasuryResponse,
  WebhookEndpoint,
} from "./types";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function hoursAgo(n: number): string {
  const d = new Date();
  d.setHours(d.getHours() - n);
  return d.toISOString();
}

// ─── Accounts ──────────────────────────────────────────────────────────────

export const MOCK_ACCOUNTS: MercuryAccount[] = [
  {
    id: "acct-001",
    accountNumber: "1029384756",
    routingNumber: "084106768",
    name: "Primary Checking",
    status: "active",
    type: "mercury",
    kind: "checking",
    createdAt: "2023-06-15T00:00:00Z",
    availableBalance: 284_391.47,
    currentBalance: 291_141.47,
    legalBusinessName: "Archway Studios Inc.",
    dashboardLink: "https://app.mercury.com",
    nickname: "Operating Account",
    canReceiveTransactions: true,
  },
  {
    id: "acct-002",
    accountNumber: "1029384800",
    routingNumber: "084106768",
    name: "Savings Reserve",
    status: "active",
    type: "mercury",
    kind: "savings",
    createdAt: "2023-06-15T00:00:00Z",
    availableBalance: 1_150_000.0,
    currentBalance: 1_150_000.0,
    legalBusinessName: "Archway Studios Inc.",
    dashboardLink: "https://app.mercury.com",
    nickname: "Tax Reserve",
    canReceiveTransactions: true,
  },
  {
    id: "acct-003",
    accountNumber: "1029384912",
    routingNumber: "084106768",
    name: "Payroll",
    status: "active",
    type: "mercury",
    kind: "checking",
    createdAt: "2024-01-10T00:00:00Z",
    availableBalance: 67_520.0,
    currentBalance: 67_520.0,
    legalBusinessName: "Archway Studios Inc.",
    dashboardLink: "https://app.mercury.com",
    nickname: "Payroll Account",
    canReceiveTransactions: true,
  },
];

// ─── Transactions ──────────────────────────────────────────────────────────
// Mix of pending/sent/processing (show in "Active" filter) and completed/posted (show in "Completed")

export const MOCK_TRANSACTIONS: Transaction[] = [
  // ── Active (pending / sent / processing) ──
  {
    id: "txn-101",
    accountId: "acct-001",
    amount: -6_750.0,
    direction: "debit",
    bankDescription: "Wire transfer",
    counterpartyName: "Sarah Chen",
    createdAt: hoursAgo(1),
    estimatedDeliveryDate: daysAgo(-1),
    externalMemo: "Contractor — February",
    kind: "externalTransfer",
    paymentMethod: "domesticWire",
    status: "pending",
    note: "Senior designer — Feb retainer",
    mercuryCategory: "Contractors",
  },
  {
    id: "txn-102",
    accountId: "acct-001",
    amount: -1_200.0,
    direction: "debit",
    bankDescription: "ACH payment",
    counterpartyName: "Figma Inc.",
    createdAt: hoursAgo(3),
    estimatedDeliveryDate: daysAgo(-2),
    externalMemo: "Annual plan renewal",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "sent",
    note: "Design tools — annual",
    mercuryCategory: "Software & SaaS",
  },
  {
    id: "txn-103",
    accountId: "acct-001",
    amount: 35_000.0,
    direction: "credit",
    bankDescription: "Wire deposit",
    counterpartyName: "Lumen Ventures LLC",
    createdAt: hoursAgo(2),
    externalMemo: "Consulting — February 2026",
    kind: "externalTransfer",
    paymentMethod: "domesticWire",
    status: "processing",
    note: "Strategy consulting retainer",
    mercuryCategory: "Revenue",
  },
  {
    id: "txn-104",
    accountId: "acct-001",
    amount: -349.0,
    direction: "debit",
    bankDescription: "ACH payment",
    counterpartyName: "Linear",
    createdAt: hoursAgo(5),
    estimatedDeliveryDate: daysAgo(-1),
    externalMemo: "Monthly plan — Feb",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "pending",
    note: "Issue tracking — monthly",
    mercuryCategory: "Software & SaaS",
  },
  {
    id: "txn-105",
    accountId: "acct-003",
    amount: -32_500.0,
    direction: "debit",
    bankDescription: "ACH payroll",
    counterpartyName: "Gusto Payroll",
    createdAt: hoursAgo(4),
    estimatedDeliveryDate: daysAgo(-1),
    externalMemo: "Payroll Feb 14",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "sent",
    note: "Bi-weekly payroll",
    mercuryCategory: "Payroll",
  },
  {
    id: "txn-106",
    accountId: "acct-001",
    amount: -2_400.0,
    direction: "debit",
    bankDescription: "ACH payment",
    counterpartyName: "WeWork",
    createdAt: hoursAgo(6),
    estimatedDeliveryDate: daysAgo(-2),
    externalMemo: "Office space — February",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "processing",
    note: "Co-working space",
    mercuryCategory: "Office & Supplies",
  },
  // ── Completed / Posted ──
  {
    id: "txn-001",
    accountId: "acct-001",
    amount: -4_250.0,
    direction: "debit",
    bankDescription: "Wire transfer",
    counterpartyName: "AWS Cloud Services",
    createdAt: daysAgo(0),
    postedAt: daysAgo(0),
    externalMemo: "February infrastructure",
    kind: "externalTransfer",
    paymentMethod: "domesticWire",
    status: "completed",
    note: "Monthly cloud hosting",
    mercuryCategory: "Software & SaaS",
  },
  {
    id: "txn-002",
    accountId: "acct-001",
    amount: 18_500.0,
    direction: "credit",
    bankDescription: "ACH deposit",
    counterpartyName: "Meridian Health Group",
    createdAt: daysAgo(0),
    postedAt: daysAgo(0),
    externalMemo: "INV-2026-0102",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "posted",
    note: "Client payment — Q1 retainer",
    mercuryCategory: "Revenue",
  },
  {
    id: "txn-003",
    accountId: "acct-001",
    amount: -1_200.0,
    direction: "debit",
    bankDescription: "ACH payment",
    counterpartyName: "Figma Inc.",
    createdAt: daysAgo(1),
    postedAt: daysAgo(1),
    externalMemo: "Annual plan",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "completed",
    note: "Design tools — annual",
    mercuryCategory: "Software & SaaS",
  },
  {
    id: "txn-004",
    accountId: "acct-001",
    amount: 42_000.0,
    direction: "credit",
    bankDescription: "Wire deposit",
    counterpartyName: "Lumen Ventures LLC",
    createdAt: daysAgo(1),
    postedAt: daysAgo(1),
    externalMemo: "Consulting Jan 2026",
    kind: "externalTransfer",
    paymentMethod: "domesticWire",
    status: "posted",
    note: "Strategy consulting",
    mercuryCategory: "Revenue",
  },
  {
    id: "txn-005",
    accountId: "acct-001",
    amount: -850.0,
    direction: "debit",
    bankDescription: "ACH payment",
    counterpartyName: "Notion Labs Inc.",
    createdAt: daysAgo(2),
    postedAt: daysAgo(2),
    externalMemo: "Team plan",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "completed",
    note: "Project management — monthly",
    mercuryCategory: "Software & SaaS",
  },
  {
    id: "txn-006",
    accountId: "acct-001",
    amount: -15_000.0,
    direction: "debit",
    bankDescription: "Wire transfer",
    counterpartyName: "Sarah Chen",
    createdAt: daysAgo(2),
    postedAt: daysAgo(2),
    externalMemo: "Contractor — January",
    kind: "externalTransfer",
    paymentMethod: "domesticWire",
    status: "completed",
    note: "Senior designer contract",
    mercuryCategory: "Contractors",
  },
  {
    id: "txn-007",
    accountId: "acct-001",
    amount: 8_750.0,
    direction: "credit",
    bankDescription: "ACH deposit",
    counterpartyName: "Oakmont Partners",
    createdAt: daysAgo(3),
    postedAt: daysAgo(3),
    externalMemo: "INV-2026-0103",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "posted",
    note: "Brand design project",
    mercuryCategory: "Revenue",
  },
  {
    id: "txn-008",
    accountId: "acct-001",
    amount: -349.0,
    direction: "debit",
    bankDescription: "ACH payment",
    counterpartyName: "Linear",
    createdAt: daysAgo(3),
    postedAt: daysAgo(3),
    externalMemo: "Monthly plan",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "completed",
    note: "Issue tracking",
    mercuryCategory: "Software & SaaS",
  },
  {
    id: "txn-009",
    accountId: "acct-003",
    amount: -32_500.0,
    direction: "debit",
    bankDescription: "ACH payroll",
    counterpartyName: "Gusto Payroll",
    createdAt: daysAgo(4),
    postedAt: daysAgo(4),
    externalMemo: "Payroll Jan 31",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "completed",
    note: "Bi-weekly payroll",
    mercuryCategory: "Payroll",
  },
  {
    id: "txn-010",
    accountId: "acct-001",
    amount: 125_000.0,
    direction: "credit",
    bankDescription: "Wire deposit",
    counterpartyName: "Redwood Capital",
    createdAt: daysAgo(5),
    postedAt: daysAgo(5),
    externalMemo: "Series A tranche 2",
    kind: "externalTransfer",
    paymentMethod: "domesticWire",
    status: "posted",
    note: "Investment funding",
    mercuryCategory: "Revenue",
  },
  {
    id: "txn-011",
    accountId: "acct-002",
    amount: 150_000.0,
    direction: "credit",
    bankDescription: "Internal transfer",
    counterpartyName: "Archway Studios Inc.",
    createdAt: daysAgo(6),
    postedAt: daysAgo(6),
    externalMemo: "Transfer to savings",
    kind: "internalTransfer",
    paymentMethod: "ach",
    status: "completed",
    note: "Monthly savings allocation",
    mercuryCategory: "Transfers",
  },
  {
    id: "txn-012",
    accountId: "acct-001",
    amount: -5_800.0,
    direction: "debit",
    bankDescription: "ACH payment",
    counterpartyName: "Carta Inc.",
    createdAt: daysAgo(7),
    postedAt: daysAgo(7),
    externalMemo: "Cap table management",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "completed",
    note: "Equity management — annual",
    mercuryCategory: "Legal & Professional",
  },
  {
    id: "txn-013",
    accountId: "acct-001",
    amount: -475.0,
    direction: "debit",
    bankDescription: "ACH payment",
    counterpartyName: "Vercel Inc.",
    createdAt: daysAgo(8),
    postedAt: daysAgo(8),
    externalMemo: "Pro plan — Jan",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "completed",
    note: "Hosting — monthly",
    mercuryCategory: "Software & SaaS",
  },
  {
    id: "txn-014",
    accountId: "acct-001",
    amount: 62_500.0,
    direction: "credit",
    bankDescription: "Wire deposit",
    counterpartyName: "Meridian Health Group",
    createdAt: daysAgo(10),
    postedAt: daysAgo(10),
    externalMemo: "INV-2026-0098",
    kind: "externalTransfer",
    paymentMethod: "domesticWire",
    status: "posted",
    note: "Platform build — milestone 2",
    mercuryCategory: "Revenue",
  },
  {
    id: "txn-015",
    accountId: "acct-003",
    amount: -32_500.0,
    direction: "debit",
    bankDescription: "ACH payroll",
    counterpartyName: "Gusto Payroll",
    createdAt: daysAgo(18),
    postedAt: daysAgo(18),
    externalMemo: "Payroll Jan 17",
    kind: "externalTransfer",
    paymentMethod: "ach",
    status: "completed",
    note: "Bi-weekly payroll",
    mercuryCategory: "Payroll",
  },
];

// ─── Cards ─────────────────────────────────────────────────────────────────

export const MOCK_CARDS: Card[] = [
  {
    cardId: "card-001",
    nameOnCard: "Alex Rivera",
    lastFourDigits: "4821",
    network: "visa",
    status: "active",
    createdAt: "2024-03-01T00:00:00Z",
    physicalCardStatus: "active",
  },
  {
    cardId: "card-002",
    nameOnCard: "Jordan Park",
    lastFourDigits: "7293",
    network: "visa",
    status: "active",
    createdAt: "2024-05-15T00:00:00Z",
    physicalCardStatus: "active",
  },
  {
    cardId: "card-003",
    nameOnCard: "Sam Novak",
    lastFourDigits: "1058",
    network: "visa",
    status: "frozen",
    createdAt: "2024-08-20T00:00:00Z",
    physicalCardStatus: "paused",
  },
  {
    cardId: "card-004",
    nameOnCard: "Taylor Brooks",
    lastFourDigits: "6340",
    network: "visa",
    status: "active",
    createdAt: "2025-01-12T00:00:00Z",
    physicalCardStatus: null,
  },
];

// ─── Recipients ────────────────────────────────────────────────────────────

export const MOCK_RECIPIENTS: Recipient[] = [
  {
    id: "rcp-001",
    name: "AWS Cloud Services",
    nickname: "AWS",
    status: "active",
    emails: ["billing@aws.amazon.com"],
    dateLastPaid: daysAgo(0),
    defaultPaymentMethod: "domesticWire",
    electronicRoutingInfo: null,
    domesticWireRoutingInfo: {
      accountNumber: "****6789",
      routingNumber: "021000021",
      bankName: "JPMorgan Chase",
      address: null,
    },
    internationalWireRoutingInfo: null,
    address: null,
  },
  {
    id: "rcp-002",
    name: "Sarah Chen",
    nickname: "Sarah — Design",
    status: "active",
    emails: ["sarah@sarahchen.design"],
    dateLastPaid: daysAgo(0),
    defaultPaymentMethod: "ach",
    electronicRoutingInfo: {
      accountNumber: "****3421",
      routingNumber: "021000089",
      bankName: "Bank of America",
      electronicAccountType: "personalChecking",
      address: null,
    },
    domesticWireRoutingInfo: null,
    internationalWireRoutingInfo: null,
    address: null,
  },
  {
    id: "rcp-003",
    name: "Figma Inc.",
    nickname: null,
    status: "active",
    emails: ["invoices@figma.com"],
    dateLastPaid: daysAgo(1),
    defaultPaymentMethod: "ach",
    electronicRoutingInfo: {
      accountNumber: "****8812",
      routingNumber: "121000358",
      bankName: "Silicon Valley Bank",
      electronicAccountType: "businessChecking",
      address: null,
    },
    domesticWireRoutingInfo: null,
    internationalWireRoutingInfo: null,
    address: null,
  },
  {
    id: "rcp-004",
    name: "Gusto Payroll",
    nickname: "Payroll",
    status: "active",
    emails: ["payments@gusto.com"],
    dateLastPaid: daysAgo(4),
    defaultPaymentMethod: "ach",
    electronicRoutingInfo: {
      accountNumber: "****5590",
      routingNumber: "121000358",
      bankName: "Silicon Valley Bank",
      electronicAccountType: "businessChecking",
      address: null,
    },
    domesticWireRoutingInfo: null,
    internationalWireRoutingInfo: null,
    address: null,
  },
  {
    id: "rcp-005",
    name: "Notion Labs Inc.",
    nickname: null,
    status: "active",
    emails: ["billing@notion.so"],
    dateLastPaid: daysAgo(2),
    defaultPaymentMethod: "ach",
    electronicRoutingInfo: {
      accountNumber: "****2210",
      routingNumber: "121000358",
      bankName: "Silicon Valley Bank",
      electronicAccountType: "businessChecking",
      address: null,
    },
    domesticWireRoutingInfo: null,
    internationalWireRoutingInfo: null,
    address: null,
  },
  {
    id: "rcp-006",
    name: "WeWork",
    nickname: "Office",
    status: "active",
    emails: ["billing@wework.com"],
    dateLastPaid: daysAgo(0),
    defaultPaymentMethod: "ach",
    electronicRoutingInfo: {
      accountNumber: "****9932",
      routingNumber: "021000021",
      bankName: "JPMorgan Chase",
      electronicAccountType: "businessChecking",
      address: null,
    },
    domesticWireRoutingInfo: null,
    internationalWireRoutingInfo: null,
    address: null,
  },
  {
    id: "rcp-007",
    name: "Carta Inc.",
    nickname: "Carta",
    status: "active",
    emails: ["billing@carta.com"],
    dateLastPaid: daysAgo(7),
    defaultPaymentMethod: "ach",
    electronicRoutingInfo: {
      accountNumber: "****4477",
      routingNumber: "121000358",
      bankName: "Silicon Valley Bank",
      electronicAccountType: "businessChecking",
      address: null,
    },
    domesticWireRoutingInfo: null,
    internationalWireRoutingInfo: null,
    address: null,
  },
  {
    id: "rcp-008",
    name: "Vercel Inc.",
    nickname: null,
    status: "active",
    emails: ["billing@vercel.com"],
    dateLastPaid: daysAgo(8),
    defaultPaymentMethod: "ach",
    electronicRoutingInfo: {
      accountNumber: "****1188",
      routingNumber: "121000358",
      bankName: "Silicon Valley Bank",
      electronicAccountType: "businessChecking",
      address: null,
    },
    domesticWireRoutingInfo: null,
    internationalWireRoutingInfo: null,
    address: null,
  },
];

// ─── Invoices ──────────────────────────────────────────────────────────────

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv-001",
    invoiceNumber: "INV-2026-0102",
    slug: "inv-0102",
    status: "Paid",
    amount: 18_500.0,
    customerId: "cust-001",
    destinationAccountId: "acct-001",
    invoiceDate: daysAgo(15),
    dueDate: daysAgo(0),
    lineItems: [
      { name: "Q1 Strategy Retainer", unitPrice: 18_500, quantity: 1 },
    ],
    creditCardEnabled: true,
    achDebitEnabled: true,
    useRealAccountNumber: false,
    ccEmails: [],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(0),
  },
  {
    id: "inv-002",
    invoiceNumber: "INV-2026-0103",
    slug: "inv-0103",
    status: "Unpaid",
    amount: 8_750.0,
    customerId: "cust-002",
    destinationAccountId: "acct-001",
    invoiceDate: daysAgo(5),
    dueDate: daysAgo(-10),
    lineItems: [
      { name: "Brand Identity Package", unitPrice: 6_500, quantity: 1 },
      { name: "Logo Variations (3x)", unitPrice: 750, quantity: 3 },
    ],
    creditCardEnabled: true,
    achDebitEnabled: true,
    useRealAccountNumber: false,
    ccEmails: [],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "inv-003",
    invoiceNumber: "INV-2026-0104",
    slug: "inv-0104",
    status: "Unpaid",
    amount: 42_000.0,
    customerId: "cust-003",
    destinationAccountId: "acct-001",
    invoiceDate: daysAgo(2),
    dueDate: daysAgo(-28),
    lineItems: [
      {
        name: "Product Strategy Consulting — February",
        unitPrice: 42_000,
        quantity: 1,
      },
    ],
    creditCardEnabled: false,
    achDebitEnabled: true,
    useRealAccountNumber: false,
    ccEmails: [],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "inv-004",
    invoiceNumber: "INV-2026-0105",
    slug: "inv-0105",
    status: "Processing",
    amount: 62_500.0,
    customerId: "cust-001",
    destinationAccountId: "acct-001",
    invoiceDate: daysAgo(1),
    dueDate: daysAgo(-14),
    lineItems: [
      {
        name: "Platform Build — Milestone 3",
        unitPrice: 50_000,
        quantity: 1,
      },
      { name: "UX Audit", unitPrice: 12_500, quantity: 1 },
    ],
    creditCardEnabled: true,
    achDebitEnabled: true,
    useRealAccountNumber: false,
    ccEmails: ["alex@archwaystudios.com"],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
    poNumber: "PO-2026-0042",
  },
  {
    id: "inv-005",
    invoiceNumber: "INV-2026-0106",
    slug: "inv-0106",
    status: "Paid",
    amount: 15_000.0,
    customerId: "cust-004",
    destinationAccountId: "acct-001",
    invoiceDate: daysAgo(30),
    dueDate: daysAgo(15),
    lineItems: [
      {
        name: "Website Redesign — Phase 1",
        unitPrice: 15_000,
        quantity: 1,
      },
    ],
    creditCardEnabled: true,
    achDebitEnabled: true,
    useRealAccountNumber: false,
    ccEmails: [],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(14),
  },
];

// ─── Customers ─────────────────────────────────────────────────────────────

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    name: "Meridian Health Group",
    email: "ap@meridianhealth.com",
    address: {
      address1: "200 Park Avenue",
      city: "New York",
      region: "NY",
      postalCode: "10166",
      country: "US",
    },
  },
  {
    id: "cust-002",
    name: "Oakmont Partners",
    email: "finance@oakmontpartners.com",
    address: {
      address1: "555 California St",
      city: "San Francisco",
      region: "CA",
      postalCode: "94104",
      country: "US",
    },
  },
  {
    id: "cust-003",
    name: "Lumen Ventures LLC",
    email: "invoices@lumenventures.co",
    address: {
      address1: "1 Main St",
      city: "Cambridge",
      region: "MA",
      postalCode: "02142",
      country: "US",
    },
  },
  {
    id: "cust-004",
    name: "Redwood Capital",
    email: "accounts@redwoodcap.com",
    address: {
      address1: "2100 Sand Hill Rd",
      city: "Menlo Park",
      region: "CA",
      postalCode: "94025",
      country: "US",
    },
  },
  {
    id: "cust-005",
    name: "Coastal Digital Agency",
    email: "billing@coastaldigital.io",
    address: {
      address1: "88 Colin P Kelly Jr St",
      city: "San Francisco",
      region: "CA",
      postalCode: "94107",
      country: "US",
    },
  },
];

// ─── Organization ──────────────────────────────────────────────────────────

export const MOCK_ORGANIZATION: Organization = {
  id: "org-001",
  kind: "business",
  legalBusinessName: "Archway Studios Inc.",
  createdAt: "2023-06-15T00:00:00Z",
  ein: "82-1234567",
  dbas: ["Archway Studios", "Archway Design Co."],
  status: "active",
};

// ─── Team ──────────────────────────────────────────────────────────────────

export const MOCK_TEAM: TeamMember[] = [
  {
    id: "usr-001",
    role: "administrator",
    email: "alex@archwaystudios.com",
    status: "active",
    createdAt: "2023-06-15T00:00:00Z",
  },
  {
    id: "usr-002",
    role: "administrator",
    email: "jordan@archwaystudios.com",
    status: "active",
    createdAt: "2023-09-01T00:00:00Z",
  },
  {
    id: "usr-003",
    role: "bookkeeper",
    email: "taylor@archwaystudios.com",
    status: "active",
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "usr-004",
    role: "employee",
    email: "sam@archwaystudios.com",
    status: "active",
    createdAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "usr-005",
    role: "cardOnlyUser",
    email: "casey@archwaystudios.com",
    status: "active",
    createdAt: "2025-02-01T00:00:00Z",
  },
];

// ─── Treasury ──────────────────────────────────────────────────────────────

export const MOCK_TREASURY: TreasuryResponse = {
  accounts: [
    {
      id: "trs-001",
      accountNumber: "1029385100",
      routingNumber: "084106768",
      name: "Treasury",
      status: "active",
      type: "treasury",
      kind: "treasury",
      createdAt: "2024-02-01T00:00:00Z",
      availableBalance: 500_000.0,
      currentBalance: 500_000.0,
      legalBusinessName: "Archway Studios Inc.",
      dashboardLink: "https://app.mercury.com",
      nickname: "Treasury Reserve",
      canReceiveTransactions: false,
    },
    {
      id: "trs-002",
      accountNumber: "1029385200",
      routingNumber: "084106768",
      name: "Treasury Growth",
      status: "active",
      type: "treasury",
      kind: "treasury",
      createdAt: "2025-01-15T00:00:00Z",
      availableBalance: 250_000.0,
      currentBalance: 250_000.0,
      legalBusinessName: "Archway Studios Inc.",
      dashboardLink: "https://app.mercury.com",
      nickname: "Growth Fund",
      canReceiveTransactions: false,
    },
  ],
};

// ─── Credit ────────────────────────────────────────────────────────────────

export const MOCK_CREDIT: CreditAccount = {
  id: "crd-001",
  creditLimit: 100_000,
  currentBalance: 12_450.0,
  availableCredit: 87_550.0,
  apr: 0,
  status: "active",
  dueDate: daysAgo(-25),
  minimumPayment: 500,
};

// ─── Statements ────────────────────────────────────────────────────────────

export const MOCK_STATEMENTS: Statement[] = [
  {
    id: "stmt-001",
    startDate: "2026-01-01",
    endDate: "2026-01-31",
    companyLegalName: "Archway Studios Inc.",
    endingBalance: 284_391.47,
    ein: "82-1234567",
  },
  {
    id: "stmt-002",
    startDate: "2025-12-01",
    endDate: "2025-12-31",
    companyLegalName: "Archway Studios Inc.",
    endingBalance: 196_842.33,
    ein: "82-1234567",
  },
  {
    id: "stmt-003",
    startDate: "2025-11-01",
    endDate: "2025-11-30",
    companyLegalName: "Archway Studios Inc.",
    endingBalance: 221_500.0,
    ein: "82-1234567",
  },
  {
    id: "stmt-004",
    startDate: "2025-10-01",
    endDate: "2025-10-31",
    companyLegalName: "Archway Studios Inc.",
    endingBalance: 178_250.0,
    ein: "82-1234567",
  },
  {
    id: "stmt-005",
    startDate: "2025-09-01",
    endDate: "2025-09-30",
    companyLegalName: "Archway Studios Inc.",
    endingBalance: 162_100.0,
    ein: "82-1234567",
  },
];

// ─── Categories ────────────────────────────────────────────────────────────

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-001", name: "Software & SaaS" },
  { id: "cat-002", name: "Contractors" },
  { id: "cat-003", name: "Payroll" },
  { id: "cat-004", name: "Office & Supplies" },
  { id: "cat-005", name: "Travel" },
  { id: "cat-006", name: "Marketing" },
  { id: "cat-007", name: "Revenue" },
  { id: "cat-008", name: "Legal & Professional" },
  { id: "cat-009", name: "Transfers" },
  { id: "cat-010", name: "Hosting & Infrastructure" },
];

// ─── Events ────────────────────────────────────────────────────────────────

export const MOCK_EVENTS: MercuryEvent[] = [
  {
    id: "evt-001",
    resourceType: "transaction",
    resourceId: "txn-101",
    operationType: "create",
    resourceVersion: 1,
    occurredAt: hoursAgo(1),
    changedPaths: ["/status", "/amount", "/counterpartyName"],
    mergePatch: {
      status: "pending",
      amount: -6750,
      counterpartyName: "Sarah Chen",
    },
  },
  {
    id: "evt-002",
    resourceType: "transaction",
    resourceId: "txn-102",
    operationType: "create",
    resourceVersion: 1,
    occurredAt: hoursAgo(3),
    changedPaths: ["/status", "/amount"],
    mergePatch: { status: "sent", amount: -1200 },
  },
  {
    id: "evt-003",
    resourceType: "transaction",
    resourceId: "txn-001",
    operationType: "update",
    resourceVersion: 2,
    occurredAt: daysAgo(0),
    changedPaths: ["/status"],
    mergePatch: { status: "completed" },
    previousValues: { status: "sent" },
  },
  {
    id: "evt-004",
    resourceType: "transaction",
    resourceId: "txn-002",
    operationType: "create",
    resourceVersion: 1,
    occurredAt: daysAgo(0),
    changedPaths: ["/status"],
    mergePatch: { status: "posted" },
  },
  {
    id: "evt-005",
    resourceType: "checkingAccount",
    resourceId: "acct-001",
    operationType: "update",
    resourceVersion: 87,
    occurredAt: hoursAgo(1),
    changedPaths: ["/availableBalance", "/currentBalance"],
    mergePatch: { availableBalance: 284391.47, currentBalance: 291141.47 },
  },
  {
    id: "evt-006",
    resourceType: "transaction",
    resourceId: "txn-103",
    operationType: "create",
    resourceVersion: 1,
    occurredAt: hoursAgo(2),
    changedPaths: ["/status", "/amount"],
    mergePatch: {
      status: "processing",
      amount: 35000,
      counterpartyName: "Lumen Ventures LLC",
    },
  },
  {
    id: "evt-007",
    resourceType: "checkingAccount",
    resourceId: "acct-003",
    operationType: "update",
    resourceVersion: 34,
    occurredAt: hoursAgo(4),
    changedPaths: ["/availableBalance"],
    mergePatch: { availableBalance: 67520 },
  },
  {
    id: "evt-008",
    resourceType: "transaction",
    resourceId: "txn-006",
    operationType: "update",
    resourceVersion: 3,
    occurredAt: daysAgo(2),
    changedPaths: ["/status"],
    mergePatch: { status: "completed" },
    previousValues: { status: "sent" },
  },
];

// ─── Webhooks ──────────────────────────────────────────────────────────────

export const MOCK_WEBHOOKS: WebhookEndpoint[] = [
  {
    id: "wh-001",
    url: "https://hooks.archwaystudios.com/mercury/transactions",
    status: "active",
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: daysAgo(0),
    eventTypes: ["transaction.created", "transaction.updated"],
  },
  {
    id: "wh-002",
    url: "https://hooks.archwaystudios.com/mercury/accounts",
    status: "active",
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: daysAgo(3),
    eventTypes: [
      "checkingAccount.updated",
      "savingsAccount.updated",
      "treasuryAccount.updated",
    ],
  },
];