export const languages = [
  { icon: "🇺🇸", title: "English", value: "en" },
  { icon: "🇪🇸", title: "Spanish", value: "es" },
  { icon: "🇩🇪", title: "German", value: "de" },
  { icon: "🇫🇷", title: "French", value: "fr" },
  { icon: "🇯🇵", title: "Japanese", value: "ja" },
  { icon: "🇷🇺", title: "Russian", value: "ru" },
  { icon: "🇵🇹", title: "Portuguese", value: "pt" },
  { icon: "🇮🇹", title: "Italian", value: "it" },
  { icon: "🇨🇳", title: "Chinese", value: "zh" },
  { icon: "🇮🇷", title: "Persian", value: "fa" },
  { icon: "🇦🇪", title: "Arabic", value: "ar" },
  { icon: "🇵🇱", title: "Polish", value: "pl" },
  { icon: "🇸🇽", title: "Dutch", value: "nl" },
  { icon: "🇹🇷", title: "Turkish", value: "tr" },
  { icon: "🇬🇷", title: "Greek", value: "el" },
];

export const excludedSections = [
  "See also",
  "References",
  "External links",
  "Further reading",
  "Notes",
  "Bibliography",
  "Sources",
  "Citations",
  "Footnotes",
  "Véase también",
  "Referencias",
  "Enlaces externos",
  "Otras lecturas",
  "Notas",
  "Bibliografía",
  "Fuentes",
  "Citas",
  "Notas al pie",
  "Siehe auch",
  "Verweise",
  "Externe Links",
  "Weiteres Lesen",
  "Anmerkungen",
  "Literaturverzeichnis",
  "Quellen",
  "Zitate",
  "Fußnoten",
  "Voir également",
  "Les références",
  "Liens externes",
  "Lecture complémentaire",
  "Remarques",
  "Bibliographie",
  "Sources",
  "Citations",
  "Notes de bas de page",
  "Смотрите также",
  "Использованная литература",
  "Внешние ссылки",
  "Дальнейшее чтение",
  "Примечания",
  "Библиография",
  "Цитаты",
  "Сноски",
  "Veja também",
  "Referências",
  "Links externos",
  "Leitura adicional",
  "Notas",
  "Bibliografia",
  "Fontes",
  "Citações",
  "Notas de rodapé",
  "Guarda anche",
  "Riferimenti",
  "Link esterno",
  "Ulteriori letture",
  "Appunti",
  "Bibliografia",
  "Fonti",
  "Citazioni",
  "Note a piè di pagina",
  "Ayrıca bakınız",
  "Referanslar",
  "Dış bağlantılar",
  "Daha fazla okuma",
  "Notlar",
  "Kaynakça",
  "Kaynaklar",
  "Alıntılar",
  "Dipnotlar",
  "Δείτε επίσης",
  "Βιβλιογραφικές αναφορές",
  "Εξωτερικοί σύνδεσμοι",
  "Περαιτέρω ανάγνωση",
  "Σημειώσεις",
  "Βιβλιογραφία",
  "Πηγές",
  "Αναφορές",
  "Υποσημειώσεις",
];

export const excludedMetatadataLabels = [
  "image",
  "cat",
  "subcat",
  "sortkey",
  "italictitle",
  "wikisource",
  "listadesplegable",
];

export const excludedMetatadataValues = ["true", "false", "si", "no", "altura"];
