export const ALOWED_IMGUR_CONTENT_TYPES = [
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/apng",
  "image/tiff",
  "video/mp4",
  "video/mpeg",
  "vide/avi",
  "video/x-matroska",
  "video/x-flv",
  "video/msvideo",
  "video/x-msvideo",
  "video/x-ms-wmv",
];
