import { showHUD } from "@raycast/api";
import { showFailureToast } from "@raycast/utils";
// Generated by the Raycast Swift build plugin from swift/Sources/CleanScreenKeyboard.
// The type-safe interface only exists after a Raycast build (`npm run dev` / ⌘B),
// so editor/`tsc` may not resolve this import until then. See dev-docs.md §13.
import { startCleaningMode } from "swift:../swift";

export default async function Command() {
  try {
    // Hand off to the native overlay (dev-docs.md §13.3): the Swift side draws a
    // black NSWindow on every screen, installs a CGEvent tap to suppress keyboard
    // input, shows the centered "Done" button, and owns its own window + run loop.
    // This Promise resolves only when the user clicks that button — at which point
    // the overlay is torn down and the keyboard is restored.
    await startCleaningMode();
    await showHUD("Screen and keyboard restored");
  } catch (error) {
    // Full keyboard blocking depends on the Accessibility permission granted to
    // the Raycast app (System Settings → Privacy & Security → Accessibility).
    await showFailureToast(error, { title: "Could not start cleaning mode" });
  }
}
