#!/usr/bin/env node

/**
 * Update the "currency" preference in the manifest to include all currencies
 * included in src/currencies.json
 *
 * Thie script should be run from this directory
 */

const fs = require('fs');

let currencies = [];
let pkg = {};

try {
  currencies = require('../src/currencies.json');
  pkg = require('../package.json');
} catch (err) {
  console.error('Could not load required file');
  process.exit(1);
}

const preferenceIdx = pkg.preferences?.findIndex(({ name }) => name === 'currency')

if (preferenceIdx === undefined) {
  console.error('Could not find currency preference in manifest');
  process.exit(1);
}

pkg.preferences[preferenceIdx].data = currencies.map((currency, idx) => {
  const expectedKeys = ['id', 'name', 'symbol', 'category'];

  expectedKeys.forEach((key) => {
    if (Object.keys(currency).includes(key) === false) {
      console.error(`Currency at index: ${idx} does not include the expected key: ${key}`);
      process.exit(1);
    }
  });

  return {
    title: `${currency.name} (${currency.symbol})`,
    value: currency.id,
  }
});

fs.writeFileSync('../package.json', `${JSON.stringify(pkg, null, 2)}\n`);

console.log('Currencies updated!');
