export interface IrregularVerb {
  /** Base form / infinitive */
  base: string;
  /** Past simple — spelling variants separated by " / " */
  preterit: string;
  /** Past participle — spelling variants separated by " / " */
  participle: string;
}

export const VERBS: IrregularVerb[] = [
  { base: "arise", preterit: "arose", participle: "arisen" },
  { base: "awake", preterit: "awoke", participle: "awoken" },
  { base: "be", preterit: "was / were", participle: "been" },
  { base: "bear", preterit: "bore", participle: "borne / born" },
  { base: "beat", preterit: "beat", participle: "beaten" },
  { base: "become", preterit: "became", participle: "become" },
  { base: "begin", preterit: "began", participle: "begun" },
  { base: "behold", preterit: "beheld", participle: "beheld" },
  { base: "bend", preterit: "bent", participle: "bent" },
  { base: "bet", preterit: "bet", participle: "bet" },
  { base: "bid", preterit: "bid", participle: "bid" },
  { base: "bind", preterit: "bound", participle: "bound" },
  { base: "bite", preterit: "bit", participle: "bitten" },
  { base: "bleed", preterit: "bled", participle: "bled" },
  { base: "blow", preterit: "blew", participle: "blown" },
  { base: "break", preterit: "broke", participle: "broken" },
  { base: "breed", preterit: "bred", participle: "bred" },
  { base: "bring", preterit: "brought", participle: "brought" },
  { base: "broadcast", preterit: "broadcast", participle: "broadcast" },
  { base: "build", preterit: "built", participle: "built" },
  { base: "burn", preterit: "burnt / burned", participle: "burnt / burned" },
  { base: "burst", preterit: "burst", participle: "burst" },
  { base: "buy", preterit: "bought", participle: "bought" },
  { base: "cast", preterit: "cast", participle: "cast" },
  { base: "catch", preterit: "caught", participle: "caught" },
  { base: "choose", preterit: "chose", participle: "chosen" },
  { base: "cling", preterit: "clung", participle: "clung" },
  { base: "come", preterit: "came", participle: "come" },
  { base: "cost", preterit: "cost", participle: "cost" },
  { base: "creep", preterit: "crept", participle: "crept" },
  { base: "cut", preterit: "cut", participle: "cut" },
  { base: "deal", preterit: "dealt", participle: "dealt" },
  { base: "dig", preterit: "dug", participle: "dug" },
  { base: "dive", preterit: "dived / dove", participle: "dived" },
  { base: "do", preterit: "did", participle: "done" },
  { base: "draw", preterit: "drew", participle: "drawn" },
  {
    base: "dream",
    preterit: "dreamt / dreamed",
    participle: "dreamt / dreamed",
  },
  { base: "drink", preterit: "drank", participle: "drunk" },
  { base: "drive", preterit: "drove", participle: "driven" },
  { base: "dwell", preterit: "dwelt / dwelled", participle: "dwelt / dwelled" },
  { base: "eat", preterit: "ate", participle: "eaten" },
  { base: "fall", preterit: "fell", participle: "fallen" },
  { base: "feed", preterit: "fed", participle: "fed" },
  { base: "feel", preterit: "felt", participle: "felt" },
  { base: "fight", preterit: "fought", participle: "fought" },
  { base: "find", preterit: "found", participle: "found" },
  { base: "flee", preterit: "fled", participle: "fled" },
  { base: "fling", preterit: "flung", participle: "flung" },
  { base: "fly", preterit: "flew", participle: "flown" },
  { base: "forbid", preterit: "forbade", participle: "forbidden" },
  { base: "forecast", preterit: "forecast", participle: "forecast" },
  { base: "foresee", preterit: "foresaw", participle: "foreseen" },
  { base: "foretell", preterit: "foretold", participle: "foretold" },
  { base: "forget", preterit: "forgot", participle: "forgotten" },
  { base: "forgive", preterit: "forgave", participle: "forgiven" },
  { base: "forsake", preterit: "forsook", participle: "forsaken" },
  { base: "freeze", preterit: "froze", participle: "frozen" },
  { base: "get", preterit: "got", participle: "got / gotten" },
  { base: "give", preterit: "gave", participle: "given" },
  { base: "go", preterit: "went", participle: "gone" },
  { base: "grind", preterit: "ground", participle: "ground" },
  { base: "grow", preterit: "grew", participle: "grown" },
  { base: "hang", preterit: "hung", participle: "hung" },
  { base: "have", preterit: "had", participle: "had" },
  { base: "hear", preterit: "heard", participle: "heard" },
  { base: "hide", preterit: "hid", participle: "hidden" },
  { base: "hit", preterit: "hit", participle: "hit" },
  { base: "hold", preterit: "held", participle: "held" },
  { base: "hurt", preterit: "hurt", participle: "hurt" },
  { base: "keep", preterit: "kept", participle: "kept" },
  { base: "kneel", preterit: "knelt / kneeled", participle: "knelt / kneeled" },
  { base: "know", preterit: "knew", participle: "known" },
  { base: "lay", preterit: "laid", participle: "laid" },
  { base: "lead", preterit: "led", participle: "led" },
  { base: "lean", preterit: "leant / leaned", participle: "leant / leaned" },
  { base: "leap", preterit: "leapt / leaped", participle: "leapt / leaped" },
  {
    base: "learn",
    preterit: "learnt / learned",
    participle: "learnt / learned",
  },
  { base: "leave", preterit: "left", participle: "left" },
  { base: "lend", preterit: "lent", participle: "lent" },
  { base: "let", preterit: "let", participle: "let" },
  { base: "lie", preterit: "lay", participle: "lain" },
  { base: "light", preterit: "lit / lighted", participle: "lit / lighted" },
  { base: "lose", preterit: "lost", participle: "lost" },
  { base: "make", preterit: "made", participle: "made" },
  { base: "mean", preterit: "meant", participle: "meant" },
  { base: "meet", preterit: "met", participle: "met" },
  { base: "mislead", preterit: "misled", participle: "misled" },
  { base: "mistake", preterit: "mistook", participle: "mistaken" },
  {
    base: "misunderstand",
    preterit: "misunderstood",
    participle: "misunderstood",
  },
  { base: "mow", preterit: "mowed", participle: "mown / mowed" },
  { base: "overcome", preterit: "overcame", participle: "overcome" },
  { base: "overhear", preterit: "overheard", participle: "overheard" },
  { base: "oversleep", preterit: "overslept", participle: "overslept" },
  { base: "overtake", preterit: "overtook", participle: "overtaken" },
  { base: "pay", preterit: "paid", participle: "paid" },
  { base: "plead", preterit: "pleaded / pled", participle: "pleaded / pled" },
  { base: "prove", preterit: "proved", participle: "proven / proved" },
  { base: "put", preterit: "put", participle: "put" },
  { base: "quit", preterit: "quit", participle: "quit" },
  { base: "read", preterit: "read", participle: "read" },
  { base: "repay", preterit: "repaid", participle: "repaid" },
  { base: "rid", preterit: "rid", participle: "rid" },
  { base: "ride", preterit: "rode", participle: "ridden" },
  { base: "ring", preterit: "rang", participle: "rung" },
  { base: "rise", preterit: "rose", participle: "risen" },
  { base: "run", preterit: "ran", participle: "run" },
  { base: "saw", preterit: "sawed", participle: "sawn / sawed" },
  { base: "say", preterit: "said", participle: "said" },
  { base: "see", preterit: "saw", participle: "seen" },
  { base: "seek", preterit: "sought", participle: "sought" },
  { base: "sell", preterit: "sold", participle: "sold" },
  { base: "send", preterit: "sent", participle: "sent" },
  { base: "set", preterit: "set", participle: "set" },
  { base: "sew", preterit: "sewed", participle: "sewn / sewed" },
  { base: "shake", preterit: "shook", participle: "shaken" },
  { base: "shed", preterit: "shed", participle: "shed" },
  { base: "shine", preterit: "shone", participle: "shone" },
  { base: "shoe", preterit: "shod", participle: "shod" },
  { base: "shoot", preterit: "shot", participle: "shot" },
  { base: "show", preterit: "showed", participle: "shown / showed" },
  { base: "shrink", preterit: "shrank", participle: "shrunk" },
  { base: "shut", preterit: "shut", participle: "shut" },
  { base: "sing", preterit: "sang", participle: "sung" },
  { base: "sink", preterit: "sank", participle: "sunk" },
  { base: "sit", preterit: "sat", participle: "sat" },
  { base: "slay", preterit: "slew", participle: "slain" },
  { base: "sleep", preterit: "slept", participle: "slept" },
  { base: "slide", preterit: "slid", participle: "slid" },
  { base: "sling", preterit: "slung", participle: "slung" },
  { base: "slit", preterit: "slit", participle: "slit" },
  { base: "smell", preterit: "smelt / smelled", participle: "smelt / smelled" },
  { base: "sow", preterit: "sowed", participle: "sown / sowed" },
  { base: "speak", preterit: "spoke", participle: "spoken" },
  { base: "speed", preterit: "sped / speeded", participle: "sped / speeded" },
  { base: "spell", preterit: "spelt / spelled", participle: "spelt / spelled" },
  { base: "spend", preterit: "spent", participle: "spent" },
  { base: "spill", preterit: "spilt / spilled", participle: "spilt / spilled" },
  { base: "spin", preterit: "spun", participle: "spun" },
  { base: "spit", preterit: "spat / spit", participle: "spat / spit" },
  { base: "split", preterit: "split", participle: "split" },
  {
    base: "spoil",
    preterit: "spoilt / spoiled",
    participle: "spoilt / spoiled",
  },
  { base: "spread", preterit: "spread", participle: "spread" },
  { base: "spring", preterit: "sprang", participle: "sprung" },
  { base: "stand", preterit: "stood", participle: "stood" },
  { base: "steal", preterit: "stole", participle: "stolen" },
  { base: "stick", preterit: "stuck", participle: "stuck" },
  { base: "sting", preterit: "stung", participle: "stung" },
  { base: "stink", preterit: "stank / stunk", participle: "stunk" },
  { base: "stride", preterit: "strode", participle: "stridden" },
  { base: "strike", preterit: "struck", participle: "struck" },
  { base: "string", preterit: "strung", participle: "strung" },
  {
    base: "strive",
    preterit: "strove / strived",
    participle: "striven / strived",
  },
  { base: "swear", preterit: "swore", participle: "sworn" },
  { base: "sweat", preterit: "sweat / sweated", participle: "sweat / sweated" },
  { base: "sweep", preterit: "swept", participle: "swept" },
  { base: "swell", preterit: "swelled", participle: "swollen / swelled" },
  { base: "swim", preterit: "swam", participle: "swum" },
  { base: "swing", preterit: "swung", participle: "swung" },
  { base: "take", preterit: "took", participle: "taken" },
  { base: "teach", preterit: "taught", participle: "taught" },
  { base: "tear", preterit: "tore", participle: "torn" },
  { base: "tell", preterit: "told", participle: "told" },
  { base: "think", preterit: "thought", participle: "thought" },
  {
    base: "thrive",
    preterit: "thrived / throve",
    participle: "thrived / thriven",
  },
  { base: "throw", preterit: "threw", participle: "thrown" },
  { base: "thrust", preterit: "thrust", participle: "thrust" },
  { base: "tread", preterit: "trod", participle: "trodden / trod" },
  { base: "undergo", preterit: "underwent", participle: "undergone" },
  { base: "understand", preterit: "understood", participle: "understood" },
  { base: "undertake", preterit: "undertook", participle: "undertaken" },
  { base: "undo", preterit: "undid", participle: "undone" },
  { base: "upset", preterit: "upset", participle: "upset" },
  { base: "wake", preterit: "woke", participle: "woken" },
  { base: "wear", preterit: "wore", participle: "worn" },
  { base: "weave", preterit: "wove", participle: "woven" },
  { base: "weep", preterit: "wept", participle: "wept" },
  { base: "wet", preterit: "wet / wetted", participle: "wet / wetted" },
  { base: "win", preterit: "won", participle: "won" },
  { base: "wind", preterit: "wound", participle: "wound" },
  { base: "withdraw", preterit: "withdrew", participle: "withdrawn" },
  { base: "withstand", preterit: "withstood", participle: "withstood" },
  { base: "wring", preterit: "wrung", participle: "wrung" },
  { base: "write", preterit: "wrote", participle: "written" },
];
