export interface Emoji {
  name: string;
  emoji: string;
}

export interface Emojis {
  "Smileys & Emotion": Emoji[];
  Activities: Emoji[];
  "Travel & Places": Emoji[];
  "Food & Drink": Emoji[];
  "Animals & Nature": Emoji[];
  "People & Body": Emoji[];
  Objects: Emoji[];
  Symbols: Emoji[];
  Flags: Emoji[];
  Component: Emoji[];
}

const emojis: Emojis = {
  "Smileys & Emotion": [
    { name: "Eye In Speech Bubble", emoji: "👁️‍🗨️" },
    { name: "Japanese Ogre", emoji: "👹" },
    { name: "Japanese Goblin", emoji: "👺" },
    { name: "Ghost", emoji: "👻" },
    { name: "Extraterrestrial Alien", emoji: "👽" },
    { name: "Alien Monster", emoji: "👾" },
    { name: "Imp", emoji: "👿" },
    { name: "Skull", emoji: "💀" },
    { name: "Kiss Mark", emoji: "💋" },
    { name: "Love Letter", emoji: "💌" },
    { name: "Beating Heart", emoji: "💓" },
    { name: "Broken Heart", emoji: "💔" },
    { name: "Two Hearts", emoji: "💕" },
    { name: "Sparkling Heart", emoji: "💖" },
    { name: "Growing Heart", emoji: "💗" },
    { name: "Heart With Arrow", emoji: "💘" },
    { name: "Blue Heart", emoji: "💙" },
    { name: "Green Heart", emoji: "💚" },
    { name: "Yellow Heart", emoji: "💛" },
    { name: "Purple Heart", emoji: "💜" },
    { name: "Heart With Ribbon", emoji: "💝" },
    { name: "Revolving Hearts", emoji: "💞" },
    { name: "Heart Decoration", emoji: "💟" },
    { name: "Anger Symbol", emoji: "💢" },
    { name: "Sleeping Symbol", emoji: "💤" },
    { name: "Collision Symbol", emoji: "💥" },
    { name: "Splashing Sweat Symbol", emoji: "💦" },
    { name: "Dash Symbol", emoji: "💨" },
    { name: "Pile Of Poo", emoji: "💩" },
    { name: "Dizzy Symbol", emoji: "💫" },
    { name: "Speech Balloon", emoji: "💬" },
    { name: "Thought Balloon", emoji: "💭" },
    { name: "Hundred Points Symbol", emoji: "💯" },
    { name: "Hole", emoji: "🕳️" },
    { name: "Black Heart", emoji: "🖤" },
    { name: "Left Speech Bubble", emoji: "🗨️" },
    { name: "Right Anger Bubble", emoji: "🗯️" },
    { name: "Grinning Face", emoji: "😀" },
    { name: "Grinning Face With Smiling Eyes", emoji: "😁" },
    { name: "Face With Tears Of Joy", emoji: "😂" },
    { name: "Smiling Face With Open Mouth", emoji: "😃" },
    { name: "Smiling Face With Open Mouth And Smiling Eyes", emoji: "😄" },
    { name: "Smiling Face With Open Mouth And Cold Sweat", emoji: "😅" },
    {
      name: "Smiling Face With Open Mouth And Tightly-closed Eyes",
      emoji: "😆",
    },
    { name: "Smiling Face With Halo", emoji: "😇" },
    { name: "Smiling Face With Horns", emoji: "😈" },
    { name: "Winking Face", emoji: "😉" },
    { name: "Smiling Face With Smiling Eyes", emoji: "😊" },
    { name: "Face Savouring Delicious Food", emoji: "😋" },
    { name: "Relieved Face", emoji: "😌" },
    { name: "Smiling Face With Heart-shaped Eyes", emoji: "😍" },
    { name: "Smiling Face With Sunglasses", emoji: "😎" },
    { name: "Smirking Face", emoji: "😏" },
    { name: "Neutral Face", emoji: "😐" },
    { name: "Expressionless Face", emoji: "😑" },
    { name: "Unamused Face", emoji: "😒" },
    { name: "Face With Cold Sweat", emoji: "😓" },
    { name: "Pensive Face", emoji: "😔" },
    { name: "Confused Face", emoji: "😕" },
    { name: "Confounded Face", emoji: "😖" },
    { name: "Kissing Face", emoji: "😗" },
    { name: "Face Throwing A Kiss", emoji: "😘" },
    { name: "Kissing Face With Smiling Eyes", emoji: "😙" },
    { name: "Kissing Face With Closed Eyes", emoji: "😚" },
    { name: "Face With Stuck-out Tongue", emoji: "😛" },
    { name: "Face With Stuck-out Tongue And Winking Eye", emoji: "😜" },
    { name: "Face With Stuck-out Tongue And Tightly-closed Eyes", emoji: "😝" },
    { name: "Disappointed Face", emoji: "😞" },
    { name: "Worried Face", emoji: "😟" },
    { name: "Angry Face", emoji: "😠" },
    { name: "Pouting Face", emoji: "😡" },
    { name: "Crying Face", emoji: "😢" },
    { name: "Persevering Face", emoji: "😣" },
    { name: "Face With Look Of Triumph", emoji: "😤" },
    { name: "Disappointed But Relieved Face", emoji: "😥" },
    { name: "Frowning Face With Open Mouth", emoji: "😦" },
    { name: "Anguished Face", emoji: "😧" },
    { name: "Fearful Face", emoji: "😨" },
    { name: "Weary Face", emoji: "😩" },
    { name: "Sleepy Face", emoji: "😪" },
    { name: "Tired Face", emoji: "😫" },
    { name: "Grimacing Face", emoji: "😬" },
    { name: "Loudly Crying Face", emoji: "😭" },
    { name: "Face Exhaling", emoji: "😮‍💨" },
    { name: "Face With Open Mouth", emoji: "😮" },
    { name: "Hushed Face", emoji: "😯" },
    { name: "Face With Open Mouth And Cold Sweat", emoji: "😰" },
    { name: "Face Screaming In Fear", emoji: "😱" },
    { name: "Astonished Face", emoji: "😲" },
    { name: "Flushed Face", emoji: "😳" },
    { name: "Sleeping Face", emoji: "😴" },
    { name: "Face With Spiral Eyes", emoji: "😵‍💫" },
    { name: "Dizzy Face", emoji: "😵" },
    { name: "Face In Clouds", emoji: "😶‍🌫️" },
    { name: "Face Without Mouth", emoji: "😶" },
    { name: "Face With Medical Mask", emoji: "😷" },
    { name: "Grinning Cat Face With Smiling Eyes", emoji: "😸" },
    { name: "Cat Face With Tears Of Joy", emoji: "😹" },
    { name: "Smiling Cat Face With Open Mouth", emoji: "😺" },
    { name: "Smiling Cat Face With Heart-shaped Eyes", emoji: "😻" },
    { name: "Cat Face With Wry Smile", emoji: "😼" },
    { name: "Kissing Cat Face With Closed Eyes", emoji: "😽" },
    { name: "Pouting Cat Face", emoji: "😾" },
    { name: "Crying Cat Face", emoji: "😿" },
    { name: "Weary Cat Face", emoji: "🙀" },
    { name: "Slightly Frowning Face", emoji: "🙁" },
    { name: "Head Shaking Horizontally", emoji: "🙂‍↔️" },
    { name: "Head Shaking Vertically", emoji: "🙂‍↕️" },
    { name: "Slightly Smiling Face", emoji: "🙂" },
    { name: "Upside-down Face", emoji: "🙃" },
    { name: "Face With Rolling Eyes", emoji: "🙄" },
    { name: "See-no-evil Monkey", emoji: "🙈" },
    { name: "Hear-no-evil Monkey", emoji: "🙉" },
    { name: "Speak-no-evil Monkey", emoji: "🙊" },
    { name: "White Heart", emoji: "🤍" },
    { name: "Brown Heart", emoji: "🤎" },
    { name: "Zipper-mouth Face", emoji: "🤐" },
    { name: "Money-mouth Face", emoji: "🤑" },
    { name: "Face With Thermometer", emoji: "🤒" },
    { name: "Nerd Face", emoji: "🤓" },
    { name: "Thinking Face", emoji: "🤔" },
    { name: "Face With Head-bandage", emoji: "🤕" },
    { name: "Robot Face", emoji: "🤖" },
    { name: "Hugging Face", emoji: "🤗" },
    { name: "Face With Cowboy Hat", emoji: "🤠" },
    { name: "Clown Face", emoji: "🤡" },
    { name: "Nauseated Face", emoji: "🤢" },
    { name: "Rolling On The Floor Laughing", emoji: "🤣" },
    { name: "Drooling Face", emoji: "🤤" },
    { name: "Lying Face", emoji: "🤥" },
    { name: "Sneezing Face", emoji: "🤧" },
    { name: "Face With One Eyebrow Raised", emoji: "🤨" },
    { name: "Grinning Face With Star Eyes", emoji: "🤩" },
    { name: "Grinning Face With One Large And One Small Eye", emoji: "🤪" },
    { name: "Face With Finger Covering Closed Lips", emoji: "🤫" },
    { name: "Serious Face With Symbols Covering Mouth", emoji: "🤬" },
    {
      name: "Smiling Face With Smiling Eyes And Hand Covering Mouth",
      emoji: "🤭",
    },
    { name: "Face With Open Mouth Vomiting", emoji: "🤮" },
    { name: "Shocked Face With Exploding Head", emoji: "🤯" },
    { name: "Smiling Face With Smiling Eyes And Three Hearts", emoji: "🥰" },
    { name: "Yawning Face", emoji: "🥱" },
    { name: "Smiling Face With Tear", emoji: "🥲" },
    { name: "Face With Party Horn And Party Hat", emoji: "🥳" },
    { name: "Face With Uneven Eyes And Wavy Mouth", emoji: "🥴" },
    { name: "Overheated Face", emoji: "🥵" },
    { name: "Freezing Face", emoji: "🥶" },
    { name: "Disguised Face", emoji: "🥸" },
    { name: "Face Holding Back Tears", emoji: "🥹" },
    { name: "Face With Pleading Eyes", emoji: "🥺" },
    { name: "Face With Monocle", emoji: "🧐" },
    { name: "Orange Heart", emoji: "🧡" },
    { name: "Light Blue Heart", emoji: "🩵" },
    { name: "Grey Heart", emoji: "🩶" },
    { name: "Pink Heart", emoji: "🩷" },
    { name: "Melting Face", emoji: "🫠" },
    { name: "Saluting Face", emoji: "🫡" },
    { name: "Face With Open Eyes And Hand Over Mouth", emoji: "🫢" },
    { name: "Face With Peeking Eye", emoji: "🫣" },
    { name: "Face With Diagonal Mouth", emoji: "🫤" },
    { name: "Dotted Line Face", emoji: "🫥" },
    { name: "Shaking Face", emoji: "🫨" },
    { name: "Skull And Crossbones", emoji: "☠️" },
    { name: "Frowning Face", emoji: "☹️" },
    { name: "White Smiling Face", emoji: "☺️" },
    { name: "Heart Exclamation", emoji: "❣️" },
    { name: "Heart On Fire", emoji: "❤️‍🔥" },
    { name: "Mending Heart", emoji: "❤️‍🩹" },
    { name: "Heavy Black Heart", emoji: "❤️" },
  ],
  Activities: [
    { name: "Mahjong Tile Red Dragon", emoji: "🀄" },
    { name: "Playing Card Black Joker", emoji: "🃏" },
    { name: "Ribbon", emoji: "🎀" },
    { name: "Wrapped Present", emoji: "🎁" },
    { name: "Jack-o-lantern", emoji: "🎃" },
    { name: "Christmas Tree", emoji: "🎄" },
    { name: "Fireworks", emoji: "🎆" },
    { name: "Firework Sparkler", emoji: "🎇" },
    { name: "Balloon", emoji: "🎈" },
    { name: "Party Popper", emoji: "🎉" },
    { name: "Confetti Ball", emoji: "🎊" },
    { name: "Tanabata Tree", emoji: "🎋" },
    { name: "Pine Decoration", emoji: "🎍" },
    { name: "Japanese Dolls", emoji: "🎎" },
    { name: "Carp Streamer", emoji: "🎏" },
    { name: "Wind Chime", emoji: "🎐" },
    { name: "Moon Viewing Ceremony", emoji: "🎑" },
    { name: "Military Medal", emoji: "🎖️" },
    { name: "Reminder Ribbon", emoji: "🎗️" },
    { name: "Admission Tickets", emoji: "🎟️" },
    { name: "Fishing Pole And Fish", emoji: "🎣" },
    { name: "Artist Palette", emoji: "🎨" },
    { name: "Ticket", emoji: "🎫" },
    { name: "Performing Arts", emoji: "🎭" },
    { name: "Video Game", emoji: "🎮" },
    { name: "Direct Hit", emoji: "🎯" },
    { name: "Slot Machine", emoji: "🎰" },
    { name: "Billiards", emoji: "🎱" },
    { name: "Game Die", emoji: "🎲" },
    { name: "Bowling", emoji: "🎳" },
    { name: "Flower Playing Cards", emoji: "🎴" },
    { name: "Running Shirt With Sash", emoji: "🎽" },
    { name: "Tennis Racquet And Ball", emoji: "🎾" },
    { name: "Ski And Ski Boot", emoji: "🎿" },
    { name: "Basketball And Hoop", emoji: "🏀" },
    { name: "Sports Medal", emoji: "🏅" },
    { name: "Trophy", emoji: "🏆" },
    { name: "American Football", emoji: "🏈" },
    { name: "Rugby Football", emoji: "🏉" },
    { name: "Cricket Bat And Ball", emoji: "🏏" },
    { name: "Volleyball", emoji: "🏐" },
    { name: "Field Hockey Stick And Ball", emoji: "🏑" },
    { name: "Ice Hockey Stick And Puck", emoji: "🏒" },
    { name: "Table Tennis Paddle And Ball", emoji: "🏓" },
    { name: "Badminton Racquet And Shuttlecock", emoji: "🏸" },
    { name: "Pistol", emoji: "🔫" },
    { name: "Crystal Ball", emoji: "🔮" },
    { name: "Joystick", emoji: "🕹️" },
    { name: "Framed Picture", emoji: "🖼️" },
    { name: "Sled", emoji: "🛷" },
    { name: "Diving Mask", emoji: "🤿" },
    { name: "Goal Net", emoji: "🥅" },
    { name: "First Place Medal", emoji: "🥇" },
    { name: "Second Place Medal", emoji: "🥈" },
    { name: "Third Place Medal", emoji: "🥉" },
    { name: "Boxing Glove", emoji: "🥊" },
    { name: "Martial Arts Uniform", emoji: "🥋" },
    { name: "Curling Stone", emoji: "🥌" },
    { name: "Lacrosse Stick And Ball", emoji: "🥍" },
    { name: "Softball", emoji: "🥎" },
    { name: "Flying Disc", emoji: "🥏" },
    { name: "Red Gift Envelope", emoji: "🧧" },
    { name: "Firecracker", emoji: "🧨" },
    { name: "Jigsaw Puzzle Piece", emoji: "🧩" },
    { name: "Spool Of Thread", emoji: "🧵" },
    { name: "Ball Of Yarn", emoji: "🧶" },
    { name: "Teddy Bear", emoji: "🧸" },
    { name: "Yo-yo", emoji: "🪀" },
    { name: "Kite", emoji: "🪁" },
    { name: "Magic Wand", emoji: "🪄" },
    { name: "Pinata", emoji: "🪅" },
    { name: "Nesting Dolls", emoji: "🪆" },
    { name: "Sewing Needle", emoji: "🪡" },
    { name: "Knot", emoji: "🪢" },
    { name: "Mirror Ball", emoji: "🪩" },
    { name: "Chess Pawn", emoji: "♟️" },
    { name: "Black Spade Suit", emoji: "♠️" },
    { name: "Black Club Suit", emoji: "♣️" },
    { name: "Black Heart Suit", emoji: "♥️" },
    { name: "Black Diamond Suit", emoji: "♦️" },
    { name: "Soccer Ball", emoji: "⚽" },
    { name: "Baseball", emoji: "⚾" },
    { name: "Flag In Hole", emoji: "⛳" },
    { name: "Ice Skate", emoji: "⛸️" },
    { name: "Sparkles", emoji: "✨" },
  ],
  "Travel & Places": [
    { name: "Cyclone", emoji: "🌀" },
    { name: "Foggy", emoji: "🌁" },
    { name: "Closed Umbrella", emoji: "🌂" },
    { name: "Night With Stars", emoji: "🌃" },
    { name: "Sunrise Over Mountains", emoji: "🌄" },
    { name: "Sunrise", emoji: "🌅" },
    { name: "Cityscape At Dusk", emoji: "🌆" },
    { name: "Sunset Over Buildings", emoji: "🌇" },
    { name: "Rainbow", emoji: "🌈" },
    { name: "Bridge At Night", emoji: "🌉" },
    { name: "Water Wave", emoji: "🌊" },
    { name: "Volcano", emoji: "🌋" },
    { name: "Milky Way", emoji: "🌌" },
    { name: "Earth Globe Europe-africa", emoji: "🌍" },
    { name: "Earth Globe Americas", emoji: "🌎" },
    { name: "Earth Globe Asia-australia", emoji: "🌏" },
    { name: "Globe With Meridians", emoji: "🌐" },
    { name: "New Moon Symbol", emoji: "🌑" },
    { name: "Waxing Crescent Moon Symbol", emoji: "🌒" },
    { name: "First Quarter Moon Symbol", emoji: "🌓" },
    { name: "Waxing Gibbous Moon Symbol", emoji: "🌔" },
    { name: "Full Moon Symbol", emoji: "🌕" },
    { name: "Waning Gibbous Moon Symbol", emoji: "🌖" },
    { name: "Last Quarter Moon Symbol", emoji: "🌗" },
    { name: "Waning Crescent Moon Symbol", emoji: "🌘" },
    { name: "Crescent Moon", emoji: "🌙" },
    { name: "New Moon With Face", emoji: "🌚" },
    { name: "First Quarter Moon With Face", emoji: "🌛" },
    { name: "Last Quarter Moon With Face", emoji: "🌜" },
    { name: "Full Moon With Face", emoji: "🌝" },
    { name: "Sun With Face", emoji: "🌞" },
    { name: "Glowing Star", emoji: "🌟" },
    { name: "Shooting Star", emoji: "🌠" },
    { name: "Thermometer", emoji: "🌡️" },
    { name: "Sun Behind Small Cloud", emoji: "🌤️" },
    { name: "Sun Behind Large Cloud", emoji: "🌥️" },
    { name: "Sun Behind Rain Cloud", emoji: "🌦️" },
    { name: "Cloud With Rain", emoji: "🌧️" },
    { name: "Cloud With Snow", emoji: "🌨️" },
    { name: "Cloud With Lightning", emoji: "🌩️" },
    { name: "Tornado", emoji: "🌪️" },
    { name: "Fog", emoji: "🌫️" },
    { name: "Wind Face", emoji: "🌬️" },
    { name: "Carousel Horse", emoji: "🎠" },
    { name: "Ferris Wheel", emoji: "🎡" },
    { name: "Roller Coaster", emoji: "🎢" },
    { name: "Circus Tent", emoji: "🎪" },
    { name: "Motorcycle", emoji: "🏍️" },
    { name: "Racing Car", emoji: "🏎️" },
    { name: "Snow-capped Mountain", emoji: "🏔️" },
    { name: "Camping", emoji: "🏕️" },
    { name: "Beach With Umbrella", emoji: "🏖️" },
    { name: "Building Construction", emoji: "🏗️" },
    { name: "Houses", emoji: "🏘️" },
    { name: "Cityscape", emoji: "🏙️" },
    { name: "Derelict House", emoji: "🏚️" },
    { name: "Classical Building", emoji: "🏛️" },
    { name: "Desert", emoji: "🏜️" },
    { name: "Desert Island", emoji: "🏝️" },
    { name: "National Park", emoji: "🏞️" },
    { name: "Stadium", emoji: "🏟️" },
    { name: "House Building", emoji: "🏠" },
    { name: "House With Garden", emoji: "🏡" },
    { name: "Office Building", emoji: "🏢" },
    { name: "Japanese Post Office", emoji: "🏣" },
    { name: "European Post Office", emoji: "🏤" },
    { name: "Hospital", emoji: "🏥" },
    { name: "Bank", emoji: "🏦" },
    { name: "Hotel", emoji: "🏨" },
    { name: "Love Hotel", emoji: "🏩" },
    { name: "Convenience Store", emoji: "🏪" },
    { name: "School", emoji: "🏫" },
    { name: "Department Store", emoji: "🏬" },
    { name: "Factory", emoji: "🏭" },
    { name: "Japanese Castle", emoji: "🏯" },
    { name: "European Castle", emoji: "🏰" },
    { name: "Barber Pole", emoji: "💈" },
    { name: "Wedding", emoji: "💒" },
    { name: "Droplet", emoji: "💧" },
    { name: "Seat", emoji: "💺" },
    { name: "Fire", emoji: "🔥" },
    { name: "Kaaba", emoji: "🕋" },
    { name: "Mosque", emoji: "🕌" },
    { name: "Synagogue", emoji: "🕍" },
    { name: "Clock Face One Oclock", emoji: "🕐" },
    { name: "Clock Face Two Oclock", emoji: "🕑" },
    { name: "Clock Face Three Oclock", emoji: "🕒" },
    { name: "Clock Face Four Oclock", emoji: "🕓" },
    { name: "Clock Face Five Oclock", emoji: "🕔" },
    { name: "Clock Face Six Oclock", emoji: "🕕" },
    { name: "Clock Face Seven Oclock", emoji: "🕖" },
    { name: "Clock Face Eight Oclock", emoji: "🕗" },
    { name: "Clock Face Nine Oclock", emoji: "🕘" },
    { name: "Clock Face Ten Oclock", emoji: "🕙" },
    { name: "Clock Face Eleven Oclock", emoji: "🕚" },
    { name: "Clock Face Twelve Oclock", emoji: "🕛" },
    { name: "Clock Face One-thirty", emoji: "🕜" },
    { name: "Clock Face Two-thirty", emoji: "🕝" },
    { name: "Clock Face Three-thirty", emoji: "🕞" },
    { name: "Clock Face Four-thirty", emoji: "🕟" },
    { name: "Clock Face Five-thirty", emoji: "🕠" },
    { name: "Clock Face Six-thirty", emoji: "🕡" },
    { name: "Clock Face Seven-thirty", emoji: "🕢" },
    { name: "Clock Face Eight-thirty", emoji: "🕣" },
    { name: "Clock Face Nine-thirty", emoji: "🕤" },
    { name: "Clock Face Ten-thirty", emoji: "🕥" },
    { name: "Clock Face Eleven-thirty", emoji: "🕦" },
    { name: "Clock Face Twelve-thirty", emoji: "🕧" },
    { name: "Mantelpiece Clock", emoji: "🕰️" },
    { name: "World Map", emoji: "🗺️" },
    { name: "Mount Fuji", emoji: "🗻" },
    { name: "Tokyo Tower", emoji: "🗼" },
    { name: "Statue Of Liberty", emoji: "🗽" },
    { name: "Silhouette Of Japan", emoji: "🗾" },
    { name: "Rocket", emoji: "🚀" },
    { name: "Helicopter", emoji: "🚁" },
    { name: "Steam Locomotive", emoji: "🚂" },
    { name: "Railway Car", emoji: "🚃" },
    { name: "High-speed Train", emoji: "🚄" },
    { name: "High-speed Train With Bullet Nose", emoji: "🚅" },
    { name: "Train", emoji: "🚆" },
    { name: "Metro", emoji: "🚇" },
    { name: "Light Rail", emoji: "🚈" },
    { name: "Station", emoji: "🚉" },
    { name: "Tram", emoji: "🚊" },
    { name: "Tram Car", emoji: "🚋" },
    { name: "Bus", emoji: "🚌" },
    { name: "Oncoming Bus", emoji: "🚍" },
    { name: "Trolleybus", emoji: "🚎" },
    { name: "Bus Stop", emoji: "🚏" },
    { name: "Minibus", emoji: "🚐" },
    { name: "Ambulance", emoji: "🚑" },
    { name: "Fire Engine", emoji: "🚒" },
    { name: "Police Car", emoji: "🚓" },
    { name: "Oncoming Police Car", emoji: "🚔" },
    { name: "Taxi", emoji: "🚕" },
    { name: "Oncoming Taxi", emoji: "🚖" },
    { name: "Automobile", emoji: "🚗" },
    { name: "Oncoming Automobile", emoji: "🚘" },
    { name: "Recreational Vehicle", emoji: "🚙" },
    { name: "Delivery Truck", emoji: "🚚" },
    { name: "Articulated Lorry", emoji: "🚛" },
    { name: "Tractor", emoji: "🚜" },
    { name: "Monorail", emoji: "🚝" },
    { name: "Mountain Railway", emoji: "🚞" },
    { name: "Suspension Railway", emoji: "🚟" },
    { name: "Mountain Cableway", emoji: "🚠" },
    { name: "Aerial Tramway", emoji: "🚡" },
    { name: "Ship", emoji: "🚢" },
    { name: "Speedboat", emoji: "🚤" },
    { name: "Horizontal Traffic Light", emoji: "🚥" },
    { name: "Vertical Traffic Light", emoji: "🚦" },
    { name: "Construction Sign", emoji: "🚧" },
    { name: "Police Cars Revolving Light", emoji: "🚨" },
    { name: "Bicycle", emoji: "🚲" },
    { name: "Bellhop Bell", emoji: "🛎️" },
    { name: "Octagonal Sign", emoji: "🛑" },
    { name: "Hindu Temple", emoji: "🛕" },
    { name: "Hut", emoji: "🛖" },
    { name: "Playground Slide", emoji: "🛝" },
    { name: "Wheel", emoji: "🛞" },
    { name: "Ring Buoy", emoji: "🛟" },
    { name: "Oil Drum", emoji: "🛢️" },
    { name: "Motorway", emoji: "🛣️" },
    { name: "Railway Track", emoji: "🛤️" },
    { name: "Motor Boat", emoji: "🛥️" },
    { name: "Small Airplane", emoji: "🛩️" },
    { name: "Airplane Departure", emoji: "🛫" },
    { name: "Airplane Arriving", emoji: "🛬" },
    { name: "Satellite", emoji: "🛰️" },
    { name: "Passenger Ship", emoji: "🛳️" },
    { name: "Scooter", emoji: "🛴" },
    { name: "Motor Scooter", emoji: "🛵" },
    { name: "Canoe", emoji: "🛶" },
    { name: "Flying Saucer", emoji: "🛸" },
    { name: "Skateboard", emoji: "🛹" },
    { name: "Auto Rickshaw", emoji: "🛺" },
    { name: "Pickup Truck", emoji: "🛻" },
    { name: "Roller Skate", emoji: "🛼" },
    { name: "Motorized Wheelchair", emoji: "🦼" },
    { name: "Manual Wheelchair", emoji: "🦽" },
    { name: "Compass", emoji: "🧭" },
    { name: "Brick", emoji: "🧱" },
    { name: "Luggage", emoji: "🧳" },
    { name: "Parachute", emoji: "🪂" },
    { name: "Ringed Planet", emoji: "🪐" },
    { name: "Rock", emoji: "🪨" },
    { name: "Wood", emoji: "🪵" },
    { name: "Watch", emoji: "⌚" },
    { name: "Hourglass", emoji: "⌛" },
    { name: "Alarm Clock", emoji: "⏰" },
    { name: "Stopwatch", emoji: "⏱️" },
    { name: "Timer Clock", emoji: "⏲️" },
    { name: "Hourglass With Flowing Sand", emoji: "⏳" },
    { name: "Black Sun With Rays", emoji: "☀️" },
    { name: "Cloud", emoji: "☁️" },
    { name: "Umbrella", emoji: "☂️" },
    { name: "Snowman", emoji: "☃️" },
    { name: "Comet", emoji: "☄️" },
    { name: "Umbrella With Rain Drops", emoji: "☔" },
    { name: "Hot Springs", emoji: "♨️" },
    { name: "Anchor", emoji: "⚓" },
    { name: "High Voltage Sign", emoji: "⚡" },
    { name: "Snowman Without Snow", emoji: "⛄" },
    { name: "Sun Behind Cloud", emoji: "⛅" },
    { name: "Cloud With Lightning And Rain", emoji: "⛈️" },
    { name: "Shinto Shrine", emoji: "⛩️" },
    { name: "Church", emoji: "⛪" },
    { name: "Mountain", emoji: "⛰️" },
    { name: "Umbrella On Ground", emoji: "⛱️" },
    { name: "Fountain", emoji: "⛲" },
    { name: "Ferry", emoji: "⛴️" },
    { name: "Sailboat", emoji: "⛵" },
    { name: "Tent", emoji: "⛺" },
    { name: "Fuel Pump", emoji: "⛽" },
    { name: "Airplane", emoji: "✈️" },
    { name: "Snowflake", emoji: "❄️" },
    { name: "White Medium Star", emoji: "⭐" },
  ],
  "Food & Drink": [
    { name: "Hot Dog", emoji: "🌭" },
    { name: "Taco", emoji: "🌮" },
    { name: "Burrito", emoji: "🌯" },
    { name: "Chestnut", emoji: "🌰" },
    { name: "Hot Pepper", emoji: "🌶️" },
    { name: "Ear Of Maize", emoji: "🌽" },
    { name: "Brown Mushroom", emoji: "🍄‍🟫" },
    { name: "Tomato", emoji: "🍅" },
    { name: "Aubergine", emoji: "🍆" },
    { name: "Grapes", emoji: "🍇" },
    { name: "Melon", emoji: "🍈" },
    { name: "Watermelon", emoji: "🍉" },
    { name: "Tangerine", emoji: "🍊" },
    { name: "Lime", emoji: "🍋‍🟩" },
    { name: "Lemon", emoji: "🍋" },
    { name: "Banana", emoji: "🍌" },
    { name: "Pineapple", emoji: "🍍" },
    { name: "Red Apple", emoji: "🍎" },
    { name: "Green Apple", emoji: "🍏" },
    { name: "Pear", emoji: "🍐" },
    { name: "Peach", emoji: "🍑" },
    { name: "Cherries", emoji: "🍒" },
    { name: "Strawberry", emoji: "🍓" },
    { name: "Hamburger", emoji: "🍔" },
    { name: "Slice Of Pizza", emoji: "🍕" },
    { name: "Meat On Bone", emoji: "🍖" },
    { name: "Poultry Leg", emoji: "🍗" },
    { name: "Rice Cracker", emoji: "🍘" },
    { name: "Rice Ball", emoji: "🍙" },
    { name: "Cooked Rice", emoji: "🍚" },
    { name: "Curry And Rice", emoji: "🍛" },
    { name: "Steaming Bowl", emoji: "🍜" },
    { name: "Spaghetti", emoji: "🍝" },
    { name: "Bread", emoji: "🍞" },
    { name: "French Fries", emoji: "🍟" },
    { name: "Roasted Sweet Potato", emoji: "🍠" },
    { name: "Dango", emoji: "🍡" },
    { name: "Oden", emoji: "🍢" },
    { name: "Sushi", emoji: "🍣" },
    { name: "Fried Shrimp", emoji: "🍤" },
    { name: "Fish Cake With Swirl Design", emoji: "🍥" },
    { name: "Soft Ice Cream", emoji: "🍦" },
    { name: "Shaved Ice", emoji: "🍧" },
    { name: "Ice Cream", emoji: "🍨" },
    { name: "Doughnut", emoji: "🍩" },
    { name: "Cookie", emoji: "🍪" },
    { name: "Chocolate Bar", emoji: "🍫" },
    { name: "Candy", emoji: "🍬" },
    { name: "Lollipop", emoji: "🍭" },
    { name: "Custard", emoji: "🍮" },
    { name: "Honey Pot", emoji: "🍯" },
    { name: "Shortcake", emoji: "🍰" },
    { name: "Bento Box", emoji: "🍱" },
    { name: "Pot Of Food", emoji: "🍲" },
    { name: "Cooking", emoji: "🍳" },
    { name: "Fork And Knife", emoji: "🍴" },
    { name: "Teacup Without Handle", emoji: "🍵" },
    { name: "Sake Bottle And Cup", emoji: "🍶" },
    { name: "Wine Glass", emoji: "🍷" },
    { name: "Cocktail Glass", emoji: "🍸" },
    { name: "Tropical Drink", emoji: "🍹" },
    { name: "Beer Mug", emoji: "🍺" },
    { name: "Clinking Beer Mugs", emoji: "🍻" },
    { name: "Baby Bottle", emoji: "🍼" },
    { name: "Fork And Knife With Plate", emoji: "🍽️" },
    { name: "Bottle With Popping Cork", emoji: "🍾" },
    { name: "Popcorn", emoji: "🍿" },
    { name: "Birthday Cake", emoji: "🎂" },
    { name: "Amphora", emoji: "🏺" },
    { name: "Hocho", emoji: "🔪" },
    { name: "Clinking Glasses", emoji: "🥂" },
    { name: "Tumbler Glass", emoji: "🥃" },
    { name: "Spoon", emoji: "🥄" },
    { name: "Croissant", emoji: "🥐" },
    { name: "Avocado", emoji: "🥑" },
    { name: "Cucumber", emoji: "🥒" },
    { name: "Bacon", emoji: "🥓" },
    { name: "Potato", emoji: "🥔" },
    { name: "Carrot", emoji: "🥕" },
    { name: "Baguette Bread", emoji: "🥖" },
    { name: "Green Salad", emoji: "🥗" },
    { name: "Shallow Pan Of Food", emoji: "🥘" },
    { name: "Stuffed Flatbread", emoji: "🥙" },
    { name: "Egg", emoji: "🥚" },
    { name: "Glass Of Milk", emoji: "🥛" },
    { name: "Peanuts", emoji: "🥜" },
    { name: "Kiwifruit", emoji: "🥝" },
    { name: "Pancakes", emoji: "🥞" },
    { name: "Dumpling", emoji: "🥟" },
    { name: "Fortune Cookie", emoji: "🥠" },
    { name: "Takeout Box", emoji: "🥡" },
    { name: "Chopsticks", emoji: "🥢" },
    { name: "Bowl With Spoon", emoji: "🥣" },
    { name: "Cup With Straw", emoji: "🥤" },
    { name: "Coconut", emoji: "🥥" },
    { name: "Broccoli", emoji: "🥦" },
    { name: "Pie", emoji: "🥧" },
    { name: "Pretzel", emoji: "🥨" },
    { name: "Cut Of Meat", emoji: "🥩" },
    { name: "Sandwich", emoji: "🥪" },
    { name: "Canned Food", emoji: "🥫" },
    { name: "Leafy Green", emoji: "🥬" },
    { name: "Mango", emoji: "🥭" },
    { name: "Moon Cake", emoji: "🥮" },
    { name: "Bagel", emoji: "🥯" },
    { name: "Crab", emoji: "🦀" },
    { name: "Shrimp", emoji: "🦐" },
    { name: "Squid", emoji: "🦑" },
    { name: "Lobster", emoji: "🦞" },
    { name: "Oyster", emoji: "🦪" },
    { name: "Cheese Wedge", emoji: "🧀" },
    { name: "Cupcake", emoji: "🧁" },
    { name: "Salt Shaker", emoji: "🧂" },
    { name: "Beverage Box", emoji: "🧃" },
    { name: "Garlic", emoji: "🧄" },
    { name: "Onion", emoji: "🧅" },
    { name: "Falafel", emoji: "🧆" },
    { name: "Waffle", emoji: "🧇" },
    { name: "Butter", emoji: "🧈" },
    { name: "Mate Drink", emoji: "🧉" },
    { name: "Ice Cube", emoji: "🧊" },
    { name: "Bubble Tea", emoji: "🧋" },
    { name: "Blueberries", emoji: "🫐" },
    { name: "Bell Pepper", emoji: "🫑" },
    { name: "Olive", emoji: "🫒" },
    { name: "Flatbread", emoji: "🫓" },
    { name: "Tamale", emoji: "🫔" },
    { name: "Fondue", emoji: "🫕" },
    { name: "Teapot", emoji: "🫖" },
    { name: "Pouring Liquid", emoji: "🫗" },
    { name: "Beans", emoji: "🫘" },
    { name: "Jar", emoji: "🫙" },
    { name: "Ginger Root", emoji: "🫚" },
    { name: "Pea Pod", emoji: "🫛" },
    { name: "Hot Beverage", emoji: "☕" },
  ],
  "Animals & Nature": [
    { name: "Seedling", emoji: "🌱" },
    { name: "Evergreen Tree", emoji: "🌲" },
    { name: "Deciduous Tree", emoji: "🌳" },
    { name: "Palm Tree", emoji: "🌴" },
    { name: "Cactus", emoji: "🌵" },
    { name: "Tulip", emoji: "🌷" },
    { name: "Cherry Blossom", emoji: "🌸" },
    { name: "Rose", emoji: "🌹" },
    { name: "Hibiscus", emoji: "🌺" },
    { name: "Sunflower", emoji: "🌻" },
    { name: "Blossom", emoji: "🌼" },
    { name: "Ear Of Rice", emoji: "🌾" },
    { name: "Herb", emoji: "🌿" },
    { name: "Four Leaf Clover", emoji: "🍀" },
    { name: "Maple Leaf", emoji: "🍁" },
    { name: "Fallen Leaf", emoji: "🍂" },
    { name: "Leaf Fluttering In Wind", emoji: "🍃" },
    { name: "Mushroom", emoji: "🍄" },
    { name: "Rosette", emoji: "🏵️" },
    { name: "Rat", emoji: "🐀" },
    { name: "Mouse", emoji: "🐁" },
    { name: "Ox", emoji: "🐂" },
    { name: "Water Buffalo", emoji: "🐃" },
    { name: "Cow", emoji: "🐄" },
    { name: "Tiger", emoji: "🐅" },
    { name: "Leopard", emoji: "🐆" },
    { name: "Rabbit", emoji: "🐇" },
    { name: "Black Cat", emoji: "🐈‍⬛" },
    { name: "Cat", emoji: "🐈" },
    { name: "Dragon", emoji: "🐉" },
    { name: "Crocodile", emoji: "🐊" },
    { name: "Whale", emoji: "🐋" },
    { name: "Snail", emoji: "🐌" },
    { name: "Snake", emoji: "🐍" },
    { name: "Horse", emoji: "🐎" },
    { name: "Ram", emoji: "🐏" },
    { name: "Goat", emoji: "🐐" },
    { name: "Sheep", emoji: "🐑" },
    { name: "Monkey", emoji: "🐒" },
    { name: "Rooster", emoji: "🐓" },
    { name: "Chicken", emoji: "🐔" },
    { name: "Service Dog", emoji: "🐕‍🦺" },
    { name: "Dog", emoji: "🐕" },
    { name: "Pig", emoji: "🐖" },
    { name: "Boar", emoji: "🐗" },
    { name: "Elephant", emoji: "🐘" },
    { name: "Octopus", emoji: "🐙" },
    { name: "Spiral Shell", emoji: "🐚" },
    { name: "Bug", emoji: "🐛" },
    { name: "Ant", emoji: "🐜" },
    { name: "Honeybee", emoji: "🐝" },
    { name: "Lady Beetle", emoji: "🐞" },
    { name: "Fish", emoji: "🐟" },
    { name: "Tropical Fish", emoji: "🐠" },
    { name: "Blowfish", emoji: "🐡" },
    { name: "Turtle", emoji: "🐢" },
    { name: "Hatching Chick", emoji: "🐣" },
    { name: "Baby Chick", emoji: "🐤" },
    { name: "Front-facing Baby Chick", emoji: "🐥" },
    { name: "Phoenix", emoji: "🐦‍🔥" },
    { name: "Black Bird", emoji: "🐦‍⬛" },
    { name: "Bird", emoji: "🐦" },
    { name: "Penguin", emoji: "🐧" },
    { name: "Koala", emoji: "🐨" },
    { name: "Poodle", emoji: "🐩" },
    { name: "Dromedary Camel", emoji: "🐪" },
    { name: "Bactrian Camel", emoji: "🐫" },
    { name: "Dolphin", emoji: "🐬" },
    { name: "Mouse Face", emoji: "🐭" },
    { name: "Cow Face", emoji: "🐮" },
    { name: "Tiger Face", emoji: "🐯" },
    { name: "Rabbit Face", emoji: "🐰" },
    { name: "Cat Face", emoji: "🐱" },
    { name: "Dragon Face", emoji: "🐲" },
    { name: "Spouting Whale", emoji: "🐳" },
    { name: "Horse Face", emoji: "🐴" },
    { name: "Monkey Face", emoji: "🐵" },
    { name: "Dog Face", emoji: "🐶" },
    { name: "Pig Face", emoji: "🐷" },
    { name: "Frog Face", emoji: "🐸" },
    { name: "Hamster Face", emoji: "🐹" },
    { name: "Wolf Face", emoji: "🐺" },
    { name: "Polar Bear", emoji: "🐻‍❄️" },
    { name: "Bear Face", emoji: "🐻" },
    { name: "Panda Face", emoji: "🐼" },
    { name: "Pig Nose", emoji: "🐽" },
    { name: "Paw Prints", emoji: "🐾" },
    { name: "Chipmunk", emoji: "🐿️" },
    { name: "Bouquet", emoji: "💐" },
    { name: "White Flower", emoji: "💮" },
    { name: "Dove", emoji: "🕊️" },
    { name: "Spider", emoji: "🕷️" },
    { name: "Spider Web", emoji: "🕸️" },
    { name: "Wilted Flower", emoji: "🥀" },
    { name: "Lion Face", emoji: "🦁" },
    { name: "Scorpion", emoji: "🦂" },
    { name: "Turkey", emoji: "🦃" },
    { name: "Unicorn Face", emoji: "🦄" },
    { name: "Eagle", emoji: "🦅" },
    { name: "Duck", emoji: "🦆" },
    { name: "Bat", emoji: "🦇" },
    { name: "Shark", emoji: "🦈" },
    { name: "Owl", emoji: "🦉" },
    { name: "Fox Face", emoji: "🦊" },
    { name: "Butterfly", emoji: "🦋" },
    { name: "Deer", emoji: "🦌" },
    { name: "Gorilla", emoji: "🦍" },
    { name: "Lizard", emoji: "🦎" },
    { name: "Rhinoceros", emoji: "🦏" },
    { name: "Giraffe Face", emoji: "🦒" },
    { name: "Zebra Face", emoji: "🦓" },
    { name: "Hedgehog", emoji: "🦔" },
    { name: "Sauropod", emoji: "🦕" },
    { name: "T-rex", emoji: "🦖" },
    { name: "Cricket", emoji: "🦗" },
    { name: "Kangaroo", emoji: "🦘" },
    { name: "Llama", emoji: "🦙" },
    { name: "Peacock", emoji: "🦚" },
    { name: "Hippopotamus", emoji: "🦛" },
    { name: "Parrot", emoji: "🦜" },
    { name: "Raccoon", emoji: "🦝" },
    { name: "Mosquito", emoji: "🦟" },
    { name: "Microbe", emoji: "🦠" },
    { name: "Badger", emoji: "🦡" },
    { name: "Swan", emoji: "🦢" },
    { name: "Mammoth", emoji: "🦣" },
    { name: "Dodo", emoji: "🦤" },
    { name: "Sloth", emoji: "🦥" },
    { name: "Otter", emoji: "🦦" },
    { name: "Orangutan", emoji: "🦧" },
    { name: "Skunk", emoji: "🦨" },
    { name: "Flamingo", emoji: "🦩" },
    { name: "Beaver", emoji: "🦫" },
    { name: "Bison", emoji: "🦬" },
    { name: "Seal", emoji: "🦭" },
    { name: "Guide Dog", emoji: "🦮" },
    { name: "Fly", emoji: "🪰" },
    { name: "Worm", emoji: "🪱" },
    { name: "Beetle", emoji: "🪲" },
    { name: "Cockroach", emoji: "🪳" },
    { name: "Potted Plant", emoji: "🪴" },
    { name: "Feather", emoji: "🪶" },
    { name: "Lotus", emoji: "🪷" },
    { name: "Coral", emoji: "🪸" },
    { name: "Empty Nest", emoji: "🪹" },
    { name: "Nest With Eggs", emoji: "🪺" },
    { name: "Hyacinth", emoji: "🪻" },
    { name: "Jellyfish", emoji: "🪼" },
    { name: "Wing", emoji: "🪽" },
    { name: "Goose", emoji: "🪿" },
    { name: "Moose", emoji: "🫎" },
    { name: "Donkey", emoji: "🫏" },
    { name: "Shamrock", emoji: "☘️" },
  ],
  "People & Body": [
    { name: "Father Christmas", emoji: "🎅" },
    { name: "Snowboarder", emoji: "🏂" },
    { name: "Woman Running", emoji: "🏃‍♀️" },
    { name: "Woman Running Facing Right", emoji: "🏃‍♀️‍➡️" },
    { name: "Man Running", emoji: "🏃‍♂️" },
    { name: "Man Running Facing Right", emoji: "🏃‍♂️‍➡️" },
    { name: "Person Running Facing Right", emoji: "🏃‍➡️" },
    { name: "Runner", emoji: "🏃" },
    { name: "Woman Surfing", emoji: "🏄‍♀️" },
    { name: "Man Surfing", emoji: "🏄‍♂️" },
    { name: "Surfer", emoji: "🏄" },
    { name: "Horse Racing", emoji: "🏇" },
    { name: "Woman Swimming", emoji: "🏊‍♀️" },
    { name: "Man Swimming", emoji: "🏊‍♂️" },
    { name: "Swimmer", emoji: "🏊" },
    { name: "Woman Lifting Weights", emoji: "🏋️‍♀️" },
    { name: "Man Lifting Weights", emoji: "🏋️‍♂️" },
    { name: "Person Lifting Weights", emoji: "🏋️" },
    { name: "Woman Golfing", emoji: "🏌️‍♀️" },
    { name: "Man Golfing", emoji: "🏌️‍♂️" },
    { name: "Person Golfing", emoji: "🏌️" },
    { name: "Eyes", emoji: "👀" },
    { name: "Eye", emoji: "👁️" },
    { name: "Ear", emoji: "👂" },
    { name: "Nose", emoji: "👃" },
    { name: "Mouth", emoji: "👄" },
    { name: "Tongue", emoji: "👅" },
    { name: "White Up Pointing Backhand Index", emoji: "👆" },
    { name: "White Down Pointing Backhand Index", emoji: "👇" },
    { name: "White Left Pointing Backhand Index", emoji: "👈" },
    { name: "White Right Pointing Backhand Index", emoji: "👉" },
    { name: "Fisted Hand Sign", emoji: "👊" },
    { name: "Waving Hand Sign", emoji: "👋" },
    { name: "Ok Hand Sign", emoji: "👌" },
    { name: "Thumbs Up Sign", emoji: "👍" },
    { name: "Thumbs Down Sign", emoji: "👎" },
    { name: "Clapping Hands Sign", emoji: "👏" },
    { name: "Open Hands Sign", emoji: "👐" },
    { name: "Footprints", emoji: "👣" },
    { name: "Bust In Silhouette", emoji: "👤" },
    { name: "Busts In Silhouette", emoji: "👥" },
    { name: "Boy", emoji: "👦" },
    { name: "Girl", emoji: "👧" },
    { name: "Man Farmer", emoji: "👨‍🌾" },
    { name: "Man Cook", emoji: "👨‍🍳" },
    { name: "Man Feeding Baby", emoji: "👨‍🍼" },
    { name: "Man Student", emoji: "👨‍🎓" },
    { name: "Man Singer", emoji: "👨‍🎤" },
    { name: "Man Artist", emoji: "👨‍🎨" },
    { name: "Man Teacher", emoji: "👨‍🏫" },
    { name: "Man Factory Worker", emoji: "👨‍🏭" },
    { name: "Family: Man, Boy, Boy", emoji: "👨‍👦‍👦" },
    { name: "Family: Man, Boy", emoji: "👨‍👦" },
    { name: "Family: Man, Girl, Boy", emoji: "👨‍👧‍👦" },
    { name: "Family: Man, Girl, Girl", emoji: "👨‍👧‍👧" },
    { name: "Family: Man, Girl", emoji: "👨‍👧" },
    { name: "Family: Man, Man, Boy", emoji: "👨‍👨‍👦" },
    { name: "Family: Man, Man, Boy, Boy", emoji: "👨‍👨‍👦‍👦" },
    { name: "Family: Man, Man, Girl", emoji: "👨‍👨‍👧" },
    { name: "Family: Man, Man, Girl, Boy", emoji: "👨‍👨‍👧‍👦" },
    { name: "Family: Man, Man, Girl, Girl", emoji: "👨‍👨‍👧‍👧" },
    { name: "Family: Man, Woman, Boy", emoji: "👨‍👩‍👦" },
    { name: "Family: Man, Woman, Boy, Boy", emoji: "👨‍👩‍👦‍👦" },
    { name: "Family: Man, Woman, Girl", emoji: "👨‍👩‍👧" },
    { name: "Family: Man, Woman, Girl, Boy", emoji: "👨‍👩‍👧‍👦" },
    { name: "Family: Man, Woman, Girl, Girl", emoji: "👨‍👩‍👧‍👧" },
    { name: "Man Technologist", emoji: "👨‍💻" },
    { name: "Man Office Worker", emoji: "👨‍💼" },
    { name: "Man Mechanic", emoji: "👨‍🔧" },
    { name: "Man Scientist", emoji: "👨‍🔬" },
    { name: "Man Astronaut", emoji: "👨‍🚀" },
    { name: "Man Firefighter", emoji: "👨‍🚒" },
    { name: "Man With White Cane Facing Right", emoji: "👨‍🦯‍➡️" },
    { name: "Man With White Cane", emoji: "👨‍🦯" },
    { name: "Man: Red Hair", emoji: "👨‍🦰" },
    { name: "Man: Curly Hair", emoji: "👨‍🦱" },
    { name: "Man: Bald", emoji: "👨‍🦲" },
    { name: "Man: White Hair", emoji: "👨‍🦳" },
    { name: "Man In Motorized Wheelchair Facing Right", emoji: "👨‍🦼‍➡️" },
    { name: "Man In Motorized Wheelchair", emoji: "👨‍🦼" },
    { name: "Man In Manual Wheelchair Facing Right", emoji: "👨‍🦽‍➡️" },
    { name: "Man In Manual Wheelchair", emoji: "👨‍🦽" },
    { name: "Man Health Worker", emoji: "👨‍⚕️" },
    { name: "Man Judge", emoji: "👨‍⚖️" },
    { name: "Man Pilot", emoji: "👨‍✈️" },
    { name: "Couple With Heart: Man, Man", emoji: "👨‍❤️‍👨" },
    { name: "Kiss: Man, Man", emoji: "👨‍❤️‍💋‍👨" },
    { name: "Man", emoji: "👨" },
    { name: "Woman Farmer", emoji: "👩‍🌾" },
    { name: "Woman Cook", emoji: "👩‍🍳" },
    { name: "Woman Feeding Baby", emoji: "👩‍🍼" },
    { name: "Woman Student", emoji: "👩‍🎓" },
    { name: "Woman Singer", emoji: "👩‍🎤" },
    { name: "Woman Artist", emoji: "👩‍🎨" },
    { name: "Woman Teacher", emoji: "👩‍🏫" },
    { name: "Woman Factory Worker", emoji: "👩‍🏭" },
    { name: "Family: Woman, Boy, Boy", emoji: "👩‍👦‍👦" },
    { name: "Family: Woman, Boy", emoji: "👩‍👦" },
    { name: "Family: Woman, Girl, Boy", emoji: "👩‍👧‍👦" },
    { name: "Family: Woman, Girl, Girl", emoji: "👩‍👧‍👧" },
    { name: "Family: Woman, Girl", emoji: "👩‍👧" },
    { name: "Family: Woman, Woman, Boy", emoji: "👩‍👩‍👦" },
    { name: "Family: Woman, Woman, Boy, Boy", emoji: "👩‍👩‍👦‍👦" },
    { name: "Family: Woman, Woman, Girl", emoji: "👩‍👩‍👧" },
    { name: "Family: Woman, Woman, Girl, Boy", emoji: "👩‍👩‍👧‍👦" },
    { name: "Family: Woman, Woman, Girl, Girl", emoji: "👩‍👩‍👧‍👧" },
    { name: "Woman Technologist", emoji: "👩‍💻" },
    { name: "Woman Office Worker", emoji: "👩‍💼" },
    { name: "Woman Mechanic", emoji: "👩‍🔧" },
    { name: "Woman Scientist", emoji: "👩‍🔬" },
    { name: "Woman Astronaut", emoji: "👩‍🚀" },
    { name: "Woman Firefighter", emoji: "👩‍🚒" },
    { name: "Woman With White Cane Facing Right", emoji: "👩‍🦯‍➡️" },
    { name: "Woman With White Cane", emoji: "👩‍🦯" },
    { name: "Woman: Red Hair", emoji: "👩‍🦰" },
    { name: "Woman: Curly Hair", emoji: "👩‍🦱" },
    { name: "Woman: Bald", emoji: "👩‍🦲" },
    { name: "Woman: White Hair", emoji: "👩‍🦳" },
    { name: "Woman In Motorized Wheelchair Facing Right", emoji: "👩‍🦼‍➡️" },
    { name: "Woman In Motorized Wheelchair", emoji: "👩‍🦼" },
    { name: "Woman In Manual Wheelchair Facing Right", emoji: "👩‍🦽‍➡️" },
    { name: "Woman In Manual Wheelchair", emoji: "👩‍🦽" },
    { name: "Woman Health Worker", emoji: "👩‍⚕️" },
    { name: "Woman Judge", emoji: "👩‍⚖️" },
    { name: "Woman Pilot", emoji: "👩‍✈️" },
    { name: "Couple With Heart: Woman, Man", emoji: "👩‍❤️‍👨" },
    { name: "Couple With Heart: Woman, Woman", emoji: "👩‍❤️‍👩" },
    { name: "Kiss: Woman, Man", emoji: "👩‍❤️‍💋‍👨" },
    { name: "Kiss: Woman, Woman", emoji: "👩‍❤️‍💋‍👩" },
    { name: "Woman", emoji: "👩" },
    { name: "Family", emoji: "👪" },
    { name: "Man And Woman Holding Hands", emoji: "👫" },
    { name: "Two Men Holding Hands", emoji: "👬" },
    { name: "Two Women Holding Hands", emoji: "👭" },
    { name: "Woman Police Officer", emoji: "👮‍♀️" },
    { name: "Man Police Officer", emoji: "👮‍♂️" },
    { name: "Police Officer", emoji: "👮" },
    { name: "Women With Bunny Ears", emoji: "👯‍♀️" },
    { name: "Men With Bunny Ears", emoji: "👯‍♂️" },
    { name: "Woman With Bunny Ears", emoji: "👯" },
    { name: "Woman With Veil", emoji: "👰‍♀️" },
    { name: "Man With Veil", emoji: "👰‍♂️" },
    { name: "Bride With Veil", emoji: "👰" },
    { name: "Woman: Blond Hair", emoji: "👱‍♀️" },
    { name: "Man: Blond Hair", emoji: "👱‍♂️" },
    { name: "Person With Blond Hair", emoji: "👱" },
    { name: "Man With Gua Pi Mao", emoji: "👲" },
    { name: "Woman Wearing Turban", emoji: "👳‍♀️" },
    { name: "Man Wearing Turban", emoji: "👳‍♂️" },
    { name: "Man With Turban", emoji: "👳" },
    { name: "Older Man", emoji: "👴" },
    { name: "Older Woman", emoji: "👵" },
    { name: "Baby", emoji: "👶" },
    { name: "Woman Construction Worker", emoji: "👷‍♀️" },
    { name: "Man Construction Worker", emoji: "👷‍♂️" },
    { name: "Construction Worker", emoji: "👷" },
    { name: "Princess", emoji: "👸" },
    { name: "Baby Angel", emoji: "👼" },
    { name: "Woman Tipping Hand", emoji: "💁‍♀️" },
    { name: "Man Tipping Hand", emoji: "💁‍♂️" },
    { name: "Information Desk Person", emoji: "💁" },
    { name: "Woman Guard", emoji: "💂‍♀️" },
    { name: "Man Guard", emoji: "💂‍♂️" },
    { name: "Guardsman", emoji: "💂" },
    { name: "Dancer", emoji: "💃" },
    { name: "Nail Polish", emoji: "💅" },
    { name: "Woman Getting Massage", emoji: "💆‍♀️" },
    { name: "Man Getting Massage", emoji: "💆‍♂️" },
    { name: "Face Massage", emoji: "💆" },
    { name: "Woman Getting Haircut", emoji: "💇‍♀️" },
    { name: "Man Getting Haircut", emoji: "💇‍♂️" },
    { name: "Haircut", emoji: "💇" },
    { name: "Kiss", emoji: "💏" },
    { name: "Couple With Heart", emoji: "💑" },
    { name: "Flexed Biceps", emoji: "💪" },
    { name: "Person In Suit Levitating", emoji: "🕴️" },
    { name: "Woman Detective", emoji: "🕵️‍♀️" },
    { name: "Man Detective", emoji: "🕵️‍♂️" },
    { name: "Detective", emoji: "🕵️" },
    { name: "Man Dancing", emoji: "🕺" },
    { name: "Hand With Fingers Splayed", emoji: "🖐️" },
    { name: "Reversed Hand With Middle Finger Extended", emoji: "🖕" },
    {
      name: "Raised Hand With Part Between Middle And Ring Fingers",
      emoji: "🖖",
    },
    { name: "Speaking Head", emoji: "🗣️" },
    { name: "Woman Gesturing No", emoji: "🙅‍♀️" },
    { name: "Man Gesturing No", emoji: "🙅‍♂️" },
    { name: "Face With No Good Gesture", emoji: "🙅" },
    { name: "Woman Gesturing Ok", emoji: "🙆‍♀️" },
    { name: "Man Gesturing Ok", emoji: "🙆‍♂️" },
    { name: "Face With Ok Gesture", emoji: "🙆" },
    { name: "Woman Bowing", emoji: "🙇‍♀️" },
    { name: "Man Bowing", emoji: "🙇‍♂️" },
    { name: "Person Bowing Deeply", emoji: "🙇" },
    { name: "Woman Raising Hand", emoji: "🙋‍♀️" },
    { name: "Man Raising Hand", emoji: "🙋‍♂️" },
    { name: "Happy Person Raising One Hand", emoji: "🙋" },
    { name: "Person Raising Both Hands In Celebration", emoji: "🙌" },
    { name: "Woman Frowning", emoji: "🙍‍♀️" },
    { name: "Man Frowning", emoji: "🙍‍♂️" },
    { name: "Person Frowning", emoji: "🙍" },
    { name: "Woman Pouting", emoji: "🙎‍♀️" },
    { name: "Man Pouting", emoji: "🙎‍♂️" },
    { name: "Person With Pouting Face", emoji: "🙎" },
    { name: "Person With Folded Hands", emoji: "🙏" },
    { name: "Woman Rowing Boat", emoji: "🚣‍♀️" },
    { name: "Man Rowing Boat", emoji: "🚣‍♂️" },
    { name: "Rowboat", emoji: "🚣" },
    { name: "Woman Biking", emoji: "🚴‍♀️" },
    { name: "Man Biking", emoji: "🚴‍♂️" },
    { name: "Bicyclist", emoji: "🚴" },
    { name: "Woman Mountain Biking", emoji: "🚵‍♀️" },
    { name: "Man Mountain Biking", emoji: "🚵‍♂️" },
    { name: "Mountain Bicyclist", emoji: "🚵" },
    { name: "Woman Walking", emoji: "🚶‍♀️" },
    { name: "Woman Walking Facing Right", emoji: "🚶‍♀️‍➡️" },
    { name: "Man Walking", emoji: "🚶‍♂️" },
    { name: "Man Walking Facing Right", emoji: "🚶‍♂️‍➡️" },
    { name: "Person Walking Facing Right", emoji: "🚶‍➡️" },
    { name: "Pedestrian", emoji: "🚶" },
    { name: "Bath", emoji: "🛀" },
    { name: "Sleeping Accommodation", emoji: "🛌" },
    { name: "Pinched Fingers", emoji: "🤌" },
    { name: "Pinching Hand", emoji: "🤏" },
    { name: "Sign Of The Horns", emoji: "🤘" },
    { name: "Call Me Hand", emoji: "🤙" },
    { name: "Raised Back Of Hand", emoji: "🤚" },
    { name: "Left-facing Fist", emoji: "🤛" },
    { name: "Right-facing Fist", emoji: "🤜" },
    { name: "Handshake", emoji: "🤝" },
    { name: "Hand With Index And Middle Fingers Crossed", emoji: "🤞" },
    { name: "I Love You Hand Sign", emoji: "🤟" },
    { name: "Woman Facepalming", emoji: "🤦‍♀️" },
    { name: "Man Facepalming", emoji: "🤦‍♂️" },
    { name: "Face Palm", emoji: "🤦" },
    { name: "Pregnant Woman", emoji: "🤰" },
    { name: "Breast-feeding", emoji: "🤱" },
    { name: "Palms Up Together", emoji: "🤲" },
    { name: "Selfie", emoji: "🤳" },
    { name: "Prince", emoji: "🤴" },
    { name: "Woman In Tuxedo", emoji: "🤵‍♀️" },
    { name: "Man In Tuxedo", emoji: "🤵‍♂️" },
    { name: "Man In Tuxedo", emoji: "🤵" },
    { name: "Mother Christmas", emoji: "🤶" },
    { name: "Woman Shrugging", emoji: "🤷‍♀️" },
    { name: "Man Shrugging", emoji: "🤷‍♂️" },
    { name: "Shrug", emoji: "🤷" },
    { name: "Woman Cartwheeling", emoji: "🤸‍♀️" },
    { name: "Man Cartwheeling", emoji: "🤸‍♂️" },
    { name: "Person Doing Cartwheel", emoji: "🤸" },
    { name: "Woman Juggling", emoji: "🤹‍♀️" },
    { name: "Man Juggling", emoji: "🤹‍♂️" },
    { name: "Juggling", emoji: "🤹" },
    { name: "Fencer", emoji: "🤺" },
    { name: "Women Wrestling", emoji: "🤼‍♀️" },
    { name: "Men Wrestling", emoji: "🤼‍♂️" },
    { name: "Wrestlers", emoji: "🤼" },
    { name: "Woman Playing Water Polo", emoji: "🤽‍♀️" },
    { name: "Man Playing Water Polo", emoji: "🤽‍♂️" },
    { name: "Water Polo", emoji: "🤽" },
    { name: "Woman Playing Handball", emoji: "🤾‍♀️" },
    { name: "Man Playing Handball", emoji: "🤾‍♂️" },
    { name: "Handball", emoji: "🤾" },
    { name: "Ninja", emoji: "🥷" },
    { name: "Bone", emoji: "🦴" },
    { name: "Leg", emoji: "🦵" },
    { name: "Foot", emoji: "🦶" },
    { name: "Tooth", emoji: "🦷" },
    { name: "Woman Superhero", emoji: "🦸‍♀️" },
    { name: "Man Superhero", emoji: "🦸‍♂️" },
    { name: "Superhero", emoji: "🦸" },
    { name: "Woman Supervillain", emoji: "🦹‍♀️" },
    { name: "Man Supervillain", emoji: "🦹‍♂️" },
    { name: "Supervillain", emoji: "🦹" },
    { name: "Ear With Hearing Aid", emoji: "🦻" },
    { name: "Mechanical Arm", emoji: "🦾" },
    { name: "Mechanical Leg", emoji: "🦿" },
    { name: "Troll", emoji: "🧌" },
    { name: "Woman Standing", emoji: "🧍‍♀️" },
    { name: "Man Standing", emoji: "🧍‍♂️" },
    { name: "Standing Person", emoji: "🧍" },
    { name: "Woman Kneeling", emoji: "🧎‍♀️" },
    { name: "Woman Kneeling Facing Right", emoji: "🧎‍♀️‍➡️" },
    { name: "Man Kneeling", emoji: "🧎‍♂️" },
    { name: "Man Kneeling Facing Right", emoji: "🧎‍♂️‍➡️" },
    { name: "Person Kneeling Facing Right", emoji: "🧎‍➡️" },
    { name: "Kneeling Person", emoji: "🧎" },
    { name: "Deaf Woman", emoji: "🧏‍♀️" },
    { name: "Deaf Man", emoji: "🧏‍♂️" },
    { name: "Deaf Person", emoji: "🧏" },
    { name: "Farmer", emoji: "🧑‍🌾" },
    { name: "Cook", emoji: "🧑‍🍳" },
    { name: "Person Feeding Baby", emoji: "🧑‍🍼" },
    { name: "Mx Claus", emoji: "🧑‍🎄" },
    { name: "Student", emoji: "🧑‍🎓" },
    { name: "Singer", emoji: "🧑‍🎤" },
    { name: "Artist", emoji: "🧑‍🎨" },
    { name: "Teacher", emoji: "🧑‍🏫" },
    { name: "Factory Worker", emoji: "🧑‍🏭" },
    { name: "Technologist", emoji: "🧑‍💻" },
    { name: "Office Worker", emoji: "🧑‍💼" },
    { name: "Mechanic", emoji: "🧑‍🔧" },
    { name: "Scientist", emoji: "🧑‍🔬" },
    { name: "Astronaut", emoji: "🧑‍🚀" },
    { name: "Firefighter", emoji: "🧑‍🚒" },
    { name: "People Holding Hands", emoji: "🧑‍🤝‍🧑" },
    { name: "Person With White Cane Facing Right", emoji: "🧑‍🦯‍➡️" },
    { name: "Person With White Cane", emoji: "🧑‍🦯" },
    { name: "Person: Red Hair", emoji: "🧑‍🦰" },
    { name: "Person: Curly Hair", emoji: "🧑‍🦱" },
    { name: "Person: Bald", emoji: "🧑‍🦲" },
    { name: "Person: White Hair", emoji: "🧑‍🦳" },
    { name: "Person In Motorized Wheelchair Facing Right", emoji: "🧑‍🦼‍➡️" },
    { name: "Person In Motorized Wheelchair", emoji: "🧑‍🦼" },
    { name: "Person In Manual Wheelchair Facing Right", emoji: "🧑‍🦽‍➡️" },
    { name: "Person In Manual Wheelchair", emoji: "🧑‍🦽" },
    { name: "Family: Adult, Adult, Child", emoji: "🧑‍🧑‍🧒" },
    { name: "Family: Adult, Adult, Child, Child", emoji: "🧑‍🧑‍🧒‍🧒" },
    { name: "Family: Adult, Child, Child", emoji: "🧑‍🧒‍🧒" },
    { name: "Family: Adult, Child", emoji: "🧑‍🧒" },
    { name: "Health Worker", emoji: "🧑‍⚕️" },
    { name: "Judge", emoji: "🧑‍⚖️" },
    { name: "Pilot", emoji: "🧑‍✈️" },
    { name: "Adult", emoji: "🧑" },
    { name: "Child", emoji: "🧒" },
    { name: "Older Adult", emoji: "🧓" },
    { name: "Woman: Beard", emoji: "🧔‍♀️" },
    { name: "Man: Beard", emoji: "🧔‍♂️" },
    { name: "Bearded Person", emoji: "🧔" },
    { name: "Person With Headscarf", emoji: "🧕" },
    { name: "Woman In Steamy Room", emoji: "🧖‍♀️" },
    { name: "Man In Steamy Room", emoji: "🧖‍♂️" },
    { name: "Person In Steamy Room", emoji: "🧖" },
    { name: "Woman Climbing", emoji: "🧗‍♀️" },
    { name: "Man Climbing", emoji: "🧗‍♂️" },
    { name: "Person Climbing", emoji: "🧗" },
    { name: "Woman In Lotus Position", emoji: "🧘‍♀️" },
    { name: "Man In Lotus Position", emoji: "🧘‍♂️" },
    { name: "Person In Lotus Position", emoji: "🧘" },
    { name: "Woman Mage", emoji: "🧙‍♀️" },
    { name: "Man Mage", emoji: "🧙‍♂️" },
    { name: "Mage", emoji: "🧙" },
    { name: "Woman Fairy", emoji: "🧚‍♀️" },
    { name: "Man Fairy", emoji: "🧚‍♂️" },
    { name: "Fairy", emoji: "🧚" },
    { name: "Woman Vampire", emoji: "🧛‍♀️" },
    { name: "Man Vampire", emoji: "🧛‍♂️" },
    { name: "Vampire", emoji: "🧛" },
    { name: "Mermaid", emoji: "🧜‍♀️" },
    { name: "Merman", emoji: "🧜‍♂️" },
    { name: "Merperson", emoji: "🧜" },
    { name: "Woman Elf", emoji: "🧝‍♀️" },
    { name: "Man Elf", emoji: "🧝‍♂️" },
    { name: "Elf", emoji: "🧝" },
    { name: "Woman Genie", emoji: "🧞‍♀️" },
    { name: "Man Genie", emoji: "🧞‍♂️" },
    { name: "Genie", emoji: "🧞" },
    { name: "Woman Zombie", emoji: "🧟‍♀️" },
    { name: "Man Zombie", emoji: "🧟‍♂️" },
    { name: "Zombie", emoji: "🧟" },
    { name: "Brain", emoji: "🧠" },
    { name: "Anatomical Heart", emoji: "🫀" },
    { name: "Lungs", emoji: "🫁" },
    { name: "People Hugging", emoji: "🫂" },
    { name: "Pregnant Man", emoji: "🫃" },
    { name: "Pregnant Person", emoji: "🫄" },
    { name: "Person With Crown", emoji: "🫅" },
    { name: "Biting Lip", emoji: "🫦" },
    { name: "Hand With Index Finger And Thumb Crossed", emoji: "🫰" },
    { name: "Rightwards Hand", emoji: "🫱" },
    { name: "Leftwards Hand", emoji: "🫲" },
    { name: "Palm Down Hand", emoji: "🫳" },
    { name: "Palm Up Hand", emoji: "🫴" },
    { name: "Index Pointing At The Viewer", emoji: "🫵" },
    { name: "Heart Hands", emoji: "🫶" },
    { name: "Leftwards Pushing Hand", emoji: "🫷" },
    { name: "Rightwards Pushing Hand", emoji: "🫸" },
    { name: "White Up Pointing Index", emoji: "☝️" },
    { name: "Skier", emoji: "⛷️" },
    { name: "Woman Bouncing Ball", emoji: "⛹️‍♀️" },
    { name: "Man Bouncing Ball", emoji: "⛹️‍♂️" },
    { name: "Person Bouncing Ball", emoji: "⛹️" },
    { name: "Raised Fist", emoji: "✊" },
    { name: "Raised Hand", emoji: "✋" },
    { name: "Victory Hand", emoji: "✌️" },
    { name: "Writing Hand", emoji: "✍️" },
  ],
  Objects: [
    { name: "School Satchel", emoji: "🎒" },
    { name: "Graduation Cap", emoji: "🎓" },
    { name: "Studio Microphone", emoji: "🎙️" },
    { name: "Level Slider", emoji: "🎚️" },
    { name: "Control Knobs", emoji: "🎛️" },
    { name: "Film Frames", emoji: "🎞️" },
    { name: "Microphone", emoji: "🎤" },
    { name: "Movie Camera", emoji: "🎥" },
    { name: "Headphone", emoji: "🎧" },
    { name: "Top Hat", emoji: "🎩" },
    { name: "Clapper Board", emoji: "🎬" },
    { name: "Musical Note", emoji: "🎵" },
    { name: "Multiple Musical Notes", emoji: "🎶" },
    { name: "Saxophone", emoji: "🎷" },
    { name: "Guitar", emoji: "🎸" },
    { name: "Musical Keyboard", emoji: "🎹" },
    { name: "Trumpet", emoji: "🎺" },
    { name: "Violin", emoji: "🎻" },
    { name: "Musical Score", emoji: "🎼" },
    { name: "Izakaya Lantern", emoji: "🏮" },
    { name: "Label", emoji: "🏷️" },
    { name: "Bow And Arrow", emoji: "🏹" },
    { name: "Crown", emoji: "👑" },
    { name: "Womans Hat", emoji: "👒" },
    { name: "Eyeglasses", emoji: "👓" },
    { name: "Necktie", emoji: "👔" },
    { name: "T-shirt", emoji: "👕" },
    { name: "Jeans", emoji: "👖" },
    { name: "Dress", emoji: "👗" },
    { name: "Kimono", emoji: "👘" },
    { name: "Bikini", emoji: "👙" },
    { name: "Womans Clothes", emoji: "👚" },
    { name: "Purse", emoji: "👛" },
    { name: "Handbag", emoji: "👜" },
    { name: "Pouch", emoji: "👝" },
    { name: "Mans Shoe", emoji: "👞" },
    { name: "Athletic Shoe", emoji: "👟" },
    { name: "High-heeled Shoe", emoji: "👠" },
    { name: "Womans Sandal", emoji: "👡" },
    { name: "Womans Boots", emoji: "👢" },
    { name: "Lipstick", emoji: "💄" },
    { name: "Syringe", emoji: "💉" },
    { name: "Pill", emoji: "💊" },
    { name: "Ring", emoji: "💍" },
    { name: "Gem Stone", emoji: "💎" },
    { name: "Electric Light Bulb", emoji: "💡" },
    { name: "Bomb", emoji: "💣" },
    { name: "Money Bag", emoji: "💰" },
    { name: "Credit Card", emoji: "💳" },
    { name: "Banknote With Yen Sign", emoji: "💴" },
    { name: "Banknote With Dollar Sign", emoji: "💵" },
    { name: "Banknote With Euro Sign", emoji: "💶" },
    { name: "Banknote With Pound Sign", emoji: "💷" },
    { name: "Money With Wings", emoji: "💸" },
    { name: "Chart With Upwards Trend And Yen Sign", emoji: "💹" },
    { name: "Personal Computer", emoji: "💻" },
    { name: "Briefcase", emoji: "💼" },
    { name: "Minidisc", emoji: "💽" },
    { name: "Floppy Disk", emoji: "💾" },
    { name: "Optical Disc", emoji: "💿" },
    { name: "Dvd", emoji: "📀" },
    { name: "File Folder", emoji: "📁" },
    { name: "Open File Folder", emoji: "📂" },
    { name: "Page With Curl", emoji: "📃" },
    { name: "Page Facing Up", emoji: "📄" },
    { name: "Calendar", emoji: "📅" },
    { name: "Tear-off Calendar", emoji: "📆" },
    { name: "Card Index", emoji: "📇" },
    { name: "Chart With Upwards Trend", emoji: "📈" },
    { name: "Chart With Downwards Trend", emoji: "📉" },
    { name: "Bar Chart", emoji: "📊" },
    { name: "Clipboard", emoji: "📋" },
    { name: "Pushpin", emoji: "📌" },
    { name: "Round Pushpin", emoji: "📍" },
    { name: "Paperclip", emoji: "📎" },
    { name: "Straight Ruler", emoji: "📏" },
    { name: "Triangular Ruler", emoji: "📐" },
    { name: "Bookmark Tabs", emoji: "📑" },
    { name: "Ledger", emoji: "📒" },
    { name: "Notebook", emoji: "📓" },
    { name: "Notebook With Decorative Cover", emoji: "📔" },
    { name: "Closed Book", emoji: "📕" },
    { name: "Open Book", emoji: "📖" },
    { name: "Green Book", emoji: "📗" },
    { name: "Blue Book", emoji: "📘" },
    { name: "Orange Book", emoji: "📙" },
    { name: "Books", emoji: "📚" },
    { name: "Scroll", emoji: "📜" },
    { name: "Memo", emoji: "📝" },
    { name: "Telephone Receiver", emoji: "📞" },
    { name: "Pager", emoji: "📟" },
    { name: "Fax Machine", emoji: "📠" },
    { name: "Satellite Antenna", emoji: "📡" },
    { name: "Public Address Loudspeaker", emoji: "📢" },
    { name: "Cheering Megaphone", emoji: "📣" },
    { name: "Outbox Tray", emoji: "📤" },
    { name: "Inbox Tray", emoji: "📥" },
    { name: "Package", emoji: "📦" },
    { name: "E-mail Symbol", emoji: "📧" },
    { name: "Incoming Envelope", emoji: "📨" },
    { name: "Envelope With Downwards Arrow Above", emoji: "📩" },
    { name: "Closed Mailbox With Lowered Flag", emoji: "📪" },
    { name: "Closed Mailbox With Raised Flag", emoji: "📫" },
    { name: "Open Mailbox With Raised Flag", emoji: "📬" },
    { name: "Open Mailbox With Lowered Flag", emoji: "📭" },
    { name: "Postbox", emoji: "📮" },
    { name: "Postal Horn", emoji: "📯" },
    { name: "Newspaper", emoji: "📰" },
    { name: "Mobile Phone", emoji: "📱" },
    { name: "Mobile Phone With Rightwards Arrow At Left", emoji: "📲" },
    { name: "Camera", emoji: "📷" },
    { name: "Camera With Flash", emoji: "📸" },
    { name: "Video Camera", emoji: "📹" },
    { name: "Television", emoji: "📺" },
    { name: "Radio", emoji: "📻" },
    { name: "Videocassette", emoji: "📼" },
    { name: "Film Projector", emoji: "📽️" },
    { name: "Prayer Beads", emoji: "📿" },
    { name: "Speaker With Cancellation Stroke", emoji: "🔇" },
    { name: "Speaker", emoji: "🔈" },
    { name: "Speaker With One Sound Wave", emoji: "🔉" },
    { name: "Speaker With Three Sound Waves", emoji: "🔊" },
    { name: "Battery", emoji: "🔋" },
    { name: "Electric Plug", emoji: "🔌" },
    { name: "Left-pointing Magnifying Glass", emoji: "🔍" },
    { name: "Right-pointing Magnifying Glass", emoji: "🔎" },
    { name: "Lock With Ink Pen", emoji: "🔏" },
    { name: "Closed Lock With Key", emoji: "🔐" },
    { name: "Key", emoji: "🔑" },
    { name: "Lock", emoji: "🔒" },
    { name: "Open Lock", emoji: "🔓" },
    { name: "Bell", emoji: "🔔" },
    { name: "Bell With Cancellation Stroke", emoji: "🔕" },
    { name: "Bookmark", emoji: "🔖" },
    { name: "Link Symbol", emoji: "🔗" },
    { name: "Electric Torch", emoji: "🔦" },
    { name: "Wrench", emoji: "🔧" },
    { name: "Hammer", emoji: "🔨" },
    { name: "Nut And Bolt", emoji: "🔩" },
    { name: "Microscope", emoji: "🔬" },
    { name: "Telescope", emoji: "🔭" },
    { name: "Candle", emoji: "🕯️" },
    { name: "Sunglasses", emoji: "🕶️" },
    { name: "Linked Paperclips", emoji: "🖇️" },
    { name: "Pen", emoji: "🖊️" },
    { name: "Fountain Pen", emoji: "🖋️" },
    { name: "Paintbrush", emoji: "🖌️" },
    { name: "Crayon", emoji: "🖍️" },
    { name: "Desktop Computer", emoji: "🖥️" },
    { name: "Printer", emoji: "🖨️" },
    { name: "Computer Mouse", emoji: "🖱️" },
    { name: "Trackball", emoji: "🖲️" },
    { name: "Card Index Dividers", emoji: "🗂️" },
    { name: "Card File Box", emoji: "🗃️" },
    { name: "File Cabinet", emoji: "🗄️" },
    { name: "Wastebasket", emoji: "🗑️" },
    { name: "Spiral Notepad", emoji: "🗒️" },
    { name: "Spiral Calendar", emoji: "🗓️" },
    { name: "Clamp", emoji: "🗜️" },
    { name: "Old Key", emoji: "🗝️" },
    { name: "Rolled-up Newspaper", emoji: "🗞️" },
    { name: "Dagger", emoji: "🗡️" },
    { name: "Ballot Box With Ballot", emoji: "🗳️" },
    { name: "Moyai", emoji: "🗿" },
    { name: "Door", emoji: "🚪" },
    { name: "Smoking Symbol", emoji: "🚬" },
    { name: "Toilet", emoji: "🚽" },
    { name: "Shower", emoji: "🚿" },
    { name: "Bathtub", emoji: "🛁" },
    { name: "Couch And Lamp", emoji: "🛋️" },
    { name: "Shopping Bags", emoji: "🛍️" },
    { name: "Bed", emoji: "🛏️" },
    { name: "Shopping Trolley", emoji: "🛒" },
    { name: "Elevator", emoji: "🛗" },
    { name: "Hammer And Wrench", emoji: "🛠️" },
    { name: "Shield", emoji: "🛡️" },
    { name: "Drum With Drumsticks", emoji: "🥁" },
    { name: "Sari", emoji: "🥻" },
    { name: "Lab Coat", emoji: "🥼" },
    { name: "Goggles", emoji: "🥽" },
    { name: "Hiking Boot", emoji: "🥾" },
    { name: "Flat Shoe", emoji: "🥿" },
    { name: "Probing Cane", emoji: "🦯" },
    { name: "Safety Vest", emoji: "🦺" },
    { name: "Billed Cap", emoji: "🧢" },
    { name: "Scarf", emoji: "🧣" },
    { name: "Gloves", emoji: "🧤" },
    { name: "Coat", emoji: "🧥" },
    { name: "Socks", emoji: "🧦" },
    { name: "Test Tube", emoji: "🧪" },
    { name: "Petri Dish", emoji: "🧫" },
    { name: "Dna Double Helix", emoji: "🧬" },
    { name: "Abacus", emoji: "🧮" },
    { name: "Fire Extinguisher", emoji: "🧯" },
    { name: "Toolbox", emoji: "🧰" },
    { name: "Magnet", emoji: "🧲" },
    { name: "Lotion Bottle", emoji: "🧴" },
    { name: "Safety Pin", emoji: "🧷" },
    { name: "Broom", emoji: "🧹" },
    { name: "Basket", emoji: "🧺" },
    { name: "Roll Of Paper", emoji: "🧻" },
    { name: "Bar Of Soap", emoji: "🧼" },
    { name: "Sponge", emoji: "🧽" },
    { name: "Receipt", emoji: "🧾" },
    { name: "Nazar Amulet", emoji: "🧿" },
    { name: "Ballet Shoes", emoji: "🩰" },
    { name: "One-piece Swimsuit", emoji: "🩱" },
    { name: "Briefs", emoji: "🩲" },
    { name: "Shorts", emoji: "🩳" },
    { name: "Thong Sandal", emoji: "🩴" },
    { name: "Drop Of Blood", emoji: "🩸" },
    { name: "Adhesive Bandage", emoji: "🩹" },
    { name: "Stethoscope", emoji: "🩺" },
    { name: "X-ray", emoji: "🩻" },
    { name: "Crutch", emoji: "🩼" },
    { name: "Boomerang", emoji: "🪃" },
    { name: "Maracas", emoji: "🪇" },
    { name: "Flute", emoji: "🪈" },
    { name: "Chair", emoji: "🪑" },
    { name: "Razor", emoji: "🪒" },
    { name: "Axe", emoji: "🪓" },
    { name: "Diya Lamp", emoji: "🪔" },
    { name: "Banjo", emoji: "🪕" },
    { name: "Military Helmet", emoji: "🪖" },
    { name: "Accordion", emoji: "🪗" },
    { name: "Long Drum", emoji: "🪘" },
    { name: "Coin", emoji: "🪙" },
    { name: "Carpentry Saw", emoji: "🪚" },
    { name: "Screwdriver", emoji: "🪛" },
    { name: "Ladder", emoji: "🪜" },
    { name: "Hook", emoji: "🪝" },
    { name: "Mirror", emoji: "🪞" },
    { name: "Window", emoji: "🪟" },
    { name: "Plunger", emoji: "🪠" },
    { name: "Bucket", emoji: "🪣" },
    { name: "Mouse Trap", emoji: "🪤" },
    { name: "Toothbrush", emoji: "🪥" },
    { name: "Headstone", emoji: "🪦" },
    { name: "Placard", emoji: "🪧" },
    { name: "Identification Card", emoji: "🪪" },
    { name: "Low Battery", emoji: "🪫" },
    { name: "Hamsa", emoji: "🪬" },
    { name: "Folding Hand Fan", emoji: "🪭" },
    { name: "Hair Pick", emoji: "🪮" },
    { name: "Bubbles", emoji: "🫧" },
    { name: "Keyboard", emoji: "⌨️" },
    { name: "Black Telephone", emoji: "☎️" },
    { name: "Hammer And Pick", emoji: "⚒️" },
    { name: "Crossed Swords", emoji: "⚔️" },
    { name: "Balance Scale", emoji: "⚖️" },
    { name: "Alembic", emoji: "⚗️" },
    { name: "Gear", emoji: "⚙️" },
    { name: "Coffin", emoji: "⚰️" },
    { name: "Funeral Urn", emoji: "⚱️" },
    { name: "Pick", emoji: "⛏️" },
    { name: "Rescue Worker’s Helmet", emoji: "⛑️" },
    { name: "Broken Chain", emoji: "⛓️‍💥" },
    { name: "Chains", emoji: "⛓️" },
    { name: "Black Scissors", emoji: "✂️" },
    { name: "Envelope", emoji: "✉️" },
    { name: "Pencil", emoji: "✏️" },
    { name: "Black Nib", emoji: "✒️" },
  ],
  Symbols: [
    { name: "Hash Key", emoji: "#️⃣" },
    { name: "Keycap: *", emoji: "*️⃣" },
    { name: "Keycap 0", emoji: "0️⃣" },
    { name: "Keycap 1", emoji: "1️⃣" },
    { name: "Keycap 2", emoji: "2️⃣" },
    { name: "Keycap 3", emoji: "3️⃣" },
    { name: "Keycap 4", emoji: "4️⃣" },
    { name: "Keycap 5", emoji: "5️⃣" },
    { name: "Keycap 6", emoji: "6️⃣" },
    { name: "Keycap 7", emoji: "7️⃣" },
    { name: "Keycap 8", emoji: "8️⃣" },
    { name: "Keycap 9", emoji: "9️⃣" },
    { name: "Copyright Sign", emoji: "©️" },
    { name: "Registered Sign", emoji: "®️" },
    { name: "Negative Squared Latin Capital Letter A", emoji: "🅰️" },
    { name: "Negative Squared Latin Capital Letter B", emoji: "🅱️" },
    { name: "Negative Squared Latin Capital Letter O", emoji: "🅾️" },
    { name: "Negative Squared Latin Capital Letter P", emoji: "🅿️" },
    { name: "Negative Squared Ab", emoji: "🆎" },
    { name: "Squared Cl", emoji: "🆑" },
    { name: "Squared Cool", emoji: "🆒" },
    { name: "Squared Free", emoji: "🆓" },
    { name: "Squared Id", emoji: "🆔" },
    { name: "Squared New", emoji: "🆕" },
    { name: "Squared Ng", emoji: "🆖" },
    { name: "Squared Ok", emoji: "🆗" },
    { name: "Squared Sos", emoji: "🆘" },
    { name: "Squared Up With Exclamation Mark", emoji: "🆙" },
    { name: "Squared Vs", emoji: "🆚" },
    { name: "Squared Katakana Koko", emoji: "🈁" },
    { name: "Squared Katakana Sa", emoji: "🈂️" },
    { name: "Squared Cjk Unified Ideograph-7121", emoji: "🈚" },
    { name: "Squared Cjk Unified Ideograph-6307", emoji: "🈯" },
    { name: "Squared Cjk Unified Ideograph-7981", emoji: "🈲" },
    { name: "Squared Cjk Unified Ideograph-7a7a", emoji: "🈳" },
    { name: "Squared Cjk Unified Ideograph-5408", emoji: "🈴" },
    { name: "Squared Cjk Unified Ideograph-6e80", emoji: "🈵" },
    { name: "Squared Cjk Unified Ideograph-6709", emoji: "🈶" },
    { name: "Squared Cjk Unified Ideograph-6708", emoji: "🈷️" },
    { name: "Squared Cjk Unified Ideograph-7533", emoji: "🈸" },
    { name: "Squared Cjk Unified Ideograph-5272", emoji: "🈹" },
    { name: "Squared Cjk Unified Ideograph-55b6", emoji: "🈺" },
    { name: "Circled Ideograph Advantage", emoji: "🉐" },
    { name: "Circled Ideograph Accept", emoji: "🉑" },
    { name: "Cinema", emoji: "🎦" },
    { name: "Automated Teller Machine", emoji: "🏧" },
    { name: "Diamond Shape With A Dot Inside", emoji: "💠" },
    { name: "Currency Exchange", emoji: "💱" },
    { name: "Heavy Dollar Sign", emoji: "💲" },
    { name: "Name Badge", emoji: "📛" },
    { name: "Vibration Mode", emoji: "📳" },
    { name: "Mobile Phone Off", emoji: "📴" },
    { name: "No Mobile Phones", emoji: "📵" },
    { name: "Antenna With Bars", emoji: "📶" },
    { name: "Twisted Rightwards Arrows", emoji: "🔀" },
    {
      name: "Clockwise Rightwards And Leftwards Open Circle Arrows",
      emoji: "🔁",
    },
    {
      name: "Clockwise Rightwards And Leftwards Open Circle Arrows With Circled One Overlay",
      emoji: "🔂",
    },
    { name: "Clockwise Downwards And Upwards Open Circle Arrows", emoji: "🔃" },
    {
      name: "Anticlockwise Downwards And Upwards Open Circle Arrows",
      emoji: "🔄",
    },
    { name: "Low Brightness Symbol", emoji: "🔅" },
    { name: "High Brightness Symbol", emoji: "🔆" },
    { name: "Radio Button", emoji: "🔘" },
    { name: "Back With Leftwards Arrow Above", emoji: "🔙" },
    { name: "End With Leftwards Arrow Above", emoji: "🔚" },
    {
      name: "On With Exclamation Mark With Left Right Arrow Above",
      emoji: "🔛",
    },
    { name: "Soon With Rightwards Arrow Above", emoji: "🔜" },
    { name: "Top With Upwards Arrow Above", emoji: "🔝" },
    { name: "No One Under Eighteen Symbol", emoji: "🔞" },
    { name: "Keycap Ten", emoji: "🔟" },
    { name: "Input Symbol For Latin Capital Letters", emoji: "🔠" },
    { name: "Input Symbol For Latin Small Letters", emoji: "🔡" },
    { name: "Input Symbol For Numbers", emoji: "🔢" },
    { name: "Input Symbol For Symbols", emoji: "🔣" },
    { name: "Input Symbol For Latin Letters", emoji: "🔤" },
    { name: "Six Pointed Star With Middle Dot", emoji: "🔯" },
    { name: "Japanese Symbol For Beginner", emoji: "🔰" },
    { name: "Trident Emblem", emoji: "🔱" },
    { name: "Black Square Button", emoji: "🔲" },
    { name: "White Square Button", emoji: "🔳" },
    { name: "Large Red Circle", emoji: "🔴" },
    { name: "Large Blue Circle", emoji: "🔵" },
    { name: "Large Orange Diamond", emoji: "🔶" },
    { name: "Large Blue Diamond", emoji: "🔷" },
    { name: "Small Orange Diamond", emoji: "🔸" },
    { name: "Small Blue Diamond", emoji: "🔹" },
    { name: "Up-pointing Red Triangle", emoji: "🔺" },
    { name: "Down-pointing Red Triangle", emoji: "🔻" },
    { name: "Up-pointing Small Red Triangle", emoji: "🔼" },
    { name: "Down-pointing Small Red Triangle", emoji: "🔽" },
    { name: "Om", emoji: "🕉️" },
    { name: "Menorah With Nine Branches", emoji: "🕎" },
    { name: "No Entry Sign", emoji: "🚫" },
    { name: "No Smoking Symbol", emoji: "🚭" },
    { name: "Put Litter In Its Place Symbol", emoji: "🚮" },
    { name: "Do Not Litter Symbol", emoji: "🚯" },
    { name: "Potable Water Symbol", emoji: "🚰" },
    { name: "Non-potable Water Symbol", emoji: "🚱" },
    { name: "No Bicycles", emoji: "🚳" },
    { name: "No Pedestrians", emoji: "🚷" },
    { name: "Children Crossing", emoji: "🚸" },
    { name: "Mens Symbol", emoji: "🚹" },
    { name: "Womens Symbol", emoji: "🚺" },
    { name: "Restroom", emoji: "🚻" },
    { name: "Baby Symbol", emoji: "🚼" },
    { name: "Water Closet", emoji: "🚾" },
    { name: "Passport Control", emoji: "🛂" },
    { name: "Customs", emoji: "🛃" },
    { name: "Baggage Claim", emoji: "🛄" },
    { name: "Left Luggage", emoji: "🛅" },
    { name: "Place Of Worship", emoji: "🛐" },
    { name: "Wireless", emoji: "🛜" },
    { name: "Large Orange Circle", emoji: "🟠" },
    { name: "Large Yellow Circle", emoji: "🟡" },
    { name: "Large Green Circle", emoji: "🟢" },
    { name: "Large Purple Circle", emoji: "🟣" },
    { name: "Large Brown Circle", emoji: "🟤" },
    { name: "Large Red Square", emoji: "🟥" },
    { name: "Large Blue Square", emoji: "🟦" },
    { name: "Large Orange Square", emoji: "🟧" },
    { name: "Large Yellow Square", emoji: "🟨" },
    { name: "Large Green Square", emoji: "🟩" },
    { name: "Large Purple Square", emoji: "🟪" },
    { name: "Large Brown Square", emoji: "🟫" },
    { name: "Heavy Equals Sign", emoji: "🟰" },
    { name: "Khanda", emoji: "🪯" },
    { name: "Double Exclamation Mark", emoji: "‼️" },
    { name: "Exclamation Question Mark", emoji: "⁉️" },
    { name: "Trade Mark Sign", emoji: "™️" },
    { name: "Information Source", emoji: "ℹ️" },
    { name: "Left Right Arrow", emoji: "↔️" },
    { name: "Up Down Arrow", emoji: "↕️" },
    { name: "North West Arrow", emoji: "↖️" },
    { name: "North East Arrow", emoji: "↗️" },
    { name: "South East Arrow", emoji: "↘️" },
    { name: "South West Arrow", emoji: "↙️" },
    { name: "Leftwards Arrow With Hook", emoji: "↩️" },
    { name: "Rightwards Arrow With Hook", emoji: "↪️" },
    { name: "Eject Button", emoji: "⏏️" },
    { name: "Black Right-pointing Double Triangle", emoji: "⏩" },
    { name: "Black Left-pointing Double Triangle", emoji: "⏪" },
    { name: "Black Up-pointing Double Triangle", emoji: "⏫" },
    { name: "Black Down-pointing Double Triangle", emoji: "⏬" },
    { name: "Next Track Button", emoji: "⏭️" },
    { name: "Last Track Button", emoji: "⏮️" },
    { name: "Play Or Pause Button", emoji: "⏯️" },
    { name: "Pause Button", emoji: "⏸️" },
    { name: "Stop Button", emoji: "⏹️" },
    { name: "Record Button", emoji: "⏺️" },
    { name: "Circled Latin Capital Letter M", emoji: "Ⓜ️" },
    { name: "Black Small Square", emoji: "▪️" },
    { name: "White Small Square", emoji: "▫️" },
    { name: "Black Right-pointing Triangle", emoji: "▶️" },
    { name: "Black Left-pointing Triangle", emoji: "◀️" },
    { name: "White Medium Square", emoji: "◻️" },
    { name: "Black Medium Square", emoji: "◼️" },
    { name: "White Medium Small Square", emoji: "◽" },
    { name: "Black Medium Small Square", emoji: "◾" },
    { name: "Ballot Box With Check", emoji: "☑️" },
    { name: "Radioactive", emoji: "☢️" },
    { name: "Biohazard", emoji: "☣️" },
    { name: "Orthodox Cross", emoji: "☦️" },
    { name: "Star And Crescent", emoji: "☪️" },
    { name: "Peace Symbol", emoji: "☮️" },
    { name: "Yin Yang", emoji: "☯️" },
    { name: "Wheel Of Dharma", emoji: "☸️" },
    { name: "Female Sign", emoji: "♀️" },
    { name: "Male Sign", emoji: "♂️" },
    { name: "Aries", emoji: "♈" },
    { name: "Taurus", emoji: "♉" },
    { name: "Gemini", emoji: "♊" },
    { name: "Cancer", emoji: "♋" },
    { name: "Leo", emoji: "♌" },
    { name: "Virgo", emoji: "♍" },
    { name: "Libra", emoji: "♎" },
    { name: "Scorpius", emoji: "♏" },
    { name: "Sagittarius", emoji: "♐" },
    { name: "Capricorn", emoji: "♑" },
    { name: "Aquarius", emoji: "♒" },
    { name: "Pisces", emoji: "♓" },
    { name: "Black Universal Recycling Symbol", emoji: "♻️" },
    { name: "Infinity", emoji: "♾️" },
    { name: "Wheelchair Symbol", emoji: "♿" },
    { name: "Medical Symbol", emoji: "⚕️" },
    { name: "Atom Symbol", emoji: "⚛️" },
    { name: "Fleur-de-lis", emoji: "⚜️" },
    { name: "Warning Sign", emoji: "⚠️" },
    { name: "Transgender Symbol", emoji: "⚧️" },
    { name: "Medium White Circle", emoji: "⚪" },
    { name: "Medium Black Circle", emoji: "⚫" },
    { name: "Ophiuchus", emoji: "⛎" },
    { name: "No Entry", emoji: "⛔" },
    { name: "White Heavy Check Mark", emoji: "✅" },
    { name: "Heavy Check Mark", emoji: "✔️" },
    { name: "Heavy Multiplication X", emoji: "✖️" },
    { name: "Latin Cross", emoji: "✝️" },
    { name: "Star Of David", emoji: "✡️" },
    { name: "Eight Spoked Asterisk", emoji: "✳️" },
    { name: "Eight Pointed Black Star", emoji: "✴️" },
    { name: "Sparkle", emoji: "❇️" },
    { name: "Cross Mark", emoji: "❌" },
    { name: "Negative Squared Cross Mark", emoji: "❎" },
    { name: "Black Question Mark Ornament", emoji: "❓" },
    { name: "White Question Mark Ornament", emoji: "❔" },
    { name: "White Exclamation Mark Ornament", emoji: "❕" },
    { name: "Heavy Exclamation Mark Symbol", emoji: "❗" },
    { name: "Heavy Plus Sign", emoji: "➕" },
    { name: "Heavy Minus Sign", emoji: "➖" },
    { name: "Heavy Division Sign", emoji: "➗" },
    { name: "Black Rightwards Arrow", emoji: "➡️" },
    { name: "Curly Loop", emoji: "➰" },
    { name: "Double Curly Loop", emoji: "➿" },
    { name: "Arrow Pointing Rightwards Then Curving Upwards", emoji: "⤴️" },
    { name: "Arrow Pointing Rightwards Then Curving Downwards", emoji: "⤵️" },
    { name: "Leftwards Black Arrow", emoji: "⬅️" },
    { name: "Upwards Black Arrow", emoji: "⬆️" },
    { name: "Downwards Black Arrow", emoji: "⬇️" },
    { name: "Black Large Square", emoji: "⬛" },
    { name: "White Large Square", emoji: "⬜" },
    { name: "Heavy Large Circle", emoji: "⭕" },
    { name: "Wavy Dash", emoji: "〰️" },
    { name: "Part Alternation Mark", emoji: "〽️" },
    { name: "Circled Ideograph Congratulation", emoji: "㊗️" },
    { name: "Circled Ideograph Secret", emoji: "㊙️" },
  ],
  Flags: [
    { name: "Ascension Island Flag", emoji: "🇦🇨" },
    { name: "Andorra Flag", emoji: "🇦🇩" },
    { name: "United Arab Emirates Flag", emoji: "🇦🇪" },
    { name: "Afghanistan Flag", emoji: "🇦🇫" },
    { name: "Antigua & Barbuda Flag", emoji: "🇦🇬" },
    { name: "Anguilla Flag", emoji: "🇦🇮" },
    { name: "Albania Flag", emoji: "🇦🇱" },
    { name: "Armenia Flag", emoji: "🇦🇲" },
    { name: "Angola Flag", emoji: "🇦🇴" },
    { name: "Antarctica Flag", emoji: "🇦🇶" },
    { name: "Argentina Flag", emoji: "🇦🇷" },
    { name: "American Samoa Flag", emoji: "🇦🇸" },
    { name: "Austria Flag", emoji: "🇦🇹" },
    { name: "Australia Flag", emoji: "🇦🇺" },
    { name: "Aruba Flag", emoji: "🇦🇼" },
    { name: "Åland Islands Flag", emoji: "🇦🇽" },
    { name: "Azerbaijan Flag", emoji: "🇦🇿" },
    { name: "Bosnia & Herzegovina Flag", emoji: "🇧🇦" },
    { name: "Barbados Flag", emoji: "🇧🇧" },
    { name: "Bangladesh Flag", emoji: "🇧🇩" },
    { name: "Belgium Flag", emoji: "🇧🇪" },
    { name: "Burkina Faso Flag", emoji: "🇧🇫" },
    { name: "Bulgaria Flag", emoji: "🇧🇬" },
    { name: "Bahrain Flag", emoji: "🇧🇭" },
    { name: "Burundi Flag", emoji: "🇧🇮" },
    { name: "Benin Flag", emoji: "🇧🇯" },
    { name: "St. Barthélemy Flag", emoji: "🇧🇱" },
    { name: "Bermuda Flag", emoji: "🇧🇲" },
    { name: "Brunei Flag", emoji: "🇧🇳" },
    { name: "Bolivia Flag", emoji: "🇧🇴" },
    { name: "Caribbean Netherlands Flag", emoji: "🇧🇶" },
    { name: "Brazil Flag", emoji: "🇧🇷" },
    { name: "Bahamas Flag", emoji: "🇧🇸" },
    { name: "Bhutan Flag", emoji: "🇧🇹" },
    { name: "Bouvet Island Flag", emoji: "🇧🇻" },
    { name: "Botswana Flag", emoji: "🇧🇼" },
    { name: "Belarus Flag", emoji: "🇧🇾" },
    { name: "Belize Flag", emoji: "🇧🇿" },
    { name: "Canada Flag", emoji: "🇨🇦" },
    { name: "Cocos (keeling) Islands Flag", emoji: "🇨🇨" },
    { name: "Congo - Kinshasa Flag", emoji: "🇨🇩" },
    { name: "Central African Republic Flag", emoji: "🇨🇫" },
    { name: "Congo - Brazzaville Flag", emoji: "🇨🇬" },
    { name: "Switzerland Flag", emoji: "🇨🇭" },
    { name: "Côte D’ivoire Flag", emoji: "🇨🇮" },
    { name: "Cook Islands Flag", emoji: "🇨🇰" },
    { name: "Chile Flag", emoji: "🇨🇱" },
    { name: "Cameroon Flag", emoji: "🇨🇲" },
    { name: "China Flag", emoji: "🇨🇳" },
    { name: "Colombia Flag", emoji: "🇨🇴" },
    { name: "Clipperton Island Flag", emoji: "🇨🇵" },
    { name: "Costa Rica Flag", emoji: "🇨🇷" },
    { name: "Cuba Flag", emoji: "🇨🇺" },
    { name: "Cape Verde Flag", emoji: "🇨🇻" },
    { name: "Curaçao Flag", emoji: "🇨🇼" },
    { name: "Christmas Island Flag", emoji: "🇨🇽" },
    { name: "Cyprus Flag", emoji: "🇨🇾" },
    { name: "Czechia Flag", emoji: "🇨🇿" },
    { name: "Germany Flag", emoji: "🇩🇪" },
    { name: "Diego Garcia Flag", emoji: "🇩🇬" },
    { name: "Djibouti Flag", emoji: "🇩🇯" },
    { name: "Denmark Flag", emoji: "🇩🇰" },
    { name: "Dominica Flag", emoji: "🇩🇲" },
    { name: "Dominican Republic Flag", emoji: "🇩🇴" },
    { name: "Algeria Flag", emoji: "🇩🇿" },
    { name: "Ceuta & Melilla Flag", emoji: "🇪🇦" },
    { name: "Ecuador Flag", emoji: "🇪🇨" },
    { name: "Estonia Flag", emoji: "🇪🇪" },
    { name: "Egypt Flag", emoji: "🇪🇬" },
    { name: "Western Sahara Flag", emoji: "🇪🇭" },
    { name: "Eritrea Flag", emoji: "🇪🇷" },
    { name: "Spain Flag", emoji: "🇪🇸" },
    { name: "Ethiopia Flag", emoji: "🇪🇹" },
    { name: "European Union Flag", emoji: "🇪🇺" },
    { name: "Finland Flag", emoji: "🇫🇮" },
    { name: "Fiji Flag", emoji: "🇫🇯" },
    { name: "Falkland Islands Flag", emoji: "🇫🇰" },
    { name: "Micronesia Flag", emoji: "🇫🇲" },
    { name: "Faroe Islands Flag", emoji: "🇫🇴" },
    { name: "France Flag", emoji: "🇫🇷" },
    { name: "Gabon Flag", emoji: "🇬🇦" },
    { name: "United Kingdom Flag", emoji: "🇬🇧" },
    { name: "Grenada Flag", emoji: "🇬🇩" },
    { name: "Georgia Flag", emoji: "🇬🇪" },
    { name: "French Guiana Flag", emoji: "🇬🇫" },
    { name: "Guernsey Flag", emoji: "🇬🇬" },
    { name: "Ghana Flag", emoji: "🇬🇭" },
    { name: "Gibraltar Flag", emoji: "🇬🇮" },
    { name: "Greenland Flag", emoji: "🇬🇱" },
    { name: "Gambia Flag", emoji: "🇬🇲" },
    { name: "Guinea Flag", emoji: "🇬🇳" },
    { name: "Guadeloupe Flag", emoji: "🇬🇵" },
    { name: "Equatorial Guinea Flag", emoji: "🇬🇶" },
    { name: "Greece Flag", emoji: "🇬🇷" },
    { name: "South Georgia & South Sandwich Islands Flag", emoji: "🇬🇸" },
    { name: "Guatemala Flag", emoji: "🇬🇹" },
    { name: "Guam Flag", emoji: "🇬🇺" },
    { name: "Guinea-bissau Flag", emoji: "🇬🇼" },
    { name: "Guyana Flag", emoji: "🇬🇾" },
    { name: "Hong Kong Sar China Flag", emoji: "🇭🇰" },
    { name: "Heard & Mcdonald Islands Flag", emoji: "🇭🇲" },
    { name: "Honduras Flag", emoji: "🇭🇳" },
    { name: "Croatia Flag", emoji: "🇭🇷" },
    { name: "Haiti Flag", emoji: "🇭🇹" },
    { name: "Hungary Flag", emoji: "🇭🇺" },
    { name: "Canary Islands Flag", emoji: "🇮🇨" },
    { name: "Indonesia Flag", emoji: "🇮🇩" },
    { name: "Ireland Flag", emoji: "🇮🇪" },
    { name: "Israel Flag", emoji: "🇮🇱" },
    { name: "Isle Of Man Flag", emoji: "🇮🇲" },
    { name: "India Flag", emoji: "🇮🇳" },
    { name: "British Indian Ocean Territory Flag", emoji: "🇮🇴" },
    { name: "Iraq Flag", emoji: "🇮🇶" },
    { name: "Iran Flag", emoji: "🇮🇷" },
    { name: "Iceland Flag", emoji: "🇮🇸" },
    { name: "Italy Flag", emoji: "🇮🇹" },
    { name: "Jersey Flag", emoji: "🇯🇪" },
    { name: "Jamaica Flag", emoji: "🇯🇲" },
    { name: "Jordan Flag", emoji: "🇯🇴" },
    { name: "Japan Flag", emoji: "🇯🇵" },
    { name: "Kenya Flag", emoji: "🇰🇪" },
    { name: "Kyrgyzstan Flag", emoji: "🇰🇬" },
    { name: "Cambodia Flag", emoji: "🇰🇭" },
    { name: "Kiribati Flag", emoji: "🇰🇮" },
    { name: "Comoros Flag", emoji: "🇰🇲" },
    { name: "St. Kitts & Nevis Flag", emoji: "🇰🇳" },
    { name: "North Korea Flag", emoji: "🇰🇵" },
    { name: "South Korea Flag", emoji: "🇰🇷" },
    { name: "Kuwait Flag", emoji: "🇰🇼" },
    { name: "Cayman Islands Flag", emoji: "🇰🇾" },
    { name: "Kazakhstan Flag", emoji: "🇰🇿" },
    { name: "Laos Flag", emoji: "🇱🇦" },
    { name: "Lebanon Flag", emoji: "🇱🇧" },
    { name: "St. Lucia Flag", emoji: "🇱🇨" },
    { name: "Liechtenstein Flag", emoji: "🇱🇮" },
    { name: "Sri Lanka Flag", emoji: "🇱🇰" },
    { name: "Liberia Flag", emoji: "🇱🇷" },
    { name: "Lesotho Flag", emoji: "🇱🇸" },
    { name: "Lithuania Flag", emoji: "🇱🇹" },
    { name: "Luxembourg Flag", emoji: "🇱🇺" },
    { name: "Latvia Flag", emoji: "🇱🇻" },
    { name: "Libya Flag", emoji: "🇱🇾" },
    { name: "Morocco Flag", emoji: "🇲🇦" },
    { name: "Monaco Flag", emoji: "🇲🇨" },
    { name: "Moldova Flag", emoji: "🇲🇩" },
    { name: "Montenegro Flag", emoji: "🇲🇪" },
    { name: "St. Martin Flag", emoji: "🇲🇫" },
    { name: "Madagascar Flag", emoji: "🇲🇬" },
    { name: "Marshall Islands Flag", emoji: "🇲🇭" },
    { name: "North Macedonia Flag", emoji: "🇲🇰" },
    { name: "Mali Flag", emoji: "🇲🇱" },
    { name: "Myanmar (burma) Flag", emoji: "🇲🇲" },
    { name: "Mongolia Flag", emoji: "🇲🇳" },
    { name: "Macao Sar China Flag", emoji: "🇲🇴" },
    { name: "Northern Mariana Islands Flag", emoji: "🇲🇵" },
    { name: "Martinique Flag", emoji: "🇲🇶" },
    { name: "Mauritania Flag", emoji: "🇲🇷" },
    { name: "Montserrat Flag", emoji: "🇲🇸" },
    { name: "Malta Flag", emoji: "🇲🇹" },
    { name: "Mauritius Flag", emoji: "🇲🇺" },
    { name: "Maldives Flag", emoji: "🇲🇻" },
    { name: "Malawi Flag", emoji: "🇲🇼" },
    { name: "Mexico Flag", emoji: "🇲🇽" },
    { name: "Malaysia Flag", emoji: "🇲🇾" },
    { name: "Mozambique Flag", emoji: "🇲🇿" },
    { name: "Namibia Flag", emoji: "🇳🇦" },
    { name: "New Caledonia Flag", emoji: "🇳🇨" },
    { name: "Niger Flag", emoji: "🇳🇪" },
    { name: "Norfolk Island Flag", emoji: "🇳🇫" },
    { name: "Nigeria Flag", emoji: "🇳🇬" },
    { name: "Nicaragua Flag", emoji: "🇳🇮" },
    { name: "Netherlands Flag", emoji: "🇳🇱" },
    { name: "Norway Flag", emoji: "🇳🇴" },
    { name: "Nepal Flag", emoji: "🇳🇵" },
    { name: "Nauru Flag", emoji: "🇳🇷" },
    { name: "Niue Flag", emoji: "🇳🇺" },
    { name: "New Zealand Flag", emoji: "🇳🇿" },
    { name: "Oman Flag", emoji: "🇴🇲" },
    { name: "Panama Flag", emoji: "🇵🇦" },
    { name: "Peru Flag", emoji: "🇵🇪" },
    { name: "French Polynesia Flag", emoji: "🇵🇫" },
    { name: "Papua New Guinea Flag", emoji: "🇵🇬" },
    { name: "Philippines Flag", emoji: "🇵🇭" },
    { name: "Pakistan Flag", emoji: "🇵🇰" },
    { name: "Poland Flag", emoji: "🇵🇱" },
    { name: "St. Pierre & Miquelon Flag", emoji: "🇵🇲" },
    { name: "Pitcairn Islands Flag", emoji: "🇵🇳" },
    { name: "Puerto Rico Flag", emoji: "🇵🇷" },
    { name: "Palestinian Territories Flag", emoji: "🇵🇸" },
    { name: "Portugal Flag", emoji: "🇵🇹" },
    { name: "Palau Flag", emoji: "🇵🇼" },
    { name: "Paraguay Flag", emoji: "🇵🇾" },
    { name: "Qatar Flag", emoji: "🇶🇦" },
    { name: "Réunion Flag", emoji: "🇷🇪" },
    { name: "Romania Flag", emoji: "🇷🇴" },
    { name: "Serbia Flag", emoji: "🇷🇸" },
    { name: "Russia Flag", emoji: "🇷🇺" },
    { name: "Rwanda Flag", emoji: "🇷🇼" },
    { name: "Saudi Arabia Flag", emoji: "🇸🇦" },
    { name: "Solomon Islands Flag", emoji: "🇸🇧" },
    { name: "Seychelles Flag", emoji: "🇸🇨" },
    { name: "Sudan Flag", emoji: "🇸🇩" },
    { name: "Sweden Flag", emoji: "🇸🇪" },
    { name: "Singapore Flag", emoji: "🇸🇬" },
    { name: "St. Helena Flag", emoji: "🇸🇭" },
    { name: "Slovenia Flag", emoji: "🇸🇮" },
    { name: "Svalbard & Jan Mayen Flag", emoji: "🇸🇯" },
    { name: "Slovakia Flag", emoji: "🇸🇰" },
    { name: "Sierra Leone Flag", emoji: "🇸🇱" },
    { name: "San Marino Flag", emoji: "🇸🇲" },
    { name: "Senegal Flag", emoji: "🇸🇳" },
    { name: "Somalia Flag", emoji: "🇸🇴" },
    { name: "Suriname Flag", emoji: "🇸🇷" },
    { name: "South Sudan Flag", emoji: "🇸🇸" },
    { name: "São Tomé & Príncipe Flag", emoji: "🇸🇹" },
    { name: "El Salvador Flag", emoji: "🇸🇻" },
    { name: "Sint Maarten Flag", emoji: "🇸🇽" },
    { name: "Syria Flag", emoji: "🇸🇾" },
    { name: "Eswatini Flag", emoji: "🇸🇿" },
    { name: "Tristan Da Cunha Flag", emoji: "🇹🇦" },
    { name: "Turks & Caicos Islands Flag", emoji: "🇹🇨" },
    { name: "Chad Flag", emoji: "🇹🇩" },
    { name: "French Southern Territories Flag", emoji: "🇹🇫" },
    { name: "Togo Flag", emoji: "🇹🇬" },
    { name: "Thailand Flag", emoji: "🇹🇭" },
    { name: "Tajikistan Flag", emoji: "🇹🇯" },
    { name: "Tokelau Flag", emoji: "🇹🇰" },
    { name: "Timor-leste Flag", emoji: "🇹🇱" },
    { name: "Turkmenistan Flag", emoji: "🇹🇲" },
    { name: "Tunisia Flag", emoji: "🇹🇳" },
    { name: "Tonga Flag", emoji: "🇹🇴" },
    { name: "Türkiye Flag", emoji: "🇹🇷" },
    { name: "Trinidad & Tobago Flag", emoji: "🇹🇹" },
    { name: "Tuvalu Flag", emoji: "🇹🇻" },
    { name: "Taiwan Flag", emoji: "🇹🇼" },
    { name: "Tanzania Flag", emoji: "🇹🇿" },
    { name: "Ukraine Flag", emoji: "🇺🇦" },
    { name: "Uganda Flag", emoji: "🇺🇬" },
    { name: "U.s. Outlying Islands Flag", emoji: "🇺🇲" },
    { name: "United Nations Flag", emoji: "🇺🇳" },
    { name: "United States Flag", emoji: "🇺🇸" },
    { name: "Uruguay Flag", emoji: "🇺🇾" },
    { name: "Uzbekistan Flag", emoji: "🇺🇿" },
    { name: "Vatican City Flag", emoji: "🇻🇦" },
    { name: "St. Vincent & Grenadines Flag", emoji: "🇻🇨" },
    { name: "Venezuela Flag", emoji: "🇻🇪" },
    { name: "British Virgin Islands Flag", emoji: "🇻🇬" },
    { name: "U.s. Virgin Islands Flag", emoji: "🇻🇮" },
    { name: "Vietnam Flag", emoji: "🇻🇳" },
    { name: "Vanuatu Flag", emoji: "🇻🇺" },
    { name: "Wallis & Futuna Flag", emoji: "🇼🇫" },
    { name: "Samoa Flag", emoji: "🇼🇸" },
    { name: "Kosovo Flag", emoji: "🇽🇰" },
    { name: "Yemen Flag", emoji: "🇾🇪" },
    { name: "Mayotte Flag", emoji: "🇾🇹" },
    { name: "South Africa Flag", emoji: "🇿🇦" },
    { name: "Zambia Flag", emoji: "🇿🇲" },
    { name: "Zimbabwe Flag", emoji: "🇿🇼" },
    { name: "Crossed Flags", emoji: "🎌" },
    { name: "Chequered Flag", emoji: "🏁" },
    { name: "Rainbow Flag", emoji: "🏳️‍🌈" },
    { name: "Transgender Flag", emoji: "🏳️‍⚧️" },
    { name: "White Flag", emoji: "🏳️" },
    { name: "Pirate Flag", emoji: "🏴‍☠️" },
    { name: "England Flag", emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    { name: "Scotland Flag", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
    { name: "Wales Flag", emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
    { name: "Waving Black Flag", emoji: "🏴" },
    { name: "Triangular Flag On Post", emoji: "🚩" },
  ],
  Component: [
    { name: "Emoji Modifier Fitzpatrick Type-1-2", emoji: "🏻" },
    { name: "Emoji Modifier Fitzpatrick Type-3", emoji: "🏼" },
    { name: "Emoji Modifier Fitzpatrick Type-4", emoji: "🏽" },
    { name: "Emoji Modifier Fitzpatrick Type-5", emoji: "🏾" },
    { name: "Emoji Modifier Fitzpatrick Type-6", emoji: "🏿" },
  ],
};

export default emojis;
