// It is generated from https://github.com/jonschlinkert/lang-map
export const FILE_NAME_EXT_TO_LANG = {
  "1": ["roff", "roff manpage"],
  "2": ["roff", "roff manpage"],
  "3": ["roff", "roff manpage"],
  "4": ["roff", "roff manpage"],
  "5": ["roff", "roff manpage"],
  "6": ["roff", "roff manpage"],
  "7": ["roff", "roff manpage"],
  "8": ["roff", "roff manpage"],
  "9": ["roff", "roff manpage"],
  bsl: ["1c enterprise"],
  os: ["1c enterprise"],
  "4dm": ["4d"],
  abap: ["abap"],
  asddls: ["abap cds"],
  abnf: ["abnf"],
  asc: ["ags script", "asciidoc", "public key"],
  ash: ["ags script"],
  aidl: ["aidl"],
  al: ["al", "perl"],
  ampl: ["ampl"],
  mod: ["ampl", "linux kernel module", "modula-2", "xml"],
  g4: ["antlr"],
  apib: ["api blueprint"],
  apl: ["apl"],
  dyalog: ["apl"],
  asl: ["asl"],
  dsl: ["asl"],
  asn: ["asn.1"],
  asn1: ["asn.1"],
  asax: ["asp.net"],
  ascx: ["asp.net"],
  ashx: ["asp.net"],
  asmx: ["asp.net"],
  aspx: ["asp.net"],
  axd: ["asp.net"],
  dats: ["ats"],
  hats: ["ats"],
  sats: ["ats"],
  as: ["actionscript", "angelscript"],
  adb: ["ada"],
  ada: ["ada"],
  ads: ["ada"],
  afm: ["adobe font metrics"],
  agda: ["agda"],
  als: ["alloy"],
  OutJob: ["altium designer"],
  PcbDoc: ["altium designer"],
  PrjPCB: ["altium designer"],
  SchDoc: ["altium designer"],
  angelscript: ["angelscript"],
  apacheconf: ["apacheconf"],
  vhost: ["apacheconf", "nginx"],
  cls: ["apex", "objectscript", "openedge abl", "tex", "vba"],
  agc: ["apollo guidance computer"],
  applescript: ["applescript"],
  scpt: ["applescript"],
  arc: ["arc"],
  asciidoc: ["asciidoc"],
  adoc: ["asciidoc"],
  aj: ["aspectj"],
  asm: ["assembly", "motorola 68k assembly"],
  a51: ["assembly"],
  i: ["assembly", "motorola 68k assembly", "swig"],
  inc: [
    "assembly",
    "c++",
    "html",
    "motorola 68k assembly",
    "nasl",
    "php",
    "pov-ray sdl",
    "pascal",
    "pawn",
    "sql",
    "sourcepawn",
  ],
  nasm: ["assembly"],
  astro: ["astro"],
  asy: ["asymptote", "ltspice symbol"],
  aug: ["augeas"],
  ahk: ["autohotkey"],
  ahkl: ["autohotkey"],
  au3: ["autoit"],
  avdl: ["avro idl"],
  awk: ["awk"],
  auk: ["awk"],
  gawk: ["awk"],
  mawk: ["awk"],
  nawk: ["awk"],
  bas: ["basic", "freebasic", "vba"],
  bal: ["ballerina"],
  bat: ["batchfile"],
  cmd: ["batchfile"],
  bf: ["beef", "brainfuck", "hyphy"],
  befunge: ["befunge"],
  bib: ["bibtex"],
  bibtex: ["bibtex"],
  bicep: ["bicep"],
  bison: ["bison"],
  bb: ["bitbake", "blitzbasic"],
  blade: ["blade"],
  "blade.php": ["blade"],
  decls: ["blitzbasic"],
  bmx: ["blitzmax"],
  bsv: ["bluespec"],
  boo: ["boo"],
  bpl: ["boogie"],
  b: ["brainfuck", "limbo"],
  brs: ["brightscript"],
  c: ["c"],
  cats: ["c"],
  h: ["c", "c++", "objective-c"],
  idc: ["c"],
  cs: ["c#", "smalltalk"],
  cake: ["c#", "coffeescript"],
  csx: ["c#"],
  linq: ["c#"],
  cpp: ["c++"],
  "c++": ["c++"],
  cc: ["c++"],
  cp: ["c++", "component pascal"],
  cxx: ["c++"],
  "h++": ["c++"],
  hh: ["c++", "hack"],
  hpp: ["c++"],
  hxx: ["c++"],
  inl: ["c++"],
  ino: ["c++"],
  ipp: ["c++"],
  re: ["c++", "reason"],
  tcc: ["c++"],
  tpp: ["c++"],
  "c-objdump": ["c-objdump"],
  chs: ["c2hs haskell"],
  cil: ["cil"],
  clp: ["clips"],
  cmake: ["cmake"],
  "cmake.in": ["cmake"],
  cob: ["cobol"],
  cbl: ["cobol"],
  ccp: ["cobol"],
  cobol: ["cobol"],
  cpy: ["cobol"],
  dae: ["collada"],
  cson: ["cson"],
  css: ["css"],
  csv: ["csv"],
  cue: ["cue", "cue sheet"],
  w: ["cweb", "openedge abl"],
  cabal: ["cabal config"],
  capnp: ["cap'n proto"],
  mss: ["cartocss"],
  ceylon: ["ceylon"],
  chpl: ["chapel"],
  ch: ["charity", "xbase"],
  ck: ["chuck"],
  cirru: ["cirru"],
  clw: ["clarion"],
  asp: ["classic asp"],
  icl: ["clean"],
  dcl: ["clean"],
  click: ["click"],
  clj: ["clojure"],
  boot: ["clojure"],
  cl2: ["clojure"],
  cljc: ["clojure"],
  cljs: ["clojure"],
  "cljs.hl": ["clojure"],
  cljscm: ["clojure"],
  cljx: ["clojure"],
  hic: ["clojure"],
  soy: ["closure templates"],
  conllu: ["conll-u"],
  conll: ["conll-u"],
  ql: ["codeql"],
  qll: ["codeql"],
  coffee: ["coffeescript"],
  _coffee: ["coffeescript"],
  cjsx: ["coffeescript"],
  iced: ["coffeescript"],
  cfm: ["coldfusion"],
  cfml: ["coldfusion"],
  cfc: ["coldfusion cfc"],
  lisp: ["common lisp", "newlisp"],
  asd: ["common lisp"],
  cl: ["common lisp", "cool", "opencl"],
  l: ["common lisp", "lex", "picolisp", "roff"],
  lsp: ["common lisp", "newlisp"],
  ny: ["common lisp"],
  podsl: ["common lisp"],
  sexp: ["common lisp"],
  cwl: ["common workflow language"],
  cps: ["component pascal"],
  coq: ["coq"],
  v: ["coq", "v", "verilog"],
  cppobjdump: ["cpp-objdump"],
  "c++-objdump": ["cpp-objdump"],
  "c++objdump": ["cpp-objdump"],
  "cpp-objdump": ["cpp-objdump"],
  "cxx-objdump": ["cpp-objdump"],
  creole: ["creole"],
  cr: ["crystal"],
  orc: ["csound"],
  udo: ["csound"],
  csd: ["csound document"],
  sco: ["csound score"],
  cu: ["cuda"],
  cuh: ["cuda"],
  cy: ["cycript"],
  pyx: ["cython"],
  pxd: ["cython"],
  pxi: ["cython"],
  d: ["d", "dtrace", "makefile"],
  di: ["d"],
  "d-objdump": ["d-objdump"],
  com: ["digital command language"],
  dm: ["dm"],
  zone: ["dns zone"],
  arpa: ["dns zone"],
  dfy: ["dafny"],
  darcspatch: ["darcs patch"],
  dpatch: ["darcs patch"],
  dart: ["dart"],
  dwl: ["dataweave"],
  dhall: ["dhall"],
  diff: ["diff"],
  patch: ["diff"],
  x: ["directx 3d file", "linker script", "logos", "rpc"],
  dockerfile: ["dockerfile"],
  djs: ["dogescript"],
  dylan: ["dylan"],
  dyl: ["dylan"],
  intr: ["dylan"],
  lid: ["dylan"],
  E: ["e"],
  eml: ["e-mail"],
  mbox: ["e-mail"],
  ebnf: ["ebnf"],
  ecl: ["ecl", "eclipse"],
  eclxml: ["ecl"],
  ejs: ["ejs"],
  ect: ["ejs"],
  jst: ["ejs"],
  eq: ["eq"],
  sch: ["eagle", "kicad schematic", "scheme", "xml"],
  brd: ["eagle", "kicad legacy layout"],
  eb: ["easybuild"],
  epj: ["ecere projects"],
  edc: ["edje data collection"],
  e: ["eiffel"],
  ex: ["elixir"],
  exs: ["elixir"],
  elm: ["elm"],
  el: ["emacs lisp"],
  emacs: ["emacs lisp"],
  "emacs.desktop": ["emacs lisp"],
  em: ["emberscript"],
  emberscript: ["emberscript"],
  erl: ["erlang"],
  "app.src": ["erlang"],
  es: ["erlang", "javascript"],
  escript: ["erlang"],
  hrl: ["erlang"],
  xrl: ["erlang"],
  yrl: ["erlang"],
  fs: ["f#", "filterscript", "forth", "glsl"],
  fsi: ["f#"],
  fsx: ["f#"],
  fst: ["f*"],
  flf: ["figlet font"],
  fx: ["flux", "hlsl"],
  flux: ["flux"],
  factor: ["factor"],
  fy: ["fancy"],
  fancypack: ["fancy"],
  fan: ["fantom"],
  dsp: ["faust", "microsoft developer studio project"],
  fnl: ["fennel"],
  f: ["filebench wml", "forth", "fortran"],
  ftl: ["fluent", "freemarker"],
  for: ["formatted", "forth", "fortran"],
  "eam.fs": ["formatted"],
  fth: ["forth"],
  "4th": ["forth"],
  forth: ["forth"],
  fr: ["forth", "frege", "text"],
  frt: ["forth"],
  f77: ["fortran"],
  fpp: ["fortran"],
  f90: ["fortran free form"],
  f03: ["fortran free form"],
  f08: ["fortran free form"],
  f95: ["fortran free form"],
  bi: ["freebasic"],
  fut: ["futhark"],
  g: ["g-code", "gap"],
  cnc: ["g-code"],
  gco: ["g-code"],
  gcode: ["g-code"],
  gaml: ["gaml"],
  gms: ["gams"],
  gap: ["gap"],
  gd: ["gap", "gdscript"],
  gi: ["gap"],
  tst: ["gap", "scilab"],
  md: ["gcc machine description", "markdown"],
  gdb: ["gdb"],
  gdbinit: ["gdb"],
  ged: ["gedcom"],
  glsl: ["glsl"],
  fp: ["glsl"],
  frag: ["glsl", "javascript"],
  frg: ["glsl"],
  fsh: ["glsl"],
  fshader: ["glsl"],
  geo: ["glsl"],
  geom: ["glsl"],
  glslf: ["glsl"],
  glslv: ["glsl"],
  gs: ["glsl", "genie", "gosu", "javascript"],
  gshader: ["glsl"],
  shader: ["glsl", "shaderlab"],
  tesc: ["glsl"],
  tese: ["glsl"],
  vert: ["glsl"],
  vrx: ["glsl"],
  vsh: ["glsl"],
  vshader: ["glsl"],
  gn: ["gn"],
  gni: ["gn"],
  gml: ["game maker language", "gerber image", "graph modeling language", "xml"],
  kid: ["genshi"],
  ebuild: ["gentoo ebuild"],
  eclass: ["gentoo eclass"],
  gbr: ["gerber image"],
  cmp: ["gerber image"],
  gbl: ["gerber image"],
  gbo: ["gerber image"],
  gbp: ["gerber image"],
  gbs: ["gerber image"],
  gko: ["gerber image"],
  gpb: ["gerber image"],
  gpt: ["gerber image"],
  gtl: ["gerber image"],
  gto: ["gerber image"],
  gtp: ["gerber image"],
  gts: ["gerber image"],
  ncl: ["gerber image", "ncl", "text", "xml"],
  sol: ["gerber image", "solidity"],
  po: ["gettext catalog"],
  pot: ["gettext catalog"],
  feature: ["gherkin"],
  story: ["gherkin"],
  gitconfig: ["git config"],
  glf: ["glyph"],
  bdf: ["glyph bitmap distribution format"],
  gp: ["gnuplot"],
  gnu: ["gnuplot"],
  gnuplot: ["gnuplot"],
  p: ["gnuplot", "openedge abl"],
  plot: ["gnuplot"],
  plt: ["gnuplot"],
  go: ["go"],
  golo: ["golo"],
  gst: ["gosu", "xml"],
  gsx: ["gosu"],
  vark: ["gosu"],
  grace: ["grace"],
  gradle: ["gradle"],
  gf: ["grammatical framework"],
  graphql: ["graphql"],
  gql: ["graphql"],
  graphqls: ["graphql"],
  dot: ["graphviz (dot)"],
  gv: ["graphviz (dot)"],
  groovy: ["groovy"],
  grt: ["groovy"],
  gtpl: ["groovy"],
  gvy: ["groovy"],
  gsp: ["groovy server pages"],
  cfg: ["haproxy", "ini"],
  hcl: ["hcl"],
  nomad: ["hcl"],
  tf: ["hcl"],
  tfvars: ["hcl"],
  workflow: ["hcl", "xml"],
  hlsl: ["hlsl"],
  cginc: ["hlsl"],
  fxh: ["hlsl"],
  hlsli: ["hlsl"],
  html: ["html"],
  hta: ["html"],
  htm: ["html"],
  "html.hl": ["html"],
  xht: ["html"],
  xhtml: ["html"],
  ecr: ["html+ecr"],
  eex: ["html+eex"],
  "html.leex": ["html+eex"],
  erb: ["html+erb"],
  "erb.deface": ["html+erb"],
  rhtml: ["html+erb"],
  phtml: ["html+php"],
  cshtml: ["html+razor"],
  razor: ["html+razor"],
  http: ["http"],
  hxml: ["hxml"],
  hack: ["hack"],
  hhi: ["hack"],
  php: ["hack", "php"],
  haml: ["haml"],
  "haml.deface": ["haml"],
  handlebars: ["handlebars"],
  hbs: ["handlebars"],
  hb: ["harbour"],
  hs: ["haskell"],
  "hs-boot": ["haskell"],
  hsc: ["haskell"],
  hx: ["haxe"],
  hxsl: ["haxe"],
  q: ["hiveql", "q"],
  hql: ["hiveql"],
  hc: ["holyc"],
  hy: ["hy"],
  pro: ["idl", "ini", "proguard", "prolog", "qmake"],
  dlm: ["idl"],
  ipf: ["igor pro"],
  ini: ["ini"],
  dof: ["ini"],
  lektorproject: ["ini"],
  prefs: ["ini"],
  properties: ["ini", "java properties"],
  irclog: ["irc log"],
  weechatlog: ["irc log"],
  idr: ["idris"],
  lidr: ["idris"],
  gitignore: ["ignore list"],
  ijm: ["imagej macro"],
  ni: ["inform 7"],
  i7x: ["inform 7"],
  iss: ["inno setup"],
  isl: ["inno setup"],
  io: ["io"],
  ik: ["ioke"],
  thy: ["isabelle"],
  ijs: ["j"],
  flex: ["jflex"],
  jflex: ["jflex"],
  json: ["json"],
  avsc: ["json"],
  geojson: ["json"],
  gltf: ["json"],
  har: ["json"],
  ice: ["json", "slice"],
  "JSON-tmLanguage": ["json"],
  jsonl: ["json"],
  mcmeta: ["json"],
  tfstate: ["json"],
  "tfstate.backup": ["json"],
  topojson: ["json"],
  webapp: ["json"],
  webmanifest: ["json"],
  yy: ["json", "yacc"],
  yyp: ["json"],
  jsonc: ["json with comments"],
  "sublime-build": ["json with comments"],
  "sublime-commands": ["json with comments"],
  "sublime-completions": ["json with comments"],
  "sublime-keymap": ["json with comments"],
  "sublime-macro": ["json with comments"],
  "sublime-menu": ["json with comments"],
  "sublime-mousemap": ["json with comments"],
  "sublime-project": ["json with comments"],
  "sublime-settings": ["json with comments"],
  "sublime-theme": ["json with comments"],
  "sublime-workspace": ["json with comments"],
  sublime_metrics: ["json with comments"],
  sublime_session: ["json with comments"],
  json5: ["json5"],
  jsonld: ["jsonld"],
  jq: ["jsoniq", "jq"],
  j: ["jasmin", "objective-j"],
  java: ["java"],
  jav: ["java"],
  jsp: ["java server pages"],
  js: ["javascript"],
  _js: ["javascript"],
  bones: ["javascript"],
  cjs: ["javascript"],
  es6: ["javascript"],
  jake: ["javascript"],
  javascript: ["javascript"],
  jsb: ["javascript"],
  jscad: ["javascript"],
  jsfl: ["javascript"],
  jsm: ["javascript"],
  jss: ["javascript"],
  jsx: ["javascript"],
  mjs: ["javascript"],
  njs: ["javascript"],
  pac: ["javascript"],
  sjs: ["javascript"],
  ssjs: ["javascript"],
  xsjs: ["javascript"],
  xsjslib: ["javascript"],
  "js.erb": ["javascript+erb"],
  snap: ["jest snapshot"],
  jinja: ["jinja"],
  j2: ["jinja"],
  jinja2: ["jinja"],
  jison: ["jison"],
  jisonlex: ["jison lex"],
  ol: ["jolie"],
  iol: ["jolie"],
  jsonnet: ["jsonnet"],
  libsonnet: ["jsonnet"],
  jl: ["julia"],
  ipynb: ["jupyter notebook"],
  krl: ["krl"],
  ksy: ["kaitai struct"],
  kak: ["kakounescript"],
  kicad_pcb: ["kicad layout"],
  kicad_mod: ["kicad layout"],
  kicad_wks: ["kicad layout"],
  kit: ["kit"],
  kt: ["kotlin"],
  ktm: ["kotlin"],
  kts: ["kotlin"],
  csl: ["kusto", "xml"],
  lfe: ["lfe"],
  ll: ["llvm"],
  lol: ["lolcode"],
  lsl: ["lsl"],
  lslp: ["lsl"],
  lvproj: ["labview"],
  lvlib: ["labview"],
  lark: ["lark"],
  lasso: ["lasso"],
  las: ["lasso"],
  lasso8: ["lasso"],
  lasso9: ["lasso"],
  latte: ["latte"],
  lean: ["lean"],
  hlean: ["lean"],
  less: ["less"],
  lex: ["lex"],
  ly: ["lilypond"],
  ily: ["lilypond"],
  m: ["limbo", "m", "matlab", "muf", "mathematica", "mercury", "objective-c"],
  ld: ["linker script"],
  lds: ["linker script"],
  liquid: ["liquid"],
  lagda: ["literate agda"],
  litcoffee: ["literate coffeescript"],
  "coffee.md": ["literate coffeescript"],
  lhs: ["literate haskell"],
  ls: ["livescript", "loomscript"],
  _ls: ["livescript"],
  xm: ["logos"],
  xi: ["logos"],
  lgt: ["logtalk"],
  logtalk: ["logtalk"],
  lookml: ["lookml"],
  "model.lkml": ["lookml"],
  "view.lkml": ["lookml"],
  lua: ["lua"],
  fcgi: ["lua", "php", "perl", "python", "ruby", "shell"],
  nse: ["lua"],
  p8: ["lua"],
  pd_lua: ["lua"],
  rbxs: ["lua"],
  rockspec: ["lua"],
  wlua: ["lua"],
  mumps: ["m"],
  m4: ["m4", "m4sugar"],
  matlab: ["matlab"],
  ms: ["maxscript", "roff", "unix assembly"],
  mcr: ["maxscript"],
  mlir: ["mlir"],
  mq4: ["mql4"],
  mqh: ["mql4", "mql5"],
  mq5: ["mql5"],
  mtml: ["mtml"],
  muf: ["muf"],
  m2: ["macaulay2"],
  mak: ["makefile"],
  make: ["makefile"],
  makefile: ["makefile"],
  mk: ["makefile"],
  mkfile: ["makefile"],
  mako: ["mako"],
  mao: ["mako"],
  markdown: ["markdown"],
  mdown: ["markdown"],
  mdwn: ["markdown"],
  mdx: ["markdown"],
  mkd: ["markdown"],
  mkdn: ["markdown"],
  mkdown: ["markdown"],
  ronn: ["markdown"],
  scd: ["markdown", "supercollider"],
  workbook: ["markdown"],
  marko: ["marko"],
  mask: ["mask", "unity3d asset"],
  mathematica: ["mathematica"],
  cdf: ["mathematica"],
  ma: ["mathematica"],
  mt: ["mathematica"],
  nb: ["mathematica", "text"],
  nbp: ["mathematica"],
  wl: ["mathematica"],
  wlt: ["mathematica"],
  maxpat: ["max"],
  maxhelp: ["max"],
  maxproj: ["max"],
  mxt: ["max"],
  pat: ["max"],
  moo: ["mercury", "moocode"],
  metal: ["metal"],
  sln: ["microsoft visual studio solution"],
  minid: ["minid"],
  druby: ["mirah"],
  duby: ["mirah"],
  mirah: ["mirah"],
  mo: ["modelica"],
  i3: ["modula-3"],
  ig: ["modula-3"],
  m3: ["modula-3"],
  mg: ["modula-3"],
  mms: ["module management system"],
  mmk: ["module management system"],
  monkey: ["monkey"],
  monkey2: ["monkey"],
  moon: ["moonscript"],
  s: ["motorola 68k assembly", "unix assembly"],
  x68: ["motorola 68k assembly"],
  muse: ["muse"],
  mustache: ["mustache"],
  myt: ["myghty"],
  nasl: ["nasl"],
  neon: ["neon"],
  nl: ["nl", "newlisp"],
  nsi: ["nsis"],
  nsh: ["nsis"],
  nss: ["nwscript"],
  ne: ["nearley"],
  nearley: ["nearley"],
  n: ["nemerle", "roff"],
  axs: ["netlinx"],
  axi: ["netlinx"],
  "axs.erb": ["netlinx+erb"],
  "axi.erb": ["netlinx+erb"],
  nlogo: ["netlogo"],
  nf: ["nextflow"],
  nginx: ["nginx"],
  nginxconf: ["nginx"],
  nim: ["nim"],
  "nim.cfg": ["nim"],
  nimble: ["nim"],
  nimrod: ["nim"],
  nims: ["nim"],
  ninja: ["ninja"],
  nit: ["nit"],
  nix: ["nix"],
  nu: ["nu"],
  numpy: ["numpy"],
  numpyw: ["numpy"],
  numsc: ["numpy"],
  njk: ["nunjucks"],
  ml: ["ocaml", "standard ml"],
  eliom: ["ocaml"],
  eliomi: ["ocaml"],
  ml4: ["ocaml"],
  mli: ["ocaml"],
  mll: ["ocaml"],
  mly: ["ocaml"],
  objdump: ["objdump"],
  odin: ["object data instance notation", "odin"],
  mm: ["objective-c++", "xml"],
  sj: ["objective-j"],
  omgrofl: ["omgrofl"],
  opa: ["opa"],
  opal: ["opal"],
  rego: ["open policy agent"],
  opencl: ["opencl"],
  qasm: ["openqasm"],
  scad: ["openscad"],
  plist: ["openstep property list", "xml property list"],
  glyphs: ["openstep property list"],
  fea: ["opentype feature file"],
  org: ["org"],
  ox: ["ox"],
  oxh: ["ox"],
  oxo: ["ox"],
  oxygene: ["oxygene"],
  oz: ["oz"],
  p4: ["p4"],
  pegjs: ["peg.js"],
  aw: ["php"],
  ctp: ["php"],
  php3: ["php"],
  php4: ["php"],
  php5: ["php"],
  phps: ["php"],
  phpt: ["php"],
  pls: ["plsql"],
  bdy: ["plsql"],
  ddl: ["plsql", "sql"],
  fnc: ["plsql"],
  pck: ["plsql"],
  pkb: ["plsql"],
  pks: ["plsql"],
  plb: ["plsql"],
  plsql: ["plsql"],
  prc: ["plsql", "sql"],
  spc: ["plsql"],
  sql: ["plsql", "plpgsql", "sql", "sqlpl", "tsql"],
  tpb: ["plsql"],
  tps: ["plsql"],
  trg: ["plsql"],
  vw: ["plsql"],
  pgsql: ["plpgsql"],
  pov: ["pov-ray sdl"],
  pan: ["pan"],
  psc: ["papyrus"],
  parrot: ["parrot"],
  pasm: ["parrot assembly"],
  pir: ["parrot internal representation"],
  pas: ["pascal"],
  dfm: ["pascal"],
  dpr: ["pascal"],
  lpr: ["pascal"],
  pascal: ["pascal"],
  pp: ["pascal", "puppet"],
  pwn: ["pawn"],
  sma: ["pawn"],
  pep: ["pep8"],
  pl: ["perl", "prolog", "raku"],
  cgi: ["perl", "python", "shell"],
  perl: ["perl"],
  ph: ["perl"],
  plx: ["perl"],
  pm: ["perl", "raku", "x pixmap"],
  psgi: ["perl"],
  t: ["perl", "raku", "terra", "turing"],
  pic: ["pic"],
  chem: ["pic"],
  pkl: ["pickle"],
  pig: ["piglatin"],
  pike: ["pike"],
  pmod: ["pike"],
  puml: ["plantuml"],
  iuml: ["plantuml"],
  plantuml: ["plantuml"],
  pod: ["pod", "pod 6"],
  pod6: ["pod 6"],
  pogo: ["pogoscript"],
  pony: ["pony"],
  pcss: ["postcss"],
  postcss: ["postcss"],
  ps: ["postscript"],
  eps: ["postscript"],
  epsi: ["postscript"],
  pfa: ["postscript"],
  pbt: ["powerbuilder"],
  sra: ["powerbuilder"],
  sru: ["powerbuilder"],
  srw: ["powerbuilder"],
  ps1: ["powershell"],
  psd1: ["powershell"],
  psm1: ["powershell"],
  prisma: ["prisma"],
  pde: ["processing"],
  prolog: ["prolog"],
  yap: ["prolog"],
  spin: ["propeller spin"],
  proto: ["protocol buffer"],
  pub: ["public key"],
  jade: ["pug"],
  pug: ["pug"],
  pd: ["pure data"],
  pb: ["purebasic"],
  pbi: ["purebasic"],
  purs: ["purescript"],
  py: ["python"],
  gyp: ["python"],
  gypi: ["python"],
  lmi: ["python"],
  py3: ["python"],
  pyde: ["python"],
  pyi: ["python"],
  pyp: ["python"],
  pyt: ["python"],
  pyw: ["python"],
  rpy: ["python", "ren'py"],
  smk: ["python"],
  spec: ["python", "rpm spec", "ruby"],
  tac: ["python"],
  wsgi: ["python"],
  xpy: ["python"],
  pytb: ["python traceback"],
  qs: ["q#", "qt script"],
  qml: ["qml"],
  qbs: ["qml"],
  pri: ["qmake"],
  r: ["r", "rebol"],
  rd: ["r"],
  rsx: ["r"],
  raml: ["raml"],
  rdoc: ["rdoc"],
  rbbas: ["realbasic"],
  rbfrm: ["realbasic"],
  rbmnu: ["realbasic"],
  rbres: ["realbasic"],
  rbtbar: ["realbasic"],
  rbuistate: ["realbasic"],
  rexx: ["rexx"],
  pprx: ["rexx"],
  rex: ["rexx"],
  rmd: ["rmarkdown"],
  rnh: ["runoff"],
  rno: ["runoff", "roff"],
  rkt: ["racket"],
  rktd: ["racket"],
  rktl: ["racket"],
  scrbl: ["racket"],
  rl: ["ragel"],
  "6pl": ["raku"],
  "6pm": ["raku"],
  nqp: ["raku"],
  p6: ["raku"],
  p6l: ["raku"],
  p6m: ["raku"],
  pl6: ["raku"],
  pm6: ["raku"],
  raku: ["raku"],
  rakumod: ["raku"],
  rsc: ["rascal"],
  raw: ["raw token data"],
  res: ["rescript", "xml"],
  rei: ["reason"],
  reb: ["rebol"],
  r2: ["rebol"],
  r3: ["rebol"],
  rebol: ["rebol"],
  red: ["red"],
  reds: ["red"],
  cw: ["redcode"],
  regexp: ["regular expression"],
  regex: ["regular expression"],
  rs: ["renderscript", "rust", "xml"],
  rsh: ["renderscript"],
  rtf: ["rich text format"],
  ring: ["ring"],
  riot: ["riot"],
  robot: ["robotframework"],
  roff: ["roff"],
  "1in": ["roff", "roff manpage"],
  "1m": ["roff", "roff manpage"],
  "1x": ["roff", "roff manpage"],
  "3in": ["roff", "roff manpage"],
  "3m": ["roff", "roff manpage"],
  "3p": ["roff", "roff manpage"],
  "3pm": ["roff", "roff manpage"],
  "3qt": ["roff", "roff manpage"],
  "3x": ["roff", "roff manpage"],
  man: ["roff", "roff manpage"],
  mdoc: ["roff", "roff manpage"],
  me: ["roff"],
  nr: ["roff"],
  tmac: ["roff"],
  rg: ["rouge"],
  rb: ["ruby"],
  builder: ["ruby"],
  eye: ["ruby"],
  gemspec: ["ruby"],
  god: ["ruby"],
  jbuilder: ["ruby"],
  mspec: ["ruby"],
  pluginspec: ["ruby", "xml"],
  podspec: ["ruby"],
  prawn: ["ruby"],
  rabl: ["ruby"],
  rake: ["ruby"],
  rbi: ["ruby"],
  rbuild: ["ruby"],
  rbw: ["ruby"],
  rbx: ["ruby"],
  ru: ["ruby"],
  ruby: ["ruby"],
  thor: ["ruby"],
  watchr: ["ruby"],
  "rs.in": ["rust"],
  sas: ["sas"],
  scss: ["scss"],
  te: ["selinux policy"],
  smt2: ["smt"],
  smt: ["smt"],
  sparql: ["sparql"],
  rq: ["sparql"],
  sqf: ["sqf"],
  hqf: ["sqf"],
  cql: ["sql"],
  mysql: ["sql"],
  tab: ["sql"],
  udf: ["sql"],
  viw: ["sql"],
  db2: ["sqlpl"],
  srt: ["srecode template", "subrip text"],
  ston: ["ston"],
  svg: ["svg"],
  sage: ["sage"],
  sagews: ["sage"],
  sls: ["saltstack", "scheme"],
  sass: ["sass"],
  scala: ["scala"],
  kojo: ["scala"],
  sbt: ["scala"],
  sc: ["scala", "supercollider"],
  scaml: ["scaml"],
  scm: ["scheme"],
  sld: ["scheme"],
  sps: ["scheme"],
  ss: ["scheme"],
  sci: ["scilab"],
  sce: ["scilab"],
  self: ["self"],
  sh: ["shell"],
  bash: ["shell"],
  bats: ["shell"],
  command: ["shell"],
  env: ["shell"],
  ksh: ["shell"],
  "sh.in": ["shell"],
  tmux: ["shell"],
  tool: ["shell"],
  zsh: ["shell"],
  "sh-session": ["shellsession"],
  shen: ["shen"],
  sieve: ["sieve"],
  sl: ["slash"],
  slim: ["slim"],
  cocci: ["smpl"],
  smali: ["smali"],
  st: ["smalltalk", "stringtemplate"],
  tpl: ["smarty"],
  sp: ["sourcepawn"],
  sfd: ["spline font database"],
  nut: ["squirrel"],
  stan: ["stan"],
  fun: ["standard ml"],
  sig: ["standard ml"],
  sml: ["standard ml"],
  bzl: ["starlark"],
  do: ["stata"],
  ado: ["stata"],
  doh: ["stata"],
  ihlp: ["stata"],
  mata: ["stata"],
  matah: ["stata"],
  sthlp: ["stata"],
  styl: ["stylus"],
  sss: ["sugarss"],
  svelte: ["svelte"],
  swift: ["swift"],
  sv: ["systemverilog"],
  svh: ["systemverilog"],
  vh: ["systemverilog"],
  "8xp": ["ti program"],
  "8xk": ["ti program"],
  "8xk.txt": ["ti program"],
  "8xp.txt": ["ti program"],
  tla: ["tla"],
  toml: ["toml"],
  tsv: ["tsv"],
  tsx: ["tsx", "xml"],
  txl: ["txl"],
  tcl: ["tcl"],
  adp: ["tcl"],
  "tcl.in": ["tcl"],
  tm: ["tcl"],
  tcsh: ["tcsh"],
  csh: ["tcsh"],
  tex: ["tex"],
  aux: ["tex"],
  bbx: ["tex"],
  cbx: ["tex"],
  dtx: ["tex"],
  ins: ["tex"],
  lbx: ["tex"],
  ltx: ["tex"],
  mkii: ["tex"],
  mkiv: ["tex"],
  mkvi: ["tex"],
  sty: ["tex"],
  toc: ["tex", "world of warcraft addon data"],
  tea: ["tea"],
  texinfo: ["texinfo"],
  texi: ["texinfo"],
  txi: ["texinfo"],
  txt: ["text", "vim help file"],
  no: ["text"],
  textile: ["textile"],
  thrift: ["thrift"],
  tu: ["turing"],
  ttl: ["turtle"],
  twig: ["twig"],
  tl: ["type language"],
  ts: ["typescript", "xml"],
  upc: ["unified parallel c"],
  anim: ["unity3d asset"],
  asset: ["unity3d asset"],
  mat: ["unity3d asset"],
  meta: ["unity3d asset"],
  prefab: ["unity3d asset"],
  unity: ["unity3d asset"],
  uno: ["uno"],
  uc: ["unrealscript"],
  ur: ["urweb"],
  urs: ["urweb"],
  frm: ["vba"],
  frx: ["vba"],
  vba: ["vba", "vim script"],
  vbs: ["vbscript"],
  vcl: ["vcl"],
  vhdl: ["vhdl"],
  vhd: ["vhdl"],
  vhf: ["vhdl"],
  vhi: ["vhdl"],
  vho: ["vhdl"],
  vhs: ["vhdl"],
  vht: ["vhdl"],
  vhw: ["vhdl"],
  vala: ["vala"],
  vapi: ["vala"],
  vdf: ["valve data format"],
  veo: ["verilog"],
  vim: ["vim script"],
  vmb: ["vim script"],
  snip: ["vim snippet"],
  snippet: ["vim snippet"],
  snippets: ["vim snippet"],
  vb: ["visual basic .net"],
  vbhtml: ["visual basic .net"],
  volt: ["volt"],
  vue: ["vue"],
  mtl: ["wavefront material"],
  obj: ["wavefront object"],
  owl: ["web ontology language"],
  wast: ["webassembly"],
  wat: ["webassembly"],
  webidl: ["webidl"],
  vtt: ["webvtt"],
  mediawiki: ["wikitext"],
  wiki: ["wikitext"],
  wikitext: ["wikitext"],
  reg: ["windows registry entries"],
  wlk: ["wollok"],
  xbm: ["x bitmap"],
  xpm: ["x pixmap"],
  x10: ["x10"],
  xc: ["xc"],
  xml: ["xml"],
  adml: ["xml"],
  admx: ["xml"],
  ant: ["xml"],
  axml: ["xml"],
  builds: ["xml"],
  ccproj: ["xml"],
  ccxml: ["xml"],
  clixml: ["xml"],
  cproject: ["xml"],
  cscfg: ["xml"],
  csdef: ["xml"],
  csproj: ["xml"],
  ct: ["xml"],
  depproj: ["xml"],
  dita: ["xml"],
  ditamap: ["xml"],
  ditaval: ["xml"],
  "dll.config": ["xml"],
  dotsettings: ["xml"],
  filters: ["xml"],
  fsproj: ["xml"],
  fxml: ["xml"],
  glade: ["xml"],
  gmx: ["xml"],
  grxml: ["xml"],
  iml: ["xml"],
  ivy: ["xml"],
  jelly: ["xml"],
  jsproj: ["xml"],
  kml: ["xml"],
  launch: ["xml"],
  mdpolicy: ["xml"],
  mjml: ["xml"],
  mxml: ["xml"],
  natvis: ["xml"],
  ndproj: ["xml"],
  nproj: ["xml"],
  nuspec: ["xml"],
  odd: ["xml"],
  osm: ["xml"],
  pkgproj: ["xml"],
  proj: ["xml"],
  props: ["xml"],
  ps1xml: ["xml"],
  psc1: ["xml"],
  pt: ["xml"],
  rdf: ["xml"],
  resx: ["xml"],
  rss: ["xml"],
  scxml: ["xml"],
  sfproj: ["xml"],
  shproj: ["xml"],
  srdf: ["xml"],
  storyboard: ["xml"],
  "sublime-snippet": ["xml"],
  targets: ["xml"],
  tml: ["xml"],
  ui: ["xml"],
  urdf: ["xml"],
  ux: ["xml"],
  vbproj: ["xml"],
  vcxproj: ["xml"],
  vsixmanifest: ["xml"],
  vssettings: ["xml"],
  vstemplate: ["xml"],
  vxml: ["xml"],
  wixproj: ["xml"],
  wsdl: ["xml"],
  wsf: ["xml"],
  wxi: ["xml"],
  wxl: ["xml"],
  wxs: ["xml"],
  x3d: ["xml"],
  xacro: ["xml"],
  xaml: ["xml"],
  xib: ["xml"],
  xlf: ["xml"],
  xliff: ["xml"],
  xmi: ["xml"],
  "xml.dist": ["xml"],
  xmp: ["xml"],
  xproj: ["xml"],
  xsd: ["xml"],
  xspec: ["xml"],
  xul: ["xml"],
  zcml: ["xml"],
  stTheme: ["xml property list"],
  tmCommand: ["xml property list"],
  tmLanguage: ["xml property list"],
  tmPreferences: ["xml property list"],
  tmSnippet: ["xml property list"],
  tmTheme: ["xml property list"],
  "xsp-config": ["xpages"],
  "xsp.metadata": ["xpages"],
  xpl: ["xproc"],
  xproc: ["xproc"],
  xquery: ["xquery"],
  xq: ["xquery"],
  xql: ["xquery"],
  xqm: ["xquery"],
  xqy: ["xquery"],
  xs: ["xs"],
  xslt: ["xslt"],
  xsl: ["xslt"],
  xojo_code: ["xojo"],
  xojo_menu: ["xojo"],
  xojo_report: ["xojo"],
  xojo_script: ["xojo"],
  xojo_toolbar: ["xojo"],
  xojo_window: ["xojo"],
  xsh: ["xonsh"],
  xtend: ["xtend"],
  yml: ["yaml"],
  mir: ["yaml"],
  reek: ["yaml"],
  rviz: ["yaml"],
  "sublime-syntax": ["yaml"],
  syntax: ["yaml"],
  yaml: ["yaml"],
  "yaml-tmlanguage": ["yaml"],
  "yaml.sed": ["yaml"],
  "yml.mysql": ["yaml"],
  yang: ["yang"],
  yar: ["yara"],
  yara: ["yara"],
  yasnippet: ["yasnippet"],
  y: ["yacc"],
  yacc: ["yacc"],
  zap: ["zap"],
  xzap: ["zap"],
  zil: ["zil"],
  mud: ["zil"],
  zeek: ["zeek"],
  bro: ["zeek"],
  zs: ["zenscript"],
  zep: ["zephir"],
  zig: ["zig"],
  zimpl: ["zimpl"],
  zmpl: ["zimpl"],
  zpl: ["zimpl"],
  desktop: ["desktop"],
  "desktop.in": ["desktop"],
  dircolors: ["dircolors"],
  ec: ["ec"],
  eh: ["ec"],
  edn: ["edn"],
  fish: ["fish"],
  mrc: ["mirc script"],
  mcfunction: ["mcfunction"],
  mu: ["mupad"],
  nanorc: ["nanorc"],
  nc: ["nesc"],
  ooc: ["ooc"],
  rst: ["restructuredtext"],
  rest: ["restructuredtext"],
  "rest.txt": ["restructuredtext"],
  "rst.txt": ["restructuredtext"],
  sed: ["sed"],
  wdl: ["wdl"],
  wisp: ["wisp"],
  prg: ["xbase"],
  prw: ["xbase"],
};
