export const operatorData = {
  operators: {
    TOP: {
      description: "Texture Operators - for image processing and manipulation",
      operators: [
        { name: "Add", description: "" },
        { name: "Analyze", description: "" },
        { name: "Anti Alias", description: "" },
        { name: "Blob Track", description: "" },
        { name: "Bloom", description: "" },
        { name: "Blur", description: "" },
        { name: "Cache Select", description: "" },
        { name: "Cache", description: "" },
        { name: "Channel Mix", description: "" },
        { name: "CHOP to TOP", description: "" },
        { name: "Chroma Key", description: "" },
        { name: "Circle", description: "" },
        { name: "Composite", description: "" },
        { name: "Constant", description: "" },
        { name: "Convolve", description: "" },
        { name: "Corner Pin", description: "" },
        { name: "CPlusPlus", description: "" },
        { name: "Crop", description: "" },
        { name: "Cross", description: "" },
        { name: "Cube Map", description: "" },
        { name: "Depth", description: "" },
        { name: "Difference", description: "" },
        { name: "Direct Display Out", description: "" },
        { name: "DirectX In", description: "" },
        { name: "DirectX Out", description: "" },
        { name: "Displace", description: "" },
        { name: "Edge", description: "" },
        { name: "Emboss", description: "" },
        { name: "Feedback", description: "" },
        { name: "Fit", description: "" },
        { name: "Flip", description: "" },
        { name: "Function", description: "" },
        { name: "GLSL Multi", description: "" },
        { name: "GLSL", description: "" },
        { name: "HSV Adjust", description: "" },
        { name: "HSV to RGB", description: "" },
        { name: "Import Select", description: "" },
        { name: "In", description: "" },
        { name: "Inside", description: "" },
        { name: "Layout", description: "" },
        { name: "Lens Distort", description: "" },
        { name: "Level", description: "" },
        { name: "Limit", description: "" },
        { name: "Lookup", description: "" },
        { name: "Luma Blur", description: "" },
        { name: "Luma Level", description: "" },
        { name: "Math", description: "" },
        { name: "Matte", description: "" },
        { name: "Mirror", description: "" },
        { name: "Monochrome", description: "" },
        { name: "Movie File In", description: "" },
        { name: "Movie File Out", description: "" },
        { name: "MPCDI", description: "" },
        { name: "Multiply", description: "" },
        { name: "NDI In", description: "" },
        { name: "NDI Out", description: "" },
        { name: "Noise", description: "" },
        { name: "Normal Map", description: "" },
        { name: "Null", description: "" },
        { name: "OP Viewer", description: "" },
        { name: "OpenColorIO", description: "" },
        { name: "OpenVR", description: "" },
        { name: "Optical Flow", description: "" },
        { name: "Out", description: "" },
        { name: "Outside", description: "" },
        { name: "Over", description: "" },
        { name: "Pack", description: "" },
        { name: "Point File In", description: "" },
        { name: "Point Transform", description: "" },
        { name: "PreFilter Map", description: "" },
        { name: "Projection", description: "" },
        { name: "Ramp", description: "" },
        { name: "Rectangle", description: "" },
        { name: "Remap", description: "" },
        { name: "Render Pass", description: "" },
        { name: "Render Select", description: "" },
        { name: "Render", description: "" },
        { name: "Reorder", description: "" },
        { name: "Resolution", description: "" },
        { name: "RGB Key", description: "" },
        { name: "RGB to HSV", description: "" },
        { name: "Screen Grab", description: "" },
        { name: "Screen", description: "" },
        { name: "Script", description: "" },
        { name: "Select", description: "" },
        { name: "Shared Mem In", description: "" },
        { name: "Shared Mem Out", description: "" },
        { name: "Slope", description: "" },
        { name: "Spectrum", description: "" },
        { name: "SSAO", description: "" },
        { name: "Subtract", description: "" },
        { name: "SVG", description: "" },
        { name: "Switch", description: "" },
        { name: "Text", description: "" },
        { name: "Texture 3D", description: "" },
        { name: "Threshold", description: "" },
        { name: "Tile", description: "" },
        { name: "Time Machine", description: "" },
        { name: "Touch In", description: "" },
        { name: "Touch Out", description: "" },
        { name: "Transform", description: "" },
        { name: "Under", description: "" },
        { name: "Video Device In", description: "" },
        { name: "Video Device Out", description: "" },
        { name: "Video Stream In", description: "" },
        { name: "Video Stream Out", description: "" },
        { name: "Web Render", description: "" },
      ],
    },
    CHOP: {
      description: "Channel Operators - for processing motion, audio, math, and data",
      operators: [
        { name: "Constant", description: "Create new channels", sweet: true },
        { name: "LFO", description: "Low Frequency Oscillator", sweet: true },
        { name: "Noise", description: "Create semi-random patterns", sweet: true },
        { name: "Select", description: "Grab a channel from any other CHOP", sweet: true },
        { name: "Merge", description: "Merge channels from two or more CHOPs", sweet: true },
        { name: "Math", description: "Add, multiply or scale channels", sweet: true },
        { name: "Lag", description: "Smooth and delay a channel", sweet: true },
        { name: "Speed", description: "Use speed to calculate distance", sweet: true },
        { name: "Lookup", description: "Use one channel to get values from another CHOP", sweet: true },
        { name: "Trail", description: "Watch a time-history of CHOP channels", sweet: true },
        { name: "Limit", description: "Restrict channels to a range or certain step values", sweet: true },
        { name: "Audio Device In", description: "Get audio from input device", sweet: true },
        { name: "OSC In", description: "Open Sound Control, MIDI", sweet: true },
        { name: "Panel", description: "Get state, u, v etc values from any panel gadget", sweet: true },
        { name: "Timer", description: "Run timers, loops, delays and trigger events", sweet: true },
      ],
    },
    SOP: {
      description: "Surface Operators - for 3D geometry manipulation",
      operators: [
        { name: "Circle", description: "Circle, sphere, torus primitives", sweet: true },
        { name: "Grid", description: "Grid, box, rectangle", sweet: true },
        { name: "Merge", description: "Merge and delete", sweet: true },
        { name: "Copy", description: "Copy or replicate", sweet: true },
        { name: "Switch", description: "Switch or blend multi-inputs", sweet: true },
        { name: "Texture", description: "Apply texture coordinated to points or vertices", sweet: true },
        { name: "Noise", description: "Apply noise, twist and deform", sweet: true },
        { name: "Transform", description: "Transform point positions", sweet: true },
        { name: "DAT to", description: "DAT table to SOP points", sweet: true },
        { name: "CHOP to", description: "CHOP channel samples to SOP points", sweet: true },
        { name: "Line", description: "Trace a TOP image to polygons", sweet: true },
        { name: "Clip", description: "Clip and carve", sweet: true },
        { name: "Facet", description: "Facet, subdivide, convert", sweet: true },
        { name: "Particle", description: "Particles", sweet: true },
        { name: "Sweep", description: "Sweep, skin, rails", sweet: true },
        { name: "Sort", description: "Sort and reorder", sweet: true },
      ],
    },
    MAT: {
      description: "Material Operators - for applying shaders to 3D geometry",
      operators: [
        { name: "Phong", description: "Applies a phong shader with lighting options" },
        { name: "PBR", description: "Applies a PBR shader, works with Environment Light COMP" },
        { name: "Line", description: "Renders geometry edges as lines and points" },
        { name: "Constant", description: "Applies flat color without specular shading" },
        { name: "Depth", description: "Gets depth information for depth-pass render" },
        { name: "GLSL", description: "Applies custom GLSL pixel and vertex shaders" },
        { name: "Point Sprite", description: "Special material for Point Sprite geometry" },
      ],
    },
    COMP: {
      description: "Components - containers that can hold networks of other operators",
      operators: [
        { name: "Ambient Light", description: "", category: "object_components" },
        { name: "Blend", description: "", category: "object_components" },
        { name: "Bone", description: "", category: "object_components" },
        { name: "Camera", description: "", category: "object_components" },
        { name: "Camera Blend", description: "", category: "object_components" },
        { name: "Environment Light", description: "", category: "object_components" },
        { name: "Nvidia Flow Emitter", description: "", category: "object_components" },
        { name: "Geometry", description: "", category: "object_components" },
        { name: "Handle", description: "", category: "object_components" },
        { name: "Light", description: "", category: "object_components" },
        { name: "Null", description: "", category: "object_components" },
        { name: "Shared Mem In", description: "", category: "object_components" },
        { name: "Shared Mem Out", description: "", category: "object_components" },
        { name: "FBX", description: "", category: "object_components" },
        { name: "USD", description: "", category: "object_components" },
        { name: "Button", description: "", category: "panel_components" },
        { name: "Container", description: "", category: "panel_components" },
        { name: "Field", description: "", category: "panel_components" },
        { name: "List", description: "", category: "panel_components" },
        { name: "OP Viewer", description: "", category: "panel_components" },
        { name: "Parameter", description: "", category: "panel_components" },
        { name: "Select", description: "", category: "panel_components" },
        { name: "Slider", description: "", category: "panel_components" },
        { name: "Table", description: "", category: "panel_components" },
        { name: "Widget", description: "", category: "panel_components" },
        { name: "Base", description: "", category: "misc_components" },
        { name: "Engine", description: "", category: "misc_components" },
        { name: "Time", description: "", category: "misc_components" },
        { name: "Animation", description: "", category: "misc_components" },
        { name: "Replicator", description: "", category: "misc_components" },
        { name: "Window", description: "", category: "misc_components" },
      ],
    },
  },
};
