export interface MaterialValue {
  name: string;
  value: string;
  type: "ior" | "color";
  keywords?: string[];
  srgb?: string;
}

export const IOR_VALUES: MaterialValue[] = [
  {
    name: "Banana",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Blackboard",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Blood",
    value: "1.35",
    type: "ior",
  },
  {
    name: "Bone",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Brick",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Car Paint",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Carrot",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Charcoal",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Chocolate",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Coffee",
    value: "1.34",
    type: "ior",
  },
  {
    name: "Concrete",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Cooking Oil",
    value: "1.47",
    type: "ior",
  },
  {
    name: "Diamond",
    value: "2.4168",
    type: "ior",
  },
  {
    name: "Egg Shell",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Eye (Cornea)",
    value: "1.376",
    type: "ior",
  },
  {
    name: "Eye (Lens)",
    value: "1.386",
    type: "ior",
  },
  {
    name: "Eye (Sclera)",
    value: "1.4",
    type: "ior",
  },
  {
    name: "Gasoline",
    value: "1.427",
    type: "ior",
  },
  {
    name: "Glass",
    value: "1.52",
    type: "ior",
  },
  {
    name: "Gray Card",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Honey (Crystallized)",
    value: "1.504",
    type: "ior",
  },
  {
    name: "Honey (Liquid)",
    value: "1.504",
    type: "ior",
  },
  {
    name: "Ice",
    value: "1.3098",
    type: "ior",
  },
  {
    name: "Ketchup",
    value: "1.3",
    type: "ior",
  },
  {
    name: "Lemon",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Marble",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Milk",
    value: "1.348",
    type: "ior",
  },
  {
    name: "MIT Black",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Musou Black",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Office Paper",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Pearl",
    value: "1.68",
    type: "ior",
  },
  {
    name: "Petroleum",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Plastic (Acrylic)",
    value: "1.4905",
    type: "ior",
  },
  {
    name: "Plastic (PC)",
    value: "1.5848",
    type: "ior",
  },
  {
    name: "Plastic (PET)",
    value: "1.575",
    type: "ior",
  },
  {
    name: "Plastic (PP)",
    value: "1.492",
    type: "ior",
  },
  {
    name: "Plastic (PUR)",
    value: "1.6",
    type: "ior",
  },
  {
    name: "Plastic (PVC)",
    value: "1.542",
    type: "ior",
  },
  {
    name: "Quartz",
    value: "1.54",
    type: "ior",
  },
  {
    name: "Salt",
    value: "1.5441",
    type: "ior",
  },
  {
    name: "Sand",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Sapphire",
    value: "1.7682",
    type: "ior",
  },
  {
    name: "Skin I",
    value: "1.4",
    type: "ior",
  },
  {
    name: "Skin II",
    value: "1.4",
    type: "ior",
  },
  {
    name: "Skin III",
    value: "1.4",
    type: "ior",
  },
  {
    name: "Skin IV",
    value: "1.4",
    type: "ior",
  },
  {
    name: "Skin V",
    value: "1.4",
    type: "ior",
  },
  {
    name: "Skin VI",
    value: "1.4",
    type: "ior",
  },
  {
    name: "Snow",
    value: "1.3098",
    type: "ior",
  },
  {
    name: "Soap Bubble",
    value: "1",
    type: "ior",
  },
  {
    name: "Tire",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Toner (Black)",
    value: "1.5",
    type: "ior",
  },
  {
    name: "Water",
    value: "1.3325",
    type: "ior",
  },
  {
    name: "Whiteboard",
    value: "1.5",
    type: "ior",
  },
];

export const PBR_COLORS: MaterialValue[] = [
  {
    name: "Aluminum",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Banana",
    value: "#D0C15E",
    type: "color",
    srgb: "208, 193, 94",
  },
  {
    name: "Beryllium",
    value: "#C2C1C1",
    type: "color",
    srgb: "194, 193, 193",
  },
  {
    name: "Blackboard",
    value: "#383838",
    type: "color",
    srgb: "56, 56, 56",
  },
  {
    name: "Blood",
    value: "#D21E1E",
    type: "color",
    srgb: "210, 30, 30",
  },
  {
    name: "Bone",
    value: "#E6E6D5",
    type: "color",
    srgb: "230, 230, 213",
  },
  {
    name: "Brass",
    value: "#F0E4AE",
    type: "color",
    srgb: "240, 228, 174",
  },
  {
    name: "Brick",
    value: "#8C5746",
    type: "color",
    srgb: "140, 87, 70",
  },
  {
    name: "Car Paint",
    value: "#595959",
    type: "color",
    srgb: "89, 89, 89",
  },
  {
    name: "Carrot",
    value: "#DC732D",
    type: "color",
    srgb: "220, 115, 45",
  },
  {
    name: "Cesium",
    value: "#DCC486",
    type: "color",
    srgb: "220, 196, 134",
  },
  {
    name: "Charcoal",
    value: "#272727",
    type: "color",
    srgb: "39, 39, 39",
  },
  {
    name: "Chocolate",
    value: "#705545",
    type: "color",
    srgb: "112, 85, 69",
  },
  {
    name: "Chromium",
    value: "#D3D8DA",
    type: "color",
    srgb: "211, 216, 218",
  },
  {
    name: "Cobalt",
    value: "#DADAD6",
    type: "color",
    srgb: "218, 218, 214",
  },
  {
    name: "Coffee",
    value: "#B26634",
    type: "color",
    srgb: "178, 102, 52",
  },
  {
    name: "Concrete",
    value: "#BDBDBD",
    type: "color",
    srgb: "189, 189, 189",
  },
  {
    name: "Cooking Oil",
    value: "#DFD855",
    type: "color",
    srgb: "223, 216, 85",
  },
  {
    name: "Copper",
    value: "#F0CFBF",
    type: "color",
    srgb: "240, 207, 191",
  },
  {
    name: "Diamond",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Egg Shell",
    value: "#CDCFD0",
    type: "color",
    srgb: "205, 207, 208",
  },
  {
    name: "Eye (Cornea)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Eye (Lens)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Eye (Sclera)",
    value: "#D3BCA8",
    type: "color",
    srgb: "211, 188, 168",
  },
  {
    name: "Gasoline",
    value: "#F0F0CE",
    type: "color",
    srgb: "240, 240, 206",
  },
  {
    name: "Germanium",
    value: "#BCBEB6",
    type: "color",
    srgb: "188, 190, 182",
  },
  {
    name: "Glass",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Gold",
    value: "#F0E496",
    type: "color",
    srgb: "240, 228, 150",
  },
  {
    name: "Gray 0% (PBR Safe)",
    value: "#1E1E1E",
    type: "color",
    srgb: "30, 30, 30",
  },
  {
    name: "Gray 10% (PBR Safe)",
    value: "#333333",
    type: "color",
    srgb: "51, 51, 51",
  },
  {
    name: "Gray 100% (PBR Safe)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Gray 20% (PBR Safe)",
    value: "#484848",
    type: "color",
    srgb: "72, 72, 72",
  },
  {
    name: "Gray 30% (PBR Safe)",
    value: "#5D5D5D",
    type: "color",
    srgb: "93, 93, 93",
  },
  {
    name: "Gray 40% (PBR Safe)",
    value: "#727272",
    type: "color",
    srgb: "114, 114, 114",
  },
  {
    name: "Gray 50% (PBR Safe)",
    value: "#878787",
    type: "color",
    srgb: "135, 135, 135",
  },
  {
    name: "Gray 60% (PBR Safe)",
    value: "#9C9C9C",
    type: "color",
    srgb: "156, 156, 156",
  },
  {
    name: "Gray 70% (PBR Safe)",
    value: "#B1B1B1",
    type: "color",
    srgb: "177, 177, 177",
  },
  {
    name: "Gray 80% (PBR Safe)",
    value: "#C6C6C6",
    type: "color",
    srgb: "198, 198, 198",
  },
  {
    name: "Gray 90% (PBR Safe)",
    value: "#DBDBDB",
    type: "color",
    srgb: "219, 219, 219",
  },
  {
    name: "Gray Card",
    value: "#767676",
    type: "color",
    srgb: "118, 118, 118",
  },
  {
    name: "Honey (Crystallized)",
    value: "#B3991E",
    type: "color",
    srgb: "179, 153, 30",
  },
  {
    name: "Honey (Liquid)",
    value: "#EBC736",
    type: "color",
    srgb: "235, 199, 54",
  },
  {
    name: "Ice",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Iridium",
    value: "#E0DEDA",
    type: "color",
    srgb: "224, 222, 218",
  },
  {
    name: "Iron",
    value: "#C0BEBB",
    type: "color",
    srgb: "192, 190, 187",
  },
  {
    name: "Ketchup",
    value: "#711E1E",
    type: "color",
    srgb: "113, 30, 30",
  },
  {
    name: "Lead",
    value: "#CFD1D9",
    type: "color",
    srgb: "207, 209, 217",
  },
  {
    name: "Lemon",
    value: "#DCB91E",
    type: "color",
    srgb: "220, 185, 30",
  },
  {
    name: "Lithium",
    value: "#F0F0E8",
    type: "color",
    srgb: "240, 240, 232",
  },
  {
    name: "Magnesium",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Manganese",
    value: "#CCCAC7",
    type: "color",
    srgb: "204, 202, 199",
  },
  {
    name: "Marble",
    value: "#EBE6E1",
    type: "color",
    srgb: "235, 230, 225",
  },
  {
    name: "Mercury",
    value: "#E5E5E4",
    type: "color",
    srgb: "229, 229, 228",
  },
  {
    name: "Milk",
    value: "#E9E9D7",
    type: "color",
    srgb: "233, 233, 215",
  },
  {
    name: "MIT Black",
    value: "#1E1E1E",
    type: "color",
    srgb: "30, 30, 30",
  },
  {
    name: "Molybdenum",
    value: "#CACDCB",
    type: "color",
    srgb: "202, 205, 203",
  },
  {
    name: "Musou Black",
    value: "#1E1E1E",
    type: "color",
    srgb: "30, 30, 30",
  },
  {
    name: "Nickel",
    value: "#D9D1C6",
    type: "color",
    srgb: "217, 209, 198",
  },
  {
    name: "Office Paper",
    value: "#E6EBF0",
    type: "color",
    srgb: "230, 235, 240",
  },
  {
    name: "Palladium",
    value: "#DEDAD5",
    type: "color",
    srgb: "222, 218, 213",
  },
  {
    name: "Pearl",
    value: "#E7E1DA",
    type: "color",
    srgb: "231, 225, 218",
  },
  {
    name: "Petroleum",
    value: "#302E2B",
    type: "color",
    srgb: "48, 46, 43",
  },
  {
    name: "Plastic (Acrylic)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Plastic (PC)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Plastic (PET)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Plastic (PP)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Plastic (PUR)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Plastic (PVC)",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Platinum",
    value: "#E3DED7",
    type: "color",
    srgb: "227, 222, 215",
  },
  {
    name: "Potassium",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Quartz",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Rubidium",
    value: "#F0EEE0",
    type: "color",
    srgb: "240, 238, 224",
  },
  {
    name: "Salt",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Sand",
    value: "#B1A784",
    type: "color",
    srgb: "177, 167, 132",
  },
  {
    name: "Sapphire",
    value: "#D6E2EE",
    type: "color",
    srgb: "214, 226, 238",
  },
  {
    name: "Silicon",
    value: "#9FA4AF",
    type: "color",
    srgb: "159, 164, 175",
  },
  {
    name: "Silver",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Skin I",
    value: "#EDD1C4",
    type: "color",
    srgb: "237, 209, 196",
  },
  {
    name: "Skin II",
    value: "#E7B99F",
    type: "color",
    srgb: "231, 185, 159",
  },
  {
    name: "Skin III",
    value: "#CFB09E",
    type: "color",
    srgb: "207, 176, 158",
  },
  {
    name: "Skin IV",
    value: "#B08365",
    type: "color",
    srgb: "176, 131, 101",
  },
  {
    name: "Skin V",
    value: "#916B4F",
    type: "color",
    srgb: "145, 107, 79",
  },
  {
    name: "Skin VI",
    value: "#553F27",
    type: "color",
    srgb: "85, 63, 39",
  },
  {
    name: "Snow",
    value: "#EDEDED",
    type: "color",
    srgb: "237, 237, 237",
  },
  {
    name: "Soap Bubble",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Sodium",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Stainless Steel",
    value: "#D6D1CB",
    type: "color",
    srgb: "214, 209, 203",
  },
  {
    name: "Tire",
    value: "#2A2A2A",
    type: "color",
    srgb: "42, 42, 42",
  },
  {
    name: "Titanium",
    value: "#B1AAA2",
    type: "color",
    srgb: "177, 170, 162",
  },
  {
    name: "Toner (Black)",
    value: "#3F3F3F",
    type: "color",
    srgb: "63, 63, 63",
  },
  {
    name: "Tungsten",
    value: "#C2C1BF",
    type: "color",
    srgb: "194, 193, 191",
  },
  {
    name: "Vanadium",
    value: "#C1C0C3",
    type: "color",
    srgb: "193, 192, 195",
  },
  {
    name: "Water",
    value: "#F0F0F0",
    type: "color",
    srgb: "240, 240, 240",
  },
  {
    name: "Whiteboard",
    value: "#F0EFE3",
    type: "color",
    srgb: "240, 239, 227",
  },
  {
    name: "Zinc",
    value: "#E8EDEF",
    type: "color",
    srgb: "232, 237, 239",
  },
];
