import { ShaderParameter, ShaderConfig } from "../types";
import { COMMON_PARAMETERS } from "../common";

// Brick shader configuration
export const BRICK_PARAMETERS: ShaderParameter[] = [
  // Effect-specific parameters (order 0-99)
  // Grid structure
  {
    id: "gridRows",
    label: "Grid Rows",
    type: "float",
    default: 50,
    min: 10,
    max: 200,
    step: 5,
    shortcut: { modifiers: [], key: "2" },
    decrementShortcut: { modifiers: [], key: "1" },
    category: "effect",
    metadata: true,
    order: 1,
  },
  {
    id: "gridGap",
    label: "Grid Gap",
    type: "float",
    default: 0,
    min: 0,
    max: 20,
    step: 1,
    shortcut: { modifiers: [], key: "w" },
    decrementShortcut: { modifiers: [], key: "q" },
    category: "effect",
    metadata: true,
    order: 2,
  },
  // Square parameters
  {
    id: "squareOpacity",
    label: "Square Opacity",
    type: "float",
    default: 0,
    min: 0,
    max: 100,
    step: 10,
    shortcut: { modifiers: [], key: "y" },
    decrementShortcut: { modifiers: [], key: "t" },
    category: "effect",
    metadata: true,
    order: 3,
  },
  {
    id: "squareBorder",
    label: "Square Border",
    type: "float",
    default: 2,
    min: 0,
    max: 10,
    step: 0.5,
    shortcut: { modifiers: [], key: "i" },
    decrementShortcut: { modifiers: [], key: "u" },
    category: "effect",
    metadata: true,
    order: 4,
  },
  {
    id: "squareRadius",
    label: "Square Radius",
    type: "float",
    default: 5,
    min: 0,
    max: 50,
    step: 2,
    shortcut: { modifiers: [], key: "p" },
    decrementShortcut: { modifiers: [], key: "o" },
    category: "effect",
    metadata: true,
    order: 5,
  },
  // Circle parameters
  {
    id: "circleOpacity",
    label: "Circle Opacity",
    type: "float",
    default: 0,
    min: 0,
    max: 100,
    step: 10,
    shortcut: { modifiers: [], key: "n" },
    decrementShortcut: { modifiers: [], key: "m" },
    category: "effect",
    metadata: true,
    order: 6,
  },
  {
    id: "circleSize",
    label: "Circle Size",
    type: "float",
    default: 0.3,
    min: 0,
    max: 1.0,
    step: 0.05,
    shortcut: { modifiers: [], key: "d" },
    decrementShortcut: { modifiers: [], key: "a" },
    category: "effect",
    metadata: true,
    order: 7,
  },
  {
    id: "circleBorder",
    label: "Circle Border",
    type: "float",
    default: 2,
    min: 0,
    max: 10,
    step: 0.5,
    shortcut: { modifiers: [], key: "f" },
    decrementShortcut: { modifiers: [], key: "b" },
    category: "effect",
    metadata: true,
    order: 8,
  },
  // Color adjustments
  {
    id: "exposure",
    label: "Exposure",
    type: "float",
    default: 1.0,
    min: 0.1,
    max: 2.0,
    step: 0.1,
    shortcut: { modifiers: [], key: "h" },
    decrementShortcut: { modifiers: [], key: "g" },
    category: "effect",
    metadata: true,
    order: 9,
  },
  {
    id: "hue",
    label: "Hue",
    type: "float",
    default: 0,
    min: -180,
    max: 180,
    step: 15,
    shortcut: { modifiers: [], key: "k" },
    decrementShortcut: { modifiers: [], key: "j" },
    category: "effect",
    metadata: true,
    order: 10,
  },
  {
    id: "lightAngle",
    label: "Light Angle",
    type: "float",
    default: 45,
    min: 0,
    max: 360,
    step: 15,
    shortcut: { modifiers: [], key: "l" },
    decrementShortcut: { modifiers: [], key: ";" },
    category: "effect",
    metadata: true,
    order: 11,
  },
  // Common parameters come last
  ...COMMON_PARAMETERS,
];

export const BRICK_CONFIG: ShaderConfig = {
  id: "brick",
  name: "Brick",
  description: "Brick effect (LEGO-like)",
  glslFile: "assets/shaders/brick.glsl",
  processor: "processImageWithBrick",
  parameters: BRICK_PARAMETERS,
};
