import { ShaderParameter, ShaderConfig } from "../types";
import { COMMON_PARAMETERS } from "../common";

// Dither shader configuration
export const DITHER_PARAMETERS: ShaderParameter[] = [
  // Effect-specific parameters (order 0-99)
  {
    id: "pattern",
    label: "Pattern",
    type: "enum",
    default: 0,
    options: [
      { value: "0", label: "Floyd-Steinberg" },
      { value: "1", label: "Bayer" },
    ],
    category: "effect",
    metadata: true,
    shortcut: { modifiers: [], key: "p" },
    order: 1,
  },
  {
    id: "pixelSize",
    label: "Pixel Size",
    type: "int",
    default: 1,
    min: 1,
    max: 19, // Max odd value <= 20
    step: 2, // Step by 2 to get only odd values
    shortcut: { modifiers: [], key: "2" },
    decrementShortcut: { modifiers: [], key: "1" },
    category: "effect",
    metadata: true,
    order: 2,
  },
  {
    id: "threshold",
    label: "Threshold",
    type: "float",
    default: 128,
    min: 0,
    max: 255,
    step: 10,
    shortcut: { modifiers: [], key: "w" },
    decrementShortcut: { modifiers: [], key: "q" },
    category: "effect",
    metadata: true,
    order: 3,
  },
  {
    id: "colorMode",
    label: "Color Mode",
    type: "bool",
    default: false,
    shortcut: { modifiers: [], key: "c" },
    category: "effect",
    metadata: true,
    order: 4,
  },
  {
    id: "monoMode",
    label: "Mono Mode",
    type: "enum",
    default: "grayscale",
    options: [
      { value: "grayscale", label: "B/W (Grayscale)" },
      { value: "mono-r", label: "Red Channel" },
      { value: "mono-g", label: "Green Channel" },
      { value: "mono-b", label: "Blue Channel" },
      { value: "mono-y", label: "Yellow (R+G)" },
      { value: "mono-c", label: "Cyan (G+B)" },
      { value: "mono-m", label: "Magenta (R+B)" },
    ],
    shortcut: { modifiers: [], key: "m" },
    category: "effect",
    metadata: true,
    order: 4.5,
  },
  {
    id: "whiteEffect",
    label: "White Effect",
    type: "bool",
    default: false,
    shortcut: { modifiers: [], key: "u" },
    category: "effect",
    metadata: true,
    order: 4.7,
  },
  {
    id: "ditherAmount",
    label: "Dithering Amount",
    type: "float",
    default: 100,
    min: 0,
    max: 100,
    step: 5,
    shortcut: { modifiers: [], key: "r" },
    decrementShortcut: { modifiers: [], key: "e" },
    category: "effect",
    metadata: true,
    order: 5,
  },
  {
    id: "hue",
    label: "Hue",
    type: "float",
    default: 0,
    min: -180,
    max: 180,
    step: 15,
    shortcut: { modifiers: [], key: "k" },
    decrementShortcut: { modifiers: [], key: "j" },
    category: "effect",
    metadata: true,
    order: 6,
  },
  // Common parameters come last
  ...COMMON_PARAMETERS,
];

export const DITHER_CONFIG: ShaderConfig = {
  id: "dither",
  name: "Dither",
  description: "Dithering effect with multiple patterns",
  glslFile: "assets/shaders/dither.glsl",
  processor: "processImageWithDither",
  parameters: DITHER_PARAMETERS,
};
