const CHAIN_LOGO_SLUG: Record<string, string> = {
  // EVM
  Ethereum: "ethereum",
  Base: "base",
  Arbitrum: "arbitrum",
  Optimism: "optimism",
  Polygon: "polygon",
  BSC: "smartchain",
  Avalanche: "avalanchec",
  Fantom: "fantom",
  zkSync: "zksync",
  Linea: "linea",
  Scroll: "scroll",
  Mantle: "mantle",
  "Ethereum Classic": "classic",
  HyperEVM: "hyperliquid",
  HyperCore: "hyperliquid",
  // L1
  Bitcoin: "bitcoin",
  "Lightning Network": "lightning",
  Solana: "solana",
  Tron: "tron",
  TON: "ton",
  Polkadot: "polkadot",
  NEAR: "near",
  Dogecoin: "doge",
  Litecoin: "litecoin",
  "Bitcoin Cash": "bitcoincash",
  ZCash: "zcash",
  Monero: "monero",
  "XRP Ledger": "xrp",
  Stellar: "stellar",
  Bittensor: "bittensor",
  Cardano: "cardano",
  Filecoin: "filecoin",
  Hedera: "hedera",
  Kaspa: "kaspa",
  Algorand: "algorand",
  MultiversX: "elrond",
  Starknet: "starknet",
  // Cosmos
  "Cosmos Hub": "cosmos",
  Osmosis: "osmosis",
  Celestia: "celestia",
  dYdX: "dydx",
  Injective: "injective",
  Sei: "sei",
  Stride: "stride",
  Stargaze: "stargaze",
  Akash: "akash",
  Axelar: "axelar",
  Kava: "kava",
  Juno: "juno",
  Evmos: "evmos",
  Secret: "secret",
  Band: "band",
  Persistence: "persistence",
  Regen: "regen",
  Sommelier: "sommelier",
  Chihuahua: "cosmos",
  Archway: "archway",
  Noble: "noble",
  Neutron: "neutron",
  Coreum: "coreum",
  KYVE: "kyve",
  Agoric: "agoric",
  Terra: "terra",
  IRISnet: "iris",
  "Cronos POS": "cronos",
  Dymension: "dymension",
  MANTRA: "cosmos",
  Babylon: "cosmos",
  Nolus: "cosmos",
  Pryzm: "cosmos",
  // Move
  Sui: "sui",
  Aptos: "aptos",
  Movement: "movement",
  IOTA: "iota",
  // Testnets (reuse mainnet logos)
  "Ethereum Sepolia": "ethereum",
  "Ethereum Holesky": "ethereum",
  "Base Sepolia": "base",
  "Arbitrum Sepolia": "arbitrum",
  "Optimism Sepolia": "optimism",
  "Polygon Amoy": "polygon",
  "BSC Testnet": "smartchain",
  "Avalanche Fuji": "avalanchec",
  "Fantom Testnet": "fantom",
  "zkSync Sepolia": "zksync",
  "Linea Sepolia": "linea",
  "Scroll Sepolia": "scroll",
  "Mantle Sepolia": "mantle",
  "Bitcoin Testnet": "bitcoin",
  "Solana Testnet": "solana",
  "Solana Devnet": "solana",
  "Cardano Preprod": "cardano",
  "Sui Testnet": "sui",
  "Aptos Testnet": "aptos",
  "NEAR Testnet": "near",
  "Tron Shasta": "tron",
  "Tron Nile": "tron",
  "TON Testnet": "ton",
  "Starknet Sepolia": "starknet",
  "XRP Testnet": "xrp",
  "Stellar Testnet": "stellar",
  "Hedera Testnet": "hedera",
  "Algorand Testnet": "algorand",
  "MultiversX Devnet": "elrond",
  "Polkadot Westend": "polkadot",
  "Filecoin Calibration": "filecoin",
  "Litecoin Testnet": "litecoin",
  "Dogecoin Testnet": "doge",
  "Bitcoin Cash Testnet": "bitcoincash",
  "ZCash Testnet": "zcash",
  "Kaspa Testnet": "kaspa",
  Tezos: "tezos",
  Aleo: "aleo",
  Nano: "nano",
  Chia: "chia",
  Nockchain: "nockchain",
  Stacks: "stacks",
  Dash: "dash",
  Urbit: "urbit",
  "Dash Testnet": "dash",
  "Lightning Testnet": "lightning",
  "Ethereum Classic Mordor": "classic",
  "HyperEVM Testnet": "hyperliquid",
  "HyperCore Testnet": "hyperliquid",
  "Osmosis Testnet": "osmosis",
  "Celestia Testnet": "celestia",
  "dYdX Testnet": "dydx",
  "Injective Testnet": "injective",
  "Axelar Testnet": "axelar",
  "Kava Testnet": "kava",
  "Persistence Testnet": "persistence",
  "Archway Testnet": "archway",
  "Noble Testnet": "noble",
  "Neutron Testnet": "neutron",
  "Coreum Testnet": "coreum",
  "MANTRA Testnet": "cosmos",
  "Babylon Testnet": "cosmos",
  THORChain: "thorchain",
  Berachain: "berachain",
  "Berachain Testnet": "berachain",
  Ronin: "ronin",
  "Ronin Saigon": "ronin",
  Flare: "flare",
  "Flare Coston2": "flare",
  "Oasis Sapphire": "oasis",
  "Oasis Sapphire Testnet": "oasis",
  Core: "core",
  "Core Testnet": "core",
  Monad: "monad",
  "Monad Testnet": "monad",
  MegaETH: "megaeth",
  Plasma: "plasma",
  // Additional EVM chains
  Gnosis: "gnosis",
  Blast: "blast",
  "World Chain": "worldchain",
  Zora: "zora",
  Unichain: "unichain",
  Celo: "celo",
  Metis: "metis",
  Moonbeam: "moonbeam",
  ApeChain: "apechain",
  "Arbitrum Nova": "arbitrum",
  "Polygon zkEVM": "polygon",
  opBNB: "smartchain",
  Sonic: "sonic",
  Abstract: "abstract",
  Soneium: "soneium",
  Mode: "mode",
  Boba: "boba",
  BOB: "bob",
  ZetaChain: "zetachain",
  Fraxtal: "fraxtal",
  Rootstock: "rootstock",
  "Flow EVM": "flow",
  Astar: "astar",
  Ink: "ink",
  Degen: "degen",
  Shape: "shape",
  Superseed: "superseed",
  Polynomial: "polynomial",
  Story: "story",
  Lens: "lens",
  Anime: "anime",
  Citrea: "citrea",
  Botanix: "botanix",
  CrossFi: "crossfi",
  Galactica: "galactica",
  Humanity: "humanity",
  Stable: "stable",
  Mythos: "mythos",
  Settlus: "settlus",
  Syndicate: "syndicate",
  "World Mobile Chain": "worldmobile",
  ADI: "adi",
  // Additional EVM Testnets
  "Gnosis Chiado": "gnosis",
  "Blast Sepolia": "blast",
  "World Chain Sepolia": "worldchain",
  "Zora Sepolia": "zora",
  "Unichain Sepolia": "unichain",
  "Celo Sepolia": "celo",
  "ApeChain Curtis": "apechain",
  "Polygon zkEVM Cardona": "polygon",
  "opBNB Testnet": "smartchain",
  "Sonic Testnet": "sonic",
  "Abstract Testnet": "abstract",
  "Soneium Minato": "soneium",
  "Mode Sepolia": "mode",
  "Boba Sepolia": "boba",
  "BOB Sepolia": "bob",
  "ZetaChain Testnet": "zetachain",
  "Fraxtal Sepolia": "fraxtal",
  "Rootstock Testnet": "rootstock",
  "Flow EVM Testnet": "flow",
  "Ink Sepolia": "ink",
  "Shape Sepolia": "shape",
  "Superseed Sepolia": "superseed",
  "Polynomial Sepolia": "polynomial",
  "Story Aeneid": "story",
  "Lens Sepolia": "lens",
  "Anime Sepolia": "anime",
  "Citrea Testnet": "citrea",
  "Botanix Testnet": "botanix",
  "CrossFi Testnet": "crossfi",
  "Galactica Cassiopeia": "galactica",
  "Humanity Testnet": "humanity",
  "Stable Testnet": "stable",
  "Settlus Testnet": "settlus",
  "Plasma Testnet": "plasma",
  "MegaETH Testnet": "megaeth",
  "ADI Testnet": "adi",
};

export function getChainLogoUrl(chainName: string): string | undefined {
  const slug = CHAIN_LOGO_SLUG[chainName];
  if (!slug) return undefined;
  return `https://multiscan.dev/logos/${slug}.png`;
}
