import { getPreferenceValues } from "@raycast/api";
import { Account, ErrorResult, PaginationInfo, Transaction, TransactionCreateRequest } from "./types";

const { maybe_url, api_key } = getPreferenceValues<ExtensionPreferences>();
export const buildMaybeUrl = (path: string) => new URL(path, maybe_url).toString();
const request = async <T>(endpoint: string, options?: RequestInit) => {
  const url = buildMaybeUrl(`api/v1/${endpoint}`);
  const response = await fetch(url, {
    method: options?.method,
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
      "X-Api-Key": api_key,
    },
    body: options?.body,
  });
  if (!response.headers.get("Content-Type")?.includes("application/json")) throw new Error(response.statusText);
  const result = await response.json();
  if (!response.ok) {
    const err = result as ErrorResult;
    if ("errors" in err && err.errors?.length) throw new Error(err.errors[0]);
    if ("message" in err) throw new Error(err.message);
    throw new Error(err.error);
  }
  return result as T;
};

export const maybe = {
  accounts: {
    list: (props: { page: number; per_page: number }) =>
      request<{ accounts: Account[] } & PaginationInfo>(`accounts?page=${props.page}&per_page=${props.per_page}`),
  },
  transactions: {
    create: (props: { transaction: TransactionCreateRequest }) =>
      request<Transaction>("transactions", { method: "POST", body: JSON.stringify(props) }),
    delete: (props: { id: string }) => request<{ message: string }>(`transactions/${props.id}`, { method: "DELETE" }),
    list: (props: { page: number; per_page: number; params: string }) =>
      request<{ transactions: Transaction[] } & PaginationInfo>(
        `transactions?page=${props.page}&per_page=${props.per_page}${props.params ? `&${props.params}` : ""}`,
      ),
  },
};

export const CURRENCIES = [
  "USD",
  "EUR",
  "GBP",
  "AUD",
  "CAD",
  "JPY",
  "BYR",
  "AFN",
  "ALL",
  "DZD",
  "AOA",
  "ARS",
  "AMD",
  "AWG",
  "AZN",
  "BSD",
  "BHD",
  "BDT",
  "BBD",
  "BYN",
  "BZD",
  "BMD",
  "BTN",
  "BTC",
  "BOB",
  "BAM",
  "BWP",
  "BRL",
  "GBX",
  "BND",
  "BGN",
  "BIF",
  "KHR",
  "CVE",
  "KYD",
  "XAF",
  "XPF",
  "CLP",
  "CNY",
  "CNH",
  "XTS",
  "COP",
  "KMF",
  "CDF",
  "CRC",
  "CUC",
  "CUP",
  "CZK",
  "DKK",
  "DJF",
  "DOP",
  "XCD",
  "EGP",
  "ERN",
  "ETB",
  "XBA",
  "XBB",
  "XBD",
  "XBC",
  "FKP",
  "FJD",
  "GMD",
  "GEL",
  "GHS",
  "GIP",
  "XAU",
  "GTQ",
  "GGP",
  "GNF",
  "GYD",
  "HTG",
  "HNL",
  "HKD",
  "HUF",
  "ISK",
  "INR",
  "IDR",
  "IRR",
  "IQD",
  "IMP",
  "ILS",
  "JMD",
  "JEP",
  "JOD",
  "KZT",
  "KES",
  "KWD",
  "KGS",
  "LAK",
  "LBP",
  "LSL",
  "LRD",
  "LYD",
  "MOP",
  "MKD",
  "MGA",
  "MWK",
  "MYR",
  "MVR",
  "MRU",
  "MUR",
  "MXN",
  "MDL",
  "MNT",
  "MAD",
  "MZN",
  "MMK",
  "NAD",
  "NPR",
  "ANG",
  "SLE",
  "TWD",
  "NZD",
  "NIO",
  "NGN",
  "KPW",
  "NOK",
  "OMR",
  "PKR",
  "XPD",
  "PAB",
  "PGK",
  "PYG",
  "PEN",
  "PHP",
  "XPT",
  "PLN",
  "QAR",
  "RON",
  "RUB",
  "RWF",
  "SHP",
  "SVC",
  "WST",
  "SAR",
  "RSD",
  "SCR",
  "SLL",
  "XAG",
  "SGD",
  "SKK",
  "SBD",
  "SOS",
  "ZAR",
  "KRW",
  "SSP",
  "XDR",
  "LKR",
  "SDG",
  "SRD",
  "SZL",
  "SEK",
  "CHF",
  "SYP",
  "STD",
  "STN",
  "TJS",
  "TZS",
  "THB",
  "TOP",
  "TTD",
  "TND",
  "TRY",
  "TMT",
  "XFU",
  "USDC",
  "UGX",
  "UAH",
  "CLF",
  "AED",
  "UYU",
  "UZS",
  "VUV",
  "VES",
  "VND",
  "XOF",
  "YER",
  "ZMK",
  "ZMW",
];
