openapi: 3.0.3
info:
  description: |
    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

    The base URI for all Web API requests is `https://api.spotify.com/v1`.

    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.
  version: 2023.2.27
  title: Spotify Web API with fixes and improvements from sonallux
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: sonallux
    url: https://github.com/sonallux/spotify-web-api
servers:
- url: https://api.spotify.com/v1
paths:
  /albums/{id}:
    x-spotify-docs-display-name: album
    x-spotify-docs-category: Albums
    get:
      operationId: get-an-album
      tags:
      - Albums
      x-spotify-docs-endpoint-name: Get an Album
      x-spotify-docs-console-url: /console/get-album/?id=0sNOF9WDwhWunNAHPD3Baj
      summary: |
        Get Album
      description: |
        Get Spotify catalog information for a single album.
      security:
      - oauth_2_0: []
  /albums:
    x-spotify-docs-display-name: several-albums
    x-spotify-docs-category: Albums
    get:
      operationId: get-multiple-albums
      tags:
      - Albums
      x-spotify-docs-endpoint-name: Get Multiple Albums
      x-spotify-docs-console-url: /console/get-several-albums/
      summary: |
        Get Several Albums
      description: |
        Get Spotify catalog information for multiple albums identified by their Spotify IDs.
      security:
      - oauth_2_0: []
  /albums/{id}/tracks:
    x-spotify-docs-display-name: album-tracks
    x-spotify-docs-category: Albums
    get:
      operationId: get-an-albums-tracks
      tags:
      - Albums
      - Tracks
      x-spotify-docs-endpoint-name: Get an Album's Tracks
      x-spotify-docs-console-url: /console/get-album-tracks/
      summary: |
        Get Album Tracks
      description: |
        Get Spotify catalog information about an album’s tracks.
        Optional parameters can be used to limit the number of tracks returned.
      security:
      - oauth_2_0: []
  /artists/{id}:
    x-spotify-docs-display-name: artist
    x-spotify-docs-category: Artists
    get:
      tags:
      - Artists
      operationId: get-an-artist
      x-spotify-docs-endpoint-name: Get an Artist
      x-spotify-docs-console-url: /console/get-artist/?id=0OdUWJ0sBjDrqHygGUXeCF
      summary: |
        Get Artist
      description: |
        Get Spotify catalog information for a single artist identified by their unique Spotify ID.
      security:
      - oauth_2_0: []
  /artists:
    x-spotify-docs-display-name: several-artists
    x-spotify-docs-category: Artists
    get:
      tags:
      - Artists
      operationId: get-multiple-artists
      x-spotify-docs-endpoint-name: Get Multiple Artists
      x-spotify-docs-console-url: "/console/get-several-artists/?ids=0oSGxfWSnnOXhD2fKuz2Gy,3dBVyJ7JuOMt4GE9607Qin"
      summary: |
        Get Several Artists
      description: |
        Get Spotify catalog information for several artists based on their Spotify IDs.
      security:
      - oauth_2_0: []
  /artists/{id}/albums:
    x-spotify-docs-display-name: artist-albums
    x-spotify-docs-category: Artists
    get:
      tags:
      - Artists
      - Albums
      operationId: get-an-artists-albums
      x-spotify-docs-endpoint-name: Get an Artist's Albums
      x-spotify-docs-console-url: /console/get-artist-albums/?album_type=single&amp;limit=2&amp;market=ES&amp;id=1vCWHaC5f2uS3yhpwWbIA6
      summary: |
        Get Artist's Albums
      description: |
        Get Spotify catalog information about an artist's albums.
      security:
      - oauth_2_0: []
  /artists/{id}/top-tracks:
    x-spotify-docs-display-name: artist-top-tracks
    x-spotify-docs-category: Artists
    get:
      tags:
      - Artists
      - Tracks
      operationId: get-an-artists-top-tracks
      x-spotify-docs-endpoint-name: Get an Artist's Top Tracks
      x-spotify-docs-console-url: /console/get-artist-top-tracks/?country=SE&amp;id=43ZHCT0cAZBISjO8DG9PnE
      summary: |
        Get Artist's Top Tracks
      description: |
        Get Spotify catalog information about an artist's top tracks by country.
      security:
      - oauth_2_0: []
  /artists/{id}/related-artists:
    x-spotify-docs-display-name: artist-related-artists
    x-spotify-docs-category: Artists
    get:
      tags:
      - Artists
      operationId: get-an-artists-related-artists
      x-spotify-docs-endpoint-name: Get an Artist's Related Artists
      x-spotify-docs-console-url: /console/get-artist-related-artists/?id=43ZHCT0cAZBISjO8DG9PnE
      summary: |
        Get Artist's Related Artists
      description: |
        Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community's [listening history](http://news.spotify.com/se/2010/02/03/related-artists/).
      security:
      - oauth_2_0: []
  /shows/{id}:
    x-spotify-docs-display-name: show
    x-spotify-docs-category: Shows
    get:
      tags:
      - Shows
      operationId: get-a-show
      x-spotify-docs-endpoint-name: Get a Show
      x-spotify-docs-console-url: /console/get-show/?id=38bS44xjbVVZ3No3ByF1dJ
      summary: |
        Get Show
      description: |
        Get Spotify catalog information for a single show identified by its
        unique Spotify ID.
      security:
      - oauth_2_0:
        - user-read-playback-position
  /shows:
    x-spotify-docs-display-name: several-shows
    x-spotify-docs-category: Shows
    get:
      tags:
      - Shows
      operationId: get-multiple-shows
      x-spotify-docs-endpoint-name: Get Multiple Shows
      x-spotify-docs-console-url: "/console/get-several-shows/?ids=5CfCWKI5pZ28U0uOzXkDHe,5as3aKmN2k11yfDDDSrvaZ"
      summary: |
        Get Several Shows
      description: |
        Get Spotify catalog information for several shows based on their Spotify IDs.
      security:
      - oauth_2_0: []
  /shows/{id}/episodes:
    x-spotify-docs-display-name: show-episodes
    x-spotify-docs-category: Shows
    get:
      tags:
      - Shows
      - Episodes
      operationId: get-a-shows-episodes
      x-spotify-docs-endpoint-name: Get a Show's Episodes
      x-spotify-docs-console-url: /console/get-show-episodes/
      summary: |
        Get Show Episodes
      description: |
        Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
      security:
      - oauth_2_0:
        - user-read-playback-position
  /episodes/{id}:
    x-spotify-docs-display-name: episode
    x-spotify-docs-category: Episodes
    get:
      tags:
      - Episodes
      operationId: get-an-episode
      x-spotify-docs-endpoint-name: Get an Episode
      x-spotify-docs-console-url: /console/get-episode/?id=512ojhOuo1ktJprKbVcKyQ
      summary: |
        Get Episode
      description: |
        Get Spotify catalog information for a single episode identified by its
        unique Spotify ID.
      security:
      - oauth_2_0:
        - user-read-playback-position
  /episodes:
    x-spotify-docs-display-name: several-episodes
    x-spotify-docs-category: Episodes
    get:
      tags:
      - Episodes
      operationId: get-multiple-episodes
      x-spotify-docs-endpoint-name: Get Multiple Episodes
      x-spotify-docs-console-url: "/console/get-several-episodes/?ids=77o6BIVlYM3msb4MMIL1jH,0Q86acNRm6V9GYx55SXKwf"
      summary: |
        Get Several Episodes
      description: |
        Get Spotify catalog information for several episodes based on their Spotify IDs.
      security:
      - oauth_2_0:
        - user-read-playback-position
  /audiobooks/{id}:
    x-spotify-docs-display-name: audiobook
    x-spotify-docs-category: Audiobooks
    get:
      operationId: get-an-audiobook
      tags:
      - Audiobooks
      x-spotify-docs-endpoint-name: Get an Audiobook
      x-spotify-docs-console-url: /console/get-audiobook/?id=5thw29eqjomhIDMY1XKsLk
      summary: |
        Get an Audiobook
      description: |
        Get Spotify catalog information for a single audiobook.<br />
        **Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      security:
      - oauth_2_0: []
  /audiobooks:
    x-spotify-docs-display-name: several-audiobooks
    x-spotify-docs-category: Audiobooks
    get:
      operationId: get-multiple-audiobooks
      tags:
      - Audiobooks
      x-spotify-docs-endpoint-name: Get Several Audiobooks
      x-spotify-docs-console-url: "/console/get-several-audiobooks/?ids=5thw29eqjomhIDMY1XKsLk,2IEBhnu61ieYGFRPEJIO40"
      summary: |
        Get Several Audiobooks
      description: |
        Get Spotify catalog information for several audiobooks identified by their Spotify IDs.<br />
        **Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      security:
      - oauth_2_0: []
  /audiobooks/{id}/chapters:
    x-spotify-docs-display-name: audiobook-chapters
    x-spotify-docs-category: Audiobooks
    get:
      operationId: get-audiobook-chapters
      tags:
      - Audiobooks
      - Chapters
      x-spotify-docs-endpoint-name: Get an Audiobook's Chapters
      x-spotify-docs-console-url: /console/get-audiobook-chapters/?id=5thw29eqjomhIDMY1XKsLk
      summary: |
        Get Audiobook Chapters
      description: |
        Get Spotify catalog information about an audiobook's chapters.<br />
        **Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      security:
      - oauth_2_0: []
  /me/audiobooks:
    x-spotify-docs-display-name: current-user-saved-audiobooks
    x-spotify-docs-category: Library
    get:
      tags:
      - Audiobooks
      - Library
      operationId: get-users-saved-audiobooks
      x-spotify-docs-endpoint-name: Get User's Saved Audiobooks
      x-spotify-docs-console-url: /console/get-current-user-saved-audiobooks/?limit=1
      summary: |
        Get User's Saved Audiobooks
      description: |
        Get a list of the audiobooks saved in the current Spotify user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-read
    put:
      tags:
      - Audiobooks
      - Library
      operationId: save-audiobooks-user
      x-spotify-docs-endpoint-name: Save Audiobooks for Current User
      x-spotify-docs-console-url: /console/put-current-user-saved-audiobooks/?ids=07bYtmE3bPsLB6ZbmmFi8d%2C48JYNjh7GMie6NjqYHMmtT%2C27cZdqrQiKt3IT00338dws
      summary: |
        Save Audiobooks for Current User
      description: |
        Save one or more audiobooks to the current Spotify user's library.
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - Audiobooks
      - Library
      operationId: remove-audiobooks-user
      x-spotify-docs-endpoint-name: Remove Audiobooks for Current User
      x-spotify-docs-console-url: /console/delete-current-user-saved-audiobooks/?ids=07bYtmE3bPsLB6ZbmmFi8d%2C48JYNjh7GMie6NjqYHMmtT%2C27cZdqrQiKt3IT00338dws
      summary: |
        Remove User's Saved Audiobooks
      description: |
        Remove one or more audiobooks from the Spotify user's library.
      security:
      - oauth_2_0:
        - user-library-modify
  /me/audiobooks/contains:
    x-spotify-docs-display-name: current-user-contains-saved-audiobooks
    x-spotify-docs-category: Library
    get:
      tags:
      - Audiobooks
      - Library
      operationId: check-users-saved-audiobooks
      x-spotify-docs-endpoint-name: Check User's Saved Audiobooks
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-audiobooks/?ids=0pJJgBzj26qnE1nSQUxaB0%2C5ZAKzV4ZIa5Gt7z29OYHv0
      summary: |
        Check User's Saved Audiobooks
      description: |
        Check if one or more audiobooks are already saved in the current Spotify user's library.
      security:
      - oauth_2_0:
        - user-library-read
  /chapters/{id}:
    x-spotify-docs-display-name: chapters
    x-spotify-docs-category: Chapters
    get:
      operationId: get-a-chapter
      tags:
      - Chapters
      x-spotify-docs-endpoint-name: Get a Chapter
      x-spotify-docs-console-url: /console/get-chapter/?id=2i47HuOBSV2XaJNy0NCZXM
      summary: |
        Get a Chapter
      description: |
        Get Spotify catalog information for a single chapter.<br />
        **Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      security:
      - oauth_2_0: []
  /chapters:
    x-spotify-docs-display-name: several-chapters
    x-spotify-docs-category: Chapters
    get:
      operationId: get-several-chapters
      tags:
      - Chapters
      x-spotify-docs-endpoint-name: Get Several Chapters
      x-spotify-docs-console-url: "/console/get-several-chapters/?ids=2i47HuOBSV2XaJNy0NCZXM,2GUbORsUnP1qVVlLwd9DzP"
      summary: |
        Get Several Chapters
      description: |
        Get Spotify catalog information for several chapters identified by their Spotify IDs.<br />
        **Note: Chapters are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      security:
      - oauth_2_0: []
  /tracks/{id}:
    x-spotify-docs-display-name: track
    x-spotify-docs-category: Tracks
    get:
      tags:
      - Tracks
      operationId: get-track
      x-spotify-docs-endpoint-name: Get a Track
      x-spotify-docs-console-url: /console/get-track/?id=3n3Ppam7vgaVa1iaRUc9Lp
      summary: |
        Get Track
      description: |
        Get Spotify catalog information for a single track identified by its
        unique Spotify ID.
      security:
      - oauth_2_0: []
  /tracks:
    x-spotify-docs-display-name: several-tracks
    x-spotify-docs-category: Tracks
    get:
      tags:
      - Tracks
      operationId: get-several-tracks
      x-spotify-docs-endpoint-name: Get Several Tracks
      x-spotify-docs-console-url: "/console/get-several-tracks/?ids=3n3Ppam7vgaVa1iaRUc9Lp,3twNvmDtFQtAd5gMKedhLD"
      summary: |
        Get Several Tracks
      description: |
        Get Spotify catalog information for multiple tracks based on their Spotify IDs.
      security:
      - oauth_2_0: []
  /search:
    x-spotify-docs-display-name: search-item
    x-spotify-docs-category: Search
    get:
      tags:
      - Search
      operationId: search
      x-spotify-docs-endpoint-name: Search for an Item
      x-spotify-docs-console-url: /console/get-search-item/?q=tania+bowra&amp;type=artist
      summary: |
        Search for Item
      description: |
        Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks
        that match a keyword string.<br />
        **Note: Audiobooks are only available for the US, UK, Ireland, New Zealand and Australia markets.**
      security:
      - oauth_2_0: []
  /me:
    x-spotify-docs-display-name: current-user
    x-spotify-docs-category: Users Profile
    get:
      tags:
      - Users
      operationId: get-current-users-profile
      x-spotify-docs-endpoint-name: Get Current User's Profile
      x-spotify-docs-console-url: /console/get-current-user/
      summary: |
        Get Current User's Profile
      description: |
        Get detailed profile information about the current user (including the
        current user's username).
      security:
      - oauth_2_0:
        - user-read-private
        - user-read-email
  /playlists/{playlist_id}:
    x-spotify-docs-display-name: playlist
    x-spotify-docs-category: Playlists
    get:
      tags:
      - Playlists
      operationId: get-playlist
      x-spotify-docs-endpoint-name: Get a Playlist
      x-spotify-docs-console-url: /console/get-playlist/?playlist_id=59ZbFPES4DQwEjBpWHzrtC&amp;user_id=spotify
      summary: |
        Get Playlist
      description: |
        Get a playlist owned by a Spotify user.
      security:
      - oauth_2_0: []
    put:
      tags:
      - Playlists
      - Library
      operationId: change-playlist-details
      x-spotify-docs-endpoint-name: Change a Playlist's Details
      x-spotify-docs-console-url: /console/put-playlist/
      summary: |
        Change Playlist Details
      description: |
        Change a playlist's name and public/private state. (The user must, of
        course, own the playlist.)
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /playlists/{playlist_id}/tracks:
    x-spotify-docs-display-name: playlist-tracks
    x-spotify-docs-category: Playlists
    get:
      tags:
      - Playlists
      - Tracks
      operationId: get-playlists-tracks
      x-spotify-docs-endpoint-name: Get a Playlist's Items
      x-spotify-docs-console-url: /console/get-playlist-tracks/?playlist_id=21THa8j9TaSGuXYNBU5tsC&amp;user_id=spotify_espa%C3%B1a
      summary: |
        Get Playlist Items
      description: |
        Get full details of the items of a playlist owned by a Spotify user.
      security:
      - oauth_2_0:
        - playlist-read-private
    post:
      tags:
      - Playlists
      - Tracks
      operationId: add-tracks-to-playlist
      x-spotify-docs-endpoint-name: Add Items to a Playlist
      x-spotify-docs-console-url: /console/post-playlist-tracks/
      summary: |
        Add Items to Playlist
      description: |
        Add one or more items to a user's playlist.
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    put:
      tags:
      - Playlists
      - Tracks
      operationId: reorder-or-replace-playlists-tracks
      x-spotify-docs-endpoint-name: Reorder or Replace a Playlist's Items
      x-spotify-docs-console-url: /console/put-playlist-tracks/
      summary: |
        Update Playlist Items
      description: |
        Either reorder or replace items in a playlist depending on the request's parameters.
        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.
        To replace items, include `uris` as either a query parameter or in the request's body.
        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.
        <br/>
        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.
        These operations can't be applied together in a single request.
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    delete:
      tags:
      - Playlists
      - Tracks
      operationId: remove-tracks-playlist
      x-spotify-docs-endpoint-name: Remove Items from a Playlist
      x-spotify-docs-console-url: /console/delete-playlist-tracks/
      summary: |
        Remove Playlist Items
      description: |
        Remove one or more items from a user's playlist.
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /me/playlists:
    x-spotify-docs-display-name: current-user-playlists
    x-spotify-docs-category: Playlists
    get:
      tags:
      - Playlists
      - Library
      operationId: get-a-list-of-current-users-playlists
      x-spotify-docs-endpoint-name: Get a List of Current User's Playlists
      x-spotify-docs-console-url: /console/get-current-user-playlists/
      summary: |
        Get Current User's Playlists
      description: |
        Get a list of the playlists owned or followed by the current Spotify
        user.
      security:
      - oauth_2_0:
        - playlist-read-private
  /me/albums:
    x-spotify-docs-display-name: current-user-saved-albums
    x-spotify-docs-category: Library
    get:
      tags:
      - Albums
      - Library
      operationId: get-users-saved-albums
      x-spotify-docs-endpoint-name: Get User's Saved Albums
      x-spotify-docs-console-url: /console/get-current-user-saved-albums/?limit=1
      summary: |
        Get User's Saved Albums
      description: |
        Get a list of the albums saved in the current Spotify user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-read
    put:
      tags:
      - Albums
      - Library
      operationId: save-albums-user
      x-spotify-docs-endpoint-name: Save Albums for Current User
      x-spotify-docs-console-url: /console/put-current-user-saved-albums/?ids=07bYtmE3bPsLB6ZbmmFi8d%2C48JYNjh7GMie6NjqYHMmtT%2C27cZdqrQiKt3IT00338dws
      summary: |
        Save Albums for Current User
      description: |
        Save one or more albums to the current user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - Albums
      - Library
      operationId: remove-albums-user
      x-spotify-docs-endpoint-name: Remove Albums for Current User
      x-spotify-docs-console-url: /console/delete-current-user-saved-albums/?ids=07bYtmE3bPsLB6ZbmmFi8d%2C48JYNjh7GMie6NjqYHMmtT%2C27cZdqrQiKt3IT00338dws
      summary: |
        Remove Users' Saved Albums
      description: |
        Remove one or more albums from the current user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-modify
  /me/albums/contains:
    x-spotify-docs-display-name: current-user-contains-saved-albums
    x-spotify-docs-category: Library
    get:
      tags:
      - Albums
      - Library
      operationId: check-users-saved-albums
      x-spotify-docs-endpoint-name: Check User's Saved Albums
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-albums/?ids=0pJJgBzj26qnE1nSQUxaB0%2C5ZAKzV4ZIa5Gt7z29OYHv0
      summary: |
        Check User's Saved Albums
      description: |
        Check if one or more albums is already saved in the current Spotify user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-read
  /me/tracks:
    x-spotify-docs-display-name: current-user-saved-tracks
    x-spotify-docs-category: Library
    get:
      tags:
      - Tracks
      - Library
      operationId: get-users-saved-tracks
      x-spotify-docs-endpoint-name: Get User's Saved Tracks
      x-spotify-docs-console-url: /console/get-current-user-saved-tracks/
      summary: |
        Get User's Saved Tracks
      description: |
        Get a list of the songs saved in the current Spotify user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-read
    put:
      tags:
      - Tracks
      - Library
      operationId: save-tracks-user
      x-spotify-docs-endpoint-name: Save Tracks for User
      x-spotify-docs-console-url: /console/put-current-user-saved-tracks/?ids=7ouMYWpwJ422jRcDASZB7P%2C4VqPOruhp5EdPBeR92t6lQ%2C2takcwOaAZWiXQijPHIx7B
      summary: |
        Save Tracks for Current User
      description: |
        Save one or more tracks to the current user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - Tracks
      - Library
      operationId: remove-tracks-user
      x-spotify-docs-endpoint-name: Remove User's Saved Tracks
      x-spotify-docs-console-url: /console/delete-current-user-saved-tracks/?ids=7ouMYWpwJ422jRcDASZB7P%2C4VqPOruhp5EdPBeR92t6lQ%2C2takcwOaAZWiXQijPHIx7B
      summary: |
        Remove User's Saved Tracks
      description: |
        Remove one or more tracks from the current user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-modify
  /me/tracks/contains:
    x-spotify-docs-display-name: current-user-contains-saved-tracks
    x-spotify-docs-category: Library
    get:
      tags:
      - Tracks
      - Library
      operationId: check-users-saved-tracks
      x-spotify-docs-endpoint-name: Check User's Saved Tracks
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-tracks/?ids=0udZHhCi7p1YzMlvI4fXoK%2C3SF5puV5eb6bgRSxBeMOk9
      summary: |
        Check User's Saved Tracks
      description: |
        Check if one or more tracks is already saved in the current Spotify user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-read
  /me/episodes:
    x-spotify-docs-display-name: current-user-saved-episodes
    x-spotify-docs-category: Library
    get:
      tags:
      - Episodes
      - Library
      operationId: get-users-saved-episodes
      x-spotify-docs-endpoint-name: Get User's Saved Episodes
      x-spotify-docs-console-url: /console/get-current-user-saved-episodes/
      summary: |
        Get User's Saved Episodes
      description: |
        Get a list of the episodes saved in the current Spotify user's library.
      security:
      - oauth_2_0:
        - user-library-read
        - user-read-playback-position
    put:
      tags:
      - Episodes
      - Library
      operationId: save-episodes-user
      x-spotify-docs-endpoint-name: Save Episodes for Current User
      x-spotify-docs-console-url: /console/put-current-user-saved-episodes/?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf
      summary: |
        Save Episodes for Current User
      description: |
        Save one or more episodes to the current user's library.
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - Episodes
      - Library
      operationId: remove-episodes-user
      x-spotify-docs-endpoint-name: Remove User's Saved Episodes
      x-spotify-docs-console-url: /console/delete-current-user-saved-episodes/?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf
      summary: |
        Remove User's Saved Episodes
      description: |
        Remove one or more episodes from the current user's library.
      security:
      - oauth_2_0:
        - user-library-modify
  /me/episodes/contains:
    x-spotify-docs-display-name: current-user-contains-saved-episodes
    x-spotify-docs-category: Library
    get:
      tags:
      - Episodes
      - Library
      operationId: check-users-saved-episodes
      x-spotify-docs-endpoint-name: Check User's Saved Episodes
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-episodes/?ids=77o6BIVlYM3msb4MMIL1jH%2C0Q86acNRm6V9GYx55SXKwf
      summary: |
        Check User's Saved Episodes
      description: |
        Check if one or more episodes is already saved in the current Spotify user's 'Your Episodes' library.
      security:
      - oauth_2_0:
        - user-library-read
  /me/shows:
    x-spotify-docs-display-name: current-user-saved-shows
    x-spotify-docs-category: Library
    get:
      tags:
      - Shows
      - Library
      operationId: get-users-saved-shows
      x-spotify-docs-endpoint-name: Get User's Saved Shows
      x-spotify-docs-console-url: /console/get-current-user-saved-shows/
      summary: |
        Get User's Saved Shows
      description: |
        Get a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.
      security:
      - oauth_2_0:
        - user-library-read
    put:
      tags:
      - Shows
      - Library
      operationId: save-shows-user
      x-spotify-docs-endpoint-name: Save Shows for Current User
      x-spotify-docs-console-url: /console/put-current-user-saved-shows/?ids=5AvwZVawapvyhJUIx71pdJ%2C6ups0LMt1G8n81XLlkbsPo%2C5AvwZVawapvyhJUIx71pdJ
      summary: |
        Save Shows for Current User
      description: |
        Save one or more shows to current Spotify user's library.
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      tags:
      - Shows
      - Library
      operationId: remove-shows-user
      x-spotify-docs-endpoint-name: Remove User's Saved Shows
      x-spotify-docs-console-url: /console/delete-current-user-saved-shows/?ids=5AvwZVawapvyhJUIx71pdJ%2C6ups0LMt1G8n81XLlkbsPo%2C5AvwZVawapvyhJUIx71pdJ
      summary: |
        Remove User's Saved Shows
      description: |
        Delete one or more shows from current Spotify user's library.
      security:
      - oauth_2_0:
        - user-library-modify
  /me/shows/contains:
    x-spotify-docs-display-name: current-user-contains-saved-shows
    x-spotify-docs-category: Library
    get:
      tags:
      - Shows
      - Library
      operationId: check-users-saved-shows
      x-spotify-docs-endpoint-name: Check User's Saved Shows
      x-spotify-docs-console-url: /console/get-current-user-contains-saved-shows/?ids=5AvwZVawapvyhJUIx71pdJ%2C6ups0LMt1G8n81XLlkbsPo%2C5AvwZVawapvyhJUIx71pdJ
      summary: |
        Check User's Saved Shows
      description: |
        Check if one or more shows is already saved in the current Spotify user's library.
      security:
      - oauth_2_0:
        - user-library-read
  /users/{user_id}:
    x-spotify-docs-display-name: users-profile
    x-spotify-docs-category: Users Profile
    get:
      tags:
      - Users
      operationId: get-users-profile
      x-spotify-docs-endpoint-name: Get a User's Profile
      x-spotify-docs-console-url: /console/get-users-profile/?user_id=wizzler
      summary: |
        Get User's Profile
      description: |
        Get public profile information about a Spotify user.
      security:
      - oauth_2_0: []
  /users/{user_id}/playlists:
    x-spotify-docs-display-name: playlists
    x-spotify-docs-category: Playlists
    get:
      tags:
      - Playlists
      - Users
      operationId: get-list-users-playlists
      x-spotify-docs-endpoint-name: Get a List of a User's Playlists
      x-spotify-docs-console-url: /console/get-playlists/?user_id=wizzler
      summary: |
        Get User's Playlists
      description: |
        Get a list of the playlists owned or followed by a Spotify user.
      security:
      - oauth_2_0:
        - playlist-read-private
        - playlist-read-collaborative
    post:
      tags:
      - Playlists
      - Library
      operationId: create-playlist
      x-spotify-docs-endpoint-name: Create a Playlist
      x-spotify-docs-console-url: /console/post-playlists/
      summary: |
        Create Playlist
      description: |
        Create a playlist for a Spotify user. (The playlist will be empty until
        you [add tracks](/documentation/web-api/reference/#/operations/add-tracks-to-playlist).)
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /playlists/{playlist_id}/followers:
    x-spotify-docs-display-name: playlist-followers
    x-spotify-docs-category: Follow
    put:
      tags:
      - Users
      - Playlists
      operationId: follow-playlist
      x-spotify-docs-endpoint-name: Follow a Playlist
      x-spotify-docs-console-url: /console/put-playlist-followers/?playlist_id=2v3iNvBX8Ay1Gt2uXtUKUT&amp;body-json=%7B%0D%0A++%22public%22%3A+true%0D%0A%7D&amp;user_id=jmperezperez
      description: |
        Add the current user as a follower of a playlist.
      summary: |
        Follow Playlist
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    delete:
      tags:
      - Users
      - Playlists
      operationId: unfollow-playlist
      x-spotify-docs-endpoint-name: Unfollow Playlist
      x-spotify-docs-console-url: /console/delete-playlist-followers/?playlist_id=2v3iNvBX8Ay1Gt2uXtUKUT&amp;user_id=jmperezperez
      summary: |
        Unfollow Playlist
      description: |
        Remove the current user as a follower of a playlist.
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /browse/featured-playlists:
    x-spotify-docs-display-name: featured-playlists
    x-spotify-docs-category: Browse
    get:
      tags:
      - Playlists
      operationId: get-featured-playlists
      x-spotify-docs-endpoint-name: Get All Featured Playlists
      x-spotify-docs-console-url: /console/get-featured-playlists/?country=SE&amp;limit=2
      summary: |
        Get Featured Playlists
      description: |
        Get a list of Spotify featured playlists (shown, for example, on a Spotify player's 'Browse' tab).
      security:
      - oauth_2_0: []
  /browse/categories:
    x-spotify-docs-display-name: browse-categories
    x-spotify-docs-category: Browse
    get:
      tags:
      - Categories
      operationId: get-categories
      x-spotify-docs-endpoint-name: Get All Categories
      x-spotify-docs-console-url: /console/get-browse-categories/
      summary: |
        Get Several Browse Categories
      description: |
        Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
      security:
      - oauth_2_0: []
  /browse/categories/{category_id}:
    x-spotify-docs-display-name: browse-category
    x-spotify-docs-category: Browse
    get:
      tags:
      - Categories
      operationId: get-a-category
      x-spotify-docs-endpoint-name: Get a Category
      x-spotify-docs-console-url: /console/get-browse-category/
      summary: |
        Get Single Browse Category
      description: |
        Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).
      security:
      - oauth_2_0: []
  /browse/categories/{category_id}/playlists:
    x-spotify-docs-display-name: category-playlists
    x-spotify-docs-category: Browse
    get:
      tags:
      - Playlists
      - Categories
      operationId: get-a-categories-playlists
      x-spotify-docs-endpoint-name: Get a Category's Playlists
      x-spotify-docs-console-url: /console/get-category-playlists/?country=BR&amp;category_id=party&amp;limit=2
      summary: |
        Get Category's Playlists
      description: |
        Get a list of Spotify playlists tagged with a particular category.
      security:
      - oauth_2_0: []
  /playlists/{playlist_id}/images:
    x-spotify-docs-display-name: playlist-images
    x-spotify-docs-category: Playlists
    get:
      tags:
      - Playlists
      operationId: get-playlist-cover
      x-spotify-docs-endpoint-name: Get a Playlist Cover Image
      x-spotify-docs-console-url: /console/get-playlist-images?playlist_id=3cEYpjA9oz9GiPac4AsH4n
      summary: |
        Get Playlist Cover Image
      description: |
        Get the current image associated with a specific playlist.
      security:
      - oauth_2_0: []
    put:
      tags:
      - Playlists
      operationId: upload-custom-playlist-cover
      x-spotify-docs-endpoint-name: Upload a Custom Playlist Cover Image
      x-spotify-docs-console-url: /console/put-playlist-images?playlist_id=3cEYpjA9oz9GiPac4AsH4n
      summary: |
        Add Custom Playlist Cover Image
      description: |
        Replace the image used to represent a specific playlist.
      security:
      - oauth_2_0:
        - ugc-image-upload
        - playlist-modify-public
        - playlist-modify-private
  /browse/new-releases:
    x-spotify-docs-display-name: new-releases
    x-spotify-docs-category: Browse
    get:
      tags:
      - Albums
      operationId: get-new-releases
      x-spotify-docs-endpoint-name: Get All New Releases
      x-spotify-docs-console-url: /console/get-new-releases/?country=SE
      summary: |
        Get New Releases
      description: |
        Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player’s “Browse” tab).
      security:
      - oauth_2_0: []
  /me/following:
    x-spotify-docs-display-name: following
    x-spotify-docs-category: Follow
    get:
      tags:
      - Users
      - Library
      - Artists
      operationId: get-followed
      x-spotify-docs-endpoint-name: Get User's Followed Artists
      x-spotify-docs-console-url: /console/get-following/?type=artist&amp;limit=20
      summary: |
        Get Followed Artists
      description: |
        Get the current user's followed artists.
      security:
      - oauth_2_0:
        - user-follow-read
    put:
      tags:
      - Users
      - Artists
      - Library
      operationId: follow-artists-users
      x-spotify-docs-endpoint-name: Follow Artists or Users
      x-spotify-docs-console-url: /console/put-following/?type=user&amp;ids=exampleuser01
      summary: |
        Follow Artists or Users
      description: |
        Add the current user as a follower of one or more artists or other Spotify users.
      security:
      - oauth_2_0:
        - user-follow-modify
    delete:
      tags:
      - Users
      - Artists
      - Library
      operationId: unfollow-artists-users
      x-spotify-docs-endpoint-name: Unfollow Artists or Users
      x-spotify-docs-console-url: /console/delete-following/?type=user&amp;ids=exampleuser01
      summary: |
        Unfollow Artists or Users
      description: |
        Remove the current user as a follower of one or more artists or other Spotify users.
      security:
      - oauth_2_0:
        - user-follow-modify
  /me/following/contains:
    x-spotify-docs-display-name: following-contains
    x-spotify-docs-category: Follow
    get:
      tags:
      - Users
      - Artists
      - Library
      operationId: check-current-user-follows
      x-spotify-docs-endpoint-name: Get Following State for Artists/Users
      x-spotify-docs-console-url: /console/get-following-contains/?type=user&amp;ids=exampleuser01
      summary: |
        Check If User Follows Artists or Users
      description: |
        Check to see if the current user is following one or more artists or other Spotify users.
      security:
      - oauth_2_0:
        - user-follow-read
  /playlists/{playlist_id}/followers/contains:
    x-spotify-docs-display-name: playlist-followers-contains
    x-spotify-docs-category: Follow
    get:
      tags:
      - Users
      - Playlists
      operationId: check-if-user-follows-playlist
      x-spotify-docs-endpoint-name: Check if Users Follow a Playlist
      x-spotify-docs-console-url: "/console/get-playlist-followers-contains/?ids=possan,elogain&amp;user_id=jmperezperez&amp;playlist_id=2v3iNvBX8Ay1Gt2uXtUKUT"
      summary: |
        Check if Users Follow Playlist
      description: |
        Check to see if one or more Spotify users are following a specified playlist.
      security:
      - oauth_2_0: []
  /audio-features:
    x-spotify-docs-display-name: audio-features-several-tracks
    x-spotify-docs-category: Tracks
    get:
      tags:
      - Tracks
      operationId: get-several-audio-features
      x-spotify-docs-endpoint-name: Get Audio Features for Several Tracks
      x-spotify-docs-console-url: "/console/get-audio-features-several-tracks/?ids=4JpKVNYnVcJ8tuMKjAj50A,2NRANZE9UCmPAS5XVbXL40,24JygzOLM0EmRQeGtFcIcG"
      summary: |
        Get Tracks' Audio Features
      description: |
        Get audio features for multiple tracks based on their Spotify IDs.
      security:
      - oauth_2_0: []
  /audio-features/{id}:
    x-spotify-docs-display-name: audio-features-track
    x-spotify-docs-category: Tracks
    get:
      tags:
      - Tracks
      operationId: get-audio-features
      x-spotify-docs-endpoint-name: Get Audio Features for a Track
      x-spotify-docs-console-url: /console/get-audio-features-track/?id=06AKEBrKUckW0KREUWRnvT
      summary: |
        Get Track's Audio Features
      description: |
        Get audio feature information for a single track identified by its unique
        Spotify ID.
      security:
      - oauth_2_0: []
  /audio-analysis/{id}:
    x-spotify-docs-display-name: audio-analysis-track
    x-spotify-docs-category: Tracks
    get:
      tags:
      - Tracks
      operationId: get-audio-analysis
      x-spotify-docs-endpoint-name: Get Audio Analysis for a Track
      x-spotify-docs-console-url: /console/get-audio-analysis-track/?id=06AKEBrKUckW0KREUWRnvT
      summary: |
        Get Track's Audio Analysis
      description: |
        Get a low-level audio analysis for a track in the Spotify catalog. The audio analysis describes the track’s structure and musical content, including rhythm, pitch, and timbre.
      security:
      - oauth_2_0: []
  /recommendations:
    x-spotify-docs-display-name: recommendations
    x-spotify-docs-category: Browse
    get:
      tags:
      - Tracks
      operationId: get-recommendations
      x-spotify-docs-endpoint-name: Get Recommendations
      x-spotify-docs-console-url: /console/get-recommendations/?seed_artists=4NHQUGzhtTLFvgF5SZesLK&amp;seed_tracks=0c6xIDDpzE81m2q797ordA&amp;min_energy=0.4&amp;min_popularity=50&amp;market=US
      summary: |
        Get Recommendations
      description: |
        Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.

        For artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.
      security:
      - oauth_2_0: []
  /recommendations/available-genre-seeds:
    x-spotify-docs-display-name: available-genre-seeds
    x-spotify-docs-category: Browse
    get:
      tags:
      - Genres
      operationId: get-recommendation-genres
      x-spotify-docs-endpoint-name: Get Recommendation Genres
      x-spotify-docs-console-url: /console/get-available-genre-seeds/
      summary: |
        Get Available Genre Seeds
      description: |
        Retrieve a list of available genres seed parameter values for [recommendations](/documentation/web-api/reference/#/operations/get-recommendations).
      security:
      - oauth_2_0: []
  /me/player:
    x-spotify-docs-display-name: user-player
    x-spotify-docs-category: Player
    get:
      tags:
      - Player
      operationId: get-information-about-the-users-current-playback
      x-spotify-docs-endpoint-name: Get Information About The User's Current Playback
      x-spotify-docs-console-url: /console/get-user-player/
      summary: |
        Get Playback State
      description: |
        Get information about the user’s current playback state, including track or episode, progress, and active device.
      security:
      - oauth_2_0:
        - user-read-playback-state
    put:
      tags:
      - Player
      operationId: transfer-a-users-playback
      x-spotify-docs-endpoint-name: Transfer a User's Playback
      x-spotify-docs-console-url: /console/put-user-player
      summary: |
        Transfer Playback
      description: |
        Transfer playback to a new device and determine if it should start playing.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/devices:
    x-spotify-docs-display-name: users-available-devices
    x-spotify-docs-category: Player
    get:
      tags:
      - Player
      operationId: get-a-users-available-devices
      x-spotify-docs-endpoint-name: Get a User's Available Devices
      x-spotify-docs-console-url: /console/get-users-available-devices/
      summary: |
        Get Available Devices
      description: |
        Get information about a user’s available devices.
      security:
      - oauth_2_0:
        - user-read-playback-state
  /me/player/currently-playing:
    x-spotify-docs-display-name: users-currently-playing-track
    x-spotify-docs-category: Player
    get:
      tags:
      - Player
      operationId: get-the-users-currently-playing-track
      x-spotify-docs-endpoint-name: Get the User's Currently Playing Track
      x-spotify-docs-console-url: /console/get-users-currently-playing-track/
      summary: |
        Get Currently Playing Track
      description: |
        Get the object currently being played on the user's Spotify account.
      security:
      - oauth_2_0:
        - user-read-currently-playing
  /me/player/play:
    x-spotify-docs-display-name: play
    x-spotify-docs-category: Player
    put:
      tags:
      - Player
      operationId: start-a-users-playback
      x-spotify-docs-endpoint-name: Start/Resume a User's Playback
      x-spotify-docs-console-url: /console/put-play/
      summary: |
        Start/Resume Playback
      description: |
        Start a new context or resume current playback on the user's active device.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/pause:
    x-spotify-docs-display-name: pause
    x-spotify-docs-category: Player
    put:
      tags:
      - Player
      operationId: pause-a-users-playback
      x-spotify-docs-endpoint-name: Pause a User's Playback
      x-spotify-docs-console-url: /console/put-pause/
      summary: |
        Pause Playback
      description: |
        Pause playback on the user's account.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/next:
    x-spotify-docs-display-name: next
    x-spotify-docs-category: Player
    post:
      tags:
      - Player
      operationId: skip-users-playback-to-next-track
      x-spotify-docs-endpoint-name: Skip User’s Playback To Next Track
      x-spotify-docs-console-url: /console/post-next/
      summary: |
        Skip To Next
      description: |
        Skips to next track in the user’s queue.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/previous:
    x-spotify-docs-display-name: previous
    x-spotify-docs-category: Player
    post:
      tags:
      - Player
      operationId: skip-users-playback-to-previous-track
      x-spotify-docs-endpoint-name: Skip User’s Playback To Previous Track
      x-spotify-docs-console-url: /console/post-previous/
      summary: |
        Skip To Previous
      description: |
        Skips to previous track in the user’s queue.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/seek:
    x-spotify-docs-display-name: seek
    x-spotify-docs-category: Player
    put:
      tags:
      - Player
      operationId: seek-to-position-in-currently-playing-track
      x-spotify-docs-endpoint-name: Seek To Position In Currently Playing Track
      x-spotify-docs-console-url: /console/put-seek/
      summary: |
        Seek To Position
      description: |
        Seeks to the given position in the user’s currently playing track.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/repeat:
    x-spotify-docs-display-name: repeat
    x-spotify-docs-category: Player
    put:
      tags:
      - Player
      operationId: set-repeat-mode-on-users-playback
      x-spotify-docs-endpoint-name: Set Repeat Mode On User’s Playback
      x-spotify-docs-console-url: /console/put-repeat/
      summary: |
        Set Repeat Mode
      description: |
        Set the repeat mode for the user's playback. Options are repeat-track,
        repeat-context, and off.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/volume:
    x-spotify-docs-display-name: volume
    x-spotify-docs-category: Player
    put:
      tags:
      - Player
      operationId: set-volume-for-users-playback
      x-spotify-docs-endpoint-name: Set Volume For User's Playback
      x-spotify-docs-console-url: /console/put-volume/
      summary: |
        Set Playback Volume
      description: |
        Set the volume for the user’s current playback device.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/shuffle:
    x-spotify-docs-display-name: shuffle
    x-spotify-docs-category: Player
    put:
      tags:
      - Player
      operationId: toggle-shuffle-for-users-playback
      x-spotify-docs-endpoint-name: Toggle Shuffle For User’s Playback
      x-spotify-docs-console-url: /console/put-shuffle/?state=true
      summary: |
        Toggle Playback Shuffle
      description: |
        Toggle shuffle on or off for user’s playback.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/recently-played:
    x-spotify-docs-display-name: recently-played
    x-spotify-docs-category: Player
    get:
      tags:
      - Player
      operationId: get-recently-played
      x-spotify-docs-endpoint-name: Get Current User's Recently Played Tracks
      x-spotify-docs-console-url: /console/get-recently-played/
      summary: |
        Get Recently Played Tracks
      description: |
        Get tracks from the current user's recently played tracks.
        _**Note**: Currently doesn't support podcast episodes._
      security:
      - oauth_2_0:
        - user-read-recently-played
  /me/player/queue:
    x-spotify-docs-display-name: queue
    x-spotify-docs-category: Player
    get:
      tags:
      - Player
      operationId: get-queue
      x-spotify-docs-endpoint-name: Get the User's Queue
      x-spotify-docs-console-url: /console/get-queue/
      summary: |
        Get the User's Queue
      description: |
        Get the list of objects that make up the user's queue.
      security:
      - oauth_2_0:
        - user-read-playback-state
    post:
      tags:
      - Player
      operationId: add-to-queue
      x-spotify-docs-endpoint-name: Add an item to queue
      x-spotify-docs-console-url: /console/post-queue/
      summary: |
        Add Item to Playback Queue
      description: |
        Add an item to the end of the user's current playback queue.
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /markets:
    x-spotify-docs-display-name: available-markets
    x-spotify-docs-category: Markets
    get:
      tags:
      - Markets
      operationId: get-available-markets
      x-spotify-docs-endpoint-name: Get Available Markets
      x-spotify-docs-console-url: /console/get-available-markets/
      summary: |
        Get Available Markets
      description: |
        Get the list of markets where Spotify is available.
      security:
      - oauth_2_0: []
  /me/top/artists:
    x-spotify-docs-display-name: current-user-top-artists
    x-spotify-docs-category: Personalization
    get:
      tags:
      - Users
      - Artists
      - Library
      operationId: get-users-top-artists
      x-spotify-docs-endpoint-name: Get a User's Top Artists
      x-spotify-docs-console-url: /console/get-current-user-top-artists-and-tracks/?type=artists
      summary: |
        Get User's Top Artists
      description: |
        Get the current user's top artists based on calculated affinity.
      security:
      - oauth_2_0:
        - user-top-read
  /me/top/tracks:
    x-spotify-docs-display-name: current-user-top-tracks
    x-spotify-docs-category: Personalization
    get:
      tags:
      - Users
      - Tracks
      - Library
      operationId: get-users-top-tracks
      x-spotify-docs-endpoint-name: Get a User's Top Tracks
      x-spotify-docs-console-url: /console/get-current-user-top-artists-and-tracks/?type=tracks
      summary: |
        Get User's Top Tracks
      description: |
        Get the current user's top tracks based on calculated affinity.
      security:
      - oauth_2_0:
        - user-top-read
components:
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: |
              Communicate with the Spotify app on your device.
            playlist-read-private: |
              Access your private playlists.
            playlist-read-collaborative: |
              Access your collaborative playlists.
            playlist-modify-public: |
              Manage your public playlists.
            playlist-modify-private: |
              Manage your private playlists.
            user-library-read: |
              Access your saved content.
            user-library-modify: |
              Manage your saved content.
            user-read-private: |
              Access your subscription details.
            user-read-email: |
              Get your real email address.
            user-follow-read: |
              Access your followers and who you are following.
            user-follow-modify: |
              Manage your saved content.
            user-top-read: |
              Read your top artists and content.
            user-read-playback-position: |
              Read your position in content you have played.
            user-read-playback-state: |
              Read your currently playing content and Spotify Connect devices information.
            user-read-recently-played: |
              Access your recently played items.
            user-read-currently-playing: |
              Read your currently playing content.
            user-modify-playback-state: |
              Control playback on your Spotify clients and Spotify Connect devices.
            ugc-image-upload: |
              Upload images to Spotify on your behalf.
            streaming: |
              Play content and control playback on your other devices.