export interface HistoricalDrive {
  starting_saved_location?: string;
  ending_saved_location?: string;
  id: number;
  started_at: number;
  ended_at: number;
  created_at: number;
  updated_at: number;
  starting_location: string;
  starting_latitude: number;
  starting_longitude: number;
  starting_odometer: number;
  ending_location: string;
  ending_latitude: number;
  ending_longitude: number;
  ending_odometer: number;
  starting_battery: number;
  ending_battery: number;
  average_inside_temperature: number;
  average_outside_temperature: number;
  average_speed: number;
  max_speed: number;
  rated_range_used: number;
  ideal_range_used: number;
  odometer_distance: number;
  // non_autopilot_distance: null | any;
  // energy_used: number;
  // tag: null | any;
  // driver_profile: null | any;
  // safety_score: null | any;
  // forward_collision_warnings: null | any;
  // forward_collision_warnings_decile: null | any;
  // hard_braking_percent: null | any;
  // hard_braking_percent_decile: null | any;
  // aggressive_turning_percent: null | any;
  // aggressive_turning_percent_decile: null | any;
  // unsafe_following_percent: null | any;
  // unsafe_following_percent_decile: null | any;
  // forced_autopilot_disengagements: null | any;
  // forced_autopilot_disengagements_decile: null | any;
  // night_driving_percent: null | any;
  // night_driving_percent_decile: null | any;
  // excessive_speed_percent: null | any;
  // excessive_speed_percent_decile: null | any;
  // seatbelt_unbuckled_percent: null | any;
  // seatbelt_unbuckled_percent_decile: null | any;
}
