export interface Info {
  id: number;
  user_id: number;
  vehicle_id: number;
  vin: string;
  color: string | null;
  access_type: string;
  granular_access: {
    hide_private: boolean;
  };
  tokens: string[];
  state: string;
  in_service: boolean;
  id_s: string;
  calendar_enabled: boolean;
  api_version: number;
  backseat_token: string | null;
  backseat_token_updated_at: string | null;
  ble_autopair_enrolled: boolean;
  charge_state: {
    battery_heater_on: boolean;
    battery_level: number;
    battery_range: number;
    charge_amps: number;
    charge_current_request: number;
    charge_current_request_max: number;
    charge_enable_request: boolean;
    charge_energy_added: number;
    charge_limit_soc: number;
    charge_limit_soc_max: number;
    charge_limit_soc_min: number;
    charge_limit_soc_std: number;
    charge_miles_added_ideal: number;
    charge_miles_added_rated: number;
    charge_port_cold_weather_mode: boolean;
    charge_port_color: string;
    charge_port_door_open: boolean;
    charge_port_latch: string;
    charge_rate: number;
    charger_actual_current: number;
    charger_phases: number;
    charger_pilot_current: number;
    charger_power: number;
    charger_voltage: number;
    charging_state: string;
    conn_charge_cable: string;
    est_battery_range: number;
    fast_charger_brand: string;
    fast_charger_present: boolean;
    fast_charger_type: string;
    ideal_battery_range: number;
    managed_charging_active: boolean;
    managed_charging_start_time: string | null;
    managed_charging_user_canceled: boolean;
    max_range_charge_counter: number;
    minutes_to_full_charge: number;
    not_enough_power_to_heat: string | null;
    off_peak_charging_enabled: boolean;
    off_peak_charging_times: string;
    off_peak_hours_end_time: number;
    preconditioning_enabled: boolean;
    preconditioning_times: string;
    scheduled_charging_mode: string;
    scheduled_charging_pending: boolean;
    scheduled_charging_start_time: string | null;
    scheduled_charging_start_time_app: number;
    scheduled_departure_time: number;
    scheduled_departure_time_minutes: number;
    supercharger_session_trip_planner: boolean;
    time_to_full_charge: number;
    timestamp: number;
    trip_charging: boolean;
    usable_battery_level: number;
    user_charge_enable_request: string | null;
  };
  display_name: string;
  climate_state: {
    battery_heater: boolean;
    battery_heater_no_power: boolean | null;
    climate_keeper_mode: string;
    driver_temp_setting: number;
    fan_status: number;
    inside_temp: number | null;
    is_auto_conditioning_on: boolean | null;
    is_climate_on: boolean;
    is_front_defroster_on: boolean | null;
    is_preconditioning: boolean;
    is_rear_defroster_on: boolean;
    left_temp_direction: number | null;
    max_avail_temp: number;
    min_avail_temp: number;
    outside_temp: number | null;
    passenger_temp_setting: number;
    remote_heater_control_enabled: boolean | null;
    right_temp_direction: number | null;
    seat_heater_left: number | null;
    seat_heater_rear_center: number | null;
    seat_heater_rear_left: number | null;
    seat_heater_rear_left_back: number | null;
    seat_heater_rear_right: number | null;
    seat_heater_rear_right_back: number | null;
    seat_heater_right: number | null;
    side_mirror_heaters: boolean | null;
    smart_preconditioning: boolean | null;
    steering_wheel_heater: boolean | null;
    timestamp: number;
    wiper_blade_heater: boolean;
  };
  vehicle_state: {
    api_version: number;
    autopark_state_v3: string;
    autopark_style: string;
    calendar_supported: boolean;
    car_version: string;
    center_display_state: number;
    df: number;
    dr: number;
    fd_window: number;
    fp_window: number;
    ft: number;
    is_user_present: boolean;
    last_autopark_error: string;
    locked: boolean;
    notifications_supported: boolean;
    odometer: number;
    parsed_calendar_supported: boolean;
    pf: number;
    pr: number;
    rd_window: number;
    remote_start: boolean;
    remote_start_enabled: boolean;
    remote_start_supported: boolean;
    rp_window: number;
    rt: number;
    sentry_mode: boolean;
    software_update: {
      expected_duration_sec: number;
      status: string;
    };
    speed_limit_mode: {
      active: boolean;
      current_limit_mph: number;
      max_limit_mph: number;
      min_limit_mph: number;
      pin_code_set: boolean;
    };
    summon_standby_mode_enabled: boolean;
    timestamp: number;
    valet_mode: boolean;
    valet_pin_needed: boolean;
    vehicle_name: string;
  };
  vehicle_config: {
    aux_park_lamps: string;
    badge_version: number;
    can_accept_navigation_requests: boolean;
    can_actuate_trunks: boolean;
    car_special_type: string;
    car_type: string;
    charge_port_type: string;
    cop_user_set_temp_supported: boolean;
    dashcam_clip_save_supported: boolean;
    default_charge_to_max: boolean;
    driver_assist: string;
    ece_restrictions: boolean;
    efficiency_package: string;
    eu_vehicle: boolean;
    exterior_color: string;
    exterior_trim: string;
    exterior_trim_override: string;
    has_air_suspension: boolean;
    has_ludicrous_mode: boolean;
    has_seat_cooling: boolean;
    headlamp_type: string;
    interior_trim_type: string;
    key_version: number;
    motorized_charge_port: boolean;
    paint_color_override: string;
    performance_package: string;
    plg: boolean;
    pws: boolean;
    rear_drive_unit: string;
    rear_seat_heaters: number;
    rear_seat_type: number;
    rhd: boolean;
    roof_color: string;
    seat_type: string | null;
    spoiler_type: string;
    sun_roof_installed: string | null;
    supports_qr_pairing: boolean;
    third_row_seats: string;
    timestamp: number;
    trim_badging: string;
    use_range_badging: boolean;
    utc_offset: number;
    webcam_selfie_supported: boolean;
    webcam_supported: boolean;
    wheel_type: string;
  };
}
