export const sportNames: { [key: string]: string } = {
  AlpineSki: "Alpine Ski",
  BackcountrySki: "Backcountry Ski",
  Canoeing: "Canoeing",
  Crossfit: "Crossfit",
  EBikeRide: "E-Bike Ride",
  Elliptical: "Elliptical",
  Hike: "Hike",
  IceSkate: "Ice Skate",
  InlineSkate: "Inline Skate",
  Kayaking: "Kayaking",
  Kitesurf: "Kitesurf",
  NordicSki: "Nordic Ski",
  Ride: "Ride",
  RockClimbing: "Rock Climbing",
  RollerSki: "Roller Ski",
  Rowing: "Rowing",
  Run: "Run",
  Snowboard: "Snowboard",
  Snowshoe: "Snowshoe",
  StairStepper: "Stair Stepper",
  StandUpPaddling: "Stand Up Paddling",
  Surfing: "Surfing",
  Swim: "Swim",
  VirtualRide: "Virtual Ride",
  Walk: "Walk",
  WeightTraining: "Weight Training",
  Windsurf: "Windsurf",
  Workout: "Workout",
  Yoga: "Yoga",
};

export const sportIcons: { [key: string]: string } = {
  Run: "run.svg",
  Ride: "ride.svg",
  VirtualRide: "ride.svg",
  EBikeRide: "ride-Ebike.svg",
  Swim: "swim.svg",
  Hike: "hike.svg",
  Walk: "walk.svg",
  AlpineSki: "ski.svg",
  NordicSki: "ski.svg",
  Workout: "workout.svg",
  WeightTraining: "workout.svg",
  Yoga: "yoga.svg",
};
