/** When the chooser opens for a link no handler routes: always, or only while fn is held. */
export type ChooserMode = "always" | "fn";

/** One remembered rule: `match` is Finicky matcher source, `browser` is a Finicky browser spec. */
export type Rule = { match: string; browser: string };

/**
 * Everything that varies in ~/.finickizer.js. The file is generated from this and parsed back into it,
 * so it never needs a JavaScript parser. Rule lines are kept verbatim, hand edits and comments included.
 */
export type Entry = { originalPath: string; gluePath: string; mode: ChooserMode; ruleLines: string[] };

const RULES_OPEN = "  rules: [";
const RULES_CLOSE = "  ],";

export function renderEntry({ originalPath, gluePath, mode, ruleLines }: Entry): string {
  return `// Finickizer entry config. Generated by the Finickizer Raycast extension.
//
// DO NOT EDIT THIS FILE BY HAND. Finickizer rewrites it and reads it back line by line, so a
// changed or reformatted file breaks saving rules from the chooser. To delete, reorder or
// retarget rules use "Manage Rules" in Raycast. Everything else belongs in your own config.
//
// Finicky loads this file because ~/.finicky.js is now a symlink to it. Your own Finicky config
// was moved, unchanged, and is imported below from:
//
//   ${originalPath}
//
// Why: Finickizer adds two things to your config, a fallback that opens the Raycast browser chooser
// for links nothing routes, and the rules you remember from that chooser. Adding them here means
// no tool ever has to edit your own config. Everything in it keeps working as before.
//
// Keep editing your config at the path above. Finicky only watches this file, not the files it
// imports, so after a change run "Reload Finicky Config" in Raycast (it also runs by itself
// within a minute). To undo all of this, run "Unpatch Finicky Config".
//
// "Patch Finicky Config" regenerates everything in this file except the lines inside \`rules\`.

import config from ${JSON.stringify(originalPath)};
import finickizer from ${JSON.stringify(gluePath)};

// prettier-ignore
export default finickizer(config, {
  // When to open the chooser for a link nothing routes: "always", or "fn" for only while fn is held
  // (a plain click then goes to your defaultBrowser). Change it with "Patch Finicky Config".
  mode: ${JSON.stringify(mode)},
  // Rules remembered from the chooser, applied in this order after your own handlers.
  // Managed by "Manage Rules" in Raycast. To give a rule priority over your handlers, copy it into your config.
${RULES_OPEN}
${ruleLines.map((line) => `${line}\n`).join("")}${RULES_CLOSE}
});
`;
}

export function parseEntry(source: string): Entry {
  const original = /^import config from (".*");$/m.exec(source);
  const glue = /^import finickizer from (".*");$/m.exec(source);
  const mode = /^\s*mode:\s*"(always|fn)",/m.exec(source);
  const lines = source.split("\n");
  const open = lines.findIndex((line) => line.trimEnd() === RULES_OPEN);
  const close = lines.findIndex((line, index) => index > open && line.trimEnd() === RULES_CLOSE);
  if (!original || !glue || !mode || open === -1 || close === -1) {
    throw new Error("~/.finickizer.js is no longer in the shape Finickizer generated");
  }
  return {
    originalPath: JSON.parse(original[1]),
    gluePath: JSON.parse(glue[1]),
    mode: mode[1] as ChooserMode,
    ruleLines: lines.slice(open + 1, close),
  };
}

export function renderRuleLine(rule: Rule): string {
  return `    { match: ${rule.match}, browser: ${JSON.stringify(rule.browser)} },`;
}

/** A readable name for the two matcher shapes Finickizer writes; anything else is shown as its source. */
export function describeMatch(match: string): { title: string; subtitle?: string } {
  const host = /^finicky\.matchHostnames\("([^"]+)"\)$/.exec(match);
  if (host) return { title: host[1] };
  const apex = /^finicky\.matchHostnames\(\["([^"]+)",\s*\/.+\/\]\)$/.exec(match);
  if (apex) return { title: `*.${apex[1]}`, subtitle: `and ${apex[1]} itself` };
  return { title: match };
}

/** Replaces the rule line with the same match, or appends a new one. Other lines are left alone. */
export function upsertRuleLine(ruleLines: string[], rule: Rule): string[] {
  const line = renderRuleLine(rule);
  const index = ruleLines.findIndex((existing) => squash(parseRuleLine(existing)?.match ?? "") === squash(rule.match));
  if (index === -1) return [...ruleLines, line];
  return ruleLines.map((existing, i) => (i === index ? line : existing));
}

export function parseRuleLine(line: string): Rule | null {
  const match = /^\s*\{\s*match:\s*(.+?),\s*browser:\s*("(?:[^"\\]|\\.)*")\s*\},?\s*$/.exec(line);
  return match ? { match: match[1], browser: JSON.parse(match[2]) } : null;
}

export function countRules(ruleLines: string[]): number {
  return ruleLines.filter((line) => parseRuleLine(line) !== null).length;
}

function squash(text: string): string {
  return text.replace(/\s+/g, "");
}
