export const tags = {
  level: ["beginner", "intermediate", "expert"],
  muscles: [
    "glutes",
    "quadriceps",
    "abs",
    "hamstrings",
    "calves",
    "adductors",
    "biceps",
    "forearms",
    "shoulders",
    "abductors",
    "triceps",
    "chest",
    "lower back",
    "traps",
    "middle back",
    "lats",
    "neck",
  ],
  equipment: [
    "bodyweight",
    "kettlebells",
    "dumbbell",
    "barbell",
    "foam roller",
    "bands",
    "medicine ball",
    "exercise ball",
    "machine",
    "other",
    "cable",
    "EZ bar",
  ],
  category: ["strength", "stretching", "plyometrics", "strongman", "powerlifting", "cardio", "olympic weightlifting"],
  force: ["pull", "push", "static"],
};
