export function getCountryName(countryCode: string | undefined): string {
  if (!countryCode) return "";
  const code = countryCode.toUpperCase();

  const countryCodeToName: Record<string, string> = {
    GB: "United Kingdom",
    SE: "Sweden",
    IT: "Italy",
    NL: "Netherlands",
    IL: "Israel",
    UA: "Ukraine",
    PT: "Portugal",
    AT: "Austria",
    DK: "Denmark",
    NO: "Norway",
    IE: "Ireland",
    FR: "France",
    DE: "Germany",
    ES: "Spain",
    CH: "Switzerland",
    FI: "Finland",
    BE: "Belgium",
    LU: "Luxembourg",
    MC: "Monaco",
    RS: "Serbia",
    RU: "Russia",
    TR: "Türkiye",
    GR: "Greece",
    EE: "Estonia",
    LV: "Latvia",
    LT: "Lithuania",
    PL: "Poland",
    CZ: "Czechia",
    SK: "Slovakia",
    SI: "Slovenia",
    HR: "Croatia",
    BA: "Bosnia and Herzegovina",
    MK: "North Macedonia",
    AL: "Albania",
    RO: "Romania",
    BG: "Bulgaria",
    MD: "Moldova",
    BY: "Belarus",
    AZ: "Azerbaijan",
    AM: "Armenia",
    GE: "Georgia",
    IS: "Iceland",
    MT: "Malta",
    CY: "Cyprus",
    AU: "Australia",
    ME: "Montenegro",
    SM: "San Marino",
    AD: "Andorra",
    HU: "Hungary",
    KZ: "Kazakhstan",
    MA: "Morocco",
    "GB-WLS": "Wales",
    WLD: "Rest of the World",
    // Old country codes
    YU: "Yugoslavia",
    CS: "Serbia and Montenegro",
    SU: "Soviet Union",
    DD: "East Germany",
    ZR: "Zaire",
    AN: "Netherlands Antilles",
  };

  return countryCodeToName[code] || "";
}
