export const defaultCommands = {
  "Compose Tweet":
    '{"iconColor":"raycast-blue","useBarcodeDetection":true,"acceptedFileExtensions":"","useSubjectClassification":true,"showResponse":true,"name":"Compose Tweet","outputKind":"detail","prompt":"Compose a tweet based on the following files:","minNumFiles":"1","actionScript":"","description":"Drafts a tweet based on the contents of selected files.","useFaceDetection":false,"icon":"bird-16","useSoundClassification":true,"useRectangleDetection":false,"useAudioDetails":true,"useMetadata":false}',
  "Recent Headlines From 68k News":
    '{"description":"Summarizes headlines from 68k news","useSubjectClassification":false,"iconColor":"raycast-blue","actionScript":"","icon":"important-01-16","outputKind":"detail","name":"Recent Headlines From 68k News","useAudioDetails":false,"minNumFiles":"0","useRectangleDetection":false,"showResponse":true,"useMetadata":false,"useSoundClassification":false,"prompt":"Discuss the recent headlines from 68k News:\\n###\\n{{http://68k.news}}\\n###","useBarcodeDetection":false,"acceptedFileExtensions":"","useFaceDetection":false}',
  "Identify Selected Files":
    '{"iconColor":"raycast-primary-text","useSoundClassification":true,"useSubjectClassification":true,"useRectangleDetection":true,"showResponse":true,"useFaceDetection":true,"actionScript":"","description":"Identifies the type, purpose, category, and use of selected files","useAudioDetails":true,"name":"Identify Selected Files","outputKind":"detail","icon":"magnifying-glass-16","prompt":"Identify the file type and most significant features of the following files based on their content. Discuss the primary purpose of the file based on its content. Categorize the content into relevant topics. Provide an assessment of the file\'s utility as well a list of relevant links and brief descriptions of them. Format the response as a markdown list using \\"## File Type\\", \\"## Topics\\", \\"## Defining Features\\", \\"## Purpose and Potential Usage\\", and \\"## Relevant Links\\" as headings.","minNumFiles":"1","acceptedFileExtensions":"","useBarcodeDetection":true,"useMetadata":true}',
  "Make Jingle":
    '{"useSubjectClassification":true,"iconColor":"raycast-red","useFaceDetection":true,"useAudioDetails":true,"useRectangleDetection":false,"useSoundClassification":true,"useMetadata":false,"acceptedFileExtensions":"","minNumFiles":"1","description":"Generates a memorable tune based on the selected files","prompt":"Create short, memorable jingles summarizing the main ideas in each of the following files, using the file names as headings.","showResponse":true,"icon":"music-16","useBarcodeDetection":false,"actionScript":"","outputKind":"detail","name":"Make Jingle"}',
  "Create Action Items":
    '{"useBarcodeDetection":true,"useRectangleDetection":false,"useSubjectClassification":true,"acceptedFileExtensions":"","prompt":"Generate a markdown list of action items from the following files, using a unique identifier for each item as bold headings. If there are any errors in the files, make actions items to fix them. In a sublist of each item, provide a description, priority, estimated level of difficulty, reasonable duration for the task, and due date based on the the duration and today\'s date, \\"{{date}}\\". Here are the files:","iconColor":"raycast-red","description":"Provides an itemized list of tasks relevant to the selected files","name":"Create Action Items","useAudioDetails":true,"outputKind":"detail","showResponse":true,"useFaceDetection":false,"minNumFiles":"1","useMetadata":false,"icon":"app-window-list-16","actionScript":"","useSoundClassification":true}',
  "Extract URLs":
    '{"iconColor":"raycast-purple","useSubjectClassification":false,"useFaceDetection":false,"useAudioDetails":true,"useRectangleDetection":false,"useSoundClassification":false,"useMetadata":false,"acceptedFileExtensions":"","minNumFiles":"1","description":"","prompt":"Extract URLs from the following files and list them as markdown links","showResponse":true,"icon":"link-16","useBarcodeDetection":true,"actionScript":"","outputKind":"detail","name":"Extract URLs"}',
  "Extract Visible Text":
    '{"useBarcodeDetection":true,"useRectangleDetection":false,"useSubjectClassification":false,"acceptedFileExtensions":"png, jpg, jpeg, gif, bmp, astc, tiff","prompt":"I want you to output the text content identified below. Preserve the original format of the content as best as possible. Always output something.","iconColor":"raycast-purple","description":"Obtains the text within an image using OCR","name":"Extract Visible Text","useAudioDetails":false,"outputKind":"detail","showResponse":true,"useFaceDetection":false,"minNumFiles":"1","useMetadata":false,"icon":"text-16","actionScript":"","useSoundClassification":false}',
  "Identify Gaps":
    '{"icon":"arrows-expand-16","minNumFiles":"1","iconColor":"raycast-primary-text","useSubjectClassification":false,"useSoundClassification":false,"showResponse":true,"useRectangleDetection":false,"acceptedFileExtensions":"","useBarcodeDetection":true,"prompt":"Identify any gaps in understanding or content that occur in the following files. Use the file names as headings. Provide content to fill in the gaps.","useAudioDetails":true,"description":"","actionScript":"","name":"Identify Gaps","outputKind":"detail","useFaceDetection":false,"useMetadata":false}',
  "Write Caption":
    '{"useAudioDetails":true,"useMetadata":false,"description":"Drafts a brief caption for files","name":"Write Caption","useBarcodeDetection":true,"outputKind":"detail","useRectangleDetection":false,"acceptedFileExtensions":"","useSoundClassification":true,"useSubjectClassification":true,"useFaceDetection":false,"prompt":"Write a two-sentence caption for these files in the style of a typical image caption, based on their contents. Use the file names as headings. The caption should summarize the content and describe its overall purpose and significance.","showResponse":true,"actionScript":"","minNumFiles":"1","iconColor":"raycast-yellow","icon":"text-cursor-16"}',
  "Suggest PromptLab Commands":
    '{"acceptedFileExtensions":"","iconColor":"raycast-magenta","useSoundClassification":false,"showResponse":true,"name":"Suggest PromptLab Commands","minNumFiles":"0","useSubjectClassification":false,"icon":"desktop-16","useBarcodeDetection":false,"prompt":"Based on my current commands for the PromptLab extension, suggest new commands to create. Provide suggestions for titles as well prompts. The prompts must be relevant to an AI that can read the content of files, get information about the system, and get outside  data such as calendar events. The commands must be unique. Format the response as a single markdown list. Here are the commands I currently have: {{promptlabCommands}}","useAudioDetails":false,"outputKind":"detail","actionScript":"","description":"Lists new prompt ideas based on all of your current prompts.","useMetadata":false,"useFaceDetection":false,"useRectangleDetection":false}',
  "Pattern Analysis":
    '{"useFaceDetection":true,"useRectangleDetection":true,"useAudioDetails":true,"acceptedFileExtensions":"","description":"Identify and describe any patterns or trends in the content of the following files. Use the file names as headers. Discuss patterns formed by any coordinates, rectangles, etc. Do not mention coordinates.","useSoundClassification":true,"iconColor":"raycast-primary-text","name":"Pattern Analysis","minNumFiles":"1","useBarcodeDetection":true,"showResponse":true,"icon":"line-chart-16","useSubjectClassification":true,"actionScript":"","outputKind":"detail","useMetadata":true,"prompt":"Identify and describe any patterns or trends in the content of the following files. Use the file names as headers. Discuss patterns formed by any coordinates, rectangles, etc. Do not mention coordinates."}',
  "Metadata Analysis":
    '{"useBarcodeDetection":true,"icon":"magnifying-glass-16","showResponse":true,"outputKind":"detail","minNumFiles":"1","prompt":"I want you to give several insights about files based on their metadata and file type. Do not summarize the file content, but instead relate the metadata to the content in a meaningful way. Use metadata to suggest improvements to the content. Provide detailed explanations for your suggestions. Format your response as a paragraph summary. Use the file names as headings.\\nHere\'s the metadata:\\n{{metadata}}\\n\\nHere are the files:","useSoundClassification":true,"iconColor":"raycast-primary-text","actionScript":"","useFaceDetection":true,"acceptedFileExtensions":"","useMetadata":true,"description":"Discusses insights derived from the metadata of selected files","useSubjectClassification":true,"name":"Metadata Analysis","useRectangleDetection":true,"useAudioDetails":true}',
  "Today's Agenda":
    '{"iconColor":"raycast-blue","useSubjectClassification":false,"useFaceDetection":false,"useAudioDetails":false,"useRectangleDetection":false,"useSoundClassification":false,"useMetadata":false,"acceptedFileExtensions":"","minNumFiles":"0","description":"Creates an itemized agenda for today","prompt":"Make an agenda for my day using the following list of events. Format the output as friendly paragraph, directed at my, explaining when there is time for breaks or other activities that you recommend. Use today\'s date ({{date}}) as a markdown header. Here are the events:\\n\\n###\\n{{todayEvents}}\\n{{todayReminders}}\\n###","showResponse":true,"icon":"calendar-16","useBarcodeDetection":false,"actionScript":"","outputKind":"detail","name":"Today\'s Agenda"}',
  "Compare Selected Files":
    '{"showResponse":true,"outputKind":"detail","useFaceDetection":true,"acceptedFileExtensions":"","iconColor":"raycast-primary-text","name":"Compare Selected Files","useMetadata":true,"description":"Provides a detailed comparison of selected files","useSubjectClassification":true,"icon":"contrast-16","minNumFiles":"2","actionScript":"","useRectangleDetection":true,"useSoundClassification":true,"prompt":"Compare and contrast the content, purpose, and significance of the following files. What are the similarities and differences between them? Format the response as one markdown paragraph.","useAudioDetails":true,"useBarcodeDetection":true}',
  "Assess Academic Validity":
    '{"iconColor":"raycast-primary-text","useSoundClassification":false,"actionScript":"","outputKind":"detail","useSubjectClassification":true,"useAudioDetails":true,"acceptedFileExtensions":"","minNumFiles":"1","icon":"book-16","showResponse":true,"useBarcodeDetection":false,"useRectangleDetection":false,"prompt":"Assess the academic validity of the following files based on their contents, the methodologies described within, and any results obtained. Use the file names as headings.","useFaceDetection":false,"useMetadata":false,"name":"Assess Academic Validity","description":"Provides a review of the truthiness, integrity, and overall value of selected files"}',
  "Extract Vocabulary":
    '{"useBarcodeDetection":true,"useRectangleDetection":false,"useSubjectClassification":false,"acceptedFileExtensions":"","prompt":"Extract the most difficult vocabulary words from the following files and define them. Format the response as a markdown list.","iconColor":"raycast-purple","description":"Defines the difficult vocabulary in selected files","name":"Extract Vocabulary","useAudioDetails":true,"showResponse":true,"outputKind":"detail","useFaceDetection":false,"minNumFiles":"1","useMetadata":false,"icon":"book-16","actionScript":"","useSoundClassification":false}',
  "Respond To Last Email":
    '{"useSoundClassification":false,"icon":"envelope-16","showResponse":true,"prompt":"Generate a response to the following email:\\n###\\n{{lastEmail}}\\n###","useAudioDetails":false,"name":"Respond To Last Email","description":"Drafts a response to the last email you received","actionScript":"","acceptedFileExtensions":"","useBarcodeDetection":false,"useSubjectClassification":false,"outputKind":"detail","useRectangleDetection":false,"minNumFiles":"0","useFaceDetection":false,"useMetadata":false,"iconColor":"raycast-yellow"}',
  "Create Notes":
    '{"acceptedFileExtensions":"","description":"Provides notes on the subject matter of the selected files","useRectangleDetection":false,"minNumFiles":"1","useSoundClassification":true,"useAudioDetails":true,"iconColor":"raycast-red","actionScript":"","useSubjectClassification":true,"useBarcodeDetection":true,"name":"Create Notes","useFaceDetection":false,"useMetadata":false,"showResponse":true,"prompt":"I want you to act as a notetaker. I will provide file names and their contents, and you will respond with a multi-level markdown list of well-structured, concise notes. The notes should be in your own words and should make connections between topics and ideas. Each list item should be at most 20 words long. Minimize the notes as much as possible. Here are the files:","outputKind":"detail","icon":"bullet-points-16"}',
  "Suggest Fonts":
    '{"useMetadata":false,"acceptedFileExtensions":"","iconColor":"raycast-magenta","useRectangleDetection":true,"useAudioDetails":false,"prompt":"Here are spme fonts I have installed. Identify some trends in my font choices, then recommend 5 unique fonts that I might like based on those trends. For each recommendation, explain why I might like it in relation to other fonts I have installed.\\nHere are the fonts:\\n{{as:use framework \\"Foundation\\"\\rset fontManager to current application\'s NSFontManager\'s sharedFontManager()\\rset allFonts to fontManager\'s availableFonts() as list\\rset randomFonts to {}\\rrepeat 25 times\\r\\tcopy some item of allFonts to end of randomFonts\\rend repeat\\rreturn randomFonts}}","actionScript":"","name":"Suggest Fonts","useSubjectClassification":true,"useFaceDetection":true,"useBarcodeDetection":true,"useSoundClassification":true,"outputKind":"detail","showResponse":true,"description":"Lists fonts you might like based on the fonts you have installed","icon":"text-16","minNumFiles":"0"}',
  "Generate Questions":
    '{"useAudioDetails":true,"description":"Lists questions related to the selected files","actionScript":"","useFaceDetection":true,"outputKind":"detail","useRectangleDetection":true,"prompt":"Generate questions based on the content of each of the following files, their metadata, filename, type, and other information. Format the response as a markdown list.","useMetadata":true,"iconColor":"raycast-red","showResponse":true,"icon":"question-mark-circle-16","acceptedFileExtensions":"","useSubjectClassification":true,"minNumFiles":"1","useBarcodeDetection":true,"name":"Generate Questions","useSoundClassification":true}',
  "Suggest Improvements":
    '{"useMetadata":true,"showResponse":true,"useSoundClassification":true,"useRectangleDetection":true,"useFaceDetection":true,"actionScript":"","prompt":"Suggest improvements to the content of the following files. Use the file names as headings. Format the response as a markdown list.","useAudioDetails":true,"minNumFiles":"1","description":"Lists possible improvements to the selected files","name":"Suggest Improvements","useBarcodeDetection":true,"useSubjectClassification":true,"acceptedFileExtensions":"","outputKind":"detail","icon":"stars-16","iconColor":"raycast-magenta"}',
  "Create Slides":
    '{"useRectangleDetection":false,"useFaceDetection":false,"useBarcodeDetection":true,"minNumFiles":"1","icon":"play-16","outputKind":"detail","name":"Create Slides","showResponse":true,"prompt":"Generate 3 or more slideshow slides for each of the following files based on their content. Each slide should have 3 or 4 meaningful bullet points. Organize the slides by topic. Format the slides as markdown lists with \'---\' separating each slide. Describe an image to include with each slide. Suggest links related to each slide\'s content. Provide an appropriate title for the slideshow at the beginning of the response.","acceptedFileExtensions":"","useSubjectClassification":true,"actionScript":"","useMetadata":false,"description":"Separates the subject matter of the selected files into slides. Outputs text and suggested images with each slide separated by three dashes.","iconColor":"raycast-red","useAudioDetails":true,"useSoundClassification":true}',
  "Write Introduction":
    '{"useRectangleDetection":false,"useAudioDetails":true,"prompt":"Write improved introduction sections for the following files in the style of an academic research paper. Use the file names as headings. The introductions must be at least 3 paragraphs long and describe what the file\'s contents are about, in future tense, as well as provide background information and a summary of the results. If the introduction includes a list, briefly describe the list instead of listing all elements.","minNumFiles":"1","description":"Drafts introduction sections for papers (or files) in their existing style","acceptedFileExtensions":"","useBarcodeDetection":true,"actionScript":"","name":"Write Introduction","iconColor":"raycast-yellow","outputKind":"detail","useSubjectClassification":true,"useMetadata":false,"useFaceDetection":false,"icon":"text-cursor-16","showResponse":true,"useSoundClassification":true}',
  "Identify Relationships":
    '{"useSubjectClassification":true,"acceptedFileExtensions":"","description":"Identifies various relationships between two or more files","useFaceDetection":false,"name":"Identify Relationships","useBarcodeDetection":true,"useMetadata":true,"actionScript":"","showResponse":true,"minNumFiles":"2","useSoundClassification":true,"outputKind":"detail","useAudioDetails":true,"useRectangleDetection":true,"prompt":"In one paragraph, identify any relationships that might exist between the following files based on their content and the topics they mention. Always identify some relationship, even if it is very general. Explain a use for the files together that none of them have individually.","iconColor":"raycast-primary-text","icon":"box-16"}',
  "Detect Bias":
    '{"name":"Detect Bias","useAudioDetails":true,"showResponse":true,"icon":"chevron-right-16","minNumFiles":"1","actionScript":"","useBarcodeDetection":false,"useRectangleDetection":false,"useFaceDetection":false,"description":"Discusses any biases in the selected files","iconColor":"raycast-primary-text","acceptedFileExtensions":"","prompt":"Identify and explain the significance of any biases in the content of the following files. Discuss what the risks and dangers of those biases are, and discuss how those risks could be minimized.","useSubjectClassification":false,"useMetadata":false,"outputKind":"detail","useSoundClassification":false}',
  "Summarize Spoken Audio":
    '{"icon":"speaker-on-16","description":"Summarizes the spoken content of audio files","useRectangleDetection":false,"useSubjectClassification":false,"useMetadata":false,"useBarcodeDetection":false,"showResponse":true,"outputKind":"detail","prompt":"Summarize and assess the the following audio files using the file names as headings. Discuss the transcribed text\'s purpose and significance. Here are the audio transcriptions:","name":"Summarize Spoken Audio","actionScript":"","acceptedFileExtensions":"mp3, wav, m4a, ogg, aiff, aac, flac, mp4","minNumFiles":"1","useSoundClassification":false,"iconColor":"raycast-orange","useAudioDetails":true,"useFaceDetection":false}',
  "Find Errors":
    '{"icon":"bug-16","description":"Identifies semantic and syntactic errors in selected files","useRectangleDetection":false,"useSubjectClassification":false,"useMetadata":false,"useBarcodeDetection":true,"showResponse":true,"outputKind":"detail","prompt":"What errors and inconsistencies in the following files, why are they significant, and how can I fix them? Format the response as markdown list of sentences with the file names in bold. Use the file names as headings.","name":"Find Errors","actionScript":"","acceptedFileExtensions":"","minNumFiles":"1","useSoundClassification":false,"iconColor":"raycast-primary-text","useAudioDetails":true,"useFaceDetection":false}',
  "Summarize Clipboard":
    '{"useSoundClassification":false,"icon":"copy-clipboard-16","prompt":"Summarize the following text, providing specific details.\\n###\\n{{clipboardText}}\\n###","name":"Summarize Clipboard","minNumFiles":"0","acceptedFileExtensions":"","useSubjectClassification":false,"useFaceDetection":false,"showResponse":true,"outputKind":"detail","useAudioDetails":false,"useMetadata":false,"useBarcodeDetection":false,"useRectangleDetection":false,"description":"","iconColor":"raycast-orange","actionScript":""}',
  "Extract Named Entities":
    '{"useSoundClassification":false,"icon":"person-lines-16","showResponse":true,"prompt":"What are the named entities in the following files, and what are their meanings and purpose? Clarify any abbreviations. Format the response as markdown list of sentences with the entity terms in bold. Use the file names as headings.","useAudioDetails":true,"name":"Extract Named Entities","description":"Identifies and defines people, places, and organizations in the contents of selected files","actionScript":"","acceptedFileExtensions":"","useBarcodeDetection":true,"useSubjectClassification":false,"outputKind":"detail","useRectangleDetection":false,"minNumFiles":"1","useFaceDetection":false,"useMetadata":false,"iconColor":"raycast-purple"}',
  "Recommend Apps":
    '{"useRectangleDetection":false,"useFaceDetection":false,"useBarcodeDetection":false,"minNumFiles":"0","outputKind":"detail","icon":"app-window-grid-3x3-16","name":"Recommend Apps","showResponse":true,"prompt":"Based on the list of apps I have installed, recommend 10 additional macOS applications that I might enjoy. Explain the significance of the relationship between each recommendation and my installed apps. Use any knowledge you have about the apps to inform your suggestions. Format the output as a markdown list. At the start, provide a paragraph analyzing common themes of my apps, directed at me.\\n\\nHere is the list of apps I have installed:\\n###\\n{{installedApps}}\\n###","useMetadata":false,"useSubjectClassification":false,"actionScript":"","acceptedFileExtensions":"","description":"Provides a list of apps you might like based on the apps you have installed","iconColor":"raycast-magenta","useAudioDetails":false,"useSoundClassification":false}',
  "Compose Response":
    '{"showResponse":true,"useBarcodeDetection":true,"actionScript":"","useAudioDetails":true,"minNumFiles":"1","useMetadata":false,"icon":"text-cursor-16","prompt":"Compose a response to the following files in the style of an email. Sign the email with the name \\"{{user}}\\"","useSubjectClassification":true,"useRectangleDetection":false,"useSoundClassification":true,"acceptedFileExtensions":"","outputKind":"detail","useFaceDetection":false,"description":"Drafts a signed email response to selected files","iconColor":"raycast-yellow","name":"Compose Response"}',
  "Translate Files To English":
    '{"showResponse":true,"useBarcodeDetection":true,"actionScript":"","useAudioDetails":true,"minNumFiles":"1","useMetadata":false,"icon":"text-16","prompt":"Translate the following files to English, using the file names as headings. Reword the translations so that they make sense in plain English. If the phrase is well known in either English or the source language, use the most commonly accepted translation.","useSubjectClassification":false,"useRectangleDetection":false,"useSoundClassification":false,"acceptedFileExtensions":"","outputKind":"detail","useFaceDetection":false,"description":"Translates selected files from any language to English","iconColor":"raycast-yellow","name":"Translate Files To English"}',
  "Extract Phone Numbers":
    '{"useBarcodeDetection":true,"useRectangleDetection":false,"useSubjectClassification":false,"acceptedFileExtensions":"","prompt":"Identify all phone numbers in the following files and list them using markdown. Include anything that might be a phone number. If possible, provide the name of the person or company to which the phone number belongs.","iconColor":"raycast-purple","description":"","name":"Extract Phone Numbers","useAudioDetails":true,"outputKind":"detail","showResponse":true,"useFaceDetection":false,"minNumFiles":"1","useMetadata":false,"icon":"phone-16","actionScript":"","useSoundClassification":false}',
  "Extend File":
    '{"name":"Extend File","useSoundClassification":false,"showResponse":true,"useMetadata":false,"useAudioDetails":true,"iconColor":"raycast-yellow","acceptedFileExtensions":"","prompt":"Generate new content for the following files using the same style as the rest of the file\'s content. Explain how the new content fits with the rest. Do not repeat the current content. Use the file names as headings.","icon":"arrows-expand-16","description":"Gets text for a longer form of each selected file","outputKind":"detail","actionScript":"","useRectangleDetection":false,"minNumFiles":"1","useFaceDetection":false,"useSubjectClassification":false,"useBarcodeDetection":false}',
  "Suggest Hashtags":
    '{"showResponse":true,"useBarcodeDetection":true,"actionScript":"","useAudioDetails":true,"minNumFiles":"1","useMetadata":false,"icon":"hashtag-16","useSubjectClassification":true,"prompt":"Suggest hashtags for the following files based on their contents. Use the file names as markdown headings.","useRectangleDetection":false,"useSoundClassification":true,"outputKind":"detail","acceptedFileExtensions":"","useFaceDetection":true,"description":"Provides a list of hashtags related to the selected files","iconColor":"raycast-magenta","name":"Suggest Hashtags"}',
  "Write Conclusion":
    '{"minNumFiles":"1","name":"Write Conclusion","actionScript":"","useBarcodeDetection":true,"iconColor":"raycast-yellow","useFaceDetection":false,"icon":"text-cursor-16","useRectangleDetection":false,"prompt":"Write conclusions for the following files in the style of the rest of their content, using the file names as headers. The conclusion should wrap up the meaning, purpose, significance, pitfalls, room to improvement, and suggest plans for future work.","useSubjectClassification":true,"description":"Drafts conclusions for papers (or files) in their existing style","outputKind":"detail","useSoundClassification":true,"acceptedFileExtensions":"","useMetadata":false,"useAudioDetails":true,"showResponse":true}',
  "Historical Context":
    '{"useAudioDetails":true,"acceptedFileExtensions":"","description":"Discusses the historical significance of the selected files and their subject matter","iconColor":"raycast-primary-text","icon":"rewind-16","useMetadata":false,"prompt":"Based on the topics mentioned in the following files, provide a list of the top 5 most significant relevant historical facts. Ensure all facts are truthful. Do not make up anything. Additionally, provide a paragraph discussing a historical fact that relates to the entire content of the file.","name":"Historical Context","actionScript":"","useSubjectClassification":true,"outputKind":"detail","useSoundClassification":true,"showResponse":true,"useRectangleDetection":false,"useBarcodeDetection":true,"useFaceDetection":false,"minNumFiles":"1"}',
  "Create Flashcards":
    '{"useMetadata":false,"useFaceDetection":false,"minNumFiles":"1","iconColor":"raycast-red","outputKind":"detail","prompt":"Create 3 Anki flashcards based on the content of the following files. Format the response as markdown with the bold questions and plaintext answers. Separate each entry with \'---\'.","actionScript":"","showResponse":true,"useSubjectClassification":true,"acceptedFileExtensions":"","description":"Provides 3 Anki flashcards related to the selected files","useRectangleDetection":false,"useAudioDetails":true,"icon":"blank-document-16","useBarcodeDetection":true,"useSoundClassification":true,"name":"Create Flashcards"}',
  "Extract Code":
    '{"showResponse":true,"useAudioDetails":false,"useRectangleDetection":false,"useBarcodeDetection":false,"minNumFiles":"1","acceptedFileExtensions":"","useMetadata":false,"useSubjectClassification":false,"prompt":"Extract lines of code written in programming languages from the following files. Format the response as markdown code blocks. Place the programming language used in each block as the heading above it. Provide a brief description of what the code does below each block. Do not provide any other commentary.","useFaceDetection":false,"icon":"code-16","name":"Extract Code","actionScript":"","description":"","useSoundClassification":false,"iconColor":"raycast-purple","outputKind":"detail"}',
  "Suggest Related Prompts":
    '{"showResponse":true,"outputKind":"detail","useFaceDetection":false,"acceptedFileExtensions":"","iconColor":"raycast-magenta","useSubjectClassification":true,"useMetadata":false,"description":"Lists 5 possible PromptLab prompts related to the selected files","name":"Suggest Related Prompts","icon":"paragraph-16","minNumFiles":"1","actionScript":"","useRectangleDetection":false,"useSoundClassification":true,"prompt":"Suggest a list of 5 prompts for an AI that can read the content of selected files. The AI can\'t modify or create files. Give prompts based on the topic and structure of the following files. Don\'t refer to the AI. Prompts must be more than retrieving contents. Each prompt must be different. Each prompt must operate on selected files. Don\'t use the file names in the prompts. Give a paragraph identifying key relationships between your prompts and the topics of the provided files.","useAudioDetails":true,"useBarcodeDetection":true}',
  "Summarize Current Tab":
    '{"acceptedFileExtensions":"","useRectangleDetection":false,"useBarcodeDetection":false,"useSoundClassification":false,"outputKind":"detail","showResponse":true,"iconColor":"raycast-orange","actionScript":"","name":"Summarize Current Tab","useFaceDetection":false,"prompt":"Based on the following text obtained from the active browser tab, what am I looking at? In your answer, discuss the content and meaning of the website. If the URL or the text are blank, report an error. For context, here is the url: {{currentURL}}:\\n\\nAnd here is the text:\\n###\\n{{currentTabText}}\\n###","minNumFiles":"0","useAudioDetails":false,"description":"","useSubjectClassification":false,"icon":"app-window-16","useMetadata":false}',
  "Assess File Overlap":
    '{"showResponse":true,"outputKind":"detail","useFaceDetection":false,"acceptedFileExtensions":"","iconColor":"raycast-primary-text","name":"Assess File Overlap","useSubjectClassification":true,"useMetadata":false,"description":"Identifies similarities in content among selected files","icon":"contrast-16","minNumFiles":"2","actionScript":"","useRectangleDetection":false,"useSoundClassification":true,"prompt":"What overlaps in content or ideas exists between the following files? What are the similarities?","useAudioDetails":true,"useBarcodeDetection":true}',
  "Location Significance":
    '{"description":"Provides an overview of the history of your current location","prompt":"What is the significance and history of {{location}}? Format your response as a friendly paragraph.","useMetadata":false,"actionScript":"","outputKind":"detail","useRectangleDetection":false,"icon":"geopin-16","iconColor":"raycast-blue","showResponse":true,"acceptedFileExtensions":"","name":"Location Significance","useSoundClassification":false,"useAudioDetails":false,"useBarcodeDetection":false,"useFaceDetection":false,"useSubjectClassification":false,"minNumFiles":"0"}',
  "Suggest Project Ideas":
    '{"iconColor":"raycast-magenta","acceptedFileExtensions":"","useSoundClassification":true,"useAudioDetails":true,"minNumFiles":"1","prompt":"I want you to act as a project idea generator. I will provide file names and their contents, and you will response with a list of project ideas based on the content of each file. Format the response as a markdown list. Use the file names as headings. Here are the files:","useFaceDetection":true,"useSubjectClassification":true,"useRectangleDetection":false,"useMetadata":false,"useBarcodeDetection":true,"description":"Lists ideas for projects based on the selected files","icon":"hammer-16","actionScript":"","showResponse":true,"name":"Suggest Project Ideas","outputKind":"detail"}',
  "Write Discussion":
    '{"actionScript":"","useBarcodeDetection":true,"acceptedFileExtensions":"","useSoundClassification":true,"useAudioDetails":true,"name":"Write Discussion","useSubjectClassification":true,"description":"Drafts discussion sections for papers (or files) in their existing style","outputKind":"detail","icon":"text-cursor-16","showResponse":true,"prompt":"Write a new discussion section for each of the following files in the style of an academic research paper. The discussion should be past tense and highlight the paper\'s successes. Use the file names as headings.","useMetadata":false,"useRectangleDetection":false,"useFaceDetection":false,"iconColor":"raycast-yellow","minNumFiles":"1"}',
  "Weather Forecast":
    '{"useFaceDetection":false,"name":"Weather Forecast","useMetadata":false,"showResponse":true,"useSubjectClassification":false,"outputKind":"detail","prompt":"Provide a weather report based on the following forecast data for the next 7 days in {{location}}: ###{{weather}}###\\n\\nDiscuss how this might affect my events over the next week. Consider the purpose and type of each event. My events are: ###{{weekEvents}}###","icon":"cloud-sun-16","useSoundClassification":false,"useRectangleDetection":false,"description":"Summarizes the forecast for the next 7 days and discusses any impacts on scheduled calendar events","acceptedFileExtensions":"","actionScript":"","minNumFiles":"0","useBarcodeDetection":false,"useAudioDetails":false,"iconColor":"raycast-blue"}',
  "Condense File":
    '{"showResponse":true,"outputKind":"detail","useFaceDetection":false,"acceptedFileExtensions":"","useSubjectClassification":false,"name":"Condense File","iconColor":"raycast-yellow","useMetadata":false,"description":"Gets text for a greatly shortened form of each selected file","icon":"arrows-contract-16","minNumFiles":"1","actionScript":"","useRectangleDetection":false,"useSoundClassification":false,"prompt":"Condense the content of the following files as much as possible. Summarize sentences. Use abbreviations where possible. If the response includes any lists, remove them and briefly describe them instead. Condense clarifying language as much as possible. Use the file names as headings.","useAudioDetails":true,"useBarcodeDetection":false}',
  "Summarize Last Email":
    '{"outputKind":"detail","useSoundClassification":false,"name":"Summarize Last Email","useBarcodeDetection":false,"useRectangleDetection":false,"useFaceDetection":false,"description":"","showResponse":true,"prompt":"Summarize my most recent email and discuss its significance. I am the recipient. Format the response as a paragraph directed to me. Here is the email:\\n###\\n{{lastEmail}}\\n###","acceptedFileExtensions":"","iconColor":"raycast-orange","minNumFiles":"0","icon":"envelope-16","useMetadata":false,"useSubjectClassification":false,"actionScript":"","useAudioDetails":false}',
  "Split Into Text Files":
    '{"useRectangleDetection":false,"showResponse":true,"name":"Split Into Text Files","useSubjectClassification":false,"description":"Splits the contents of files into sections and creates a text file for each section in the current directory","iconColor":"raycast-green","minNumFiles":"1","useSoundClassification":false,"outputKind":"detail","useFaceDetection":false,"useMetadata":false,"acceptedFileExtensions":"","actionScript":"set parts to split(response, \\"$$$$$\\")\\n\\ntell application \\"Finder\\"\\n\\tset currentDir to POSIX path of (insertion location as alias)\\nend tell\\n\\nrepeat with i from 1 to length of parts\\n    set theFile to open for access currentDir & (word 1 of item i of parts) & i & \\".txt\\" with write permission\\n    write item i of parts to theFile\\n    close access theFile\\nend repeat","prompt":"Split the content of the following file into multiple logical sections. Do not put headings in their own section. Output the text of each section. Write \\"$$$$$\\" between each section.","icon":"new-document-16","useAudioDetails":false,"useBarcodeDetection":false}',
  "Write Abstract":
    '{"useBarcodeDetection":true,"useMetadata":false,"icon":"text-cursor-16","useRectangleDetection":false,"useAudioDetails":true,"minNumFiles":"1","description":"Drafts abtracts for papers (or files) in their existing style","outputKind":"detail","useSoundClassification":true,"iconColor":"raycast-yellow","useFaceDetection":false,"useSubjectClassification":true,"actionScript":"","showResponse":true,"name":"Write Abstract","prompt":"Write an abstract for the following files in the style of an academic research paper. Use the file names as headings. If the abstract includes a list, briefly describe it instead of listing all elements.","acceptedFileExtensions":""}',
  "Suggest Title":
    '{"iconColor":"raycast-magenta","useSubjectClassification":true,"acceptedFileExtensions":"","useSoundClassification":true,"useAudioDetails":true,"description":"Provides possible titles for each selected file","useRectangleDetection":false,"outputKind":"detail","icon":"text-16","actionScript":"","prompt":"Suggest new titles for the following files based on their content and topics mentioned. Use the file names as headings.","useBarcodeDetection":true,"useFaceDetection":false,"showResponse":true,"minNumFiles":"1","name":"Suggest Title","useMetadata":false}',
  "Table Of Contents":
    '{"useRectangleDetection":false,"useFaceDetection":false,"useBarcodeDetection":true,"minNumFiles":"1","outputKind":"detail","icon":"bullet-points-16","showResponse":true,"name":"Table Of Contents","prompt":"Generate a table of contents for each of the following files based on their content. Use the file names as headings. For each item in the table, provide an percent estimation of how far into the document the associated content occurs. Format the tables as markdown tables.","useMetadata":false,"acceptedFileExtensions":"","actionScript":"","useSubjectClassification":true,"description":"Generates a markdown table of contents for the selected files","iconColor":"raycast-red","useAudioDetails":true,"useSoundClassification":true}',
  "What Is This?":
    '{"showResponse":true,"useBarcodeDetection":true,"actionScript":"","useAudioDetails":true,"minNumFiles":"1","icon":"question-mark-circle-16","useMetadata":true,"useSubjectClassification":true,"prompt":"Based on the content of the following files, answer this question: What is this? Use the file names as headings.","useRectangleDetection":true,"useSoundClassification":true,"acceptedFileExtensions":"","outputKind":"detail","useFaceDetection":true,"description":"Explain what the selected files are and are for","iconColor":"raycast-primary-text","name":"What Is This?"}',
  "Create Meeting Agenda":
    '{"useFaceDetection":false,"useRectangleDetection":false,"useAudioDetails":true,"acceptedFileExtensions":"","description":"Generates a meeting agenda based on the contents of selected files","prompt":"Create a meeting agenda covering the contents of the following files. Use today\'s date and time, {{date}}, to provide headings and structure to the agenda.","useSoundClassification":false,"iconColor":"raycast-red","name":"Create Meeting Agenda","minNumFiles":"1","useBarcodeDetection":false,"showResponse":true,"icon":"app-window-list-16","useSubjectClassification":false,"useMetadata":false,"outputKind":"detail","actionScript":""}',
  "Make Poem":
    '{"useFaceDetection":true,"useMetadata":false,"name":"Make Poem","showResponse":true,"useSubjectClassification":true,"outputKind":"detail","prompt":"Make rhyming poems about the the following files. Be creative and include references to the content and purpose of the file in unexpected ways. Do not summarize the file. Make each poem at least 3 stanzas long, but longer for longer files. Use the file names as markdown headings.","icon":"short-paragraph-16","useSoundClassification":true,"useRectangleDetection":false,"description":"Generates a poem based on the selected files","acceptedFileExtensions":"","actionScript":"","minNumFiles":"1","useBarcodeDetection":true,"useAudioDetails":true,"iconColor":"raycast-red"}',
  "Suggest Tools":
    '{"showResponse":true,"useBarcodeDetection":true,"actionScript":"","useAudioDetails":true,"minNumFiles":"1","icon":"wrench-screwdriver-16","useMetadata":true,"useSubjectClassification":true,"prompt":"Suggest tools to use based on the topics discussed in the following files. Explain why each tool is relevant. Use the file names as headings. Do not provide any commentary other than the list of tools and their explanations.","useRectangleDetection":false,"useSoundClassification":true,"outputKind":"detail","acceptedFileExtensions":"","useFaceDetection":false,"description":"Lists and describes various tools relevant to the selected files","iconColor":"raycast-magenta","name":"Suggest Tools"}',
  "Make Song":
    '{"useSoundClassification":true,"icon":"music-16","showResponse":true,"prompt":"Make a song based on the content of the following files. Provide a name for the song.","useAudioDetails":true,"name":"Make Song","description":"Generates a song based on the selected files","actionScript":"","acceptedFileExtensions":"","useBarcodeDetection":true,"useSubjectClassification":true,"outputKind":"detail","useRectangleDetection":false,"minNumFiles":"1","useFaceDetection":true,"useMetadata":false,"iconColor":"raycast-red"}',
  "Extract Email Addresses":
    '{"useFaceDetection":false,"useRectangleDetection":false,"useAudioDetails":false,"acceptedFileExtensions":"","description":"","prompt":"Extract email addresses from the following files and list them as markdown links:","useSoundClassification":false,"iconColor":"raycast-purple","name":"Extract Email Addresses","minNumFiles":"1","useBarcodeDetection":false,"showResponse":true,"icon":"envelope-16","useSubjectClassification":false,"actionScript":"","outputKind":"detail","useMetadata":false}',
  "Performance Summary":
    '{"name":"Performance Summary","useBarcodeDetection":false,"useSubjectClassification":false,"actionScript":"","iconColor":"raycast-blue","useRectangleDetection":false,"useAudioDetails":false,"icon":"computer-chip-16","prompt":"Give me an analysis of my CPU and RAM usage. Output two friendly paragraphs along with two markdown tables. Use this data to guide your response: ###{{shell:top -stats command,cpu,rsize -n 10 -l 2 -s 1 -e | tail -20 | grep -iE \'(PhysMem|CPU Usage)\'}}###","acceptedFileExtensions":"","outputKind":"detail","useMetadata":false,"minNumFiles":"0","showResponse":true,"description":"Provides an overview of your current CPU and RAM usage","useFaceDetection":false,"useSoundClassification":false}',
};
