/**
 * Shared runtime for every generated Raycast AI tool. Each wrapper in
 * `src/tools/` (all auto-generated by scripts/generate-tools.ts) builds a
 * config object and forwards here — no per-tool handler logic lives in
 * the repo.
 *
 * Responsibilities:
 *   1. Resolve the active SaaSFlow company when the path template
 *      contains `{companyId}` and the caller didn't pass one.
 *   2. Interpolate path params, attach query params, and pass through
 *      the body.
 *   3. Call the typed openapi-fetch client (cast to a loose shape so
 *      arbitrary paths work — the generator is the source of truth for
 *      which paths are reached, not TypeScript).
 *   4. Return the response payload as `Record<string, unknown>` so the
 *      LLM can read whatever shape the API returns.
 */
import { getClient } from "./client.js";
import { resolveCompany } from "./companyContext.js";

export type RunEndpointConfig = {
    method: "GET" | "POST";
    /** OpenAPI path template, e.g. `/companies/{companyId}/transactions/{transactionId}`. */
    pathTemplate: string;
    /**
     * Caller-supplied path params (excluding `companyId`, which is resolved
     * automatically when the template contains it).
     */
    pathParams?: Record<string, string>;
    /** Caller-supplied company id; falls back to the active company. */
    companyId?: string;
    query?: Record<string, unknown>;
    body?: Record<string, unknown>;
};

export async function runEndpoint(config: RunEndpointConfig): Promise<Record<string, unknown>> {
    const needsCompany = config.pathTemplate.includes("{companyId}");
    const path: Record<string, string> = { ...config.pathParams };

    if (needsCompany) {
        const resolved = await resolveCompany(config.companyId);
        if (!resolved) {
            throw new Error("No company found for the signed-in user.");
        }
        path.companyId = resolved.id;
    }

    const client = await getClient();
    const loose = client as unknown as {
        GET: (
            p: string,
            init: { params?: { path?: Record<string, string>; query?: Record<string, unknown> } },
        ) => Promise<{ data: unknown }>;
        POST: (
            p: string,
            init: {
                params?: { path?: Record<string, string>; query?: Record<string, unknown> };
                body?: unknown;
            },
        ) => Promise<{ data: unknown }>;
    };

    const init: {
        params?: { path?: Record<string, string>; query?: Record<string, unknown> };
        body?: unknown;
    } = {};
    if (Object.keys(path).length > 0 || config.query) {
        init.params = {};
        if (Object.keys(path).length > 0) init.params.path = path;
        if (config.query) init.params.query = pruneUndefined(config.query);
    }
    if (config.body !== undefined) init.body = pruneUndefined(config.body);

    const { data } =
        config.method === "GET"
            ? await loose.GET(config.pathTemplate, init)
            : await loose.POST(config.pathTemplate, init);

    if (Array.isArray(data)) {
        // The LLM expects a JSON object back; wrap raw arrays under a
        // generic key so callers can iterate `.items`.
        return { items: data } as Record<string, unknown>;
    }
    return (data ?? {}) as Record<string, unknown>;
}

function pruneUndefined<T extends Record<string, unknown>>(obj: T): T {
    const out = {} as Record<string, unknown>;
    for (const [k, v] of Object.entries(obj)) {
        if (v !== undefined) out[k] = v;
    }
    return out as T;
}
