"use strict";var I=Object.create;var c=Object.defineProperty;var O=Object.getOwnPropertyDescriptor;var M=Object.getOwnPropertyNames;var F=Object.getPrototypeOf,H=Object.prototype.hasOwnProperty;var z=(e,t)=>{for(var a in t)c(e,a,{get:t[a],enumerable:!0})},v=(e,t,a,d)=>{if(t&&typeof t=="object"||typeof t=="function")for(let n of M(t))!H.call(e,n)&&n!==a&&c(e,n,{get:()=>t[n],enumerable:!(d=O(t,n))||d.enumerable});return e};var D=(e,t,a)=>(a=e!=null?I(F(e)):{},v(t||!e||!e.__esModule?c(a,"default",{value:e,enumerable:!0}):a,e)),N=e=>v(c({},"__esModule",{value:!0}),e);var K={};z(K,{default:()=>R});module.exports=N(K);var o=require("@raycast/api"),f=require("react");var l=require("@raycast/api"),w="dicelab:aliases",A="dicelab:history",Y=100;async function h(){let e=await l.LocalStorage.getItem(w);if(!e)return{};try{return JSON.parse(e)}catch{return{}}}async function x(e){await l.LocalStorage.setItem(w,JSON.stringify(e))}async function J(){let e=await l.LocalStorage.getItem(A);if(!e)return[];try{return JSON.parse(e)}catch{return[]}}async function E(e){let t=await J(),a=[e,...t].slice(0,Y);await l.LocalStorage.setItem(A,JSON.stringify(a))}var k=require("@raycast/api"),S=D(require("path")),m=null,g=null;async function b(){return m||(g||(g=(async()=>{let e=S.default.join(k.environment.assetsPath,"wasm","dicebook.js");try{return require(e)}catch(t){throw console.error("Failed to load WASM module:",t),new Error(`Failed to load Dicelab engine: ${t instanceof Error?t.message:String(t)}`)}})()),m=await g,m)}var P="raycast-dicelab";var s=null,y=null;async function T(){return s||(y||(y=(async()=>{let e=await b(),t=new e.WasmEngine(P),a=await h();return Object.keys(a).length>0&&t.setAliases(a),t})()),s=await y,s)}async function C(){if(!s)return;let e=s.getAliases();await x(e)}var i=require("react/jsx-runtime");function R(){let[e,t]=(0,f.useState)(""),[a,d]=(0,f.useState)([]),{push:n}=(0,o.useNavigation)();async function W(){if(e.trim())try{let p=(await T()).evaluate(e),r;typeof p=="string"?r=p:r=p.result,d([...a,{expression:e,result:r}]),await E({expression:e,result:r,timestamp:Date.now()}),e.trim().toLowerCase().startsWith("let ")&&await C(),t("");let _=`# Result

\`\`\`
${r}
\`\`\`

## Expression
\`${e}\``;n((0,i.jsx)(o.Detail,{markdown:_}))}catch(u){await(0,o.showToast)({style:o.Toast.Style.Failure,title:"Evaluation Failed",message:u instanceof Error?u.message:"Unknown error"})}}return(0,i.jsxs)(o.Form,{actions:(0,i.jsx)(o.ActionPanel,{children:(0,i.jsx)(o.Action.SubmitForm,{title:"Evaluate",onSubmit:W})}),children:[(0,i.jsx)(o.Form.TextField,{id:"expression",title:"Expression",placeholder:"d20, 2d6+4, let str = 18, analyze d20adv+5",value:e,onChange:t}),(0,i.jsx)(o.Form.Description,{text:`Enter a dice expression, variable assignment, or analyze command.

Previous results: ${a.length}`})]})}
