import fs from "fs/promises";
import { Rule } from "../types";

function ruleToHandler(rule: Rule): string {
  const browser = JSON.stringify(rule.browser);

  if (rule.matchType === "regex") {
    const sources = rule.patterns.map((p) => p.trim()).filter(Boolean);

    if (sources.length === 0) return "";

    const combined = sources.length === 1 ? sources[0] : `(?:${sources.join(")|(?:")})`;

    return `{
    match: ({ urlString }) => new RegExp(${JSON.stringify(combined)}, "i").test(urlString),
    browser: ${browser}
}`;
  }

  const patterns = rule.patterns
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => JSON.stringify(p))
    .join(",\n            ");

  if (!patterns) return "";

  return `{
    match: [
            ${patterns}
    ],
    browser: ${browser}
}`;
}

export function generateFinickyConfig(params: { defaultBrowser: string; rules: Rule[] }): string {
  const enabledRules = params.rules.filter((r) => r.enabled);

  const handlers = enabledRules
    .map((r) => {
      const handler = ruleToHandler(r);
      if (!handler) return "";
      return `// Rule: ${r.name}\n${handler}`;
    })
    .filter(Boolean)
    .join(",\n\n        ");

  return `// Generated by Raycast: Finicky Rules Manager
// Do not edit by hand (your changes may be overwritten).

export default {
    defaultBrowser: ${JSON.stringify(params.defaultBrowser)},

    handlers: [
        ${handlers}
    ]
};
`;
}

export async function writeConfigFile(args: { configPath: string; configContents: string }) {
  await fs.writeFile(args.configPath, args.configContents, { encoding: "utf8" });
}
