// stockData.ts
export const stockList = [
  { id: "1", query: "AAPL", description: "Apple Inc.", url: "https://stocks.apple.com/symbol/AAPL" },
  { id: "2", query: "MSFT", description: "Microsoft Corporation", url: "https://stocks.apple.com/symbol/MSFT" },
  { id: "3", query: "AMZN", description: "Amazon.com Inc.", url: "https://stocks.apple.com/symbol/AMZN" },
  { id: "4", query: "GOOGL", description: "Alphabet Inc. Class A", url: "https://stocks.apple.com/symbol/GOOGL" },
  { id: "5", query: "GOOG", description: "Alphabet Inc. Class C", url: "https://stocks.apple.com/symbol/GOOG" },
  { id: "6", query: "FB", description: "Meta Platforms Inc.", url: "https://stocks.apple.com/symbol/FB" },
  { id: "7", query: "TSLA", description: "Tesla Inc.", url: "https://stocks.apple.com/symbol/TSLA" },
  {
    id: "8",
    query: "BRK.B",
    description: "Berkshire Hathaway Inc. Class B",
    url: "https://stocks.apple.com/symbol/BRK-B",
  },
  { id: "9", query: "NVDA", description: "NVIDIA Corporation", url: "https://stocks.apple.com/symbol/NVDA" },
  { id: "10", query: "JPM", description: "JPMorgan Chase & Co.", url: "https://stocks.apple.com/symbol/JPM" },
  { id: "11", query: "JNJ", description: "Johnson & Johnson", url: "https://stocks.apple.com/symbol/JNJ" },
  {
    id: "12",
    query: "UNH",
    description: "UnitedHealth Group Incorporated",
    url: "https://stocks.apple.com/symbol/UNH",
  },
  { id: "13", query: "HD", description: "The Home Depot Inc.", url: "https://stocks.apple.com/symbol/HD" },
  { id: "14", query: "PG", description: "The Procter & Gamble Company", url: "https://stocks.apple.com/symbol/PG" },
  { id: "15", query: "BAC", description: "Bank of America Corporation", url: "https://stocks.apple.com/symbol/BAC" },
  { id: "16", query: "ADBE", description: "Adobe Inc.", url: "https://stocks.apple.com/symbol/ADBE" },
  { id: "17", query: "MA", description: "Mastercard Incorporated", url: "https://stocks.apple.com/symbol/MA" },
  { id: "18", query: "CMCSA", description: "Comcast Corporation", url: "https://stocks.apple.com/symbol/CMCSA" },
  { id: "19", query: "XOM", description: "Exxon Mobil Corporation", url: "https://stocks.apple.com/symbol/XOM" },
  { id: "20", query: "NFLX", description: "Netflix Inc.", url: "https://stocks.apple.com/symbol/NFLX" },
  { id: "21", query: "VZ", description: "Verizon Communications Inc.", url: "https://stocks.apple.com/symbol/VZ" },
  { id: "22", query: "DIS", description: "The Walt Disney Company", url: "https://stocks.apple.com/symbol/DIS" },
  { id: "23", query: "CSCO", description: "Cisco Systems Inc.", url: "https://stocks.apple.com/symbol/CSCO" },
  { id: "24", query: "PFE", description: "Pfizer Inc.", url: "https://stocks.apple.com/symbol/PFE" },
  { id: "25", query: "INTC", description: "Intel Corporation", url: "https://stocks.apple.com/symbol/INTC" },
  { id: "26", query: "ABT", description: "Abbott Laboratories", url: "https://stocks.apple.com/symbol/ABT" },
  { id: "27", query: "PEP", description: "PepsiCo Inc.", url: "https://stocks.apple.com/symbol/PEP" },
  { id: "28", query: "COST", description: "Costco Wholesale Corporation", url: "https://stocks.apple.com/symbol/COST" },
  { id: "29", query: "CVX", description: "Chevron Corporation", url: "https://stocks.apple.com/symbol/CVX" },
  { id: "30", query: "WMT", description: "Walmart Inc.", url: "https://stocks.apple.com/symbol/WMT" },
  { id: "31", query: "MRK", description: "Merck & Co. Inc.", url: "https://stocks.apple.com/symbol/MRK" },
  { id: "32", query: "TMO", description: "Thermo Fisher Scientific Inc.", url: "https://stocks.apple.com/symbol/TMO" },
  { id: "33", query: "ABBV", description: "AbbVie Inc.", url: "https://stocks.apple.com/symbol/ABBV" },
  { id: "34", query: "AVGO", description: "Broadcom Inc.", url: "https://stocks.apple.com/symbol/AVGO" },
  { id: "35", query: "ACN", description: "Accenture plc", url: "https://stocks.apple.com/symbol/ACN" },
  { id: "36", query: "PYPL", description: "PayPal Holdings Inc.", url: "https://stocks.apple.com/symbol/PYPL" },
  { id: "37", query: "DHR", description: "Danaher Corporation", url: "https://stocks.apple.com/symbol/DHR" },
  { id: "38", query: "MCD", description: "McDonald's Corporation", url: "https://stocks.apple.com/symbol/MCD" },
  { id: "39", query: "TXN", description: "Texas Instruments Incorporated", url: "https://stocks.apple.com/symbol/TXN" },
  { id: "40", query: "NKE", description: "NIKE Inc.", url: "https://stocks.apple.com/symbol/NKE" },
  { id: "41", query: "UNP", description: "Union Pacific Corporation", url: "https://stocks.apple.com/symbol/UNP" },
  { id: "42", query: "QCOM", description: "QUALCOMM Incorporated", url: "https://stocks.apple.com/symbol/QCOM" },
  { id: "43", query: "LLY", description: "Eli Lilly and Company", url: "https://stocks.apple.com/symbol/LLY" },
  { id: "44", query: "NEE", description: "NextEra Energy Inc.", url: "https://stocks.apple.com/symbol/NEE" },
  { id: "45", query: "AMD", description: "Advanced Micro Devices Inc.", url: "https://stocks.apple.com/symbol/AMD" },
  { id: "46", query: "AMGN", description: "Amgen Inc.", url: "https://stocks.apple.com/symbol/AMGN" },
  { id: "47", query: "HON", description: "Honeywell International Inc.", url: "https://stocks.apple.com/symbol/HON" },
  { id: "48", query: "CRM", description: "Salesforce.com Inc.", url: "https://stocks.apple.com/symbol/CRM" },
  { id: "49", query: "LOW", description: "Lowe's Companies Inc.", url: "https://stocks.apple.com/symbol/LOW" },
  { id: "50", query: "SBUX", description: "Starbucks Corporation", url: "https://stocks.apple.com/symbol/SBUX" },
  { id: "51", query: "BMY", description: "Bristol-Myers Squibb Company", url: "https://stocks.apple.com/symbol/BMY" },
  { id: "52", query: "UPS", description: "United Parcel Service Inc.", url: "https://stocks.apple.com/symbol/UPS" },
  { id: "53", query: "ORCL", description: "Oracle Corporation", url: "https://stocks.apple.com/symbol/ORCL" },
  { id: "54", query: "T", description: "AT&T Inc.", url: "https://stocks.apple.com/symbol/T" },
  { id: "55", query: "CAT", description: "Caterpillar Inc.", url: "https://stocks.apple.com/symbol/CAT" },
  { id: "56", query: "LIN", description: "Linde plc", url: "https://stocks.apple.com/symbol/LIN" },
  { id: "57", query: "CHTR", description: "Charter Communications Inc.", url: "https://stocks.apple.com/symbol/CHTR" },
  { id: "58", query: "INTU", description: "Intuit Inc.", url: "https://stocks.apple.com/symbol/INTU" },
  { id: "59", query: "ISRG", description: "Intuitive Surgical Inc.", url: "https://stocks.apple.com/symbol/ISRG" },
  { id: "60", query: "CVS", description: "CVS Health Corporation", url: "https://stocks.apple.com/symbol/CVS" },
  { id: "61", query: "DE", description: "Deere & Company", url: "https://stocks.apple.com/symbol/DE" },
  { id: "62", query: "MDLZ", description: "Mondelez International Inc.", url: "https://stocks.apple.com/symbol/MDLZ" },
  {
    id: "63",
    query: "SCHW",
    description: "The Charles Schwab Corporation",
    url: "https://stocks.apple.com/symbol/SCHW",
  },
  { id: "64", query: "GS", description: "The Goldman Sachs Group Inc.", url: "https://stocks.apple.com/symbol/GS" },
  { id: "65", query: "AXP", description: "American Express Company", url: "https://stocks.apple.com/symbol/AXP" },
  { id: "66", query: "BLK", description: "BlackRock Inc.", url: "https://stocks.apple.com/symbol/BLK" },
  { id: "67", query: "BKNG", description: "Booking Holdings Inc.", url: "https://stocks.apple.com/symbol/BKNG" },
  { id: "68", query: "ADI", description: "Analog Devices Inc.", url: "https://stocks.apple.com/symbol/ADI" },
  { id: "69", query: "MMM", description: "3M Company", url: "https://stocks.apple.com/symbol/MMM" },
  { id: "70", query: "GILD", description: "Gilead Sciences Inc.", url: "https://stocks.apple.com/symbol/GILD" },
  { id: "71", query: "TGT", description: "Target Corporation", url: "https://stocks.apple.com/symbol/TGT" },
  { id: "72", query: "SPGI", description: "S&P Global Inc.", url: "https://stocks.apple.com/symbol/SPGI" },
  { id: "73", query: "ZTS", description: "Zoetis Inc.", url: "https://stocks.apple.com/symbol/ZTS" },
  { id: "74", query: "ANTM", description: "Anthem Inc.", url: "https://stocks.apple.com/symbol/ANTM" },
  { id: "75", query: "AMAT", description: "Applied Materials Inc.", url: "https://stocks.apple.com/symbol/AMAT" },
  { id: "76", query: "CI", description: "Cigna Corporation", url: "https://stocks.apple.com/symbol/CI" },
  { id: "77", query: "C", description: "Citigroup Inc.", url: "https://stocks.apple.com/symbol/C" },
  {
    id: "78",
    query: "FIS",
    description: "Fidelity National Information Services Inc.",
    url: "https://stocks.apple.com/symbol/FIS",
  },
  { id: "79", query: "ATVI", description: "Activision Blizzard Inc.", url: "https://stocks.apple.com/symbol/ATVI" },
  { id: "80", query: "SYK", description: "Stryker Corporation", url: "https://stocks.apple.com/symbol/SYK" },
  { id: "81", query: "PLD", description: "Prologis Inc.", url: "https://stocks.apple.com/symbol/PLD" },
  { id: "82", query: "LRCX", description: "Lam Research Corporation", url: "https://stocks.apple.com/symbol/LRCX" },
  { id: "83", query: "MS", description: "Morgan Stanley", url: "https://stocks.apple.com/symbol/MS" },
  { id: "84", query: "BA", description: "The Boeing Company", url: "https://stocks.apple.com/symbol/BA" },
  { id: "85", query: "NOW", description: "ServiceNow Inc.", url: "https://stocks.apple.com/symbol/NOW" },
  { id: "86", query: "GE", description: "General Electric Company", url: "https://stocks.apple.com/symbol/GE" },
  { id: "87", query: "DUK", description: "Duke Energy Corporation", url: "https://stocks.apple.com/symbol/DUK" },
  {
    id: "88",
    query: "RTX",
    description: "Raytheon Technologies Corporation",
    url: "https://stocks.apple.com/symbol/RTX",
  },
  { id: "89", query: "BDX", description: "Becton Dickinson and Company", url: "https://stocks.apple.com/symbol/BDX" },
  { id: "90", query: "ILMN", description: "Illumina Inc.", url: "https://stocks.apple.com/symbol/ILMN" },
  { id: "91", query: "TJX", description: "The TJX Companies Inc.", url: "https://stocks.apple.com/symbol/TJX" },
  {
    id: "92",
    query: "MMC",
    description: "Marsh & McLennan Companies Inc.",
    url: "https://stocks.apple.com/symbol/MMC",
  },
  {
    id: "93",
    query: "PNC",
    description: "The PNC Financial Services Group Inc.",
    url: "https://stocks.apple.com/symbol/PNC",
  },
  { id: "94", query: "CSX", description: "CSX Corporation", url: "https://stocks.apple.com/symbol/CSX" },
  {
    id: "95",
    query: "CCI",
    description: "Crown Castle International Corp.",
    url: "https://stocks.apple.com/symbol/CCI",
  },
  { id: "96", query: "ADSK", description: "Autodesk Inc.", url: "https://stocks.apple.com/symbol/ADSK" },
  { id: "97", query: "EL", description: "The Estée Lauder Companies Inc.", url: "https://stocks.apple.com/symbol/EL" },
  { id: "98", query: "USB", description: "U.S. Bancorp", url: "https://stocks.apple.com/symbol/USB" },
  { id: "99", query: "CL", description: "Colgate-Palmolive Company", url: "https://stocks.apple.com/symbol/CL" },
  { id: "100", query: "CME", description: "CME Group Inc.", url: "https://stocks.apple.com/symbol/CME" },
  { id: "101", query: "EOG", description: "EOG Resources, Inc.", url: "https://stocks.apple.com/symbol/EOG" },
  {
    id: "102",
    query: "ICE",
    description: "Intercontinental Exchange, Inc.",
    url: "https://stocks.apple.com/symbol/ICE",
  },
  {
    id: "103",
    query: "REGN",
    description: "Regeneron Pharmaceuticals, Inc.",
    url: "https://stocks.apple.com/symbol/REGN",
  },
  { id: "104", query: "SO", description: "The Southern Company", url: "https://stocks.apple.com/symbol/SO" },
  { id: "105", query: "NSC", description: "Norfolk Southern Corporation", url: "https://stocks.apple.com/symbol/NSC" },
  {
    id: "106",
    query: "VRTX",
    description: "Vertex Pharmaceuticals Incorporated",
    url: "https://stocks.apple.com/symbol/VRTX",
  },
  { id: "107", query: "EQIX", description: "Equinix, Inc.", url: "https://stocks.apple.com/symbol/EQIX" },
  { id: "108", query: "FISV", description: "Fiserv, Inc.", url: "https://stocks.apple.com/symbol/FISV" },
  { id: "109", query: "HUM", description: "Humana Inc.", url: "https://stocks.apple.com/symbol/HUM" },
  { id: "110", query: "ITW", description: "Illinois Tool Works Inc.", url: "https://stocks.apple.com/symbol/ITW" },
  { id: "111", query: "KLAC", description: "KLA Corporation", url: "https://stocks.apple.com/symbol/KLAC" },
  {
    id: "112",
    query: "APD",
    description: "Air Products and Chemicals, Inc.",
    url: "https://stocks.apple.com/symbol/APD",
  },
  { id: "113", query: "TMUS", description: "T-Mobile US, Inc.", url: "https://stocks.apple.com/symbol/TMUS" },
  { id: "114", query: "GM", description: "General Motors Company", url: "https://stocks.apple.com/symbol/GM" },
  { id: "115", query: "SHW", description: "The Sherwin-Williams Company", url: "https://stocks.apple.com/symbol/SHW" },
  {
    id: "116",
    query: "ADP",
    description: "Automatic Data Processing, Inc.",
    url: "https://stocks.apple.com/symbol/ADP",
  },
  { id: "117", query: "MRNA", description: "Moderna, Inc.", url: "https://stocks.apple.com/symbol/MRNA" },
  { id: "118", query: "F", description: "Ford Motor Company", url: "https://stocks.apple.com/symbol/F" },
  { id: "119", query: "IDXX", description: "IDEXX Laboratories, Inc.", url: "https://stocks.apple.com/symbol/IDXX" },
  {
    id: "120",
    query: "EW",
    description: "Edwards Lifesciences Corporation",
    url: "https://stocks.apple.com/symbol/EW",
  },
  { id: "121", query: "MCO", description: "Moody's Corporation", url: "https://stocks.apple.com/symbol/MCO" },
  { id: "122", query: "NXPI", description: "NXP Semiconductors N.V.", url: "https://stocks.apple.com/symbol/NXPI" },
  {
    id: "123",
    query: "CDNS",
    description: "Cadence Design Systems, Inc.",
    url: "https://stocks.apple.com/symbol/CDNS",
  },
  { id: "124", query: "WM", description: "Waste Management, Inc.", url: "https://stocks.apple.com/symbol/WM" },
  {
    id: "125",
    query: "ADM",
    description: "Archer-Daniels-Midland Company",
    url: "https://stocks.apple.com/symbol/ADM",
  },
  { id: "126", query: "ROP", description: "Roper Technologies, Inc.", url: "https://stocks.apple.com/symbol/ROP" },
  { id: "127", query: "GD", description: "General Dynamics Corporation", url: "https://stocks.apple.com/symbol/GD" },
  { id: "128", query: "TT", description: "Trane Technologies plc", url: "https://stocks.apple.com/symbol/TT" },
  {
    id: "129",
    query: "CTSH",
    description: "Cognizant Technology Solutions Corporation",
    url: "https://stocks.apple.com/symbol/CTSH",
  },
  { id: "130", query: "SNPS", description: "Synopsys, Inc.", url: "https://stocks.apple.com/symbol/SNPS" },
  {
    id: "131",
    query: "MNST",
    description: "Monster Beverage Corporation",
    url: "https://stocks.apple.com/symbol/MNST",
  },
  { id: "132", query: "CTAS", description: "Cintas Corporation", url: "https://stocks.apple.com/symbol/CTAS" },
  { id: "133", query: "KMB", description: "Kimberly-Clark Corporation", url: "https://stocks.apple.com/symbol/KMB" },
  { id: "134", query: "D", description: "Dominion Energy, Inc.", url: "https://stocks.apple.com/symbol/D" },
  { id: "135", query: "EXC", description: "Exelon Corporation", url: "https://stocks.apple.com/symbol/EXC" },
  { id: "136", query: "FTNT", description: "Fortinet, Inc.", url: "https://stocks.apple.com/symbol/FTNT" },
  { id: "137", query: "BIIB", description: "Biogen Inc.", url: "https://stocks.apple.com/symbol/BIIB" },
  { id: "138", query: "A", description: "Agilent Technologies, Inc.", url: "https://stocks.apple.com/symbol/A" },
  { id: "139", query: "DXCM", description: "DexCom, Inc.", url: "https://stocks.apple.com/symbol/DXCM" },
  {
    id: "140",
    query: "MCHP",
    description: "Microchip Technology Incorporated",
    url: "https://stocks.apple.com/symbol/MCHP",
  },
  { id: "141", query: "ORLY", description: "O'Reilly Automotive, Inc.", url: "https://stocks.apple.com/symbol/ORLY" },
  { id: "142", query: "MSCI", description: "MSCI Inc.", url: "https://stocks.apple.com/symbol/MSCI" },
  { id: "143", query: "APH", description: "Amphenol Corporation", url: "https://stocks.apple.com/symbol/APH" },
  {
    id: "144",
    query: "SBAC",
    description: "SBA Communications Corporation",
    url: "https://stocks.apple.com/symbol/SBAC",
  },
  { id: "145", query: "PAYX", description: "Paychex, Inc.", url: "https://stocks.apple.com/symbol/PAYX" },
  { id: "146", query: "CMG", description: "Chipotle Mexican Grill, Inc.", url: "https://stocks.apple.com/symbol/CMG" },
  { id: "147", query: "ROST", description: "Ross Stores, Inc.", url: "https://stocks.apple.com/symbol/ROST" },
  { id: "148", query: "CARR", description: "Carrier Global Corporation", url: "https://stocks.apple.com/symbol/CARR" },
  { id: "149", query: "IQV", description: "IQVIA Holdings Inc.", url: "https://stocks.apple.com/symbol/IQV" },
  { id: "150", query: "OTIS", description: "Otis Worldwide Corporation", url: "https://stocks.apple.com/symbol/OTIS" },
  { id: "151", query: "ALGN", description: "Align Technology, Inc.", url: "https://stocks.apple.com/symbol/ALGN" },
  { id: "152", query: "WELL", description: "Welltower Inc.", url: "https://stocks.apple.com/symbol/WELL" },
  {
    id: "153",
    query: "AEP",
    description: "American Electric Power Company, Inc.",
    url: "https://stocks.apple.com/symbol/AEP",
  },
  { id: "154", query: "XLNX", description: "Xilinx, Inc.", url: "https://stocks.apple.com/symbol/XLNX" },
  { id: "155", query: "TRV", description: "The Travelers Companies, Inc.", url: "https://stocks.apple.com/symbol/TRV" },
  {
    id: "156",
    query: "HLT",
    description: "Hilton Worldwide Holdings Inc.",
    url: "https://stocks.apple.com/symbol/HLT",
  },
  { id: "157", query: "MET", description: "MetLife, Inc.", url: "https://stocks.apple.com/symbol/MET" },
  { id: "158", query: "KMI", description: "Kinder Morgan, Inc.", url: "https://stocks.apple.com/symbol/KMI" },
  { id: "159", query: "PSA", description: "Public Storage", url: "https://stocks.apple.com/symbol/PSA" },
  { id: "160", query: "MAR", description: "Marriott International, Inc.", url: "https://stocks.apple.com/symbol/MAR" },
  { id: "161", query: "MTCH", description: "Match Group, Inc.", url: "https://stocks.apple.com/symbol/MTCH" },
  { id: "162", query: "STZ", description: "Constellation Brands, Inc.", url: "https://stocks.apple.com/symbol/STZ" },
  { id: "163", query: "AZO", description: "AutoZone, Inc.", url: "https://stocks.apple.com/symbol/AZO" },
  { id: "164", query: "TWTR", description: "Twitter, Inc.", url: "https://stocks.apple.com/symbol/TWTR" },
  { id: "165", query: "YUM", description: "Yum! Brands, Inc.", url: "https://stocks.apple.com/symbol/YUM" },
  { id: "166", query: "EBAY", description: "eBay Inc.", url: "https://stocks.apple.com/symbol/EBAY" },
  { id: "167", query: "VRSK", description: "Verisk Analytics, Inc.", url: "https://stocks.apple.com/symbol/VRSK" },
  { id: "168", query: "DLTR", description: "Dollar Tree, Inc.", url: "https://stocks.apple.com/symbol/DLTR" },
  { id: "169", query: "EA", description: "Electronic Arts Inc.", url: "https://stocks.apple.com/symbol/EA" },
  { id: "170", query: "CERN", description: "Cerner Corporation", url: "https://stocks.apple.com/symbol/CERN" },
  {
    id: "171",
    query: "ALXN",
    description: "Alexion Pharmaceuticals, Inc.",
    url: "https://stocks.apple.com/symbol/ALXN",
  },
  { id: "172", query: "CPRT", description: "Copart, Inc.", url: "https://stocks.apple.com/symbol/CPRT" },
  { id: "173", query: "ANSS", description: "ANSYS, Inc.", url: "https://stocks.apple.com/symbol/ANSS" },
  { id: "174", query: "TROW", description: "T. Rowe Price Group, Inc.", url: "https://stocks.apple.com/symbol/TROW" },
  { id: "175", query: "PCAR", description: "PACCAR Inc", url: "https://stocks.apple.com/symbol/PCAR" },
  { id: "176", query: "FAST", description: "Fastenal Company", url: "https://stocks.apple.com/symbol/FAST" },
  { id: "177", query: "SWKS", description: "Skyworks Solutions, Inc.", url: "https://stocks.apple.com/symbol/SWKS" },
  { id: "178", query: "KEYS", description: "Keysight Technologies, Inc.", url: "https://stocks.apple.com/symbol/KEYS" },
  { id: "179", query: "CTVA", description: "Corteva, Inc.", url: "https://stocks.apple.com/symbol/CTVA" },
  { id: "180", query: "DG", description: "Dollar General Corporation", url: "https://stocks.apple.com/symbol/DG" },
  {
    id: "181",
    query: "MXIM",
    description: "Maxim Integrated Products, Inc.",
    url: "https://stocks.apple.com/symbol/MXIM",
  },
  { id: "182", query: "FRC", description: "First Republic Bank", url: "https://stocks.apple.com/symbol/FRC" },
  { id: "183", query: "VRSN", description: "VeriSign, Inc.", url: "https://stocks.apple.com/symbol/VRSN" },
  { id: "184", query: "APTV", description: "Aptiv PLC", url: "https://stocks.apple.com/symbol/APTV" },
  {
    id: "185",
    query: "WLTW",
    description: "Willis Towers Watson Public Limited Company",
    url: "https://stocks.apple.com/symbol/WLTW",
  },
  { id: "186", query: "SIVB", description: "SVB Financial Group", url: "https://stocks.apple.com/symbol/SIVB" },
  { id: "187", query: "GLW", description: "Corning Incorporated", url: "https://stocks.apple.com/symbol/GLW" },
  {
    id: "188",
    query: "ODFL",
    description: "Old Dominion Freight Line, Inc.",
    url: "https://stocks.apple.com/symbol/ODFL",
  },
  { id: "189", query: "CBRE", description: "CBRE Group, Inc.", url: "https://stocks.apple.com/symbol/CBRE" },
  { id: "190", query: "FITB", description: "Fifth Third Bancorp", url: "https://stocks.apple.com/symbol/FITB" },
  {
    id: "191",
    query: "MTD",
    description: "Mettler-Toledo International Inc.",
    url: "https://stocks.apple.com/symbol/MTD",
  },
  { id: "192", query: "NTRS", description: "Northern Trust Corporation", url: "https://stocks.apple.com/symbol/NTRS" },
  {
    id: "193",
    query: "ZBRA",
    description: "Zebra Technologies Corporation",
    url: "https://stocks.apple.com/symbol/ZBRA",
  },
  { id: "194", query: "GRMN", description: "Garmin Ltd.", url: "https://stocks.apple.com/symbol/GRMN" },
  { id: "195", query: "CDW", description: "CDW Corporation", url: "https://stocks.apple.com/symbol/CDW" },
  { id: "196", query: "TSCO", description: "Tractor Supply Company", url: "https://stocks.apple.com/symbol/TSCO" },
  { id: "197", query: "HOLX", description: "Hologic, Inc.", url: "https://stocks.apple.com/symbol/HOLX" },
  { id: "198", query: "ETSY", description: "Etsy, Inc.", url: "https://stocks.apple.com/symbol/ETSY" },
  { id: "199", query: "PAYC", description: "Paycom Software, Inc.", url: "https://stocks.apple.com/symbol/PAYC" },
  {
    id: "200",
    query: "ARE",
    description: "Alexandria Real Estate Equities, Inc.",
    url: "https://stocks.apple.com/symbol/ARE",
  },
  { id: "201", query: "POOL", description: "Pool Corporation", url: "https://stocks.apple.com/symbol/POOL" },
  { id: "202", query: "ULTA", description: "Ulta Beauty, Inc.", url: "https://stocks.apple.com/symbol/ULTA" },
  { id: "203", query: "NDAQ", description: "Nasdaq, Inc.", url: "https://stocks.apple.com/symbol/NDAQ" },
  {
    id: "204",
    query: "EXPD",
    description: "Expeditors International of Washington, Inc.",
    url: "https://stocks.apple.com/symbol/EXPD",
  },
  {
    id: "205",
    query: "MPWR",
    description: "Monolithic Power Systems, Inc.",
    url: "https://stocks.apple.com/symbol/MPWR",
  },
  { id: "206", query: "CTAS", description: "Cintas Corporation", url: "https://stocks.apple.com/symbol/CTAS" },
  { id: "207", query: "INCY", description: "Incyte Corporation", url: "https://stocks.apple.com/symbol/INCY" },
  { id: "208", query: "URI", description: "United Rentals, Inc.", url: "https://stocks.apple.com/symbol/URI" },
  { id: "209", query: "GNRC", description: "Generac Holdings Inc.", url: "https://stocks.apple.com/symbol/GNRC" },
  { id: "210", query: "DAL", description: "Delta Air Lines, Inc.", url: "https://stocks.apple.com/symbol/DAL" },
  { id: "211", query: "ABMD", description: "ABIOMED, Inc.", url: "https://stocks.apple.com/symbol/ABMD" },
  { id: "212", query: "TDG", description: "TransDigm Group Incorporated", url: "https://stocks.apple.com/symbol/TDG" },
  { id: "213", query: "TYL", description: "Tyler Technologies, Inc.", url: "https://stocks.apple.com/symbol/TYL" },
  { id: "214", query: "TER", description: "Teradyne, Inc.", url: "https://stocks.apple.com/symbol/TER" },
  {
    id: "215",
    query: "JKHY",
    description: "Jack Henry & Associates, Inc.",
    url: "https://stocks.apple.com/symbol/JKHY",
  },
  { id: "216", query: "AKAM", description: "Akamai Technologies, Inc.", url: "https://stocks.apple.com/symbol/AKAM" },
  {
    id: "217",
    query: "TTWO",
    description: "Take-Two Interactive Software, Inc.",
    url: "https://stocks.apple.com/symbol/TTWO",
  },
  { id: "218", query: "LDOS", description: "Leidos Holdings, Inc.", url: "https://stocks.apple.com/symbol/LDOS" },
  { id: "219", query: "PKI", description: "PerkinElmer, Inc.", url: "https://stocks.apple.com/symbol/PKI" },
  { id: "220", query: "QRVO", description: "Qorvo, Inc.", url: "https://stocks.apple.com/symbol/QRVO" },
  { id: "221", query: "DPZ", description: "Domino's Pizza, Inc.", url: "https://stocks.apple.com/symbol/DPZ" },
  {
    id: "222",
    query: "JBHT",
    description: "J.B. Hunt Transport Services, Inc.",
    url: "https://stocks.apple.com/symbol/JBHT",
  },
  { id: "223", query: "NLOK", description: "NortonLifeLock Inc.", url: "https://stocks.apple.com/symbol/NLOK" },
  { id: "224", query: "DISH", description: "DISH Network Corporation", url: "https://stocks.apple.com/symbol/DISH" },
  { id: "225", query: "CTXS", description: "Citrix Systems, Inc.", url: "https://stocks.apple.com/symbol/CTXS" },
  { id: "226", query: "WAT", description: "Waters Corporation", url: "https://stocks.apple.com/symbol/WAT" },
  { id: "227", query: "NTAP", description: "NetApp, Inc.", url: "https://stocks.apple.com/symbol/NTAP" },
  { id: "228", query: "LUMN", description: "Lumen Technologies, Inc.", url: "https://stocks.apple.com/symbol/LUMN" },
  {
    id: "229",
    query: "CHRW",
    description: "C.H. Robinson Worldwide, Inc.",
    url: "https://stocks.apple.com/symbol/CHRW",
  },
  {
    id: "230",
    query: "FBHS",
    description: "Fortune Brands Home & Security, Inc.",
    url: "https://stocks.apple.com/symbol/FBHS",
  },
  { id: "231", query: "XRAY", description: "DENTSPLY SIRONA Inc.", url: "https://stocks.apple.com/symbol/XRAY" },
  { id: "232", query: "IPGP", description: "IPG Photonics Corporation", url: "https://stocks.apple.com/symbol/IPGP" },
  { id: "233", query: "FFIV", description: "F5 Networks, Inc.", url: "https://stocks.apple.com/symbol/FFIV" },
  { id: "234", query: "JNPR", description: "Juniper Networks, Inc.", url: "https://stocks.apple.com/symbol/JNPR" },
  {
    id: "235",
    query: "ZION",
    description: "Zions Bancorporation, National Association",
    url: "https://stocks.apple.com/symbol/ZION",
  },
  { id: "236", query: "PTC", description: "PTC Inc.", url: "https://stocks.apple.com/symbol/PTC" },
  { id: "237", query: "TECH", description: "Bio-Techne Corporation", url: "https://stocks.apple.com/symbol/TECH" },
  { id: "238", query: "TFX", description: "Teleflex Incorporated", url: "https://stocks.apple.com/symbol/TFX" },
  { id: "239", query: "NDSN", description: "Nordson Corporation", url: "https://stocks.apple.com/symbol/NDSN" },
  {
    id: "240",
    query: "SEDG",
    description: "SolarEdge Technologies, Inc.",
    url: "https://stocks.apple.com/symbol/SEDG",
  },
  { id: "241", query: "TRMB", description: "Trimble Inc.", url: "https://stocks.apple.com/symbol/TRMB" },
  {
    id: "242",
    query: "BR",
    description: "Broadridge Financial Solutions, Inc.",
    url: "https://stocks.apple.com/symbol/BR",
  },
  { id: "243", query: "EVRG", description: "Evergy, Inc.", url: "https://stocks.apple.com/symbol/EVRG" },
  { id: "244", query: "STE", description: "STERIS plc", url: "https://stocks.apple.com/symbol/STE" },
  {
    id: "245",
    query: "TDY",
    description: "Teledyne Technologies Incorporated",
    url: "https://stocks.apple.com/symbol/TDY",
  },
  { id: "246", query: "SJM", description: "The J. M. Smucker Company", url: "https://stocks.apple.com/symbol/SJM" },
  { id: "247", query: "DRI", description: "Darden Restaurants, Inc.", url: "https://stocks.apple.com/symbol/DRI" },
  { id: "248", query: "FANG", description: "Diamondback Energy, Inc.", url: "https://stocks.apple.com/symbol/FANG" },
  { id: "249", query: "NLSN", description: "Nielsen Holdings plc", url: "https://stocks.apple.com/symbol/NLSN" },
  { id: "250", query: "PEAK", description: "Healthpeak Properties, Inc.", url: "https://stocks.apple.com/symbol/PEAK" },
  { id: "251", query: "BIO", description: "Bio-Rad Laboratories, Inc.", url: "https://stocks.apple.com/symbol/BIO" },
  { id: "252", query: "ALLE", description: "Allegion plc", url: "https://stocks.apple.com/symbol/ALLE" },
  { id: "253", query: "FMC", description: "FMC Corporation", url: "https://stocks.apple.com/symbol/FMC" },
  { id: "254", query: "VTRS", description: "Viatris Inc.", url: "https://stocks.apple.com/symbol/VTRS" },
  { id: "255", query: "HSIC", description: "Henry Schein, Inc.", url: "https://stocks.apple.com/symbol/HSIC" },
  { id: "256", query: "EXPE", description: "Expedia Group, Inc.", url: "https://stocks.apple.com/symbol/EXPE" },
  { id: "257", query: "ENPH", description: "Enphase Energy, Inc.", url: "https://stocks.apple.com/symbol/ENPH" },
  { id: "258", query: "FOXA", description: "Fox Corporation", url: "https://stocks.apple.com/symbol/FOXA" },
  { id: "259", query: "FOX", description: "Fox Corporation", url: "https://stocks.apple.com/symbol/FOX" },
  { id: "260", query: "WYNN", description: "Wynn Resorts, Limited", url: "https://stocks.apple.com/symbol/WYNN" },
  { id: "261", query: "CBOE", description: "Cboe Global Markets, Inc.", url: "https://stocks.apple.com/symbol/CBOE" },
  { id: "262", query: "IEX", description: "IDEX Corporation", url: "https://stocks.apple.com/symbol/IEX" },
  { id: "263", query: "NWSA", description: "News Corporation", url: "https://stocks.apple.com/symbol/NWSA" },
  { id: "264", query: "NWS", description: "News Corporation", url: "https://stocks.apple.com/symbol/NWS" },
  { id: "265", query: "LKQ", description: "LKQ Corporation", url: "https://stocks.apple.com/symbol/LKQ" },
  { id: "266", query: "LRCX", description: "Lam Research Corporation", url: "https://stocks.apple.com/symbol/LRCX" },
  { id: "267", query: "LNT", description: "Alliant Energy Corporation", url: "https://stocks.apple.com/symbol/LNT" },
  { id: "268", query: "HWM", description: "Howmet Aerospace Inc.", url: "https://stocks.apple.com/symbol/HWM" },
  {
    id: "269",
    query: "LYV",
    description: "Live Nation Entertainment, Inc.",
    url: "https://stocks.apple.com/symbol/LYV",
  },
  { id: "270", query: "CTLT", description: "Catalent, Inc.", url: "https://stocks.apple.com/symbol/CTLT" },
  { id: "271", query: "AOS", description: "A. O. Smith Corporation", url: "https://stocks.apple.com/symbol/AOS" },
  { id: "272", query: "CE", description: "Celanese Corporation", url: "https://stocks.apple.com/symbol/CE" },
  {
    id: "273",
    query: "UAL",
    description: "United Airlines Holdings, Inc.",
    url: "https://stocks.apple.com/symbol/UAL",
  },
  { id: "274", query: "PENN", description: "Penn National Gaming, Inc.", url: "https://stocks.apple.com/symbol/PENN" },
  { id: "275", query: "MKTX", description: "MarketAxess Holdings Inc.", url: "https://stocks.apple.com/symbol/MKTX" },
  { id: "276", query: "DISCA", description: "Discovery, Inc.", url: "https://stocks.apple.com/symbol/DISCA" },
  { id: "277", query: "DISCK", description: "Discovery, Inc.", url: "https://stocks.apple.com/symbol/DISCK" },
  { id: "278", query: "AMCR", description: "Amcor plc", url: "https://stocks.apple.com/symbol/AMCR" },
  { id: "279", query: "CZR", description: "Caesars Entertainment, Inc.", url: "https://stocks.apple.com/symbol/CZR" },
  {
    id: "280",
    query: "CINF",
    description: "Cincinnati Financial Corporation",
    url: "https://stocks.apple.com/symbol/CINF",
  },
  { id: "281", query: "SWKS", description: "Skyworks Solutions, Inc.", url: "https://stocks.apple.com/symbol/SWKS" },
  { id: "282", query: "COO", description: "The Cooper Companies, Inc.", url: "https://stocks.apple.com/symbol/COO" },
  {
    id: "283",
    query: "HBAN",
    description: "Huntington Bancshares Incorporated",
    url: "https://stocks.apple.com/symbol/HBAN",
  },
  { id: "284", query: "MOS", description: "The Mosaic Company", url: "https://stocks.apple.com/symbol/MOS" },
  { id: "285", query: "SNA", description: "Snap-on Incorporated", url: "https://stocks.apple.com/symbol/SNA" },
  { id: "286", query: "MTCH", description: "Match Group, Inc.", url: "https://stocks.apple.com/symbol/MTCH" },
  { id: "287", query: "BXP", description: "Boston Properties, Inc.", url: "https://stocks.apple.com/symbol/BXP" },
  {
    id: "288",
    query: "PFG",
    description: "Principal Financial Group, Inc.",
    url: "https://stocks.apple.com/symbol/PFG",
  },
  { id: "289", query: "ANET", description: "Arista Networks, Inc.", url: "https://stocks.apple.com/symbol/ANET" },
  {
    id: "290",
    query: "ETFC",
    description: "E*TRADE Financial Corporation",
    url: "https://stocks.apple.com/symbol/ETFC",
  },
  { id: "291", query: "DXC", description: "DXC Technology Company", url: "https://stocks.apple.com/symbol/DXC" },
  { id: "292", query: "UDR", description: "UDR, Inc.", url: "https://stocks.apple.com/symbol/UDR" },
  { id: "293", query: "NLOK", description: "NortonLifeLock Inc.", url: "https://stocks.apple.com/symbol/NLOK" },
  { id: "294", query: "APA", description: "Apache Corporation", url: "https://stocks.apple.com/symbol/APA" },
  {
    id: "295",
    query: "JKHY",
    description: "Jack Henry & Associates, Inc.",
    url: "https://stocks.apple.com/symbol/JKHY",
  },
  { id: "296", query: "REG", description: "Regency Centers Corporation", url: "https://stocks.apple.com/symbol/REG" },
  { id: "297", query: "DISH", description: "DISH Network Corporation", url: "https://stocks.apple.com/symbol/DISH" },
  {
    id: "298",
    query: "HII",
    description: "Huntington Ingalls Industries, Inc.",
    url: "https://stocks.apple.com/symbol/HII",
  },
  { id: "299", query: "NRG", description: "NRG Energy, Inc.", url: "https://stocks.apple.com/symbol/NRG" },
  { id: "300", query: "AAP", description: "Advance Auto Parts, Inc.", url: "https://stocks.apple.com/symbol/AAP" },
  { id: "301", query: "CTXS", description: "Citrix Systems, Inc.", url: "https://stocks.apple.com/symbol/CTXS" },
  {
    id: "302",
    query: "PKG",
    description: "Packaging Corporation of America",
    url: "https://stocks.apple.com/symbol/PKG",
  },
  {
    id: "303",
    query: "FBHS",
    description: "Fortune Brands Home & Security, Inc.",
    url: "https://stocks.apple.com/symbol/FBHS",
  },
  { id: "304", query: "NVR", description: "NVR, Inc.", url: "https://stocks.apple.com/symbol/NVR" },
  {
    id: "305",
    query: "CHRW",
    description: "C.H. Robinson Worldwide, Inc.",
    url: "https://stocks.apple.com/symbol/CHRW",
  },
  { id: "306", query: "WHR", description: "Whirlpool Corporation", url: "https://stocks.apple.com/symbol/WHR" },
  {
    id: "307",
    query: "JBHT",
    description: "J.B. Hunt Transport Services, Inc.",
    url: "https://stocks.apple.com/symbol/JBHT",
  },
  { id: "308", query: "XRAY", description: "DENTSPLY SIRONA Inc.", url: "https://stocks.apple.com/symbol/XRAY" },
  {
    id: "309",
    query: "NCLH",
    description: "Norwegian Cruise Line Holdings Ltd.",
    url: "https://stocks.apple.com/symbol/NCLH",
  },
  { id: "310", query: "HAS", description: "Hasbro, Inc.", url: "https://stocks.apple.com/symbol/HAS" },
  { id: "311", query: "LW", description: "Lamb Weston Holdings, Inc.", url: "https://stocks.apple.com/symbol/LW" },
  { id: "312", query: "FFIV", description: "F5 Networks, Inc.", url: "https://stocks.apple.com/symbol/FFIV" },
  { id: "313", query: "PNR", description: "Pentair plc", url: "https://stocks.apple.com/symbol/PNR" },
  { id: "314", query: "NWSA", description: "News Corporation", url: "https://stocks.apple.com/symbol/NWSA" },
  { id: "315", query: "NWS", description: "News Corporation", url: "https://stocks.apple.com/symbol/NWS" },
  { id: "316", query: "SEE", description: "Sealed Air Corporation", url: "https://stocks.apple.com/symbol/SEE" },
  { id: "317", query: "IPGP", description: "IPG Photonics Corporation", url: "https://stocks.apple.com/symbol/IPGP" },
  { id: "318", query: "JNPR", description: "Juniper Networks, Inc.", url: "https://stocks.apple.com/symbol/JNPR" },
  { id: "319", query: "ROL", description: "Rollins, Inc.", url: "https://stocks.apple.com/symbol/ROL" },
  { id: "320", query: "HRL", description: "Hormel Foods Corporation", url: "https://stocks.apple.com/symbol/HRL" },
  {
    id: "321",
    query: "PBCT",
    description: "People's United Financial, Inc.",
    url: "https://stocks.apple.com/symbol/PBCT",
  },
  { id: "322", query: "LNC", description: "Lincoln National Corporation", url: "https://stocks.apple.com/symbol/LNC" },
  { id: "323", query: "HST", description: "Host Hotels & Resorts, Inc.", url: "https://stocks.apple.com/symbol/HST" },
  {
    id: "324",
    query: "ZION",
    description: "Zions Bancorporation, National Association",
    url: "https://stocks.apple.com/symbol/ZION",
  },
  { id: "325", query: "DVA", description: "DaVita Inc.", url: "https://stocks.apple.com/symbol/DVA" },
  { id: "326", query: "AIZ", description: "Assurant, Inc.", url: "https://stocks.apple.com/symbol/AIZ" },
  { id: "327", query: "RE", description: "Everest Re Group, Ltd.", url: "https://stocks.apple.com/symbol/RE" },
  { id: "328", query: "CPB", description: "Campbell Soup Company", url: "https://stocks.apple.com/symbol/CPB" },
  {
    id: "329",
    query: "UHS",
    description: "Universal Health Services, Inc.",
    url: "https://stocks.apple.com/symbol/UHS",
  },
  { id: "330", query: "NLSN", description: "Nielsen Holdings plc", url: "https://stocks.apple.com/symbol/NLSN" },
  {
    id: "331",
    query: "PNW",
    description: "Pinnacle West Capital Corporation",
    url: "https://stocks.apple.com/symbol/PNW",
  },
  { id: "332", query: "NI", description: "NiSource Inc.", url: "https://stocks.apple.com/symbol/NI" },
  { id: "333", query: "WYNN", description: "Wynn Resorts, Limited", url: "https://stocks.apple.com/symbol/WYNN" },
  { id: "334", query: "TAP", description: "Molson Coors Beverage Company", url: "https://stocks.apple.com/symbol/TAP" },
  { id: "335", query: "AOS", description: "A. O. Smith Corporation", url: "https://stocks.apple.com/symbol/AOS" },
  {
    id: "336",
    query: "RHI",
    description: "Robert Half International Inc.",
    url: "https://stocks.apple.com/symbol/RHI",
  },
  { id: "337", query: "HSIC", description: "Henry Schein, Inc.", url: "https://stocks.apple.com/symbol/HSIC" },
  { id: "338", query: "AAL", description: "American Airlines Group Inc.", url: "https://stocks.apple.com/symbol/AAL" },
  { id: "339", query: "BWA", description: "BorgWarner Inc.", url: "https://stocks.apple.com/symbol/BWA" },
  { id: "340", query: "ALLE", description: "Allegion plc", url: "https://stocks.apple.com/symbol/ALLE" },
  { id: "341", query: "FANG", description: "Diamondback Energy, Inc.", url: "https://stocks.apple.com/symbol/FANG" },
  { id: "342", query: "ALK", description: "Alaska Air Group, Inc.", url: "https://stocks.apple.com/symbol/ALK" },
  { id: "343", query: "HOLX", description: "Hologic, Inc.", url: "https://stocks.apple.com/symbol/HOLX" },
  { id: "344", query: "HBI", description: "Hanesbrands Inc.", url: "https://stocks.apple.com/symbol/HBI" },
  { id: "345", query: "CMA", description: "Comerica Incorporated", url: "https://stocks.apple.com/symbol/CMA" },
  { id: "346", query: "DRE", description: "Duke Realty Corporation", url: "https://stocks.apple.com/symbol/DRE" },
  { id: "347", query: "NDSN", description: "Nordson Corporation", url: "https://stocks.apple.com/symbol/NDSN" },
  { id: "348", query: "CBOE", description: "Cboe Global Markets, Inc.", url: "https://stocks.apple.com/symbol/CBOE" },
  { id: "349", query: "TFX", description: "Teleflex Incorporated", url: "https://stocks.apple.com/symbol/TFX" },
  { id: "350", query: "CDAY", description: "Ceridian HCM Holding Inc.", url: "https://stocks.apple.com/symbol/CDAY" },
  { id: "351", query: "QRVO", description: "Qorvo, Inc.", url: "https://stocks.apple.com/symbol/QRVO" },
  { id: "352", query: "FOXA", description: "Fox Corporation", url: "https://stocks.apple.com/symbol/FOXA" },
  { id: "353", query: "FOX", description: "Fox Corporation", url: "https://stocks.apple.com/symbol/FOX" },
  { id: "354", query: "IEX", description: "IDEX Corporation", url: "https://stocks.apple.com/symbol/IEX" },
  { id: "355", query: "SJM", description: "The J. M. Smucker Company", url: "https://stocks.apple.com/symbol/SJM" },
  {
    id: "356",
    query: "MXIM",
    description: "Maxim Integrated Products, Inc.",
    url: "https://stocks.apple.com/symbol/MXIM",
  },
  { id: "357", query: "GRMN", description: "Garmin Ltd.", url: "https://stocks.apple.com/symbol/GRMN" },
  { id: "358", query: "AKAM", description: "Akamai Technologies, Inc.", url: "https://stocks.apple.com/symbol/AKAM" },
  { id: "359", query: "LDOS", description: "Leidos Holdings, Inc.", url: "https://stocks.apple.com/symbol/LDOS" },
  {
    id: "360",
    query: "TTWO",
    description: "Take-Two Interactive Software, Inc.",
    url: "https://stocks.apple.com/symbol/TTWO",
  },
  { id: "361", query: "TYL", description: "Tyler Technologies, Inc.", url: "https://stocks.apple.com/symbol/TYL" },
  { id: "362", query: "TER", description: "Teradyne, Inc.", url: "https://stocks.apple.com/symbol/TER" },
  { id: "363", query: "ABMD", description: "ABIOMED, Inc.", url: "https://stocks.apple.com/symbol/ABMD" },
  { id: "364", query: "TDG", description: "TransDigm Group Incorporated", url: "https://stocks.apple.com/symbol/TDG" },
  { id: "365", query: "GNRC", description: "Generac Holdings Inc.", url: "https://stocks.apple.com/symbol/GNRC" },
  { id: "366", query: "POOL", description: "Pool Corporation", url: "https://stocks.apple.com/symbol/POOL" },
  { id: "367", query: "ULTA", description: "Ulta Beauty, Inc.", url: "https://stocks.apple.com/symbol/ULTA" },
  { id: "368", query: "NDAQ", description: "Nasdaq, Inc.", url: "https://stocks.apple.com/symbol/NDAQ" },
  {
    id: "369",
    query: "EXPD",
    description: "Expeditors International of Washington, Inc.",
    url: "https://stocks.apple.com/symbol/EXPD",
  },
  {
    id: "370",
    query: "MPWR",
    description: "Monolithic Power Systems, Inc.",
    url: "https://stocks.apple.com/symbol/MPWR",
  },
  { id: "371", query: "INCY", description: "Incyte Corporation", url: "https://stocks.apple.com/symbol/INCY" },
  { id: "372", query: "URI", description: "United Rentals, Inc.", url: "https://stocks.apple.com/symbol/URI" },
  { id: "373", query: "DAL", description: "Delta Air Lines, Inc.", url: "https://stocks.apple.com/symbol/DAL" },
  { id: "374", query: "PKI", description: "PerkinElmer, Inc.", url: "https://stocks.apple.com/symbol/PKI" },
  { id: "375", query: "DPZ", description: "Domino's Pizza, Inc.", url: "https://stocks.apple.com/symbol/DPZ" },
  { id: "376", query: "DISH", description: "DISH Network Corporation", url: "https://stocks.apple.com/symbol/DISH" },
  { id: "377", query: "WAT", description: "Waters Corporation", url: "https://stocks.apple.com/symbol/WAT" },
  { id: "378", query: "NTAP", description: "NetApp, Inc.", url: "https://stocks.apple.com/symbol/NTAP" },
  { id: "379", query: "LUMN", description: "Lumen Technologies, Inc.", url: "https://stocks.apple.com/symbol/LUMN" },
  { id: "380", query: "PTC", description: "PTC Inc.", url: "https://stocks.apple.com/symbol/PTC" },
  { id: "381", query: "TECH", description: "Bio-Techne Corporation", url: "https://stocks.apple.com/symbol/TECH" },
  {
    id: "382",
    query: "SEDG",
    description: "SolarEdge Technologies, Inc.",
    url: "https://stocks.apple.com/symbol/SEDG",
  },
  { id: "383", query: "TRMB", description: "Trimble Inc.", url: "https://stocks.apple.com/symbol/TRMB" },
  {
    id: "384",
    query: "BR",
    description: "Broadridge Financial Solutions, Inc.",
    url: "https://stocks.apple.com/symbol/BR",
  },
  { id: "385", query: "EVRG", description: "Evergy, Inc.", url: "https://stocks.apple.com/symbol/EVRG" },
  { id: "386", query: "STE", description: "STERIS plc", url: "https://stocks.apple.com/symbol/STE" },
  {
    id: "387",
    query: "TDY",
    description: "Teledyne Technologies Incorporated",
    url: "https://stocks.apple.com/symbol/TDY",
  },
  { id: "388", query: "DRI", description: "Darden Restaurants, Inc.", url: "https://stocks.apple.com/symbol/DRI" },
  { id: "389", query: "PEAK", description: "Healthpeak Properties, Inc.", url: "https://stocks.apple.com/symbol/PEAK" },
  { id: "390", query: "BIO", description: "Bio-Rad Laboratories, Inc.", url: "https://stocks.apple.com/symbol/BIO" },
  { id: "391", query: "FMC", description: "FMC Corporation", url: "https://stocks.apple.com/symbol/FMC" },
  { id: "392", query: "VTRS", description: "Viatris Inc.", url: "https://stocks.apple.com/symbol/VTRS" },
  { id: "393", query: "EXPE", description: "Expedia Group, Inc.", url: "https://stocks.apple.com/symbol/EXPE" },
  { id: "394", query: "ENPH", description: "Enphase Energy, Inc.", url: "https://stocks.apple.com/symbol/ENPH" },
  { id: "395", query: "LKQ", description: "LKQ Corporation", url: "https://stocks.apple.com/symbol/LKQ" },
  { id: "396", query: "LNT", description: "Alliant Energy Corporation", url: "https://stocks.apple.com/symbol/LNT" },
  { id: "397", query: "HWM", description: "Howmet Aerospace Inc.", url: "https://stocks.apple.com/symbol/HWM" },
  {
    id: "398",
    query: "LYV",
    description: "Live Nation Entertainment, Inc.",
    url: "https://stocks.apple.com/symbol/LYV",
  },
  { id: "399", query: "CTLT", description: "Catalent, Inc.", url: "https://stocks.apple.com/symbol/CTLT" },
  { id: "400", query: "CE", description: "Celanese Corporation", url: "https://stocks.apple.com/symbol/CE" },
  {
    id: "401",
    query: "UAL",
    description: "United Airlines Holdings, Inc.",
    url: "https://stocks.apple.com/symbol/UAL",
  },
  { id: "402", query: "PENN", description: "Penn National Gaming, Inc.", url: "https://stocks.apple.com/symbol/PENN" },
  { id: "403", query: "MKTX", description: "MarketAxess Holdings Inc.", url: "https://stocks.apple.com/symbol/MKTX" },
  { id: "404", query: "DISCA", description: "Discovery, Inc.", url: "https://stocks.apple.com/symbol/DISCA" },
  { id: "405", query: "DISCK", description: "Discovery, Inc.", url: "https://stocks.apple.com/symbol/DISCK" },
  { id: "406", query: "AMCR", description: "Amcor plc", url: "https://stocks.apple.com/symbol/AMCR" },
  { id: "407", query: "CZR", description: "Caesars Entertainment, Inc.", url: "https://stocks.apple.com/symbol/CZR" },
  {
    id: "408",
    query: "CINF",
    description: "Cincinnati Financial Corporation",
    url: "https://stocks.apple.com/symbol/CINF",
  },
  { id: "409", query: "COO", description: "The Cooper Companies, Inc.", url: "https://stocks.apple.com/symbol/COO" },
  {
    id: "410",
    query: "HBAN",
    description: "Huntington Bancshares Incorporated",
    url: "https://stocks.apple.com/symbol/HBAN",
  },
  { id: "411", query: "MOS", description: "The Mosaic Company", url: "https://stocks.apple.com/symbol/MOS" },
  { id: "412", query: "SNA", description: "Snap-on Incorporated", url: "https://stocks.apple.com/symbol/SNA" },
  { id: "413", query: "BXP", description: "Boston Properties, Inc.", url: "https://stocks.apple.com/symbol/BXP" },
  {
    id: "414",
    query: "PFG",
    description: "Principal Financial Group, Inc.",
    url: "https://stocks.apple.com/symbol/PFG",
  },
  { id: "415", query: "ANET", description: "Arista Networks, Inc.", url: "https://stocks.apple.com/symbol/ANET" },
  { id: "416", query: "DXC", description: "DXC Technology Company", url: "https://stocks.apple.com/symbol/DXC" },
  { id: "417", query: "UDR", description: "UDR, Inc.", url: "https://stocks.apple.com/symbol/UDR" },
  { id: "418", query: "APA", description: "APA Corporation", url: "https://stocks.apple.com/symbol/APA" },
  { id: "419", query: "REG", description: "Regency Centers Corporation", url: "https://stocks.apple.com/symbol/REG" },
  {
    id: "420",
    query: "HII",
    description: "Huntington Ingalls Industries, Inc.",
    url: "https://stocks.apple.com/symbol/HII",
  },
  { id: "421", query: "NRG", description: "NRG Energy, Inc.", url: "https://stocks.apple.com/symbol/NRG" },
  { id: "422", query: "AAP", description: "Advance Auto Parts, Inc.", url: "https://stocks.apple.com/symbol/AAP" },
  { id: "423", query: "BBWI", description: "Bath & Body Works, Inc.", url: "https://stocks.apple.com/symbol/BBWI" },
  { id: "424", query: "IVZ", description: "Invesco Ltd.", url: "https://stocks.apple.com/symbol/IVZ" },
  { id: "425", query: "RL", description: "Ralph Lauren Corporation", url: "https://stocks.apple.com/symbol/RL" },
  { id: "426", query: "NWSA", description: "News Corporation", url: "https://stocks.apple.com/symbol/NWSA" },
  { id: "427", query: "NWS", description: "News Corporation", url: "https://stocks.apple.com/symbol/NWS" },
  { id: "428", query: "PRGO", description: "Perrigo Company plc", url: "https://stocks.apple.com/symbol/PRGO" },
  {
    id: "429",
    query: "FRT",
    description: "Federal Realty Investment Trust",
    url: "https://stocks.apple.com/symbol/FRT",
  },
  {
    id: "430",
    query: "PNW",
    description: "Pinnacle West Capital Corporation",
    url: "https://stocks.apple.com/symbol/PNW",
  },
  { id: "431", query: "NI", description: "NiSource Inc.", url: "https://stocks.apple.com/symbol/NI" },
  { id: "432", query: "ROL", description: "Rollins, Inc.", url: "https://stocks.apple.com/symbol/ROL" },
  { id: "433", query: "NLOK", description: "NortonLifeLock Inc.", url: "https://stocks.apple.com/symbol/NLOK" },
  { id: "434", query: "TPR", description: "Tapestry, Inc.", url: "https://stocks.apple.com/symbol/TPR" },
  {
    id: "435",
    query: "JKHY",
    description: "Jack Henry & Associates, Inc.",
    url: "https://stocks.apple.com/symbol/JKHY",
  },
  { id: "436", query: "ALK", description: "Alaska Air Group, Inc.", url: "https://stocks.apple.com/symbol/ALK" },
  { id: "437", query: "HAS", description: "Hasbro, Inc.", url: "https://stocks.apple.com/symbol/HAS" },
  { id: "438", query: "SEE", description: "Sealed Air Corporation", url: "https://stocks.apple.com/symbol/SEE" },
  {
    id: "439",
    query: "FBHS",
    description: "Fortune Brands Home & Security, Inc.",
    url: "https://stocks.apple.com/symbol/FBHS",
  },
  {
    id: "440",
    query: "CHRW",
    description: "C.H. Robinson Worldwide, Inc.",
    url: "https://stocks.apple.com/symbol/CHRW",
  },
  { id: "441", query: "CPB", description: "Campbell Soup Company", url: "https://stocks.apple.com/symbol/CPB" },
  { id: "442", query: "JNPR", description: "Juniper Networks, Inc.", url: "https://stocks.apple.com/symbol/JNPR" },
  { id: "443", query: "HST", description: "Host Hotels & Resorts, Inc.", url: "https://stocks.apple.com/symbol/HST" },
  {
    id: "444",
    query: "ZION",
    description: "Zions Bancorporation, National Association",
    url: "https://stocks.apple.com/symbol/ZION",
  },
  { id: "445", query: "DVA", description: "DaVita Inc.", url: "https://stocks.apple.com/symbol/DVA" },
  { id: "446", query: "PNR", description: "Pentair plc", url: "https://stocks.apple.com/symbol/PNR" },
  {
    id: "447",
    query: "NCLH",
    description: "Norwegian Cruise Line Holdings Ltd.",
    url: "https://stocks.apple.com/symbol/NCLH",
  },
  {
    id: "448",
    query: "RHI",
    description: "Robert Half International Inc.",
    url: "https://stocks.apple.com/symbol/RHI",
  },
  { id: "449", query: "IPGP", description: "IPG Photonics Corporation", url: "https://stocks.apple.com/symbol/IPGP" },
  { id: "450", query: "FFIV", description: "F5, Inc.", url: "https://stocks.apple.com/symbol/FFIV" },
  { id: "451", query: "AIZ", description: "Assurant, Inc.", url: "https://stocks.apple.com/symbol/AIZ" },
  { id: "452", query: "LNC", description: "Lincoln National Corporation", url: "https://stocks.apple.com/symbol/LNC" },
  {
    id: "453",
    query: "PBCT",
    description: "People's United Financial, Inc.",
    url: "https://stocks.apple.com/symbol/PBCT",
  },
  {
    id: "454",
    query: "UHS",
    description: "Universal Health Services, Inc.",
    url: "https://stocks.apple.com/symbol/UHS",
  },
  { id: "455", query: "AOS", description: "A. O. Smith Corporation", url: "https://stocks.apple.com/symbol/AOS" },
  { id: "456", query: "HRL", description: "Hormel Foods Corporation", url: "https://stocks.apple.com/symbol/HRL" },
  { id: "457", query: "LW", description: "Lamb Weston Holdings, Inc.", url: "https://stocks.apple.com/symbol/LW" },
  { id: "458", query: "RE", description: "Everest Re Group, Ltd.", url: "https://stocks.apple.com/symbol/RE" },
  { id: "459", query: "WYNN", description: "Wynn Resorts, Limited", url: "https://stocks.apple.com/symbol/WYNN" },
  { id: "460", query: "TAP", description: "Molson Coors Beverage Company", url: "https://stocks.apple.com/symbol/TAP" },
  { id: "461", query: "HSIC", description: "Henry Schein, Inc.", url: "https://stocks.apple.com/symbol/HSIC" },
  { id: "462", query: "AAL", description: "American Airlines Group Inc.", url: "https://stocks.apple.com/symbol/AAL" },
  { id: "463", query: "BWA", description: "BorgWarner Inc.", url: "https://stocks.apple.com/symbol/BWA" },
  { id: "464", query: "ALLE", description: "Allegion plc", url: "https://stocks.apple.com/symbol/ALLE" },
  { id: "465", query: "FANG", description: "Diamondback Energy, Inc.", url: "https://stocks.apple.com/symbol/FANG" },
  { id: "466", query: "HOLX", description: "Hologic, Inc.", url: "https://stocks.apple.com/symbol/HOLX" },
  { id: "467", query: "HBI", description: "Hanesbrands Inc.", url: "https://stocks.apple.com/symbol/HBI" },
  { id: "468", query: "CMA", description: "Comerica Incorporated", url: "https://stocks.apple.com/symbol/CMA" },
  { id: "469", query: "DRE", description: "Duke Realty Corporation", url: "https://stocks.apple.com/symbol/DRE" },
  { id: "470", query: "NDSN", description: "Nordson Corporation", url: "https://stocks.apple.com/symbol/NDSN" },
  { id: "471", query: "CBOE", description: "Cboe Global Markets, Inc.", url: "https://stocks.apple.com/symbol/CBOE" },
  { id: "472", query: "TFX", description: "Teleflex Incorporated", url: "https://stocks.apple.com/symbol/TFX" },
  { id: "473", query: "CDAY", description: "Ceridian HCM Holding Inc.", url: "https://stocks.apple.com/symbol/CDAY" },
  { id: "474", query: "QRVO", description: "Qorvo, Inc.", url: "https://stocks.apple.com/symbol/QRVO" },
  { id: "475", query: "FOXA", description: "Fox Corporation", url: "https://stocks.apple.com/symbol/FOXA" },
  { id: "476", query: "FOX", description: "Fox Corporation", url: "https://stocks.apple.com/symbol/FOX" },
  { id: "477", query: "IEX", description: "IDEX Corporation", url: "https://stocks.apple.com/symbol/IEX" },
  { id: "478", query: "SJM", description: "The J. M. Smucker Company", url: "https://stocks.apple.com/symbol/SJM" },
  { id: "479", query: "GRMN", description: "Garmin Ltd.", url: "https://stocks.apple.com/symbol/GRMN" },
  { id: "480", query: "AKAM", description: "Akamai Technologies, Inc.", url: "https://stocks.apple.com/symbol/AKAM" },
  { id: "481", query: "LDOS", description: "Leidos Holdings, Inc.", url: "https://stocks.apple.com/symbol/LDOS" },
  {
    id: "482",
    query: "TTWO",
    description: "Take-Two Interactive Software, Inc.",
    url: "https://stocks.apple.com/symbol/TTWO",
  },
  { id: "483", query: "TYL", description: "Tyler Technologies, Inc.", url: "https://stocks.apple.com/symbol/TYL" },
  { id: "484", query: "TER", description: "Teradyne, Inc.", url: "https://stocks.apple.com/symbol/TER" },
  { id: "485", query: "ABMD", description: "ABIOMED, Inc.", url: "https://stocks.apple.com/symbol/ABMD" },
  { id: "486", query: "TDG", description: "TransDigm Group Incorporated", url: "https://stocks.apple.com/symbol/TDG" },
  { id: "487", query: "GNRC", description: "Generac Holdings Inc.", url: "https://stocks.apple.com/symbol/GNRC" },
  { id: "488", query: "POOL", description: "Pool Corporation", url: "https://stocks.apple.com/symbol/POOL" },
  { id: "489", query: "ULTA", description: "Ulta Beauty, Inc.", url: "https://stocks.apple.com/symbol/ULTA" },
  { id: "490", query: "NDAQ", description: "Nasdaq, Inc.", url: "https://stocks.apple.com/symbol/NDAQ" },
  {
    id: "491",
    query: "EXPD",
    description: "Expeditors International of Washington, Inc.",
    url: "https://stocks.apple.com/symbol/EXPD",
  },
  {
    id: "492",
    query: "MPWR",
    description: "Monolithic Power Systems, Inc.",
    url: "https://stocks.apple.com/symbol/MPWR",
  },
  { id: "493", query: "INCY", description: "Incyte Corporation", url: "https://stocks.apple.com/symbol/INCY" },
  { id: "494", query: "URI", description: "United Rentals, Inc.", url: "https://stocks.apple.com/symbol/URI" },
  { id: "495", query: "DAL", description: "Delta Air Lines, Inc.", url: "https://stocks.apple.com/symbol/DAL" },
  { id: "496", query: "PKI", description: "PerkinElmer, Inc.", url: "https://stocks.apple.com/symbol/PKI" },
  { id: "497", query: "DPZ", description: "Domino's Pizza, Inc.", url: "https://stocks.apple.com/symbol/DPZ" },
  { id: "498", query: "DISH", description: "DISH Network Corporation", url: "https://stocks.apple.com/symbol/DISH" },
  { id: "499", query: "WAT", description: "Waters Corporation", url: "https://stocks.apple.com/symbol/WAT" },
  { id: "500", query: "NTAP", description: "NetApp, Inc.", url: "https://stocks.apple.com/symbol/NTAP" },
];
