interface FileTypeIconMap {
  [key: string]: string;
}

interface FileTypeColorMap {
  [key: string]: string;
}
export const FileTypeIcons: FileTypeIconMap = {
  ".txt": "text",
  ".md": "markdown",
  ".pdf": "pdf",
  ".zip": "archive",
  ".rar": "archive",
  ".7z": "archive",
  ".csv": "spreadsheet",
  ".xlsx": "spreadsheet",
  ".xlsm": "spreadsheet",
  ".xls": "spreadsheet",
  ".json": "code",
  ".doc": "word",
  ".docx": "word",
  ".ppt": "powerpoint",
  ".pptx": "powerpoint",
  ".mp3": "audio",
  ".wav": "audio",
  ".mp4": "video",
  ".avi": "video",
  ".mov": "video",
  ".html": "web",
  ".css": "web",
  ".js": "web",
  ".ts": "web",
  ".php": "code",
  ".py": "code",
  ".java": "code",
  ".c": "code",
  ".cpp": "code",
  ".cs": "code",
  ".rb": "code",
  ".go": "code",
};

export const FileTypeColors: FileTypeColorMap = {
  ".txt": "#1A1AA6",
  ".md": "#6E5494",
  ".pdf": "#FF0000",
  ".csv": "#F1C40F",
  ".xls": "#1D8348",
  ".xlsx": "#1D8348",
  ".doc": "#2E86C1",
  ".docx": "#2E86C1",
  ".ppt": "#E74C3C",
  ".pptx": "#E74C3C",
  ".jpg": "#7D3C98",
  ".jpeg": "#7D3C98",
  ".png": "#F39C12",
  ".gif": "#45B39D",
  ".bmp": "#3498DB",
  ".webp": "#16A085",
  ".zip": "#BA4A00",
  ".rar": "#BA4A00",
  ".tar": "#BA4A00",
  ".gz": "#BA4A00",
  ".7z": "#BA4A00",
  ".mp3": "#2874A6",
  ".wav": "#2874A6",
  ".mp4": "#E67E22",
  ".mkv": "#E67E22",
  ".avi": "#E67E22",
  ".mov": "#E67E22",
  ".js": "#F1C40F",
  ".ts": "#F1C40F",
  ".html": "#E74C3C",
  ".css": "#9B59B6",
};
