// Classify endpoints so auth recovery retries reads, never writes or generation.
export const endpointCatalog = [
  { path: "/v2/get-documents", kind: "read", input: "none" },
  { path: "/v1/get-user-info", kind: "read", input: "none" },
  { path: "/v1/get-document-lists-metadata", kind: "read", input: "none" },
  { path: "/v1/get-document-set", kind: "read", input: "none" },
  { path: "/v1/get-recipes", kind: "read", input: "none" },
  { path: "/v1/get-documents-batch", kind: "read", input: "batch" },
  { path: "/v1/get-document-transcript", kind: "read", input: "note" },
  { path: "/v1/get-document-panels", kind: "read", input: "note" },
  { path: "/v1/get-document-metadata", kind: "read", input: "note" },
  { path: "/v1/get-document-list", kind: "read", input: "folder" },
  { path: "/v1/create-document", kind: "write" },
  { path: "/v1/update-document", kind: "write" },
  { path: "/v1/insert-transcriptions", kind: "write" },
  { path: "/v1/create-document-panel", kind: "write" },
  { path: "/v1/update-document-panel", kind: "write" },
  { path: "/v1/create-document-list-v2", kind: "write" },
  { path: "/v1/delete-document-list-v2", kind: "write" },
  { path: "/v1/add-document-to-list", kind: "write" },
  { path: "/v1/remove-document-from-list", kind: "write" },
  { path: "/v1/save-to-notion", kind: "write" },
  { path: "/v1/refresh-google-events", kind: "write" },
  { path: "/v1/llm-proxy", kind: "generation" },
  { path: "/v1/llm-proxy-stream", kind: "generation", host: "stream.api.granola.ai" },
  { path: "/v1/chat-with-documents", kind: "generation", host: "stream.api.granola.ai" },
  { path: "/user_management/authorize/device", kind: "auth", host: "auth.granola.ai" },
  { path: "/user_management/authenticate", kind: "auth", host: "auth.granola.ai" },
] as const;
