export const NT_BOOKS = [
  "Mat",
  "Mar",
  "Luk",
  "John",
  "Acts",
  "Rom",
  "1Cor",
  "2Cor",
  "Gal",
  "Eph",
  "Phil",
  "Col",
  "1Ths",
  "2Ths",
  "1Tim",
  "2Tim",
  "Tit",
  "Phlm",
  "Heb",
  "Jam",
  "1Pet",
  "2Pet",
  "1Jn",
  "2Jn",
  "3Jn",
  "Jud",
  "Rev",
];

export const OT_BOOKS = [
  "Gen",
  "Exo",
  "Lev",
  "Num",
  "Deu",
  "Josh",
  "Judg",
  "Ruth",
  "1Sam",
  "2Sam",
  "1Kin",
  "2Kin",
  "1Chr",
  "2Chr",
  "Ezr",
  "Neh",
  "Esth",
  "Job",
  "Ps",
  "Prov",
  "Eccl",
  "Song",
  "Isa",
  "Jer",
  "Lam",
  "Ezek",
  "Dan",
  "Hos",
  "Joel",
  "Am",
  "Oba",
  "Jona",
  "Mic",
  "Nah",
  "Hab",
  "Zeph",
  "Hag",
  "Zech",
  "Mal",
];

export const ABBREV_MAP = new Map<string, string>([
  ["Genesis", "Gen"],
  ["Gen", "Gen"],
  ["1 Mose", "Gen"],
  ["1Mose", "Gen"],
  ["1. Mose", "Gen"],
  ["1.Mose", "Gen"],
  ["Exodus", "Exo"],
  ["Exod", "Exo"],
  ["Exo", "Exo"],
  ["2 Mose", "Exo"],
  ["2Mose", "Exo"],
  ["2. Mose", "Exo"],
  ["2.Mose", "Exo"],
  ["Leviticus", "Lev"],
  ["Levit", "Lev"],
  ["Lev", "Lev"],
  ["3 Mose", "Lev"],
  ["3Mose", "Lev"],
  ["3. Mose", "Lev"],
  ["3.Mose", "Lev"],
  ["Numbers", "Num"],
  ["Num", "Num"],
  ["4 Mose", "Num"],
  ["4Mose", "Num"],
  ["4. Mose", "Num"],
  ["4.Mose", "Num"],
  ["Deuteronomy", "Deu"],
  ["Deut", "Deu"],
  ["Deu", "Deu"],
  ["5 Mose", "Deu"],
  ["5Mose", "Deu"],
  ["5. Mose", "Deu"],
  ["5.Mose", "Deu"],
  ["Joshua", "Josh"],
  ["Josh", "Josh"],
  ["Josua", "Josh"],
  ["Jos", "Josh"],
  ["Judges", "Judg"],
  ["Judg", "Judg"],
  ["Richter", "Judg"],
  ["Ri", "Judg"],
  ["Ruth", "Ruth"],
  ["Rut", "Ruth"],
  ["1 Samuel", "1Sam"],
  ["1 Sam", "1Sam"],
  ["1Sam", "1Sam"],
  ["1.Sam", "1Sam"],
  ["1. Sam", "1Sam"],
  ["1Samuel", "1Sam"],
  ["1. Samuel", "1Sam"],
  ["1.Samuel", "1Sam"],
  ["2 Samuel", "2Sam"],
  ["2Samuel", "2Sam"],
  ["2 Sam", "2Sam"],
  ["2. Sam", "2Sam"],
  ["2.Sam", "2Sam"],
  ["2Sam", "2Sam"],
  ["2 Samuel", "2Sam"],
  ["2Samuel", "2Sam"],
  ["2. Samuel", "2Sam"],
  ["2.Samuel", "2Sam"],
  ["1 Kings", "1Kin"],
  ["1 Kgs", "1Kin"],
  ["1Kin", "1Kin"],
  ["1 Kin", "1Kin"],
  ["1Kings", "1Kin"],
  ["1 Könige", "1Kin"],
  ["1Kön", "1Kin"],
  ["1 Kön", "1Kin"],
  ["1. Könige", "1Kin"],
  ["2 Kings", "2Kin"],
  ["2Kings", "2Kin"],
  ["2.Kings", "2Kin"],
  ["2. Kings", "2Kin"],
  ["2 Kgs", "2Kin"],
  ["2Kgs", "2Kin"],
  ["2Kin", "2Kin"],
  ["2 Könige", "2Kin"],
  ["2Kön", "2Kin"],
  ["2 Kön", "2Kin"],
  ["2. Kön", "2Kin"],
  ["2.Kön", "2Kin"],
  ["2 Kön", "2Kin"],
  ["2. Könige", "2Kin"],
  ["1 Chronicles", "1Chr"],
  ["1 Chron", "1Chr"],
  ["1Chr", "1Chr"],
  ["1 Chronik", "1Chr"],
  ["1Chr", "1Chr"],
  ["1. Chronik", "1Chr"],
  ["2 Chronicles", "2Chr"],
  ["2 Chron", "2Chr"],
  ["2Chr", "2Chr"],
  ["2 Chronik", "2Chr"],
  ["2Chr", "2Chr"],
  ["2. Chronik", "2Chr"],
  ["Ezra", "Ezr"],
  ["Ezr", "Ezr"],
  ["Esra", "Ezr"],
  ["Esr", "Ezr"],
  ["Nehemiah", "Neh"],
  ["Neh", "Neh"],
  ["Nehemia", "Neh"],
  ["Esther", "Esth"],
  ["Esth", "Esth"],
  ["Ester", "Esth"],
  ["Job", "Job"],
  ["Hiob", "Job"],
  ["Hi", "Job"],
  ["Psalms", "Ps"],
  ["Psal", "Ps"],
  ["Ps", "Ps"],
  ["Psalm", "Ps"],
  ["Psa", "Ps"],
  ["Proverbs", "Prov"],
  ["Prov", "Prov"],
  ["Sprüche", "Prov"],
  ["Spr", "Prov"],
  ["Ecclesiastes", "Eccl"],
  ["Eccles", "Eccl"],
  ["Eccl", "Eccl"],
  ["Prediger", "Eccl"],
  ["Pred", "Eccl"],
  ["Song of Songs", "Song"],
  ["Song of Solomon", "Song"],
  ["Song", "Song"],
  ["Hohelied", "Song"],
  ["S.S.", "Song"],
  ["SS", "Song"],
  ["S S", "Song"],
  ["S. S.", "Song"],
  ["Hl", "Song"],
  ["Hohel", "Song"],
  ["Isaiah", "Isa"],
  ["Isa", "Isa"],
  ["Jesaja", "Isa"],
  ["Jes", "Isa"],
  ["Jeremiah", "Jer"],
  ["Jer", "Jer"],
  ["Jeremia", "Jer"],
  ["Lamentations", "Lam"],
  ["Lam", "Lam"],
  ["Klagelieder", "Lam"],
  ["Klag", "Lam"],
  ["Ezekiel", "Ezek"],
  ["Ezek", "Ezek"],
  ["Hesekiel", "Ezek"],
  ["Hes", "Ezek"],
  ["Daniel", "Dan"],
  ["Dan", "Dan"],
  ["Daniel", "Dan"],
  ["Da", "Dan"],
  ["Hosea", "Hos"],
  ["Hos", "Hos"],
  ["Hosea", "Hos"],
  ["Joel", "Joel"],
  ["Joel", "Joel"],
  ["Amos", "Am"],
  ["Am", "Am"],
  ["Amos", "Am"],
  ["Obadiah", "Oba"],
  ["Obad", "Oba"],
  ["Oba", "Oba"],
  ["Obadja", "Oba"],
  ["Ob", "Oba"],
  ["Jonah", "Jona"],
  ["Jon", "Jona"],
  ["Jona", "Jona"],
  ["Jonah", "Jona"],
  ["Micah", "Mic"],
  ["Mic", "Mic"],
  ["Micha", "Mic"],
  ["Nahum", "Nah"],
  ["Nah", "Nah"],
  ["Nahum", "Nah"],
  ["Habakkuk", "Hab"],
  ["Hab", "Hab"],
  ["Habakuk", "Hab"],
  ["Zephaniah", "Zeph"],
  ["Zeph", "Zeph"],
  ["Zephanja", "Zeph"],
  ["Haggai", "Hag"],
  ["Hag", "Hag"],
  ["Haggai", "Hag"],
  ["Zechariah", "Zech"],
  ["Zech", "Zech"],
  ["Sacharja", "Zech"],
  ["Sach", "Zech"],
  ["Malachi", "Mal"],
  ["Mal", "Mal"],
  ["Maleachi", "Mal"],
  ["Matthew", "Mat"],
  ["Matt", "Mat"],
  ["Mat", "Mat"],
  ["Matthäus", "Mat"],
  ["Mt", "Mat"],
  ["Mark", "Mar"],
  ["Mk", "Mar"],
  ["Mar", "Mar"],
  ["Markus", "Mar"],
  ["Mk", "Mar"],
  ["Luke", "Luk"],
  ["Lk", "Luk"],
  ["Luk", "Luk"],
  ["Lukas", "Luk"],
  ["Lk", "Luk"],
  ["John", "John"],
  ["Jn", "John"],
  ["Joh", "John"],
  ["Johannes", "John"],
  ["Joh", "John"],
  ["Acts", "Acts"],
  ["Act", "Acts"],
  ["Acts", "Acts"],
  ["Apostelgeschichte", "Acts"],
  ["Apg", "Acts"],
  ["Romans", "Rom"],
  ["Rom", "Rom"],
  ["Römer", "Rom"],
  ["Röm", "Rom"],
  ["1 Corinthians", "1Cor"],
  ["1 Cor", "1Cor"],
  ["1.Cor", "1Cor"],
  ["1. Cor", "1Cor"],
  ["1Cor", "1Cor"],
  ["1 Korinther", "1Cor"],
  ["1Korinther", "1Cor"],
  ["1. Korinther", "1Cor"],
  ["1Kor", "1Cor"],
  ["1 Kor", "1Cor"],
  ["1.Kor", "1Cor"],
  ["1. Kor", "1Cor"],
  ["1. Korinther", "1Cor"],
  ["1.Korinther", "1Cor"],
  ["2 Corinthians", "2Cor"],
  ["2 Cor", "2Cor"],
  ["2Cor", "2Cor"],
  ["2.Cor", "2Cor"],
  ["2. Cor", "2Cor"],
  ["2 Korinther", "2Cor"],
  ["2Korinther", "2Cor"],
  ["2Kor", "2Cor"],
  ["2 Kor", "2Cor"],
  ["2. Korinther", "2Cor"],
  ["2.Korinther", "2Cor"],
  ["Galatians", "Gal"],
  ["Gal", "Gal"],
  ["Galater", "Gal"],
  ["Ephesians", "Eph"],
  ["Ephes", "Eph"],
  ["Eph", "Eph"],
  ["Epheser", "Eph"],
  ["Philippians", "Phil"],
  ["Philip", "Phil"],
  ["Phil", "Phil"],
  ["Philipper", "Phil"],
  ["Colossians", "Col"],
  ["Coloss", "Col"],
  ["Col", "Col"],
  ["Kolosser", "Col"],
  ["Kol", "Col"],
  ["1Thes", "1Ths"],
  ["1Ths", "1Ths"],
  ["1Thess", "1Ths"],
  ["1.Thess", "1Ths"],
  ["1.Ths", "1Ths"],
  ["1.Thes", "1Ths"],
  ["1Thessalonians", "1Ths"],
  ["1Thessalonicher", "1Ths"],
  ["1.Thessalonicher", "1Ths"],
  ["1 Thessalonians", "1Ths"],
  ["1 Thess", "1Ths"],
  ["1. Thess", "1Ths"],
  ["1. Thes", "1Ths"],
  ["1 Thessalonicher", "1Ths"],
  ["1. Thessalonicher", "1Ths"],
  ["2 Thessalonians", "2Ths"],
  ["2 Thessalonicher", "2Ths"],
  ["2. Thessalonicher", "2Ths"],
  ["2Thessalonians", "2Ths"],
  ["2Thessalonicher", "2Ths"],
  ["2.Thessalonicher", "2Ths"],
  ["2 Thess", "2Ths"],
  ["2Thes", "2Ths"],
  ["2Ths", "2Ths"],
  ["2.Thes", "2Ths"],
  ["2.Ths", "2Ths"],
  ["2. Thess", "2Ths"],
  ["2Thess", "2Ths"],
  ["1Tim", "1Tim"],
  ["1Timothy", "1Tim"],
  ["1Timotheus", "1Tim"],
  ["1.Timotheus", "1Tim"],
  ["1 Timothy", "1Tim"],
  ["1 Timotheus", "1Tim"],
  ["1. Timotheus", "1Tim"],
  ["1 Tim", "1Tim"],
  ["2Tim", "2Tim"],
  ["2.Timotheus", "2Tim"],
  ["2Timotheus", "2Tim"],
  ["2Timothy", "2Tim"],
  ["2 Timothy", "2Tim"],
  ["2 Tim", "2Tim"],
  ["2 Timotheus", "2Tim"],
  ["2. Timotheus", "2Tim"],
  ["Titus", "Tit"],
  ["Tit", "Tit"],
  ["Titus", "Tit"],
  ["Philemon", "Phlm"],
  ["Philem", "Phlm"],
  ["Phlm", "Phlm"],
  ["Philemon", "Phlm"],
  ["Hebrews", "Heb"],
  ["Hebr", "Heb"],
  ["Heb", "Heb"],
  ["Hebräer", "Heb"],
  ["Hebr", "Heb"],
  ["James", "Jam"],
  ["Jam", "Jam"],
  ["Jakobus", "Jam"],
  ["Jak", "Jam"],
  ["1 Peter", "1Pet"],
  ["1 Pet", "1Pet"],
  ["1 Petr", "1Pet"],
  ["1 Petrus", "1Pet"],
  ["1. Petrus", "1Pet"],
  ["1Peter", "1Pet"],
  ["1Pet", "1Pet"],
  ["1Petr", "1Pet"],
  ["1Petrus", "1Pet"],
  ["1.Petrus", "1Pet"],
  ["2Pet", "2Pet"],
  ["2Petrus", "2Pet"],
  ["2Petr", "2Pet"],
  ["2Petr", "2Pet"],
  ["2.Petrus", "2Pet"],
  ["2 Pet", "2Pet"],
  ["2 Petrus", "2Pet"],
  ["2 Petr", "2Pet"],
  ["2 Petr", "2Pet"],
  ["2. Petrus", "2Pet"],
  ["1 John", "1Jn"],
  ["1John", "1Jn"],
  ["1 Jn", "1Jn"],
  ["1Joh", "1Jn"],
  ["1 Johannes", "1Jn"],
  ["1 Joh", "1Jn"],
  ["1. Johannes", "1Jn"],
  ["2 John", "2Jn"],
  ["2John", "2Jn"],
  ["2 Jn", "2Jn"],
  ["2Joh", "2Jn"],
  ["2 Johannes", "2Jn"],
  ["2 Joh", "2Jn"],
  ["2. Johannes", "2Jn"],
  ["3 John", "3Jn"],
  ["3John", "3Jn"],
  ["3 Jn", "3Jn"],
  ["3Joh", "3Jn"],
  ["3 Johannes", "3Jn"],
  ["3 Joh", "3Jn"],
  ["3. Johannes", "3Jn"],
  ["Jude", "Jud"],
  ["Jd", "Jud"],
  ["Jud", "Jud"],
  ["Judas", "Jud"],
  ["Revelation", "Rev"],
  ["Revel", "Rev"],
  ["Rev", "Rev"],
  ["Offenbarung", "Rev"],
  ["Offb", "Rev"],
]);

export const RCV_APP_ABBREV_MAP = new Map<string, string>([
  ["Genesis", "Gen"],
  ["Exodus", "Exo"],
  ["Leviticus", "Lev"],
  ["Numbers", "Num"],
  ["Deuteronomy", "Deu"],
  ["Joshua", "Jos"],
  ["Judges", "Jud"],
  ["Ruth", "Rut"],
  ["1 Samuel", "FSa"],
  ["2 Samuel", "SSa"],
  ["1 Kings", "FKi"],
  ["2 Kings", "SKi"],
  ["1 Chronicles", "FCh"],
  ["2 Chronicles", "SCh"],
  ["Ezra", "Ezr"],
  ["Nehemiah", "Neh"],
  ["Esther", "Est"],
  ["Job", "Job"],
  ["Psalms", "Psa"],
  ["Proverbs", "Pro"],
  ["Ecclesiastes", "Ecc"],
  ["Song of Solomon", "Son"],
  ["Isaiah", "Isa"],
  ["Jeremiah", "Jer"],
  ["Lamentations", "Lam"],
  ["Ezekiel", "Eze"],
  ["Daniel", "Dan"],
  ["Hosea", "Hos"],
  ["Joel", "Joe"],
  ["Amos", "Amo"],
  ["Obadiah", "Oba"],
  ["Jonah", "Jon"],
  ["Micah", "Mic"],
  ["Nahum", "Nah"],
  ["Habakkuk", "Hab"],
  ["Zephaniah", "Zep"],
  ["Haggai", "Hag"],
  ["Zechariah", "Zec"],
  ["Malachi", "Mal"],
  ["Matthew", "Mat"],
  ["Mark", "Mar"],
  ["Luke", "Luk"],
  ["John", "Joh"],
  ["Acts", "Act"],
  ["Romans", "Rom"],
  ["1 Corinthians", "FCo"],
  ["2 Corinthians", "SCo"],
  ["Galatians", "Gal"],
  ["Ephesians", "Eph"],
  ["Philippians", "Phi"],
  ["Colossians", "Col"],
  ["1 Thessalonians", "FTh"],
  ["2 Thessalonians", "STh"],
  ["1 Timothy", "FTi"],
  ["2 Timothy", "STi"],
  ["Titus", "Tit"],
  ["Philemon", "Phi"],
  ["Hebrews", "Heb"],
  ["James", "Jam"],
  ["1 Peter", "FPe"],
  ["2 Peter", "SPe"],
  ["1 John", "FJo"],
  ["2 John", "SJo"],
  ["3 John", "TJo"],
  ["Jude", "Jde"],
  ["Revelation", "Rev"],
]);

export const JUBILEE_APP_ABBREV_MAP = new Map<string, string>([
  ["Genesis", "Gen"],
  ["Exodus", "Exo"],
  ["Leviticus", "Lev"],
  ["Numbers", "Num"],
  ["Deuteronomy", "Deu"],
  ["Joshua", "Jos"],
  ["Judges", "Jdg"],
  ["Ruth", "Rut"],
  ["1 Samuel", "1Sa"],
  ["2 Samuel", "2Sa"],
  ["1 Kings", "1Ki"],
  ["2 Kings", "2Ki"],
  ["1 Chronicles", "1Ch"],
  ["2 Chronicles", "2Ch"],
  ["Ezra", "Ezr"],
  ["Nehemiah", "Neh"],
  ["Esther", "Est"],
  ["Job", "Job"],
  ["Psalms", "Psa"],
  ["Proverbs", "Prb"],
  ["Ecclesiastes", "Ecc"],
  ["Song of Solomon", "SoS"],
  ["Isaiah", "Isa"],
  ["Jeremiah", "Jer"],
  ["Lamentations", "Lam"],
  ["Ezekiel", "Ezk"],
  ["Daniel", "Dan"],
  ["Hosea", "Hos"],
  ["Joel", "Joe"],
  ["Amos", "Amo"],
  ["Obadiah", "Oba"],
  ["Jonah", "Jon"],
  ["Micah", "Mic"],
  ["Nahum", "Nah"],
  ["Habakkuk", "Hab"],
  ["Zephaniah", "Zep"],
  ["Haggai", "Hag"],
  ["Zechariah", "Zec"],
  ["Malachi", "Mal"],
  ["Matthew", "Mat"],
  ["Mark", "Mar"],
  ["Luke", "Luk"],
  ["John", "Joh"],
  ["Acts", "Act"],
  ["Romans", "Rom"],
  ["1 Corinthians", "1Co"],
  ["2 Corinthians", "2Co"],
  ["Galatians", "Gal"],
  ["Ephesians", "Eph"],
  ["Philippians", "Phm"],
  ["Colossians", "Col"],
  ["1 Thessalonians", "1Th"],
  ["2 Thessalonians", "2Th"],
  ["1 Timothy", "1Ti"],
  ["2 Timothy", "2Ti"],
  ["Titus", "Tit"],
  ["Philemon", "Phi"],
  ["Hebrews", "Heb"],
  ["James", "Jam"],
  ["1 Peter", "1Pe"],
  ["2 Peter", "2Pe"],
  ["1 John", "1Jo"],
  ["2 John", "2Jo"],
  ["3 John", "3Jo"],
  ["Jude", "Jud"],
  ["Revelation", "Rev"],
]);

export const OBSIDIAN_ABBREV_MAP = new Map<string, string>([
  ["Genesis", "Gen"],
  ["Exodus", "Exo"],
  ["Leviticus", "Lev"],
  ["Numbers", "Num"],
  ["Deuteronomy", "Deut"],
  ["Joshua", "Josh"],
  ["Judges", "Judg"],
  ["Ruth", "Ruth"],
  ["1 Samuel", "1 Sam"],
  ["2 Samuel", "2 Sam"],
  ["1 Kings", "1 Kings"],
  ["2 Kings", "2 Kings"],
  ["1 Chronicles", "1 Chron"],
  ["2 Chronicles", "2 Chron"],
  ["Ezra", "Ezra"],
  ["Nehemiah", "Neh"],
  ["Esther", "Esth"],
  ["Job", "Job"],
  ["Psalms", "Psa"],
  ["Proverbs", "Prov"],
  ["Ecclesiastes", "Eccl"],
  ["Song of Solomon", "SoS"],
  ["S.S", "SoS"],
  ["S.S.", "SoS"],
  ["SS", "SoS"],
  ["Isaiah", "Isa"],
  ["Jeremiah", "Jer"],
  ["Lamentations", "Lam"],
  ["Ezekiel", "Ezek"],
  ["Daniel", "Dan"],
  ["Hosea", "Hosea"],
  ["Joel", "Joel"],
  ["Amos", "Amos"],
  ["Obadiah", "Obad"],
  ["Jonah", "Jonah"],
  ["Micah", "Micah"],
  ["Nahum", "Nah"],
  ["Habakkuk", "Hab"],
  ["Zephaniah", "Zep"],
  ["Haggai", "Hag"],
  ["Zechariah", "Zech"],
  ["Malachi", "Mal"],
  ["Matthew", "Matt"],
  ["Mark", "Mark"],
  ["Luke", "Luke"],
  ["John", "John"],
  ["Acts", "Acts"],
  ["Romans", "Rom"],
  ["1 Corinthians", "1 Cor"],
  ["2 Corinthians", "2 Cor"],
  ["Galatians", "Gal"],
  ["Ephesians", "Eph"],
  ["Philippians", "Phil"],
  ["Colossians", "Col"],
  ["1 Thessalonians", "1 Thes"],
  ["2 Thessalonians", "2 Thes"],
  ["1 Timothy", "1 Tim"],
  ["2 Timothy", "2 Tim"],
  ["Titus", "Titue"],
  ["Philemon", "Philem"],
  ["Hebrews", "Heb"],
  ["James", "James"],
  ["1 Peter", "1 Pet"],
  ["2 Peter", "2 Pet"],
  ["1 John", "1 John"],
  ["2 John", "2 John"],
  ["3 John", "3 John"],
  ["Jude", "Jude"],
  ["Revelation", "Rev"],
]);

export const BOOKS_ABBREV = [...OT_BOOKS, ...NT_BOOKS];

export const MODE = ["OT", "NT", "OT+NT"];

export interface Ref {
  book: string;
  chapterFrom: number | undefined;
  verseFrom: number | undefined;
  chapterTo: number | undefined;
  verseTo: number | undefined;
}

export interface Verse {
  book_number: number;
  book_name: string;
  book_name_long: string;
  chapter: number;
  verse: number;
  text: string;
  footnote?: string;
}

export interface VerseListLoading {
  isLoading: boolean;
  data: Verse[] | undefined;
  permissionView: JSX.Element | undefined;
}

export interface Query {
  filter: string | undefined;
  refs: Ref[] | undefined;
}
export interface QueryAndMode {
  query: Query | undefined;
  // otnt: string;
}
