export default [
  {
    name: "WPKirk-Boilerplate",
    title: "Starter Boilerplate",
    subtitle: "The most used starting point for WP Bones plugins",
    icon: "star.svg",
    shortcut: { modifiers: ["cmd", "shift"], key: "b" },
    keywords: ["starter", "routes"],
  },
  {
    name: "WPKirk-API-Boilerplate",
    title: "API",
    subtitle: "How to create a REST API for WP Bones",
    icon: "api.svg",
    keywords: ["api", "rest", "json", "endpoint", "endpoints"],
  },
  {
    name: "WPKirk-Internationalization-Boilerplate",
    title: "Internationalization",
    subtitle: "How to localize your WP Bones plugin",
    icon: "language.svg",
    keywords: ["internationalization", "localize", "localization", "languages"],
  },
  {
    name: "WPKirk-Mantine-Boilerplate",
    title: "Mantine UI",
    subtitle: "How to use Mantine UI with WP Bones",
    icon: "brand-mantine.svg",
    keywords: ["reactjs", "react", "javascript", "jsx", "components", "mantine", "ui"],
  },
  {
    name: "WPKirk-ReactJS-Boilerplate",
    title: "ReactJS",
    subtitle: "How to use ReactJS with WP Bones",
    icon: "brand-react.svg",
    keywords: ["reactjs", "react", "javascript", "jsx", "components"],
  },
  {
    name: "WPKirk-Routes-Boilerplate",
    title: "Routes",
    subtitle: "How to handle routes for WP Bones",
    icon: "arrow-guide.svg",
    keywords: ["starter", "routes"],
  },
  {
    name: "WPKirk-Database-Boilerplate",
    title: "Database",
    subtitle: "How to manage database in WP Bones",
    icon: "database-cog.svg",
    keywords: [
      "db",
      "database",
      "sql",
      "mysql",
      "mariadb",
      "model",
      "models",
      "table",
      "tables",
      "illuminate",
      "eloquent",
      "query",
      "queries",
      "orm",
      "migration",
      "migrations",
      "seed",
      "seeds",
    ],
  },
];
