const potsByAccount: any = [
  {
    account: {
      id: "acc_1",
      closed: false,
      created: "2017-07-27T17:37:09.515Z",
      description: "user_1",
      type: "uk_retail",
      currency: "GBP",
      country_code: "GB",
      owners: [
        {
          user_id: "user_1",
          preferred_name: "Dan Palmer",
          preferred_first_name: "Dan",
        },
      ],
      account_number: "12345678",
      sort_code: "040004",
      payment_details: {
        locale_uk: { account_number: "12345678", sort_code: "040004" },
      },
    },
    pots: [
      {
        id: "pot_1",
        name: "Bills",
        style: "color_purple",
        balance: 12345,
        currency: "GBP",
        type: "default",
        product_id: "default",
        current_account_id: "acc_1",
        cover_image_url:
          "https://public-images.monzo.com/pots/gallery_covers/purple.png",
        isa_wrapper: "",
        round_up: false,
        round_up_multiplier: null,
        is_tax_pot: false,
        created: "2019-09-26T11:28:27.942Z",
        updated: "2021-06-14T18:50:54.925Z",
        deleted: false,
        locked: false,
        available_for_bills: true,
        has_virtual_cards: false,
      },
      {
        id: "pot_2",
        name: "Savings",
        style: "",
        balance: 111055,
        currency: "GBP",
        goal_amount: 1000000,
        type: "flexible_savings",
        product_id: "Totally_Real_Savings_Account",
        current_account_id: "acc_1",
        cover_image_url:
          "https://public-images.monzo.com/pots/gallery_covers/purple.png",
        isa_wrapper: "",
        round_up: true,
        round_up_multiplier: 1,
        is_tax_pot: false,
        created: "2020-07-25T11:37:37.794Z",
        updated: "2021-06-14T18:49:38.152Z",
        deleted: false,
        locked: false,
        available_for_bills: false,
        has_virtual_cards: false,
      },
    ],
  },
];

const balance: any = {
  balance: 34500,
  total_balance: 123400,
  balance_including_flexible_savings: 123400,
  currency: "GBP",
  spend_today: -1410,
  local_currency: "",
  local_exchange_rate: 0,
  local_spend: [],
};

const transactions: any = [
  {
    id: "tx_1",
    created: "2022-10-08T17:43:29.149Z",
    settled: "2022-10-08T17:43:29.149Z",
    description: "Morrisons",
    amount: -1410,
    fees: {},
    currency: "GBP",
    local_currency: "GBP",
    category: "groceries",
    merchant: {
      id: "merch_1",
      group_id: "grp_1",
      name: "Morrisons",
      logo: "https://mondo-logo-cache.appspot.com/twitter/@Morrisons/?size=large",
      emoji: "🍏",
      category: "groceries",
      online: false,
      atm: false,
      address: {
        short_formatted: "Park Avenue, London, E15 1HP",
        city: "London",
        approximate: false,
        formatted: "Park Avenue, London E15 1HP, United Kingdom",
        address: "Park Avenue, London E15 1HP",
        region: "",
        country: "GBR",
        postcode: "",
      },
      disable_feedback: false,
      suggested_tags: "#groceries #food",
      metadata: {
        suggested_tags: "#groceries #food",
      },
    },
    metadata: { trigger: "" },
  },
  {
    id: "tx_2",
    created: "2022-10-08T13:27:29.149Z",
    settled: "2022-10-08T13:27:29.149Z",
    description: "Morrisons",
    amount: 12000,
    fees: {},
    currency: "GBP",
    local_currency: "GBP",
    category: "holidays",
    note: "✈️ Flights",
    counterparty: { name: "Jenny" },
    scheme: "p2p_payment",
    metadata: { trigger: "", reaction: "🙏" },
  },
  {
    id: "tx_3",
    created: "2022-10-09T07:00:11.479Z",
    description: "pot_1",
    amount: -10000,
    fees: {},
    currency: "GBP",
    merchant: null,
    notes: "",
    metadata: {
      trigger: "ifttt",
      user_id: "user_1",
    },
    labels: null,
    attachments: null,
    international: null,
    category: "savings",
    is_load: false,
    settled: "2022-10-09T07:00:11.479Z",
    local_amount: -282,
    local_currency: "GBP",
    updated: "2022-10-09T07:00:11.956Z",
    account_id: "acc_1",
    user_id: "",
    counterparty: {},
    scheme: "uk_retail_pot",
    dedupe_id: "dedupe-id",
    originator: true,
    include_in_spending: false,
  },
];

export const testData = {
  potsByAccount,
  balance,
  transactions,
};
