import type { ValueRepresentation } from "./types";

export const valueRepresentations: ValueRepresentation[] = [
  "AE",
  "AS",
  "AT",
  "CS",
  "DA",
  "DS",
  "DT",
  "FL",
  "FD",
  "IS",
  "LO",
  "LT",
  "OB",
  "OD",
  "OF",
  "OL",
  "OV",
  "OW",
  "PN",
  "SH",
  "SL",
  "SQ",
  "SS",
  "ST",
  "SV",
  "TM",
  "UC",
  "UI",
  "UL",
  "UN",
  "UR",
  "US",
  "UT",
  "UV",
];

export const valueRepresentationNames: Record<ValueRepresentation, string> = {
  AE: "Application Entity",
  AS: "Age String",
  AT: "Attribute Tag",
  CS: "Code String",
  DA: "Date",
  DS: "Decimal String",
  DT: "Date Time",
  FL: "Floating Point Single",
  FD: "Floating Point Double",
  IS: "Integer String",
  LO: "Long String",
  LT: "Long Text",
  OB: "Other Byte",
  OD: "Other Double",
  OF: "Other Float",
  OL: "Other Long",
  OV: "Other 64-bit Very Long",
  OW: "Other Word",
  PN: "Person Name",
  SH: "Short String",
  SL: "Signed Long",
  SQ: "Sequence of Items",
  SS: "Signed Short",
  ST: "Short Text",
  SV: "Signed 64-bit Very Long",
  TM: "Time",
  UC: "Unlimited Characters",
  UI: "Unique Identifier (UID)",
  UL: "Unsigned Long",
  UN: "Unknown",
  UR: "Universal Resource Identifier or Universal Resource Locator (URI/URL)",
  US: "Unsigned Short",
  UT: "Unlimited Text",
  UV: "Unsigned 64-bit Very Long",
};

export const valueRepresentationDescriptions: Record<ValueRepresentation, string> = {
  AE: "A string of characters that identifies an Application Entity with leading and trailing spaces (20H) being non-significant. A Value consisting solely of spaces shall not be used.",
  AS: "A string of characters with one of the following formats -- nnnD, nnnW, nnnM, nnnY; where nnn shall contain the number of days for D, weeks for W, months for M, or years for Y. Example 018M would represent an age of 18 months.",
  AT: "Ordered pair of 16-bit unsigned integers that is the Value of a Data Element Tag. Example: A Data Element Tag of (0018,00FF) would be encoded as a series of 4 bytes in a Little-Endian Transfer Syntax as 18H,00H,FFH,00H.",
  CS: "A string of characters identifying a controlled concept. Leading or trailing spaces (20H) are not significant.",
  DA: 'A string of characters of the format YYYYMMDD; where YYYY shall contain year, MM shall contain the month, and DD shall contain the day, interpreted as a date of the Gregorian calendar system. Example: "19930822" would represent August 22, 1993.',
  DS: 'A string of characters representing either a fixed point number or a floating point number. A fixed point number shall contain only the characters 0-9 with an optional leading "+" or "-" and an optional "." to mark the decimal point. A floating point number shall be conveyed as defined in ANSI X3.9, with an "E" or "e" to indicate the start of the exponent. Decimal Strings may be padded with leading or trailing spaces. Embedded spaces are not allowed.',
  DT: 'A concatenated date-time character string in the format: YYYYMMDDHHMMSS.FFFFFF&ZZXX. The components of this string, from left to right, are YYYY = Year, MM = Month, DD = Day, HH = Hour (range "00" - "23"), MM = Minute (range "00" - "59"), SS = Second (range "00" - "60"). FFFFFF = Fractional Second contains a fractional part of a second as small as 1 millionth of a second (range "000000" - "999999"). &ZZXX is an optional suffix for offset from Coordinated Universal Time (UTC), where & = "+" or "-", and ZZ = Hours and XX = Minutes of offset. The year, month, and day shall be interpreted as a date of the Gregorian calendar system. A 24-hour clock is used. Midnight shall be represented by only "0000" since "2400" would violate the hour range. The Fractional Second component, if present, shall contain 1 to 6 digits. If Fractional Second is unspecified the preceding "." shall not be included. The offset suffix, if present, shall contain 4 digits. The string may be padded with trailing SPACE characters. Leading and embedded spaces are not allowed. A component that is omitted from the string is termed a null component. Trailing null components of Date Time indicate that the Value is not precise to the precision of those components. The YYYY component shall not be null. Non-trailing null components are prohibited. The optional suffix is not considered as a component. A Date Time Value without the optional suffix is interpreted to be in the local time zone of the application creating the Data Element, unless explicitly specified by the Timezone Offset From UTC (0008,0201). UTC offsets are calculated as "local time minus UTC". The offset for a Date Time Value in UTC shall be +0000.',
  FL: "Single precision binary floating point number represented in IEEE 754:1985 32-bit Floating Point Number Format.",
  FD: "Double precision binary floating point number represented in IEEE 754:1985 64-bit Floating Point Number Format.",
  IS: 'A string of characters representing an Integer in base-10 (decimal), shall contain only the characters 0 - 9, with an optional leading "+" or "-". It may be padded with leading and/or trailing spaces. Embedded spaces are not allowed.',
  LO: 'A character string that may be padded with leading and/or trailing spaces. The character code 5CH (the BACKSLASH "\\" in ISO-IR 6) shall not be present, as it is used as the delimiter between Values in multi-valued Data Elements. The string shall not have Control Characters except for ESC.',
  LT: 'A character string that may contain one or more paragraphs. It may contain the Graphic Character set and the Control Characters, CR, LF, FF, and ESC. It may be padded with trailing spaces, which may be ignored, but leading spaces are considered to be significant. Data Elements with this VR shall not be multi-valued and therefore character code 5CH (the BACKSLASH "\\" in ISO-IR 6) may be used.',
  OB: "An octet-stream where the encoding of the contents is specified by the negotiated Transfer Syntax.",
  OD: "A stream of 64-bit IEEE 754:1985 floating point words.",
  OF: "A stream of 32-bit IEEE 754:1985 floating point words.",
  OL: "A stream of 32-bit words where the encoding of the contents is specified by the negotiated Transfer Syntax.",
  OV: "A stream of 64-bit words where the encoding of the contents is specified by the negotiated Transfer Syntax.",
  OW: "A stream of 16-bit words where the encoding of the contents is specified by the negotiated Transfer Syntax.",
  PN: 'A character string encoded using a 5 component convention. The character code 5CH (the BACKSLASH "\\" in ISO-IR 6) shall not be present, as it is used as the delimiter between Values in multi-valued Data Elements. The string may be padded with trailing spaces. For human use, the five components in their order of occurrence are: family name complex, given name complex, middle name, name prefix, name suffix.',
  SH: 'A character string that may be padded with leading and/or trailing spaces. The character code 05CH (the BACKSLASH "\\" in ISO-IR 6) shall not be present, as it is used as the delimiter between Values for multi-valued Data Elements. The string shall not have Control Characters except ESC.',
  SL: "Signed binary integer 32 bits long in 2's complement form.",
  SQ: "Value is a Sequence of zero or more Items",
  SS: "Signed binary integer 16 bits long in 2's complement form.",
  ST: 'A character string that may contain one or more paragraphs. It may contain the Graphic Character set and the Control Characters, CR, LF, FF, and ESC. It may be padded with trailing spaces, which may be ignored, but leading spaces are considered to be significant. Data Elements with this VR shall not be multi-valued and therefore character code 5CH (the BACKSLASH "\\" in ISO-IR 6) may be used.',
  SV: "Signed binary integer 64 bits long.",
  TM: 'A string of characters of the format HHMMSS.FFFFFF; where HH contains hours (range "00" - "23"), MM contains minutes (range "00" - "59"), SS contains seconds (range "00" - "60"), and FFFFFF contains a fractional part of a second as small as 1 millionth of a second (range "000000" - "999999"). A 24-hour clock is used. Midnight shall be represented by only "0000" since "2400" would violate the hour range. The string may be padded with trailing spaces. Leading and embedded spaces are not allowed. One or more of the components MM, SS, or FFFFFF may be unspecified as long as every component to the right of an unspecified component is also unspecified, which indicates that the Value is not precise to the precision of those unspecified components. The FFFFFF component, if present, shall contain 1 to 6 digits. If FFFFFF is unspecified the preceding "." shall not be included. Examples: 1. "070907.0705 " represents a time of 7 hours, 9 minutes and 7.0705 seconds. 2. "1010" represents a time of 10 hours, and 10 minutes. 3. "021 " is an invalid Value.',
  UC: 'A character string that may be of unlimited length that may be padded with trailing spaces. The character code 5CH (the BACKSLASH "\\" in ISO-IR 6) shall not be present, as it is used as the delimiter between Values in multi-valued Data Elements. The string shall not have Control Characters except for ESC.',
  UI: 'A character string containing a UID that is used to uniquely identify a wide variety of items. The UID is a series of numeric components separated by the period "." character. If a Value Field containing one or more UIDs is an odd number of bytes in length, the Value Field shall be padded with a single trailing NULL (00H) character to ensure that the',
  UL: "Unsigned binary integer 32 bits long.",
  UN: "An octet-stream where the encoding of the contents is unknown",
  UR: "A string of characters that identifies a URI or a URL. Leading spaces are not allowed. Trailing spaces shall be ignored. Data Elements with this VR shall not be multi-valued.",
  US: "Unsigned binary integer 16 bits long.",
  UT: 'A character string that may contain one or more paragraphs. It may contain the Graphic Character set and the Control Characters, CR, LF, FF, and ESC. It may be padded with trailing spaces, which may be ignored, but leading spaces are considered to be significant. Data Elements with this VR shall not be multi-valued and therefore character code 5CH (the BACKSLASH "\\" in ISO-IR 6) may be used.',
  UV: "Unsigned binary integer 64 bits long.",
};
