export const letters = [
  { content: "أ", keywords: ["A", "Aleph"], path: "../assets/items/aleph.svg" },
  { content: "ب", keywords: ["B", "Baa"], path: "../assets/items/baa.svg" },
  { content: "ت", keywords: ["T", "Ta"], path: "../assets/items/taa.svg" },
  { content: "ث", keywords: ["Th", "Thaa"], path: "../assets/items/thaa.svg" },
  { content: "ج", keywords: ["J", "Jeem"], path: "../assets/items/jeem.svg" },
  { content: "ح", keywords: ["H", "Haa"], path: "../assets/items/haa.svg" },
  { content: "خ", keywords: ["KH", "Khaa"], path: "../assets/items/khaa.svg" },
  { content: "د", keywords: ["D", "Daal"], path: "../assets/items/daal.svg" },
  { content: "ذ", keywords: ["DH", "Thaal"], path: "../assets/items/thaal.svg" },
  { content: "ر", keywords: ["R", "Raa"], path: "../assets/items/raa.svg" },
  { content: "ز", keywords: ["Z", "Zaay"], path: "../assets/items/zaay.svg" },
  { content: "س", keywords: ["S", "Seen"], path: "../assets/items/seen.svg" },
  { content: "ش", keywords: ["SH", "Sheen"], path: "../assets/items/sheen.svg" },
  { content: "ص", keywords: ["S", "Saad"], path: "../assets/items/saad.svg" },
  { content: "ض", keywords: ["D", "Daad"], path: "../assets/items/daad.svg" },
  { content: "ط", keywords: ["T", "Taa"], path: "../assets/items/tad.svg" },
  { content: "ظ", keywords: ["Z", "Zaa"], path: "../assets/items/zaa.svg" },
  { content: "ع", keywords: ["A", "Ayn"], path: "../assets/items/ayn.svg" },
  { content: "غ", keywords: ["GH", "Ghayn"], path: "../assets/items/ghayn.svg" },
  { content: "ف", keywords: ["F", "Faa"], path: "../assets/items/faa.svg" },
  { content: "ق", keywords: ["Q", "Qaaf"], path: "../assets/items/qaaf.svg" },
  { content: "ك", keywords: ["K", "Kaaf"], path: "../assets/items/kaaf.svg" },
  { content: "ل", keywords: ["L", "Laam"], path: "../assets/items/laam.svg" },
  { content: "م", keywords: ["M", "Meem"], path: "../assets/items/meem.svg" },
  { content: "ن", keywords: ["N", "Noon"], path: "../assets/items/noon.svg" },
  { content: "ه", keywords: ["H", "Haa"], path: "../assets/items/ha.svg" },
  { content: "و", keywords: ["W", "Waw"], path: "../assets/items/waw.svg" },
  { content: "ي", keywords: ["Y", "Yaa"], path: "../assets/items/yaa.svg" },
];

export const numbers = [
  { content: "٠", keywords: ["0", "Zero"], path: "../assets/items/zero.svg" },
  { content: "١", keywords: ["1", "One"], path: "../assets/items/one.svg" },
  { content: "٢", keywords: ["2", "Two"], path: "../assets/items/two.svg" },
  { content: "٣", keywords: ["3", "Three"], path: "../assets/items/three.svg" },
  { content: "٤", keywords: ["4", "Four"], path: "../assets/items/four.svg" },
  { content: "٥", keywords: ["5", "Five"], path: "../assets/items/five.svg" },
  { content: "٦", keywords: ["6", "Six"], path: "../assets/items/six.svg" },
  { content: "٧", keywords: ["7", "Seven"], path: "../assets/items/seven.svg" },
  { content: "٨", keywords: ["8", "Eight"], path: "../assets/items/eight.svg" },
  { content: "٩", keywords: ["9", "Nine"], path: "../assets/items/nine.svg" },
];
