import { OSINTSource, OSINTCategory } from "../types/osint-types";

export const osintSources: OSINTSource[] = [
  // General Search & Intelligence
  {
    id: "google",
    name: "Google Search",
    category: OSINTCategory.GENERAL,
    url: "https://www.google.com/search?q=",
    description: "Search the web using Google",
    requiresInput: true,
  },
  {
    id: "duckduckgo",
    name: "DuckDuckGo",
    category: OSINTCategory.GENERAL,
    url: "https://duckduckgo.com/?q=",
    description: "Privacy-focused search engine",
    requiresInput: true,
  },
  {
    id: "bing",
    name: "Bing Search",
    category: OSINTCategory.GENERAL,
    url: "https://www.bing.com/search?q=",
    description: "Microsoft's search engine",
    requiresInput: true,
  },

  // Social Media
  {
    id: "twitter",
    name: "Twitter/X Search",
    category: OSINTCategory.SOCIAL_MEDIA,
    url: "https://twitter.com/search?q=",
    description: "Search Twitter/X for posts and users",
    requiresInput: true,
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    category: OSINTCategory.SOCIAL_MEDIA,
    url: "https://www.linkedin.com/search/results/all/?keywords=",
    description: "Search LinkedIn profiles and companies",
    requiresInput: true,
  },
  {
    id: "facebook",
    name: "Facebook Search",
    category: OSINTCategory.SOCIAL_MEDIA,
    url: "https://www.facebook.com/search/top?q=",
    description: "Search Facebook posts and profiles",
    requiresInput: true,
  },
  {
    id: "instagram",
    name: "Instagram",
    category: OSINTCategory.SOCIAL_MEDIA,
    url: "https://www.instagram.com/",
    description: "Search Instagram profiles",
    requiresInput: true,
  },
  {
    id: "reddit",
    name: "Reddit Search",
    category: OSINTCategory.SOCIAL_MEDIA,
    url: "https://www.reddit.com/search?q=",
    description: "Search Reddit posts and comments",
    requiresInput: true,
  },

  // Domain & IP Intelligence
  {
    id: "whois",
    name: "WHOIS Lookup",
    category: OSINTCategory.DOMAIN_IP,
    url: "https://who.is/whois/",
    description: "Domain registration information",
    requiresInput: true,
  },
  {
    id: "virustotal",
    name: "VirusTotal",
    category: OSINTCategory.DOMAIN_IP,
    url: "https://www.virustotal.com/gui/search/",
    description: "Analyze suspicious files, URLs, domains and IPs",
    requiresInput: true,
  },
  {
    id: "shodan",
    name: "Shodan",
    category: OSINTCategory.DOMAIN_IP,
    url: "https://www.shodan.io/search?query=",
    description: "Search engine for Internet-connected devices",
    requiresInput: true,
  },
  {
    id: "censys",
    name: "Censys",
    category: OSINTCategory.DOMAIN_IP,
    url: "https://search.censys.io/search?q=",
    description: "Search engine for Internet-connected devices and certificates",
    requiresInput: true,
  },
  {
    id: "securitytrails",
    name: "SecurityTrails",
    category: OSINTCategory.DOMAIN_IP,
    url: "https://securitytrails.com/domain/",
    description: "Domain and IP history",
    requiresInput: true,
  },
  {
    id: "urlscan",
    name: "URLScan.io",
    category: OSINTCategory.DOMAIN_IP,
    url: "https://urlscan.io/search/#",
    description: "URL scanner and analyzer",
    requiresInput: true,
  },
  {
    id: "webcheck",
    name: "WebCheck",
    category: OSINTCategory.DOMAIN_IP,
    url: "https://web-check.xyz",
    description: "All-in-one website analyzer",
    requiresInput: false,
  },

  // Email Intelligence
  {
    id: "hunter",
    name: "Hunter.io",
    category: OSINTCategory.EMAIL,
    url: "https://hunter.io/search/",
    description: "Find email addresses associated with a domain",
    requiresInput: true,
  },
  {
    id: "emailrep",
    name: "EmailRep",
    category: OSINTCategory.EMAIL,
    url: "https://emailrep.io/",
    description: "Email reputation lookup",
    requiresInput: true,
  },
  {
    id: "haveibeenpwned",
    name: "Have I Been Pwned",
    category: OSINTCategory.EMAIL,
    url: "https://haveibeenpwned.com/",
    description: "Check if email has been in a data breach",
    requiresInput: false,
  },

  // People & Username Search
  {
    id: "pipl",
    name: "Pipl",
    category: OSINTCategory.PEOPLE,
    url: "https://pipl.com/search/?q=",
    description: "People search engine",
    requiresInput: true,
  },
  {
    id: "whitepages",
    name: "Whitepages",
    category: OSINTCategory.PEOPLE,
    url: "https://www.whitepages.com/name/",
    description: "US phone and address lookup",
    requiresInput: true,
  },
  {
    id: "namechk",
    name: "Namechk",
    category: OSINTCategory.PEOPLE,
    url: "https://namechk.com/",
    description: "Check username availability across platforms",
    requiresInput: false,
  },
  {
    id: "sherlock",
    name: "Sherlock Project",
    category: OSINTCategory.PEOPLE,
    url: "https://sherlock-project.github.io/",
    description: "Hunt down social media accounts by username",
    requiresInput: false,
  },

  // Data Breaches & Leaks
  {
    id: "dehashed",
    name: "DeHashed",
    category: OSINTCategory.BREACH_DATA,
    url: "https://dehashed.com/search?query=",
    description: "Search through data breaches",
    requiresInput: true,
  },
  {
    id: "intelx",
    name: "Intelligence X",
    category: OSINTCategory.BREACH_DATA,
    url: "https://intelx.io/",
    description: "Search engine for data breaches and leaks",
    requiresInput: false,
  },
  {
    id: "leakcheck",
    name: "LeakCheck",
    category: OSINTCategory.BREACH_DATA,
    url: "https://leakcheck.io/",
    description: "Data breach search engine",
    requiresInput: false,
  },

  // Code & Developer
  {
    id: "github",
    name: "GitHub Search",
    category: OSINTCategory.CODE,
    url: "https://github.com/search?q=",
    description: "Search GitHub repositories and code",
    requiresInput: true,
  },
  {
    id: "gitlab",
    name: "GitLab Search",
    category: OSINTCategory.CODE,
    url: "https://gitlab.com/search?search=",
    description: "Search GitLab projects",
    requiresInput: true,
  },
  {
    id: "pastebin",
    name: "Pastebin",
    category: OSINTCategory.CODE,
    url: "https://pastebin.com/",
    description: "Search code snippets and pastes",
    requiresInput: false,
  },

  // Geolocation
  {
    id: "google-maps",
    name: "Google Maps",
    category: OSINTCategory.GEOLOCATION,
    url: "https://www.google.com/maps/search/",
    description: "Search locations and places",
    requiresInput: true,
  },
  {
    id: "wigle",
    name: "WiGLE",
    category: OSINTCategory.GEOLOCATION,
    url: "https://wigle.net/",
    description: "Wireless network mapping",
    requiresInput: false,
  },

  // Document & File Search
  {
    id: "google-docs",
    name: "Google Docs Search",
    category: OSINTCategory.DOCUMENTS,
    url: "https://www.google.com/search?q=filetype:pdf+",
    description: "Search for documents using Google",
    requiresInput: true,
  },
  {
    id: "scribd",
    name: "Scribd",
    category: OSINTCategory.DOCUMENTS,
    url: "https://www.scribd.com/search?query=",
    description: "Document sharing platform",
    requiresInput: true,
  },

  // Cryptocurrency
  {
    id: "blockchain",
    name: "Blockchain.com",
    category: OSINTCategory.CRYPTO,
    url: "https://www.blockchain.com/explorer/search?search=",
    description: "Bitcoin blockchain explorer",
    requiresInput: true,
  },
  {
    id: "etherscan",
    name: "Etherscan",
    category: OSINTCategory.CRYPTO,
    url: "https://etherscan.io/search?q=",
    description: "Ethereum blockchain explorer",
    requiresInput: true,
  },

  // Dark Web
  {
    id: "onionscan",
    name: "OnionScan",
    category: OSINTCategory.DARK_WEB,
    url: "https://github.com/s-rah/onionscan",
    description: "Dark web site scanner",
    requiresInput: false,
  },
  {
    id: "ahmia",
    name: "Ahmia",
    category: OSINTCategory.DARK_WEB,
    url: "https://ahmia.fi/search/?q=",
    description: "Search engine for Tor hidden services",
    requiresInput: true,
  },

  // Threat Intelligence
  {
    id: "alienvault",
    name: "AlienVault OTX",
    category: OSINTCategory.THREAT_INTEL,
    url: "https://otx.alienvault.com/browse/global/pulses",
    description: "Open threat intelligence community",
    requiresInput: false,
  },
  {
    id: "threatcrowd",
    name: "ThreatCrowd",
    category: OSINTCategory.THREAT_INTEL,
    url: "https://www.threatcrowd.org/searchApi/v2/domain/report/?domain=",
    description: "Threat intelligence search engine",
    requiresInput: true,
  },
  {
    id: "abuseipdb",
    name: "AbuseIPDB",
    category: OSINTCategory.THREAT_INTEL,
    url: "https://www.abuseipdb.com/check/",
    description: "IP address abuse database",
    requiresInput: true,
  },

  // Images & Visual
  {
    id: "google-images",
    name: "Google Images",
    category: OSINTCategory.IMAGES,
    url: "https://images.google.com/",
    description: "Reverse image search",
    requiresInput: false,
  },
  {
    id: "tineye",
    name: "TinEye",
    category: OSINTCategory.IMAGES,
    url: "https://tineye.com/",
    description: "Reverse image search",
    requiresInput: false,
  },
  {
    id: "yandex-images",
    name: "Yandex Images",
    category: OSINTCategory.IMAGES,
    url: "https://yandex.com/images/",
    description: "Reverse image search",
    requiresInput: false,
  },
];
