import { Contact } from "./contacts-jxa";

// Demo mode flag - set to true for screenshots, false for production
export const DEMO_MODE = false;

export const DEMO_CONTACTS: Contact[] = [
  {
    identifier: "demo-1",
    givenName: "Sarah",
    familyName: "Anderson",
    nickname: "",
    organizationName: "Acme Corporation",
    jobTitle: "Product Manager",
    departmentName: "Product",
    phoneNumbers: [
      { label: "mobile", value: "+1 (555) 123-4567" },
      { label: "work", value: "+1 (555) 987-6543" },
    ],
    emailAddresses: [
      { label: "work", value: "sarah.anderson@acme.com" },
      { label: "home", value: "sarah.a@email.com" },
    ],
    postalAddresses: [
      {
        label: "work",
        street: "123 Innovation Drive",
        city: "San Francisco",
        state: "CA",
        postalCode: "94105",
        country: "United States",
        isoCountryCode: "US",
      },
    ],
    urlAddresses: [{ label: "website", value: "https://sarahanderson.dev" }],
    birthday: "1988-03-15",
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-2",
    givenName: "Michael",
    familyName: "Chen",
    nickname: "Mike",
    organizationName: "TechStart Inc",
    jobTitle: "Software Engineer",
    departmentName: "Engineering",
    phoneNumbers: [{ label: "mobile", value: "+1 (555) 234-5678" }],
    emailAddresses: [{ label: "work", value: "michael.chen@techstart.io" }],
    postalAddresses: [],
    urlAddresses: [{ label: "GitHub", value: "https://github.com/mikechen" }],
    birthday: "1992-07-22",
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-3",
    givenName: "Emily",
    familyName: "Rodriguez",
    nickname: "",
    organizationName: "Creative Studios",
    jobTitle: "UX Designer",
    departmentName: "Design",
    phoneNumbers: [
      { label: "mobile", value: "+1 (555) 345-6789" },
      { label: "home", value: "+1 (555) 111-2222" },
    ],
    emailAddresses: [
      { label: "work", value: "emily@creativestudios.co" },
      { label: "home", value: "emily.rodriguez@gmail.com" },
    ],
    postalAddresses: [
      {
        label: "home",
        street: "456 Oak Avenue, Apt 12",
        city: "Austin",
        state: "TX",
        postalCode: "78701",
        country: "United States",
        isoCountryCode: "US",
      },
    ],
    urlAddresses: [],
    birthday: null,
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-4",
    givenName: "James",
    familyName: "Wilson",
    nickname: "Jim",
    organizationName: "",
    jobTitle: "",
    departmentName: "",
    phoneNumbers: [{ label: "mobile", value: "+1 (555) 456-7890" }],
    emailAddresses: [{ label: "home", value: "james.wilson@outlook.com" }],
    postalAddresses: [],
    urlAddresses: [],
    birthday: "1985-11-30",
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-5",
    givenName: "Olivia",
    familyName: "Martinez",
    nickname: "Liv",
    organizationName: "Global Consulting Group",
    jobTitle: "Senior Consultant",
    departmentName: "Strategy",
    phoneNumbers: [
      { label: "work", value: "+1 (555) 567-8901" },
      { label: "mobile", value: "+1 (555) 333-4444" },
    ],
    emailAddresses: [{ label: "work", value: "o.martinez@globalconsulting.com" }],
    postalAddresses: [
      {
        label: "work",
        street: "789 Business Center Blvd",
        city: "New York",
        state: "NY",
        postalCode: "10001",
        country: "United States",
        isoCountryCode: "US",
      },
      {
        label: "home",
        street: "42 Park Avenue, Apt 15B",
        city: "Brooklyn",
        state: "NY",
        postalCode: "11201",
        country: "United States",
        isoCountryCode: "US",
      },
      {
        label: "vacation",
        street: "1200 Ocean Drive",
        city: "Miami Beach",
        state: "FL",
        postalCode: "33139",
        country: "United States",
        isoCountryCode: "US",
      },
    ],
    urlAddresses: [{ label: "LinkedIn", value: "https://linkedin.com/in/oliviamartinez" }],
    birthday: null,
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-6",
    givenName: "David",
    familyName: "Kim",
    nickname: "",
    organizationName: "Sunrise Coffee",
    jobTitle: "Owner",
    departmentName: "",
    phoneNumbers: [{ label: "work", value: "+1 (555) 678-9012" }],
    emailAddresses: [{ label: "work", value: "david@sunrisecoffee.com" }],
    postalAddresses: [
      {
        label: "work",
        street: "321 Main Street",
        city: "Seattle",
        state: "WA",
        postalCode: "98101",
        country: "United States",
        isoCountryCode: "US",
      },
    ],
    urlAddresses: [],
    birthday: "1979-04-08",
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-7",
    givenName: "Jessica",
    familyName: "Thompson",
    nickname: "Jess",
    organizationName: "HealthFirst Medical",
    jobTitle: "Physician",
    departmentName: "Family Medicine",
    phoneNumbers: [
      { label: "work", value: "+1 (555) 789-0123" },
      { label: "mobile", value: "+1 (555) 555-6666" },
    ],
    emailAddresses: [
      { label: "work", value: "dr.thompson@healthfirst.org" },
      { label: "home", value: "jess.thompson@icloud.com" },
    ],
    postalAddresses: [],
    urlAddresses: [],
    birthday: "1982-09-12",
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-8",
    givenName: "Robert",
    familyName: "Garcia",
    nickname: "Rob",
    organizationName: "",
    jobTitle: "",
    departmentName: "",
    phoneNumbers: [{ label: "mobile", value: "+1 (555) 890-1234" }],
    emailAddresses: [{ label: "home", value: "rob.garcia@yahoo.com" }],
    postalAddresses: [
      {
        label: "home",
        street: "555 Elm Street",
        city: "Denver",
        state: "CO",
        postalCode: "80202",
        country: "United States",
        isoCountryCode: "US",
      },
    ],
    urlAddresses: [],
    birthday: null,
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-9",
    givenName: "Amanda",
    familyName: "Lee",
    nickname: "",
    organizationName: "Bright Future Academy",
    jobTitle: "Principal",
    departmentName: "Administration",
    phoneNumbers: [{ label: "work", value: "+1 (555) 901-2345" }],
    emailAddresses: [{ label: "work", value: "a.lee@brightfutureacademy.edu" }],
    postalAddresses: [],
    urlAddresses: [{ label: "school", value: "https://brightfutureacademy.edu" }],
    birthday: "1975-12-03",
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-10",
    givenName: "Christopher",
    familyName: "Brown",
    nickname: "Chris",
    organizationName: "Brown & Associates Law",
    jobTitle: "Attorney",
    departmentName: "Litigation",
    phoneNumbers: [
      { label: "work", value: "+1 (555) 012-3456" },
      { label: "mobile", value: "+1 (555) 777-8888" },
    ],
    emailAddresses: [
      { label: "work", value: "cbrown@brownlaw.com" },
      { label: "home", value: "chris.brown@gmail.com" },
    ],
    postalAddresses: [
      {
        label: "work",
        street: "100 Legal Plaza, Suite 500",
        city: "Chicago",
        state: "IL",
        postalCode: "60601",
        country: "United States",
        isoCountryCode: "US",
      },
    ],
    urlAddresses: [],
    birthday: "1970-06-25",
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-11",
    givenName: "",
    familyName: "",
    nickname: "",
    organizationName: "Pizza Palace",
    jobTitle: "",
    departmentName: "",
    phoneNumbers: [{ label: "main", value: "+1 (555) 742-9922" }],
    emailAddresses: [{ label: "orders", value: "orders@pizzapalace.com" }],
    postalAddresses: [
      {
        label: "store",
        street: "888 Food Court Way",
        city: "Los Angeles",
        state: "CA",
        postalCode: "90001",
        country: "United States",
        isoCountryCode: "US",
      },
    ],
    urlAddresses: [{ label: "website", value: "https://pizzapalace.com" }],
    birthday: null,
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
  {
    identifier: "demo-12",
    givenName: "Jennifer",
    familyName: "Davis",
    nickname: "Jen",
    organizationName: "Fitness First Gym",
    jobTitle: "Personal Trainer",
    departmentName: "",
    phoneNumbers: [{ label: "mobile", value: "+1 (555) 321-9876" }],
    emailAddresses: [{ label: "work", value: "jen.davis@fitnessfirst.com" }],
    postalAddresses: [],
    urlAddresses: [{ label: "Instagram", value: "https://instagram.com/jentrains" }],
    birthday: "1990-01-18",
    imageDataAvailable: false,
    thumbnailBase64: null,
  },
];
