// AUTO-GENERATED by scripts/raycast/generate.mjs — do not edit.
// Rebuilt from src/data/tools.ts on every `astro build` (and `yarn raycast:gen`).
import type { ToolRun } from '../../src/lib/tools/types';

import { run as r_pangram_checker } from '../../src/lib/tools/pangram-checker';
import { run as r_word_counter } from '../../src/lib/tools/word-counter';
import { run as r_word_frequency } from '../../src/lib/tools/word-frequency';
import { run as r_find_and_replace } from '../../src/lib/tools/find-and-replace';
import { run as r_case_converter } from '../../src/lib/tools/case-converter';
import { run as r_utf8_byte_counter } from '../../src/lib/tools/utf8-byte-counter';
import { run as r_palindrome_checker } from '../../src/lib/tools/palindrome-checker';
import { run as r_reading_time } from '../../src/lib/tools/reading-time';
import { run as r_readability_score } from '../../src/lib/tools/readability-score';
import { run as r_sentence_counter } from '../../src/lib/tools/sentence-counter';
import { run as r_keyword_density } from '../../src/lib/tools/keyword-density';
import { run as r_letter_frequency } from '../../src/lib/tools/letter-frequency';
import { run as r_syllable_counter } from '../../src/lib/tools/syllable-counter';
import { run as r_shannon_entropy } from '../../src/lib/tools/shannon-entropy';
import { run as r_subtitle_cps } from '../../src/lib/tools/subtitle-cps';
import { run as r_text_direction } from '../../src/lib/tools/text-direction';
import { run as r_count_occurrences } from '../../src/lib/tools/count-occurrences';
import { run as r_longest_word_finder } from '../../src/lib/tools/longest-word-finder';
import { run as r_sort_words } from '../../src/lib/tools/sort-words';
import { run as r_swap_words } from '../../src/lib/tools/swap-words';
import { run as r_sort_lines } from '../../src/lib/tools/sort-lines';
import { run as r_add_prefix_suffix } from '../../src/lib/tools/add-prefix-suffix';
import { run as r_line_breaks } from '../../src/lib/tools/line-breaks';
import { run as r_split_text } from '../../src/lib/tools/split-text';
import { run as r_reverse_text } from '../../src/lib/tools/reverse-text';
import { run as r_repeat_text } from '../../src/lib/tools/repeat-text';
import { run as r_shuffle_text } from '../../src/lib/tools/shuffle-text';
import { run as r_truncate_text } from '../../src/lib/tools/truncate-text';
import { run as r_extract_column } from '../../src/lib/tools/extract-column';
import { run as r_acronym_generator } from '../../src/lib/tools/acronym-generator';
import { run as r_extract_lines } from '../../src/lib/tools/extract-lines';
import { run as r_extract_first_word } from '../../src/lib/tools/extract-first-word';
import { run as r_transpose_text } from '../../src/lib/tools/transpose-text';
import { run as r_number_extractor } from '../../src/lib/tools/number-extractor';
import { run as r_hashtag_extractor } from '../../src/lib/tools/hashtag-extractor';
import { run as r_srt_time_shifter } from '../../src/lib/tools/srt-time-shifter';
import { run as r_typo_generator } from '../../src/lib/tools/typo-generator';
import { run as r_reverse_words } from '../../src/lib/tools/reverse-words';
import { run as r_phone_number_extractor } from '../../src/lib/tools/phone-number-extractor';
import { run as r_duplicate_each_line } from '../../src/lib/tools/duplicate-each-line';
import { run as r_reverse_each_word } from '../../src/lib/tools/reverse-each-word';
import { run as r_word_scrambler } from '../../src/lib/tools/word-scrambler';
import { run as r_sentence_splitter } from '../../src/lib/tools/sentence-splitter';
import { run as r_remove_non_ascii } from '../../src/lib/tools/remove-non-ascii';
import { run as r_remove_brackets } from '../../src/lib/tools/remove-brackets';
import { run as r_remove_extra_spaces } from '../../src/lib/tools/remove-extra-spaces';
import { run as r_remove_duplicate_lines } from '../../src/lib/tools/remove-duplicate-lines';
import { run as r_collapse_repeated_lines } from '../../src/lib/tools/collapse-repeated-lines';
import { run as r_remove_empty_lines } from '../../src/lib/tools/remove-empty-lines';
import { run as r_remove_accents } from '../../src/lib/tools/remove-accents';
import { run as r_remove_lines_containing } from '../../src/lib/tools/remove-lines-containing';
import { run as r_remove_characters } from '../../src/lib/tools/remove-characters';
import { run as r_remove_duplicate_words } from '../../src/lib/tools/remove-duplicate-words';
import { run as r_remove_emoji } from '../../src/lib/tools/remove-emoji';
import { run as r_remove_html_tags } from '../../src/lib/tools/remove-html-tags';
import { run as r_remove_punctuation } from '../../src/lib/tools/remove-punctuation';
import { run as r_remove_words } from '../../src/lib/tools/remove-words';
import { run as r_phone_number_formatter } from '../../src/lib/tools/phone-number-formatter';
import { run as r_html_comment_remover } from '../../src/lib/tools/html-comment-remover';
import { run as r_disemvowel } from '../../src/lib/tools/disemvowel';
import { run as r_line_length_filter } from '../../src/lib/tools/line-length-filter';
import { run as r_strip_markdown } from '../../src/lib/tools/strip-markdown';
import { run as r_duplicate_line_finder } from '../../src/lib/tools/duplicate-line-finder';
import { run as r_srt_to_text } from '../../src/lib/tools/srt-to-text';
import { run as r_invisible_character_detector } from '../../src/lib/tools/invisible-character-detector';
import { run as r_remove_numbers } from '../../src/lib/tools/remove-numbers';
import { run as r_remove_urls } from '../../src/lib/tools/remove-urls';
import { run as r_email_quote_stripper } from '../../src/lib/tools/email-quote-stripper';
import { run as r_data_redactor } from '../../src/lib/tools/data-redactor';
import { run as r_dedupe_by_column } from '../../src/lib/tools/dedupe-by-column';
import { run as r_bom_manager } from '../../src/lib/tools/bom-manager';
import { run as r_sdh_stripper } from '../../src/lib/tools/sdh-stripper';
import { run as r_ai_phrase_remover } from '../../src/lib/tools/ai-phrase-remover';
import { run as r_remove_line_numbers } from '../../src/lib/tools/remove-line-numbers';
import { run as r_trim_lines } from '../../src/lib/tools/trim-lines';
import { run as r_remove_quotes } from '../../src/lib/tools/remove-quotes';
import { run as r_remove_duplicate_characters } from '../../src/lib/tools/remove-duplicate-characters';
import { run as r_remove_whitespace } from '../../src/lib/tools/remove-whitespace';
import { run as r_indent_text } from '../../src/lib/tools/indent-text';
import { run as r_insert_blank_lines } from '../../src/lib/tools/insert-blank-lines';
import { run as r_add_line_numbers } from '../../src/lib/tools/add-line-numbers';
import { run as r_json_formatter } from '../../src/lib/tools/json-formatter';
import { run as r_tabs_to_spaces } from '../../src/lib/tools/tabs-to-spaces';
import { run as r_word_wrap } from '../../src/lib/tools/word-wrap';
import { run as r_pad_text } from '../../src/lib/tools/pad-text';
import { run as r_thousands_separator } from '../../src/lib/tools/thousands-separator';
import { run as r_smart_quotes } from '../../src/lib/tools/smart-quotes';
import { run as r_sort_paragraphs } from '../../src/lib/tools/sort-paragraphs';
import { run as r_merge_paragraphs } from '../../src/lib/tools/merge-paragraphs';
import { run as r_markdown_table_generator } from '../../src/lib/tools/markdown-table-generator';
import { run as r_xml_formatter } from '../../src/lib/tools/xml-formatter';
import { run as r_line_ending_converter } from '../../src/lib/tools/line-ending-converter';
import { run as r_justify_text } from '../../src/lib/tools/justify-text';
import { run as r_spoiler_tag_wrapper } from '../../src/lib/tools/spoiler-tag-wrapper';
import { run as r_paragraph_separator } from '../../src/lib/tools/paragraph-separator';
import { run as r_whitespace_visualizer } from '../../src/lib/tools/whitespace-visualizer';
import { run as r_wrap_in_quotes } from '../../src/lib/tools/wrap-in-quotes';
import { run as r_mirror_text } from '../../src/lib/tools/mirror-text';
import { run as r_fancy_text } from '../../src/lib/tools/fancy-text';
import { run as r_normalize_unicode } from '../../src/lib/tools/normalize-unicode';
import { run as r_text_decorations } from '../../src/lib/tools/text-decorations';
import { run as r_upside_down_text } from '../../src/lib/tools/upside-down-text';
import { run as r_zalgo_text } from '../../src/lib/tools/zalgo-text';
import { run as r_leet_speak } from '../../src/lib/tools/leet-speak';
import { run as r_invisible_text } from '../../src/lib/tools/invisible-text';
import { run as r_ascii_box } from '../../src/lib/tools/ascii-box';
import { run as r_text_wave } from '../../src/lib/tools/text-wave';
import { run as r_pig_latin } from '../../src/lib/tools/pig-latin';
import { run as r_fullwidth_text } from '../../src/lib/tools/fullwidth-text';
import { run as r_superscript_generator } from '../../src/lib/tools/superscript-generator';
import { run as r_bubble_text } from '../../src/lib/tools/bubble-text';
import { run as r_small_caps } from '../../src/lib/tools/small-caps';
import { run as r_subscript_generator } from '../../src/lib/tools/subscript-generator';
import { run as r_strikethrough_text } from '../../src/lib/tools/strikethrough-text';
import { run as r_underline_text } from '../../src/lib/tools/underline-text';
import { run as r_ascii85 } from '../../src/lib/tools/ascii85';
import { run as r_base64 } from '../../src/lib/tools/base64';
import { run as r_url_encode } from '../../src/lib/tools/url-encode';
import { run as r_html_entities } from '../../src/lib/tools/html-entities';
import { run as r_encrypt_text } from '../../src/lib/tools/encrypt-text';
import { run as r_hex_converter } from '../../src/lib/tools/hex-converter';
import { run as r_rot13 } from '../../src/lib/tools/rot13';
import { run as r_timestamp_converter } from '../../src/lib/tools/timestamp-converter';
import { run as r_cron_parser } from '../../src/lib/tools/cron-parser';
import { run as r_binary_converter } from '../../src/lib/tools/binary-converter';
import { run as r_morse_code } from '../../src/lib/tools/morse-code';
import { run as r_atbash_cipher } from '../../src/lib/tools/atbash-cipher';
import { run as r_base32 } from '../../src/lib/tools/base32';
import { run as r_char_code_converter } from '../../src/lib/tools/char-code-converter';
import { run as r_nato_alphabet } from '../../src/lib/tools/nato-alphabet';
import { run as r_punycode_converter } from '../../src/lib/tools/punycode-converter';
import { run as r_json_escape } from '../../src/lib/tools/json-escape';
import { run as r_vigenere_cipher } from '../../src/lib/tools/vigenere-cipher';
import { run as r_xor_cipher } from '../../src/lib/tools/xor-cipher';
import { run as r_polybius_square } from '../../src/lib/tools/polybius-square';
import { run as r_rail_fence_cipher } from '../../src/lib/tools/rail-fence-cipher';
import { run as r_bacon_cipher } from '../../src/lib/tools/bacon-cipher';
import { run as r_quoted_printable } from '../../src/lib/tools/quoted-printable';
import { run as r_base58 } from '../../src/lib/tools/base58';
import { run as r_braille_translator } from '../../src/lib/tools/braille-translator';
import { run as r_caesar_cipher } from '../../src/lib/tools/caesar-cipher';
import { run as r_rot47 } from '../../src/lib/tools/rot47';
import { run as r_random_emoji_generator } from '../../src/lib/tools/random-emoji-generator';
import { run as r_passphrase_generator } from '../../src/lib/tools/passphrase-generator';
import { run as r_password_generator } from '../../src/lib/tools/password-generator';
import { run as r_random_string } from '../../src/lib/tools/random-string';
import { run as r_random_number } from '../../src/lib/tools/random-number';
import { run as r_uuid_generator } from '../../src/lib/tools/uuid-generator';
import { run as r_lorem_ipsum } from '../../src/lib/tools/lorem-ipsum';
import { run as r_random_words } from '../../src/lib/tools/random-words';
import { run as r_dice_roller } from '../../src/lib/tools/dice-roller';
import { run as r_mac_address_generator } from '../../src/lib/tools/mac-address-generator';
import { run as r_google_calendar_link } from '../../src/lib/tools/google-calendar-link';
import { run as r_random_date_generator } from '../../src/lib/tools/random-date-generator';
import { run as r_random_ip_generator } from '../../src/lib/tools/random-ip-generator';
import { run as r_random_color_generator } from '../../src/lib/tools/random-color-generator';
import { run as r_ulid_generator } from '../../src/lib/tools/ulid-generator';
import { run as r_password_strength_checker } from '../../src/lib/tools/password-strength-checker';
import { run as r_nanoid_generator } from '../../src/lib/tools/nanoid-generator';
import { run as r_random_username_generator } from '../../src/lib/tools/random-username-generator';
import { run as r_diceware } from '../../src/lib/tools/diceware';
import { run as r_coin_flip } from '../../src/lib/tools/coin-flip';
import { run as r_pin_generator } from '../../src/lib/tools/pin-generator';
import { run as r_repeat_character } from '../../src/lib/tools/repeat-character';
import { run as r_list_to_csv } from '../../src/lib/tools/list-to-csv';
import { run as r_random_picker } from '../../src/lib/tools/random-picker';
import { run as r_reverse_list } from '../../src/lib/tools/reverse-list';
import { run as r_combinations } from '../../src/lib/tools/combinations';
import { run as r_permutation_generator } from '../../src/lib/tools/permutation-generator';
import { run as r_matrix_combinator } from '../../src/lib/tools/matrix-combinator';
import { run as r_list_splitter } from '../../src/lib/tools/list-splitter';
import { run as r_random_team_generator } from '../../src/lib/tools/random-team-generator';
import { run as r_matchmaker } from '../../src/lib/tools/matchmaker';
import { run as r_email_validator } from '../../src/lib/tools/email-validator';
import { run as r_duration_calculator } from '../../src/lib/tools/duration-calculator';
import { run as r_words_to_numbers } from '../../src/lib/tools/words-to-numbers';
import { run as r_fraction_converter } from '../../src/lib/tools/fraction-converter';
import { run as r_number_to_words } from '../../src/lib/tools/number-to-words';
import { run as r_number_sequence } from '../../src/lib/tools/number-sequence';
import { run as r_roman_numerals } from '../../src/lib/tools/roman-numerals';
import { run as r_number_stats } from '../../src/lib/tools/number-stats';
import { run as r_credit_card_validator } from '../../src/lib/tools/credit-card-validator';
import { run as r_byte_unit_converter } from '../../src/lib/tools/byte-unit-converter';
import { run as r_percentage_calculator } from '../../src/lib/tools/percentage-calculator';
import { run as r_temperature_converter } from '../../src/lib/tools/temperature-converter';
import { run as r_base_converter } from '../../src/lib/tools/base-converter';
import { run as r_iban_validator } from '../../src/lib/tools/iban-validator';
import { run as r_gcd_lcm_calculator } from '../../src/lib/tools/gcd-lcm-calculator';
import { run as r_date_difference } from '../../src/lib/tools/date-difference';
import { run as r_prime_checker } from '../../src/lib/tools/prime-checker';
import { run as r_sort_numbers } from '../../src/lib/tools/sort-numbers';
import { run as r_css_formatter } from '../../src/lib/tools/css-formatter';
import { run as r_css_gradient_generator } from '../../src/lib/tools/css-gradient-generator';
import { run as r_sort_json } from '../../src/lib/tools/sort-json';
import { run as r_uuid_decoder } from '../../src/lib/tools/uuid-decoder';
import { run as r_meta_tag_generator } from '../../src/lib/tools/meta-tag-generator';
import { run as r_svg_url_encoder } from '../../src/lib/tools/svg-url-encoder';
import { run as r_email_extractor } from '../../src/lib/tools/email-extractor';
import { run as r_slug_generator } from '../../src/lib/tools/slug-generator';
import { run as r_hash_generator } from '../../src/lib/tools/hash-generator';
import { run as r_color_converter } from '../../src/lib/tools/color-converter';
import { run as r_csv_delimiter } from '../../src/lib/tools/csv-delimiter';
import { run as r_csv_to_json } from '../../src/lib/tools/csv-to-json';
import { run as r_yaml_to_json } from '../../src/lib/tools/yaml-to-json';
import { run as r_ics_generator } from '../../src/lib/tools/ics-generator';
import { run as r_regex_tester } from '../../src/lib/tools/regex-tester';
import { run as r_url_extractor } from '../../src/lib/tools/url-extractor';
import { run as r_csv_to_html_table } from '../../src/lib/tools/csv-to-html-table';
import { run as r_html_table_to_markdown } from '../../src/lib/tools/html-table-to-markdown';
import { run as r_url_query_parser } from '../../src/lib/tools/url-query-parser';
import { run as r_query_string_builder } from '../../src/lib/tools/query-string-builder';
import { run as r_css_minifier } from '../../src/lib/tools/css-minifier';
import { run as r_sql_minifier } from '../../src/lib/tools/sql-minifier';
import { run as r_json_to_env } from '../../src/lib/tools/json-to-env';
import { run as r_user_agent_parser } from '../../src/lib/tools/user-agent-parser';
import { run as r_utm_generator } from '../../src/lib/tools/utm-generator';
import { run as r_whatsapp_link_generator } from '../../src/lib/tools/whatsapp-link-generator';
import { run as r_url_validator } from '../../src/lib/tools/url-validator';
import { run as r_html_to_bbcode } from '../../src/lib/tools/html-to-bbcode';
import { run as r_sql_comment_remover } from '../../src/lib/tools/sql-comment-remover';
import { run as r_robots_txt_generator } from '../../src/lib/tools/robots-txt-generator';
import { run as r_sitemap_generator } from '../../src/lib/tools/sitemap-generator';
import { run as r_csp_generator } from '../../src/lib/tools/csp-generator';
import { run as r_humans_txt_generator } from '../../src/lib/tools/humans-txt-generator';
import { run as r_jwt_decoder } from '../../src/lib/tools/jwt-decoder';
import { run as r_json_flattener } from '../../src/lib/tools/json-flattener';
import { run as r_chmod_calculator } from '../../src/lib/tools/chmod-calculator';
import { run as r_ip_subnet_calculator } from '../../src/lib/tools/ip-subnet-calculator';
import { run as r_contrast_checker } from '../../src/lib/tools/contrast-checker';
import { run as r_css_unit_converter } from '../../src/lib/tools/css-unit-converter';
import { run as r_aspect_ratio_calculator } from '../../src/lib/tools/aspect-ratio-calculator';
import { run as r_mailto_link_generator } from '../../src/lib/tools/mailto-link-generator';
import { run as r_vcard_generator } from '../../src/lib/tools/vcard-generator';
import { run as r_markdown_toc_generator } from '../../src/lib/tools/markdown-toc-generator';
import { run as r_sql_formatter } from '../../src/lib/tools/sql-formatter';
import { run as r_html_formatter } from '../../src/lib/tools/html-formatter';
import { run as r_json_to_typescript } from '../../src/lib/tools/json-to-typescript';
import { run as r_hmac_generator } from '../../src/lib/tools/hmac-generator';
import { run as r_domain_extractor } from '../../src/lib/tools/domain-extractor';
import { run as r_ip_extractor } from '../../src/lib/tools/ip-extractor';
import { run as r_vtt_to_srt } from '../../src/lib/tools/vtt-to-srt';
import { run as r_subtitle_line_wrapper } from '../../src/lib/tools/subtitle-line-wrapper';
import { run as r_ip_converter } from '../../src/lib/tools/ip-converter';
import { run as r_xml_to_json } from '../../src/lib/tools/xml-to-json';
import { run as r_split_camel_case } from '../../src/lib/tools/split-camel-case';
import { run as r_lines_to_html_list } from '../../src/lib/tools/lines-to-html-list';
import { run as r_remove_first_line } from '../../src/lib/tools/remove-first-line';
import { run as r_remove_last_line } from '../../src/lib/tools/remove-last-line';
import { run as r_remove_leading_zeros } from '../../src/lib/tools/remove-leading-zeros';
import { run as r_remove_text_in_brackets } from '../../src/lib/tools/remove-text-in-brackets';
import { run as r_remove_repeated_words } from '../../src/lib/tools/remove-repeated-words';
import { run as r_keep_only_letters } from '../../src/lib/tools/keep-only-letters';
import { run as r_keep_only_numbers } from '../../src/lib/tools/keep-only-numbers';
import { run as r_extract_last_word } from '../../src/lib/tools/extract-last-word';
import { run as r_rotate_lines } from '../../src/lib/tools/rotate-lines';
import { run as r_numbered_list } from '../../src/lib/tools/numbered-list';
import { run as r_bullet_list } from '../../src/lib/tools/bullet-list';
import { run as r_capitalize_sentences } from '../../src/lib/tools/capitalize-sentences';
import { run as r_swap_case } from '../../src/lib/tools/swap-case';
import { run as r_count_words_per_line } from '../../src/lib/tools/count-words-per-line';
import { run as r_duplicate_word_finder } from '../../src/lib/tools/duplicate-word-finder';
import { run as r_cursive_text } from '../../src/lib/tools/cursive-text';
import { run as r_gothic_text } from '../../src/lib/tools/gothic-text';
import { run as r_monospace_text } from '../../src/lib/tools/monospace-text';
import { run as r_double_struck_text } from '../../src/lib/tools/double-struck-text';
import { run as r_clap_text } from '../../src/lib/tools/clap-text';
import { run as r_mocking_case } from '../../src/lib/tools/mocking-case';
import { run as r_squared_text } from '../../src/lib/tools/squared-text';
import { run as r_regional_indicator_text } from '../../src/lib/tools/regional-indicator-text';
import { run as r_spaced_letters } from '../../src/lib/tools/spaced-letters';
import { run as r_sum_numbers } from '../../src/lib/tools/sum-numbers';
import { run as r_factorial_calculator } from '../../src/lib/tools/factorial-calculator';
import { run as r_fibonacci_generator } from '../../src/lib/tools/fibonacci-generator';
import { run as r_multiplication_table } from '../../src/lib/tools/multiplication-table';
import { run as r_percentage_change } from '../../src/lib/tools/percentage-change';
import { run as r_number_to_ordinal } from '../../src/lib/tools/number-to-ordinal';
import { run as r_round_numbers } from '../../src/lib/tools/round-numbers';
import { run as r_even_odd_splitter } from '../../src/lib/tools/even-odd-splitter';
import { run as r_a1z26_cipher } from '../../src/lib/tools/a1z26-cipher';
import { run as r_affine_cipher } from '../../src/lib/tools/affine-cipher';
import { run as r_keyboard_shift_cipher } from '../../src/lib/tools/keyboard-shift-cipher';
import { run as r_base45 } from '../../src/lib/tools/base45';
import { run as r_tap_code } from '../../src/lib/tools/tap-code';
import { run as r_beaufort_cipher } from '../../src/lib/tools/beaufort-cipher';
import { run as r_json_to_xml } from '../../src/lib/tools/json-to-xml';
import { run as r_json_to_csv } from '../../src/lib/tools/json-to-csv';
import { run as r_html_list_to_lines } from '../../src/lib/tools/html-list-to-lines';
import { run as r_markdown_link_extractor } from '../../src/lib/tools/markdown-link-extractor';
import { run as r_env_to_json } from '../../src/lib/tools/env-to-json';
import { run as r_ini_to_json } from '../../src/lib/tools/ini-to-json';
import { run as r_properties_to_json } from '../../src/lib/tools/properties-to-json';
import { run as r_csv_to_sql } from '../../src/lib/tools/csv-to-sql';
import { run as r_css_to_js_object } from '../../src/lib/tools/css-to-js-object';
import { run as r_html_to_jsx } from '../../src/lib/tools/html-to-jsx';
import { run as r_curl_to_code } from '../../src/lib/tools/curl-to-code';
import { run as r_bbcode_to_html } from '../../src/lib/tools/bbcode-to-html';
import { run as r_htaccess_generator } from '../../src/lib/tools/htaccess-generator';
import { run as r_kaomoji_library } from '../../src/lib/tools/kaomoji-library';
import { run as r_rpg_name_generator } from '../../src/lib/tools/rpg-name-generator';

export interface CatalogTool {
  slug: string;
  name: string;
  category: string;
  mode: 'transform' | 'generate';
  run: ToolRun;
}

export const catalog: CatalogTool[] = [
  { slug: "pangram-checker", name: "Pangram checker", category: "Basic tools", mode: "transform", run: r_pangram_checker },
  { slug: "word-counter", name: "Word and character counter", category: "Basic tools", mode: "transform", run: r_word_counter },
  { slug: "word-frequency", name: "Word frequency counter", category: "Basic tools", mode: "transform", run: r_word_frequency },
  { slug: "find-and-replace", name: "Find and replace", category: "Basic tools", mode: "transform", run: r_find_and_replace },
  { slug: "case-converter", name: "Case converter", category: "Basic tools", mode: "transform", run: r_case_converter },
  { slug: "utf8-byte-counter", name: "UTF-8 byte counter", category: "Basic tools", mode: "transform", run: r_utf8_byte_counter },
  { slug: "palindrome-checker", name: "Palindrome checker", category: "Basic tools", mode: "transform", run: r_palindrome_checker },
  { slug: "reading-time", name: "Reading time calculator", category: "Basic tools", mode: "transform", run: r_reading_time },
  { slug: "readability-score", name: "Readability score checker", category: "Basic tools", mode: "transform", run: r_readability_score },
  { slug: "sentence-counter", name: "Sentence counter", category: "Basic tools", mode: "transform", run: r_sentence_counter },
  { slug: "keyword-density", name: "Keyword density checker", category: "Basic tools", mode: "transform", run: r_keyword_density },
  { slug: "letter-frequency", name: "Letter frequency counter", category: "Basic tools", mode: "transform", run: r_letter_frequency },
  { slug: "syllable-counter", name: "Syllable counter", category: "Basic tools", mode: "transform", run: r_syllable_counter },
  { slug: "shannon-entropy", name: "Shannon entropy calculator", category: "Basic tools", mode: "transform", run: r_shannon_entropy },
  { slug: "subtitle-cps", name: "Subtitle reading speed (CPS)", category: "Basic tools", mode: "transform", run: r_subtitle_cps },
  { slug: "text-direction", name: "Text direction detector (LTR/RTL)", category: "Basic tools", mode: "transform", run: r_text_direction },
  { slug: "count-occurrences", name: "Count occurrences", category: "Basic tools", mode: "transform", run: r_count_occurrences },
  { slug: "longest-word-finder", name: "Longest Word Finder", category: "Basic tools", mode: "transform", run: r_longest_word_finder },
  { slug: "sort-words", name: "Sort words", category: "Text manipulation", mode: "transform", run: r_sort_words },
  { slug: "swap-words", name: "Swap words", category: "Text manipulation", mode: "transform", run: r_swap_words },
  { slug: "sort-lines", name: "Sort lines", category: "Text manipulation", mode: "transform", run: r_sort_lines },
  { slug: "add-prefix-suffix", name: "Add prefix and suffix", category: "Text manipulation", mode: "transform", run: r_add_prefix_suffix },
  { slug: "line-breaks", name: "Add or remove line breaks", category: "Text manipulation", mode: "transform", run: r_line_breaks },
  { slug: "split-text", name: "Split text", category: "Text manipulation", mode: "transform", run: r_split_text },
  { slug: "reverse-text", name: "Reverse text", category: "Text manipulation", mode: "transform", run: r_reverse_text },
  { slug: "repeat-text", name: "Repeat text", category: "Text manipulation", mode: "transform", run: r_repeat_text },
  { slug: "shuffle-text", name: "Shuffle text", category: "Text manipulation", mode: "transform", run: r_shuffle_text },
  { slug: "truncate-text", name: "Truncate text", category: "Text manipulation", mode: "transform", run: r_truncate_text },
  { slug: "extract-column", name: "Extract column", category: "Text manipulation", mode: "transform", run: r_extract_column },
  { slug: "acronym-generator", name: "Acronym generator", category: "Text manipulation", mode: "transform", run: r_acronym_generator },
  { slug: "extract-lines", name: "Extract lines", category: "Text manipulation", mode: "transform", run: r_extract_lines },
  { slug: "extract-first-word", name: "Extract first word", category: "Text manipulation", mode: "transform", run: r_extract_first_word },
  { slug: "transpose-text", name: "Transpose text", category: "Text manipulation", mode: "transform", run: r_transpose_text },
  { slug: "number-extractor", name: "Number extractor", category: "Text manipulation", mode: "transform", run: r_number_extractor },
  { slug: "hashtag-extractor", name: "Hashtag extractor", category: "Text manipulation", mode: "transform", run: r_hashtag_extractor },
  { slug: "srt-time-shifter", name: "SRT subtitle time shifter", category: "Text manipulation", mode: "transform", run: r_srt_time_shifter },
  { slug: "typo-generator", name: "Typo generator", category: "Text manipulation", mode: "transform", run: r_typo_generator },
  { slug: "reverse-words", name: "Reverse words", category: "Text manipulation", mode: "transform", run: r_reverse_words },
  { slug: "phone-number-extractor", name: "Phone number extractor", category: "Text manipulation", mode: "transform", run: r_phone_number_extractor },
  { slug: "duplicate-each-line", name: "Duplicate each line", category: "Text manipulation", mode: "transform", run: r_duplicate_each_line },
  { slug: "reverse-each-word", name: "Reverse each word", category: "Text manipulation", mode: "transform", run: r_reverse_each_word },
  { slug: "word-scrambler", name: "Word scrambler", category: "Text manipulation", mode: "transform", run: r_word_scrambler },
  { slug: "sentence-splitter", name: "Sentence splitter", category: "Text manipulation", mode: "transform", run: r_sentence_splitter },
  { slug: "remove-non-ascii", name: "Remove non-ASCII characters", category: "Text cleaning", mode: "transform", run: r_remove_non_ascii },
  { slug: "remove-brackets", name: "Remove brackets", category: "Text cleaning", mode: "transform", run: r_remove_brackets },
  { slug: "remove-extra-spaces", name: "Remove extra spaces", category: "Text cleaning", mode: "transform", run: r_remove_extra_spaces },
  { slug: "remove-duplicate-lines", name: "Remove duplicate lines", category: "Text cleaning", mode: "transform", run: r_remove_duplicate_lines },
  { slug: "collapse-repeated-lines", name: "Collapse repeated lines", category: "Text cleaning", mode: "transform", run: r_collapse_repeated_lines },
  { slug: "remove-empty-lines", name: "Remove empty lines", category: "Text cleaning", mode: "transform", run: r_remove_empty_lines },
  { slug: "remove-accents", name: "Remove accents", category: "Text cleaning", mode: "transform", run: r_remove_accents },
  { slug: "remove-lines-containing", name: "Remove lines containing", category: "Text cleaning", mode: "transform", run: r_remove_lines_containing },
  { slug: "remove-characters", name: "Remove characters", category: "Text cleaning", mode: "transform", run: r_remove_characters },
  { slug: "remove-duplicate-words", name: "Remove duplicate words", category: "Text cleaning", mode: "transform", run: r_remove_duplicate_words },
  { slug: "remove-emoji", name: "Remove emoji", category: "Text cleaning", mode: "transform", run: r_remove_emoji },
  { slug: "remove-html-tags", name: "Remove HTML tags", category: "Text cleaning", mode: "transform", run: r_remove_html_tags },
  { slug: "remove-punctuation", name: "Remove punctuation", category: "Text cleaning", mode: "transform", run: r_remove_punctuation },
  { slug: "remove-words", name: "Remove words", category: "Text cleaning", mode: "transform", run: r_remove_words },
  { slug: "phone-number-formatter", name: "Phone number formatter", category: "Text cleaning", mode: "transform", run: r_phone_number_formatter },
  { slug: "html-comment-remover", name: "Remove HTML comments", category: "Text cleaning", mode: "transform", run: r_html_comment_remover },
  { slug: "disemvowel", name: "Remove vowels", category: "Text cleaning", mode: "transform", run: r_disemvowel },
  { slug: "line-length-filter", name: "Filter lines by length", category: "Text cleaning", mode: "transform", run: r_line_length_filter },
  { slug: "strip-markdown", name: "Strip Markdown", category: "Text cleaning", mode: "transform", run: r_strip_markdown },
  { slug: "duplicate-line-finder", name: "Duplicate line finder", category: "Text cleaning", mode: "transform", run: r_duplicate_line_finder },
  { slug: "srt-to-text", name: "SRT to plain text", category: "Text cleaning", mode: "transform", run: r_srt_to_text },
  { slug: "invisible-character-detector", name: "Invisible character detector", category: "Text cleaning", mode: "transform", run: r_invisible_character_detector },
  { slug: "remove-numbers", name: "Remove numbers", category: "Text cleaning", mode: "transform", run: r_remove_numbers },
  { slug: "remove-urls", name: "Remove URLs", category: "Text cleaning", mode: "transform", run: r_remove_urls },
  { slug: "email-quote-stripper", name: "Email quote stripper", category: "Text cleaning", mode: "transform", run: r_email_quote_stripper },
  { slug: "data-redactor", name: "Data redactor", category: "Text cleaning", mode: "transform", run: r_data_redactor },
  { slug: "dedupe-by-column", name: "Remove duplicate rows by column", category: "Text cleaning", mode: "transform", run: r_dedupe_by_column },
  { slug: "bom-manager", name: "BOM manager (add / remove)", category: "Text cleaning", mode: "transform", run: r_bom_manager },
  { slug: "sdh-stripper", name: "SDH subtitle stripper", category: "Text cleaning", mode: "transform", run: r_sdh_stripper },
  { slug: "ai-phrase-remover", name: "AI phrase remover", category: "Text cleaning", mode: "transform", run: r_ai_phrase_remover },
  { slug: "remove-line-numbers", name: "Remove line numbers", category: "Text cleaning", mode: "transform", run: r_remove_line_numbers },
  { slug: "trim-lines", name: "Trim lines", category: "Text cleaning", mode: "transform", run: r_trim_lines },
  { slug: "remove-quotes", name: "Remove quotes", category: "Text cleaning", mode: "transform", run: r_remove_quotes },
  { slug: "remove-duplicate-characters", name: "Remove duplicate characters", category: "Text cleaning", mode: "transform", run: r_remove_duplicate_characters },
  { slug: "remove-whitespace", name: "Remove whitespace", category: "Text cleaning", mode: "transform", run: r_remove_whitespace },
  { slug: "indent-text", name: "Indent text", category: "Text formatting", mode: "transform", run: r_indent_text },
  { slug: "insert-blank-lines", name: "Insert blank lines", category: "Text formatting", mode: "transform", run: r_insert_blank_lines },
  { slug: "add-line-numbers", name: "Add line numbers", category: "Text formatting", mode: "transform", run: r_add_line_numbers },
  { slug: "json-formatter", name: "JSON formatter & validator", category: "Text formatting", mode: "transform", run: r_json_formatter },
  { slug: "tabs-to-spaces", name: "Tabs to spaces", category: "Text formatting", mode: "transform", run: r_tabs_to_spaces },
  { slug: "word-wrap", name: "Word wrap", category: "Text formatting", mode: "transform", run: r_word_wrap },
  { slug: "pad-text", name: "Pad text", category: "Text formatting", mode: "transform", run: r_pad_text },
  { slug: "thousands-separator", name: "Thousands separator", category: "Text formatting", mode: "transform", run: r_thousands_separator },
  { slug: "smart-quotes", name: "Smart quotes converter", category: "Text formatting", mode: "transform", run: r_smart_quotes },
  { slug: "sort-paragraphs", name: "Sort paragraphs", category: "Text formatting", mode: "transform", run: r_sort_paragraphs },
  { slug: "merge-paragraphs", name: "Merge paragraphs", category: "Text formatting", mode: "transform", run: r_merge_paragraphs },
  { slug: "markdown-table-generator", name: "Markdown table generator", category: "Text formatting", mode: "transform", run: r_markdown_table_generator },
  { slug: "xml-formatter", name: "XML formatter", category: "Text formatting", mode: "transform", run: r_xml_formatter },
  { slug: "line-ending-converter", name: "Line ending converter", category: "Text formatting", mode: "transform", run: r_line_ending_converter },
  { slug: "justify-text", name: "Justify text", category: "Text formatting", mode: "transform", run: r_justify_text },
  { slug: "spoiler-tag-wrapper", name: "Spoiler tag wrapper", category: "Text formatting", mode: "transform", run: r_spoiler_tag_wrapper },
  { slug: "paragraph-separator", name: "Paragraph divider inserter", category: "Text formatting", mode: "transform", run: r_paragraph_separator },
  { slug: "whitespace-visualizer", name: "Whitespace visualizer", category: "Text formatting", mode: "transform", run: r_whitespace_visualizer },
  { slug: "wrap-in-quotes", name: "Wrap in quotes", category: "Text formatting", mode: "transform", run: r_wrap_in_quotes },
  { slug: "mirror-text", name: "Mirror text", category: "Stylish text", mode: "transform", run: r_mirror_text },
  { slug: "fancy-text", name: "Fancy text generator", category: "Stylish text", mode: "transform", run: r_fancy_text },
  { slug: "normalize-unicode", name: "Normalize Unicode text", category: "Stylish text", mode: "transform", run: r_normalize_unicode },
  { slug: "text-decorations", name: "Text decorations", category: "Stylish text", mode: "transform", run: r_text_decorations },
  { slug: "upside-down-text", name: "Upside down text", category: "Stylish text", mode: "transform", run: r_upside_down_text },
  { slug: "zalgo-text", name: "Zalgo glitch text", category: "Stylish text", mode: "transform", run: r_zalgo_text },
  { slug: "leet-speak", name: "Leet speak translator", category: "Stylish text", mode: "transform", run: r_leet_speak },
  { slug: "invisible-text", name: "Invisible text generator", category: "Stylish text", mode: "generate", run: r_invisible_text },
  { slug: "ascii-box", name: "ASCII box generator", category: "Stylish text", mode: "transform", run: r_ascii_box },
  { slug: "text-wave", name: "Text wave generator", category: "Stylish text", mode: "transform", run: r_text_wave },
  { slug: "pig-latin", name: "Pig Latin translator", category: "Stylish text", mode: "transform", run: r_pig_latin },
  { slug: "fullwidth-text", name: "Full-width text generator", category: "Stylish text", mode: "transform", run: r_fullwidth_text },
  { slug: "superscript-generator", name: "Superscript generator", category: "Stylish text", mode: "transform", run: r_superscript_generator },
  { slug: "bubble-text", name: "Bubble text", category: "Stylish text", mode: "transform", run: r_bubble_text },
  { slug: "small-caps", name: "Small caps converter", category: "Stylish text", mode: "transform", run: r_small_caps },
  { slug: "subscript-generator", name: "Subscript generator", category: "Stylish text", mode: "transform", run: r_subscript_generator },
  { slug: "strikethrough-text", name: "Strikethrough text", category: "Stylish text", mode: "transform", run: r_strikethrough_text },
  { slug: "underline-text", name: "Underline text", category: "Stylish text", mode: "transform", run: r_underline_text },
  { slug: "ascii85", name: "Ascii85 encode and decode", category: "Encoding & conversion", mode: "transform", run: r_ascii85 },
  { slug: "base64", name: "Base64 encode and decode", category: "Encoding & conversion", mode: "transform", run: r_base64 },
  { slug: "url-encode", name: "URL encode and decode", category: "Encoding & conversion", mode: "transform", run: r_url_encode },
  { slug: "html-entities", name: "HTML entities encode and decode", category: "Encoding & conversion", mode: "transform", run: r_html_entities },
  { slug: "encrypt-text", name: "Encrypt text with a password", category: "Encoding & conversion", mode: "transform", run: r_encrypt_text },
  { slug: "hex-converter", name: "Hex to text and back", category: "Encoding & conversion", mode: "transform", run: r_hex_converter },
  { slug: "rot13", name: "ROT13 / Caesar cipher", category: "Encoding & conversion", mode: "transform", run: r_rot13 },
  { slug: "timestamp-converter", name: "Unix timestamp converter", category: "Encoding & conversion", mode: "transform", run: r_timestamp_converter },
  { slug: "cron-parser", name: "Cron expression parser", category: "Developer tools", mode: "transform", run: r_cron_parser },
  { slug: "binary-converter", name: "Binary to text and back", category: "Encoding & conversion", mode: "transform", run: r_binary_converter },
  { slug: "morse-code", name: "Morse code translator", category: "Encoding & conversion", mode: "transform", run: r_morse_code },
  { slug: "atbash-cipher", name: "Atbash cipher", category: "Encoding & conversion", mode: "transform", run: r_atbash_cipher },
  { slug: "base32", name: "Base32 encode and decode", category: "Encoding & conversion", mode: "transform", run: r_base32 },
  { slug: "char-code-converter", name: "Character code converter", category: "Encoding & conversion", mode: "transform", run: r_char_code_converter },
  { slug: "nato-alphabet", name: "NATO phonetic alphabet", category: "Encoding & conversion", mode: "transform", run: r_nato_alphabet },
  { slug: "punycode-converter", name: "Punycode converter", category: "Encoding & conversion", mode: "transform", run: r_punycode_converter },
  { slug: "json-escape", name: "JSON string escape and unescape", category: "Encoding & conversion", mode: "transform", run: r_json_escape },
  { slug: "vigenere-cipher", name: "Vigenère cipher", category: "Encoding & conversion", mode: "transform", run: r_vigenere_cipher },
  { slug: "xor-cipher", name: "XOR cipher", category: "Encoding & conversion", mode: "transform", run: r_xor_cipher },
  { slug: "polybius-square", name: "Polybius square", category: "Encoding & conversion", mode: "transform", run: r_polybius_square },
  { slug: "rail-fence-cipher", name: "Rail fence cipher", category: "Encoding & conversion", mode: "transform", run: r_rail_fence_cipher },
  { slug: "bacon-cipher", name: "Bacon cipher", category: "Encoding & conversion", mode: "transform", run: r_bacon_cipher },
  { slug: "quoted-printable", name: "Quoted-printable decoder", category: "Encoding & conversion", mode: "transform", run: r_quoted_printable },
  { slug: "base58", name: "Base58 encode and decode", category: "Encoding & conversion", mode: "transform", run: r_base58 },
  { slug: "braille-translator", name: "Braille translator", category: "Encoding & conversion", mode: "transform", run: r_braille_translator },
  { slug: "caesar-cipher", name: "Caesar cipher", category: "Encoding & conversion", mode: "transform", run: r_caesar_cipher },
  { slug: "rot47", name: "ROT47 cipher", category: "Encoding & conversion", mode: "transform", run: r_rot47 },
  { slug: "random-emoji-generator", name: "Random emoji generator", category: "Random generators", mode: "generate", run: r_random_emoji_generator },
  { slug: "passphrase-generator", name: "Passphrase generator", category: "Random generators", mode: "generate", run: r_passphrase_generator },
  { slug: "password-generator", name: "Password generator", category: "Random generators", mode: "generate", run: r_password_generator },
  { slug: "random-string", name: "Random string generator", category: "Random generators", mode: "generate", run: r_random_string },
  { slug: "random-number", name: "Random number generator", category: "Random generators", mode: "generate", run: r_random_number },
  { slug: "uuid-generator", name: "UUID generator", category: "Random generators", mode: "generate", run: r_uuid_generator },
  { slug: "lorem-ipsum", name: "Lorem ipsum generator", category: "Random generators", mode: "generate", run: r_lorem_ipsum },
  { slug: "random-words", name: "Random word generator", category: "Random generators", mode: "generate", run: r_random_words },
  { slug: "dice-roller", name: "Dice roller & coin flip", category: "Random generators", mode: "generate", run: r_dice_roller },
  { slug: "mac-address-generator", name: "MAC address generator", category: "Random generators", mode: "generate", run: r_mac_address_generator },
  { slug: "google-calendar-link", name: "Google Calendar link generator", category: "Random generators", mode: "generate", run: r_google_calendar_link },
  { slug: "random-date-generator", name: "Random date generator", category: "Random generators", mode: "generate", run: r_random_date_generator },
  { slug: "random-ip-generator", name: "Random IP address generator", category: "Random generators", mode: "generate", run: r_random_ip_generator },
  { slug: "random-color-generator", name: "Random color generator", category: "Random generators", mode: "generate", run: r_random_color_generator },
  { slug: "ulid-generator", name: "ULID generator", category: "Random generators", mode: "generate", run: r_ulid_generator },
  { slug: "password-strength-checker", name: "Password strength checker", category: "Random generators", mode: "transform", run: r_password_strength_checker },
  { slug: "nanoid-generator", name: "Nano ID generator", category: "Random generators", mode: "generate", run: r_nanoid_generator },
  { slug: "random-username-generator", name: "Random username generator", category: "Random generators", mode: "generate", run: r_random_username_generator },
  { slug: "diceware", name: "Diceware passphrase generator", category: "Random generators", mode: "generate", run: r_diceware },
  { slug: "coin-flip", name: "Coin flip", category: "Random generators", mode: "generate", run: r_coin_flip },
  { slug: "pin-generator", name: "PIN generator", category: "Random generators", mode: "generate", run: r_pin_generator },
  { slug: "repeat-character", name: "Repeat character", category: "Random generators", mode: "generate", run: r_repeat_character },
  { slug: "list-to-csv", name: "List to CSV converter", category: "Lists & combinations", mode: "transform", run: r_list_to_csv },
  { slug: "random-picker", name: "Random picker", category: "Lists & combinations", mode: "transform", run: r_random_picker },
  { slug: "reverse-list", name: "Reverse list order", category: "Lists & combinations", mode: "transform", run: r_reverse_list },
  { slug: "combinations", name: "Combination generator", category: "Lists & combinations", mode: "transform", run: r_combinations },
  { slug: "permutation-generator", name: "Permutation generator", category: "Lists & combinations", mode: "transform", run: r_permutation_generator },
  { slug: "matrix-combinator", name: "Cartesian product of lists", category: "Lists & combinations", mode: "transform", run: r_matrix_combinator },
  { slug: "list-splitter", name: "List splitter", category: "Lists & combinations", mode: "transform", run: r_list_splitter },
  { slug: "random-team-generator", name: "Random team generator", category: "Lists & combinations", mode: "transform", run: r_random_team_generator },
  { slug: "matchmaker", name: "Random matchmaker", category: "Lists & combinations", mode: "transform", run: r_matchmaker },
  { slug: "email-validator", name: "Email list validator", category: "Lists & combinations", mode: "transform", run: r_email_validator },
  { slug: "duration-calculator", name: "Duration calculator", category: "Numbers", mode: "transform", run: r_duration_calculator },
  { slug: "words-to-numbers", name: "Words to numbers", category: "Numbers", mode: "transform", run: r_words_to_numbers },
  { slug: "fraction-converter", name: "Fraction converter", category: "Numbers", mode: "transform", run: r_fraction_converter },
  { slug: "number-to-words", name: "Number to words", category: "Numbers", mode: "transform", run: r_number_to_words },
  { slug: "number-sequence", name: "Number sequence generator", category: "Numbers", mode: "generate", run: r_number_sequence },
  { slug: "roman-numerals", name: "Roman numeral converter", category: "Numbers", mode: "transform", run: r_roman_numerals },
  { slug: "number-stats", name: "Sum and number statistics", category: "Numbers", mode: "transform", run: r_number_stats },
  { slug: "credit-card-validator", name: "Credit card number checker", category: "Numbers", mode: "transform", run: r_credit_card_validator },
  { slug: "byte-unit-converter", name: "Byte unit converter", category: "Numbers", mode: "transform", run: r_byte_unit_converter },
  { slug: "percentage-calculator", name: "Percentage calculator", category: "Numbers", mode: "generate", run: r_percentage_calculator },
  { slug: "temperature-converter", name: "Temperature converter", category: "Numbers", mode: "transform", run: r_temperature_converter },
  { slug: "base-converter", name: "Number base converter", category: "Numbers", mode: "transform", run: r_base_converter },
  { slug: "iban-validator", name: "IBAN validator", category: "Numbers", mode: "transform", run: r_iban_validator },
  { slug: "gcd-lcm-calculator", name: "GCD and LCM calculator", category: "Numbers", mode: "transform", run: r_gcd_lcm_calculator },
  { slug: "date-difference", name: "Date difference calculator", category: "Numbers", mode: "generate", run: r_date_difference },
  { slug: "prime-checker", name: "Prime number checker", category: "Numbers", mode: "transform", run: r_prime_checker },
  { slug: "sort-numbers", name: "Sort numbers", category: "Numbers", mode: "transform", run: r_sort_numbers },
  { slug: "css-formatter", name: "CSS formatter", category: "Developer tools", mode: "transform", run: r_css_formatter },
  { slug: "css-gradient-generator", name: "CSS gradient generator", category: "Developer tools", mode: "generate", run: r_css_gradient_generator },
  { slug: "sort-json", name: "Sort JSON", category: "Developer tools", mode: "transform", run: r_sort_json },
  { slug: "uuid-decoder", name: "UUID decoder", category: "Developer tools", mode: "transform", run: r_uuid_decoder },
  { slug: "meta-tag-generator", name: "Meta tag generator", category: "Developer tools", mode: "generate", run: r_meta_tag_generator },
  { slug: "svg-url-encoder", name: "SVG URL encoder", category: "Developer tools", mode: "transform", run: r_svg_url_encoder },
  { slug: "email-extractor", name: "Email extractor", category: "Developer tools", mode: "transform", run: r_email_extractor },
  { slug: "slug-generator", name: "Slug generator", category: "Developer tools", mode: "transform", run: r_slug_generator },
  { slug: "hash-generator", name: "Hash generator", category: "Developer tools", mode: "transform", run: r_hash_generator },
  { slug: "color-converter", name: "Color converter", category: "Developer tools", mode: "transform", run: r_color_converter },
  { slug: "csv-delimiter", name: "Change CSV delimiter", category: "Developer tools", mode: "transform", run: r_csv_delimiter },
  { slug: "csv-to-json", name: "CSV ⇄ JSON converter", category: "Developer tools", mode: "transform", run: r_csv_to_json },
  { slug: "yaml-to-json", name: "YAML ⇄ JSON converter", category: "Developer tools", mode: "transform", run: r_yaml_to_json },
  { slug: "ics-generator", name: "ICS generator", category: "Developer tools", mode: "generate", run: r_ics_generator },
  { slug: "regex-tester", name: "Regex tester", category: "Developer tools", mode: "transform", run: r_regex_tester },
  { slug: "url-extractor", name: "URL extractor", category: "Developer tools", mode: "transform", run: r_url_extractor },
  { slug: "csv-to-html-table", name: "CSV to HTML table", category: "Developer tools", mode: "transform", run: r_csv_to_html_table },
  { slug: "html-table-to-markdown", name: "HTML table to Markdown", category: "Developer tools", mode: "transform", run: r_html_table_to_markdown },
  { slug: "url-query-parser", name: "URL query parser", category: "Developer tools", mode: "transform", run: r_url_query_parser },
  { slug: "query-string-builder", name: "Query string builder", category: "Developer tools", mode: "transform", run: r_query_string_builder },
  { slug: "css-minifier", name: "CSS minifier", category: "Developer tools", mode: "transform", run: r_css_minifier },
  { slug: "sql-minifier", name: "SQL minifier", category: "Developer tools", mode: "transform", run: r_sql_minifier },
  { slug: "json-to-env", name: "JSON to .env converter", category: "Developer tools", mode: "transform", run: r_json_to_env },
  { slug: "user-agent-parser", name: "User-agent parser", category: "Developer tools", mode: "transform", run: r_user_agent_parser },
  { slug: "utm-generator", name: "UTM link generator", category: "Developer tools", mode: "transform", run: r_utm_generator },
  { slug: "whatsapp-link-generator", name: "WhatsApp link generator", category: "Developer tools", mode: "generate", run: r_whatsapp_link_generator },
  { slug: "url-validator", name: "URL validator", category: "Developer tools", mode: "transform", run: r_url_validator },
  { slug: "html-to-bbcode", name: "HTML to BBCode converter", category: "Developer tools", mode: "transform", run: r_html_to_bbcode },
  { slug: "sql-comment-remover", name: "SQL comment remover", category: "Developer tools", mode: "transform", run: r_sql_comment_remover },
  { slug: "robots-txt-generator", name: "Robots.txt generator", category: "Developer tools", mode: "generate", run: r_robots_txt_generator },
  { slug: "sitemap-generator", name: "Sitemap XML generator", category: "Developer tools", mode: "transform", run: r_sitemap_generator },
  { slug: "csp-generator", name: "CSP header generator", category: "Developer tools", mode: "generate", run: r_csp_generator },
  { slug: "humans-txt-generator", name: "Humans.txt generator", category: "Developer tools", mode: "transform", run: r_humans_txt_generator },
  { slug: "jwt-decoder", name: "JWT decoder", category: "Developer tools", mode: "transform", run: r_jwt_decoder },
  { slug: "json-flattener", name: "JSON flattener", category: "Developer tools", mode: "transform", run: r_json_flattener },
  { slug: "chmod-calculator", name: "Chmod calculator", category: "Developer tools", mode: "transform", run: r_chmod_calculator },
  { slug: "ip-subnet-calculator", name: "IP subnet calculator", category: "Developer tools", mode: "transform", run: r_ip_subnet_calculator },
  { slug: "contrast-checker", name: "Contrast checker", category: "Developer tools", mode: "transform", run: r_contrast_checker },
  { slug: "css-unit-converter", name: "CSS unit converter", category: "Developer tools", mode: "transform", run: r_css_unit_converter },
  { slug: "aspect-ratio-calculator", name: "Aspect ratio calculator", category: "Developer tools", mode: "transform", run: r_aspect_ratio_calculator },
  { slug: "mailto-link-generator", name: "Mailto link generator", category: "Developer tools", mode: "generate", run: r_mailto_link_generator },
  { slug: "vcard-generator", name: "vCard generator", category: "Developer tools", mode: "generate", run: r_vcard_generator },
  { slug: "markdown-toc-generator", name: "Markdown TOC generator", category: "Developer tools", mode: "transform", run: r_markdown_toc_generator },
  { slug: "sql-formatter", name: "SQL formatter", category: "Developer tools", mode: "transform", run: r_sql_formatter },
  { slug: "html-formatter", name: "HTML formatter", category: "Developer tools", mode: "transform", run: r_html_formatter },
  { slug: "json-to-typescript", name: "JSON to TypeScript", category: "Developer tools", mode: "transform", run: r_json_to_typescript },
  { slug: "hmac-generator", name: "HMAC generator", category: "Developer tools", mode: "transform", run: r_hmac_generator },
  { slug: "domain-extractor", name: "Domain extractor", category: "Developer tools", mode: "transform", run: r_domain_extractor },
  { slug: "ip-extractor", name: "IP address extractor", category: "Developer tools", mode: "transform", run: r_ip_extractor },
  { slug: "vtt-to-srt", name: "VTT ⇄ SRT converter", category: "Developer tools", mode: "transform", run: r_vtt_to_srt },
  { slug: "subtitle-line-wrapper", name: "Subtitle line wrapper", category: "Developer tools", mode: "transform", run: r_subtitle_line_wrapper },
  { slug: "ip-converter", name: "IP address converter (hex/dec/binary)", category: "Developer tools", mode: "transform", run: r_ip_converter },
  { slug: "xml-to-json", name: "XML to JSON converter", category: "Developer tools", mode: "transform", run: r_xml_to_json },
  { slug: "split-camel-case", name: "Split camelCase", category: "Developer tools", mode: "transform", run: r_split_camel_case },
  { slug: "lines-to-html-list", name: "Lines to HTML list", category: "Developer tools", mode: "transform", run: r_lines_to_html_list },
  { slug: "remove-first-line", name: "Remove first line", category: "Text cleaning", mode: "transform", run: r_remove_first_line },
  { slug: "remove-last-line", name: "Remove last line", category: "Text cleaning", mode: "transform", run: r_remove_last_line },
  { slug: "remove-leading-zeros", name: "Remove leading zeros", category: "Text cleaning", mode: "transform", run: r_remove_leading_zeros },
  { slug: "remove-text-in-brackets", name: "Remove text in brackets", category: "Text cleaning", mode: "transform", run: r_remove_text_in_brackets },
  { slug: "remove-repeated-words", name: "Remove repeated words", category: "Text cleaning", mode: "transform", run: r_remove_repeated_words },
  { slug: "keep-only-letters", name: "Keep only letters", category: "Text cleaning", mode: "transform", run: r_keep_only_letters },
  { slug: "keep-only-numbers", name: "Keep only numbers", category: "Text cleaning", mode: "transform", run: r_keep_only_numbers },
  { slug: "extract-last-word", name: "Extract last word", category: "Text manipulation", mode: "transform", run: r_extract_last_word },
  { slug: "rotate-lines", name: "Rotate lines", category: "Text manipulation", mode: "transform", run: r_rotate_lines },
  { slug: "numbered-list", name: "Numbered list", category: "Text manipulation", mode: "transform", run: r_numbered_list },
  { slug: "bullet-list", name: "Bullet list", category: "Text manipulation", mode: "transform", run: r_bullet_list },
  { slug: "capitalize-sentences", name: "Capitalize sentences", category: "Text manipulation", mode: "transform", run: r_capitalize_sentences },
  { slug: "swap-case", name: "Case swapper", category: "Text manipulation", mode: "transform", run: r_swap_case },
  { slug: "count-words-per-line", name: "Count words per line", category: "Basic tools", mode: "transform", run: r_count_words_per_line },
  { slug: "duplicate-word-finder", name: "Duplicate word finder", category: "Basic tools", mode: "transform", run: r_duplicate_word_finder },
  { slug: "cursive-text", name: "Cursive text", category: "Stylish text", mode: "transform", run: r_cursive_text },
  { slug: "gothic-text", name: "Gothic text", category: "Stylish text", mode: "transform", run: r_gothic_text },
  { slug: "monospace-text", name: "Monospace text", category: "Stylish text", mode: "transform", run: r_monospace_text },
  { slug: "double-struck-text", name: "Double-struck text", category: "Stylish text", mode: "transform", run: r_double_struck_text },
  { slug: "clap-text", name: "Clap text", category: "Stylish text", mode: "transform", run: r_clap_text },
  { slug: "mocking-case", name: "Mocking case", category: "Stylish text", mode: "transform", run: r_mocking_case },
  { slug: "squared-text", name: "Squared text", category: "Stylish text", mode: "transform", run: r_squared_text },
  { slug: "regional-indicator-text", name: "Regional indicator text", category: "Stylish text", mode: "transform", run: r_regional_indicator_text },
  { slug: "spaced-letters", name: "Spaced letters", category: "Stylish text", mode: "transform", run: r_spaced_letters },
  { slug: "sum-numbers", name: "Sum numbers", category: "Numbers", mode: "transform", run: r_sum_numbers },
  { slug: "factorial-calculator", name: "Factorial calculator", category: "Numbers", mode: "generate", run: r_factorial_calculator },
  { slug: "fibonacci-generator", name: "Fibonacci generator", category: "Numbers", mode: "generate", run: r_fibonacci_generator },
  { slug: "multiplication-table", name: "Multiplication table", category: "Numbers", mode: "generate", run: r_multiplication_table },
  { slug: "percentage-change", name: "Percentage change", category: "Numbers", mode: "generate", run: r_percentage_change },
  { slug: "number-to-ordinal", name: "Number to ordinal", category: "Numbers", mode: "transform", run: r_number_to_ordinal },
  { slug: "round-numbers", name: "Round numbers", category: "Numbers", mode: "transform", run: r_round_numbers },
  { slug: "even-odd-splitter", name: "Even / odd splitter", category: "Numbers", mode: "transform", run: r_even_odd_splitter },
  { slug: "a1z26-cipher", name: "A1Z26 cipher", category: "Encoding & conversion", mode: "transform", run: r_a1z26_cipher },
  { slug: "affine-cipher", name: "Affine cipher", category: "Encoding & conversion", mode: "transform", run: r_affine_cipher },
  { slug: "keyboard-shift-cipher", name: "Keyboard shift cipher", category: "Encoding & conversion", mode: "transform", run: r_keyboard_shift_cipher },
  { slug: "base45", name: "Base45 encoder", category: "Encoding & conversion", mode: "transform", run: r_base45 },
  { slug: "tap-code", name: "Tap code", category: "Encoding & conversion", mode: "transform", run: r_tap_code },
  { slug: "beaufort-cipher", name: "Beaufort cipher", category: "Encoding & conversion", mode: "transform", run: r_beaufort_cipher },
  { slug: "json-to-xml", name: "JSON to XML converter", category: "Developer tools", mode: "transform", run: r_json_to_xml },
  { slug: "json-to-csv", name: "JSON to CSV converter", category: "Developer tools", mode: "transform", run: r_json_to_csv },
  { slug: "html-list-to-lines", name: "HTML list to lines", category: "Developer tools", mode: "transform", run: r_html_list_to_lines },
  { slug: "markdown-link-extractor", name: "Markdown link extractor", category: "Developer tools", mode: "transform", run: r_markdown_link_extractor },
  { slug: "env-to-json", name: "Env to JSON", category: "Developer tools", mode: "transform", run: r_env_to_json },
  { slug: "ini-to-json", name: "INI ⇄ JSON converter", category: "Developer tools", mode: "transform", run: r_ini_to_json },
  { slug: "properties-to-json", name: "Properties to JSON converter", category: "Developer tools", mode: "transform", run: r_properties_to_json },
  { slug: "csv-to-sql", name: "CSV to SQL INSERT generator", category: "Developer tools", mode: "transform", run: r_csv_to_sql },
  { slug: "css-to-js-object", name: "CSS to JS object converter", category: "Developer tools", mode: "transform", run: r_css_to_js_object },
  { slug: "html-to-jsx", name: "HTML to JSX converter", category: "Developer tools", mode: "transform", run: r_html_to_jsx },
  { slug: "curl-to-code", name: "cURL to code converter", category: "Developer tools", mode: "transform", run: r_curl_to_code },
  { slug: "bbcode-to-html", name: "BBCode to HTML converter", category: "Developer tools", mode: "transform", run: r_bbcode_to_html },
  { slug: "htaccess-generator", name: ".htaccess generator", category: "Developer tools", mode: "generate", run: r_htaccess_generator },
  { slug: "kaomoji-library", name: "Kaomoji library", category: "Stylish text", mode: "generate", run: r_kaomoji_library },
  { slug: "rpg-name-generator", name: "RPG name generator", category: "Random generators", mode: "generate", run: r_rpg_name_generator },
];
