export const LANGUAGE_STRINGS = [
  "English [en]",
  "Unknown language",
  "Spanish [es]",
  "Italian [it]",
  "French [fr]",
  "Chinese [zh]",
  "Dutch [nl]",
  "Portuguese [pt]",
  "Russian [ru]",
  "German [de]",
  "Hungarian [hu]",
  "Romanian [ro]",
  "Afrikaans [af]",
  "Vietnamese [vi]",
  "Greek [el]",
  "Ukrainian [uk]",
  "Catalan [ca]",
  "Latin [la]",
  "Czech [cs]",
  "Japanese [ja]",
  "Flemish [nl‑BE]",
  "Ndolo [ndl]",
  "Polish [pl]",
  "Croatian [hr]",
  "Turkish [tr]",
  "Danish [da]",
  "Serbian [sr]",
  "Unknown language [und]",
  "Luxembourgish [lb]",
  "Hindi [hi]",
  "Bulgarian [bg]",
  "Unknown language [us]",
  "Indonesian [id]",
  "Arabic [ar]",
  "Latvian [lv]",
  "Dongxiang [sce]",
  "Welsh [cy]",
  "Belarusian [be]",
  "Korean [ko]",
  "Lithuanian [lt]",
  "Bangla [bn]",
  "Irish [ga]",
  "Swedish [sv]",
  "Traditional Chinese [zh‑Hant]",
  "Hebrew [he]",
  "Persian [fa]",
  "Urdu [ur]",
  "Norwegian [no]",
  "Kazakh [kk]",
  "Tamil [ta]",
];

export const FILE_TYPES = [
  "pdf",
  "epub",
  "zip",
  "mobi",
  "fb2",
  "cbr",
  "cbz",
  "txt",
  "djvu",
  "azw3",
  "doc",
  "lit",
  "rtf",
  "rar",
  "htm",
  "html",
  "docx",
  "mht",
  "lrf",
  "jpg",
  "chm",
  "azw",
  "pdb",
  "odt",
  "ppt",
  "kfx",
  "xls",
  "xlsx",
  "json",
  "prc",
  "tar",
  "tif",
  "snb",
  "updb",
  "htmlz",
  "7z",
  "cb7",
  "gz",
  "pptx",
  "exe",
  "ai",
  "fb2.zip",
] as const;

export type FileType = (typeof FILE_TYPES)[number];

export const DOC_TYPES = [
  "Book (non-fiction)",
  "Book (fiction)",
  "Book (unknown)",
  "Journal article",
  "Comic book",
  "Magazine",
  "Standards document",
];

export const MIRROR_LIST = [
  "https://annas-archive.gl",
  "https://annas-archive.pk",
  "https://annas-archive.vg",
  "https://annas-archive.gd",
] as const;

export const DEFAULT_MIRROR = "https://annas-archive.gl";

export const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36";
