export const languageStrings = [
  "English [en]",
  "Unknown language",
  "Spanish [es]",
  "Italian [it]",
  "French [fr]",
  "Chinese [zh]",
  "Dutch [nl]",
  "Portuguese [pt]",
  "Russian [ru]",
  "German [de]",
  "Hungarian [hu]",
  "Romanian [ro]",
  "Afrikaans [af]",
  "Vietnamese [vi]",
  "Greek [el]",
  "Ukrainian [uk]",
  "Catalan [ca]",
  "Latin [la]",
  "Czech [cs]",
  "Japanese [ja]",
  "Flemish [nl‑BE]",
  "Ndolo [ndl]",
  "Polish [pl]",
  "Croatian [hr]",
  "Turkish [tr]",
  "Danish [da]",
  "Serbian [sr]",
  "Unknown language [und]",
  "Luxembourgish [lb]",
  "Hindi [hi]",
  "Bulgarian [bg]",
  "Unknown language [us]",
  "Indonesian [id]",
  "Arabic [ar]",
  "Latvian [lv]",
  "Dongxiang [sce]",
  "Welsh [cy]",
  "Belarusian [be]",
  "Korean [ko]",
  "Lithuanian [lt]",
  "Bangla [bn]",
  "Irish [ga]",
  "Swedish [sv]",
  "Traditional Chinese [zh‑Hant]",
  "Hebrew [he]",
  "Persian [fa]",
  "Urdu [ur]",
  "Norwegian [no]",
  "Kazakh [kk]",
  "Tamil [ta]",
];

export const fileTypes = ["pdf", "epub", "cbr", "mobi", "fb2", "cbz", "azw3", "djvu", "fb2.zip", "rar", "zip"];

export const docTypes = [
  "Book (non-fiction)",
  "Book (fiction)",
  "Book (unknown)",
  "Journal article",
  "Comic book",
  "Magazine",
  "Standards document",
];
