import type { FlipFrame } from "./types";

export const FLIP_FRAMES: FlipFrame[] = [
  { row: 6, shadow: "______", symbol: "◉" },
  { row: 5, shadow: "_____", symbol: "◍" },
  { row: 4, shadow: "____", symbol: "◉" },
  { row: 3, shadow: "___", symbol: "▮" },
  { row: 2, shadow: "__", symbol: "│" },
  { row: 1, shadow: "_", symbol: "▮" },
  { row: 2, shadow: "__", symbol: "│" },
  { row: 3, shadow: "___", symbol: "▮" },
  { row: 4, shadow: "____", symbol: "◉" },
  { row: 5, shadow: "_____", symbol: "◍" },
  { row: 6, shadow: "______", symbol: "◉" },
];

export const FLIP_LABEL_BANK = [
  "Throwing caution away",
  "Leaving mortal concerns",
  "Reaching the sun",
  "Consulting destiny",
  "Defying gravity politely",
  "Peaking dramatically",
  "Returning from orbit",
  "Negotiating with fate",
  "Falling with style",
  "Preparing the verdict",
  "Borrowing luck briefly",
  "Ignoring several laws of physics",
  "Making suspense expensive",
  "Asking the universe nicely",
  "Orbiting tiny decisions",
  "Building unnecessary tension",
  "Flirting with chaos",
  "Keeping statisticians nervous",
  "Gathering cinematic energy",
  "Dramatizing probability",
  "Testing the boundaries of fate",
  "Playing with the cosmos",
  "Turning chance into art",
  "Inviting randomness",
  "Dancing with destiny",
  "Embracing uncertainty",
  "Exploring the unknown",
  "Navigating the uncharted",
  "Charting the unpredictable",
  "Taming the chaos",
  "Mastering the randomness",
  "Conquering the unknown",
  "Overcoming the uncharted",
  "Triumphing over the unpredictable",
  "Defeating the chaos",
  "Mastering the chaos",
  "OMG! What a toss!",
  "What a toss!",
  "Really? Use a real coin next time.",
  "Magic greatness!",
  "Amazing toss!",
  "A bit of luck?",
  "I'm not sure about that.",
  "Good luck next time.",
  "That's a tough one.",
  "Gonna have luck?",
];

export const FRAME_DURATION_MS = 85;
export const COIN_ROWS = 7;
export const FLIP_DURATION_MS = FLIP_FRAMES.length * FRAME_DURATION_MS;
export const LABEL_HOLD_FRAMES = 2;
