export const LABEL_BANK = [
  "Throwing caution away",
  "Leaving mortal concerns",
  "Reaching the sun",
  "Consulting destiny",
  "Defying gravity politely",
  "Peaking dramatically",
  "Returning from orbit",
  "Negotiating with fate",
  "Falling with style",
  "Preparing the verdict",
  "Borrowing luck briefly",
  "Ignoring several laws of physics",
  "Making suspense expensive",
  "Asking the universe nicely",
  "Orbiting tiny decisions",
  "Building unnecessary tension",
  "Flirting with chaos",
  "Keeping statisticians nervous",
  "Gathering cinematic energy",
  "Dramatizing probability",
  "Testing the boundaries of fate",
  "Playing with the cosmos",
  "Turning chance into art",
  "Inviting randomness",
  "Dancing with destiny",
  "Embracing uncertainty",
  "Exploring the unknown",
  "Navigating the uncharted",
  "Charting the unpredictable",
  "Taming the chaos",
  "Mastering the randomness",
  "Conquering the unknown",
  "Overcoming the uncharted",
  "Triumphing over the unpredictable",
  "Defeating the chaos",
  "Mastering the chaos",
  "OMG! What an action!",
  "What an action!",
  "Really? Use a real item next time.",
  "Magic greatness!",
  "Amazing throw!",
  "A bit of luck?",
  "I'm not sure about that.",
  "Good luck next time.",
  "That's a tough one.",
  "Gonna have luck?",
];
