export const TAGS = {
  // Header
  BEGIN_STRING: 8,
  BODY_LENGTH: 9,
  MSG_TYPE: 35,
  SENDER_COMP_ID: 49,
  TARGET_COMP_ID: 56,
  MSG_SEQ_NUM: 34,
  SENDING_TIME: 52,
  ON_BEHALF_OF_COMP_ID: 115,
  DELIVER_TO_COMP_ID: 128,
  SECURE_DATA_LEN: 90,
  SECURE_DATA: 91,
  ENCRYPT_METHOD: 98,
  HEART_BT_INT: 108,
  RESET_SEQ_NUM_FLAG: 141,
  MSG_ENCODING: 347,
  LAST_MSG_SEQ_NUM_PROCESSED: 369,
  NO_HOPS: 627,

  // Trailer
  CHECK_SUM: 10,
  SIGNATURE: 89,
  SIGNATURE_LENGTH: 93,

  // Common Body Tags
  ACCOUNT: 1,
  AVG_PX: 6,
  CL_ORD_ID: 11,
  EXEC_ID: 17,
  LAST_PX: 31,
  ORDER_ID: 37,
  ORD_STATUS: 39,
  ORIG_CL_ORD_ID: 41,
  PRICE: 44,
  SIDE: 54,
  TRANSACT_TIME: 60,
  SECONDARY_ORDER_ID: 198,
  SYMBOL: 55,
  ORDER_QTY: 38,
  CUM_QTY: 14,
  LEAVES_QTY: 151,
  TEXT: 58,
};

export const MSG_TYPE = {
  HEARTBEAT: "0",
  TEST_REQUEST: "1",
  LOGON: "A",
  LOGOUT: "5",
  REJECT: "3",
  BUSINESS_MESSAGE_REJECT: "j",
  NEW_ORDER_SINGLE: "D",
  EXECUTION_REPORT: "8",
  ORDER_CANCEL_REQUEST: "F",
  ORDER_CANCEL_REPLACE_REQUEST: "G",
  ORDER_CANCEL_REJECT: "9",
};

export const SIDE = {
  BUY: "1",
  SELL: "2",
};

export const ORD_STATUS = {
  NEW: "0",
  PARTIALLY_FILLED: "1",
  FILLED: "2",
  CANCELED: "4",
  REJECTED: "8",
};

export const HEADER_TAGS = [
  TAGS.BEGIN_STRING,
  TAGS.BODY_LENGTH,
  TAGS.MSG_TYPE,
  TAGS.SENDER_COMP_ID,
  TAGS.TARGET_COMP_ID,
  TAGS.MSG_SEQ_NUM,
  TAGS.SENDING_TIME,
  TAGS.ON_BEHALF_OF_COMP_ID,
  TAGS.DELIVER_TO_COMP_ID,
  TAGS.SECURE_DATA_LEN,
  TAGS.SECURE_DATA,
  TAGS.ENCRYPT_METHOD,
  TAGS.HEART_BT_INT,
  TAGS.RESET_SEQ_NUM_FLAG,
  TAGS.MSG_ENCODING,
  TAGS.LAST_MSG_SEQ_NUM_PROCESSED,
  TAGS.NO_HOPS,
];

export const TRAILER_TAGS = [TAGS.CHECK_SUM, TAGS.SIGNATURE, TAGS.SIGNATURE_LENGTH];
