// Automatically generated by scripts/sync-commands.mjs. Do not edit manually.
import { getTextCommandConfig } from "./commandManifest";
import { runTextCommand } from "./core/command";

export const commandConfig = getTextCommandConfig("ai-humanize");

export default async function command(): Promise<void> {
  return runTextCommand(commandConfig);
}
