// ==UserScript==
// @name         【无水印下载神器】豆包|即梦生成图片视频一键无水印
// @name:en      Watermark-Free Download Tool for Doubao|Jimeng
// @namespace    https://greasyfork.org/users/3001-hanjian-wu
// @version      1.4.0
// @description  实现豆包&即梦生成的图片视频免费无水印下载，支持一键下载原图和视频
// @description:en Free watermark-free download for images and videos generated by Doubao and Jimeng platforms
// @author       hanjian wu
// @homepage     https://greasyfork.org/users/3001-hanjian-wu
// @supportURL   https://greasyfork.org/users/3001-hanjian-wu
// @match        https://www.doubao.com/*
// @match        https://jimeng.jianying.com/ai-tool/*
// @grant        GM_download
// @grant        GM_xmlhttpRequest
// @connect      *
// @license      MIT
// @run-at       document-start
// @icon         data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPjxwYXRoIGQ9Ik0yMSAxNXY0YTIgMiAwIDAgMS0yIDJINWEyIDIgMCAwIDEtMi0ydi00Ii8+PHBvbHlsaW5lIHBvaW50cz0iNyAxMCAxMiAxNSAxNyAxMCIvPjxsaW5lIHgxPSIxMiIgeTE9IjE1IiB4Mj0iMTIiIHkyPSIzIi8+PC9zdmc+
// ==/UserScript==

(function() {
    'use strict';
  
    // 检测当前平台
    const currentPlatform = getCurrentPlatform();
  
    function getCurrentPlatform() {
        const hostname = window.location.hostname;
        if (hostname.includes('doubao.com')) return 'doubao';
        if (hostname.includes('jimeng.jianying.com')) return 'jimeng';
        return 'unknown';
    }
  
    // 基础样式
    const style = document.createElement('style');
    style.textContent = `
        .download-confirm-dialog {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background: rgba(255, 255, 255, 0.95);
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.12);
            z-index: 10000;
            min-width: 300px;
            backdrop-filter: blur(10px);
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        }
        .download-confirm-overlay {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(0, 0, 0, 0.5);
            z-index: 9999;
        }
        .floating-tip {
            position: fixed;
            bottom: 20px;
            left: 50%;
            transform: translateX(-50%);
            background: rgba(0, 0, 0, 0.8);
            color: white;
            padding: 10px 20px;
            border-radius: 8px;
            z-index: 10001;
            font-size: 14px;
        }
        .custom-download-btn {
            display: flex;
            align-items: center;
            padding: 8px 12px;
            cursor: pointer;
            border-radius: 6px;
            transition: background-color 0.2s;
            background: rgba(0, 0, 0, 0.05);
            margin: 4px;
            font-size: 14px;
            border: 1px solid rgba(0, 0, 0, 0.1);
        }
        .custom-download-btn:hover {
            background-color: rgba(0, 0, 0, 0.1);
        }
        .custom-download-btn svg {
            margin-right: 6px;
        }
        .jimeng-download-btn {
            background: #1890ff;
            color: white;
            border: none;
            border-radius: 4px;
            padding: 6px 12px;
            font-size: 12px;
            cursor: pointer;
            display: flex;
            align-items: center;
            gap: 4px;
        }
        .jimeng-download-btn:hover {
            background: #40a9ff;
        }
        .right-label-btn-wrapper-VRGRva {
            display: flex;
            align-items: center;
            padding: 8px;
            cursor: pointer;
            border-radius: 6px;
            transition: background-color 0.2s;
        }
        .right-label-btn-wrapper-VRGRva:hover {
            background-color: rgba(0, 0, 0, 0.06);
        }
        .btn-label-TbdJ1L {
            margin-left: 8px;
            font-size: 14px;
        }
        @media (prefers-color-scheme: dark) {
            .custom-download-btn:hover {
                background-color: rgba(255, 255, 255, 0.1);
            }
            .right-label-btn-wrapper-VRGRva:hover {
                background-color: rgba(255, 255, 255, 0.1);
            }
            .download-confirm-dialog {
                background: rgba(40, 40, 45, 0.95);
                color: white;
            }
        }
    `;
    document.head.appendChild(style);
  
    // 工具函数
    function getFileExtension(url) {
        const extension = url.split('?')[0].match(/\.(jpg|jpeg|png|gif|mp4|webm|webp)$/i);
        return extension ? extension[0] : '.jpg';
    }
  
    // 处理即梦图片URL，移除水印参数
    function processJimengImageUrl(url) {
        try {
            if (url.includes('dreamina-sign.byteimg.com')) {
                const urlObj = new URL(url);
  
                // 移除签名和过期时间参数
                const paramsToRemove = ['lk3s', 'x-expires', 'x-signature', 'format'];
                paramsToRemove.forEach(param => urlObj.searchParams.delete(param));
  
                // 移除resize参数，获取原始尺寸
                let pathname = urlObj.pathname;
                if (pathname.includes('~tplv-tb4s082cfz-aigc_resize:')) {
                    pathname = pathname.split('~tplv-tb4s082cfz-aigc_resize:')[0];
                    urlObj.pathname = pathname;
                }
  
                // 移除webp格式限制，改为png
                urlObj.searchParams.delete('format');
                if (pathname.endsWith('.webp')) {
                    pathname = pathname.replace('.webp', '.png');
                    urlObj.pathname = pathname;
                }
  
                return urlObj.toString();
            }
            return url;
        } catch (e) {
            console.error('处理即梦图片URL时出错:', e);
            return url;
        }
    }
  
    // 处理豆包图片URL - 保持签名参数以避免403错误
    function processDoubaoImageUrl(url) {
        try {
            if (url.includes('byteimg.com') || url.includes('imagex-sign')) {
                // 对于豆包，我们不移除签名参数，只处理水印相关的路径
                let processedUrl = url;
  
                // 如果URL包含缩略图标识，尝试转换为原图
                if (url.includes('~tplv-a9rns2rl98-web-thumb-watermark')) {
                    processedUrl = url.replace('~tplv-a9rns2rl98-web-thumb-watermark', '_origin~tplv-a9rns2rl98-image-dark-watermark');
                }
  
                // 如果已经是原图格式，直接返回
                if (url.includes('_origin~tplv-a9rns2rl98-image-dark-watermark')) {
                    return url;
                }
  
                return processedUrl;
            }
            return url;
        } catch (e) {
            console.error('处理豆包图片URL时出错:', e);
            return url;
        }
    }
  
    // 处理视频URL
    function processVideoUrl(url) {
        try {
            if (url.includes('vlabvod.com')) {
                const urlObj = new URL(url);
  
                // 移除水印和限制参数
                const paramsToRemove = [
                    'a', 'ch', 'cr', 'dr', 'er', 'cd', 'cs', 'ds', 'ft',
                    'mime_type', 'qs', 'rc', 'btag', 'dy_q', 'feature_id', 'l'
                ];
                paramsToRemove.forEach(param => urlObj.searchParams.delete(param));
  
                // 提升视频质量
                if (urlObj.searchParams.has('br')) {
                    const br = parseInt(urlObj.searchParams.get('br'));
                    urlObj.searchParams.set('br', Math.max(br, 8000).toString());
                    urlObj.searchParams.set('bt', Math.max(br, 8000).toString());
                }
  
                return urlObj.toString();
            }
            return url;
        } catch (e) {
            console.error('处理视频URL时出错:', e);
            return url;
        }
    }
  
    // 统一的URL处理函数
    function processMediaUrl(url, type) {
        if (type === 'video') {
            return processVideoUrl(url);
        } else {
            if (currentPlatform === 'jimeng') {
                return processJimengImageUrl(url);
            } else if (currentPlatform === 'doubao') {
                return processDoubaoImageUrl(url);
            }
        }
        return url;
    }
  
    // 获取豆包平台的请求头
    function getDoubaoHeaders() {
        return {
            'Accept': 'image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Cache-Control': 'no-cache',
            'Pragma': 'no-cache',
            'Referer': 'https://www.doubao.com/',
            'Sec-Ch-Ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            'Sec-Ch-Ua-Mobile': '?0',
            'Sec-Ch-Ua-Platform': '"Windows"',
            'Sec-Fetch-Dest': 'image',
            'Sec-Fetch-Mode': 'no-cors',
            'Sec-Fetch-Site': 'cross-site',
            'User-Agent': navigator.userAgent
        };
    }
  
    // 获取即梦平台的请求头
    function getJimengHeaders() {
        return {
            'Accept': 'image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
            'Cache-Control': 'no-cache',
            'Pragma': 'no-cache',
            'Referer': 'https://jimeng.jianying.com/',
            'Sec-Ch-Ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
            'Sec-Ch-Ua-Mobile': '?0',
            'Sec-Ch-Ua-Platform': '"Windows"',
            'Sec-Fetch-Dest': 'image',
            'Sec-Fetch-Mode': 'no-cors',
            'Sec-Fetch-Site': 'cross-site',
            'User-Agent': navigator.userAgent
        };
    }
  
    // 下载处理函数
    function downloadMedia(url, type, onSuccess, fileName, onProgress, onError) {
        const processedUrl = processMediaUrl(url, type);
        console.log(`下载${type}URL:`, processedUrl);
  
        // 根据平台选择合适的请求头
        let headers;
        if (currentPlatform === 'doubao') {
            headers = getDoubaoHeaders();
        } else if (currentPlatform === 'jimeng') {
            headers = getJimengHeaders();
        } else {
            headers = {
                'Referer': window.location.href,
                'User-Agent': navigator.userAgent
            };
        }
  
        GM_xmlhttpRequest({
            method: 'GET',
            url: processedUrl,
            responseType: 'blob',
            headers: headers,
            onprogress: (progress) => {
                if (progress.lengthComputable && onProgress) {
                    onProgress(Math.round((progress.loaded / progress.total) * 100));
                }
            },
            onload: (response) => {
                if (response.status === 200) {
                    const blob = response.response;
                    const url = URL.createObjectURL(blob);
                    const link = document.createElement('a');
                    link.href = url;
                    link.download = fileName;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                    setTimeout(() => URL.revokeObjectURL(url), 100);
                    if (onSuccess) onSuccess();
                } else {
                    console.error('下载失败，状态码:', response.status);
                    console.error('响应详情:', response);
                    if (onError) onError(`HTTP ${response.status} - 可能是防盗链限制`);
                }
            },
            onerror: (error) => {
                console.error('下载请求失败:', error);
                if (onError) onError(error.message || '网络错误');
            }
        });
    }
  
    // 创建下载对话框
    function createDownloadDialog(mediaUrl, mediaType) {
        const dialog = document.createElement('div');
        dialog.className = 'download-confirm-dialog';
  
        const now = new Date();
        const defaultFileName = `${currentPlatform}_${now.getFullYear()}${(now.getMonth()+1).toString().padStart(2,'0')}${now.getDate().toString().padStart(2,'0')}_${now.getHours().toString().padStart(2,'0')}${now.getMinutes().toString().padStart(2,'0')}`;
        const extension = mediaType === 'video' ? '.mp4' : '.png';
  
        dialog.innerHTML = `
            <h3>下载${mediaType === 'video' ? '视频' : '图片'}</h3>
            <div style="margin: 20px 0;">
                <label style="display: block; margin-bottom: 8px;">文件名称</label>
                <input type="text" id="fileName" value="${defaultFileName}${extension}"
                    style="width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 4px;">
            </div>
            <div style="margin: 10px 0; font-size: 12px; color: #666;">
                原始URL: ${mediaUrl.substring(0, 80)}${mediaUrl.length > 80 ? '...' : ''}
            </div>
            <div style="display: flex; justify-content: flex-end; gap: 10px;">
                <button id="cancelDownload" style="padding: 8px 16px; border: none; border-radius: 4px; background: #f0f0f0; cursor: pointer;">取消</button>
                <button id="confirmDownload" style="padding: 8px 16px; border: none; border-radius: 4px; background: #1a73e8; color: white; cursor: pointer;">下载</button>
            </div>
            <div id="progressText" style="margin-top: 10px; text-align: center;"></div>
        `;
  
        const overlay = document.createElement('div');
        overlay.className = 'download-confirm-overlay';
  
        document.body.appendChild(overlay);
        document.body.appendChild(dialog);
  
        const progressText = dialog.querySelector('#progressText');
        const confirmBtn = dialog.querySelector('#confirmDownload');
  
        confirmBtn.onclick = () => {
            const fileName = dialog.querySelector('#fileName').value;
            downloadMedia(mediaUrl, mediaType,
                () => {
                    document.body.removeChild(dialog);
                    document.body.removeChild(overlay);
                    showFloatingTip('下载完成！');
                },
                fileName,
                (percent) => {
                    progressText.textContent = `下载中 ${percent}%`;
                    confirmBtn.disabled = true;
                },
                (error) => {
                    alert(`下载失败: ${error}`);
                    confirmBtn.disabled = false;
                    progressText.textContent = '';
                }
            );
        };
  
        dialog.querySelector('#cancelDownload').onclick = () => {
            document.body.removeChild(dialog);
            document.body.removeChild(overlay);
        };
  
        overlay.onclick = () => {
            document.body.removeChild(dialog);
            document.body.removeChild(overlay);
        };
    }
  
    // 显示浮动提示
    function showFloatingTip(message) {
        const tip = document.createElement('div');
        tip.className = 'floating-tip';
        tip.textContent = message;
        document.body.appendChild(tip);
        setTimeout(() => {
            if (tip.parentNode) {
                document.body.removeChild(tip);
            }
        }, 3000);
    }
  
    // 即梦平台：获取当前显示的媒体URL
    function getJimengMediaUrl() {
        // 查找视频 - 更新的选择器
        const videoSelectors = [
            '.videoWrapper-pUQv4n video',
            '.videoWrapper-oUYz4J video',
            'video[src*="vlabvod.com"]'
        ];
  
        for (const selector of videoSelectors) {
            const video = document.querySelector(selector);
            if (video && video.src) {
                console.log('找到视频:', video.src);
                return { url: video.src, type: 'video' };
            }
        }
  
        // 查找图片 - 更新的选择器
        const imageSelectors = [
            '.container-zpjKFA .image-ArSTaO',
            '.container-haV1lv .image-DU6JLr',
            '.image-yUAN3J .image-ArSTaO',
            'img[src*="dreamina-sign.byteimg.com"]'
        ];
  
        for (const selector of imageSelectors) {
            const img = document.querySelector(selector);
            if (img && img.src) {
                console.log('找到图片:', img.src);
                return { url: img.src, type: 'image' };
            }
        }
  
        return null;
    }
  
    // 豆包平台：获取当前显示的图片URL
    function getDoubaoImageUrl() {
        // 优先查找主预览图片
        const mainImg = document.querySelector('[data-testid="in_painting_picture"]');
        if (mainImg && mainImg.src) {
            console.log('找到主预览图片:', mainImg.src);
            return mainImg.src;
        }
  
        // 查找活跃的缩略图
        const activeThumb = document.querySelector('.thumb-image-tHDFzq.active-_DKfjD');
        if (activeThumb && activeThumb.src) {
            console.log('找到活跃缩略图:', activeThumb.src);
            // 将缩略图URL转换为原图URL
            let originalUrl = activeThumb.src;
            if (originalUrl.includes('web-thumb-watermark')) {
                originalUrl = originalUrl.replace('~tplv-a9rns2rl98-web-thumb-watermark', '_origin~tplv-a9rns2rl98-image-dark-watermark');
                // 修改文件扩展名为png
                originalUrl = originalUrl.replace('.jpeg', '.png');
            }
            console.log('转换后的原图URL:', originalUrl);
            return originalUrl;
        }
  
        // 查找容器中的图片
        const container = document.querySelector('[data-testid="canvas_image_container"]');
        if (container) {
            const img = container.querySelector('img');
            if (img && img.src) {
                console.log('找到容器图片:', img.src);
                return img.src;
            }
        }
  
        return null;
    }
  
    // 查找并下载主要媒体
    function findAndDownloadMainMedia() {
        if (currentPlatform === 'jimeng') {
            const media = getJimengMediaUrl();
            if (media) {
                console.log(`找到${media.type}URL:`, media.url);
                createDownloadDialog(media.url, media.type);
                return true;
            }
        } else if (currentPlatform === 'doubao') {
            const imageUrl = getDoubaoImageUrl();
            if (imageUrl) {
                console.log('找到图片URL:', imageUrl);
                createDownloadDialog(imageUrl, 'image');
                return true;
            }
        }
  
        showFloatingTip('未找到可下载的图片或视频');
        return false;
    }
  
    // 即梦平台：添加下载按钮
    function addJimengDownloadButton() {
        const checkExist = setInterval(() => {
            // 更新的选择器，适配新的页面结构
            const topActionBarSelectors = [
                '.topActionBar-IGbsIk',
                '.topActionBar-v7_WTk'
            ];
  
            let topActionBar = null;
            for (const selector of topActionBarSelectors) {
                topActionBar = document.querySelector(selector);
                if (topActionBar) break;
            }
  
            if (topActionBar && !document.querySelector('#jimeng-custom-download-btn')) {
                clearInterval(checkExist);
  
                const newButton = document.createElement('div');
                newButton.id = 'jimeng-custom-download-btn';
                newButton.className = 'jimeng-download-btn';
                newButton.innerHTML = `
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M12 2a1 1 0 0 1 1 1v11.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-5 5a1 1 0 0 1-1.414 0l-5-5a1 1 0 1 1 1.414-1.414L11 14.586V3a1 1 0 0 1 1-1zM3 17a1 1 0 0 1 1-1h16a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1z" fill="currentColor"/>
                    </svg>
                    <span>无水印下载</span>
                `;
  
                // 插入到第一个按钮之后
                const firstBtnSelectors = [
                    '.operationBtnItem-O7bor4',
                    '.operationBtnItem-_GEqBw'
                ];
  
                let firstBtn = null;
                for (const selector of firstBtnSelectors) {
                    firstBtn = topActionBar.querySelector(selector);
                    if (firstBtn) break;
                }
  
                if (firstBtn) {
                    topActionBar.insertBefore(newButton, firstBtn.nextSibling);
                } else {
                    topActionBar.appendChild(newButton);
                }
  
                newButton.addEventListener('click', (e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    try {
                        findAndDownloadMainMedia();
                    } catch (err) {
                        console.error('下载功能触发失败:', err);
                        showFloatingTip('下载功能初始化失败，请重试');
                    }
                });
  
                console.log('即梦无水印下载按钮已添加');
            }
        }, 1000);
  
        setTimeout(() => clearInterval(checkExist), 10000);
    }
  
    // 豆包平台：添加下载按钮
    function addDoubaoDownloadButton() {
        const checkExist = setInterval(() => {
            const originalDownloadButton = document.querySelector('[data-testid="edit_image_download_button"]');
            const rightContainer = document.querySelector('.right-Ilii0V');
  
            if (originalDownloadButton && rightContainer && !document.querySelector('#doubao-custom-download-btn')) {
                clearInterval(checkExist);
  
                const newButton = document.createElement('div');
                newButton.id = 'doubao-custom-download-btn';
                newButton.className = 'right-label-btn-wrapper-VRGRva hover-qCVMA7';
                newButton.innerHTML = `
                    <span role="img" class="semi-icon semi-icon-default !text-16">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="none" viewBox="0 0 24 24">
                            <path fill="currentColor" d="M12 2a1 1 0 0 1 1 1v11.586l3.293-3.293a1 1 0 1 1 1.414 1.414l-5 5a1 1 0 0 1-1.414 0l-5-5a1 1 0 1 1 1.414-1.414L11 14.586V3a1 1 0 0 1 1-1zM3 17a1 1 0 0 1 1-1h16a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1z"></path>
                        </svg>
                    </span>
                    <span class="btn-label-TbdJ1L">无水印下载</span>
                `;
  
                originalDownloadButton.parentNode.insertBefore(newButton, originalDownloadButton.nextSibling);
  
                newButton.addEventListener('click', (e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    try {
                        findAndDownloadMainMedia();
                    } catch (err) {
                        console.error('下载功能触发失败:', err);
                        showFloatingTip('下载功能初始化失败，请重试');
                    }
                });
  
                console.log('豆包无水印下载按钮已添加');
            }
        }, 1000);
  
        setTimeout(() => clearInterval(checkExist), 10000);
    }
  
    // 监听页面变化
    function observePageChanges() {
        const observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                if (mutation.type === 'childList') {
                    if (currentPlatform === 'jimeng') {
                        const topActionBar = document.querySelector('.topActionBar-IGbsIk') || document.querySelector('.topActionBar-v7_WTk');
                        if (topActionBar && !document.querySelector('#jimeng-custom-download-btn')) {
                            setTimeout(addJimengDownloadButton, 1000);
                        }
                    } else if (currentPlatform === 'doubao') {
                        const editorPanel = document.querySelector('[data-testid="image_editor_panel"]');
                        if (editorPanel && !document.querySelector('#doubao-custom-download-btn')) {
                            setTimeout(addDoubaoDownloadButton, 1000);
                        }
                    }
                }
            });
        });
  
        observer.observe(document.body, {
            childList: true,
            subtree: true
        });
    }
  
    // 初始化脚本
      // 初始化脚本
      function initScript() {
          try {
              console.log(`初始化${currentPlatform}平台无水印下载脚本`);
  
              if (!document.querySelector('#download-script-style')) {
                  style.id = 'download-script-style';
              }
  
              // 根据平台添加对应的下载按钮
              if (currentPlatform === 'jimeng') {
                  setTimeout(addJimengDownloadButton, 2000);
              } else if (currentPlatform === 'doubao') {
                  setTimeout(addDoubaoDownloadButton, 2000);
              }
  
              observePageChanges();
  
              // 添加键盘快捷键
              document.addEventListener('keydown', (e) => {
                  if (e.ctrlKey && e.shiftKey && e.key === 'D') {
                      e.preventDefault();
                      findAndDownloadMainMedia();
                  }
              });
  
          } catch (e) {
              console.error('初始化脚本时出错:', e);
          }
      }
  
  
      // 启动脚本
      if (document.readyState === 'loading') {
          document.addEventListener('DOMContentLoaded', initScript);
      } else {
          initScript();
      }
  
      window.addEventListener('load', () => {
          if (currentPlatform === 'jimeng') {
              setTimeout(addJimengDownloadButton, 3000);
          } else if (currentPlatform === 'doubao') {
              setTimeout(addDoubaoDownloadButton, 3000);
          }
      });
  
  })();