export interface Device {
  active_time: number;
  biz_type: number;
  category: DeviceCategories;
  create_time: number;
  icon: string;
  id: string;
  ip: string;
  lat: string;
  local_key: string;
  lon: string;
  model: string;
  name: string;
  online: boolean;
  owner_id: string;
  product_id: string;
  product_name: string;
  status: FunctionItem[];
  sub: boolean;
  time_zone: string;
  uid: string;
  update_time: number;
  uuid: string;
  pinned: boolean;
}

export interface Status {
  code: string;
  value?: boolean | number | string;
  name?: string;
}

export interface Preferences {
  accessId: string;
  accessSecret: string;
  region: string;
}

export interface DevicesReponse {
  devices: Device[];
  has_more: boolean;
  last_row_key: string;
}

export interface DeviceCategory {
  code: string;
  name: DeviceCategories;
}

export interface CommandResponse {
  success: boolean;
  result: boolean;
  t: number;
}

export interface DeviceFunctionsResult {
  category: string;
  functions: FunctionItem[];
}

export interface FunctionItem {
  code: string;
  desc?: string;
  name: string;
  type?: string;
  value?: boolean | number | string;
  values?: string;
}

export type DeviceCategories =
  | "cz"
  | "dcb"
  | "pc"
  | "aqcz"
  | "wkcz"
  | "ckmb"
  | "znspq"
  | "kg"
  | "tgkg"
  | "clkg"
  | "cjkg"
  | "wxkg"
  | "fskg"
  | "ckqdkg"
  | "wxml"
  | "tdq"
  | "ckmkzq"
  | "xdkzq"
  | "zigbeeqc"
  | "qjdcz"
  | "zigbeekt"
  | "znjxs"
  | "dz"
  | "PDpc"
  | "znjrf"
  | "jlmkzq"
  | "zncdq"
  | "gcmkzq"
  | "hwsb"
  | "sjx"
  | "dgncz"
  | "cljqr"
  | "wxjrq"
  | "dbs"
  | "dj"
  | "gqzm"
  | "tyd"
  | "fwd"
  | "zwd"
  | "cxd"
  | "lzd"
  | "gkd"
  | "tccd"
  | "fbd"
  | "sfd"
  | "tpd"
  | "fgd"
  | "yjd"
  | "ggd"
  | "qcd"
  | "zwszd"
  | "gld"
  | "qxtyd"
  | "sjyd"
  | "ryd"
  | "bgd"
  | "zjd"
  | "zsd"
  | "xtd"
  | "jqd"
  | "bd"
  | "tyndc"
  | "tynyddy"
  | "zmdg"
  | "ybd"
  | "ztd"
  | "rgbsb"
  | "hcsbd"
  | "3dd"
  | "leddzp"
  | "zbd"
  | "tyntyd"
  | "tyngyd"
  | "tynlyd"
  | "zmdd"
  | "zmcgd"
  | "sdt"
  | "xdsjd"
  | "gxd"
  | "hzjd"
  | "sbd"
  | "tynafd"
  | "gf"
  | "xnykq"
  | "cmykq"
  | "yzd"
  | "jsd"
  | "hbd"
  | "sxtpmtbq"
  | "zmkzq"
  | "sntydj"
  | "syzmqd"
  | "hdmipmtbq"
  | "hyd"
  | "hctyd"
  | "dd"
  | "xdd"
  | "gyd"
  | "wbldgyd"
  | "fsd"
  | "tyndj"
  | "dc"
  | "td"
  | "hcdc"
  | "tgq"
  | "txd"
  | "sxd"
  | "hwtydj"
  | "dsd"
  | "zmqd"
  | "pjd"
  | "mbd"
  | "pd"
  | "ld"
  | "ykq"
  | "dsdsoc"
  | "xyd"
  | "xktyd"
  | "djb"
  | "g9"
  | "gu10"
  | "kt"
  | "bx"
  | "xy"
  | "rs"
  | "bgl"
  | "znrb"
  | "ydkt"
  | "gyj"
  | "xbx"
  | "sd"
  | "tdjqr"
  | "yech"
  | "xdj"
  | "xfs_1"
  | "ds_1"
  | "zm_wy_fs"
  | "ccjqr"
  | "gcj"
  | "xcq"
  | "cwclt"
  | "fs"
  | "ks"
  | "scxdj"
  | "xxj"
  | "cwq"
  | "jsq"
  | "ycjqr"
  | "cs"
  | "kj"
  | "qn"
  | "dr"
  | "mjj"
  | "dbl"
  | "dnz"
  | "cwmw"
  | "cwwsq"
  | "cwwsqipc"
  | "cwysj"
  | "cwwqfsq"
  | "cwtswsq"
  | "msp"
  | "dcq"
  | "szpc"
  | "ygwsq"
  | "ygsb"
  | "ygjrb"
  | "sz"
  | "szj"
  | "zndsj"
  | "sjz"
  | "clykq"
  | "yb"
  | "ysj"
  | "mwd"
  | "ktkzq"
  | "lyz"
  | "petfinder"
  | "tjx"
  | "cwbb"
  | "cwhgx"
  | "cwjwq"
  | "cwqys"
  | "xgmjq"
  | "yyy"
  | "yec"
  | "etaqzy"
  | "xnq"
  | "ywhjj"
  | "ljt"
  | "mt"
  | "znnz"
  | "ntq"
  | "dyj"
  | "yug"
  | "yyh"
  | "tyykq"
  | "wk"
  | "wkf"
  | "xfj"
  | "bmwk"
  | "hwktwkq"
  | "cl"
  | "zigbeecm"
  | "lyj"
  | "mc"
  | "xg"
  | "sf"
  | "ttm"
  | "dg"
  | "jdcljqr"
  | "szjqr"
  | "kqzg"
  | "kfj"
  | "yinsj"
  | "xcj"
  | "dsq"
  | "dylg"
  | "dkl"
  | "swzkfkj"
  | "df"
  | "mzj"
  | "kx"
  | "bh"
  | "wb"
  | "cn"
  | "cyljclq"
  | "mg"
  | "pbj"
  | "ccj"
  | "ggj"
  | "js"
  | "tnq"
  | "zx"
  | "xdg"
  | "llj"
  | "xwj"
  | "xd"
  | "jcz"
  | "fsj"
  | "swtz"
  | "yexdg"
  | "ysh"
  | "nnq"
  | "snj"
  | "znlt"
  | "zzj"
  | "djj"
  | "mb"
  | "jyj"
  | "rq"
  | "bqlj"
  | "yyj"
  | "dcl"
  | "zbj"
  | "znfh"
  | "cbj"
  | "jg"
  | "znsjq"
  | "afcg"
  | "ggkzq"
  | "fkq"
  | "dzbq"
  | "timer"
  | "cwy"
  | "jbq"
  | "hjjcy"
  | "wlj"
  | "dltcq"
  | "szjcy"
  | "dytcq"
  | "znykq"
  | "gykzq"
  | "fgycgq"
  | "cjy"
  | "ybq"
  | "csbcgq"
  | "wsdykq"
  | "wbcgq"
  | "zwcgq"
  | "jjjcy"
  | "zdshj"
  | "twj"
  | "pir"
  | "hps"
  | "mcs"
  | "sos"
  | "mhq"
  | "sj"
  | "hzdcgq"
  | "zd"
  | "gas_controller"
  | "ylcg"
  | "sgbj"
  | "wsdcg"
  | "llcgq"
  | "ldcg"
  | "qxj"
  | "jqbj"
  | "pm2.5"
  | "co2bj"
  | "voc"
  | "zwjcy"
  | "ywbj"
  | "rqbj"
  | "jwbj"
  | "ywcgq"
  | "cobj"
  | "rg"
  | "dgnbj"
  | "mal"
  | "znzy"
  | "slm"
  | "tzc1"
  | "yyc"
  | "jbamy"
  | "jmq"
  | "mry"
  | "ts"
  | "kswes"
  | "pltwj"
  | "xyy"
  | "ksqhty"
  | "tmy"
  | "BDJTZC"
  | "tew_1"
  | "jsj"
  | "ewq"
  | "gbtwj"
  | "dztwj"
  | "sb"
  | "cpj"
  | "xyj"
  | "tzc10"
  | "bsy"
  | "znhsb"
  | "amy"
  | "zpbj"
  | "smd"
  | "smnk"
  | "znc"
  | "znzt"
  | "bzyd"
  | "liliao"
  | "zyp"
  | "ys"
  | "znyh"
  | "jmy"
  | "txj"
  | "znqp"
  | "push_up_bars"
  | "vibration_plate"
  | "znwqp"
  | "znyl"
  | "znwlq"
  | "dgdc"
  | "znhlq"
  | "znjfl"
  | "znllq"
  | "hcj"
  | "zncyq"
  | "xlt"
  | "yoga_mat"
  | "znmzj"
  | "zfs"
  | "sp"
  | "doorbell"
  | "jz"
  | "camera"
  | "fkj"
  | "videolock"
  | "kshgh"
  | "smsxj"
  | "jtmspro"
  | "photolock"
  | "ms"
  | "gyms"
  | "hotelms"
  | "bxx"
  | "znmj"
  | "xcjly"
  | "nvr"
  | "ms_category"
  | "mk"
  | "small_lock"
  | "jtmsbh"
  | "aihz"
  | "dghsxj"
  | "wgsxj"
  | "smartms_pro"
  | "jisentest"
  | "jzq"
  | "lyqwg"
  | "bywg"
  | "zigbee"
  | "wg2"
  | "dgnzk"
  | "videohub"
  | "xnwg"
  | "alexa_yyxxj"
  | "zxgjcp"
  | "alexa_built_in"
  | "zhzkp"
  | "alexa_yywg"
  | "ldjcq"
  | "ups"
  | "MPPT"
  | "LCRV"
  | "zcnbq"
  | "wxnbq"
  | "cjq"
  | "byq"
  | "qccdz"
  | "ddzxccdz"
  | "bxsdy"
  | "zndb"
  | "znsb"
  | "dlq"
  | "znqb"
  | "znnbq"
  | "fsjl"
  | "bpq"
  | "cnsb"
  | "znjdq"
  | "slj"
  | "gywg"
  | "BTU"
  | "ggq"
  | "sfkzq"
  | "yxzdcgq"
  | "dlcgq"
  | "wsdcgq"
  | "cocgq"
  | "co2cgq"
  | "pm25cgq"
  | "ptlkzq"
  | "ptl"
  | "gyxhd"
  | "anzsd"
  | "ysjsb"
  | "xgjcsb"
  | "tpjsb"
  | "hlhsb"
  | "lwcsy"
  | "aoisb"
  | "cnc"
  | "zsj"
  | "ddc"
  | "dmq"
  | "znlj"
  | "AGV"
  | "yqcgq"
  | "ylcgq"
  | "iomk"
  | "gylsj"
  | "pfj"
  | "yxywcgq"
  | "phcgq"
  | "eccgq"
  | "admk"
  | "ktykq"
  | "plc"
  | "ds"
  | "mj"
  | "bjyy"
  | "tyy"
  | "ej"
  | "dzrl"
  | "dzbp"
  | "jp"
  | "yj"
  | "mkf"
  | "zkp"
  | "wpyyzk"
  | "zwyyzs"
  | "3ddyj"
  | "loudspeaker_box"
  | "etqcc"
  | "bxdyj"
  | "twdyj"
  | "wjxc"
  | "yxk"
  | "cryp"
  | "jdh"
  | "ddzxc"
  | "cqb"
  | "ddly"
  | "phc"
  | "tk"
  | "bbyx"
  | "sswifi"
  | "zfhz"
  | "BatteryPack"
  | "shg"
  | "ddzxcdc"
  | "hwcxcp"
  | "fusion_positioning"
  | "qdxc"
  | "hbc"
  | "tracker"
  | "znddc"
  | "fdq"
  | "znyg"
  | "znwg"
  | "znylbsq"
  | "wyzxj"
  | "hjjc"
  | "xjq"
  | "rba"
  | "dzy"
  | "dayu"
  | "zhxf"
  | "gpsxt"
  | "lryxt"
  | "spfxt"
  | "ktxt"
  | "dtxt"
  | "baznsb"
  | "byqnhxt"
  | "xfxt"
  | "bazmxt"
  | "hjjkxt"
  | "gsxt"
  | "zyktxt"
  | "sssbxt"
  | "balryxt"
  | "access_point"
  | "rfid_reader"
  | "dmjkzq"
  | "hymp"
  | "qtsdk"
  | "wnykq"
  | "zntc"
  | "zntk"
  | "wfcon"
  | "znyxss"
  | "qt"
  | "ss_sl"
  | "vocie_platform_only"
  | "Socket"
  | "Battery Pack"
  | "Power Strip"
  | "Metering socket"
  | "Temperature control socket"
  | "RGB Touch Panel"
  | "Adapter"
  | "Switch"
  | "Dimmer Switch"
  | "Curtain Switch"
  | "Scenario Switch"
  | "Wireless Switch"
  | "Fan Switch"
  | "Card Switch"
  | "Wireless Doorbell"
  | "Breaker"
  | "Garage Door Opener"
  | "Disinfection controller"
  | "Wall Socket"
  | "Scenario Light Socket"
  | "Air Conditioner Mate"
  | "Smart Manipulator Arm"
  | "Electric Drill"
  | "Power strip"
  | "heating suit"
  | "Rolling door controller"
  | "Professional charger"
  | "Barn Door"
  | "Water Pump"
  | "data cable"
  | "Temperature and humidity socket"
  | "Curtain Robot"
  | "Mosquito repellent heater"
  | "Electric Wrench"
  | "Light Source"
  | "Public Area Lighting"
  | "Garden Light"
  | "Ambient Light"
  | "Grow Light"
  | "Magnetic Fastening Light"
  | "Candle Lamp"
  | "Bay Light"
  | "Parking Lot Light"
  | "Explosion-proof Light"
  | "Tri-proof Light"
  | "Canopy Light"
  | "Flood Light"
  | "Emergency Light"
  | "High-mast Light"
  | "Sports Light"
  | "Horticulture Light"
  | "Light Therapy Lamp"
  | "Holographic Imaging Light"
  | "Salt Lamp"
  | "Lava Lamp"
  | "Fill Light"
  | "Batten Light"
  | "Chandelier"
  | "Linear Luminarie"
  | "Mirror Light"
  | "wall light"
  | "Solar String Light"
  | "Solar Power Bank"
  | "LED Tube"
  | "Yuba Light"
  | "Candleholder Lamp"
  | "RGB Mouse"
  | "Dreamcolor Mouse Mat"
  | "Three-dimensional Lamp"
  | "LED Electronic Display"
  | "Selfie Light"
  | "Solar Pathway Light"
  | "Solar Motion Sensor Light"
  | "Solar Camping Light"
  | "Pendant Light"
  | "Cabinet Light"
  | "flash light"
  | "Germicidal Light"
  | "Fiber Optic Light"
  | "Makeup Light"
  | "Paper Lantern"
  | "Solar Security Light"
  | "Photovoltaics"
  | "Knob Remote Control"
  | "Touch Remote Control"
  | "Farming Light"
  | "Classroom Light"
  | "Blackboard Light"
  | "Camera Screen Sync Controller"
  | "LED Controller"
  | "Indoor Lighting"
  | "Commercial LED Driver"
  | "HDMI Screen Sync Controller"
  | "Flame Bulb"
  | "Dreamcolor Garden Light"
  | "Strip Lights"
  | "Ceiling Light"
  | "PIR Light"
  | "Microwave radar sensor light"
  | "Ceiling Fan"
  | "solar light"
  | "String Lights"
  | "Table Lmap/Floor Lamp"
  | "Colorful String Light"
  | "Light Modulator"
  | "Downlight"
  | "Spotlight"
  | "Solution for outdoor light"
  | "Filament lamp"
  | "Lighting Driver"
  | "DIY Light Panels"
  | "Panel Light"
  | "PAR Light"
  | "Street light"
  | "Lighting remote control"
  | "Ceiling fan light"
  | "Night light"
  | "Star projector"
  | "Light"
  | "G9 Light"
  | "GU10 Light"
  | "Air Conditioner"
  | "Refrigerator"
  | "Washing Machine"
  | "Water Heater"
  | "Boiler"
  | "Smart Heat Pump"
  | "Portable Air Conditioner"
  | "Clothes Dryer"
  | "Mini Refrigerator"
  | "Robot Vacuum"
  | "Automatic Mopping Robot"
  | "Baby scale"
  | "Disinfection machine"
  | "Mini fan"
  | "beacon ceiling fan"
  | "Leaves the table fan"
  | "Window Cleaner"
  | "Mower"
  | "Vacuum Cleaner"
  | "Pet Food Bucket"
  | "Fan"
  | "Air Cooler"
  | "Hand-held Mopping Robot"
  | "Diffuser"
  | "Deodorizer"
  | "Humidifier"
  | "Pool Robot"
  | "Dehumidifier"
  | "Air Purifier"
  | "Heater"
  | "Electric Blanket"
  | "Towel rack"
  | "Electric fireplace"
  | "Electric Heating Table"
  | "Pet House"
  | "Pet Feeder"
  | "Pet Feeder with IPC"
  | "Pet Water Feeder"
  | "Pet Ball Thrower"
  | "Pet Treat Feeder"
  | "Cat Toilet"
  | "Pet Toys Ball"
  | "Aquarium Power Strip"
  | "Fish Feeder"
  | "Aquarium Pump"
  | "Aquarium Heaters"
  | "Plant Grower"
  | "Shredder"
  | "Smart TV Shelf"
  | "Lifting Table"
  | "Curtain Remote"
  | "Bathroom Heater"
  | "Bathroom Mirror"
  | "Mosquito Lamp"
  | "Air Conditioner"
  | "Shower Column"
  | "Pet Finder"
  | "Electric Baseboard Heater"
  | "Pet Bag"
  | "Pet Dryer"
  | "Pet Odor Remover"
  | "Pet Leash"
  | "Shoe cabinet sterilizer"
  | "Baby Rocking Chair"
  | "Crib"
  | "Child Safety Seat"
  | "Breast pump"
  | "Wash Aid"
  | "Mintpass Rubbish"
  | "Smart Toilet"
  | "Smart alarm clock"
  | "HVAC"
  | "Printer"
  | "Fish Tank"
  | "Music Box"
  | "Remote Control"
  | "Thermostat"
  | "TRV"
  | "Ventilation System"
  | "North American thermostat"
  | "IR Air Thermostat"
  | "Curtain"
  | "Curtain Motor"
  | "Drying Rack"
  | "Door/Window Controller"
  | "Shoe cabinet"
  | "Smart Sofa"
  | "Tatami"
  | "Wall Cabinet"
  | "Curtain robot"
  | "Finger robot"
  | "Air Fryer"
  | "Coffee Maker"
  | "Water Dispenser"
  | "Vegetable cleaner"
  | "Timer"
  | "Electric Pressure Cooker"
  | "Electric Grill"
  | "Vacuum Sealer"
  | "Rice Cooker"
  | "Sous Vide Cooker"
  | "Oven"
  | "Smart Kettle"
  | "Microwave"
  | "Milk Dispenser"
  | "Food Waste Disposer"
  | "Rice cabinet"
  | "Blender"
  | "Cooker"
  | "Dehydrator"
  | "Water Purifier"
  | "Smart Milk Kettle"
  | "Steam Oven"
  | "Sterilizer"
  | "Food Processor"
  | "Dishwasher"
  | "Disinfection Cabinet"
  | "Integrated Kitchen"
  | "Babycook"
  | "Food Probe"
  | "Baby Sterilizer"
  | "Health pot"
  | "Bottle Warmer"
  | "Yogurt Maker"
  | "Smart Faucet"
  | "Juicer"
  | "Soymilk Maker"
  | "Bread Maker"
  | "Drinking Water Dispensers"
  | "Gas Stove"
  | "Ice Cream Machine"
  | "Hood"
  | "Induction Cooker"
  | "Ice Machine"
  | "Bento Box"
  | "Tea Machine"
  | "Wine cabinet"
  | "Smart Pump"
  | "sensor"
  | "Lighting Controller"
  | "Card Issuer（Wi-Fi）"
  | "Electronic Label"
  | "Fixed Time"
  | "Thermometer"
  | "Pedometer"
  | "Environmental detector"
  | "Grip meter"
  | "Current Detector"
  | "Water quality detector"
  | "Voltage Detector"
  | "Smart remote"
  | "Motion Sensor Controller"
  | "Wind and rain sensor"
  | "Laser  distance meter"
  | "Greeter"
  | "Ultrasonic Parking Detector"
  | "Temp Humidity Remote Control"
  | "Microwave sensor"
  | "Occupancy Sensor"
  | "Alcohol Detector"
  | "Vending Machine"
  | "Body Thermometer"
  | "Motion Detector"
  | "Human Presence Sensor"
  | "Contact Sensor"
  | "Emergency Button"
  | "Smart Fire Extinguisher"
  | "Flooding Detector"
  | "Constant Illumination Sensor"
  | "Vibration Sensor"
  | "Gas Controller"
  | "Pressure Sensor"
  | "Siren"
  | "Temperature and Humidity Sensor"
  | "Flow Sensor"
  | "Luminance Sensor"
  | "Clock Weather station"
  | "Formaldehyde Detector"
  | "PM2.5 Sensor"
  | "CO2 Detector"
  | "VOC Sensor"
  | "Plant monitor"
  | "Smoke Detector"
  | "Gas Detector"
  | "Methane Detector"
  | "Liquid level Sensor"
  | "CO Detector"
  | "Heat Detector"
  | "Multi-function Sensor"
  | "Multifunctional Alarm"
  | "Smart Seat"
  | "Sound level meter"
  | "Body Fat Scale"
  | "Nutrition scale"
  | "Neck massage"
  | "Fascial Gun"
  | "Beauty Instrument"
  | "Smart Rope Skipping"
  | "Ear Wax Removal Otoscope"
  | "Ovulation Thermometer"
  | "Oximeter"
  | "Visual Blackhead Remover"
  | "hair removal instrument"
  | "eight electrodes body fat scale"
  | "Temperature Stick"
  | "Fitness mirror"
  | "Forehead thermometer"
  | "Wall-mounted thermometer"
  | "electronic clinical thermometer"
  | "Watch/Bracelet"
  | "Skin Scurbber"
  | "Blood Pressure Monitor"
  | "Body weight scale"
  | "Moisturizing machine"
  | "Smart glass"
  | "Massage Chair"
  | "Treadmill"
  | "Sleep Band"
  | "Sleep Dot"
  | "Smart Bed"
  | "Smart pillow"
  | "White Noise Light"
  | "Physiotherapy Products"
  | "Foot Tub"
  | "Toothbrush"
  | "Smart Pill Box"
  | "Smart cleanser"
  | "Shaving machine"
  | "Smart Badminton Racket"
  | "Push Up Bars"
  | "Vibration Plate"
  | "Smart Tennis Racket"
  | "Smart Dumbbells"
  | "Smart Wrist Ball"
  | "Indoor Cycling Bike"
  | "Hula Hoop"
  | "Abdominal Wheel"
  | "Resistance Band"
  | "Rowing Mchine"
  | "Smart Oral Irrigator"
  | "Heart Rate Sticker"
  | "Yoga Mat"
  | "Beauty Mirror"
  | "Straight Hair Comb"
  | "Smart Camera"
  | "Smart Doorbell"
  | "Base Station"
  | "Smart Camera"
  | "Visitor machine"
  | "videolock"
  | "Visual personal care"
  | "Binocular Camera"
  | "Residential Lock PRO"
  | "real-time video lock"
  | "Residential Lock"
  | "Business Lock"
  | "Hotel Lock"
  | "safe"
  | "Access Control"
  | "Car Recorder"
  | "NVR"
  | "DoorLock Accessories"
  | "Gating Lock"
  | "Small Lock"
  | "Smart Lock（Stand by）"
  | "AI Box"
  | "LE Camera"
  | "Gateway Camera"
  | "SmartLock Pro"
  | "jisentest"
  | "Fitting"
  | "Router"
  | "IoT Edge Gateway"
  | "Gateway"
  | "Gateway"
  | "Tuya Multi-function Controller"
  | "videohub"
  | "Virtual Gateway"
  | "diffuser with alexa built-in"
  | "Xiao Zhi Ai Product"
  | "alexa_built_in"
  | "Smart Panel"
  | "Gateway with Alexa"
  | "Leakage Detector"
  | "UPS"
  | "MPPT controller"
  | "Control Valve"
  | "String Inverter"
  | "Micro Inverter"
  | "data concentrator"
  | "Transformer"
  | "EV charger"
  | "Moped Charging Station"
  | "Portable power station"
  | "Smart Electric Meter"
  | "Smart Water Meter"
  | "Switch Module"
  | "Smart gas meter"
  | "smart inverter"
  | "Anemometer"
  | "Frequency converter"
  | "Photovoltaic energy storage"
  | "Relay"
  | "Water Flowmeter"
  | "Industrial gateway"
  | "DTU"
  | "Irrigators"
  | "Water valve controller"
  | "Vibration Sensor"
  | "Current Sensor"
  | "T&H Sensor"
  | "Co Sensor"
  | "Co2 Sensor"
  | "Pm25 Sensor"
  | "PTL Controller"
  | "Pick To Light"
  | "Industrial Signal Lamp"
  | "Button Indicator"
  | "Printer Device"
  | "Solder paste testing equipment"
  | "Mounter Device"
  | "Welding Device"
  | "Furnace temperature tester"
  | "AOI Device"
  | "CNC"
  | "Injection Machine"
  | "DDC"
  | "code reader"
  | "Intelligent material rack"
  | "Automated Guided Vehicle"
  | "Oxygen Sensor"
  | "Pressure Sensor"
  | "IO Module"
  | "Cooling Water Machine"
  | "Fertilizer Machine"
  | "Liquid Level Sensor"
  | "Ph Sensor"
  | "Ec Sensor"
  | "AD Module"
  | "Air Conditioning Controller"
  | "plc"
  | "TV"
  | "Smart Mirror"
  | "Background music"
  | "Projector"
  | "Headphone"
  | "E-calendar"
  | "Signage"
  | "Keyboard"
  | "Glasses"
  | "Microphone"
  | "Smart Console Center"
  | "Voice panel"
  | "Chinese AI voice products"
  | "3D Printer"
  | "Speaker"
  | "Children Ride_on Car"
  | "Portable Printer"
  | "Digital printer"
  | "toy car"
  | "Cloud Frame"
  | "Vibrator Egg"
  | "set-top box"
  | "Electric Bicycle"
  | "Gonfiatore"
  | "Electric wheelchair"
  | "Hoverboards"
  | "Helmet"
  | "Receive payment speaker"
  | "Portable  Wi-Fi"
  | "Payment box"
  | "E-bike battery pack"
  | "Vending cabinet"
  | "Electric Bike Battery"
  | "Outdoor Product"
  | "Indoor and outdoor fusion locator"
  | "ATV"
  | "Scooter"
  | "Tracker"
  | "Intelligent electric vehicle（BLE）"
  | "Burglar Alarm"
  | "Smoke Sensor"
  | "Smart temperature"
  | "Pressure Transmitters"
  | "Property Center Machine"
  | "Community environmental testing"
  | "Inspection device"
  | "Building Automation"
  | "E-cigarette"
  | "dayu"
  | "Intelligent fire fighting"
  | "Water supply and drainage system"
  | "Cold and heat source system"
  | "BA ventilation system"
  | "Combined air-conditioning wind cabinet"
  | "BA Elevator system"
  | "BA Intelligent water meter"
  | "BA Energy consumption system"
  | "BA Fire fighting system"
  | "BA Lighting System"
  | "BA Environmental Monitoring System"
  | "BA Water supply system"
  | "BA Air conditioning system"
  | "BA Facilities and equipment system"
  | "BA Cold and heat source system"
  | "Access Point"
  | "RFID Reader"
  | "Multi Door Game"
  | "Conference Reservation Tablet"
  | "Others (SDK)"
  | "Universal Remote Control"
  | "Smart Parking"
  | "Smart Elevator"
  | "Connector"
  | "Smart Speaker"
  | "Others"
  | "Business license & buildings"
  | "Voice Platform";
