type RssFeed = { category: string; title: string; value: string; url: string };

export function rssFeedCollection(): RssFeed[] {
  return [
    {
      category: "Alle Meldungen",
      title: "Alle Meldungen von tagesschau.de",
      value: "main",
      url: "https://www.tagesschau.de/infoservices/alle-meldungen-100~rss2.xml",
    },
    {
      category: "Alle Meldungen",
      title: "Alle Meldungen der Startseite",
      value: "homepage",
      url: "https://www.tagesschau.de/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Alle Artikel aus dem Ressort Inland",
      value: "inland",
      url: "https://www.tagesschau.de/inland/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Innenpolitik",
      value: "innenpolitik",
      url: "https://www.tagesschau.de/inland/innenpolitik/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Gesellschaft",
      value: "gesellschaft",
      url: "https://www.tagesschau.de/inland/gesellschaft/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Regional",
      value: "regional",
      url: "https://www.tagesschau.de/inland/regional/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Baden-Württemberg",
      value: "baden-wuerttemberg",
      url: "https://www.tagesschau.de/inland/regional/badenwuerttemberg/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Bayern",
      value: "bayern",
      url: "https://www.tagesschau.de/inland/regional/bayern/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Berlin",
      value: "berlin",
      url: "https://www.tagesschau.de/inland/regional/berlin/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Brandenburg",
      value: "brandenburg",
      url: "https://www.tagesschau.de/inland/regional/brandenburg/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Bremen",
      value: "bremen",
      url: "https://www.tagesschau.de/inland/regional/bremen/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Hamburg",
      value: "hamburg",
      url: "https://www.tagesschau.de/inland/regional/hamburg/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Hessen",
      value: "hessen",
      url: "https://www.tagesschau.de/inland/regional/hessen/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Mecklenburg-Vorpommern",
      value: "mecklenburg-vorpommern",
      url: "https://www.tagesschau.de/inland/regional/mecklenburgvorpommern/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Niedersachsen",
      value: "niedersachsen",
      url: "https://www.tagesschau.de/inland/regional/niedersachsen/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Nordrhein-Westfalen",
      value: "nordrhein-westfalen",
      url: "https://www.tagesschau.de/inland/regional/nordrheinwestfalen/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Rheinland-Pfalz",
      value: "rheinland-pfalz",
      url: "https://www.tagesschau.de/inland/regional/rheinlandpfalz/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Saarland",
      value: "saarland",
      url: "https://www.tagesschau.de/inland/regional/saarland/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Sachsen",
      value: "sachsen",
      url: "https://www.tagesschau.de/inland/regional/sachsen/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Sachsen-Anhalt",
      value: "sachsen-anhalt",
      url: "https://www.tagesschau.de/inland/regional/sachsenanhalt/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Schleswig-Holstein",
      value: "schleswig-holstein",
      url: "https://www.tagesschau.de/inland/regional/schleswigholstein/index~rss2.xml",
    },
    {
      category: "Inland",
      title: "Thüringen",
      value: "thueringen",
      url: "https://www.tagesschau.de/inland/regional/thueringen/index~rss2.xml",
    },
    {
      category: "Ausland",
      title: "Alle Artikel aus dem Ressort Ausland",
      value: "ausland",
      url: "https://www.tagesschau.de/ausland/index~rss2.xml",
    },
    {
      category: "Ausland",
      title: "Europa",
      value: "europa",
      url: "https://www.tagesschau.de/ausland/europa/index~rss2.xml",
    },
    {
      category: "Ausland",
      title: "Amerika",
      value: "amerika",
      url: "https://www.tagesschau.de/ausland/amerika/index~rss2.xml",
    },
    {
      category: "Ausland",
      title: "Afrika",
      value: "afrika",
      url: "https://www.tagesschau.de/ausland/afrika/index~rss2.xml",
    },
    {
      category: "Ausland",
      title: "Asien",
      value: "asien",
      url: "https://www.tagesschau.de/ausland/asien/index~rss2.xml",
    },
    {
      category: "Ausland",
      title: "Ozeanien",
      value: "ozeanien",
      url: "https://www.tagesschau.de/ausland/ozeanien/index~rss2.xml",
    },
    {
      category: "Wirtschaft",
      title: "Alle Artikel aus dem Ressort Wirtschaft",
      value: "wirtschaft",
      url: "https://www.tagesschau.de/wirtschaft/index~rss2.xml",
    },
    {
      category: "Wirtschaft",
      title: "Finanzen",
      value: "finanzen",
      url: "https://www.tagesschau.de/wirtschaft/finanzen/index~rss2.xml",
    },
    {
      category: "Wirtschaft",
      title: "Unternehmen",
      value: "unternehmen",
      url: "https://www.tagesschau.de/wirtschaft/unternehmen/index~rss2.xml",
    },
    {
      category: "Wirtschaft",
      title: "Verbraucher",
      value: "verbraucher",
      url: "https://www.tagesschau.de/wirtschaft/verbraucher/index~rss2.xml",
    },
    {
      category: "Wirtschaft",
      title: "Technologien",
      value: "technologien",
      url: "https://www.tagesschau.de/wirtschaft/technologie/index~rss2.xml",
    },
    {
      category: "Wirtschaft",
      title: "Weltwirtschaft",
      value: "weltwirtschaft",
      url: "https://www.tagesschau.de/wirtschaft/weltwirtschaft/index~rss2.xml",
    },
    {
      category: "Wirtschaft",
      title: "Konjunktur",
      value: "konjunktur",
      url: "https://www.tagesschau.de/wirtschaft/konjunktur/index~rss2.xml",
    },
    {
      category: "Wissen",
      title: "Alle Artikel aus dem Ressort Wissen",
      value: "wissen",
      url: "https://www.tagesschau.de/wissen/index~rss2.xml",
    },
    {
      category: "Wissen",
      title: "Gesundheit",
      value: "gesundheit",
      url: "https://www.tagesschau.de/wissen/gesundheit/index~rss2.xml",
    },
    {
      category: "Wissen",
      title: "Klima & Umwelt",
      value: "klima-umwelt",
      url: "https://www.tagesschau.de/wissen/klima/index~rss2.xml",
    },
    {
      category: "Wissen",
      title: "Forschung",
      value: "forschung",
      url: "https://www.tagesschau.de/wissen/forschung/index~rss2.xml",
    },
    {
      category: "Wissen",
      title: "Technologie",
      value: "technologie",
      url: "https://www.tagesschau.de/wissen/technologie/index~rss2.xml",
    },
    {
      category: "Faktenfinder",
      title: "Alle Artikel aus dem Ressort Faktenfinder",
      value: "faktenfinder",
      url: "https://www.tagesschau.de/faktenfinder/index~rss2.xml",
    },
    {
      category: "Investigativ",
      title: "Alle Artikel aus dem Ressort Investigativ",
      value: "investigativ",
      url: "https://www.tagesschau.de/investigativ/index~rss2.xml",
    },
  ];
}
