// Generated by Raycast CLI. Do not edit manually.
// See: https://developers.raycast.com/api-reference/preferences

export {};

declare global {
  namespace Raycast {
    interface Preferences {
      revcastApiBaseUrl?: string;
    }
  }
}
