export const defaultProfilePathChrome = ["Application Support", "Google", "Chrome", "Default", "History"];
export const defaultProfilePathFirefox = ["Application Support", "Firefox", "Profiles"];
export const defaultProfilePathSafari = ["Safari", "History.db"];
export const defaultProfilePathEdge = ["Application Support", "Microsoft Edge", "Default", "History"];
export const defaultProfilePathBrave = ["Application Support", "BraveSoftware", "Brave-Browser", "Default", "History"];
export const defaultProfilePathVivaldi = ["Application Support", "Vivaldi", "Default", "History"];
export const defaultProfilePathArc = ["Application Support", "Arc", "User Data", "Default", "History"];
export const defaultProfilePathOpera = ["Application Support", "com.operasoftware.Opera", "History"];
export const defaultProfilePathIridium = ["Application Support", "Iridium", "Default", "History"];
