import type { Friend } from "./interfaces";

export const MOCK_FRIENDS: Friend[] = [
  {
    xuid: "2535415850813572",
    gamertag: "ShadowReaper#2847",
    modernGamertag: "ShadowReaper2847",
    displayName: "Shadow",
    displayPicRaw: "",
    gamerScore: "42850",
    presenceState: "Online",
    presenceText: "In game",
    lastSeenDateTimeUtc: new Date().toISOString(),
    titlePresences: [
      { titleId: "9NBLGGH5FV99", titleName: "Halo Infinite", titleType: "Game", state: "Active", lastModified: "" },
    ],
    isBroadcasting: true,
  },
  {
    xuid: "2535479872341098",
    gamertag: "DriftKing42",
    modernGamertag: "DriftKing42",
    displayName: "Marcus",
    displayPicRaw: "",
    gamerScore: "67200",
    presenceState: "Online",
    presenceText: "In multiplayer",
    lastSeenDateTimeUtc: new Date().toISOString(),
    titlePresences: [
      { titleId: "9NBLGTH5FV99", titleName: "Forza Horizon 5", titleType: "Game", state: "Active", lastModified: "" },
    ],
    isBroadcasting: false,
  },
  {
    xuid: "2535412345678901",
    gamertag: "CraftMaster",
    modernGamertag: "CraftMaster",
    displayName: "Alex",
    displayPicRaw: "",
    gamerScore: "125600",
    presenceState: "Online",
    presenceText: "In game",
    lastSeenDateTimeUtc: new Date().toISOString(),
    titlePresences: [
      { titleId: "9NBLGJ08FV99", titleName: "Minecraft", titleType: "Game", state: "Active", lastModified: "" },
    ],
    isBroadcasting: true,
  },
  {
    xuid: "2535487654321098",
    gamertag: "SniperElite#991",
    modernGamertag: "SniperElite991",
    displayName: "Jake",
    displayPicRaw: "",
    gamerScore: "28900",
    presenceState: "Away",
    presenceText: "In menu",
    lastSeenDateTimeUtc: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    titlePresences: [
      {
        titleId: "9NBLGJ72FV99",
        titleName: "Call of Duty: Modern Warfare III",
        titleType: "Game",
        state: "Inactive",
        lastModified: "",
      },
    ],
    isBroadcasting: false,
  },
  {
    xuid: "2535498765432109",
    gamertag: "PirateLegend",
    modernGamertag: "PirateLegend",
    displayName: "Sam",
    displayPicRaw: "",
    gamerScore: "54300",
    presenceState: "Away",
    presenceText: "Away",
    lastSeenDateTimeUtc: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    titlePresences: null,
    isBroadcasting: false,
  },
  {
    xuid: "2535411122334455",
    gamertag: "RacingPro",
    modernGamertag: "RacingPro",
    displayName: "Chris",
    displayPicRaw: "",
    gamerScore: "18700",
    presenceState: "Offline",
    presenceText: "Offline",
    lastSeenDateTimeUtc: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    titlePresences: null,
    isBroadcasting: false,
  },
  {
    xuid: "2535422233445566",
    gamertag: "NetflixBinge#2042",
    modernGamertag: "NetflixBinge2042",
    displayName: "Jordan",
    displayPicRaw: "",
    gamerScore: "8920",
    presenceState: "Offline",
    presenceText: "Offline",
    lastSeenDateTimeUtc: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    titlePresences: null,
    isBroadcasting: false,
  },
  {
    xuid: "2535433344556677",
    gamertag: "SeaWolf",
    modernGamertag: "SeaWolf",
    displayName: "Taylor",
    displayPicRaw: "",
    gamerScore: "35600",
    presenceState: "Offline",
    presenceText: "Offline",
    lastSeenDateTimeUtc: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    titlePresences: null,
    isBroadcasting: false,
  },
  {
    xuid: "2535444455667788",
    gamertag: "XboxVeteran",
    modernGamertag: "XboxVeteran",
    displayName: "Mike",
    displayPicRaw: "",
    gamerScore: "234500",
    presenceState: "Offline",
    presenceText: "Offline",
    lastSeenDateTimeUtc: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    titlePresences: null,
    isBroadcasting: false,
  },
];
