import { Clipboard, Toast, closeMainWindow, showHUD, showToast } from "@raycast/api";
import { fetchSvg } from "./fetch";
import { parseSvgContent } from "./parse-svg";

const vueAndSvelteComponentTemplate = async (lang: string, url: string, framework: "Vue" | "Svelte") => {
  const svg = await fetchSvg(url);

  const { templateContent, componentStyle } = parseSvgContent(svg, framework);

  if (framework === "Vue") {
    return `<script setup${lang ? ` lang="${lang}"` : ""}></script>
<template>
 ${templateContent}
</template>
  
    ${componentStyle}
    `;
  } else {
    return `<script${lang ? ` lang="${lang}"` : ""}></script>
 ${templateContent}
  
${componentStyle}
    `;
  }
};

export const generateVueOrSvelteComponentAndCopy = async (lang: string, url: string, framework: "Vue" | "Svelte") => {
  const toast = await showToast({
    style: Toast.Style.Animated,
    title: `Fetching ${framework} component`,
  });

  try {
    const component = await vueAndSvelteComponentTemplate(lang, url, framework);
    await toast.hide();
    Clipboard.copy(component);
    showHUD(`Copied ${framework} component to clipboard`);
    closeMainWindow();
  } catch (error) {
    if (error instanceof Error) {
      await showToast({
        style: Toast.Style.Failure,
        title: `Failed to fetch ${framework.toLowerCase()} component`,
        message: error.message,
      });
    } else {
      await showToast({
        style: Toast.Style.Failure,
        title: `Failed to fetch ${framework.toLowerCase()} component`,
      });
    }
    return;
  }
};

export const generateAngularComponentAndCopy = async (url: string, componentName: string) => {
  const toast = await showToast({
    style: Toast.Style.Animated,
    title: `Fetching Angular component`,
  });

  try {
    const svg = await fetchSvg(url);
    const updatedSvg = svg.replace(/<svg([^>]*)>/, `<svg$1 [attr.width]="size.width" [attr.height]="size.height">`);

    await toast.hide();
    Clipboard.copy(`
  /**
   * -------------------------------------------------------------------------
   * This Angular standalone component was generated by svgl.app
   * 🧩 A beautiful library with SVG logos
   * -------------------------------------------------------------------------
   */
  import { Component, Input } from '@angular/core';
  @Component({
    selector: 'svg-${componentName}',
    standalone: true,
    template: \`
      ${updatedSvg.trim()}
    \`,
  })
  export class ${componentName}Component {
    @Input({ required: true }) size: { width: number; height: number };
  }
  `);
    showHUD(`Copied Angular component to clipboard`);
    closeMainWindow();
  } catch (error) {
    if (error instanceof Error) {
      await showToast({
        style: Toast.Style.Failure,
        title: `Failed to fetch angular component`,
        message: error.message,
      });
    } else {
      await showToast({
        style: Toast.Style.Failure,
        title: `Failed to fetch angular component`,
      });
    }
    return;
  }
};
