export const POPULAR_LANGUAGES = [
  { value: "bash", label: "Bash / Shell" },
  { value: "css", label: "CSS" },
  { value: "dockerfile", label: "Dockerfile" },
  { value: "go", label: "Go" },
  { value: "html", label: "HTML" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JavaScript" },
  { value: "json", label: "JSON" },
  { value: "markdown", label: "Markdown" },
  { value: "php", label: "PHP" },
  { value: "python", label: "Python" },
  { value: "rust", label: "Rust" },
  { value: "sql", label: "SQL" },
  { value: "text", label: "Plain text" },
  { value: "toml", label: "TOML" },
  { value: "typescript", label: "TypeScript" },
  { value: "xml", label: "XML" },
  { value: "yaml", label: "YAML" },
];

export const MORE_LANGUAGES = [
  { value: "c", label: "C" },
  { value: "cpp", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "crystal", label: "Crystal" },
  { value: "dart", label: "Dart" },
  { value: "diff", label: "Diff" },
  { value: "elixir", label: "Elixir" },
  { value: "erb", label: "ERB" },
  { value: "gleam", label: "Gleam" },
  { value: "graphql", label: "GraphQL" },
  { value: "groovy", label: "Groovy" },
  { value: "haskell", label: "Haskell" },
  { value: "http", label: "HTTP" },
  { value: "ini", label: "INI" },
  { value: "jsx", label: "JSX" },
  { value: "julia", label: "Julia" },
  { value: "kotlin", label: "Kotlin" },
  { value: "latex", label: "LaTeX" },
  { value: "lua", label: "Lua" },
  { value: "makefile", label: "Makefile" },
  { value: "nginx", label: "Nginx" },
  { value: "nix", label: "Nix" },
  { value: "objc", label: "Objective-C" },
  { value: "perl", label: "Perl" },
  { value: "powershell", label: "PowerShell" },
  { value: "prisma", label: "Prisma" },
  { value: "proto", label: "Protobuf" },
  { value: "r", label: "R" },
  { value: "regex", label: "Regex" },
  { value: "ruby", label: "Ruby" },
  { value: "scala", label: "Scala" },
  { value: "scss", label: "SCSS" },
  { value: "solidity", label: "Solidity" },
  { value: "swift", label: "Swift" },
  { value: "terraform", label: "Terraform / HCL" },
  { value: "tsx", label: "TSX" },
  { value: "vue", label: "Vue" },
  { value: "wasm", label: "WebAssembly" },
  { value: "zig", label: "Zig" },
];

const ALL_LANGUAGES = [...POPULAR_LANGUAGES, ...MORE_LANGUAGES];

export function getLangLabel(value: string | null | undefined): string {
  if (!value) return "No language";
  return ALL_LANGUAGES.find((l) => l.value === value)?.label ?? value;
}
