// Explicit MLB/NBA aliases from ParlayAPI's team roster. Unknown names stay exact;
// no city-prefix, substring or cross-sport inference is used.
export const TEAM_ALIASES: Record<string, readonly (readonly string[])[]> = {
  baseball_mlb: [
    ["Arizona Diamondbacks", "ARI", "AZ", "Arizona", "Diamondbacks", "Dbacks", "ARI Diamondbacks"],
    ["Atlanta Braves", "ATL", "Atlanta", "Braves", "ATL Braves"],
    ["Baltimore Orioles", "BAL", "Baltimore", "Orioles", "BAL Orioles"],
    ["Boston Red Sox", "BOS", "Boston", "Red Sox", "BOS Red Sox"],
    ["Chicago Cubs", "CHC", "Cubs", "CHI Cubs"],
    ["Chicago White Sox", "CWS", "White Sox", "CHW", "CHI White Sox"],
    ["Cincinnati Reds", "CIN", "Cincinnati", "Reds", "CIN Reds"],
    ["Cleveland Guardians", "CLE", "Cleveland", "Guardians", "CLE Guardians"],
    ["Colorado Rockies", "COL", "Colorado", "Rockies", "COL Rockies"],
    ["Detroit Tigers", "DET", "Detroit", "Tigers", "DET Tigers"],
    ["Houston Astros", "HOU", "Houston", "Astros", "HOU Astros"],
    ["Kansas City Royals", "KC", "Kansas City", "Royals", "KC Royals", "KCR"],
    ["Los Angeles Angels", "LAA", "LA Angels", "Angels"],
    ["Los Angeles Dodgers", "LAD", "LA Dodgers", "Dodgers", "LA"],
    ["Miami Marlins", "MIA", "Miami", "Marlins", "MIA Marlins"],
    ["Milwaukee Brewers", "MIL", "Milwaukee", "Brewers", "MIL Brewers"],
    ["Minnesota Twins", "MIN", "Minnesota", "Twins", "MIN Twins"],
    ["New York Mets", "NYM", "NY Mets", "Mets"],
    ["New York Yankees", "NYY", "NY Yankees", "Yankees"],
    ["Oakland Athletics", "OAK", "Oakland", "Athletics", "ATH", "A's", "As", "The Athletics"],
    ["Philadelphia Phillies", "PHI", "Philadelphia", "Phillies", "PHI Phillies"],
    ["Pittsburgh Pirates", "PIT", "Pittsburgh", "Pirates", "PIT Pirates"],
    ["San Diego Padres", "SD", "San Diego", "Padres", "SD Padres", "SDP"],
    ["San Francisco Giants", "SF", "San Francisco", "Giants", "SF Giants", "SFG"],
    ["Seattle Mariners", "SEA", "Seattle", "Mariners", "SEA Mariners"],
    ["St. Louis Cardinals", "STL", "St Louis", "St. Louis", "Cardinals", "STL Cardinals"],
    ["Tampa Bay Rays", "TB", "Tampa Bay", "Rays", "TB Rays", "TBR"],
    ["Texas Rangers", "TEX", "Texas", "Rangers", "TEX Rangers"],
    ["Toronto Blue Jays", "TOR", "Toronto", "Blue Jays", "TOR Blue Jays"],
    ["Washington Nationals", "WSH", "Washington", "Nationals", "WSH Nationals", "WAS", "WAS Nationals"],
  ],
  basketball_nba: [
    ["Atlanta Hawks", "ATL", "Atlanta", "Hawks", "ATL Hawks"],
    ["Boston Celtics", "BOS", "Boston", "Celtics", "BOS Celtics"],
    ["Brooklyn Nets", "BKN", "Brooklyn", "Nets", "BKN Nets", "BRK"],
    ["Charlotte Hornets", "CHA", "Charlotte", "Hornets", "CHA Hornets", "CHH", "CHO"],
    ["Chicago Bulls", "CHI", "Chicago", "Bulls", "CHI Bulls"],
    ["Cleveland Cavaliers", "CLE", "Cleveland", "Cavaliers", "Cavs", "CLE Cavaliers"],
    ["Dallas Mavericks", "DAL", "Dallas", "Mavericks", "Mavs", "DAL Mavericks"],
    ["Denver Nuggets", "DEN", "Denver", "Nuggets", "DEN Nuggets"],
    ["Detroit Pistons", "DET", "Detroit", "Pistons", "DET Pistons"],
    ["Golden State Warriors", "GSW", "Golden State", "Warriors", "GSW Warriors", "GS", "GS Warriors"],
    ["Houston Rockets", "HOU", "Houston", "Rockets", "HOU Rockets"],
    ["Indiana Pacers", "IND", "Indiana", "Pacers", "IND Pacers"],
    ["LA Clippers", "LAC", "Los Angeles Clippers", "Clippers", "LAC Clippers"],
    ["Los Angeles Lakers", "LAL", "LA Lakers", "Lakers", "LAL Lakers"],
    ["Memphis Grizzlies", "MEM", "Memphis", "Grizzlies", "MEM Grizzlies"],
    ["Miami Heat", "MIA", "Miami", "Heat", "MIA Heat"],
    ["Milwaukee Bucks", "MIL", "Milwaukee", "Bucks", "MIL Bucks"],
    ["Minnesota Timberwolves", "MIN", "Minnesota", "Timberwolves", "T'Wolves", "MIN Timberwolves"],
    ["New Orleans Pelicans", "NOP", "New Orleans", "Pelicans", "NOP Pelicans", "NO"],
    ["New York Knicks", "NYK", "NY Knicks", "Knicks", "NYK Knicks", "NY"],
    ["Oklahoma City Thunder", "OKC", "Oklahoma City", "Thunder", "OKC Thunder"],
    ["Orlando Magic", "ORL", "Orlando", "Magic", "ORL Magic"],
    ["Philadelphia 76ers", "PHI", "Philadelphia", "76ers", "Sixers", "PHI 76ers", "PHL"],
    ["Phoenix Suns", "PHX", "Phoenix", "Suns", "PHX Suns", "PHO", "PHO Suns"],
    ["Portland Trail Blazers", "POR", "Portland", "Trail Blazers", "Blazers", "POR Trail Blazers"],
    ["Sacramento Kings", "SAC", "Sacramento", "Kings", "SAC Kings"],
    ["San Antonio Spurs", "SAS", "San Antonio", "Spurs", "SAS Spurs", "SA", "SA Spurs"],
    ["Toronto Raptors", "TOR", "Toronto", "Raptors", "TOR Raptors"],
    ["Utah Jazz", "UTA", "Utah", "Jazz", "UTA Jazz", "UTH"],
    ["Washington Wizards", "WAS", "Washington", "Wizards", "WAS Wizards", "WSH"],
  ],
};
