import { ShaderParameter } from "./types";

// Common parameters shared by all shaders
// These are added last in the parameter list (higher order numbers)
export const COMMON_PARAMETERS: ShaderParameter[] = [
  {
    id: "showEffect",
    label: "Effect Enabled",
    type: "bool",
    default: true,
    category: "common",
    metadata: true,
    order: 100,
  },
  {
    id: "blackPoint",
    label: "Black Point",
    type: "float",
    default: 0,
    min: 0,
    max: 255,
    step: 5,
    shortcut: { modifiers: [], key: "4" },
    decrementShortcut: { modifiers: [], key: "3" },
    category: "preprocessing",
    metadata: true,
    order: 2.5,
  },
  {
    id: "whitePoint",
    label: "White Point",
    type: "float",
    default: 255,
    min: 0,
    max: 255,
    step: 5,
    shortcut: { modifiers: [], key: "6" },
    decrementShortcut: { modifiers: [], key: "5" },
    category: "preprocessing",
    metadata: true,
    order: 2.6,
  },
  {
    id: "blur",
    label: "Blur",
    type: "float",
    default: 0,
    min: 0,
    max: 30,
    step: 1,
    shortcut: { modifiers: [], key: "8" },
    decrementShortcut: { modifiers: [], key: "7" },
    category: "preprocessing",
    metadata: true,
    order: 200,
  },
  {
    id: "grain",
    label: "Grain",
    type: "float",
    default: 0,
    min: 0,
    max: 1,
    step: 0.1,
    shortcut: { modifiers: [], key: "0" },
    decrementShortcut: { modifiers: [], key: "9" },
    category: "preprocessing",
    metadata: true,
    order: 201,
  },
  {
    id: "gamma",
    label: "Gamma",
    type: "float",
    default: 1.0,
    min: 0.1,
    max: 3.0,
    step: 0.1,
    shortcut: { modifiers: [], key: "x" },
    decrementShortcut: { modifiers: [], key: "z" },
    category: "preprocessing",
    metadata: true,
    order: 202,
  },
];
