import { getSelectedText, Clipboard, showHUD } from "@raycast/api";

const cyrillicToLatin: { [key: string]: string } = {
  а: "a",
  б: "b",
  в: "v",
  г: "h",
  д: "d",
  ж: "ž",
  з: "z",
  и: "i",
  й: "j",
  к: "k",
  л: "ł",
  м: "m",
  н: "n",
  о: "o",
  п: "p",
  р: "r",
  с: "s",
  т: "t",
  у: "u",
  ў: "ŭ",
  ф: "f",
  ц: "c",
  ч: "č",
  ш: "š",
  ы: "y",
  ь: "",
  э: "e",
  "'": "",
};

const softLetters: { [key: string]: string } = {
  /** whistling З */
  збе: "źbie",
  збё: "źbio",
  збі: "źbi",
  збю: "źbiu",
  збя: "źbia",
  зве: "źvie",
  звё: "źvio",
  зві: "źvi",
  звю: "źviu",
  звя: "źvia",
  ззе: "źzie",
  ззё: "źzio",
  ззі: "źzi",
  ззю: "źziu",
  ззя: "źzia",
  зле: "źle",
  злё: "źlo",
  злі: "źli",
  злю: "źlu",
  зля: "źla",
  зме: "źmie",
  змё: "źmio",
  змі: "źmi",
  змю: "źmiu",
  змя: "źmia",
  зне: "źnie",
  знё: "źnio",
  зні: "źni",
  зню: "źniu",
  зня: "źnia",
  зпе: "źpie",
  зпё: "źpio",
  зпі: "źpi",
  зпю: "źpiu",
  зпя: "źpia",
  зсе: "źsie",
  зсё: "źsio",
  зсі: "źsi",
  зсю: "źsiu",
  зся: "źsia",
  зфе: "źfie",
  зфё: "źfio",
  зфі: "źfi",
  зфю: "źfiu",
  зфя: "źfia",
  зце: "źcie",
  зцё: "źcio",
  зці: "źci",
  зцю: "źciu",
  зця: "źcia",

  /** whistling С */
  сбе: "śbie",
  сбё: "śbio",
  сбі: "śbi",
  сбю: "śbiu",
  сбя: "śbia",
  све: "śvie",
  свё: "śvio",
  сві: "śvi",
  свю: "śviu",
  свя: "śvia",
  сзе: "śzie",
  сзё: "śzio",
  сзі: "śzi",
  сзю: "śziu",
  сзя: "śzia",
  сле: "śle",
  слё: "ślo",
  слі: "śli",
  слю: "ślu",
  сля: "śla",
  сме: "śmie",
  смё: "śmio",
  смі: "śmi",
  смю: "śmiu",
  смя: "śmia",
  сне: "śnie",
  снё: "śnio",
  сні: "śni",
  сню: "śniu",
  сня: "śnia",
  спе: "śpie",
  спё: "śpio",
  спі: "śpi",
  спю: "śpiu",
  спя: "śpia",
  ссе: "śsie",
  ссё: "śsio",
  ссі: "śsi",
  ссю: "śsiu",
  сся: "śsia",
  сфе: "śfie",
  сфё: "śfio",
  сфі: "śfi",
  сфю: "śfiu",
  сфя: "śfia",
  сце: "ście",
  сцё: "ścio",
  сці: "ści",
  сцю: "ściu",
  сця: "ścia",

  /** whistling Ц */
  цбе: "ćbie",
  цбё: "ćbio",
  цбі: "ćbi",
  цбю: "ćbiu",
  цбя: "ćbia",
  цве: "ćvie",
  цвё: "ćvio",
  цві: "ćvi",
  цвю: "ćviu",
  цвя: "ćvia",
  цзе: "ćzie",
  цзё: "ćzio",
  цзі: "ćzi",
  цзю: "ćziu",
  цзя: "ćzia",
  цле: "ćle",
  цлё: "ćlo",
  цлі: "ćli",
  цлю: "ćlu",
  цля: "ćla",
  цме: "ćmie",
  цмё: "ćmio",
  цмі: "ćmi",
  цмю: "ćmiu",
  цмя: "ćmia",
  цне: "ćnie",
  цнё: "ćnio",
  цні: "ćni",
  цню: "ćniu",
  цня: "ćnia",
  цпе: "ćpie",
  цпё: "ćpio",
  цпі: "ćpi",
  цпю: "ćpiu",
  цпя: "ćpia",
  цсе: "ćsie",
  цсё: "ćsio",
  цсі: "ćsi",
  цсю: "ćsiu",
  цся: "ćsia",
  цфе: "ćfie",
  цфё: "ćfio",
  цфі: "ćfi",
  цфю: "ćfiu",
  цфя: "ćfia",
  цце: "ćcie",
  ццё: "ćcio",
  цці: "ćci",
  ццю: "ćciu",
  цця: "ćcia",

  /** double Н */
  нне: "ńnie",
  ннё: "ńnio",
  нні: "ńni",
  нню: "ńniu",
  ння: "ńnia",
  Нне: "Ńnie",
  Ннё: "Ńnio",
  Нні: "Ńni",
  Нню: "Ńniu",
  Ння: "Ńnia",

  /** double л */
  лле: "lle",
  ллё: "llo",
  ллі: "lli",
  ллю: "llu",
  лля: "lla",
  Лле: "Lle",
  Ллё: "Llo",
  Ллі: "Lli",
  Ллю: "Llu",
  Лля: "Lla",

  /** soft */
  бь: "b́",
  Бь: "B́",
  вь: "v́",
  Вь: "V́",
  гь: "h́",
  Гь: "H́",
  зь: "ź",
  Зь: "Ź",
  кь: "ḱ",
  Кь: "Ḱ",
  ль: "l",
  Ль: "L",
  мь: "ḿ",
  Мь: "Ḿ",
  нь: "ń",
  Нь: "Ń",
  пь: "ṕ",
  Пь: "Ṕ",
  сь: "ś",
  Сь: "Ś",
  фь: "f́",
  Фь: "F́",
  хь: "ch́",
  Хь: "Ch́",
  ць: "ć",
  Ць: "Ć",

  /** soft L */
  Ле: "Le",
  ле: "le",
  Лё: "Lo",
  лё: "lo",
  Лі: "Lі",
  лі: "li",
  Лю: "Lu",
  лю: "lu",
  Ля: "La",
  ля: "la",

  /** soft E */

  бе: "bie",
  Бе: "Bie",
  ве: "vie",
  Ве: "Vie",
  ге: "hie",
  Ге: "Hie",
  зе: "zie",
  Зе: "Zie",
  ке: "kie",
  Ке: "Kie",
  ме: "mie",
  Ме: "Mie",
  не: "nie",
  Не: "Nie",
  пе: "pie",
  Пе: "Pie",
  се: "sie",
  Се: "Sie",
  фе: "fie",
  Фе: "Fie",
  хе: "chie",
  Хе: "Chie",
  це: "cie",
  Це: "Cie",

  /** soft Ë */
  бё: "bio",
  Бё: "Bio",
  вё: "vio",
  Вё: "Vio",
  гё: "hio",
  Гё: "Hio",
  зё: "zio",
  Зё: "Zio",
  кё: "kio",
  Кё: "Kio",
  мё: "mio",
  Мё: "Mio",
  нё: "nio",
  Нё: "Nio",
  пё: "pio",
  Пё: "Pio",
  сё: "sio",
  Сё: "Sio",
  фё: "fio",
  Фё: "Fio",
  хё: "chio",
  Хё: "Chio",
  цё: "cio",
  Цё: "Cio",

  /** soft Ю */
  бю: "biu",
  Бю: "Biu",
  вю: "viu",
  Вю: "Viu",
  гю: "hiu",
  Гю: "Hiu",
  зю: "ziu",
  Зю: "Ziu",
  кю: "kiu",
  Кю: "Kiu",
  мю: "miu",
  Мю: "Miu",
  ню: "niu",
  Ню: "Niu",
  пю: "piu",
  Пю: "Piu",
  сю: "siu",
  Сю: "Siu",
  фю: "fiu",
  Фю: "Fiu",
  хю: "chiu",
  Хю: "Chiu",
  цю: "ciu",
  Цю: "Ciu",

  /** soft Я */
  бя: "bia",
  Бя: "Bia",
  вя: "via",
  Вя: "Via",
  гя: "hia",
  Гя: "Hia",
  зя: "zia",
  Зя: "Zia",
  кя: "kia",
  Кя: "Kia",
  мя: "mia",
  Мя: "Mia",
  ня: "nia",
  Ня: "Nia",
  пя: "pia",
  Пя: "Pia",
  ся: "sia",
  Ся: "Sia",
  фя: "fia",
  Фя: "Fia",
  хя: "chia",
  Хя: "Chia",
  ця: "cia",
  Ця: "Cia",

  /** double */
  е: "je",
  Е: "Je",
  ё: "jo",
  Ë: "Jo",
  ю: "ju",
  Ю: "Ju",
  я: "ja",
  Я: "Ja",
  х: "ch",
  Х: "Ch",
};

export default async function Command() {
  try {
    let text = await getSelectedText();

    let latinText = "";

    for (const letter in softLetters) {
      text = text.replaceAll(letter, softLetters[letter]);
    }

    for (const char of text) {
      if (char.toLowerCase() in cyrillicToLatin) {
        if (char === char.toUpperCase()) {
          latinText += cyrillicToLatin[char.toLowerCase()].toUpperCase();
        } else {
          latinText += cyrillicToLatin[char.toLowerCase()];
        }
      } else {
        latinText += char;
      }
    }

    await Clipboard.paste(latinText);
  } catch (error) {
    await showHUD("❌ Couldn't get selected text");
  }
}
