name: (Dev) Extensions Build & Publish

on:
  workflow_dispatch:
    inputs:
      paths:
        description: 'Extensions to update (space-separated relative paths for extensions) or ("extensions/**"" to execute on all possible subdirectories)'
        required: true
      command:
        description: 'Ray CLI command to run (build | publish)'
        default: 'build'
        required: true

jobs:
  extensions_build_publish:
    name: Extensions Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Ray CLI
        uses: raycast/github-actions/ray@develop
        with:
          access_token: "${{ secrets.RAYCAST_CLI_ACCESS_TOKEN }}"
          api_url: "${{ secrets.RAYCAST_CLI_API_URL }}"
          command: "${{ inputs.command }}"
          paths: "${{ inputs.paths }}"