name: Generate Docs
on:
  push:
    paths:
      - "docs/**"
    branches: ["main"]
  workflow_dispatch:
  workflow_call:

jobs:
  generate-docs:
    if: github.repository == 'raycast/extensions'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: raycast/github-actions/setup-node@master

      - name: Setup git
        uses: raycast/github-actions/setup-git@master

      - name: Fetch the latest types
        run: |
          configJson=`cat ./docs/.config.json`
          version=`echo $(jq -r '.version' <<< "$configJson")`
          curl -o types.d.ts "https://unpkg.com/@raycast/api@$version/types/index.d.ts"

      - name: Generate the docs
        run: |
          rsync -arv ./docs/ ./generated-docs
          node ./scripts/stitch-docs.js
          npm_config_yes=true npx @raycast/generate-docs --docs=./generated-docs --types=./types.d.ts --output=./generated-docs
          rm types.d.ts

      - name: Deploy the generated docs to the gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.RAYCAST_BOT_API_ACCESS_TOKEN }}
          publish_dir: ./generated-docs

      - name: Notify Failure to Slack
        if: failure()
        uses: edge/simple-slack-notify@master
        with:
          color: "danger"
          text: ":no_entry_sign: ${env.GITHUB_WORKFLOW} has failed"
          fields: |
            [
              { "title": "Action logs:", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"},
              { "title": "Commit:", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/commit/${ env.GITHUB_SHA }"}
            ]
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_CHANNEL_WEBHOOK_URL }}
