export const DESTINATION_PROVIDERS = {
  AWS: "Amazon Web Services (AWS) S3",
  Alibaba: "Alibaba Cloud Object Storage System (OSS) formerly Aliyun",
  ArvanCloud: "Arvan Cloud Object Storage (AOS)",
  Ceph: "Ceph Object Storage",
  ChinaMobile: "China Mobile Ecloud Elastic Object Storage (EOS)",
  Cloudflare: "Cloudflare R2 Storage",
  DigitalOcean: "DigitalOcean Spaces",
  Dreamhost: "Dreamhost DreamObjects",
  GCS: "Google Cloud Storage",
  HuaweiOBS: "Huawei Object Storage Service",
  IBMCOS: "IBM COS S3",
  IDrive: "IDrive e2",
  IONOS: "IONOS Cloud",
  LyveCloud: "Seagate Lyve Cloud",
  Leviia: "Leviia Object Storage",
  Liara: "Liara Object Storage",
  Linode: "Linode Object Storage",
  Magalu: "Magalu Object Storage",
  Minio: "Minio Object Storage",
  Netease: "Netease Object Storage (NOS)",
  Petabox: "Petabox Object Storage",
  RackCorp: "RackCorp Object Storage",
  Rclone: "Rclone S3 Server",
  Scaleway: "Scaleway Object Storage",
  SeaweedFS: "SeaweedFS S3",
  StackPath: "StackPath Object Storage",
  Storj: "Storj (S3 Compatible Gateway)",
  Synology: "Synology C2 Object Storage",
  TencentCOS: "Tencent Cloud Object Storage (COS)",
  Wasabi: "Wasabi Object Storage",
  Qiniu: "Qiniu Object Storage (Kodo)",
  Other: "Any other S3 compatible provider",
};
