import { Icon } from "@raycast/api";
import { AwsService } from "./types";

export const services: AwsService[] = [
  // ── Compute ──
  {
    id: "ec2",
    name: "Amazon EC2",
    consoleUrl: "ec2/home#Instances:",
    aliases: ["ec2"],
    keywords: ["compute", "instance", "server", "virtual machine", "vm"],
    category: "Compute",
    isGlobal: false,
    icon: Icon.Monitor,
  },
  {
    id: "lightsail",
    name: "Amazon Lightsail",
    consoleUrl: "lightsail/home",
    aliases: ["lightsail"],
    keywords: ["vps", "compute", "simple"],
    category: "Compute",
    isGlobal: false,
    icon: Icon.Monitor,
  },
  {
    id: "ec2-autoscaling",
    name: "EC2 Auto Scaling",
    consoleUrl: "ec2/home#AutoScalingGroups:",
    aliases: ["asg", "autoscaling"],
    keywords: ["scaling", "auto scaling group"],
    category: "Compute",
    isGlobal: false,
    icon: Icon.Monitor,
  },
  {
    id: "elastic-beanstalk",
    name: "AWS Elastic Beanstalk",
    consoleUrl: "elasticbeanstalk/home",
    aliases: ["eb", "beanstalk"],
    keywords: ["paas", "deploy", "platform"],
    category: "Compute",
    isGlobal: false,
    icon: Icon.Monitor,
  },
  {
    id: "batch",
    name: "AWS Batch",
    consoleUrl: "batch/home#jobs",
    aliases: ["batch"],
    keywords: ["batch", "job", "compute"],
    category: "Compute",
    isGlobal: false,
    icon: Icon.Monitor,
  },

  // ── Serverless ──
  {
    id: "lambda",
    name: "AWS Lambda",
    consoleUrl: "lambda/home#/functions",
    aliases: ["lambda", "fn"],
    keywords: ["serverless", "function", "faas"],
    category: "Serverless",
    isGlobal: false,
    icon: Icon.Code,
  },
  {
    id: "api-gateway",
    name: "Amazon API Gateway",
    consoleUrl: "apigateway/main/apis",
    aliases: ["apigw", "apigateway"],
    keywords: ["api", "rest", "websocket", "http", "gateway"],
    category: "Serverless",
    isGlobal: false,
    icon: Icon.Code,
  },
  {
    id: "step-functions",
    name: "AWS Step Functions",
    consoleUrl: "states/home#/statemachines",
    aliases: ["sfn", "stepfunctions"],
    keywords: ["workflow", "state machine", "orchestration"],
    category: "Serverless",
    isGlobal: false,
    icon: Icon.Code,
  },
  {
    id: "eventbridge",
    name: "Amazon EventBridge",
    consoleUrl: "events/home#/eventbuses",
    aliases: ["eventbridge", "events"],
    keywords: ["event", "bus", "rule", "scheduler", "cron"],
    category: "Serverless",
    isGlobal: false,
    icon: Icon.Code,
  },
  {
    id: "apprunner",
    name: "AWS App Runner",
    consoleUrl: "apprunner/home#/services",
    aliases: ["apprunner"],
    keywords: ["container", "deploy", "web app"],
    category: "Serverless",
    isGlobal: false,
    icon: Icon.Code,
  },

  // ── Storage ──
  {
    id: "s3",
    name: "Amazon S3",
    consoleUrl: "https://s3.console.aws.amazon.com/s3/buckets",
    aliases: ["s3"],
    keywords: ["storage", "bucket", "object", "file", "blob"],
    category: "Storage",
    isGlobal: true,
    icon: Icon.HardDrive,
  },
  {
    id: "efs",
    name: "Amazon EFS",
    consoleUrl: "efs/home#/file-systems",
    aliases: ["efs"],
    keywords: ["file system", "nfs", "elastic file system"],
    category: "Storage",
    isGlobal: false,
    icon: Icon.HardDrive,
  },
  {
    id: "fsx",
    name: "Amazon FSx",
    consoleUrl: "fsx/home#file-systems",
    aliases: ["fsx"],
    keywords: ["file system", "windows", "lustre", "netapp"],
    category: "Storage",
    isGlobal: false,
    icon: Icon.HardDrive,
  },
  {
    id: "backup",
    name: "AWS Backup",
    consoleUrl: "backup/home#/backupplan",
    aliases: ["backup"],
    keywords: ["backup", "restore", "recovery"],
    category: "Storage",
    isGlobal: false,
    icon: Icon.HardDrive,
  },
  {
    id: "glacier",
    name: "Amazon S3 Glacier",
    consoleUrl: "glacier/home",
    aliases: ["glacier"],
    keywords: ["archive", "cold storage", "vault"],
    category: "Storage",
    isGlobal: false,
    icon: Icon.HardDrive,
  },

  // ── Database ──
  {
    id: "rds",
    name: "Amazon RDS",
    consoleUrl: "rds/home#databases:",
    aliases: ["rds"],
    keywords: [
      "database",
      "mysql",
      "postgres",
      "postgresql",
      "sql",
      "aurora",
      "mariadb",
      "oracle",
    ],
    category: "Database",
    isGlobal: false,
    icon: Icon.List,
  },
  {
    id: "dynamodb",
    name: "Amazon DynamoDB",
    consoleUrl: "dynamodbv2/home#tables",
    aliases: ["dynamo", "ddb"],
    keywords: ["nosql", "database", "table", "key-value"],
    category: "Database",
    isGlobal: false,
    icon: Icon.List,
  },
  {
    id: "elasticache",
    name: "Amazon ElastiCache",
    consoleUrl: "elasticache/home#/redis",
    aliases: ["elasticache", "redis"],
    keywords: ["cache", "redis", "memcached", "in-memory"],
    category: "Database",
    isGlobal: false,
    icon: Icon.List,
  },
  {
    id: "redshift",
    name: "Amazon Redshift",
    consoleUrl: "redshiftv2/home#clusters",
    aliases: ["redshift"],
    keywords: ["data warehouse", "analytics", "sql", "columnar"],
    category: "Database",
    isGlobal: false,
    icon: Icon.List,
  },
  {
    id: "documentdb",
    name: "Amazon DocumentDB",
    consoleUrl: "docdb/home#clusters",
    aliases: ["docdb"],
    keywords: ["mongodb", "document", "database", "nosql"],
    category: "Database",
    isGlobal: false,
    icon: Icon.List,
  },
  {
    id: "neptune",
    name: "Amazon Neptune",
    consoleUrl: "neptune/home#databases",
    aliases: ["neptune"],
    keywords: ["graph", "database", "gremlin", "sparql"],
    category: "Database",
    isGlobal: false,
    icon: Icon.List,
  },
  {
    id: "memorydb",
    name: "Amazon MemoryDB",
    consoleUrl: "memorydb/home#/clusters",
    aliases: ["memorydb"],
    keywords: ["redis", "in-memory", "database"],
    category: "Database",
    isGlobal: false,
    icon: Icon.List,
  },

  // ── Networking ──
  {
    id: "vpc",
    name: "Amazon VPC",
    consoleUrl: "vpcconsole/home#vpcs:",
    aliases: ["vpc"],
    keywords: [
      "network",
      "virtual private cloud",
      "subnet",
      "cidr",
      "security group",
    ],
    category: "Networking",
    isGlobal: false,
    icon: Icon.Globe,
  },
  {
    id: "cloudfront",
    name: "Amazon CloudFront",
    consoleUrl:
      "https://us-east-1.console.aws.amazon.com/cloudfront/v4/home#/distributions",
    aliases: ["cf", "cloudfront"],
    keywords: ["cdn", "distribution", "cache", "edge"],
    category: "Networking",
    isGlobal: true,
    icon: Icon.Globe,
  },
  {
    id: "route53",
    name: "Amazon Route 53",
    consoleUrl:
      "https://us-east-1.console.aws.amazon.com/route53/v2/hostedzones",
    aliases: ["r53", "route53"],
    keywords: ["dns", "domain", "hosted zone", "record"],
    category: "Networking",
    isGlobal: true,
    icon: Icon.Globe,
  },
  {
    id: "elb",
    name: "Elastic Load Balancing",
    consoleUrl: "ec2/home#LoadBalancers:",
    aliases: ["elb", "alb", "nlb"],
    keywords: ["load balancer", "target group", "listener"],
    category: "Networking",
    isGlobal: false,
    icon: Icon.Globe,
  },
  {
    id: "direct-connect",
    name: "AWS Direct Connect",
    consoleUrl: "directconnect/v2/home",
    aliases: ["dx", "directconnect"],
    keywords: ["dedicated network", "private connection"],
    category: "Networking",
    isGlobal: false,
    icon: Icon.Globe,
  },
  {
    id: "transit-gateway",
    name: "AWS Transit Gateway",
    consoleUrl: "vpc/home#TransitGateways:",
    aliases: ["tgw"],
    keywords: ["transit", "gateway", "network hub"],
    category: "Networking",
    isGlobal: false,
    icon: Icon.Globe,
  },
  {
    id: "global-accelerator",
    name: "AWS Global Accelerator",
    consoleUrl:
      "https://us-west-2.console.aws.amazon.com/globalaccelerator/home",
    aliases: ["ga", "globalaccelerator"],
    keywords: ["accelerator", "anycast", "global"],
    category: "Networking",
    isGlobal: true,
    icon: Icon.Globe,
  },

  // ── Security ──
  {
    id: "iam",
    name: "AWS IAM",
    consoleUrl: "https://us-east-1.console.aws.amazon.com/iam/home",
    aliases: ["iam"],
    keywords: [
      "identity",
      "access",
      "role",
      "policy",
      "user",
      "permission",
      "group",
    ],
    category: "Security",
    isGlobal: true,
    icon: Icon.Lock,
  },
  {
    id: "iam-identity-center",
    name: "AWS IAM Identity Center",
    consoleUrl: "singlesignon/home",
    aliases: ["sso", "identity-center"],
    keywords: ["sso", "single sign-on", "identity center", "saml"],
    category: "Security",
    isGlobal: false,
    icon: Icon.Lock,
  },
  {
    id: "cognito",
    name: "Amazon Cognito",
    consoleUrl: "cognito/v2/home",
    aliases: ["cognito"],
    keywords: ["auth", "user pool", "identity pool", "authentication"],
    category: "Security",
    isGlobal: false,
    icon: Icon.Lock,
  },
  {
    id: "secrets-manager",
    name: "AWS Secrets Manager",
    consoleUrl: "secretsmanager/listsecrets",
    aliases: ["secrets", "secretsmanager"],
    keywords: ["secret", "credential", "password", "api key"],
    category: "Security",
    isGlobal: false,
    icon: Icon.Lock,
  },
  {
    id: "kms",
    name: "AWS KMS",
    consoleUrl: "kms/home#/kms/keys",
    aliases: ["kms"],
    keywords: ["key", "encryption", "crypto", "key management"],
    category: "Security",
    isGlobal: false,
    icon: Icon.Lock,
  },
  {
    id: "acm",
    name: "AWS Certificate Manager",
    consoleUrl: "acm/home#/certificates/list",
    aliases: ["acm", "cert"],
    keywords: ["certificate", "ssl", "tls", "https"],
    category: "Security",
    isGlobal: false,
    icon: Icon.Lock,
  },
  {
    id: "waf",
    name: "AWS WAF",
    consoleUrl: "wafv2/homev2/web-acls",
    aliases: ["waf"],
    keywords: ["firewall", "web application firewall", "security", "acl"],
    category: "Security",
    isGlobal: false,
    icon: Icon.Lock,
  },
  {
    id: "guardduty",
    name: "Amazon GuardDuty",
    consoleUrl: "guardduty/home#/findings",
    aliases: ["guardduty"],
    keywords: ["threat", "detection", "security", "intrusion"],
    category: "Security",
    isGlobal: false,
    icon: Icon.Lock,
  },
  {
    id: "security-hub",
    name: "AWS Security Hub",
    consoleUrl: "securityhub/home#/summary",
    aliases: ["securityhub"],
    keywords: ["security", "compliance", "findings", "posture"],
    category: "Security",
    isGlobal: false,
    icon: Icon.Lock,
  },

  // ── Containers ──
  {
    id: "ecs",
    name: "Amazon ECS",
    consoleUrl: "ecs/v2/clusters",
    aliases: ["ecs"],
    keywords: ["container", "docker", "fargate", "cluster", "task", "service"],
    category: "Containers",
    isGlobal: false,
    icon: Icon.Box,
  },
  {
    id: "eks",
    name: "Amazon EKS",
    consoleUrl: "eks/home#/clusters",
    aliases: ["eks", "k8s"],
    keywords: ["kubernetes", "container", "cluster", "pod"],
    category: "Containers",
    isGlobal: false,
    icon: Icon.Box,
  },
  {
    id: "ecr",
    name: "Amazon ECR",
    consoleUrl: "ecr/repositories",
    aliases: ["ecr"],
    keywords: ["container", "registry", "docker", "image", "repository"],
    category: "Containers",
    isGlobal: false,
    icon: Icon.Box,
  },

  // ── Management ──
  {
    id: "cloudformation",
    name: "AWS CloudFormation",
    consoleUrl: "cloudformation/home#/stacks",
    aliases: ["cfn", "cloudformation"],
    keywords: ["stack", "infrastructure", "iac", "template", "deploy"],
    category: "Management",
    isGlobal: false,
    icon: Icon.Cog,
  },
  {
    id: "cloudwatch",
    name: "Amazon CloudWatch",
    consoleUrl: "cloudwatch/home",
    aliases: ["cw", "cloudwatch"],
    keywords: ["monitoring", "metrics", "alarm", "dashboard"],
    category: "Management",
    isGlobal: false,
    icon: Icon.Cog,
  },
  {
    id: "cloudwatch-logs",
    name: "CloudWatch Logs",
    consoleUrl: "cloudwatch/home#logsV2:log-groups",
    aliases: ["cwlogs", "logs"],
    keywords: ["log", "log group", "logging", "cloudwatch"],
    category: "Management",
    isGlobal: false,
    icon: Icon.Cog,
  },
  {
    id: "cloudtrail",
    name: "AWS CloudTrail",
    consoleUrl: "cloudtrailv2/home#/events",
    aliases: ["cloudtrail", "trail"],
    keywords: ["audit", "trail", "event history", "api log"],
    category: "Management",
    isGlobal: false,
    icon: Icon.Cog,
  },
  {
    id: "systems-manager",
    name: "AWS Systems Manager",
    consoleUrl: "systems-manager/home",
    aliases: ["ssm", "systemsmanager"],
    keywords: ["parameter store", "session manager", "patch", "run command"],
    category: "Management",
    isGlobal: false,
    icon: Icon.Cog,
  },
  {
    id: "config",
    name: "AWS Config",
    consoleUrl: "config/home",
    aliases: ["config"],
    keywords: ["compliance", "configuration", "rules", "conformance"],
    category: "Management",
    isGlobal: false,
    icon: Icon.Cog,
  },
  {
    id: "organizations",
    name: "AWS Organizations",
    consoleUrl:
      "https://us-east-1.console.aws.amazon.com/organizations/v2/home",
    aliases: ["org", "organizations"],
    keywords: ["organization", "account", "ou", "scp"],
    category: "Management",
    isGlobal: true,
    icon: Icon.Cog,
  },
  {
    id: "service-catalog",
    name: "AWS Service Catalog",
    consoleUrl: "servicecatalog/home",
    aliases: ["sc"],
    keywords: ["catalog", "portfolio", "product"],
    category: "Management",
    isGlobal: false,
    icon: Icon.Cog,
  },
  {
    id: "trusted-advisor",
    name: "AWS Trusted Advisor",
    consoleUrl: "https://us-east-1.console.aws.amazon.com/trustedadvisor/home",
    aliases: ["ta", "trustedadvisor"],
    keywords: ["advisor", "best practice", "optimization", "recommendation"],
    category: "Management",
    isGlobal: true,
    icon: Icon.Cog,
  },
  {
    id: "health",
    name: "AWS Health Dashboard",
    consoleUrl: "https://health.console.aws.amazon.com/health/home",
    aliases: ["health", "phd"],
    keywords: ["health", "status", "event", "outage"],
    category: "Management",
    isGlobal: true,
    icon: Icon.Cog,
  },

  // ── Developer Tools ──
  {
    id: "codecommit",
    name: "AWS CodeCommit",
    consoleUrl: "codesuite/codecommit/repositories",
    aliases: ["codecommit"],
    keywords: ["git", "repository", "source"],
    category: "Developer Tools",
    isGlobal: false,
    icon: Icon.Terminal,
  },
  {
    id: "codebuild",
    name: "AWS CodeBuild",
    consoleUrl: "codesuite/codebuild/projects",
    aliases: ["codebuild"],
    keywords: ["build", "ci", "compile"],
    category: "Developer Tools",
    isGlobal: false,
    icon: Icon.Terminal,
  },
  {
    id: "codepipeline",
    name: "AWS CodePipeline",
    consoleUrl: "codesuite/codepipeline/pipelines",
    aliases: ["codepipeline", "pipeline"],
    keywords: ["pipeline", "ci", "cd", "deploy", "cicd"],
    category: "Developer Tools",
    isGlobal: false,
    icon: Icon.Terminal,
  },
  {
    id: "codedeploy",
    name: "AWS CodeDeploy",
    consoleUrl: "codesuite/codedeploy/deployments",
    aliases: ["codedeploy"],
    keywords: ["deploy", "deployment", "rolling"],
    category: "Developer Tools",
    isGlobal: false,
    icon: Icon.Terminal,
  },
  {
    id: "cloud9",
    name: "AWS Cloud9",
    consoleUrl: "cloud9control/home",
    aliases: ["cloud9", "c9"],
    keywords: ["ide", "editor", "development"],
    category: "Developer Tools",
    isGlobal: false,
    icon: Icon.Terminal,
  },
  {
    id: "xray",
    name: "AWS X-Ray",
    consoleUrl: "xray/home#/traces",
    aliases: ["xray"],
    keywords: ["trace", "tracing", "distributed", "debug"],
    category: "Developer Tools",
    isGlobal: false,
    icon: Icon.Terminal,
  },

  // ── Analytics ──
  {
    id: "athena",
    name: "Amazon Athena",
    consoleUrl: "athena/home#/query-editor",
    aliases: ["athena"],
    keywords: ["query", "sql", "s3", "analytics", "presto"],
    category: "Analytics",
    isGlobal: false,
    icon: Icon.BarChart,
  },
  {
    id: "kinesis",
    name: "Amazon Kinesis",
    consoleUrl: "kinesis/home#/streams/list",
    aliases: ["kinesis"],
    keywords: ["streaming", "real-time", "data stream"],
    category: "Analytics",
    isGlobal: false,
    icon: Icon.BarChart,
  },
  {
    id: "glue",
    name: "AWS Glue",
    consoleUrl: "glue/home",
    aliases: ["glue"],
    keywords: ["etl", "catalog", "crawler", "data", "spark"],
    category: "Analytics",
    isGlobal: false,
    icon: Icon.BarChart,
  },
  {
    id: "emr",
    name: "Amazon EMR",
    consoleUrl: "emr/home#/clusters",
    aliases: ["emr"],
    keywords: ["hadoop", "spark", "big data", "mapreduce"],
    category: "Analytics",
    isGlobal: false,
    icon: Icon.BarChart,
  },
  {
    id: "opensearch",
    name: "Amazon OpenSearch Service",
    consoleUrl: "aos/home#opensearch/domains",
    aliases: ["opensearch", "elasticsearch", "es"],
    keywords: ["search", "elasticsearch", "kibana", "log analytics"],
    category: "Analytics",
    isGlobal: false,
    icon: Icon.BarChart,
  },
  {
    id: "quicksight",
    name: "Amazon QuickSight",
    consoleUrl: "https://quicksight.aws.amazon.com",
    aliases: ["quicksight", "qs"],
    keywords: ["bi", "dashboard", "visualization", "report"],
    category: "Analytics",
    isGlobal: true,
    icon: Icon.BarChart,
  },
  {
    id: "data-pipeline",
    name: "AWS Data Pipeline",
    consoleUrl: "datapipeline/home",
    aliases: ["datapipeline"],
    keywords: ["pipeline", "data", "etl", "workflow"],
    category: "Analytics",
    isGlobal: false,
    icon: Icon.BarChart,
  },
  {
    id: "lakeformation",
    name: "AWS Lake Formation",
    consoleUrl: "lakeformation/home",
    aliases: ["lakeformation"],
    keywords: ["data lake", "catalog", "governance"],
    category: "Analytics",
    isGlobal: false,
    icon: Icon.BarChart,
  },

  // ── Application Integration ──
  {
    id: "sqs",
    name: "Amazon SQS",
    consoleUrl: "sqs/v3/home#/queues",
    aliases: ["sqs"],
    keywords: ["queue", "message", "messaging", "fifo"],
    category: "Application Integration",
    isGlobal: false,
    icon: Icon.Message,
  },
  {
    id: "sns",
    name: "Amazon SNS",
    consoleUrl: "sns/v3/home#/topics",
    aliases: ["sns"],
    keywords: ["notification", "pub/sub", "topic", "push", "fanout"],
    category: "Application Integration",
    isGlobal: false,
    icon: Icon.Message,
  },
  {
    id: "ses",
    name: "Amazon SES",
    consoleUrl: "ses/home#/account",
    aliases: ["ses"],
    keywords: ["email", "mail", "smtp"],
    category: "Application Integration",
    isGlobal: false,
    icon: Icon.Message,
  },
  {
    id: "mq",
    name: "Amazon MQ",
    consoleUrl: "amazon-mq/home#/brokers",
    aliases: ["mq"],
    keywords: ["message broker", "activemq", "rabbitmq"],
    category: "Application Integration",
    isGlobal: false,
    icon: Icon.Message,
  },

  // ── Machine Learning ──
  {
    id: "sagemaker",
    name: "Amazon SageMaker",
    consoleUrl: "sagemaker/home",
    aliases: ["sagemaker", "sm"],
    keywords: ["ml", "machine learning", "notebook", "training", "model"],
    category: "Machine Learning",
    isGlobal: false,
    icon: Icon.Stars,
  },
  {
    id: "bedrock",
    name: "Amazon Bedrock",
    consoleUrl: "bedrock/home",
    aliases: ["bedrock"],
    keywords: ["ai", "foundation model", "llm", "generative ai", "claude"],
    category: "Machine Learning",
    isGlobal: false,
    icon: Icon.Stars,
  },
  {
    id: "rekognition",
    name: "Amazon Rekognition",
    consoleUrl: "rekognition/home",
    aliases: ["rekognition"],
    keywords: ["image", "video", "vision", "face", "label"],
    category: "Machine Learning",
    isGlobal: false,
    icon: Icon.Stars,
  },
  {
    id: "comprehend",
    name: "Amazon Comprehend",
    consoleUrl: "comprehend/home",
    aliases: ["comprehend"],
    keywords: ["nlp", "text", "sentiment", "entity"],
    category: "Machine Learning",
    isGlobal: false,
    icon: Icon.Stars,
  },

  // ── Cost Management ──
  {
    id: "billing",
    name: "AWS Billing",
    consoleUrl: "https://us-east-1.console.aws.amazon.com/billing/home",
    aliases: ["billing"],
    keywords: ["cost", "bill", "payment", "invoice", "charge"],
    category: "Cost Management",
    isGlobal: true,
    icon: Icon.BankNote,
  },
  {
    id: "cost-explorer",
    name: "AWS Cost Explorer",
    consoleUrl:
      "https://us-east-1.console.aws.amazon.com/cost-management/home#/cost-explorer",
    aliases: ["cost", "ce"],
    keywords: ["cost", "spending", "usage", "explorer", "analysis"],
    category: "Cost Management",
    isGlobal: true,
    icon: Icon.BankNote,
  },
  {
    id: "budgets",
    name: "AWS Budgets",
    consoleUrl:
      "https://us-east-1.console.aws.amazon.com/billing/home#/budgets/overview",
    aliases: ["budgets"],
    keywords: ["budget", "cost", "alert", "threshold"],
    category: "Cost Management",
    isGlobal: true,
    icon: Icon.BankNote,
  },
];
